Framework: Use qs module instead of querystring
Automattic/wp-calypso pull request #23265
Opened 2018-03-13 12:19 UTC by ockham

The [`querystring` module](https://www.npmjs.com/package/querystring)'s functionality overlaps with `qs`, but `querystring` hasn't been updated in 5 years (!) and has a big ['Maintiner Needed'](https://github.com/Gozala/querystring#status-maintiner-needed) _(sic)_ note.

To test:
* This is all over the place, so probably a bit unwieldy to test; maybe just test a few occurrences (e.g. one for `decode`, one for `parse`, one for `stringify`) to gain confidence it works.
* Let's merge, deploy, and stick around in case things go 💥?

2018-03-13 16:29 UTC, samouri commented
Can we restrict this PR to teh dependency swap and leave out changing it to named imports?

2018-03-13 20:37 UTC, ockham commented
> Can we restrict this PR to the dependency swap and leave out changing it to named imports?

@samouri That was the plan, yeah. It includes #23263, but since that has been merged, I'll rebase now.

2018-03-13 20:50 UTC, ockham commented
Rebased.

2018-03-13 22:02 UTC, samouri requested changes
Code LGTM!   Seeing a couple strange things. 

First, there isn't a drop in chunk size like I would expect from removing a dependency:
```
Commit: a056400c4a6a9ec66347cf7506dacfb7a89a1605
Author: ockham
At: 2018-03-13T20:37:43Z
Message: Framework: Remove querystring module
Delta:
chunk                                   stat_size           parsed_size           gzip_size
async-load-post-editor-editor-location       -9 B  (-0.1%)         -5 B  (-0.1%)       +0 B
build                                       -59 B  (-0.0%)        -72 B  (-0.0%)      -14 B  (-0.0%)
manifest                                     +0 B                  +0 B                +4 B  (+0.1%)
post-editor                                 -18 B  (-0.0%)         -5 B  (-0.0%)       +0 B
sharing                                      -9 B  (-0.0%)         -5 B  (-0.0%)       +0 B
woocommerce                                 -45 B  (-0.0%)         -5 B  (-0.0%)       +1 B  (+0.0%)
```

Second, Calypso doesn't boot 🤣:
<img width="1027" alt="screen shot 2018-03-13 at 6 01 36 pm" src="https://user-images.githubusercontent.com/4656974/37372304-aa3d1190-26e8-11e8-8be3-b9bb5e87250b.png">

2018-03-13 22:14 UTC, samouri commented
Turns out `qs` does not contain a decode function. 
I couldn't actually find any documentation on decode in nodejs documentation. According to [the source](https://github.com/Gozala/querystring/blob/master/index.js#L3) decode is an alias for parse so I've pushed a commit that swaps it.

2018-03-13 22:38 UTC, samouri commented
`npm-shrinkwrap.json` shows that the url polyfill internally uses `querystring`. We only use a few helpers from `url` throughout the codebase -- I can replace that in a future PR.

2018-03-13 22:52 UTC, samouri approved these changes

2018-03-13 23:38 UTC, blowery commented
> First, there isn't a drop in chunk size like I would expect from removing a dependency

> npm-shrinkwrap.json shows that the url polyfill internally uses querystring

yup. just that.

I've been mulling options for replacing the url polyfill. 

Ideally, I think we polyfill URL and UrlSearchParams, ideally only in browers that need it. But then we also have to switch to a different API for URL parsing. That might get rid of the need for `qs` or `querysting` altogether. However, we may be inadvertantly using https://github.com/ljharb/qs#parsing-objects in qs and querystring... Which would complicate things.

2018-03-14 08:44 UTC, ockham commented
> Turns out `qs` does not contain a decode function. 
> I couldn't actually find any documentation on decode in nodejs documentation. According to [the source](https://github.com/Gozala/querystring/blob/master/index.js#L3) decode is an alias for parse so I've pushed a commit that swaps it.

Thanks a lot @samouri, and apologies for not doing so myself (had called it a day briefly after rebasing 😬).

2018-03-14 08:45 UTC, ockham commented on .eslintrc.js
> +		'import/no-nodejs-modules': [ 'error', { allow: [ 'url', 'events', 'path' ] } ],
👍

2018-03-14 08:54 UTC, merged