Store: Display warning notice upon failure to retrieve payment methods
Automattic/wp-calypso pull request #23307
Opened 2018-03-14 18:03 UTC by dechov

Shows a notice in the event that the payment method list was not successfully updated:

<img width="690" alt="screen shot 2018-03-14 at 2 01 32 pm" src="https://user-images.githubusercontent.com/1867547/37421659-3ce9f2f4-2790-11e8-8480-13cd14d23837.png">

Inert until warning message string is passed back in https://github.com/Automattic/woocommerce-services/pull/1338

Fixes or helps to address https://github.com/Automattic/woocommerce-services/issues/616

2018-03-14 18:06 UTC, jeffstieler commented
![](https://user-images.githubusercontent.com/1867547/37421659-3ce9f2f4-2790-11e8-8480-13cd14d23837.png)

Where does the error text come form? Can we remove "WooCommerce Services"?

2018-03-14 18:12 UTC, dechov commented
It comes from https://github.com/Automattic/woocommerce-services/pull/1338 — updated the string there :+1:

<img width="692" alt="screen shot 2018-03-14 at 2 12 04 pm" src="https://user-images.githubusercontent.com/1867547/37422542-b79b62f2-2791-11e8-81a0-f5d788af9099.png">

2018-03-14 19:43 UTC, dechov commented
If we want, we can modify this to receive a boolean in the response and just hardcode the notice text in the view.

2018-03-14 21:59 UTC, dechov commented
Now offering a "Retry" action, instead of suggesting page refresh, which is overkill:

<img width="686" alt="screen shot 2018-03-14 at 5 57 19 pm" src="https://user-images.githubusercontent.com/1867547/37433165-36166464-27b1-11e8-9871-a880a7cc1547.png">

2018-03-15 16:50 UTC, jeffstieler requested changes

2018-03-15 16:50 UTC, jeffstieler commented on client/extensions/woocommerce/woocommerce-services/views/label-settings/label-settings.js
> +				<NoticeAction onClick={ this.refetchSettings }>Retry</NoticeAction>
This text needs to be wrapped for translation.

2018-03-19 18:57 UTC, jeffstieler commented
![screen shot 2018-03-19 at 12 51 05 pm](https://user-images.githubusercontent.com/63922/37616130-9a7c07bc-2b74-11e8-9227-d9bd2b51271f.png)

This warning is pretty confusing when shown with credit cards. It doesn't look like fetching the cards failed. (I know this is from cache)

If we fail to refresh our cache, but there are cards in the cache, I don't think we need to show a warning.

However, if we're attempting to fetch cards for a user **and** don't have any cached, we should definitely show this warning.

2018-03-19 19:03 UTC, dechov commented
If we failed to refetch, the user could be left wondering why a card they've added at WP.com isn't showing up here, with no indication of anything having gone wrong on our end and no way to proceed. What do you think?

I do think "fetch" is the wrong term here from the client's perspective though — "update" maybe?

2018-03-19 19:09 UTC, jeffstieler commented
> If we failed to refetch, the user could be left wondering why a card they've added at WP.com isn't showing up here, with no indication of anything having gone wrong on our end and no way to proceed. What do you think?
> 
> I do think "fetch" is the wrong term here from the client's perspective though — "update" maybe?

Good catch! Yeah, I think swapping "update" for "fetch" should suffice here. 👍

2018-03-19 19:36 UTC, dechov commented
@jeffstieler Fixed in https://github.com/Automattic/woocommerce-services/pull/1338/commits/cfd5743c568b0375cd4ac125d9c33db223702153

2018-03-26 23:41 UTC, jeffstieler approved these changes

2018-03-30 17:14 UTC, merged