People: migrate React component to ES6 and remove Jetpack version checks
Automattic/wp-calypso pull request #31453
Opened 2019-03-14 09:53 UTC by jsnajdr

Janitorial opportunity I noticed when reviewing #31153:
- the `People` component can be migrated to ES6, as it doesn't need the `observe( 'peopleLog' )` mixin at all
- legacy Jetpack version checks can be removed, too.

**How to test:**
Click around the "People" section and verify that it works: Simple sites, Jetpack sites, private sites... Pay attention to the navigation toolbar:

<img width="729" alt="Screenshot 2019-03-14 at 10 49 35" src="https://user-images.githubusercontent.com/664258/54347394-3e19a080-4647-11e9-80b3-fe11d14682cc.png">

It should display the "Viewers" tab only on private non-Jetpack sites.

2019-03-14 20:38 UTC, tyxla requested changes
This looks good and tests well overall! 👍 

However, I've noticed a regression: previously, the People sections, we had pollers, so if a change occurs in the background (for example, someone follows your site), the list would autoupdate with the change shortly. 

You can try the following in production and with this branch:

* Load `/people/followers/:site` where `:site` is a WP.com simple site where your current user is admin.
* Login in a separate browser session as another user.
* Follow the `:site` site.
* Wait a little bit.
* Observe the pollers behavior:
  * In production, after some time, the followers list will get updated and the new follower will be added.
  * In this branch, followers will never be updated automatically.

2019-03-20 09:21 UTC, jsnajdr commented
> However, I've noticed a regression: previously, the People sections, we had pollers, so if a change occurs in the background (for example, someone follows your site), the list would autoupdate with the change shortly.

There's no obvious reason why this PR should break the poller. I investigated how this could happen and the poller still works as expected.

But the pollers run only when the document is visible, i.e., you are not on another tab. There is a listener for the `document.visibilitychange` that pauses and resumes all pollers. Maybe that's what happened when you were testing?

2019-03-21 12:06 UTC, tyxla commented
Hm, I'm pretty sure I kept the tab open for at least 20 seconds (albeit with the Network tab open), and I didn't see the change be reflected in the people list. The poller should have resumed and should have hit a new request at least once for that period of time, right?

2019-03-21 14:32 UTC, jsnajdr commented
> The poller should have resumed and should have hit a new request at least once for that period of time, right?

Yes, the poller should have resumed after activating the tab again. Can you please test once again a check if you can still reproduce?

2019-03-22 16:01 UTC, tyxla approved these changes
Seems to be working well! 🚢 Sorry for the red herring 🔴

2019-03-22 16:17 UTC, merged