Fix error with wrong react version
Automattic/wp-calypso pull request #31607
Opened 2019-03-20 21:27 UTC by gravityrail

I was getting a runtime error due to Webpack somehow pulling in the wrong React version.

First of all, I got this warning during the build:

```
WARNING in react
  Multiple versions of react found:
    0.14.9 ./~/jsx-to-string/~/react
    16.2.0 ./packages/i18n-calypso/~/react
    16.8.4 ./~/react
```

No matter - webpack should automatically choose the highest version number to package. Yet somehow this didn't happen, and I got a runtime error like this:

```
Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_1___default.a.useState is not a function
    at useTranslate (use-translate.js:22)
(snip)
```

It turns out that if I look at React.version in a breakpoint in use-translate.js, I get `16.2.0`. Whoops.

This change forces webpack to use the top-level React version always, and assumes that this is the React version we want.

#### Changes proposed in this Pull Request

* Force usage of top-level React in `node_modules`

#### Testing instructions

* Build everything
* Run it
* Looks good?
* Cool

2019-03-21 08:53 UTC, jsnajdr commented
React in `jsx-to-string` is a known issue (@belcherj submitted a PR to the package recently?), but `i18n-calypso` has the correct 16.8.x dependency. Your `node_modules` tree was likely broken and fresh `npm install` should put everything back in order.

It's not necessary to add a webpack alias here. Let's do that only in cases where we have a reason to override what's in `package.json`s.

2019-03-21 11:09 UTC, blowery requested changes
I'd much rather not have the alias. This error is highlighting a deeper problem that we would have otherwise papered over. 

The question is, why and how are you getting an old react under i18n-calypso?

cc @Automattic/luna maybe this is related to using `lerna bootstrap --scope...` ?

2019-03-21 11:26 UTC, simison commented
cc @Automattic/gutenpack

2019-03-21 14:54 UTC, roccotripaldi commented
It looks like the react version [here](https://github.com/Automattic/wp-calypso/blob/master/packages/i18n-calypso/package.json#L31) is lower than the root's dependency.
Should we just bump the version in i18n?

2019-03-21 15:27 UTC, blowery commented
@roccotripaldi what's really odd is that that's still higher than the `16.2.0` that Dan reported. 

I don't think we need to bump i18n-calypso's version. Ideally package versions are as loose as we can support and root versions are exact versions that dictate what we run with.

2019-03-21 16:28 UTC, belcherj commented
I dont think the jsx-to-string react version was causing the issue but here is the PR:  https://github.com/grommet/jsx-to-string/pull/44

2019-03-21 18:34 UTC, gravityrail commented
The issue was fixed by doing a `npm run distclean` (I was just blowing away the root `node_modules` folder). 

The question is, why wasn't the build system picking up that i18n-calypso had incorrect dependency versions?

That seems to be the deeper issue here. This isn't a version number issue either, since the version got bumped yesterday but I was still experiencing the issue on `master` today.

I will close this for now since `npm run distclean` fixes the issue.

2019-03-21 18:34 UTC, closed without merging

2019-03-21 18:42 UTC, simison commented
Should we check for `package.json` updates under `packages/` folder in here?

https://github.com/Automattic/wp-calypso/blob/2eaea21285069c29ff4efe1bb99050dd256a3543/bin/install-if-deps-outdated.js#L20-L41

2019-03-22 15:17 UTC, gravityrail commented
@simison that does seem like the underlying issue here

2019-03-22 15:37 UTC, blowery commented
Opened https://github.com/Automattic/wp-calypso/pull/31683 to make the installer a bit smarter about how to clean things up.

2019-03-22 15:38 UTC, blowery commented
> Should we check for package.json updates under packages/ folder in here?

I don't think we should need to as changes there should have come with a corresponding update to the shrinkwrap in the root, which we already check. Combined with #31683 it may be enough...