Add a starting point for Muriel Typography
Automattic/wp-calypso pull request #32076
Opened 2019-04-05 19:16 UTC by blowery

#### Changes proposed in this Pull Request

* Adds a place to put rules / mixins for muriel-based typography rules

2019-04-09 16:14 UTC, davewhitley requested changes
Looks like a good start aside from my comment.

2019-04-09 16:14 UTC, drw158 commented on packages/muriel-typography/typography.scss
> +  font-weight: regular;
```suggestion
  font-weight: 400;
```

Same for all instances of font-weight: ~regular~ normal;

2019-04-09 23:41 UTC, blowery commented
@drw158 what do you think of the names? Do we want mixins in additions to the utility classes?

2019-04-10 16:38 UTC, drw158 commented
I just cleaned up the CSS and renamed Overline

https://codepen.io/drw158/pen/zbgEqO

```css
.display-large {
  font-weight: 400;
  font-size: 32px;
}

.display-medium {
  font-weight: 400;
  font-size: 24px;
}

.display-small {
  font-weight: 400;
  font-size: 20px;
}

.subtitle {
  font-weight: 600;
  font-size: 16px;
}

.subtitle-small {
  font-weight: 600;
  font-size: 14px;
}

.body {
  font-weight: 400;
  font-size: 16px;
  line-height: 22px;
}

.body-small {
  font-weight: 400;
  font-size: 14px;
  line-height: 20px;
}

.button {
  font-weight: 600;
  font-size: 14px;
}

.caption {
  font-weight: 400;
  font-size: 12px;
  line-height: 16px;
}

.title-small {
  font-weight: 600;
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 1px;
  line-height: 16px;
}```

2019-04-10 16:42 UTC, drw158 commented
I just went ahead and made the changes. I don't think we should do mixins because once ppl start using them, it'll be hard to remove them if we decide they are a problem.

I don't know how I feel about the muriel prefix. If I'm using the class names, I'd rather just write "text-..." or for the css variables, "--color-...". It's less verbose.

2019-04-10 18:04 UTC, blowery commented
LGTM. Want to land it as is and move on?

2019-04-11 11:47 UTC, davewhitley approved these changes
👍

2019-04-11 15:45 UTC, merged

2019-04-11 23:00 UTC, scruffian commented
>  I don't think we should do mixins yet because once ppl start using them, it'll be hard to remove them if we decide they are a problem.

@drw158 could you explain your reasoning here? Why would mixins be a problem?

2019-04-12 19:57 UTC, drw158 commented
Large-scale CSS usage is not my forte, but I think the common argument is that it will introduce a lot of repetition in the CSS. But, I guess that's not a problem with gzip files?

https://csswizardry.com/2016/02/mixins-better-for-performance/

Mostly, I wanted to hold off on mixins until some more framework minded folks could weigh in before we implement something.

2019-04-12 23:21 UTC, scruffian commented
My concern is that we start using these class names in our CSS instead of following the naming conventions we already have. Maybe that's actually more efficient, but if that's the approach we are taking we should be deliberate about it...