Update/async load partner logos
Automattic/wp-calypso pull request #32103
Opened 2019-04-08 13:33 UTC by sgomes

All partner logos were being bundled together, when there will never be more than one (if any) shown. After this change, only the required logo will be loaded.

In addition, the Jetpack header itself only needs to be shown on Jetpack sites, so after this change it too will be lazily loaded, conditionally.

This appears to save ~20KB in JSX-encoded SVG on `/log-in`.
A nice future improvement would be to move the SVG data out of JSX to static SVG files.

#### Changes proposed in this Pull Request

* Lazily load partner logos with `AsyncLoad`.
* Lazily load `JetpackHeader` itself (only needed when site is Jetpack).

#### Testing instructions

* Test correct presence and behaviour of Jetpack header in Jetpack site login
* Test correct behaviour of non-Jetpack site login

2019-04-08 15:07 UTC, blowery commented
Probably need to rebase since https://github.com/Automattic/wp-calypso/pull/32099 landed

2019-04-08 15:11 UTC, sgomes commented
> Probably need to rebase since #32099 landed

I rebased, but there doesn't seem to have been any need for it. That PR only affected the example.

2019-04-08 15:22 UTC, blowery commented
> That PR only affected the example.

My bad, I got confused on what was changing.

2019-04-08 15:24 UTC, sgomes commented
> 
> My bad, I got confused on what was changing.

No worries, rebasing often is a good idea anyway :)

2019-04-10 06:56 UTC, tyxla requested changes
Thanks for this! 👍 

Seems like the default AsyncLoad placeholder doesn't make much sense there:

![](https://cldup.com/8J_Vnb-9Yb.png)

We could fix that by hiding the placeholder with adding `placeholder={ null }` to the new `<AsyncLoad />` instances. I think it would be beneficial for all the instances touched in this PR.

2019-04-10 12:50 UTC, sgomes commented
> Seems like the default AsyncLoad placeholder doesn't make much sense there.
> 
> We could fix that by hiding the placeholder with adding `placeholder={ null }` to the new `<AsyncLoad />` instances. I think it would be beneficial for all the instances touched in this PR.

Great points, @tyxla, thanks! I added a null placeholder to all of the above.

On an unrelated note, I moved to using the full path for all of the `require`s as well, to improve the generated chunk names.

2019-04-10 12:51 UTC, tyxla commented
Thanks @sgomes! I'll take another look shortly.

2019-04-10 13:22 UTC, tyxla approved these changes
Looking and working well 👍 🚢 Thanks!

2019-04-10 14:16 UTC, merged