[WIP] Try i18n scanner
Automattic/wp-calypso pull request #32923
Opened 2019-05-09 10:48 UTC by deBhal

#### Changes proposed in this Pull Request

This PR explores a new i18n tool to help reviewers & developers identify, track, and report translations by "recording" the translated strings and finding the matching translation in glotpress and the matching diff in github.

#### Testing instructions

TBD

2019-05-15 11:26 UTC, deBhal commented
I've added some logic to watch the `gp-record` for cookies, but it's not integrated with the UI, as I'm not sure where it's going to live yet.

I'm leaning towards putting it into the community-translator at the moment, so I've gone with the low-frills object mode and skipped the UI for now, so you'll need to fiddle with the console to see it working, but you can:
1) `document.cookie='gp-record=1;path=/;domain=calypso.localhost';`
2) Navigate around to trigger some translations
3) `document.cookie='gp-record=;path=/;domain=calypso.localhost;expires=Thu, 01 Jan 1970 00:00:01 GMT';`
4) check `window.i18nScanner.loggedTranslations`

2019-05-24 03:45 UTC, akirk commented
After some back and forth whether this could be done as a side-effect of the community translator, we decided to move forward on this in with a light-weight version (because eventually we'll want to retire the jQuery community translator in favor of an always-on #21591).

o Remove UI (starting or stopping happens on translate.wordpress.com)
o Verify it works logged out (since it will be activated through the cookie)
o Ping `query-by-originals` with the strings instead of making the Community Translator do it

2019-06-03 11:38 UTC, deBhal commented on client/layout/community-translator/launcher.jsx
> +	static translationScanner =
I'm not sure entirely sure about this. It's nice to be able to catch all the startup translations, and this does get a lot of them, but I'm not sure if it's early enough to catch all of them.

2019-06-04 08:19 UTC, lsl requested changes
Looks good so far, there are a few things you should probably remove before merging.

Still couldn't get it working on my end, I'll have another go tomorrow a.m. and see if I can get it to kick with fresh eye's.

2019-06-04 08:19 UTC, lsl commented on client/lib/i18n-utils/translation-scanner.js
> +		if ( ! this.installed ) {
move check inside `install()`

2019-06-04 08:19 UTC, lsl commented on client/lib/i18n-utils/translation-scanner.js
> +		if ( ! config.isEnabled( 'i18n/translation-scanner' ) ) {
remove - handled in community translator

2019-06-04 08:19 UTC, lsl commented on client/lib/i18n-utils/translation-scanner.js
> +		if ( ! config.isEnabled( 'i18n/translation-scanner' ) ) {
remove - handled in community translator

2019-06-05 03:36 UTC, lsl commented
Got this working now, works great. - needed manually set cookie for localhost testing.

2019-06-05 03:37 UTC, lsl approved these changes
Approving to unblock, tested and LGTM. Please clean up the extra checks before merging.

2019-06-05 03:59 UTC, deBhal commented on client/lib/i18n-utils/constants.js
> +export const GP_PROJECT = process.env.NODE_ENV === 'production' ? 'wpcom' : 'test';
No. Good catch, looks like this is broken. I'm going to plead "grandfathered" https://github.com/Automattic/wp-calypso/issues/33623 but I think it actually impacts the v2 community translator

2019-06-05 04:21 UTC, deBhal commented on client/lib/i18n-utils/translation-scanner.js
> +		install && this.install();
I'll remove the `install()` in `start()` instead. `install()` puts the translation filter and the cookie watcher into place, and then the cookie watcher is the only thing calling start/stop at the moment so it seems reasonable (for now at least) to assume installation in `start()`

2019-06-05 11:06 UTC, merged