Add space between between toggle and label
Automattic/wp-calypso pull request #33446
Opened 2019-05-30 01:56 UTC by trey

Fixes #33141.

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #

2019-06-03 22:33 UTC, trey commented
How does this look @arunsathiya?

2019-06-04 15:09 UTC, arunsathiya requested changes
Thanks for attempting a patch!

I am afraid this isn't the right approach here. As we can see on the image from your PR description, the label title text and the description are still not aligned.

Plus, the best approach would be to position the title text using CSS changes. You may like to check how the styles for `term-form-dialog__top-level-description` are set, and that might give you a hint. :) 

Here is a similar PR https://github.com/Automattic/wp-calypso/pull/32064. While this was closed, this is likely to help you in the right direction.

Happy to answer any questions you might have.

2019-06-05 12:27 UTC, trey commented
@arunsathiya Thanks! That was very helpful. How does that latest commit look? I've also updated the screenshot.

2019-06-05 13:25 UTC, arunsathiya reviewed
Tested locally, and this looks good now. Thanks! 

Although, I am not familiar with the linter warnings. I am inviting @Automattic/team-calypso for an overall look and any advise on fixing the linter warnings.

2019-06-05 19:10 UTC, blowery commented
Hi @trey, thanks for the PR!

I think there may be a simpler way to fix this. Notice that FormToggle is surrounded by a FormLabel, but FormToggle itself creates a label if its handed children. Instead of fixing the positioning using CSS, you might try removing the FormLabel and passing the text as children to the FormToggle. Like:

```
<FormToggle ...>
  <span ...>
</FormToggle>
```

FormToggle already knows how to lay out the children in a nice way, so we could probably reduce the amount of CSS we need to write in the process.

2019-06-05 19:12 UTC, blowery commented
The linter warnings are from existing warnings in that particular file and should be fixed by https://github.com/Automattic/wp-calypso/pull/33644

2019-06-06 01:32 UTC, trey commented
@blowery wonderful, thank you! That did the trick. I rebased with `master` to get rid of those linter warnings too.

2019-06-25 14:33 UTC, sixhours commented
Looks good to me @trey ! Merging.

2019-06-25 14:33 UTC, merged