Refactor G Suite Dialog to use New User List Component
Automattic/wp-calypso pull request #34133
Opened 2019-06-19 16:29 UTC by cbauerman

#### Changes proposed in this Pull Request

* Completely refactor `GSuiteDialog` as a functional component using the new `GSuiteNewUserList` shared component
* Refactor parents ( `GSuiteUpgrade`, `GSuiteNudge` ) to use new props

#### Testing instructions

TBD

2019-06-20 16:26 UTC, stephanethomas requested changes
> Confirm you have been taking to /domains/add/:domain/google-apps/:siteSlug

We should update that path to mention `gsuite` instead of `google-apps` but this can of course happen in another pull request.

I had a few suggestions but otherwise it works fine ... except for one thing: when clicking the `Skip` button at step #16 the checkout page loads entirely. It seems `page.js` doesn't perform the redirect. It doesn't happen for the `Purchase G Suite` button though.

2019-06-21 17:27 UTC, cbauerman commented
> when clicking the Skip button at step #16 the checkout page loads entirely. It seems page.js doesn't perform the redirect. It doesn't happen for the Purchase G Suite button though

Weird, let's see what we can do to fix that.

2019-06-21 18:02 UTC, cbauerman commented on client/components/upgrades/gsuite/gsuite-dialog/index.jsx
> +const GSuiteDialog = ( {
I forgot it is also not a dialog in Calypso terms 🤦‍♂️ I will get it a better, more descriptive name.

2019-06-21 19:30 UTC, cbauerman commented
> > when clicking the Skip button at step #16 the checkout page loads entirely. It seems page.js doesn't perform the redirect. It doesn't happen for the Purchase G Suite button though
> 
> Weird, let's see what we can do to fix that.

Turns out a leading space will mess up a page redirect 🙂

2019-06-23 13:05 UTC, stephanethomas commented
> Turns out a leading space will mess up a page redirect

Wow, good catch.

2019-06-23 14:06 UTC, stephanethomas approved these changes
I only had a minor comment, otherwise this looks good and works fine.

2019-06-24 17:21 UTC, cbauerman commented on client/components/upgrades/gsuite/gsuite-upsell-card/style.scss
> +	text-indent: -999999px;
😅 Let's take this chance to get rid of it

2019-06-24 18:27 UTC, cbauerman commented on client/components/upgrades/gsuite/gsuite-upsell-card/style.scss
> +	text-indent: -999999px;
actually it definitely still does it's job, we can address it later

2019-06-24 18:28 UTC, merged

2019-06-25 15:21 UTC, Stojdza commented
@cbauerman This PR broke [one e2e test](https://circleci.com/gh/Automattic/wp-calypso/340843) - `Sign up for a site on a business paid plan w/ domain name coming in via /create as business flow in CAD currency @parallel`. It's because selector has [changed](https://github.com/Automattic/wp-calypso/pull/34133/files#diff-c1dfd624e934d3390ddb96b1796310c2R16) in this PR and the full e2e suite wasn't started against PR so you couldn't catch a failure. 

Is it possible to return selector value for the "Skip" button to be `gsuite-upsell-card__checkout-button`? If not, we can work on a workaround to pass these tests.

2019-06-25 17:19 UTC, cbauerman commented
> This PR broke [one e2e test](https://circleci.com/gh/Automattic/wp-calypso/340843) - `Sign up for a site on a business paid plan w/ domain name coming in via /create as business flow in CAD currency @parallel`.

Darn, I'm sorry! Looking at the PR it looked like those selectors were [already](https://github.com/Automattic/wp-calypso/pull/34133/files?file-filters%5B%5D=.js#diff-ed0d30e59fb045357c60a35660c56244) [hit](https://github.com/Automattic/wp-calypso/pull/34133/files?file-filters%5B%5D=.js#diff-c1dfd624e934d3390ddb96b1796310c2) by a search-and-replace I did ( which is really why I should have been able to notice 🤦‍♂ 🤦‍♂ 🤦‍♂  )

@Stojdza since I already changed the selectors is it ok to change them again to be more idiomatic with the rest of the component? #34276 is what I have in mind.