Signup: Differentiate site types configuration for wpcom and jetpack
Automattic/wp-calypso pull request #34199
Opened 2019-06-21 21:04 UTC by creativecoder

#### Changes proposed in this Pull Request

WordPress.com and Jetpack onboarding flows share the site type step. However, in at least one case, a "Purchase required" badge for the "Online store" site type, we need the step to present differently, depending on which context the user is in.

This PR updates the site types configuration to be specific to each context, including displaying the Purchase required badge only in WordPress.com flows.

#### Testing instructions

**WordPress.com**

* Visit `/start` and proceed to the site type step
* See that "Purchase required" displays under the "Online store" site type

**Jetpack**

* Create a site on jurassic.ninja and note the url
* Visit `/jetpack/connect` and enter the site url
* Proceed to the site type step and see that "Purchase required" is not visible

Fixes #33544

2019-06-21 21:07 UTC, creativecoder commented on client/lib/signup/site-type.js
> +export function getSiteTypePropertyValue( key, value, property, siteTypes = getWpcomSiteTypes() ) {
In all the instances I could find, `getSiteTypePropertyValue` is used in the context of wpcom onboarding, so this defaults to using wpcom site types.

2019-06-21 21:08 UTC, creativecoder commented on client/signup/steps/site-type/form.jsx
> -		siteType: PropTypes.string,
`siteType` was declared as a prop but wasn't used anywhere in the component.

2019-06-21 21:11 UTC, creativecoder commented
@Automattic/luna @Automattic/zelda (cc @mattsherman @jonathansadowski ) here's my second attempt at adding the "Purchase required" badge to the site type step, but only for WordPress.com and not Jetpack.

Please evaluate the approach here, since it sets a precedent for displaying this step differently in each context.

2019-06-21 21:55 UTC, shaunandrews approved these changes

2019-06-24 17:23 UTC, jonathansadowski reviewed
Verified that the badge shows up for WPCOM site-types, but not Jetpack Connect site-types. Also double-checked that, since `getAllSiteTypes` is no longer exported, it wasn't used anywhere else.

Looks good to my eyes, but as you mentioned you'd like other reviews, I'll hold-off on approving it.

2019-06-25 03:39 UTC, p-jackson requested changes
> In all the instances I could find, `getSiteTypePropertyValue` is used in the context of wpcom onboarding, so this defaults to using wpcom site types.

`getSiteTypePropertyValue` is called in `<SiteVerticalsSuggestionSearch>`, which is included in `<SiteTopicForm>`, which is included in `<JetpackSiteTopic>` 🙀 This means that the Jetpack site topic field is using suggestions from wpcom plans (which are identical as of right now).

So there's no visible bug, but just worried we're leaving a foot gun for ourselves.

One option is we bite the bullet and remove the default value for the `siteTypes` parameter of `getSiteTypePropertyValue`. We'll need to explicitly pass either Jetpack or wpcom site types wherever it's used. Might get messy.

Another option removing the `purchaseRequired` property from site types and add a flag to `<SiteTypeForm>` instead i.e. `<SiteTypeForm showPurchaseRequiredBadge={true} />`. Although I liked the original solution, now I'm wondering whether it's not modeling the right thing. Is there really something fundamentally different between the Jetpack and wpcom site types? Maybe the badge is just a visual option and not something different at the data layer.

2019-06-25 04:08 UTC, creativecoder commented
> getSiteTypePropertyValue is called in <SiteVerticalsSuggestionSearch>, which is included in <SiteTopicForm>, which is included in <JetpackSiteTopic> 🙀 This means that the Jetpack site topic field is using suggestions from wpcom plans (which are identical as of right now).
>
> So there's no visible bug, but just worried we're leaving a foot gun for ourselves.

🙊 spoke too soon! Thank you for catching this. Agreed that I do not want to lay this kind of trap in the code--it's just asking for a bug.

> One option is we bite the bullet and remove the default value for the siteTypes parameter of getSiteTypePropertyValue. We'll need to explicitly pass either Jetpack or wpcom site types wherever it's used. Might get messy.

I'm leaning toward this option and favoring being explicit. While it might be annoying to import `getWpcomSiteTypes` or `getJetpackSiteTypes` everywhere `getSiteTypePropertyValue` is used, or refactor to use `getWpcomSiteTypeValue` and `getJetpackSiteTypeValue`, having to declare which context you're in helps bring awareness that the flows share components but are different.

> Another option removing the purchaseRequired property from site types and add a flag to <SiteTypeForm> instead i.e. <SiteTypeForm showPurchaseRequiredBadge={true} />

I don't like this road because I've seen where it leads... every small UI variation leads to a new configuration prop and that's it's own kind of mess.

> Is there really something fundamentally different between the Jetpack and wpcom site types?

Maybe a member of @Automattic/luna can weigh in here... I have a sense that as Jetpack flows evolve and we figure out how to actually use site type information for Jetpack onboarding, site types may very well have different display needs.

_And_ I share the feeling that there's a better solution just out of reach.

2019-06-25 04:15 UTC, p-jackson commented
That's fair. It makes sense that Jetpack might end up going after quite different market segments one day. I'm happy with having to explicitly specify what context you're including a component in 👍

2019-06-26 00:05 UTC, ramonjd commented
> We'll need to explicitly pass either Jetpack or wpcom site types wherever it's used. Might get messy.

Seems like the most valid option to me for now too. At least we retain the dependency injection and therefore keep things reasonably testable.

What are folks' thoughts on making this an API endpoint? E.g., `/segments/site-types?context=jetpack&segment=1&{...}` (Doesn't have to be, but I added it as a child route of `segments` at a whim since the site-types are segment-specific)

Does the use case and complexity of logic warrant it (yet)? It seems like this config file has the potential to grow arms and legs and run away on us.

> I have a sense that as Jetpack flows evolve and we figure out how to actually use site type information for Jetpack onboarding

Good point. Let's wait to see what @Automattic/luna says. 

If it turns out that the possibility of Jetpack/WordPress.com divergence is still a 'known unknown' 😵, then my opinion is that, if you can think of a way to optimize the style config, go for it! 

One last thing: if we ever decide to move this config to the backend, all we'd have to do is remove any conditional values, let Jetpack do whatever Jetpack has to do, and we'd still have a neater and dumber frontend for the purposes of WordPress.com signup.

<sub>_/runs away_</sub>

2019-06-26 09:12 UTC, sirreal commented
I'm not very familiar with site types and how all this works.

> Maybe a member of @Automattic/luna can weigh in here... I have a sense that as Jetpack flows evolve and we figure out how to actually use site type information for Jetpack onboarding, site types may very well have different display needs.

@jeffgolenski or @simison might have better input about our roadmap. I would anticipate that we'll find Jetpack sites do have different need. Not because of fundamental _site_ difference (although there are some). Rather, I believe Jetpack users tend to have different needs.

> One option is we bite the bullet and remove the default value for the siteTypes parameter of getSiteTypePropertyValue. We'll need to explicitly pass either Jetpack or wpcom site types wherever it's used.

Getting rid of a default value in favor of explicitness in this case seems good.

2019-06-26 09:23 UTC, sirreal approved these changes
I'll reiterate that I'm not familiar with a lot of this code, so I'm not providing a deep review of the code changes.

I did test Jetpack and Simple site flows and this seems to be working as expected.

2019-06-26 09:35 UTC, simison commented
>I have a sense that as Jetpack flows evolve and we figure out how to actually use site type information for Jetpack onboarding, site types may very well have different display needs.

Yeah, I'm quite sure we'll eventually at least modify the copy for all these vertical/site-type questions or even hide some of the steps completely.

In this specific step we might also introduce different site types for Jetpack compared to .com, so these changes towads more flexibility are useful.

Basically what I'm saying is that we'll change something, just not sure yet what. :-)

Thanks for looping us in!

2019-07-03 18:23 UTC, creativecoder commented
I've refactored this to address the issue @p-jackson found with component `<SiteVerticalsSuggestionSearch>` shared by WordPress.com and Jetpack flows.

This PR has become fairly invasive and now there's a lot more to test.

In the meantime, I'd like to get the small, underlying UI change (showing a "Purchase required" badge for wpcom only) shipped. Here's a PR that does that more simply: https://github.com/Automattic/wp-calypso/pull/34444

2019-07-04 13:43 UTC, simison commented
Please note that we decided to hide these steps for Jetpack, which should simplify any implementation issues here quite a bit. paObgF-k1-p2

2019-07-04 16:11 UTC, creativecoder commented
> Please note that we decided to hide these steps for Jetpack, which should simplify any implementation issues here quite a bit.

Thanks @simison ! I'm going to close this PR in favor of the simpler option (#34444). We can come back to this approach when we're sure we'll need it finer control over the site type steps for Jetpack onboarding.

2019-07-04 16:11 UTC, closed without merging