Rewind credentials: Hint to LastPass not to autocomplete
Automattic/wp-calypso pull request #34376
Opened 2019-07-01 11:39 UTC by seear

#### Changes proposed in this Pull Request

**Before** (note the LastPass icon in username/password inputs)

<img width="1000" alt="Screenshot 2019-07-01 at 12 27 48" src="https://user-images.githubusercontent.com/7767559/60433134-f4f05b00-9bfb-11e9-8412-7fadcae96fd6.png">

**After**

<img width="1015" alt="Screenshot 2019-07-01 at 12 29 49" src="https://user-images.githubusercontent.com/7767559/60433138-f7eb4b80-9bfb-11e9-821e-4d60e3ca0182.png">

Fixes https://github.com/Automattic/jetpack/issues/12893, preventing LastPass from attempting to autocomplete Rewind server credentials using unrelated WordPress.com login info.

Using `data-lpignore="true"` instead of `autocomplete="new-password"`, which needs an option set in LastPass to prevent autocomplete.

#### Testing instructions

* Install LastPass browser extension
* Log into WordPress.com and allow LastPass to save the login
* On this branch, go to http://calypso.localhost:3000/start/rewind-setup/rewind-form-creds
* Ensure LastPass does not attempt to autofill the server username and password

2019-07-01 15:00 UTC, singerb commented
I did a quick google but was unable to find a similar attribute for 1Password.

2019-07-01 15:25 UTC, seear commented
> I did a quick google but was unable to find a similar attribute for 1Password.

For some reason 1Password is not offering to autofill these fields in my browser (Chrome on Mac).

2019-07-01 15:46 UTC, singerb commented
> 
> 
> > I did a quick google but was unable to find a similar attribute for 1Password.
> 
> For some reason 1Password is not offering to autofill these fields in my browser (Chrome on Mac).

Might be smarter than LastPass :-)

2019-07-01 23:10 UTC, MichaelArestad commented
LGTM!

2019-07-01 23:10 UTC, MichaelArestad approved these changes

2019-07-01 23:56 UTC, gravityrail requested changes
I am still seeing Chrome's native autofill prompt

<img width="1680" alt="chrome-autofill" src="https://user-images.githubusercontent.com/51896/60473264-2b8c9c80-9c21-11e9-88ff-894048c2afc7.png">

2019-07-02 00:01 UTC, gravityrail approved these changes
I'm changing my review. Chrome offers auto-*complete* on the field, not autofill. 
Only lastpass was autofilling.

2019-07-02 12:09 UTC, seear commented
Thanks for the reviews!

2019-07-02 12:10 UTC, merged

2019-07-05 06:33 UTC, simison commented
Wondering if Chrome stops giving autocomplete when `autocomplete="new-password` is there?