Replace usage of superagent in i18n-utils.
Automattic/wp-calypso pull request #34712
Opened 2019-07-17 11:47 UTC by sgomes

Some functions used `superagent`, a 3rd party `npm` package, for network requests, and have here been rewritten to use native fetch instead.

This is part of an effort to remove `superagent` from client code altogether, and replace it with native fetch functionality. This will eventually lead to being able to drop that dependency from the client-side bundle, thus improving loading performance.

#### Changes proposed in this Pull Request

* Rewrite several `i18n-utils` functions using `fetch` instead of `superagent`

#### Testing instructions

I am not familiar with this functionality, so I can't provide good testing instructions. Please ensure that `glotpress` and locale switching functionality continue to work correctly with these changes.

If I added you as a reviewer and you're not familiar with this code, sorry about that, I'm just going by GitHub recommendations! If that's the case, please feel free to remove yourself or ignore the PR. And if you can point me to a better reviewer, please do! 🙂

2019-07-24 06:51 UTC, southp requested changes
Thanks for working on this. I'm all for using native APIs, but the locale switching functionality is broken:
![demo-switch-locale-pr](https://user-images.githubusercontent.com/1842898/61771404-5c2bb480-ae22-11e9-9437-6760a03ec4e3.gif)

For comparison, this is how it looks like on current dotcom:
![demo-switch-locale-dotcom](https://user-images.githubusercontent.com/1842898/61771434-6d74c100-ae22-11e9-881a-b4752feb8062.gif)

Once it is fixed, please feel free to ping me for a revisit :)

2019-07-24 09:37 UTC, sgomes commented
> Once it is fixed, please feel free to ping me for a revisit :)

Thank you for the videos, @southp! I was having trouble figuring out how to test this, so they really helped out!

Looks like I'd forgotten to parse the JSON in the response. Should be working now!

2019-07-26 03:32 UTC, southp approved these changes
Thanks for making our codebase cleaner, @sgomes . It works as expected and LGTM 🚢

2019-07-26 08:49 UTC, merged

2019-07-26 08:50 UTC, sgomes commented
Thanks for the review, @southp ! 👍