Avoid multiple concurrent requests for lang file.
Automattic/wp-calypso pull request #35045
Opened 2019-08-01 07:12 UTC by sgomes

In some cases, multiple concurrent requests for the language JSON file could take place. This behaved normally, but resulted in wasted bandwidth for the user.

This issue was likely introduced in #34712. 

#### Changes proposed in this Pull Request

* De-duplicate network requests when loading a language file.

#### Testing instructions

* Log in
* Set your account language to a locale other than US English
* Go to `/log-in`
* Open DevTools and switch to the network tab
* Refresh page

Before, this could produce multiple network requests for e.g. `en-gb-v1.1.json`. Now, it should produce a single one.

2019-08-06 09:26 UTC, southp requested changes
Thanks for the fix. I have tried to diagnose where all the requests come and it looks like quite hard to avoid multiple calls without sacrificing some robustness. Thus I think your approach has hit a nice fair ground :)

While it works, I noticed there is an unhandled Promise rejection:
<img width="1432" alt="螢幕快照 2019-08-06 下午5 06 03" src="https://user-images.githubusercontent.com/1842898/62528264-21d50500-b86f-11e9-91ee-6f8508dccc76.png">

Once it has been resolved, please feel free to ping me for a revisit 🙇🏻

2019-08-06 10:45 UTC, sgomes commented
Excellent catch, @southp ! That error never popped up in my tests, but it's caused by the most infuriating aspect of the `fetch` API: response bodies can only be read once. The code I wrote didn't account for that, and all pending locale changes would try to read the response body and perform the locale change.

I added a simple check for `bodyUsed`, to determine whether a previous locale change had already read the response body (and thus completed, we assume).

2019-08-12 06:32 UTC, southp approved these changes
Thanks for the fix, @sgomes ! It works as expected after retesting. LGTM 🚢

2019-08-12 10:17 UTC, sgomes commented
Thanks again for the review, @southp ! 🙂

2019-08-12 10:17 UTC, merged