Signup: Show domain step in import flows
Automattic/wp-calypso pull request #35175
Opened 2019-08-06 21:13 UTC by creativecoder

#### Changes proposed in this Pull Request

* Show domain step in `import` and `import-onboarding` flows (no longer autocomplete it)
* Autofill domain input with domain or site name from the import url

#### Testing instructions

* TBD

2019-08-07 22:20 UTC, creativecoder commented
Pinging @aidvu , who worked on domains-only auto searching, to make sure I haven't missed anything else related to this functionality.

2019-08-08 09:16 UTC, aidvu commented on client/signup/steps/domains/index.jsx
> +		const suggestedDomain = get( props, 'signupDependencies.suggestedDomain' );
Doing things in the constructor like this is very brittle. Please test all the cases when landing on the domain screen with the `suggestedDomain` set like refreshing the browser, going back and forth through the steps.

2019-08-08 16:18 UTC, andfinally commented on client/lib/importers/utils.ts
> +	if ( parsedHostname && parsedHostname.length > 2 ) {
Just discovered `url.parse` ignores the `www`, so this works fine!

2019-08-08 16:22 UTC, andfinally reviewed
This LGTM, I've tested with a variety of URLs in both logged-out and logged-in states, and using the browser back button and flow back button, and everything works as expected. We're getting eight tests failing - I'm not sure why, for example:

```
"after all" hook - [WPCOM] Calypso Gutenberg Editor: Pages (desktop) Insert a payment button into a page: @parallel
invalid session id

"after all" hook - [WPCOM] Editor: Pages (desktop) Insert a payment button into a page: @parallel @jetpack
invalid session id

"after all" hook - [WPCOM] Editor: Posts (desktop) Insert a payment button: @parallel @jetpack
invalid session id
```

2019-08-08 16:52 UTC, andfinally approved these changes
Tests have now passed, so apart from resolving the conflict I'd say this is good to go!

2019-08-08 20:13 UTC, creativecoder commented on client/lib/signup/step-actions.js
> +	if ( 'import' === lastKnownFlow || 'import-onboarding' === lastKnownFlow ) {
I'm not totally sure either, but in testing adding the plans step to the `import` flow, we saw `flowName` empty in some cases, so it seems more reliable to use `lastKnownFlow`

2019-08-08 20:54 UTC, creativecoder commented
I've rebased this and updated the domain suggestion logic. Now subdomain is used as a suggestion only for specific services, WordPress.com, Blogger, GoDaddy, Squarespace, and Tumblr. Otherwise we suggest the full domain, so the suggestion for `blog.example.com` isn't `blog`, it's `blog.example.com`.

2019-08-08 21:05 UTC, jonathansadowski requested changes
Can we move the `client/lib/importers` code into `client/lib/importer`? I'm attempting to make that change in #35240, as I feel the distinction between the two isn't strong enough to warrant the two confusingly similar names

2019-08-08 21:12 UTC, jonathansadowski requested changes
Edit: False alarm, testing error.

2019-08-08 21:43 UTC, creativecoder commented
> Can we move the client/lib/importers code into client/lib/importer? I'm attempting to make that change in #35240, as I feel the distinction between the two isn't strong enough to warrant the two confusingly similar names

Good call -- updated.

2019-08-08 21:45 UTC, jonathansadowski approved these changes
Works well for me. Thanks for making the change to the library path! Goodjob

2019-08-09 15:11 UTC, merged