Plans: Use Jetpack Colours for Jetpack Sites
Automattic/wp-calypso pull request #35217
Opened 2019-08-08 09:36 UTC by Aurorum

#### Changes proposed in this Pull Request

For Jetpack sites, use Jetpack colours for the Plans table, except for the title of the plan (I feel it looks odd in green, so I used the variable from the Jetpack Connect table)

<img width="1142" alt="Screenshot 2019-08-08 at 10 34 01" src="https://user-images.githubusercontent.com/43215253/62692170-12b59a80-b9c8-11e9-8a17-4c2c51204746.png">

#### Testing instructions

Visit `/plans/` on a Jetpack site and verify that the screenshot looks as above, but it doesn't on a WordPress.com site, or in any other plans tables.

Fixes #30054

2019-08-08 13:22 UTC, drw158 commented
It might be the same color, as you are using but I'd just use the --color-text variable for the black text.

2019-08-08 14:35 UTC, Aurorum commented
Switched! :)

2021-05-11 20:56 UTC, eeeeevon13 requested changes
We are trying to update all of our CTA's to Jetpack Green 50 ( #008A20)
because it passes the contrast test for accessibility.  The one you have used does not. If can update this we're all set.

2021-05-11 20:59 UTC, keoshi commented
This PR is pretty old. Both the tables and their styling have been updated since. Are we sure this even applies to what we have now?

2021-05-12 14:21 UTC, folletto commented
Yup this was a ping from the **Stale Bot**

We don't have that UI anymore, so closing.

2021-05-12 14:21 UTC, closed without merging

2021-05-12 14:22 UTC, folletto commented
Adding also a late apology to Aurorum as this got stuck in the fogs of time.