Checkout: Add phone number field
Automattic/wp-calypso pull request #35750
Opened 2019-08-23 17:04 UTC by sirbrillig

This adds an optional phone number field to the checkout page.

#### Testing instructions

TBD

#### Todo

- [ ] Prevent spinner on load
- [ ] Add tooltip with explanation
- [ ] Make sure data goes to the right place
- [ ] Make sure form looks good for ebanx also

2019-08-26 10:37 UTC, yoavf commented
I can confirm the form looks good and works as expected with ebanx:
<img width="731" alt="Screen Shot 2019-08-26 at 13 33 23" src="https://user-images.githubusercontent.com/844866/63684671-22294600-c806-11e9-833a-6233877c1b6a.png">

2019-08-26 10:58 UTC, yoavf commented
> Make sure data goes to the right place
Just pushed a commit to do that.

Design change: per legal's preference, let's put the explanation under the field (see "Explanation under the field" in the mockup).

2019-08-27 15:14 UTC, yoavf approved these changes
👍 Let's hold on merging until we've run through Legal's todo p2y3YZ-3G7-p2

2019-08-29 13:57 UTC, fditrapani requested changes
It works well for me. I left two comments relating to this:

> I moved it below the field (I called this a "sublabel" because I don't think the pattern exists anywhere yet, but if you know of it somewhere else I can change it).

We have "explainer" text for form fields here: https://wpcalypso.wordpress.com/devdocs/design/form-fields

2019-08-29 20:02 UTC, sirbrillig commented on client/components/credit-card-form-fields/index.jsx
> +		<label className="credit-card-form-fields__sublabel">
Thanks! From your link above I found the component `FormSettingExplanation` which looks quite good!

2019-08-29 21:32 UTC, sirbrillig commented
Moved this into an abtest. @yoavf I didn't know what abtest settings to use so I just copied some from another test, but feel free to change those are let me know.

2019-10-03 19:19 UTC, merged