Devdocs: Remove obsolete endpoints
Automattic/wp-calypso pull request #35810
Opened 2019-08-27 10:08 UTC by ockham

#### Changes proposed in this Pull Request

Remove server-side routes (endpoints) `/devdocs/service/list` and `/devdocs/service/search`, which AFAICS aren't used anywhere.

Somewhat related to #35809, where I hope to replace the `/devdocs/service/content` endpoint with a Webpack loader.

#### Testing instructions

* Go to Devdocs (http://calypso.localhost:3000/devdocs/design/) and give it some thorough testing.
* Verify that the `/devdocs/service/list` and `/devdocs/service/search` routes aren't used anywhere in the code.

2019-08-28 16:16 UTC, sirreal requested changes
This errors at [/devdocs](https://calypso.live/devdocs?branch=remove/obsolete-devdocs-endpoints)

2019-08-29 06:19 UTC, ockham commented
> This errors at [/devdocs](https://calypso.live/devdocs?branch=remove/obsolete-devdocs-endpoints)

Yeah, just noticed that `client/devdocs/main` [uses](https://github.com/Automattic/wp-calypso/blob/54d53e6969ec7126169822e37c61f205d3149f9d/client/devdocs/main.jsx#L15) exprts from the `client/devdocs/services` module...

2020-01-10 16:10 UTC, jsnajdr commented
@ockham The page at `/devdocs` offers search in all the `*.md` documentation files, and that search uses the `/search` endpoint. The `/list` endpoint is used, too, to get the list of "default" results, i.e., documents displayed when there is no search term entered.

I think this PR can be closed 🙂

2020-01-13 12:47 UTC, ockham commented
> @ockham The page at `/devdocs` offers search in all the `*.md` documentation files, and that search uses the `/search` endpoint. The `/list` endpoint is used, too, to get the list of "default" results, i.e., documents displayed when there is no search term entered.
> 
> I think this PR can be closed

Yep, took me a while to realize that :grimacing:

2020-01-13 12:47 UTC, closed without merging