Add a google sheets connection
Automattic/wp-calypso pull request #36928
Opened 2019-10-21 23:07 UTC by scruffian

#### Changes proposed in this Pull Request

* WIP

#### Testing instructions

*

Fixes #

2019-10-22 16:04 UTC, davemart-in approved these changes
Looks good to me visually. I made some updates in https://github.com/Automattic/wp-calypso/commit/4f33745080316dfec2e19940c7fd5486a2af77ca to add the three images and to add both the form and the sheets screenshot.

**Preview**
![Screen Shot 2019-10-22 at 12 02 14 PM-1](https://user-images.githubusercontent.com/5634774/67305965-361abc80-f4c4-11e9-867c-651be7f71bf2.png)

2019-10-31 21:02 UTC, creativecoder requested changes
Now that we've decided on using a site keyring for Google Drive, let's make sure we create and delete site keyrings when a connection is made. See comments for details.

2019-10-31 21:02 UTC, creativecoder commented on client/my-sites/marketing/connections/services/google-drive.js
> +		this.props.deleteStoredKeyringConnection( last( this.props.keyringConnections ) );
See how `google_my_business` site keyrings are disconnected when a user triggers the "Disconnect" action:  https://github.com/Automattic/wp-calypso/blob/add/google-sheets-connection/client/my-sites/marketing/connections/services/google-my-business.js#L71

2019-11-18 12:26 UTC, scruffian commented
Putting this on hold until we have a clearer idea of how to proceed

2019-11-18 12:26 UTC, closed without merging