Remove the domain privacy protection selector in the checkout
Automattic/wp-calypso pull request #37932
Opened 2019-11-25 21:15 UTC by hambai

#### Changes proposed in this Pull Request

* as discussed we want to remove the option to select domain privacy when purchasing a new domain as it is now provided for free and people can always enable/disable the privacy protection at any time after domain purchase. We believe that we can provide privacy for all new domain registrations.

see full discussion here - p99Zz8-Ql-p2

#### Testing instructions

* add a new domain in your cart and proceed to the next step where you enter your contact information - there should be no option to enable/disable privacy

2019-11-26 13:54 UTC, danhauk requested changes
Small copy changes, but otherwise design looks good.

2019-11-26 13:54 UTC, danhauk commented on client/my-sites/checkout/checkout/domain-details-form.jsx
> +								'Protection is included to protect your identity. {{a}}Learn more{{/a}}',
This should be "... is included to help protect your personal information." per @kelliepeterson's comment in the thread at p99Zz8-Ql-p2

2019-11-26 13:54 UTC, danhauk commented on client/my-sites/checkout/checkout/domain-details-form.jsx
> +								'Protection is included for all eligible domains to protect your identity. {{a}}Learn more{{/a}}',
`to protect your identity` -> `to help protect your personal information`

2019-11-26 15:54 UTC, danhauk approved these changes
Looks good from a product perspective. I'll let someone else approve code.

2019-11-26 19:46 UTC, hambai commented
Uh... I have to fix the e2e tests

2019-11-27 12:00 UTC, daledupreez commented
@hambai, if someone has more than one domain without privacy available, the copy is a bit misleading -- it reads: "Privacy Protection is unavailable for this domain."
I am not sure if it's worth splitting this up and/or pluralizing the string. (This is as much a style thing as anything else -- we could also try for a non-plural approach to the text, say "Privacy Protection is not available for any of the domains in your cart."

Other than that, this looks good.

2019-11-28 13:53 UTC, daledupreez reviewed
Rats - forgot to submit this yesterday.

2019-11-29 10:00 UTC, hambai commented on client/lib/cart-values/cart-items.js
> + * @param {object} cart - cart as `CartValue` object
yep :)

2019-11-29 12:25 UTC, daledupreez approved these changes
LGTM!

2019-12-02 15:09 UTC, merged