Update pre-commit phpcs presence logic
Automattic/wp-calypso pull request #38011
Opened 2019-11-27 17:34 UTC by marekhrabe

#### Current situation

I was working on some PHP code in this repo and I have came across a strange failure message coming from the pre-commit hook and preventing the commit:

```
PHP files will not be processed because PHPCS was not found.

Prettier formatting staged file: …/something.js
[error] No parser could be inferred for file: …/something.php
```

I do have PHPCS (but not in PATH yet) so that's obviously the error but I don't think it is being handled well. 

Internally, the pre-commit script is looking at staged files and putting them in buckets based on their file type (scss/php/js). However, this logic was written in a way that PHP files are either processed with phpcs (when present) or with Prettier (when phpcs missing), which is contrary to the initial message the script prints ("…will not be processed…")

Prettier knows nothing about PHP files so it will always fail the check. 

#### Changes proposed in this Pull Request

I have updated the script to always put PHP files into their respective buckets and moved the check for `phpcs` being installed later to the code where it is about to be executed. I believe this is more expected than passing PHP files to Prettier. 

Although it was a side effect, you weren't previously able to pass the check with PHP files staged and no `phpcs` installed. This PR changes it in a way you can pass in such situation while still showing the message in red:

```
PHP files will not be processed because PHPCS was not found.
```

If we want to make the PHPCS check required when dealing with staged PHP, I'm happy to adjust this PR to make it an explicit failure with an appropriate error message instead of the one where Prettier says it has no parser for PHP. 

However, I think we should be good just skipping those, as the message suggests. 

#### Testing instructions

* try committing PHP file on this branch without `phpcs` available in PATH
* it should pass on this branch VS it will fail in master with the Prettier error msg

2019-11-27 17:34 UTC, marekhrabe commented on bin/pre-commit-hook.js
> + * @param   {string} command Command to run. Expects output like `git diff --name-only […]`
a linter asked me for this one so I went with it

2019-12-04 15:46 UTC, obenland commented
@kwight Do you think you'll have time to take a look at this one?

2019-12-04 18:57 UTC, kwight commented
> This PR changes it in a way you can pass in such situation while still showing the message in red

I'm torn on this. I think we should still fail if a dev is trying to update PHP files without PHPCS able to verify; it was the whole point of adding PHPCS support in the first place. If a dev is given the option of going through PHPCS setup, or just committing whatever they have, they will just commit 100% of the time – meaning code quality will degrade, and we might as well remove PHPCS completely to avoid the friction and confusion it has introduced.

So I guess the question is: do we want to require PHPCS for PHP commits? If yes, we'll need to modify this to keep the failure. If no, I'd argue we should just remove everything PHPCS to avoid dev friction.

@obenland I think you felt strongest about PHPCS in the beginning – any opinions?

2019-12-04 19:04 UTC, kwight approved these changes
Works great, definite improvement 🎉

Any changes required from ongoing discussion can be a followup.

2019-12-04 19:09 UTC, obenland requested changes
@kwight is making a good point above.

> If we want to make the PHPCS check required when dealing with staged PHP, I'm happy to adjust this PR to make it an explicit failure with an appropriate error message instead of the one where Prettier says it has no parser for PHP.

Let's do that.

2019-12-05 10:19 UTC, marekhrabe commented
I'm not sure I'm comfortable forcing it when there are no clear instructions for installing the tool. It took me well over an hour and a lot of error message googling :( 

What about adding the condition to force it once #34552 is addressed?

2019-12-05 19:08 UTC, kwight commented
> I'm not sure I'm comfortable forcing it when there are no clear instructions for installing the tool

Yeah, this is because those instructions will vary so much between devs, for [the reasons mentioned](https://github.com/Automattic/wp-calypso/issues/34552#issuecomment-524098652). PHPCS is also a big pain because you don't just have to get it installed, but get all of the rules installed and working properly – it's a pain of a tool 🙃 

@marekhrabe Do what you think is best. None of us are pretending we'll get to any further improvements any time soon (and this PR _is_ an improvement).

2019-12-10 16:25 UTC, obenland approved these changes

2019-12-10 16:36 UTC, getdave commented
In my opinion, if we merge this then we're never going to reinstate this. In reality, this means PHP files can be merged without being checked by PHPCS. This will likely lead to inconsistency or bugs.

I appreciate PHPCS is a pain (I've recently done this) but I don't see it as a reason to disable it. That just opens the flood gates.

I vote that we make it a priority to update the documentation for PHPCS.

2019-12-13 15:32 UTC, marekhrabe commented
Sub-PR adding install instructions and making PHP checks required — #38409

2020-01-08 15:14 UTC, merged