Gutenboarding: Change colors for signup flow for new flow
Automattic/wp-calypso pull request #39045
Opened 2020-01-23 22:10 UTC by jeraldjuice

### Summary

This PR changes the colors in the signup process, only for the Gutenboarding/frankenflow signup flow, to match the [designs](https://github.com/Automattic/wp-calypso/issues/38934).

- Adds a custom class to the body through the `Layout` component when visiting the frankenflow route.
- Overrides existing styles for primary-colored background and inverted text/headers.

<hr>

### Specifics

- This does cause a flash of primary when visiting the `/frankenflow` route, as the `.is-frankenflow` class isn't added to the body until after the route is available in the `Layout` component - slightly later than the `.is-section-signup` class.
     - I imagine we can come back to this later, when we have more flags for Gutenboarding/Frankenflow in the store to hook into, instead of creating an arbitrary one now.
- Not sure the best naming system to use here, can take suggestions for an alternative to `.is-frankenflow`.
- Made the WP logo the brand default - this could also probably be a muted gray instead.

<hr>

### Screenshots

<img width="1433" alt="Screen Shot 2020-01-23 at 4 57 52 PM" src="https://user-images.githubusercontent.com/8892849/73027521-968e0280-3e01-11ea-95d6-b5c310b7ba40.png">
<img width="1429" alt="Screen Shot 2020-01-23 at 4 58 02 PM" src="https://user-images.githubusercontent.com/8892849/73027522-968e0280-3e01-11ea-9a05-6a71ab65b984.png">
<img width="1428" alt="Screen Shot 2020-01-23 at 4 58 12 PM" src="https://user-images.githubusercontent.com/8892849/73027523-968e0280-3e01-11ea-8d2c-d7ec00eccc42.png">

<hr>

### Testing

* Navigate to `/start/frankenflow`.
    * Ensure that the background is a light color, and text on the page is an appropriate contrasting color.
* Navigate to `/start`.
    * Ensure there are no regressions.

<hr>

Part of #38934

2020-01-23 22:12 UTC, jeraldjuice commented on client/layout/index.jsx
> +	const isFrankenflow = startsWith( currentRoute, '/start/frankenflow' );
Hoping to change this later on, when we start adding more frankenflow-specific stuff to the store

2020-01-23 22:13 UTC, jeraldjuice commented on client/signup/style.scss
> +// Background color override for new flow
Kept this separate for now, as opposed to adding a bunch of `:not()`s that we'll have to track down later

2020-01-24 09:26 UTC, razvanpapadopol requested changes
Working well and the flash is barely visible so I think this would be just fine for testing 👍 

I would go one step further and set dark grey color for header text (_Step 1 of 2_) and button (_Back_) visible on second step. Even if the implementation may change in the near future, we should aim to maintain the UI consistent and accessible with each iteration.

2020-01-24 16:28 UTC, jeraldjuice commented
@razvanpapadopol thanks for the feedback! I'll make those changes for this PR 👍

2020-01-28 22:20 UTC, Addison-Stavlo approved these changes
This looks great to me!

And it looks everything @razvanpapadopol mentioned has been taken care of as well.

LGTM!? 😄

2020-01-28 22:30 UTC, jeraldjuice commented
rebased for tests :)

2020-01-28 23:31 UTC, razvanpapadopol approved these changes

2020-01-29 12:44 UTC, merged