Lock down terser version in calypso-build rather than calypso
Automattic/wp-calypso pull request #39448
Opened 2020-02-13 23:23 UTC by roo2

#### Changes proposed in this Pull Request
We just had to pin down the `terser` version to prevent the `n is not a function` module loading error in production code. https://github.com/Automattic/wp-calypso/pull/39367

@jsnajdr raised the point that pinning the version in `wp-calypso/package.json` means that the `calypso-build` library cannot be safely used by e.g. jetpack without jetpack also needing to pin the calypso version. https://github.com/Automattic/wp-calypso/pull/39368#issuecomment-585601732

#### Testing instructions

* Test that the production build does not suffer from the `n is not a function` bug that broke staging the other week.
* Possibly test jetpack builds with this module?

2020-02-14 10:10 UTC, sirreal requested changes
I've added the "Needs Review" label, which triggers e2e tests. That's a good practice for e2e and also to communicate status to other folks.

I'd like to rollback the babel changes in the package lock. Things are unusually fragile there, we should get #39420 landed first.

Otherwise, this seems fine.

2020-02-14 10:10 UTC, sirreal commented on package-lock.json
> +				"@babel/compat-data": {
We'll need to make these package-lock updates eventually, but let's let https://github.com/Automattic/wp-calypso/pull/39420 handle that.

Can you rollback these package lock changes?

2020-02-14 12:23 UTC, sirreal commented
#39420 landed, this will need a rebase.

2020-05-03 23:24 UTC, roo2 commented
This approach should be re-though after the changes to the typescript build and moving to yarn.

2020-05-03 23:24 UTC, closed without merging