Domains: Improve default search experience at /domains/add
Automattic/wp-calypso pull request #39664
Opened 2020-02-25 11:38 UTC by klimeryk

#### Changes proposed in this Pull Request
The default search experience at `/domains/add` is a bit bleak - it just shows two search results, not sure where they came from (behind the scenes they are fetched based on the site slug) and we're not tracking them.

Let's improve that by making the whole search explicit and work just like any other search. Additionally, let's not go back to the "default" suggestions on clearing the search. That does not make sense, IMHO. Let's just preserve the current state of the search and let the user make another search in peace.

Before:
<img width="1074" alt="Screenshot 2020-02-25 at 11 36 24" src="https://user-images.githubusercontent.com/3392497/75244111-158ca700-57c3-11ea-96e3-379a68e0781f.png">

After:
<img width="1067" alt="Screenshot 2020-02-25 at 11 36 15" src="https://user-images.githubusercontent.com/3392497/75244121-1a515b00-57c3-11ea-9e17-bee0a4e73a69.png">

#### Testing instructions
Go to Domains -> Add Domain. Verify that this immediately triggers a search based on the first part of your primary domain (example.com -> example).
Verify that if you empty the search (either by removing the text or clicking the X icon), the state of the component is preserved.

Go to signup and verify that the search works there as previously.

2020-02-25 13:06 UTC, fditrapani approved these changes
I tried this out and it works well. I'm curious if you have any thoughts about how we can measure this change? I'm not saying we need to a/b test it but just to have an idea of what impact it might have?

2020-02-26 12:40 UTC, hambai requested changes
I've tested this and found the following issue - if you click on domains > add and then switch to another site  I'd expect the search query to change and to get results for the new site title but it seems to just hang with placeholders and the old site title visible in the text input.

2020-02-27 13:45 UTC, klimeryk commented
Great catch, @hambai!
Had to do some gymnastics, but I think I fixed the bug 🙇

2020-02-27 14:00 UTC, fditrapani commented
Yeah, good catch @hambai. I just confirmed that the fix worked. Thanks @klimeryk!

2020-03-03 15:45 UTC, klimeryk commented
Hmm, I'm having a hard time figuring out what exactly the e2e tests are complaining about. Definitely seems related to this change, but it's hard to see what assumption was broken with this change. Seems like it's originating from https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-manage-domains-spec.js#L49

@bsessions85, I would really appreciate your e2e expertise here 🙏 

Just to be clear, the changes this PR introduces is that now when entering the Domains -> Add domain screen, the input field is automatically filled with the first part of the site's slug. Whatever is up to the first `.`. For example, `example.wordpress.com` => `example`. `example.com` => `example`. This triggers a full, "normal" domain search. Before this change, the input was empty, but behind the scenes we fetched suggestions based on the same criteria (`example`) and just showed two suggestions on the frontend, in a very simplified way (see the screenshots in the PR's description).

2020-03-06 09:56 UTC, bsessions85 commented
Hi @klimeryk , sorry for the slow response on this one! For some reason this test failed differently the 3rd time which made it so the error you see in CircleCI is not the actual issue it is having. The problem is this line: https://github.com/Automattic/wp-calypso/blob/f0bd9a3748d641a05ea1d673c25a3d83b993a6f2/test/e2e/lib/components/find-a-domain-component.js#L51

The test is going in and waiting to be able to set the search field, but now the field isn't empty so it doesn't know what to do. We can't just remove that line because it is used by other tests where that field is not populated, like in the sign up process. The solution would probably be to check if it has a value and then continue if it does, or better yet, we could update the test with a parameter that lets us know that the value should be set already, so we can test that it is set, and continue if it is as expected.

2020-03-11 11:39 UTC, Stojdza commented
Hey @klimeryk @bsessions85 👋

I've played around a little bit and found two possible solutions for this situation:

1. `executeScript` method: Change [this](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/lib/driver-helper.js#L247) line to:
`return driver.executeScript( "arguments[0].value = '';", element ).then(`

2. Clear field by clicking on `X` if present: After [this](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/lib/components/find-a-domain-component.js#L50) line add the following: 
```
const clearButton = By.css( '.search__close-icon' );
if ( await driverHelper.isEventuallyPresentAndDisplayed( this.driver, clearButton ) ) {
   await driverHelper.clickWhenClickable( this.driver, clearButton );
}
```

NOTE: I tested this locally only by running `Adding a domain to an existing site @parallel` and it passes. Didn't try with other tests or full suite.

2020-03-11 11:52 UTC, klimeryk commented
@Stojdza, thanks for looking! Interestingly, even with just the fixes from @bsessions85 in 4e3204c, the `specs/wp-manage-domains-spec.js` is passing (both locally and on CI). Now, it seems the Gutenberg tests are failing 🤔 I've rebased the patch to see if that helps, but did not seem to have helped. Not sure if that means the workaround (Cmd + A, Backspace) is causing a problem there or if it's unrelated.

2020-03-11 12:57 UTC, Stojdza commented
Ah, I see. These failures are related to change in https://github.com/Automattic/wp-calypso/commit/4e3204c4aa960b88bf7438a3dd14b1405880e017 - `sendKeys` is returning a promise and it's not handled. If you look at any video of failed tests, you will spot in one moment that everything is selected and removed, in a wrong moment :)

2020-03-11 16:08 UTC, bsessions85 commented
@klimeryk I got it working this time, you should be good to go. Thanks @Stojdza for looking as well.

2020-03-12 20:06 UTC, klimeryk commented
Thank you, @bsessions85 and @Stojdza, really appreciate your help, as always! 🙇 🙌

2020-03-12 20:07 UTC, merged