Add/jetpack cloud backuppage indexed backup logs with timezone
Automattic/wp-calypso pull request #40403
Opened 2020-03-24 17:06 UTC by cleacos

#### Changes proposed in this Pull Request

Create an indexed backup base on the backup date (in the correct time zone), so we can easily manage the backups included on each date without calculating it part of the code where we need it. 

At the same time, when we are creating the indexed backup list, we can determine the oldest date of the backup to pass it to DatePicker and limit the browsing to the left on the dates.

#### Testing instructions

- Check the code to see how indexed backups are created
- It works as before

2020-03-24 19:49 UTC, cbauerman approved these changes
This looks good! The lacks of a stop on the oldest date of the picker has been bothering me, so I will be glad to see it fixed! 

As a next step here is the render where the index is generated:
<img width="400" alt="Screen Shot 2020-03-24 at 12 42 15 PM" src="https://user-images.githubusercontent.com/2810519/77469970-27b33280-6dcd-11ea-9a38-6ef1313cd65b.png">
While that is a minuscule amount of time all told, this is a pretty mild case for input ( my site is relatively recent ).

We should look into using memoization, pagination or both in the future.

2020-03-24 20:15 UTC, cleacos commented
Thanks @cbauerman for the review! 

> The lacks of a stop on the oldest date of the picker has been bothering me, so I will be glad to see it fixed!

I'm not sure what you mean here, could you expand on that?

2020-03-24 22:05 UTC, cleacos commented
@cbauerman about the `oldestDateAvailable` is done in this PR https://github.com/Automattic/wp-calypso/pull/40407 ready for review

2020-03-25 00:31 UTC, rcoll requested changes
Parts of this are fantastic additions. I have a concern though. It's best demonstrated with a screenshot:

<img width="1792" alt="Screen Shot 2020-03-24 at 8 24 10 PM" src="https://user-images.githubusercontent.com/5528445/77489216-da0aea00-6e0d-11ea-945e-5cb07099bf95.png">

This _looks_ fine, except the date is now wrong. This backup was actually performed on March 24, at 11:42AM (local time, EST). I have confirmed that time, and that the site's timezone is set to New York, EST.

I'm not sure where the disconnect is introduced, but this is a problem. Perhaps this problem arises when a date has multiple full backups. Perhaps it's something else.

Furthermore:

![Screen Shot 2020-03-24 at 8 31 45 PM](https://user-images.githubusercontent.com/5528445/77489448-85b43a00-6e0e-11ea-9291-02fc1b6c1881.png)

This backup literally does not exist. There simply isn't a more recent backup than the one in the first screenshot. It's possible that the indexing just isn't aligned properly.

Here are a few important things to keep in mind, and possibly some back-information on why I constructed this the way I did initially:
- Dates can (and fairly frequently DO, for a variety of reasons) have multiple backups.
- The initial construct of this part of the app accounted for that by strategically selecting the latest backup performed on any given day.
- I'll add more ideas in person, let's chat tomorrow.

Overall, very nice work, but let's work together to double check everything before we merge it.

2020-03-25 01:09 UTC, cleacos commented
Hey, @rcoll thank you very much for the review.

In this PR we've only touched the BackupsPage component to add a function to create an indexed backup list based on the date of the backups, but nothing else. We've not touched the DailyBackupStatus yet. 

In my local development, I have a code prepared that will update the DailyBackupStatus component to works properly with the site time zone. I'll let you know when it's ready to check and review this part. Is it okay for you?

LGTM this PR?

2020-03-28 22:19 UTC, cleacos commented
All the changes are in this PR https://github.com/Automattic/wp-calypso/pull/40496

2020-03-28 22:20 UTC, closed without merging