Jetpack Cloud: Display product-based DocumentHead title
Automattic/wp-calypso pull request #41289
Opened 2020-04-20 16:09 UTC by rcoll

#### Changes proposed in this Pull Request

* Instead of simply "Backups", the page header should specify "Real-time Backups" or "Daily Backups".

#### Testing instructions

Load up the main Backups page and ensure that either "Real-time Backups" or "Daily Backups" appears at the top of the page. This should reflect the actual product you have purchased for the site.

2020-04-23 11:12 UTC, enejb commented
I tested this and it shows the "Daily vs Realtime" backups as expected. 
It does however display the wrong label for a fraction of a second.

Should we display nothing instead or Just Backup? While we figure out what kind of capabilities the site has? 

I think that can probably addressed in a different PR.

2020-04-30 13:26 UTC, rcoll commented
> I tested this and it shows the "Daily vs Realtime" backups as expected.
> It does however display the wrong label for a fraction of a second.
> 
> Should we display nothing instead or Just Backup? While we figure out what kind of capabilities the site has?
> 
> I think that can probably addressed in a different PR.

Hmmm, good point. I did think about that. Not sure how to track the status of the capabilities request, perhaps you can help there?

2020-05-06 19:48 UTC, eeeeevon13 approved these changes

2020-05-06 23:44 UTC, cbauerman approved these changes
Really can't see a way this simpler. LGTM!

2020-05-07 10:27 UTC, cleacos requested changes
@eeeeevon13 @rcoll I think we have a collision with this task 1142395350490785-as-1173475308570809 with this description:

> Currently we see Backups in the page heading, and "status" selected in the nav. There should never be a discrepancy between the two.  
We want to change the page "Status" to read "Latest Backups". Status does not reflect what this page is. 

![image](https://user-images.githubusercontent.com/9832440/81283980-6a675c00-9055-11ea-9ee1-eb00b1f78d6e.png)

![image](https://user-images.githubusercontent.com/9832440/81284006-72bf9700-9055-11ea-804b-d0f5afa2a44c.png)


And this task was done recently and it's in production

2020-06-01 18:39 UTC, mattgawarecki commented
Is this still an active PR?

2020-06-03 10:33 UTC, cleacos commented
@mattgawarecki Nope. We have this PR https://github.com/Automattic/wp-calypso/pull/42402, that it's also in standby. Thanks. Closing this

2020-06-03 10:33 UTC, closed without merging