Jetpack Cloud: Backup status design tweaks
Automattic/wp-calypso pull request #41680
Opened 2020-04-30 15:33 UTC by rcoll

#### Changes proposed in this Pull Request

* Move `BackupDelta` component into the `DailyBackupStatus` component for daily backups. This makes it much easier to enclose it in the same `Card` element, per the designs. BackupDelta remains outside `DailyBackupStatus` for real-time backups. I realize this is not ideal, let's fix later :-)
* A few other design tweaks, per notes in 1142395350490785-as-1173118334902067

#### Testing instructions

1. Strap your seatbelt. It's going to get bumpy.
2. For a Real-time site: Check all types of backup statuses (pending, complete, error). Make sure that what is displayed is correct per the linked task. Do this for both mobile and desktop breakpoints.
3. For a Daily Backup site: Check all types of backup statuses (pending, complete, error). Make sure that what is displayed is correct per the linked task. Do this for both mobile and desktop breakpoints.

Fixes 1142395350490785-as-1173118334902067

2020-04-30 17:27 UTC, eeeeevon13 commented
Getting close!
Couple of small things

1. Time of backup should be page heading font (36px bold)
2. Got some spacing issues, bulleted them out in the image
3. Icon should be backups complete icon
4. There should be a line under "changes in this backup"  (sub heading
![backups-top](https://user-images.githubusercontent.com/49159284/80740624-f7526880-8add-11ea-8ffc-bd7cdd208ef9.png)
 style)

2020-05-01 11:31 UTC, cleacos requested changes
I think that the 'Latest' word only should have been removed for the desktop views and keep it for the mobile views.

- From a functional point of view, it works as expected. 
- The expected design doesn't match with the screenshot of the task linked as @eeeeevon13  commented.

2020-05-06 17:39 UTC, cleacos requested changes
I think that the 'Latest' word only should have been removed for the desktop views and keep it for the mobile views.

Mobile view of this PR:
![image](https://user-images.githubusercontent.com/9832440/81209741-d2239580-8fc8-11ea-8d76-fa875f948f62.png)

2020-05-14 19:58 UTC, cleacos commented
Most of the issues were solved

2020-05-14 19:58 UTC, closed without merging