Modularise form state
Automattic/wp-calypso pull request #41684
Opened 2020-04-30 16:16 UTC by sgomes

This PR is one of many working on modularising state in Calypso. This one is a bit special, however, as it as it's modularising what's essentially third-party state, or at least state that's managed by `redux-form`.

There are a few parts of Calypso making use of this (somewhat large) library, such as a `tinymce` plugin and the `zoninator` extension. While they aren't migrated away from `redux-form`, we can at least ensure that its state is modularised, so that the library doesn't need to be loaded on boot.

For mode details on state modularisation, see #39261 and p4TIVU-9lM-p2.

#### Changes proposed in this Pull Request

* Extract form state into its own directory structure
* Add README discouraging use
* Modularise form state

#### Testing instructions

Ensure that the functionality making use of `redux-form` continues to work correctly, by e.g. testing the simple payments plugin for `tinymce` or the `zoninator` extension.

2020-05-05 09:39 UTC, sgomes commented
Looks like this PR saves ~16KB (4KB gzipped) on the `entry-main` critical path! 🎉

2020-05-14 15:57 UTC, sgomes commented
Hey folks! Any chance of a review on this PR?

2020-05-28 13:31 UTC, sgomes commented
Anyone in @Automattic/team-calypso able to take a look at this PR?

2020-06-04 12:27 UTC, lynnbgriffith requested changes
I notice some `no-restricted-imports` noise in `lint-and-translate`.  Worth cleaning up?

2020-06-04 12:30 UTC, sgomes commented
> I notice some `no-restricted-imports` noise in `lint-and-translate`. Worth cleaning up?

The linting errors are expected, since I'm modifying the root reducer, which uses linting errors to point out unmodularised state in an attempt to prevent more of it from being created.

Is there a better alternative you'd prefer?

2020-06-04 12:44 UTC, lynnbgriffith approved these changes
Just saw your note to that effect on #41932.  Makes sense.  Will keep that in mind for these PRs going forward.  This one is looking good to me.  Nice savings on this one!  🚀

2020-06-04 13:38 UTC, merged

2020-06-04 13:39 UTC, sgomes commented
No worries, @griffbrad! I should have gone back and added the note to all PRs 🙂 

Thank you for the review!