Gutenboarding: Fixes for cursor position in acquire intent contenteditable elements
Automattic/wp-calypso pull request #42251
Opened 2020-05-15 07:23 UTC by andrewserong

This PR attempts to fix a couple of cursor position issues in the acquire intent step of Gutenboarding. The main fixes are:

* When a user moves the cursor to the beginning of the vertical they've typed in, the cursor should not drop down lower unexpectedly (#41976).
* When a user clicks label text, it should move the cursor to the end of the associated editable field, just like a `label` on an `input` element.
* When a user gets to the Design selection step and clicks back, the cursor should be at the end of the site title.

This is kind of a speculative PR, as it introduces extra control over the cursor position. Is this something we want to do? On balance, is this change more valuable than the risk of messing around with the cursor position when someone clicks things?

#### Changes proposed in this Pull Request

* Give the whitespace a height and alignment consistent with the vertical input.
* Prevent site title from focusing too frequently (e.g. with each vertical object change) by caching the vertical label and using that string in `useEffect`. This resolves a subtle issue where if you click and hold the text preceding the vertical, the cursor would be moved to focus on the site title, until you let go of the mouse button.
* Add `moveCaretToEnd` function to move the selection to the end of the desired input area when clicking the form. This makes the label areas behave a bit more like an input field's label, by sending the cursor to the end of the editable area.
* Prevent clicking either editable field from bubbling up to the `form` onClick handler so that the browser default behaviour of clicking into a field moves the cursor to within the field as we'd expect.

#### Screenshot

Demo of clicking label text to send the cursor to the end of the editable areas, and then clicking back from the Design step where the cursor then goes to the end of the site title field:

![acquire-intent-cursor-position-small](https://user-images.githubusercontent.com/14988353/82022514-279a2980-96d0-11ea-994c-ce5319a57329.gif)

#### Testing instructions

Note: as @razvanpapadopol mentioned elsewhere, dealing with the cursor position can become quite hacky. So, I'm interested in your opinion here, too! Does this approach seem reasonable, or does it feel too brittle?

Things to test:

* From `/new`
* Enter and delete text in the vertical field
* Enter and delete text in the site title field
* Click within each of these fields while there's text there, to make sure the cursor goes to the correct position
* Click the label text of each, and ensure that the cursor goes to the end of the line
* Go to the design step with a site title entered, and then click back, does the cursor go to the end of the line
* Test going to the design step with no title, or no vertical, and then click back, make sure nothing breaks
* Check across a variety of browsers, Safari, Chrome, Firefox, IE, mobile browsers, and make sure nothing breaks

---

Fixes #41976 
And issue raised in PR https://github.com/Automattic/wp-calypso/pull/42197#issuecomment-629010997
And related to discussion in PR https://github.com/Automattic/wp-calypso/pull/40645#discussion_r402186180

2020-05-15 09:03 UTC, ramonjd approved these changes
Tested in Chrome, FF, Safari, iOS Safari, IE11. 

Only Edge 81 on Windows 10 didn't behave quite as expected. The cursor drops a bit.

![cursor](https://user-images.githubusercontent.com/6458278/82032150-2f60ca80-96de-11ea-949c-1be575fb1f9d.gif)

Not a blocker. This PR fixes the more annoying bugs reported :)

2020-05-15 13:02 UTC, razvanpapadopol commented
I've tested on desktop and found a regression compared to what we have on master when there is a previously entered value in vertical input and you press TAB key without changing the value:
- what I expect: the focus should move to site title input
- what happens: nothing. the cursor stays in the same position

Also there's an inconsistency between the 2 inputs when both have values and you move the focus to them by tabbing:
- on site title input the cursor is at the end
- on vertical input the cursor is at the beginning

2020-05-15 13:03 UTC, razvanpapadopol requested changes
I've tested on desktop and found a regression compared to what we have on master when there is a previously entered value in vertical input and you press TAB key without changing the value:
- what I expect: the focus should move to site title input
- what happens: nothing. the cursor stays in the same position

Also there's an inconsistency between the 2 inputs when both have values and you move the focus to them by tabbing:
- on site title input the cursor is at the end
- on vertical input the cursor is at the beginning

2020-05-18 06:23 UTC, andrewserong commented
Thanks for reviewing @razvanpapadopol! I've pushed an update which should resolve the tabbing behaviour and also fixes the following:

* Add 1px horizontal padding to the madlib__input class as a workaround to fix a Firefox bug related to caret position in contenteditable elements: https://bugzilla.mozilla.org/show_bug.cgi?id=1252108.
* Remove z-index from the madlib placeholder, so that it doesn't render on top of the drop-down suggestions.
* When tabbing between elements, default to the cursor being at the end of the element.

To get the tabbing behaviour to work as expected, while still preserving the changes in this PR, I've updated the vertical select to add a `handleBlurEvent` function that checks whether or not the vertical needs updating before calling `selectLastInputValue` — this reduces the frequency with which the vertical object gets changed, which makes the `siteTitle` useEffect that depends on the vertical fire a bit less aggressively.

This is ready for another test, now. Please do let me know if you think it's not quite the right approach, though. All of the workarounds to get `contenteditable` playing nicely are pretty challenging to wrangle, and I keep running into more complexities with long-running Firefox bugs, too. So, I don't want to add in changes that we feel might be too brittle. If this PR doesn't seem quite the right approach, I'm happy to spin up a separate PR with just the fixes that we might want to preserve (e.g. Firefox bug workaround, z-index issue, and cursor position at the beginning of the vertical input).

2020-05-19 08:49 UTC, razvanpapadopol approved these changes

2020-05-19 09:17 UTC, razvanpapadopol commented on client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
> -		z-index: 2;
Now, when wrapped to a new line, the placeholder area (marked with red) is no longer focusable with click.
<img width="859" alt="Screenshot 2020-05-19 at 12 00 05" src="https://user-images.githubusercontent.com/14192054/82308544-9d510e80-99ca-11ea-8987-83142e28ee27.png">

2020-05-20 01:19 UTC, ramonjd commented
@razvanpapadopol @andrewserong @simison 

Given the plans to remove the site category/vertical step in https://github.com/Automattic/wp-calypso/issues/42363 is it worth investing more development time into these changes?

2020-05-20 08:22 UTC, andrewserong commented
I ran out of time to do [the final tweaks](https://github.com/Automattic/wp-calypso/pull/42251#discussion_r427154306) on this one (was focused primarily on https://github.com/Automattic/wp-calypso/pull/41854/), but as Ramon mentioned, given the plans to remove the vertical step, it sounds like this PR will be superseded? @razvanpapadopol — thanks for all the reviews on this one, but do let me know if you think it's worth finishing it off after all, and I can take another look at this tomorrow. 🙇

2020-05-21 05:11 UTC, andrewserong commented
Closing this now that we've gone with hiding the vertical step and replacing the site title `contenteditable` span with an input field in https://github.com/Automattic/wp-calypso/pull/42406.

2020-05-21 05:11 UTC, closed without merging

2020-05-21 06:48 UTC, razvanpapadopol commented
We can always find here and use this [piece of magic](https://github.com/Automattic/wp-calypso/pull/42251/files#diff-77e5f87d23bb9ec994b17b589daf16fdR28-R40) if we want to go back to `contenteditable` at some point 😁