Cache packages folder builds to cut down the build time
Automattic/wp-calypso pull request #42822
Opened 2020-05-30 12:07 UTC by alshakero

#### Changes proposed in this Pull Request

* Calculate the checksum for the whole "packages" dir (minus `node_modules`, `dist`) and store it in a git ignored file.
* Create a `build-packages-if-needed` command.
* In this command, calculate the checksum of the packages directory and compare it against the stored one. If they match, it means no build is needed. 
* Save 20s. Profit. 

#### Testing instructions

1. Run `yarn build`
2. It should build packages.
3. Run `yarn build`
4. It h

Fixes #

2020-06-01 07:07 UTC, scinos requested changes
A few notes:

* `yarn build-packages` also builds `apps/`, not only `packages/`. We should include them in the checksum and any other computation
* The checksum also has to include dependencies. Some of them will live in `./packages/**/node_modules` or `./apps/**/node_modules` but most of them will be in `./node_modules`. A proxy may be to include `package.json` and `./yarn.lock` in the hash, but it is not 100% guaranteed (a package could be importing a module that is not declared in its `package.json`).

2020-06-01 13:28 UTC, blowery commented on bin/do-packages-need-a-rebuild.js
> +async function shouldRebuild() {
we should also rebuild if anything in the compilation chain has changed. Different babel version, babel plugin versions, typescript versions, etc etc.

2020-06-01 13:29 UTC, blowery commented on bin/do-packages-need-a-rebuild.js
> +async function shouldRebuild() {
a decent proxy for that might be a combo hash of the root yarn.lock and root babel config

2020-06-08 08:53 UTC, simison commented
> yarn build-packages also builds apps/, not only packages/. We should include them in the checksum and any other computation

`apps` and `packages` could have their separate cache-busting though.

2020-06-11 23:40 UTC, alshakero commented
Thank you @scinos and @blowery for the reviews! I addressed all issues.

2020-06-18 19:19 UTC, alshakero commented
I feel that this change, albeit makes a considerable performance difference, it overcomplicates a bit and might make maintenance harder. I'll close it and we can look at for inspo later.

2020-06-18 19:19 UTC, closed without merging