Remove composite checkout abtest (take 2)
Automattic/wp-calypso pull request #43238
Opened 2020-06-12 18:36 UTC by sirbrillig

#### Changes proposed in this Pull Request

This is a second attempt at https://github.com/Automattic/wp-calypso/pull/43163 

Currently this includes https://github.com/Automattic/wp-calypso/pull/43223 but all those commits will be rebased out of this PR when that is merged.

This removes the composite checkout abtest and sends 100% of page loads to new checkout versus old if they pass our other conditions, which are currently:

- Site is not jetpack (atomic sites are fine).
- Cart contains no jetpack plans.
- URL contains no unknown products (just to protect against things we haven't tested).
- Country code is US.
- Locale is EN.
- Currency is USD.

#### Testing instructions

Visit checkout with the above conditions met, and verify that you see new checkout.

2020-06-15 17:08 UTC, sirbrillig commented
Well now I don't know what's going on. The e2e builds are just failing outright. Maybe e2e tests are just broken. 🤔

2020-06-16 15:38 UTC, sirbrillig commented
e2e tests should be fixed again by https://github.com/Automattic/wp-calypso/pull/43298 Rebasing...

2020-06-16 15:44 UTC, michaeldcain approved these changes
:shipit:

2020-06-16 15:54 UTC, merged

2020-06-16 16:14 UTC, wp-desktop requested changes
WordPress Desktop CI Failure (ci/wp-desktop): @sirbrillig please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes. Please also ensure this branch is rebased off latest Calypso master.