Adds initial test skeleton and helper component
Automattic/wp-calypso pull request #43381
Opened 2020-06-17 13:18 UTC by getdave

#### Changes proposed in this Pull Request

We do not currently have any tests to cover the support search functionality in:

* the "FAB" inline help popover.
* the "Get help" card on My Home.

This PR will add e2e tests to cover the basic mechanics of this. This provides us with a solid foundation upon which to:

- refactor the existing components.
- add new functionality (such as being able to search site settings).

#### Testing instructions

* Configure the Calypso local e2e testing environment as per the docs.
* Boot Calypso locally - `yarn && yarn start`. Make sure it's running at `http://calypso.localhost:3000/`.
* Run the individual e2e test 
  - `cd` to the `test/e2e` directory.
  - run `./node_modules/.bin/mocha specs/wp-support-search`
* See tests run and verify they all pass.

Fixes https://github.com/Automattic/wp-calypso/issues/43135

2020-06-22 14:04 UTC, bsessions85 requested changes
This is failing for me in mobile view locally because the sidebar doesn't show up so it can't go to themes page. I'm going to push in a change that should help with that and then I left a few comments on some other things to look at.

2020-06-23 09:36 UTC, getdave commented on test/e2e/lib/components/support-search-component.js
> +		return await driver.wait(
Nice. Thanks for this. I've updated.

2020-06-23 09:37 UTC, getdave commented on test/e2e/specs/wp-support-search.js
> +				return await inlineHelpPopoverComponent.isPopoverVisible();
Agreed. Not sure what I was doing there as I did exactly that in the next `step()`!

2020-06-23 09:58 UTC, getdave commented on test/e2e/specs/wp-support-search.js
> +			// The "inline help" FAB sholuld not appear on the My Home
Fixed.

2020-06-23 10:11 UTC, getdave commented
@bsessions85 Thanks very much for the review and the fix for mobile. I've re-tested using `env BROWSERSIZE=mobile ./node_modules/.bin/mocha specs/wp-support-search` and it now works.

I'm not going to tackle in this PR, but there is a 2nd instance of "support search" on the My Home (see below). I'd appreciate some advice on how I could reuse the `SupportSearchComponent` so that it also works for this version which uses different classes but is essentially identical in functionality.

<img width="950" alt="Screen Shot 2020-06-23 at 11 10 02" src="https://user-images.githubusercontent.com/444434/85391537-37642380-b542-11ea-897b-1d4b7a8f3fca.png">

2020-06-23 11:40 UTC, retrofox commented
> refactor the "Get help" card to share components with the FAB implementation 
this isn't being addressed here, right?

2020-06-23 12:44 UTC, retrofox commented
**web version**

✓ Login and select a non My Home page (10469ms)
✓ Check help toggle is visible
✓ Open Inline Help popover (154ms)
✓ Close Inline Help popover (2341ms)
✓ Re-open Inline Help popover (113ms)
✓ Displays contextual search results by default
✓ Returns search results for valid search query (2992ms)
✓ Resets search UI to default state when search input is cleared  (98ms)
✓ Shows "No results" indicator and re-displays contextual results for search queries which return no results (8753ms)
✓ Does not request search results for empty search queries (4322ms)

10 passing (33s)

2020-06-23 12:53 UTC, retrofox commented
Same result setting the browser size to mobile

```
> env BROWSERSIZE=mobile ./node_modules/.bin/mocha specs/wp-support-search.js
```

2020-06-23 12:55 UTC, retrofox commented
LGTM. Going to give the last ✅ to @bsessions85. Nice job, Dave 👍

2020-06-23 13:49 UTC, bsessions85 approved these changes

2020-06-23 13:52 UTC, bsessions85 commented
@getdave One way to try would be just to add the selectors of the My home search box to the existing SupportSearchComponent selectors. 
Instead of `By.css( '.inline-help' )` you'd have something like `By.css( '.inline-help, .my-home-help' ). That will make it look for either one of those selectors. Give it a try and ping me if you need help.

2020-06-23 13:54 UTC, merged