Consume monorepo packages without building them
Automattic/wp-calypso pull request #43679
Opened 2020-06-25 12:07 UTC by jsnajdr

This PR makes it possible to consume monorepo packages (`packages/*`) without building them. To build Calypso, i.e., its webpack bundle, the `dist/esm` and `dist/cjs` folders don't need to be created and populated with transpiled files. That's a task that's needed only when preparing a package to be published in the NPM registry.

Instead, the Calypso webpack build can now directly consume the sources in `src/`, and transpile any Babel-enhanced JavaScript or TypeScript with its webpack loaders, just like any other non-package file in `client/`.

I achieved this by adding `calypso:main` field to all packages, and pointing in to the `./src/index` source file. Then I configured the webpack resolver to look at `calypso:main` first, using the `resolve.mainFields` option.

To make tests work, the Jest resolver needs to be aware of `calypso:main`, too. That's harder, and I had to write a custom resolver (`packages/calypso-build/jest/calypso-resolver`) by copying and modifying the default resolver from Jest sources.

Building Calypso, both in development (with the dev middleware that watches the sources for changes) and production, now doesn't require the `build-packages` or `build-packages:watch` steps. Simply running webpack is enough.

The only package that still needs the build step is `calypso-color-schemes`. It does SCSS-to-CSS-and-JS compilation, and also performs some magic with copying `color-schemes` assets (I remember that @ockham had to add that at some point to solve some problem that didn't have any other solution)

**Risks:**
There are several independent implementations of the module resolution algorithm in various tools:
- webpack
- TypeScript
- Jest
- Node.js

And not all of them can be easily configured to look at the `calypso:main` fields. We might end up with some part of our build pipeline being unable to load the monorepo packages correctly.

**How to test:**
Run `yarn start` and see if it builds Calypso correctly and if the build is faster now.

2020-06-25 12:33 UTC, wp-desktop requested changes
WordPress Desktop CI Failure (ci/wp-desktop): @jsnajdr please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes. Please also ensure this branch is rebased off latest Calypso master.

2020-06-25 14:46 UTC, nsakaimbo commented
Haven't seen this one before:

```
Application entry file "/Users/distiller/wp-desktop/release/mac/WordPress.com.app/Contents/Resources/app/build/desktop.js" does not exist. Seems like a wrong configuration.  stackTrace=
```

2020-06-30 09:16 UTC, alshakero requested changes
Thank you so much for this Jarda! 

I reviewed this and it seems to build correctly and works and is faster!

I investigated the caveats you mentioned a bit and I think I've come up with a solution for TypeScript.

#### TypeScript

Currently, TypeScript fails because `types` field in `package.json` (of a given package) points to a possibly non-existing file. Changing `types` field to the source file (`src/index.ts`) fixes the issue but is bad because if the package is ever published, `src` theoretically won't be published with it.

An OK solution is to add an `index.ts` file in the root of every TS pacakge. It should only be:
```ts
export * from './src/index';
```
💡 And `npmignore` this file.

This works because TS mimics the Node resolving algorithm, an `index.ts` file will tip it off to find the types file (in src) before failing over to `types` field in `package.json`. And when the package is published, `index.ts` won't exist, and `types` field will take precedence and the types in `dist` will be used. 

Maybe we can create a nice comment and add it inside this `index.ts` file to explain its existence. 

#### clean:packages
Currently, there is a still a package.json script called "clean:packages". It runs when node_modules is outdated and it takes some time. I think this can go :tada:

#### calypso-color-schemes
> The only package that still needs the build step is calypso-color-schemes

I think a fair solution is to rename its output to something other than `dist` and remove the output files from `gitignore`. The output is CSS (or the equivalent), I don't think it will be OS or Node version dependant. No need to rebuild them on everyone's machine.

If you'd like me to execute these changes I'd be happy to.

2020-06-30 09:47 UTC, sgomes commented
@jsnajdr: the bundle size savings in this PR are interesting. My guess is that they come from packages now being compiled with `evergreen` build settings?

2020-06-30 10:09 UTC, jsnajdr commented
> My guess is that they come from packages now being compiled with evergreen build settings in the evergreen build (which is the one ICFY measures)?

Yes, I didn't investigate it in detail, but I think the savings come from two places:
- transpiling the package source with `BROWSERSLIST_ENV=evergreen` rather than with `defaults`
- the monorepo packages are no longer placed in the `vendors` cache group, making the chunk layout more optimal

I'm not sure if the second thing (no `vendors`) is already happening, or if we need to nudge webpack to actually do it. It looks like a good thing to do: only third party libraries like React should be in `vendors` chunks.

2020-06-30 12:24 UTC, jsnajdr commented
> an `index.ts` file will tip it off to find the types file (in `src`) before failing over to `types` field in `package.json`.

That would require the resolver to first look for `package-dir/index.ts` before looking at `package-dir/package.json` and finding the `types` field there. But the resolver does the lookup in the opposite order.

But this `package-dir/index.ts` is used in case the `dist/*` directories don't exist, and the lookup by `package.json` fields (`main`, `module`, `types`) fails to find the target file. Then `package-dir/index.ts` is used as a fallback.

If the `dist/` directory exists, then the files from there will be used and `index.ts` will be ignored. That's OK.

After implementing this though, I have a little problem with the `patch-types.ts` modules:

```
client/landing/gutenboarding/gutenberg-types-patch.ts:2:7 - error TS2300: Duplicate identifier 'breakpoint'.

2  type breakpoint = 'huge' | 'wide' | 'large' | 'medium' | 'small' | 'mobile';
        ~~~~~~~~~~

  packages/plans-grid/src/types-patch.ts:2:7
    2  type breakpoint = 'huge' | 'wide' | 'large' | 'medium' | 'small' | 'mobile';
            ~~~~~~~~~~
    'breakpoint' was also declared here.

client/landing/gutenboarding/gutenberg-types-patch.ts:3:7 - error TS2300: Duplicate identifier 'operator'.

3  type operator = '>=' | '<';
        ~~~~~~~~

  packages/plans-grid/src/types-patch.ts:3:7
    3  type operator = '>=' | '<';
            ~~~~~~~~
    'operator' was also declared here.

packages/plans-grid/src/types-patch.ts:1:1 - error TS1208: All files must be modules when the '--isolatedModules' flag is provided.

1 declare module '@wordpress/compose' {
  ~~~~~~~
```

Apparently, if the `tsc` build uses the `*.d.ts` files from `dist/types`, then the `packages/plans-grid/dist/types/types-patch.d.ts` is never loaded. But from `src/`, the corresponding source file _is_ loaded and triggers a duplication error.

@alshakero @razvanpapadopol I assume that the "types patch" is there to monkey-patch a bug in the `@wordpress/compose` package typings? If so, I think it would help to deduplicate them by splitting a new, common package.

2020-06-30 13:00 UTC, alshakero commented
> @alshakero @razvanpapadopol I assume that the "types patch" is there to monkey-patch a bug in the @wordpress/compose package typings? 

That's right.

> If so, I think it would help to deduplicate them by splitting a new, common package.

Sounds like a good solution

2020-06-30 13:11 UTC, jsnajdr commented
The `typecheck-strict` and `transpile` tasks continue to be a challenge, because they directly use the `tsc` executable.

If you load the TypeScript compiler programmatically from the `typescript` package and invoke it, you can pass a "language services host" object that implements a custom `resolveModuleNames` method. That's what webpack `ts-loader` does, for example.

But configuring the `tsc` executable is not possible. The TypeScript repo has had an issue open since 2017: https://github.com/Microsoft/TypeScript/issues/18896

What's kind of a good news is that the Yarn PnP project needs to do the same thing as we do here: pass a custom resolver to various tools. We're not alone. Yarn PnP works with webpack, `ts-loader`, with Jest. The only gap is the `tsc` compiler itself. More info is on this Yarn docs page: https://classic.yarnpkg.com/en/docs/pnp/getting-started/

Maybe we could stop using `tsc` directly, in favor of a wrapper script? [This comment](https://github.com/Microsoft/TypeScript/issues/18896#issuecomment-333685601) from the TS team lead suggest it's normal and expected 🙂

> Note that this is already an option for non-`tsc` environments because the `host` object given to the compiler exposes `resolveModuleNames` which hosts may implement to their liking.
>
> I'm not sure there's anyone who would want this ability who isn't already loading TS through some more advanced build pipeline.

2020-08-12 06:44 UTC, scinos commented
A few notes: 

* Writing our custom resolver is very tricky, as it won't support clearing the cache when Jest is run in watch mode. Unfortunately Jest doesn't provide a better way right now. I [raised a PR](https://github.com/facebook/jest/pull/10393) with them to allow reusing the defaultResolver (so we get cache management for free) and be able to use packageFilter to look for other fields. More info in https://github.com/facebook/jest/issues/2702#issuecomment-671947783

* The change in this PR is too big in scope. I think we could ignore TypeScript packages for now and focus on pure JavaScript packages which should be easier. It will already be a big improvement (~38% faster installations according to my local tests and smaller bundle sizes for evergreen). 

* I'm not sold on the idea of introducing `calypso:main`, it will be yet another non standard "calypsoism" that people will have to understand and maintain. I think we could change the field `module` to point to the untranspiled source code (already in ESM), and leave `main` with the CJS transpilation for published packages.

2020-08-17 05:40 UTC, scinos commented
Raised https://github.com/Automattic/wp-calypso/pull/44824 to cover some of the intent of this PR (do not build JS packages, leave TS packages for now)

2020-08-17 06:06 UTC, jsnajdr commented
> Writing our custom resolver is very tricky, as it won't support clearing the cache when Jest is run in watch mode. 

If I understand it correctly, that's now solved with your Jest PR and your Jest resolver in #44824 uses the same technique as the one in this PR?

> The change in this PR is too big in scope.

Yes, I agree that it's too big for merging at once. My intent was to figure out if there's a solution that works for the whole codebase, without any errors, and then implement it incrementally.

It would be a waste to implement some technique only to discover there is a roadblock that prevents us from using it universally.

> I think we could change the field `module` to point to the untranspiled source code (already in ESM), and leave `main` with the CJS transpilation for published packages.

Beware that there are two kinds of "transpilation" that are orthogonal to each other:
- what _code_ syntax does the code use? Old compatible ES5 or latest ES2020 that needs to be transpiled for older browsers?
- what _module_ syntax does the code use? It's possible to create a CJS module with fancy syntax (ES2020, JSX, even custom Babel extensions) or an ESM module with a conservative ES3 syntax.

The CJS and ESM bits will be completely removed by the bundler (webpack), but the remaining code will stay and will be shipped to the destination (a browser or a Node runtime).

2020-08-17 06:17 UTC, jsnajdr commented
> I'm not sold on the idea of introducing `calypso:main`

Few weeks ago, while on leave, I found this article that suggests using the modern `exports` field for the same purpose: https://twitter.com/_developit/status/1289271769287671809

Looks like something definitely worth looking at.

2025-04-16 07:15 UTC, jsnajdr commented
Closing as this idea (`calypso:src`) was already shipped a long time ago.

2025-04-16 07:15 UTC, closed without merging