FSE: Disable Block Directory on Simple sites
Automattic/wp-calypso pull request #44070
Opened 2020-07-10 13:11 UTC by WunderBart

#### Changes proposed in this Pull Request

Disable Block Directory via FSE's Block Inserter Modifications module by unregistering the `block-directory` plugin and registering our own to render `no results` state.

⚠️ This module should be removed once we start supporting Block Directory.

#### Testing instructions

- Enable edge sticker on your Simple test site,
- Open that site sandboxed and verify that it's using Gutenberg v8.5.1,
- Run `yarn dev --sync` to upload local FSE `dev` build to your sandbox,
- Go to the Editor and open the Block Inserter,
- Try searching for something that should return no results - you should see the `No results found.` message,
- Try searching for `css` - you should see the no results message **and** the Contextual Tip about our Customizer,
- Build and upload the plugin to your AT site and make sure the Block Directory isn't disabled there.

#### Screenshots

| Before<br>(no results)  | Before<br>(no res. + cont. tip) | After<br>(no results) | After<br>(no res. + cont. tip) |
| ------------- | ------------- | ------------- |  ------------- |
| ![image](https://user-images.githubusercontent.com/1451471/87157177-221b2300-c2be-11ea-90e6-6e9eb7dcd700.png) | ![image](https://user-images.githubusercontent.com/1451471/87157200-2b0bf480-c2be-11ea-97d5-28404e255bdc.png) | ![image](https://user-images.githubusercontent.com/1451471/87157113-03b52780-c2be-11ea-957a-454afa1fb82d.png) | ![image](https://user-images.githubusercontent.com/1451471/87157130-0b74cc00-c2be-11ea-8fbd-3ba46d14861e.png) |

Fixes #43677

2020-07-10 13:21 UTC, a8ci18n commented on apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/disable-block-directory/index.js
> +								{ __( 'No results found.', 'full-site-editing' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **58** times:
`translate( 'No results found.', { context: 'search results'} )` *ES Score: 11*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/try/disable-block-directory)

2020-07-10 13:28 UTC, a8ci18n commented on apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/disable-block-directory/index.js
> +									{ __( 'No results found.', 'full-site-editing' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **58** times:
`translate( 'No results found.', { context: 'search results'} )` *ES Score: 11*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/try/disable-block-directory)

2020-07-10 18:20 UTC, fullofcaffeine commented
Hi Bart :wave:! 

I've tested this changeset in a test site of mine, here are the steps I followed:

1. I made sure `fullofcaffeine.wordpress.com` was sandboxed;
2. I `shh`'ed into my sandbox, `cd`'ed into `public_html` and ran `svn reset -R .` then `svn st | grep '^?' | awk '{print }' | xargs rm -rf` to make sure to remove any untracked leftovers;
3. I then came back to my local box, `cd`ed to `wp-calypso` and checked out your branch, and `cd`ed to the FSE sub-directory to run `yarn dev --dev`;
4. Accessed `https://fullofcaffeine.wordpress.com/wp-admin/post-new.php?post_type=page`/. Made sure I was using Gutenberg `8.5.1`:

![version](https://user-images.githubusercontent.com/81248/87185631-b5992780-c2af-11ea-8b72-c164e452923d.png)


5. Brought up the contextual picker on the page, by clicking the rounded square + button. Searched for an unexistent block, got this:

![unexistingblock](https://user-images.githubusercontent.com/81248/87185173-eb89dc00-c2ae-11ea-995b-edbc88037091.png)

6. Tried the same thing, but this time used the button on the top-left corner of the content area, in the main toolbar (the picker that appears in the sidebar). Got this:

![unexisting2](https://user-images.githubusercontent.com/81248/87185282-212ec500-c2af-11ea-9b64-873fc4208af7.png)

7. Then proceeded to try searching for `css`, first with the page inline picker:

![fr1](https://user-images.githubusercontent.com/81248/87185368-402d5700-c2af-11ea-8d2b-dda14db3908e.png)

8. Then with the sidebar picker:

![fr2](https://user-images.githubusercontent.com/81248/87185422-5cc98f00-c2af-11ea-8ee9-cbdd383a6472.png)


So, it works fine when the sidebar picker is used but doesn't for the inline picker. Perhaps I'm missing something?

I'm yet to test the AT site scenario but will do so shortly and post my findings here.

2020-07-10 19:15 UTC, fullofcaffeine commented
> Build and upload the plugin to your AT site and make sure the Block Directory isn't disabled there.

1. I created a new ephemeral AT site and `scp`'ed the `full-site-editing-plugin` sub-dir after building the whole project with `yarn build`. Made sure it was activated;
2. I also installed Gutenberg `8.5.1` and activated it;
3. Brought up the picker from the page and tried searching for an unexistent block. Got a "No results found." message:

![1](https://user-images.githubusercontent.com/81248/87189977-3e679180-c2b7-11ea-88e3-1c8e4de4759b.png)

4. Brought up the sidebar picker and searched for an unexistent block. Got a "No blocks found in your library", which I think is the expected result?

![2](https://user-images.githubusercontent.com/81248/87190014-54755200-c2b7-11ea-8b6c-a263a3982259.png)

I noticed that the "page" inline picker also has a slightly different UI and behavior here as well. Is that expected?

2020-07-13 10:27 UTC, a8ci18n commented on apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/disable-block-directory/index.js
> +									<p>{ __( 'No results found.', 'full-site-editing' ) }</p>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **58** times:
`translate( 'No results found.', { context: 'search results'} )` *ES Score: 11*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/try/disable-block-directory)

2020-07-13 10:55 UTC, WunderBart commented
Thanks for the thorough review, @fullofcaffeine 🙇 

> 7. Then proceeded to try searching for css, first with the page inline picker. Expected to see the contextual tip, but it didn't appear:

Nice catch! This seems to be an issue with the  `>=8.3.0`, where the [Quick Inserter](https://github.com/WordPress/gutenberg/blob/1bec21feb1ba8110fdd11b01c84dc2a3849884a1/packages/block-editor/src/components/inserter/quick-inserter.js) is not using the `__experimentalInserterMenuExtension` slot that we need for [rendering Contextual Tips](https://github.com/Automattic/wp-calypso/blob/837afc0e09524316c292771c3d244717a3f1d44b/apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/contextual-tips.js#L25-L26) anymore. @retrofox, is that something you'd want to look into?

> (On AT site) I noticed that the "page" inline picker also has a slightly different UI and behavior here as well. Is that expected?

Yep, this is how it looks without the disabling script on - AT site should not be affected at all by it and, according to your review, it's not 👍 

---

I added the block icon to the no results page for more consistency between inserters (+ updated screenshots in the description).

2020-07-14 14:33 UTC, sirreal commented
> ⚠️ This module should be removed once we start supporting Block Directory.

I don't expect to remove this, Simple sites won't support one-click block installs but will offer an upgrade path that would probably be implemented on top of the solution we're working on here.

2020-07-14 14:34 UTC, sirreal requested changes
I'm not sure what's going on, but the notice is either rendered too eagerly or needs to be cleaned up when there are results:

![Screen Shot 2020-07-14 at 16 32 09](https://user-images.githubusercontent.com/841763/87438445-d505bc80-c5ef-11ea-94d4-9956dd95d8e0.png)

2020-07-14 16:52 UTC, sirreal commented
If we're only interested in shipping this functionality to Simple sites, it's probably best to implement it as a WPCOM diff. We don't need to get into all the FSE complexity, it may be as simple as dequeueing a script.

2020-07-16 14:43 UTC, sirreal commented
Let's go with D46418-code instead of working through FSE.

2020-07-16 14:43 UTC, closed without merging