Add warning notice in checkout when plan includes backup already
Automattic/wp-calypso pull request #44181
Opened 2020-07-15 18:00 UTC by monsieur-z

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #

2020-07-15 21:40 UTC, a8ci18n commented on client/my-sites/checkout/checkout/duplicate-product-notice-content.tsx
> +				{ translate( 'Manage Subscription' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **33** times:
`translate( 'Manage subscription' )` *ES Score: 14*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/plan-backup-warning-in-checkout)

2020-07-16 15:07 UTC, monsieur-z commented on client/my-sites/checkout/checkout/style.scss
> +		.checkout__payment-box-section {
Just some reformatting.

2020-07-16 15:30 UTC, monsieur-z commented on client/my-sites/checkout/checkout/secure-payment-form.jsx
> -	renderCreditCardPaymentBox() {
This method is never used.

2020-07-16 15:49 UTC, wp-desktop submitted a review, later dismissed
WordPress Desktop CI Failure for job "wp-desktop-source".

@monsieur-z please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/813312). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-07-16 19:40 UTC, monsieur-z commented on client/my-sites/checkout/checkout-system-decider.js
> +	const jetpackPlan = getPlanByPathSlug( product, GROUP_JETPACK );
`product` is a string.

2020-07-16 23:10 UTC, robertf4 commented
I'm having trouble getting the message to display in one case. It seems to be a problem with `getPlanByPathSlug()`. 

To reproduce:
1. Buy Jetpack Personal on a new site.
2. Visit `/checkout/<site_slug>/jetpack_backup_daily`
3. `getPlanByPathSlug()` returns `undefined`, so the notice doesn't display.

2020-07-16 23:11 UTC, robertf4 reviewed
I'm having trouble getting the message to display in one case. It seems to be a problem with getPlanByPathSlug().

To reproduce:

1. Buy Jetpack Personal on a new site.
2. Visit /checkout/<site_slug>/jetpack_backup_daily
3. getPlanByPathSlug() returns undefined, so the notice doesn't display.

2020-07-20 15:20 UTC, monsieur-z commented
@robertf4, from my understanding the scope of the issue was to display the notice when you have a Backup product (either _Daily_ or _Real-Time_) and are about to purchase a plan that already includes it.

In your example, it's the other way around: you have a plan and want to buy a Backup product. The UI of Calypso already prevents you from reaching the checkout page with this state, though it could happen from Jetpack.com indeed.

I can handle this in a different PR, if we feel it should be part of the fix too.

2020-07-21 14:33 UTC, rcanepa commented on client/my-sites/checkout/checkout/secure-payment-form.jsx
> -	renderCreditCardPaymentBox() {
I noticed the same thing.

2020-07-21 14:45 UTC, robertf4 commented
@monsieur-z I think it's fine to do in a separate PR but I think we do need to do it. The order the conflicting plans are purchased in isn't as important as as the fact that they are purchased simultaneously, and I know we have users who have purchased them in both orders.

I was looking at this Friday but didn't get very far, the plans-list doesn't account for products and so it's hard to know where to check for the product slug.

2020-07-21 14:55 UTC, rcanepa approved these changes
LGTM. I test this with several payment types and it worked as expected. 

I have one question though, why did you decide to check for a duplicate Backup feature inside the `CheckoutSystemDecider` component? I ask because I saw we are passing down the `infoMessage`  prop through three components that don't need it. The chain looks like `CheckoutSystemDecider > CheckoutContainer > Checkout > SecurePaymentForm`, and `SecurePaymentForm` is the component that actually makes use of the prop.

2020-07-21 14:59 UTC, rcanepa commented
> @monsieur-z I think it's fine to do in a separate PR but I think we do need to do it. The order the conflicting plans are purchased in isn't as important as as the fact that they are purchased simultaneously, and I know we have users who have purchased them in both orders.
> 
> I was looking at this Friday but didn't get very far, the plans-list doesn't account for products and so it's hard to know where to check for the product slug.

I agree with this. Maybe this PR is not the place to fix the issue, but we should address it because users can easily get to the checkout page with a Backup product in their cart because they followed a link outside of Calypso.

2020-07-21 15:14 UTC, monsieur-z commented
> I have one question though, why did you decide to check for a duplicate Backup feature inside the `CheckoutSystemDecider` component? I ask because I saw we are passing down the `infoMessage` prop through three components that don't need it. The chain looks like `CheckoutSystemDecider > CheckoutContainer > Checkout > SecurePaymentForm`, and `SecurePaymentForm` is the component that actually makes use of the prop.

Good point @rcanepa. The very same notice is used for the composite checkout (which you can see in this separate PR #44237), so it made sense to have the logic where the 2 checkout components were created.

2020-07-21 15:19 UTC, monsieur-z commented
> I think it's fine to do in a separate PR but I think we do need to do it.

I agree @robertf4 and @rcanepa. We focused on releasing a solution for the main scenario first. I believe  I'll have time to handle this case this week too.

2020-07-22 12:43 UTC, wp-desktop submitted a review, later dismissed
WordPress Desktop CI Failure for job "wp-desktop-source".

@monsieur-z please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/820084). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-07-22 13:05 UTC, merged

2020-07-22 13:15 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@monsieur-z please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/820228). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-07-22 14:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4120774

Thank you @monsieur-z for including a screenshot in the description! This is really helpful for our translators.

2020-07-30 16:33 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4120774).

2020-08-01 02:02 UTC, juzer28 commented
G

2020-08-07 19:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4120774).