Extract context middleware
Automattic/wp-calypso pull request #44200
Opened 2020-07-16 06:13 UTC by scinos

### Background

I'm trying to extract webpack-dev-server form `client/server` logic. The idea is that for production it will read the assets from the filesystem (as it does today), but for dev mode it will redirect it to a separate web server. This will allow quick reload of the node service without having to bundle everything all the time. It will also pave the path for potential improvements like deploy the client assets to a shared place (eg: an S3 bucket) without having to deploy the node service every time. The next step is to use that safety net to refactor this mega-module and split into smaller modules. Note that no tests has been changed but everything still passes. 

The progress so far has been:
* Introduce tests for the server to make sure I don't break anything (#43177). 
* Extract middleware related to files and assets (#44178)

### Future

The next step would be to refactor the tests without changing the code to accommodate them to the new modules (i.e. split the meta-test). Then rinse and repeat with further refactors, until we are happy with the structure of this part of the code.

### Changes in this PR

* Extract `defaultContext` logic and split it into cohesive modules.
* Extract middleware to detect subdomain and locale
* Extract middleware to detect if the user is logged in or is a support session.

### Testing instructions

* Check that you can load the page in different locales, including RTL language.
* Check that you can load the page as an authenticated user and as an anonymous user.
* Check that the badge still works, including abtest and preferences helper.
* Check that the branch name is displayed in the badge (you need to start Calypso locally to verify this)
* Check that SSR pages (login form, `/start`, and `/themes`) works

2020-07-29 12:36 UTC, saramarcondes commented
This PR has the same problem as https://github.com/Automattic/wp-calypso/pull/39979 for me, when I log out it does not redirect me correctly. I instead get a blank page with just the top bar and the GDPR banner.

@griffbrad any ideas what might be going on here?

2020-07-29 13:06 UTC, saramarcondes commented
- [x] Check that you can load the page in different locales, including RTL language.
- [ ] Check that you can load the page as an authenticated user and as an anonymous user. (see https://github.com/Automattic/wp-calypso/pull/44200#issuecomment-665638072)
- [x] Check that the badge still works, including abtest and preferences helper.
- [x] Check that the branch name is displayed in the badge (you need to start Calypso locally to verify this)
- [x] Check that SSR pages (login form, /start, and /themes) works

2020-07-29 14:51 UTC, griffbrad commented
> @griffbrad any ideas what might be going on here?

I do see the same behavior on this PR when logging out.  I'm not sure of the cause, though.  Nothing obvious in the console.  Manually navigating to another route (e.g. `/read`) will trigger a redirect to login.  I wonder if there is any special handling of the root route (`/`) that might be causing the issue both here and in #39979.

@sgomes are there any special routing considerations to take into account given the separate entry point?

2020-07-29 15:04 UTC, sgomes commented
> @sgomes are there any special routing considerations to take into account given the separate entry point?

Login is currently handled separately in `server/pages/index.js`, since it's a different entry point:

```js
// Set up login routing.
handleSectionPath( LOGIN_SECTION_DEFINITION, '/log-in', 'entry-login' );
loginRouter( serverRouter( app, setUpRoute, null ) );
```

I don't see anything like that in the modified code, but I haven't tried to fully grok it. Perhaps it's now been made a bit more generic, and the special case isn't needed any more?

2020-07-29 21:24 UTC, scinos commented
I do see the same behaviour in other live branches (https://calypso.live/?branch=add/eslint-no-relative-imports-rule) and in https://wpcalypso.wordpress.com/.

2020-07-30 11:10 UTC, lynnbgriffith approved these changes
I hadn't noticed that it was affecting other .live branches earlier.  Interesting.  I think we can move forward here, then.  👍

2020-08-05 13:47 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-source".

@scinos please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/839858). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2021-02-03 11:12 UTC, scinos commented
Stale and no plans to work on it in the near future

2021-02-03 11:12 UTC, closed without merging