[WIP] Add domain price check for premium domains in the domain suggestions page
Automattic/wp-calypso pull request #45008
Opened 2020-08-18 19:54 UTC by hambai

#### Changes proposed in this Pull Request

* We want to start selling premium domains to our users. The domain suggestion endpoint is already capable of returning premium domains. Now we need to show the proper premium domain price and work out any other cases.

#### Testing instructions

* Depends on D48244-code which introduces a new REST API endpoint

2020-08-20 14:50 UTC, daledupreez requested changes
I've only skimmed the code, but I noticed two issues:
 * The premium pill is left-aligned in the "normal" suggestions section, while it should be right-aligned per the design in p99Zz8-1mx-p2
 * If the user still has a domain credit available, the suggestions are shown with the text "First year free with your plan" and then have the correct renewal price.

2020-08-20 14:50 UTC, daledupreez commented on client/components/domains/register-domain-step/index.jsx
> +						pending: true,
Is this really still pending?

2020-08-25 08:59 UTC, merged

2020-08-25 10:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4270315

Thank you @hambai for including a screenshot in the description! This is really helpful for our translators.

2020-09-04 09:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4270315).