Gutenboarding: Fix theme name + premium badge center alignment in design selection
Automattic/wp-calypso pull request #45151
Opened 2020-08-24 12:54 UTC by ciampo

#### Changes proposed in this Pull Request

* Changed the layout of the `.design-selector__option-meta` element from `inline-grid` to `inline-flex`
* This allows for its content to be always horizontally centered, regardless of the theme being premium or not
* Theme name and premium label allowed to wrap on more lines, in case they don't fit into one line

#### Testing instructions

* `yarn start`
* visit `localhost:3000/new`
* proceed through the onboarding flow until reaching the Design (theme) selection step
* scroll through the page until premium themes are shows
* notice how both non-premium and premium themes have their name center-aligned

#### Before

![Theme names and premium label are not horizontally centered](https://user-images.githubusercontent.com/1083581/91046846-6ddd1e00-e619-11ea-9736-e2d5af390e47.png)

#### After

![Theme names and premium label are horizontally centered](https://user-images.githubusercontent.com/1083581/91046905-88af9280-e619-11ea-85a1-7ad171b08a4c.png)

Fixes #44685

2020-08-24 14:07 UTC, yansern commented
Tested on Chrome & also tested on RTL on Firefox.
![2020-08-24_16-06-47](https://user-images.githubusercontent.com/1287077/91053911-d4673980-e623-11ea-8bf8-e8dcc88e7a12.png)

2020-08-24 14:09 UTC, yansern commented
Perhaps the font size for the badge could be smaller?

![image](https://user-images.githubusercontent.com/1287077/91054411-0e384000-e624-11ea-8c16-121360ea46a8.png)



This is how it looks like in Figma. (Also it seems that it is full caps).

![image](https://user-images.githubusercontent.com/1287077/91054894-332cb300-e624-11ea-9b97-290c9ae989d9.png)

2020-08-24 14:10 UTC, yansern commented on client/landing/gutenboarding/onboarding-block/design-selector/style.scss
> +		flex-wrap: wrap; // If theme name and premium badge don't fit on one line
Very useful comment! Thanks!

2020-08-24 14:11 UTC, yansern requested changes
Perhaps the font size for the badge could be smaller?

![image](https://user-images.githubusercontent.com/1287077/91054411-0e384000-e624-11ea-8c16-121360ea46a8.png)



This is how it looks like in Figma. (Also it seems that it is full caps).

![image](https://user-images.githubusercontent.com/1287077/91054894-332cb300-e624-11ea-9b97-290c9ae989d9.png)

2020-08-24 16:46 UTC, ciampo commented
Updated theme name & premium badge typography, following the Figma spec:

- Smaller font size for theme name
- Smaller font size for premium badge (note: it's now 10px, which causes a lint error as that is not one of the allowed font sizes — I've disabled the linter rule for now, and added the `//typography-exception`inline comment)
- Smaller icon size for premium badge
- DIfferent background for the Premium badge (gray 80), instead of pure black
- Uppercase text in the premium badge

2020-08-25 07:07 UTC, razvanpapadopol commented
> Smaller font size for premium badge. Note: it's now 10px, which causes a lint error as that is not one of the allowed font sizes (see packages/typography/styles/variables.scss) — I've disabled the linter rule for now, and added the //typography-exceptioninline comment

Not a blocker for this PR but we should take this example and some bigger font-size we need for the PlansGrid and try updating these rules and [typography variables](https://github.com/Automattic/wp-calypso/blob/master/packages/typography/styles/variables.scss). 

Small vertical alignment issue between design name and badge:
<img width="339" alt="Screenshot 2020-08-25 at 09 57 40" src="https://user-images.githubusercontent.com/14192054/91143063-98cb7e80-e6ba-11ea-8b96-747fcb2749fa.png">

Note: we should remember to update also the **After** screenshot in description once the implementation is final (or at least ready for review).

2020-08-25 07:55 UTC, ciampo commented
> Not a blocker for this PR but we should take this example and a similar one for the PlansGrid and propose an update for this rule and typography variables.

Is there anything I can help with this?


> There is only some vertical alignment issue between design name and badge:

I adjusted the vertical alignment to the best I could before starting to fight with sub-pixel alignment


> Note: we should remember to update also the After screenshot in description once the implementation is final (or at least ready for review).

Good point — it's done now

2020-08-25 08:25 UTC, yansern commented
It appears that the tooltip becomes uppercase as well (but we can leave that for the other PR).
![image](https://user-images.githubusercontent.com/1287077/91150962-56577100-e6bd-11ea-9c20-05b5f6c3edcf.png)

2020-08-25 08:31 UTC, ciampo commented
Rebased on top of master

2020-08-25 08:37 UTC, yansern approved these changes
Approving this PR. Other minor tweaks can be pushed to another PR.

2020-08-25 10:20 UTC, merged