Add/editing toolkit coming soon
Automattic/wp-calypso pull request #45167
Opened 2020-08-25 06:00 UTC by ramonjd

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #

2020-09-01 08:27 UTC, andrewserong commented
I don't have much to add yet, but this is coming along nicely already! I was pleasantly surprised at how easily this seems to be able to override the existing coming soon mode by just setting public to 0, and therefore none of the existing coming soon behaviour will fire. I think I might have been overthinking things in regards to supporting coming soon v1.

I'm not _too_ sure where you're up to in the PR yet, but I was able to successfully display the fallback coming soon on my test site, but switching a page to Coming Soon from the pages view looks like it's doing the correct thing in Calypso, but doesn't appear to show the page for me yet. Calling `get_blog_option` in my sandbox shows that the `wpcom_coming_soon_page_id` setting hasn't been updated even though the response from the server with D45700-code is applied looks like it _has_... I might be missing something obvious here, so will give it another try tomorrow!

2020-09-01 08:46 UTC, ramonjd commented
thanks for testing @andrewserong !!

> Calling get_blog_option in my sandbox shows that the wpcom_coming_soon_page_id setting hasn't been updated even though the response from the server with D45700-code is applied looks like it has... I might be missing something obvious here, so will give it another try tomorrow!

I was just trying to get that working this afternoon when time ran out. Feel free to take a stab tomorrow if you dare ;)

2020-09-02 02:10 UTC, andrewserong commented
Thanks @ramonjd! Got it working, just needed a tiny update to D45700-code (the site option was set to `page_for_coming_soon` so I've changed it to `wpcom_coming_soon_page_id` to match this PR). Seems to be working okay, now!

2020-09-02 02:12 UTC, andrewserong commented
I thought I might have a go at copying over the markup for the existing Coming Soon page to this PR later on this afternoon — but let me know if I'll be stepping on toes by messing around in this PR and I can branch off this one, or look at a different area (like getting the launch / logged in coming soon banner to support the new public coming soon mode).

2020-09-02 02:29 UTC, ramonjd commented
> the site option was set to page_for_coming_soon so I've changed it to wpcom_coming_soon_page_id to match this PR

Awesome, thank you for catching that one I missed!

> I thought I might have a go at copying over the markup for the existing Coming Soon page to this PR later on this afternoon

Go ahead to do whatever you want. Don't wanna break your stride. I'll peel off and look at something else.

2020-09-02 08:43 UTC, andrewserong commented
## Fallback coming soon

I've added the current Coming Soon markup as the fallback and got it to load Recolata

* [ ] I notice the current theme is overriding some styling to do with the buttons, which will need to be fixed up on mobile

![image](https://user-images.githubusercontent.com/14988353/91958884-438f0d00-ed4b-11ea-909a-f8a3adb09b68.png)

## Coming soon page selected

Here's what it looks like if I pick a Coming Soon page (here I've just created a simple page with a big Cover block and gradient background):

![image](https://user-images.githubusercontent.com/14988353/91959386-e0ea4100-ed4b-11ea-80dc-1c802284301c.png)

## Other screenshots of the current state of the PR

Just adding a couple of other screenshots to show the current state of the PR for anyone else looking on :)

![image](https://user-images.githubusercontent.com/14988353/91958911-4be74800-ed4b-11ea-8b50-586e52785118.png)

![image](https://user-images.githubusercontent.com/14988353/91958946-5b669100-ed4b-11ea-915a-8764332744c2.png)

There's still heaps more to do of course!

2020-09-07 01:55 UTC, roo2 commented
Amazing progress!
I tested locally, here's what I've found still to do so far

*Settings Page*
* Make unlaunched sites start as coming soon, make launching a site set it to public, not coming soon
* I think the coming soon settings section should have a link to set the coming soon page

*Pages List*
* We should probably only be able to set the coming soon page if the settings is enabled? or otherwise indicate that the page won't be used if the setting is not enabled.
* setting coming soon pages triggers a " Homepage is showing latest posts" message, even if homepage is set to an existing page 🤔 
* once coming soon page is set, the option to set homepage and latest post page disappears from the dropdown menu next to the page  🤔 
* When I had a coming soon page set, as an incognito user, I continued to see the default coming soon page.
* I think sites should start with a default coming soon page (if you're on the right plan?).
* Make the coming soon page feature only work for paid users and communication around that

* Live site *
* When logged in, the v1 coming soon shows a site banner saying "your site is not launched yet, only you can see it until the site is launched" I think we should do something like that too.
* Fix login link on default coming soon page, currently it just goes to #
* a8cs can see peoples coming soon sites, is that expected?

2020-09-07 03:23 UTC, ramonjd commented
Thanks for capturing these ideas! 

> Make unlaunched sites start as coming soon, make launching a site set it to public, not coming soon

Maybe we could start on this, putting it behind some query option in `sites/new` and/or feature flag? There's an [issue](https://github.com/Automattic/wp-calypso/issues/45019) that loosely related to this topic.

> I think the coming soon settings section should have a link to set the coming soon page

To the editor version? Either way, good idea. Noted.

> setting coming soon pages triggers a " Homepage is showing latest posts" message, even if homepage is set to an existing page 🤔
> once coming soon page is set, the option to set homepage and latest post page disappears from the dropdown menu next to the page 🤔

This would be worth looking into now too @roo2 

Not sure what the right logic would be, but I guess we should be able to switch between home and coming soon types as we wish. Noting that if a user switches a coming soon page to be the home page, they'll fallback back to the default coming soon page (if the feature is activated.

> a8cs can see peoples coming soon sites, is that expected?

I guess so. I think only the user themselves sees the full site if they're logged in (and with coming soon enabled)


> Fix login link on default coming soon page, currently it just goes to #


Maybe we could address that in https://github.com/Automattic/wp-calypso/pull/44888 ?

2020-09-07 04:38 UTC, roo2 commented
>> setting coming soon pages triggers a " Homepage is showing latest posts" message, even if homepage is set to an existing page 🤔
>> once coming soon page is set, the option to set homepage and latest post page disappears from the dropdown menu next to the page 🤔
> This would be worth looking into now too @roo2

Great, yea I'd quite like to take a look at this on this PR/branch

2020-09-10 01:51 UTC, roo2 commented
rebased

2020-09-10 09:58 UTC, simison commented on apps/editing-toolkit/editing-toolkit-plugin/wpcom-coming-soon/class-wpcom-coming-soon.php
> +		wp_enqueue_style( 'recoleta-font', '//s1.wp.com/i/fonts/recoleta/css/400.min.css' );
No strong opinion on this, but you might also look at importing in CSS [from the typography package](https://github.com/Automattic/wp-calypso/tree/master/packages/typography).

2020-09-11 13:27 UTC, lsl commented
Did a bit of work on this in #45581 let me know if all that is ok to push into this, I'm not sure I've done the typography import right so didn't feel too comfortable pushing into this PR directly.

2020-09-14 03:23 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@roo2 please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/886637). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-09-14 08:50 UTC, ramonjd commented
Closing this one in favour of https://github.com/Automattic/wp-calypso/pull/45581

2020-09-14 08:50 UTC, closed without merging