Don't show upsell if a term variant of the upsold product is already owned
Automattic/wp-calypso pull request #45556
Opened 2020-09-10 19:12 UTC by monsieur-z

### Changes proposed in this Pull Request

Let's say you own a product of a specific term (e.g. Backup Daily, monthly). When purchasing another product that upsells it (e.g. Scan), with a different term selected, the upsell is still shown. In this PR, we make sure to not show the upsell in that case.

Note: upselling a product with a superior term is maybe something we'd like to do in the future, but the UI doesn't handle this case well for now.

### Testing instructions

- Select a self-hosted Jetpack site that has no product or plan
- Visit the _Plans_ section with the offer flow enabled
- Try to purchase Scan, with any term
- Verify that you see the upsell for Backup Daily
- Select a site that has Backup Daily, with a monthly term, and go back to the _Plans_ page
- Try to purchase Scan, with a yearly term
- Verify that no upsell is shown
- Do the same with Backup Daily on a yearly term, and Scan on a monthly term

2020-09-10 20:13 UTC, rcanepa requested changes
For some unknown reason, it didn't work when I tested it having Jetpack Scan yearly on my site. I could see the Jetpack Scan upsell when I followed the Jetpack Backup Daily monthly path. This is what I saw:

![Kapture 2020-09-10 at 17 11 16](https://user-images.githubusercontent.com/3418513/92797858-d43b9d80-f388-11ea-890e-df5fc6a3f751.gif)

2020-09-10 20:15 UTC, rcanepa commented
The approach is great. I think we may be able to re-use what you did here to accomplish 1169247016322522-as-1191532836382393. Basically, that ticket calls for having a way to switch between terms of the same product, e.g., `jetpack_scan` to `jetpack_scan_monthly` and vice versa.

2020-09-11 20:11 UTC, monsieur-z commented
Up for review again.

2020-09-11 20:29 UTC, rcanepa commented on client/my-sites/plans-v2/use-has-product-upsell.ts
> +export default function useHasProductUpsell(): ( arg0: ProductSlug ) => boolean {
This is pretty cool.

2020-09-11 20:29 UTC, rcanepa approved these changes
LGTM now!

2020-09-14 13:03 UTC, merged