Masterbar: fix reader unread bubble positioning on mobile
Automattic/wp-calypso pull request #45730
Opened 2020-09-17 13:50 UTC by frontdevde

#### Changes proposed in this Pull Request

* This PR ensures that the reader unread bubble is positioned correctly across mobile viewports.

#### The issue 

Currently in production the reader unread bubble is not positioned correctly across mobile viewports.

|before|after|
|-|-|
|<img width="371" alt="Screenshot 2020-09-17 at 15 49 35" src="https://user-images.githubusercontent.com/1562646/93480109-613ca480-f8fd-11ea-92f7-e954ea277ca7.png">|<img width="377" alt="Screenshot 2020-09-17 at 15 49 20" src="https://user-images.githubusercontent.com/1562646/93480144-6994df80-f8fd-11ea-88b1-ba738e53254f.png">|

#### Testing instructions

* Locally: check out PR, `yarn && yarn start` and visit http://calypso.localhost:3000/
* Calypso.live: visit https://calypso.live/?branch=fix/masterbar-reader-bubble-on-mobile

Compare the masterbar on this branch to the masterbar in production. Ensure that the reader unread bubble is positioned correctly across mobile viewports.

2020-09-17 13:50 UTC, frontdevde commented on client/layout/masterbar/style.scss
> +	// stylelint-disable-next-line scales/font-size
Not changed. Had to disable because the linter wouldn't let me commit otherwise.

2020-09-17 14:53 UTC, cpapazoglou requested changes
Thanks @frontdevde for fixing this! Visually wise it is perfect. There is a glitch though when going to My Sites and switching back to the Reader.

![SS 2020-09-17 at 17 46 42](https://user-images.githubusercontent.com/12430020/93487368-dca65200-f90d-11ea-927a-772de2f501bd.gif)

it seems that using
```
top: calc(50% - 14px);
left: calc(50% - 14px);
``` 

and removing `transform: translate( -14px, -14px );` fixes the problem

2020-09-17 14:56 UTC, obenland commented
I say: Keep it! 😃

2020-09-17 18:05 UTC, frontdevde commented
Thanks for catching that, @cpapazoglou! While hilarious, it's clearly not ideal 😄
I usually prefer to not use `calc()` over already computed values but here it gets us around the transition. Changed! 👍

2020-09-18 11:04 UTC, cpapazoglou approved these changes
Thanks @frontdevde for following up! 🚢 !

2020-09-18 11:05 UTC, merged