Jetpack Cloud: Pricing - carry over url query params to wpcom connect
Automattic/wp-calypso pull request #45887
Opened 2020-09-23 20:44 UTC by elliottprogrammer

### Changes proposed in this Pull Request

TODO: In progress

#### Implementation notes:

TODO: In progress

### Testing instructions

TODO: In progress

Fixes: 1169247016322522-as-1195115733367185/f

2020-09-24 18:26 UTC, monsieur-z commented on client/components/jetpack/card/jetpack-free-card/index.tsx
> +import { QueryArgs } from 'my-sites/plans-v2/types';
You missed the `type` keyword here ;)

2020-09-24 18:28 UTC, monsieur-z commented on client/my-sites/plans-v2/controller.tsx
> +import { Duration, QueryArgs } from 'my-sites/plans-v2/types';
Same comment as above for the `type` keyword.

2020-09-24 18:40 UTC, monsieur-z requested changes
Code looks good and it tests well!

There seems to be one blocker though: in `client/my-sites/plans-v2/details.tsx`, `getPathToDetails` still uses the old function signature.

2020-09-24 18:53 UTC, elliottprogrammer commented on client/components/jetpack/card/jetpack-free-card/index.tsx
> +import { QueryArgs } from 'my-sites/plans-v2/types';
ahh, yes..  awesome, thank you! 👍

2020-09-24 19:16 UTC, elliottprogrammer commented
> There seems to be one blocker though: in `client/my-sites/plans-v2/details.tsx`, `getPathToDetails` still uses the old function signature.

Great catch, thank you! 👍

2020-09-24 19:32 UTC, monsieur-z approved these changes
Code update looks good!

2020-09-28 22:16 UTC, raamdev approved these changes
@elliottprogrammer I ran through testing the affiliate tracking flow and it works as expected. Looks great! 👍

2020-09-29 00:27 UTC, merged