Update browserslist(-useragent) and caniuse-lite
Automattic/wp-calypso pull request #45960
Opened 2020-09-28 14:26 UTC by sgomes

Update `browserslist`, `browserslist-useragent`, `caniuse-lite`, and their dependencies.

#### Changes proposed in this Pull Request

* Update resolved versions of `browserslist`, `browserslist-useragent`, `caniuse-lite`, and their dependencies.
* Remove duplicates.

#### Testing instructions

Smoke-test Calypso and ensure nothing breaks.

2020-09-28 14:45 UTC, sgomes commented
Looks like this PR is breaking the build somehow. Investigating.

2020-09-28 14:50 UTC, sgomes commented
I suspect this is because new syntax is finally making it into the evergreen build, and breaking a later stage of the build process. It's a good thing that the new syntax is making it in, but we'll need to make sure it's supported by every build tool 🙂 Investigating.

2020-09-28 15:14 UTC, sgomes commented
I believe I found the problem. `webpack` depends on `acorn "^6.4.1"`, which doesn't support `?.` and similar syntax. Once this syntax starts making its way past the early stages of the build and into things like the bundle analyzer, things start breaking.

The only solution here seems to be to move to `webpack` 5, which does support newer `acorn` versions.

FYI @Automattic/team-calypso

2020-09-29 10:59 UTC, sgomes commented
I added a selective version resolution, so that webpack's `acorn` resolves to the newer `^7.4.0` version range, rather than the older `^6.4.1` range, which does not support newer syntax.

While it's a major version change, `webpack` seems to work correctly with the newer `acorn` version in my local testing. CI results should confirm that here.

2020-09-29 11:04 UTC, sgomes commented
Looks like there's some breakage. Investigating.

2020-09-29 11:08 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@sgomes please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/907819). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-09-29 11:29 UTC, sgomes commented
Regarding the `wp-desktop` breakage, this branch is still a work in progress and no ready to merge. It will either be fixed or closed.

2020-09-29 12:07 UTC, sgomes commented
Looks like `acorn 7` is fundamentally incompatible with `webpack 4`, due to a breaking change in how dynamic imports are handled. I'll close this branch, as there seems to be no way around upgrading to `webpack 5`.

2020-09-29 12:07 UTC, closed without merging