Build: write the assets-*.json files to the build/ directory
Automattic/wp-calypso pull request #46047
Opened 2020-09-30 13:31 UTC by jsnajdr

Make the Calypso server more self-contained by writing the `assets-*.json` files to the `build/` directory, where the server loads them from, instead of the source directory under `client/server/bundler`.

**How to test:**
Verify that after the `build-client` task, the `assets-*.json` files are in `build/` and that the server can load them at runtime.

Verify also the same thing for the desktop app: after `build-desktop`, the `assets-*.json` files should be in `desktop/build/` and should also be shipped in the app bundle (`Wordpress.com.app` on Mac)

The `assets-evergreen.json` and `assets-fallback.json` files are used by the server to determine which chunks to send to the client when requesting a certain section.

For example, the response for the `/reader` page should include all chunks (JS in `<script>` and CSS in `<link>` tags) that belong to the `entry-main` entrypoint and the `reader` section.

2020-10-01 20:48 UTC, nsakaimbo approved these changes
LGTM! Smoke-tested the Desktop app and also confirmed that the assets are placed in the `build` folder of the application bundle.

<p align="center">
<img width="250" alt="desktop-assets" src="https://user-images.githubusercontent.com/8979548/94861655-df24a380-0405-11eb-8c68-5377b1e0eda0.png">
</p>

2020-10-02 08:22 UTC, tyxla requested changes
Seems like a lot of server tests are failing. Do we need to change the module path in the Jest server tests config?

2020-10-02 10:10 UTC, jsnajdr commented
@tyxla Turns out I forgot to update a filesystem mock for the `assets-*.json` files, which ended up failing the tests with some spectacular error messages coming from inside express.js and Node.js streams. Fixed. Let's see if tests come back green this time.

2020-10-02 11:58 UTC, tyxla approved these changes
Looks great 🚢

2020-10-06 11:26 UTC, merged