Settings: re-enable Anti-spam upsell and update its copy
Automattic/wp-calypso pull request #46156
Opened 2020-10-05 16:07 UTC by rcanepa

#### Changes proposed in this Pull Request

* This upsell was disabled because its copy promoted Jetpack Personal which is a plan we don't offer anymore. This PR re-enables the upsell and update its copy.

#### Implementation notes

* Clicking the upsell redirects users to the Plans page and adds `&plan=jetpack_security_daily` to the URL. Currently, we are not handling that parameter so I won't do anything. However, in the future we expect to do something with it (maybe highlight the plan/product card).

#### Testing instructions

* Run this PR.
* Select a site with Jetpack Free that doesn't have Akismet or Jetpack Anti-spam.
* Visit `/settings/security/:site`.
* Verify that you see an upsell (see capture below) in the `Anti-spam` panel.
* Verify that the upsell's copy look like the one in the capture.
* Click the upsell.
* Verify that you end up in the Plans page.
* Do the same with a site that has either Jetpack Security or Jetpack Complete.
* Verify that you don't see the upsell.

Fixes 1196341175636977-as-1196942190681387

#### Demo
![image](https://user-images.githubusercontent.com/3418513/95103914-9aea1980-070b-11eb-8158-39ee8abf6835.png)

2020-10-05 16:17 UTC, a8ci18n commented on client/my-sites/site-settings/spam-filtering-settings.jsx
> +					'Save time, get more responses, give your visitors a better experience - all without lifting a finger.'
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **24** times:
`translate( 'Automatically clear spam from comments and forms. Save time, get more responses, give your visitors a better experience – all without lifting a finger.' )` *ES Score: 7*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/improve/anti-spam-upsell-copy)

2020-10-05 16:17 UTC, a8ci18n commented on client/my-sites/site-settings/spam-filtering-settings.jsx
> +				title={ translate( 'Automatically clear spam from comments and forms' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Automatically clear spam from comments and forms.' )` *ES Score: 11*

2020-10-05 16:42 UTC, rcanepa commented on client/my-sites/plans-v2/utils.ts
> +import { getFeatureByKey, getFeatureCategoryByKey } from 'lib/plans/features-list';
Fix the circular import error (temporarily I guess?).

2020-10-05 16:49 UTC, a8ci18n commented on client/my-sites/site-settings/spam-filtering-settings.jsx
> +				title={ translate( 'Automatically clear spam from comments and forms' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Automatically clear spam from comments and forms.' )` *ES Score: 11*

2020-10-06 13:27 UTC, monsieur-z requested changes
The upsell looks great and the code as well. I noticed 2 things:
- the upsell is still shown for a site with Anti-spam
- the upsell briefly appears before disappearing for a site that includes Anti-spam (e.g. Complete). It should probably be hidden while site purchases are being fetched.

2020-10-06 16:23 UTC, rcanepa commented
> The upsell looks great and the code as well. I noticed 2 things:
> 
> * the upsell is still shown for a site with Anti-spam

I can't reproduce this issue. Could it be that the site you used to test this had the Akismet plugin deactivated or not installed at all? Since Jetpack Anti-spam relies on Akismet under the hood, we check for the existence of the Akismet plugin. The other check is about verifying whether the Jetpack Anti-spam feature is present in the site's plan.

> * the upsell briefly appears before disappearing for a site that includes Anti-spam (e.g. Complete). It should probably be hidden while site purchases are being fetched.

I noticed also that there is an odd state in which the `FoldableCard` appears empty because the data is still being fetched. I included in the check whether we are requesting the site's plan.

2020-10-06 19:00 UTC, monsieur-z commented
> I can't reproduce this issue. Could it be that the site you used to test this had the Akismet plugin deactivated or not installed at all? Since Jetpack Anti-spam relies on Akismet under the hood, we check for the existence of the Akismet plugin. The other check is about verifying whether the Jetpack Anti-spam feature is present in the site's plan.

@rcanepa, I used a brand new JN site and added Anti-spam through the store admin. 
<img width="947" alt="Screen Shot 2020-10-06 at 2 58 45 PM" src="https://user-images.githubusercontent.com/1620183/95247974-96ddfa80-07e4-11eb-840a-e57b792ec836.png">

<img width="943" alt="Screen Shot 2020-10-06 at 2 58 28 PM" src="https://user-images.githubusercontent.com/1620183/95247971-96456400-07e4-11eb-998d-8181620efea7.png">

2020-10-06 21:38 UTC, rcanepa commented
> @rcanepa, I used a brand new JN site and added Anti-spam through the store admin.

@monsieur-z I think I know what's going on. I don't know exactly why, but the provisioning process is not quite the same when you purchase the product through the UI as it's when you do it in Store Admin. In one case you'll end up with Akismet activated and working while in the other you won't. That's why it was showing the upsell for you.

I updated the PR to check for Jetpack Anti-spam as product. Before we were only checking for Jetpack Anti-spam and Akismet as features. Now the upsell shouldn't appear if the site has Jetpack Anti-spam regardless the state of the Akismet plugin.

2020-10-06 21:39 UTC, rcanepa commented on client/my-sites/site-settings/spam-filtering-settings.jsx
> +	const isStoredKey = wordpress_api_key === currentAkismetKey && !! wordpress_api_key;
Since `wordpress_api_key` could be an empty string, we don't want to set `isStoredKey` as true in this case.

2020-10-06 21:40 UTC, rcanepa commented on client/my-sites/site-settings/spam-filtering-settings.jsx
> +	const inTransition = isRequestingSettings || isSavingSettings || isRequestingSitePurchases;
Wait for the site purchases before showing anything.

2020-10-06 21:40 UTC, rcanepa commented on client/my-sites/site-settings/spam-filtering-settings.jsx
> +	}
If things are loading, don't show anything.

2020-10-06 21:45 UTC, rcanepa commented on client/my-sites/site-settings/spam-filtering-settings.jsx
> +	if ( ! ( hasAkismetFeature || hasAntiSpamFeature || hasJetpackAntiSpamProduct ) ) {
Only show the upsell if the site doesn't have any of the following: Akismet as a feature, Jetpack Anti-spam as feature, or Jetpack Anti-spam as a product.

2020-10-21 13:52 UTC, monsieur-z approved these changes
LGTM! I don't know if that's something we still want to do, but with the old flow it should probably redirect to the Personal (or Business?) plan.

2020-10-23 19:34 UTC, rcanepa commented
> LGTM! I don't know if that's something we still want to do, but with the old flow it should probably redirect to the Personal (or Business?) plan.

Good question. Since the new approach doesn't explicitly mention any plan and it takes users directly to the checkout, it would work also in the old flow. For that reason, I'll leave as it is.

2020-10-23 19:34 UTC, rcanepa commented
Rebased to solve conflicts.

2020-10-23 19:57 UTC, merged

2020-10-23 20:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5029139

Thank you @rcanepa for including a screenshot in the description! This is really helpful for our translators.

2020-11-04 12:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5029139).