Revert "Layout: AsyncLoad GdprBanner in LayoutLoggedOut"
Automattic/wp-calypso pull request #46213
Opened 2020-10-06 19:18 UTC by klimeryk

Reverts Automattic/wp-calypso#46133

Looks like it might the culprit behind https://github.com/Automattic/wp-calypso/issues/46206 and https://github.com/Automattic/wp-calypso/issues/46211

2020-10-06 19:21 UTC, griffbrad approved these changes
Thanks for picking up the revert. Looks good.

2020-10-06 19:25 UTC, merged

2020-10-06 19:37 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@klimeryk please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/917779). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-10-07 06:57 UTC, tyxla commented
Thanks for the revert @klimeryk! Who would have thought such a change would have such an avalanche effect!

2020-10-07 10:42 UTC, klimeryk commented
Indeed! This is a really fascinating case of unintended side-effects.