Jetpack Search: enable on all WP.com sites
Automattic/wp-calypso pull request #46220
Opened 2020-10-06 20:30 UTC by gibrown

#### Changes proposed in this Pull Request

* Allow purchases on private wp.com sites (simple and atomic)
* Clean up and simplify the purchase code a bit.
* Allow canceling JPS on Atomic sites without contacting support
* Rewrite and update the settings code and upgrade nudge

#### Testing instructions

* TBD

2020-10-07 00:44 UTC, gibrown commented
@rcanepa more of an fyi since you had just been changing the settings code in https://github.com/Automattic/wp-calypso/pull/46163. This uses the same language for both jetpack and wp.com sites.

2020-10-07 00:56 UTC, bluefuton commented on client/my-sites/site-settings/search.jsx
> +								{ translate( 'Replace WordPress built-in search a higher performance query.' ) }
Missing "with".

2020-10-07 01:02 UTC, bluefuton commented
"eplace WordPress built-in search with a higher performance query" seems a bit techie.

How about "Speed up WordPress built-in search with Jetpack" or similar? (Shall we ask for a copy review?)

2020-10-07 22:32 UTC, jsnmoon requested changes
Everything appears to work as expected, except one exception: Trying to purchasing Jetpack Search via `/purchase-product/jetpack_search/monthly` doesn't work. Pressing `Get Search` puts the page into a loading state indefinitely.

EDIT: Full repro steps:
1. Navigate to /purchase-product/jetpack_search/monthly.
2. Enter a simple or private simple site URL.
3. Click Get Search.
4. Interface gets stuck in the loading state indefinitely.

2020-10-07 23:53 UTC, jsnmoon approved these changes

2020-10-08 17:39 UTC, merged

2020-10-08 18:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4885619

Thank you @gibrown for including a screenshot in the description! This is really helpful for our translators.

2020-10-19 13:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4885619).