Fix a bug in the new checkout e2e tests
Automattic/wp-calypso pull request #46233
Opened 2020-10-07 09:46 UTC by hambai

I needed to run the e2e tests locally against my local environment so I can test some backend change but they failed. Finally I think I found the issue (though I'm not sure why it works that way). Seems like when I'm running the e2e tests locally they use the new checkout flow and the payment button selector selects the disabled "waiting..." button. Anyway - here's a fix for that.

#### Changes proposed in this Pull Request

* Fix the selector for the new checkout payment button

#### Testing instructions

* Run the signup e2e tests against locally running Calypso

2020-10-07 15:57 UTC, sirbrillig approved these changes
Sounds good to me. I'm surprised we didn't notice this before. Thank you for tracking that down.

2020-10-07 15:59 UTC, sirbrillig commented
Although... I notice that now a bunch of e2e tests are failing. 🤔

2020-10-07 16:08 UTC, sirbrillig requested changes
It seems like this should work just fine, but it causes other e2e tests to fail. I'll try to go over this today and figure out why.

2020-10-07 23:04 UTC, sirbrillig commented
Ah, I think I know what the issue is. In new checkout, when you're editing an existing cart, you go into a sort of "edit cart mode" where you have to click "Save order" before you can continue. While in that mode, the payment submit button is disabled.

In tests like `Viewing a specific plan with coupon`, we edit the cart to remove a product. However, the test code wasn't closing the edit mode, so the submit button was not active. I'm pushing some commits that should help make these tests more accurate.

2020-10-07 23:44 UTC, sirbrillig approved these changes
Ok, this works for me now. If all the tests also pass for you and on this PR, then :shipit:

2020-10-09 18:14 UTC, hambai commented
> Ok, this works for me now. If all the tests also pass for you and on this PR, then :shipit:

@sirbrillig The tests fail though and I have no idea how it's supposed to work... Seems like it's stuck on "enter your billing information" in the new checkout flow with this error:
```
         Can then see the secure payment page with the expected currency in the cart:
     TimeoutError: Timed out waiting for element with css selector of '.credit-card-payment-box button.is-primary:not([disabled]),.composite-checkout .checkout-submit-button button:not([disabled])' to be present and displayed
Wait timed out after 40122ms
      at /Users/hambai/www/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:842:17
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

2020-10-09 19:09 UTC, sirbrillig commented
Ok, in this case the issue is that some tests want to inspect the button even if it's inactive.

As I was going about fixing it, it seems like the easiest thing is just to undo the change you initially added, which makes me wonder: what was the failing test you were seeing that inspired this PR in the first place?

2020-10-12 11:11 UTC, hambai commented
> what was the failing test you were seeing that inspired this PR in the first place?

Oh sorry - here're the details. I was trying to run the e2e tests against my local Calypso build in order to actually verify that moving the backend from OpenSRS OTE to Key Systems OTE would work. But the tests failed with a bunch of errors like this one:
```

  [WPCOM] Sign Up  (mobile, en)
    Sign up for a domain only purchase coming in from wordpress.com/domains in EUR currency @signup
      ✓ We can visit set the sandbox cookie for payments (555ms)
      ✓ Can visit the domains start page (2370ms)
      ✓ Can select domain only from the domain first choice page (3426ms)
      ✓ Can then enter account details (1304ms)
      ✓ Can then see the sign up processing page which will finish automatically move along (6612ms)
      ✓ Can see checkout page and enter registrar details (6602ms)
      ✓ Can then see the secure payment page with the correct products in the cart (57ms)
      1) Can then see the secure payment page with the expected currency in the cart
FAILED: Taking screenshot of: 'http://calypso.localhost:3000/checkout/no-site?signup=1&isDomainOnly=1'
      - Can enter/submit test payment details
      - Can open the sidebar
      - We should only see one option - the settings option
There was an error in the hooks that clean up the test account but since it is cleaning up we really don't care: 'TimeoutError: Timed out waiting for element with css selector of '.sidebar' to be present and displayed
Wait timed out after 22114ms'


  7 passing (1m)
  3 pending
  1 failing

  1) [WPCOM] Sign Up  (mobile, en)
       Sign up for a domain only purchase coming in from wordpress.com/domains in EUR currency @signup
         Can then see the secure payment page with the expected currency in the cart:

      AssertionError [ERR_ASSERTION]: The payment button text 'Please wait…' does not contain the expected currency symbol: '€'
      + expected - actual

      -false
      +true

      at Context.<anonymous> (specs/wp-signup-spec.js:830:12)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Which I traced back to the `paymentButtonText` thing. I have no idea why that doesn't fail in the TeamCity runs but I assumed that it's a timing issue or something... Or maybe we're running a different test set in TeamCity? Anyway - can you actually run the tests locally?

2020-10-12 22:43 UTC, sirbrillig commented
🤔  Interesting! I ran those tests locally and they passed, but it may be that we're running them differently. I'm guessing from your description that you ran them with `calypsoBaseURL` set to `calypso.localhost:3000`? 

Here's what I tried:

```
➜ env BROWSERSIZE=desktop ./node_modules/.bin/mocha --grep "Sign up for a domain only purchase coming in from wordpress.com/domains in EUR currency" specs/wp-signup-spec.js

  [WPCOM] Sign Up  (desktop, en)
    Sign up for a domain only purchase coming in from wordpress.com/domains in EUR currency @signup
      ✓ We can visit set the sandbox cookie for payments (335ms)
      ✓ Can visit the domains start page (2391ms)
      ✓ Can select domain only from the domain first choice page (875ms)
      ✓ Can then enter account details (2357ms)
      ✓ Can then see the sign up processing page which will finish automatically move along (6724ms)
      ✓ Can see checkout page and enter registrar details (4563ms)
      ✓ Can then see the secure payment page with the correct products in the cart (187ms)
      ✓ Can then see the secure payment page with the expected currency in the cart (182ms)
      ✓ Can enter/submit test payment details (25392ms)
      ✓ Can open the sidebar (22339ms)
      ✓ We should only see one option - the settings option (113ms)
```

If I instead run them on calypso.localhost, I get the same error you got, but it's misleading. The error happens because the credit card payment method is not available. This is because when visiting checkout on calypso.localhost your store API must be sandboxed since Stripe test mode requires a server-side change. (You can see this yourself if you manually try to use checkout on calypso.localhost without sandboxing the store.)

2020-10-12 22:56 UTC, sirbrillig commented
If I try to sandbox the API while running the tests on localhost, I get a different error:

```
      ✓ Can see checkout page and enter registrar details (11835ms)
      ✓ Can then see the secure payment page with the correct products in the cart (123ms)
      1) Can then see the secure payment page with the expected currency in the cart
FAILED: Taking screenshot of: 'http://calypso.localhost:3000/checkout/no-site?signup=1&isDomainOnly=1#step2'
      - Can enter/submit test payment details
      - Can open the sidebar
      - We should only see one option - the settings option
There was an error in the hooks that clean up the test account but since it is cleaning up we really don't care: 'TimeoutError: Timed out waiting for element with css selector of '.is-section-reader' to
 be present and displayed
Wait timed out after 20022ms'


  7 passing (1m)
  3 pending
  1 failing

  1) [WPCOM] Sign Up  (desktop, en)
       Sign up for a domain only purchase coming in from wordpress.com/domains in EUR currency @signup
         Can then see the secure payment page with the expected currency in the cart:

      AssertionError [ERR_ASSERTION]: The cart total '$12.50' does not begin with '€'
```

I'm not sure about that one. It might have something to do with the currency being set by geo IP? I didn't see anywhere during the signup process that the currency was set to EUR.

It's interesting that your test failure differed from both of mine. I wonder how your setup differs?

2020-10-12 23:21 UTC, sirbrillig commented
>       AssertionError [ERR_ASSERTION]: The payment button text 'Please wait…' does not contain the expected currency symbol: '€'

Thinking about this some more, you're right that this text implies that the form is still loading while it's looking for the currency. I wish I could reproduce this to work on it. The challenge is that the payment button may sometimes display "Please wait" and then change to the correct text, but still be disabled. That's why the tests on this PR are currently failing. 

I pushed a change that might handle both our situations. We'll see.

2020-10-13 04:33 UTC, sirbrillig commented
Ok, the test that's failing now on this PR is

```
23:40:56     Sign up for a site on a personal paid plan coming in via /create as personal flow in GBP currency @signup
23:41:00       ✓ We can set the sandbox cookie for payments (487ms)
23:41:01       ✓ Can visit the start page (1439ms)
23:41:02       ✓ Can see the account details page and enter account details (953ms)
23:41:07       ✓ Can then see the domains page and can search for a blog name, can see and select a free WordPress.com blog address in results (5120ms)
23:41:16       ✓ Can then see the sign up processing page which will finish automatically move along (8980ms)
23:41:39       1) Can then see the secure payment page with the expected currency in the cart
23:41:39       - Can then see the secure payment page with the expected products in the cart
```

And the screenshot shows the problem:

<img width="581" alt="Screen Shot 2020-10-13 at 12 18 26 AM" src="https://user-images.githubusercontent.com/2036909/95815049-e3946a80-0ce9-11eb-946f-92b75dcc2a23.png">

It's looking for the currency on the button but the button is not active because the contact details haven't been filled out. I pushed another change to try waiting for the "Please wait" to be finished. Let's see if that does it.

2020-10-14 20:28 UTC, hambai commented
Sorry I didn't respond earlier... I really am not sure what's happening here. Is it possible that because calypso.local is running over http stripe doesn't show up correctly. I have the "Live Stripe.js integration must use HTTPS" in one of the screenshots I got while running the tests. But when I visit calypso.local in my browser I can't see that error?

2020-10-14 21:41 UTC, sirbrillig commented
> But when I visit calypso.local in my browser I can't see that error?

You won't see that error if your API is sandboxed, but you should see it if not.

2021-05-05 17:04 UTC, sirbrillig commented
Seems like this is pretty important but maybe it was already fixed somehow? We should find out.

2022-07-04 16:14 UTC, worldomonation commented
I'm casually doing some repo gardening on older Selenium issues and PRs and think we can close this one out, as we've moved on from using Selenium/WebDriverJS in favor of Playwright.

2025-06-17 06:40 UTC, closed without merging