Plans: support free products in the JetpackProductCard
Automattic/wp-calypso pull request #46373
Opened 2020-10-12 20:31 UTC by rcanepa

#### Changes proposed in this Pull Request

* Add support for free products.
* Hardcode Jetpack CRM price at -1 (to enable the free price section).

#### Implementation notes

* I will address the technical debt in a follow-up.

#### Testing instructions

* Run this PR (any environment).
* Visit the Plans page.
* Verify that the Jetpack CRM card looks like the capture below.

Fixes 1196341175636977-as-1198189456928808

#### Demo
![image](https://user-images.githubusercontent.com/3418513/95787763-8b8d4200-0cb0-11eb-8141-1285182e6166.png)
![image](https://user-images.githubusercontent.com/3418513/95787776-947e1380-0cb0-11eb-8234-9bc325bc8f6c.png)
![image](https://user-images.githubusercontent.com/3418513/95787817-a5c72000-0cb0-11eb-8075-44cd206cd2b0.png)

2020-10-12 20:31 UTC, rcanepa commented on client/components/jetpack/card/jetpack-product-card-alt/index.tsx
> -	hidePrice?: boolean;
In this new version of the Plans grid, all products feature their prices, so we no longer need this property.

2020-10-12 20:32 UTC, rcanepa commented on client/my-sites/plans-v2/product-card-alt/index.tsx
> +		: null;
This doesn't belong here. In a follow-up PR I'll make sure to put this in the right place.

2020-10-12 20:32 UTC, rcanepa commented on client/my-sites/plans-v2/use-item-price.ts
> +		originalPrice = -1;
For now, -1 is going to mean that the product is free.

2020-10-12 21:25 UTC, eeeeevon13 requested changes
Please make the word free "semi bold" (it should match the thickest font in the price) also change the wording on the button to read "Start using CRM for free" 
<img width="251" alt="Screen Shot 2020-10-12 at 4 24 29 PM" src="https://user-images.githubusercontent.com/49159284/95791713-8d9ed300-0ca7-11eb-8c12-66ac403f034f.png">

2020-10-12 21:42 UTC, rcanepa commented
Thanks @eeeeevon13 ! I have updated the PR with the following changes:

- Make the Free word bolder (use the same font-weight the rest of the prices use).
- Update the CTA copy.

2020-10-12 22:14 UTC, robertf4 approved these changes
As long as there is a followup PR to address the mentioned technical debt, LGTM!

2020-10-12 22:43 UTC, rcanepa commented
I actually managed to remove the tech debt right here in this PR.

2020-10-13 13:43 UTC, eeeeevon13 approved these changes
Looks good to me!

2020-10-13 13:44 UTC, keoshi requested changes
Requesting some changes before merging:

- `.plan-price-free__main` should have a `font-weight: 400` and not `600`.
- CRM card should be visible when monthly billing is selected, as mentioned in p1602593660073000-slack-CQXNTE9K9

Everything else looks fantastic!

2020-10-13 14:00 UTC, rcanepa commented
@keoshi , I updated the PR with the following changes: 
- Decrease the `Free` word font-weight to 400.
- Display Jetpack CRM on monthly billing.

2020-10-13 14:06 UTC, keoshi approved these changes
Perfect, @rcanepa ! Thank you.

🚀

2020-10-13 14:21 UTC, merged

2020-10-13 15:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4968765

Thank you @rcanepa for including a screenshot in the description! This is really helpful for our translators.

2020-10-22 09:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4968765).