Clean up old redirect when reader was disabled
Automattic/wp-calypso pull request #46445
Opened 2020-10-14 08:14 UTC by scinos

#### Changes proposed in this Pull Request

* Remove redirect from `/` to `/stats` when reader was disabled. Reader has been enabled in all environments for years.

#### Testing instructions

N/A

2020-10-14 09:06 UTC, tyxla requested changes
Tests are currently failing.

Noting that this redirect is fine to remove, but for a different reason - this redirect is handled by express.js middleware here: https://github.com/Automattic/wp-calypso/blob/master/client/root.js#L48

Also, I'd like to note that the reader is disabled for any of the Jetpack Cloud environments, but this is fine because these environments manually select which sections to enable, and the reader isn't among them: https://github.com/Automattic/wp-calypso/blob/master/config/jetpack-cloud-production.json#L38

2020-10-14 09:06 UTC, tyxla commented on client/server/pages/index.js
> -	app.get( '/', function ( request, response, next ) {
Removing this, we'll also have to remove a test: https://github.com/Automattic/wp-calypso/blob/master/client/server/pages/test/index.js#L1359

2020-10-19 09:23 UTC, jsnajdr commented
> Noting that this redirect is fine to remove, but for a different reason - this redirect is handled by express.js middleware here

Both redirects are very different from each other though. The server one looks at the feature flags and is not really ever used. I agree that it can be removed.

The client one looks at your primary site and redirects to Reader, Home or Stats depending on the site type and whether you have a primary site at all.

It would be somewhat desirable to have that redirect on the server: the browser could start downloading the JS and CSS chunks for the target section a bit earlier, instead of making a roundtrip through the `root` section. That could infinitesimally improve the initial load times 🙂 

But the downside is that to make the redirect decision, the user info from the user bootstrap is not enough. The server code would need to fetch the site info for the primary site with an extra REST request.

Alternatively, the `/me` response could contain some additional properties with the necessary info. For example, it already has a `primary_blog_is_jetpack` flag.

By the way, when this PR made me look at the `client/root.js` code, I spotted a subtle bug there 🙂 Fixing in #46561.

2021-02-03 11:13 UTC, scinos commented
Stale and no plans to work on it in the near future

2021-02-03 11:13 UTC, closed without merging