Nav Unification - fix to allow toggling of sidebar menu sections
Automattic/wp-calypso pull request #46447
Opened 2020-10-14 10:00 UTC by getdave

## Changes proposed in this Pull Request

* Allow for toggling of sidebar menu sections by clicking.
* Don't allow for "selected" state to determine toggle state of menu - rely on triggering the toggle based on the selected state (see the existing `useRef` implementation).

## Testing instructions

* run `yarn && yarn start`
* add `?flags=nav-unification` to the URL

#### On Master 
* Click on `Posts`. See menu expand.
* Click on `Posts` again. See menu remain in expanded state. 

Note it is impossible to toggle open/closed.

#### On this PR

* Click on `Posts`. See menu expand.
* Click on `Posts` again. See menu collapse.
* `Posts` menu item should remain visually "selected".
* Should be able to toggle open/closed `Posts` section at will.
* Should also be able to toggle other sections as per the above.

Fixes https://github.com/Automattic/wp-calypso/issues/46089

2020-10-14 14:14 UTC, frontdevde commented
General question on this:
Does this behavior need a fix or is it a "feature"? I know the current navigation in Calypso allows for toggling the sidebar. 
That said from what I can tell it is currently not possible to toggle sidebar menu sections in wp-admin right now? In terms of unifying the experience, do we prefer the toggle? If so would we want to introduce it to wp-admin as well?

2020-10-14 14:24 UTC, frontdevde approved these changes
General question on this: Does this behavior need a fix or is it a "feature"? I know the current navigation in Calypso allows for toggling the sidebar. That said from what I can tell it is currently not possible to toggle sidebar menu sections in wp-admin right now? In terms of unifying the experience, do we prefer the toggle? If so would we want to introduce it to wp-admin as well? Personally, I like the ability to toggle the sidebar items. 

With that in mind, given that we want sidebar menu items to toggle, this works as expected. LGTM 👍

2020-10-14 15:29 UTC, frontdevde requested changes
Update: Looks like unfortunately this behaviour seems to be a "feature" because it's how wp-admin works.

See related issue https://github.com/Automattic/wp-calypso/issues/46089#issuecomment-708472862

2020-10-21 08:46 UTC, getdave commented
I think it's safe to say the consensus is that we're going with the route proposed in https://github.com/Automattic/wp-calypso/pull/46598

2020-10-21 08:46 UTC, closed without merging