Billing: Add account-level payment methods tab
Automattic/wp-calypso pull request #46545
Opened 2020-10-17 03:55 UTC by michaeldcain

In #46300, we moved the payment methods from the site-level billing history to its own tab. This PR does the same for the account-level view. It additionally makes all of the account-level purchase screens full-width, to both accommodate the number of items in the nav and match the site-level views. If we need to, we can break the width changes into their own PR @fditrapani.

Fixes: #46324 

<img width="1499" alt="payment-methods" src="https://user-images.githubusercontent.com/942359/96327748-20be6c80-100a-11eb-85a9-f023294cb858.png">

<img width="1499" alt="add-card" src="https://user-images.githubusercontent.com/942359/96327757-2d42c500-100a-11eb-968e-47d8b79bc518.png">

**To test:**
- visit `/me/purchases`
- verify that the different screens in this section are all full-width
- verify that "payment methods" exist as a section nav item
- visit "billing history"
- verify that the payment methods are no longer shown below the billing history table
- visit "payment methods"
- verify that your payment methods are shown
- click "add credit card"
- verify that you're taken to the add credit card screen
- verify that clicking back returns you to the payment methods screen
- verify that you can add a new card
- verify that you're returned to the payment methods screen after adding a new card
- verify that the new card shows up in the payment methods screen
- verify that cards can be deleted from the payment methods screen

2020-10-17 04:20 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@michaeldcain please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/926826). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-10-19 13:39 UTC, fditrapani approved these changes
Amazing! I tested this by removing all my payment methods and adding a new one. The new one showed up in checkout when I tried to upgrade my plan. I also tested this at the site-level and added a card on a plan and it all worked.

2020-10-19 18:36 UTC, nbloomf commented
Here are the results of my testing. TL;DR: everything works as expected. I did have a calypso build error when running this locally but it appears not to affect this PR.

- I visited `/me/purchases`; the "Payment Methods" nav item is available and the components are displayed at full width.

![Screen Shot 2020-10-19 at 1 24 43 PM](https://user-images.githubusercontent.com/9310939/96496253-9c890680-120e-11eb-95fc-25879c64432f.png)

- I clicked to navigate to "Billing History". Payment methods are not shown below the billing history table. The component is full width, and definitely shows the billing history for all of my test user's sites.

![Screen Shot 2020-10-19 at 1 27 13 PM](https://user-images.githubusercontent.com/9310939/96496514-f38edb80-120e-11eb-8227-df9c4a6f3909.png)

- I clicked to navigate to "Payment Methods". My payment methods (both cards and PayPal billing agreements) are shown at full width as expected.

- From the payment methods tab, I clicked to add a new credit card and navigated to the add card screen (with the correct "Add Credit Card" header). Clicking back from here (either the browser button or from the header cake) navigated back to the account level payment methods screen. Validation on the add card form works as expected, and after submitting a valid (test) card I was redirected back to the account level payment methods screen. My newly added card appears in the payment methods list, and I can delete cards from the account level component.

2020-10-19 18:36 UTC, nbloomf approved these changes

2020-10-19 18:38 UTC, nbloomf commented
For good measure I also tested the site-level components, and did not see any regressions there.

2020-10-19 20:49 UTC, merged