Extensions: Remove invokeMap usage from WCS order fulfilment
Automattic/wp-calypso pull request #46568
Opened 2020-10-19 12:47 UTC by tyxla

We'll likely all agree that we're using `lodash` far more than we should. Especially, there are cases that can completely be replaced with their native alternatives. One of them is `_.invokeMap()` - it can often be replaced with `.map()` without any additional cost. 

This PR removes the only usage of `invokeMap`.

By removing `invokeMap` lodash usage it will also be removed from all the relevant chunks, making them slightly smaller. Going further with this approach, we might be able to completely remove lodash one day!

#### Changes proposed in this Pull Request

* Remove lodash `invokeMap` in favor of `Array.prototype.map`

#### Testing instructions

* Open a site with WooCommerce and WooCommerce Services (AKA WooCommerce Shipping & Tax) installed, and United States selected as the store country.
* Make sure shipping labels are enabled and configured.
* Make an order.
* Go to the Orders and start fulfilling the order.
* In the "Create shipping labels" modal, input a wrong address that can't be auto verified.
* Try the link to Google Maps and verify it still works the same way as it did before.

cc @timmyc and @c-shultz as I assume they have the best context to test this change.

2020-10-19 13:11 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@tyxla please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/927468). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-10-19 23:26 UTC, timmyc commented
I don't have a good amount of experience in the WooCommerce Services side of things, so I'll defer to @c-shultz on this one.

2020-10-20 18:44 UTC, brezocordero commented
cc: @c-shultz 
Tested the **WooCommerce Shipping and Tax** side of things.
It works the same as before.
After the address can not be verified, the link to Google maps is correct.
![GoogleLink](https://user-images.githubusercontent.com/8002881/96629954-e7bc1b80-12d9-11eb-9598-72fb163a3671.png)


`http://www.google.com/maps/place/fake%20address%2C%20city%2C%20CA%2011111`

2020-10-20 18:58 UTC, c-shultz approved these changes
Looks like we're good on this. Thanks for testing, @brezocordero! 💯

2020-10-21 10:28 UTC, tyxla commented
Thank you, folks 🙌

2020-10-21 10:28 UTC, merged