Jetpack Backup, Jetpack Scan: Standardize upsell look/feel for incompatible sites
Automattic/wp-calypso pull request #46657
Opened 2020-10-21 19:20 UTC by mattgawarecki

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #

2020-10-21 19:23 UTC, mattgawarecki commented on client/assets/images/jetpack/vaultpress-logo.svg
> +<svg width="36" height="40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2.42 8.73S6.05 26.89 17.51 37c.28-.24.55-.5.82-.75l.11-.1.1-.1.3-.29.09-.1.1-.1c.28-.27.55-.55.81-.83l.09-.1.09-.1
This new VaultPress logo doesn't have any of its own padding, so we can line it up better with the other icons using CSS.

2020-10-21 19:25 UTC, mattgawarecki commented on client/components/jetpack/has-vaultpress-switch/index.tsx
> +const productStateImpliesVaultPress = ( productState?: { state?: string; reason?: string } ) => {
I added queries for the Jetpack Scan product state to this component, to cover sites that may only have purchased Scan.

2020-10-21 19:26 UTC, mattgawarecki commented on client/my-sites/backup/wpcom-backup-upsell.tsx
> +			image={ { path: VaultPressLogo } }
This change gives us the same DOM tree as we get for other PromoCard icons, making it easier to style with fewer rules.

2020-10-21 19:27 UTC, mattgawarecki commented on client/my-sites/scan/style.scss
> +.scan .formatted-header.is-left-align {
I added specificity here to avoid a collision with rules for normal formatted headers, and to make it look the same as the Backup page.

2020-10-21 19:28 UTC, mattgawarecki commented on client/my-sites/scan/style.scss
> +.scan__wpcom-ctas {
These two rules are also meant to match the Backup page.

2020-10-22 14:16 UTC, monsieur-z requested changes
The upsells look good for the multi-site and VaultPress scenarios (both in Calypso and Cloud, both on desktop and mobile).

However, I'm seeing a blank section for the regular site (and no error in the console). The Backup only and Scan only scenarios seem to behave similarly. Can you reproduce this on your side?

Another weird thing is that in production, with Backup only, the scan page shows an error instead of the upsell. If it's an easy fix it'd be nice to include it in this PR.
<img width="760" alt="Screen Shot 2020-10-22 at 10 15 37 AM" src="https://user-images.githubusercontent.com/1620183/96884485-8d44cb80-144f-11eb-992b-28867b94175c.png">

2020-10-22 15:36 UTC, mattgawarecki commented
@monsieur-z Good catches 😎 I'll look into these ASAP.

2020-10-22 16:50 UTC, keoshi approved these changes
Design-wise this is looking really good to me. Thanks for all these changes, @mattgawarecki !

2020-10-22 18:11 UTC, monsieur-z approved these changes
LGTM!

2020-10-22 19:46 UTC, mattgawarecki commented
The errors described by @monsieur-z look to be the result of a stale cache. I'll deploy this PR, since it seems to be unrelated.

2020-10-22 19:47 UTC, merged