JITMs: Remove per-site cache and per-page distinction for sidebar_notice
Automattic/wp-calypso pull request #46812
Opened 2020-10-27 14:51 UTC by mreishus

fixes #46809

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

2020-10-27 14:52 UTC, mreishus commented
Need to examine/consider the comments on #46713 as well

2020-10-27 19:48 UTC, mreishus commented
* Includes changes in [#46824 JITM understands both messagePath and messagePathSuffix props]  
* Still needs performance testing
* Still needs write-up + description

2020-10-28 12:50 UTC, jsnajdr approved these changes
Looks good :+1: I'd prefer it over #46824 as it's more complete.

2020-10-28 12:50 UTC, jsnajdr commented on client/my-sites/theme/main.jsx
> +					<AsyncLoad require="calypso/blocks/jitm" messagePath={ 'calypso:theme:admin_notices' } />
This could use the JSX syntax for string props: `messagePath="calypso:..."`

2020-10-28 15:42 UTC, mreishus commented
Just adding Dave so he can see the latest developments when he gets back.  Review is not needed right now

2020-10-28 16:04 UTC, merged

2020-10-28 16:16 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@mreishus please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/936147). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-11-02 11:55 UTC, getdave commented
Wow! So this continued to get more complex. Thanks for handling things whilst I was away. Nice job!

2020-11-02 14:41 UTC, mreishus commented
> Wow! So this continued to get more complex. Thanks for handling things whilst I was away. Nice job!

No prob, you may want to check out my demo recording if you have some extra time: paYJgx-169-p2