Reader Lists: Enable list creation
Automattic/wp-calypso pull request #47028
Opened 2020-11-02 22:45 UTC by jsnmoon

#### Changes proposed in this Pull Request

* Adds a `Create new list` link in the sidebar.
> <img width="269" alt="Screen Shot 2020-11-02 at 3 40 00 PM" src="https://user-images.githubusercontent.com/4044428/97927226-d33c4200-1d21-11eb-9abb-7f2ba426945c.png">

* Tweaks data-layer and state handling to work properly with our ListForm.

#### Testing instructions

* Spin this up locally or enable the `reader/list-management` feature flag in the environment of your choice.
* Ensure that you can see the new `Create new list` link in the Reader sidebar. It should be within the Lists dropdown folder.
* Ensure that clicking the link takes you to a working create form.
* Ensure that creating a list takes you directly to the list edit page (`/read/list/:user/:listSlug/edit`).

2020-11-03 00:46 UTC, bluefuton approved these changes
Lovely. Works well for me 🚢

2020-11-03 13:27 UTC, blowery commented
Tests failed due to bad syntax?

```
[22:44:03]Summary of all failing tests
[22:44:03]FAIL state/reader/lists/test/reducer.js
[22:44:03]  ● Test suite failed to run
[22:44:03]
[22:44:03]    Jest encountered an unexpected token
[22:44:03]
[22:44:03]    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
[22:44:03]
[22:44:03]    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
[22:44:03]
[22:44:03]    Here's what you can do:
[22:44:03]     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
[22:44:03]     • If you need a custom transformation specify a "transform" option in your config.
[22:44:03]     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
[22:44:03]
[22:44:03]    You'll find more details and examples of these config options in the docs:
[22:44:03]    https://jestjs.io/docs/en/configuration.html
[22:44:03]
[22:44:03]    Details:
[22:44:03]
[22:44:03]    SyntaxError: /home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/client/state/reader/lists/test/reducer.js: Unexpected token (289:0)
[22:44:03]
[22:44:03]      287 | 	} );
[22:44:03]      288 | } );
[22:44:03]    > 289 | 
[22:44:03]          | ^

```

2020-11-03 13:28 UTC, blowery commented on client/state/reader/lists/test/reducer.js
> +		test( 'should add a list on creation', () => {
forgot to close the previous test here

2020-11-03 13:28 UTC, blowery commented on client/state/reader/lists/test/reducer.js
> +		test( 'should add a list on creation', () => {
```suggestion
		} );
		
		test( 'should add a list on creation', () => {
```

2020-11-03 13:30 UTC, blowery requested changes
fix the test, then it's gtg

2020-11-03 20:38 UTC, merged

2020-11-03 21:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5110585

Thank you @jsnmoon for including a screenshot in the description! This is really helpful for our translators.

2020-11-19 16:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5110585).