Domain picker & focused launch: UI and data changes
Automattic/wp-calypso pull request #47110
Opened 2020-11-04 17:01 UTC by alshakero

This PR implements the neccessary changes to focused launch and domain picker to have them work together without breaking any other usage of the domain picker.

#### Todo

- [x] Implement the data-store changes needed to get the current domain status of the site.
- [x] Implement the already purchased custom domain UI.
- [x] Only 3 domains are shown (one is the free domain)
- [x] Implement the dynamic steps count (finished steps don't count as steps). Eg if the user has a domain, step lables look like this: (1. Name your site, Your domain, 2. Pick a plan). 
- [ ] Implement the [info tip icon](https://user-images.githubusercontent.com/1083581/97448093-8aa31400-1930-11eb-9c05-9b074619e4a1.png) when the domain is already purchased. 
- [ ] New "domain item" design
- [ ] Show blue highlight for selected domain item

#### Testing instructions - requires sandboxing 

1. In apps/editing-toolkit run `yarn dev --sync`.
2. Sandbox testingfocusedflow.wordpress.com.
3. Visit https://testingfocusedflow.wordpress.com/wp-admin/post-new.php.
4. In console, type `wp.data.dispatch('automattic/launch' ).openFocusedLaunch()`.

Fixes #46862

2020-11-04 17:17 UTC, a8ci18n commented on packages/launch/src/focused-launch/index.tsx
> +											{ stepNumber++ }. { __( 'Confirm your domain', __i18n_text_domain__ ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **7** times:
`translate( '2. Confirm your domain' )` *ES Score: 9*

2020-11-04 17:17 UTC, a8ci18n commented on packages/launch/src/focused-launch/index.tsx
> +							{ stepNumber++ }. { __( 'Confirm your plan', __i18n_text_domain__ ) }
:warning: This change will be queued for retranslation. We'll display the English text until then.

2020-11-05 08:07 UTC, a8ci18n commented on packages/launch/src/focused-launch/summary/index.tsx
> +											{ stepNumber++ }. { __( 'Confirm your domain', __i18n_text_domain__ ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **7** times:
`translate( '2. Confirm your domain' )` *ES Score: 9*

2020-11-05 08:07 UTC, a8ci18n commented on packages/launch/src/focused-launch/summary/index.tsx
> +							{ stepNumber++ }. { __( 'Confirm your plan', __i18n_text_domain__ ) }
:warning: This change will be queued for retranslation. We'll display the English text until then.

2020-11-05 08:08 UTC, razvanpapadopol commented on packages/launch/src/focused-launch/summary/index.tsx
> -						</Link>
The link to `DomainDetails` was probably removed by mistake during merge.

2020-11-05 09:34 UTC, alshakero commented
This is ready for review. I'll leave the last two items to a separate PR. This one grew slightly too big.

2020-11-05 11:11 UTC, tjcafferkey approved these changes
This works for me.

However we don't seem to be doing anything in the `catch` if the resolvers request fails? How will this impact the UI, do you think it's worth creating an issue for?

2020-11-05 12:36 UTC, merged

2020-11-05 12:36 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@alshakero please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/942732). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-11-05 13:00 UTC, razvanpapadopol commented on packages/domain-picker/src/domain-picker/locked-purchased-item.tsx
> +export default LockedPurchasedItem;
This component doesn't seem to have anything to do with `domain-picker` package. We need the exact same UI component also for `plans-grid`.
<img width="520" alt="Screenshot 2020-11-05 at 14 19 11" src="https://user-images.githubusercontent.com/14192054/98242223-cb281080-1f74-11eb-950f-32a9e984e8a5.png">

Created issue https://github.com/Automattic/wp-calypso/issues/47147

2020-11-05 13:16 UTC, razvanpapadopol commented on packages/launch/src/focused-launch/summary/index.tsx
> +									</Tooltip>
There is already a reusable component for this. It needs to be extracted to `@automattic/components`.
https://github.com/Automattic/wp-calypso/issues/45449