Add ectoplasm color scheme (Method A)
Automattic/wp-calypso pull request #47122
Opened 2020-11-04 21:57 UTC by mreishus

One part of #47036
Method B refers to #47103

#### Changes proposed in this Pull Request

* Add ectoplasm color scheme

#### Testing instructions

* Visit /me/account
* Choose ectoplasm and save

To see the wp-admin color scheme, create an atomic site, then visit /wp-admin/profile.php, choose color scheme and save.

Calypso:
![2020-11-04_15-54](https://user-images.githubusercontent.com/937354/98171825-fdbf0400-1eb5-11eb-82c6-17af95880050.png)
Wp-Admin:
![2020-11-04_15-54_1](https://user-images.githubusercontent.com/937354/98171911-15968800-1eb6-11eb-95f3-c7cc1a6f21d7.png)

#### Known Issues

* Big: All lightness values of both primary and accent colors, -10 through -90, are set to the same color.  How do we generate these while maintaining a seamless experience between wp-admin and calypso?  [Here's how color-studio generates them](https://github.com/Automattic/color-studio/blob/master/data/color-definitions.js).

2020-11-05 19:18 UTC, mreishus commented
Listing issues that arise from setting all primary-10 - primary-90 and accent-10 - accent-90 colors to wp-admin highlight color.  (Starting with one and will edit others in)

Hover tab bar - Unreadable text
![2020-11-05_13-16](https://user-images.githubusercontent.com/937354/98286271-5a2f2b80-1f69-11eb-80f2-695960a81ef3.png)
![2020-11-05_13-16_1](https://user-images.githubusercontent.com/937354/98286279-5dc2b280-1f69-11eb-9ca7-e058d9a23223.png)

2020-11-05 21:01 UTC, mreishus commented
So, having all -10 -90 assigned to the same color was causing some issues as illustrated above.  I used color-studio to generate a range of colors and it fixes the issue.

Since we set the sidebar colors exactly, we can make sure that those match wp-admin exactly and don't use the "palette" colors.

in `data/color-definitions.js`
```
    {
      name: 'Ectoplasm Green',
      default: 50,
      specs: {
        hue_start: 70,
        hue_end: 72,
        hue_curve: 'easeOutSine',
        sat_steps: [
          8, 27, 56, 80, 100, 100, 100, 100, 100, 100, 100, 100
        ],
        lum_steps: [
          96, 96, 95, 94, 87, 75.1, 61.6, 49, 40.5, 31, 20, 11
        ]
      }
    }
```
![2020-11-05_15-01](https://user-images.githubusercontent.com/937354/98295868-bef18280-1f77-11eb-9207-22358233d2b4.png)


![2020-11-05_14-56](https://user-images.githubusercontent.com/937354/98295761-96698880-1f77-11eb-814d-cc8265ae22a0.png)
![2020-11-05_14-57](https://user-images.githubusercontent.com/937354/98295765-98334c00-1f77-11eb-8f89-f8d873373b8f.png)
![2020-11-05_14-57_1](https://user-images.githubusercontent.com/937354/98295771-99fd0f80-1f77-11eb-9f54-00065dbeb82b.png)
![2020-11-05_14-58](https://user-images.githubusercontent.com/937354/98295780-9bc6d300-1f77-11eb-9ade-68ce24c72b46.png)
![2020-11-05_14-58_1](https://user-images.githubusercontent.com/937354/98295798-a1241d80-1f77-11eb-8d4a-d46ae7d95305.png)
![2020-11-05_14-58_2](https://user-images.githubusercontent.com/937354/98295801-a2ede100-1f77-11eb-84a5-8ff2c052c69f.png)
![2020-11-05_14-58_3](https://user-images.githubusercontent.com/937354/98295806-a41f0e00-1f77-11eb-9749-009c20c3fb4f.png)
![2020-11-05_14-59](https://user-images.githubusercontent.com/937354/98295809-a5e8d180-1f77-11eb-9ed3-1fd312828597.png)

2020-11-06 14:48 UTC, sixhours requested changes
Took this for a quick spin! I noticed the outline around the help button could be tweaked to use a variation of the green:

<img width="84" alt="Screen Shot 2020-11-06 at 9 03 06 AM" src="https://user-images.githubusercontent.com/2124984/98377196-805cd600-2012-11eb-8102-9ee72f40e2bc.png">

What do you think about adding a darker purple for the top bar border color to give it a little separation from the side nav?

<img width="611" alt="Screen Shot 2020-11-06 at 9 00 57 AM" src="https://user-images.githubusercontent.com/2124984/98377269-99658700-2012-11eb-9df7-fbde042edd00.png">

<img width="705" alt="Screen Shot 2020-11-06 at 9 21 01 AM" src="https://user-images.githubusercontent.com/2124984/98377273-9b2f4a80-2012-11eb-90c4-84ab567c0f10.png">

2020-11-06 15:27 UTC, cpapazoglou requested changes
Thanks @mreishus for wrangling this!
Generally it works as expected. I navigated around and checked the components page! Let's check if we can easily address the following:

Menu Heading should be the same as links or at least vivid enough
![](https://cln.sh/Nf1Tq4+)

2020-11-06 15:32 UTC, cpapazoglou commented
> Took this for a quick spin! I noticed the outline around the help button could be tweaked to use a variation of the green:
> 
> <img alt="Screen Shot 2020-11-06 at 9 03 06 AM" width="84" src="https://user-images.githubusercontent.com/2124984/98377196-805cd600-2012-11eb-8102-9ee72f40e2bc.png">
> 
> What do you think about adding a darker purple for the top bar border color to give it a little separation from the side nav?
> 
> <img alt="Screen Shot 2020-11-06 at 9 00 57 AM" width="611" src="https://user-images.githubusercontent.com/2124984/98377269-99658700-2012-11eb-9df7-fbde042edd00.png">
> 
> <img alt="Screen Shot 2020-11-06 at 9 21 01 AM" width="705" src="https://user-images.githubusercontent.com/2124984/98377273-9b2f4a80-2012-11eb-90c4-84ab567c0f10.png">

@sixhours thanks for chiming in! As it seems all wp-admin color schemes make no distinction between the masterbar and the sidebar in terms of colour or bordering. I agree it would be best, but I am not sure that we should start making changes to already wp-admin defined colour schemes. This would increase maintainability of schemes and make the scope of porting the colour schemes even larger. @davemart-in , @lcollette what is your take on this?

2020-11-06 15:35 UTC, mreishus commented on packages/calypso-color-schemes/src/shared/color-schemes/_ectoplasm.scss
> +    --theme-notification-color: #d46f15; /* Direct from wp-admin */
I'm not sure I understand, these are specific for each theme.  I define them at the top and use them later in the theme file.
One exception is the text color, all of the wp-admin themes use the same text color (so far).

2020-11-06 15:37 UTC, sixhours commented
The /wp-admin version of Ectoplasm shows a border for me:

<img width="287" alt="Screen Shot 2020-11-06 at 10 36 29 AM" src="https://user-images.githubusercontent.com/2124984/98384618-016c9b00-201c-11eb-9313-628add43b107.png">

2020-11-06 16:32 UTC, mreishus commented on packages/calypso-color-schemes/src/shared/color-schemes/_ectoplasm.scss
> +    --theme-notification-color: #d46f15; /* Direct from wp-admin */
We talked about this a little more in IM and discussed a solution :)

2020-11-06 16:40 UTC, cpapazoglou commented
> The /wp-admin version of Ectoplasm shows a border for me:
> 
> <img alt="Screen Shot 2020-11-06 at 10 36 29 AM" width="287" src="https://user-images.githubusercontent.com/2124984/98384618-016c9b00-201c-11eb-9313-628add43b107.png">

Interesting, the core version doesn't have one... It is a wpcom hack. 
![](https://cln.sh/7EysHS+)

That said, I am not sure how we should proceed... `wpcom-admin-bar.css` contains a dozen of overrides.

2020-11-06 17:25 UTC, mreishus commented
### **Variable scope change**
Done.
### **Notification circle color in masterbar:**
Done.
### **Masterbar bottom border color:**
As noted above, it seems like this looks different depending on if you're on atomic or not. I'm okay adding a bottom border since there is already support in it in calypso, and I only have to change one line.  **I've made the change here.**  I guess it ultimately depends on which version of WP we want to be consistent with.
### FAB Outer ring color
It is already based on the green highlight color, but can be hard to tell: 
![2020-11-06_11-21](https://user-images.githubusercontent.com/937354/98395747-527f8d80-2022-11eb-9dae-114c48eaa86a.png)
It doesn't seem too out of line with an existing theme in calypso, like sunset:
![2020-11-06_11-23](https://user-images.githubusercontent.com/937354/98395889-8490ef80-2022-11eb-964b-80aef1feb27d.png)
This one I'm hesitant to change because I'd have to make `--color-primary-dark` lighter, which might affect readability of some text (like the CreditCard code listing change a few posts up)


### **Sidebar top level menu text brightness**
I can do this, (And I have), but I'm wondering if it's the right thing to do.

In calypso, it's normal for the top level menus to have less contrast than the inner menus.  Examples:
![2020-11-06_10-59](https://user-images.githubusercontent.com/937354/98394599-a12c2800-2020-11eb-83ba-eded780d32a4.png)
![2020-11-06_11-00](https://user-images.githubusercontent.com/937354/98394655-b30dcb00-2020-11eb-91f6-0d8afe7eaaec.png)

In wp-admin, I see the outer menus brighter
![2020-11-06_11-15](https://user-images.githubusercontent.com/937354/98395145-71315480-2021-11eb-9cb0-532dc1691800.png)
 
So we have three options for the ports
A (Dimmer outer, conforms to calypso feeling)
![2020-11-06_11-14-bright-inner](https://user-images.githubusercontent.com/937354/98395216-8dcd8c80-2021-11eb-8a3f-4f04ee11f544.png)

B (Dimmer inner, conforms to wp-admin feeling)
![2020-11-06_11-12-bright-outer](https://user-images.githubusercontent.com/937354/98395243-97ef8b00-2021-11eb-88c1-c1c8f7593714.png)

C (Both bright, compromise)
![2020-11-06_11-11-same-bright](https://user-images.githubusercontent.com/937354/98395261-9d4cd580-2021-11eb-8740-ced4349e2bab.png)

What should we go with?  I have "C" pushed right now.

2020-11-06 23:14 UTC, mreishus commented
:man_facepalming: I just realized that these don't work when the nav unification flag is on, because [these overrides](https://github.com/Automattic/wp-calypso/blob/6d4d5f8fa0094aca366a4ed221985a201dbc822e/client/my-sites/sidebar-unified/style.scss#L4-L28) take precedence.  I made a crude fix that re-specifies all the theme variables inside a `.is-nav-unification { }` selector, but will think about a better fix on Monday.

2020-11-09 09:45 UTC, cpapazoglou commented
> 🤦‍♂️ I just realized that these don't work when the nav unification flag is on, because [these overrides](https://github.com/Automattic/wp-calypso/blob/6d4d5f8fa0094aca366a4ed221985a201dbc822e/client/my-sites/sidebar-unified/style.scss#L4-L28) take precedence. I made a crude fix that re-specifies all the theme variables inside a `.is-nav-unification { }` selector, but will think about a better fix on Monday.

Changes in `sidebar-unified/style.scss` will ultimately reside in the default theme `_default.scss` and they will be overridden by each colour-scheme. Till then, I pushed a commit, making your idea DRY. It should be enough.

2020-11-09 09:45 UTC, cpapazoglou approved these changes
Thanks for pushing the changes @mreishus!

LGTM!

2020-11-09 22:03 UTC, merged