Focused Launch: Split Summary into modular Steps
Automattic/wp-calypso pull request #47125
Opened 2020-11-04 23:16 UTC by ciampo

This is going to allow hiding/showing/changing order of the steps

#### Changes proposed in this Pull Request

Refactor `<Summary />` component and split it into different steps. This should help the implementation of the logic to show/hide/sort steps (as highlighted in #46858)

#### Testing instructions

* WIP (compare against production, nothing should change)

2020-11-04 23:26 UTC, a8ci18n commented on packages/launch/src/focused-launch/summary/index.tsx
> +									{ stepIndex }. { __( 'Confirm your domain', __i18n_text_domain__ ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **7** times:
`translate( '2. Confirm your domain' )` *ES Score: 9*

2020-11-04 23:26 UTC, a8ci18n commented on packages/launch/src/focused-launch/summary/index.tsx
> +						{ stepIndex }. { __( 'Confirm your plan', __i18n_text_domain__ ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **7** times:
`translate( '3. Confirm your plan' )` *ES Score: 9*

2020-11-05 11:31 UTC, tjcafferkey requested changes

2020-11-05 11:31 UTC, tjcafferkey commented on packages/launch/src/focused-launch/summary/index.tsx
> +									<Icon icon={ bulb } /> 46.9% of globally registered domains are .com
Is there a reason we aren't translating this?

2020-11-05 11:31 UTC, tjcafferkey commented on packages/launch/src/focused-launch/summary/index.tsx
> +						<Icon icon={ bulb } /> Monetize your site with <strong>WordPress Premium</strong>
Seems like we should be translating this?

2020-11-05 11:31 UTC, tjcafferkey commented on packages/launch/src/focused-launch/summary/index.tsx
>  						Monetize your site with <strong>WordPress Premium</strong>
Seems like we should be translating this?

2020-11-05 11:31 UTC, tjcafferkey commented on packages/launch/src/focused-launch/summary/index.tsx
>  							<Icon icon={ check } /> Accept payments
Seems like we should be translating this?

2020-11-05 11:31 UTC, tjcafferkey commented on packages/launch/src/focused-launch/summary/index.tsx
>  						<strong>46.9%</strong> of globally registered domains are <strong>.com</strong>
Seems like we should be translating this?

2020-11-05 11:31 UTC, tjcafferkey commented on packages/launch/src/focused-launch/summary/index.tsx
>  							<Icon icon={ check } /> Builds brand recognition and trust
Seems like we should be translating this?

2020-11-05 12:38 UTC, ciampo commented
@tjcafferkey The untranslated text was introduced by https://github.com/Automattic/wp-calypso/pull/46784

I already opened a separate issue https://github.com/Automattic/wp-calypso/issues/47057 to keep track of the untranslated text. We should fix these issues in a separate PR and keep the focus of this PR on being just a refactor

2020-11-05 12:44 UTC, alshakero commented
I put these untranslated strings because I was just trying to focus on the layout back then, and instead of lorem ipsum I decided to throw in the original text. I'll work on them later.

2020-11-05 12:45 UTC, tjcafferkey commented
@ciampo okay cool that's fine if we're keeping track of those. I've added a checklist to your original issue to include this referenced file. That might also be worth doing to ensure we don't miss any when we come to close the issue as its description is quite ambiguous. 👍🏻 

Feel free to dismiss my requested changes.

2020-11-05 15:03 UTC, ciampo commented on packages/launch/src/focused-launch/summary/index.tsx
> +	].filter( ( step ) => step !== null ) as ( ( index: number ) => JSX.Element )[];
This is the only difference in behaviour introduced by this PR.

Previously, if the user has a paid domain, the domain step was still rendered together with the other summary steps (but without a "step index" in the title) — see #47110 

With this PR, if the user has a paid domain, the domain step is shown at the top (as a "disabled step"). The remaining "active" steps are shown below.

2020-11-05 15:16 UTC, ciampo commented
Incorporated changes from https://github.com/Automattic/wp-calypso/pull/47110 after it got merged.

PR is ready for a proper review.

@alshakero Please have a close look at this PR, and make sure that all of the changes/fixes that you introduced in #47110 have been kept (with the exception of https://github.com/Automattic/wp-calypso/pull/47125#discussion_r518118936)

This PR splits the summary into steps, which should allow for a more modular approach for the next tasks and for an easier way to define the steps logic required in #46858

2020-11-05 15:59 UTC, alshakero approved these changes
Absolutely love how this is designed. Such a beauty, thank you.

2020-11-05 15:59 UTC, alshakero commented on packages/launch/src/focused-launch/summary/index.tsx
> +	].filter( ( step ) => step !== null ) as ( ( index: number ) => JSX.Element )[];
```suggestion
	// Steps that are not interactive (e.g. user has already selected domain/plan)
	const disabledSteps = hasPaidDomain ? [ renderDomainStep ] : [];

	// Steps that require the user interaction
	const activeSteps = hasPaidDomain
		? [ renderSiteNameStep, renderPlanStep ]
		: [ renderSiteNameStep, renderDomainStep, renderPlanStep ];
```

2020-11-05 16:43 UTC, merged