Nav Unification: introduce Classic Dark as the new default color scheme
Automattic/wp-calypso pull request #47151
Opened 2020-11-05 15:21 UTC by frontdevde

#### Changes proposed in this Pull Request

This PR
* introduces Classic Dark as the new default color scheme
* adds Classic Bright as a copy of the previous default color scheme
* adds missing colors to Classic Blue that were previously inherited from Classic Bright default

Context: 

With the nav unification project we're introducing unified default colors across Calypso and wp-admin. @rickybanister suggested we introduce these colors to Calypso users early via a new default color scheme. The colors in this PR are based on the most recent Navigation Unification, Design Update (see p2-pbAPfg-13V).

Related issue: https://github.com/Automattic/wp-calypso/issues/47135

![new-default-color-scheme](https://user-images.githubusercontent.com/1562646/98258262-f1ec4400-1f80-11eb-982d-8c41b332825f.gif)

#### Testing instructions

* Check out branch locally, `yarn && yarn start`, visit http://calypso.localhost:3000/me/account
* OR use calypso.live link below (easier!)
* Test on a user account that has never had a color scheme set. On this account the new Classic Dark color scheme should show as default now.
* Navigate around Calypso and see if everything looks as expected
* Change color schemes to Classic Bright and Classic Blue and see if those still match what you see in production.

Fixes https://github.com/Automattic/wp-calypso/issues/47135

2020-11-05 15:25 UTC, frontdevde commented
CC'ing all designers involved for design review @sfougnier @lcollette @davemart-in @rickybanister 

Given that this would replace the default color scheme, I'd highly appreciate if y'all could take a look and let me know about any changes we'd want to make. Thank you!

2020-11-05 15:50 UTC, frontdevde commented on packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
> +	--color-masterbar-item-active-background: #23282d;
@sfougnier @lcollette 
These two colors (#333, #23282d) are the exact values from wp-admin. If I understand the new Navigation Unification, Design Update (see p2-pbAPfg-13V) correctly, it seems like for brand consistency we're starting to tweak wp-admin colors a bit too. If so could you let me if these should be replaced with color studio vars and if so which ones? Thank you!

2020-11-05 16:31 UTC, davemart-in commented
> Given that this would replace the default color scheme for everyone that doesn't have color scheme set

If possible, I'd very much prefer to make this swap for everyone who signs up past the timestamp for when we launch this. Otherwise this is going to change the color scheme for hundreds of thousands of customers, perhaps millions with no warning or explanation as to why it happened. 

I know introducing a signup date stamp will introduce complexity on the code side of things, but this is the only real option that I see.

2020-11-05 17:09 UTC, marekhrabe commented
Next steps as I understand them from the meeting:
- let's add this new color scheme to the list of available ones
- add a separate task for the default scheme choice which will happen under TBD contitions (we can repost the start of the discussion from here)

2020-11-06 13:49 UTC, cpapazoglou commented
It seems to me that Classic Dark will be the default for **all users with no specific scheme selected** _after_ nav unification is launched. Till then we can launch it but not make it default. I am not sure we should introduce any signup date timestamp.

2020-11-06 14:11 UTC, cpapazoglou requested changes
Thanks @frontdevde for wrangling this!

Followed the testing instructions and LGTM! 
- Booting calypso with a user with no color scheme selected, defaulted to Classic Dark.
- Navigated around and everything seems good. 
- Changing to Classic Bright or Classic Blue works as expected

Following this comment https://github.com/Automattic/wp-calypso/pull/47151#issuecomment-722488401, I would suggest making Classic Bright the default again and creating a separate file for Classic Dark. When we launch nav unification to 100% of users we can move the Classic Dark styles to the default and remove the separate Classic Dark file.

2020-11-10 09:06 UTC, frontdevde commented
Closing this PR as the approach changed. Will open a new PR to address https://github.com/Automattic/wp-calypso/issues/47266.

2020-11-10 09:06 UTC, closed without merging