Gutenboarding i18n: i18n for domain picker in the launch flow
Automattic/wp-calypso pull request #47178
Opened 2020-11-06 03:07 UTC by p-jackson

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #

2020-11-06 06:52 UTC, andrewserong commented
Nice approach! I ran out of time to test this properly before the end of the day, but I think we'll want to use a similar approach in `@automattic/plans-grid` so that we can get the plans grid & detailed feature comparison to be translated in the launch flow, too.

2020-11-08 22:08 UTC, p-jackson commented
Rebased due to a refactor in the `<FocusedLaunchModal>` component.

The ETK php unit tests are failing. Some chat here () about node versions. The tests passed locally so I think this is just an issue with versioning on CI.

To make running the tests locally was close to what CI does I changed `.wp-env.override.json` to:
```
```

2020-11-10 00:02 UTC, andrewserong requested changes
This is throwing a fatal for me on my sandboxed test site (not sure if I missed something!) Tested in `en` and `fr`, when I click on the launch button I get the following:

![image](https://user-images.githubusercontent.com/14988353/98610234-460d7480-2343-11eb-8d44-db27cdddfb19.png)

The error message is `TypeError: Cannot read property 'Provider' of undefined` at LaunchSidebar `attach-launch-sidebar.tsx:54`. I haven't had a close look to see _why_ the LaunchContext isn't available at that stage though... 🤔

2020-11-10 00:18 UTC, andrewserong commented
Ah, wait, ignore me. Apologies @p-jackson — looks like I needed to rebuild Calypso to get this working, because of the `@automattic/launch` package. So it appears to be working for me in the sandbox now. I also see it needs another rebase due to a conflict with focused-launch/summary/index.tsx.

2020-11-10 02:24 UTC, p-jackson commented
Thanks @andrewserong, an easy rebase thankfully 😌

2020-11-10 04:24 UTC, andrewserong approved these changes
LGTM! Works nicely in the launch flow in the editor, tested with `en`, `fr`, `es` and `zh-tw`. 👍 

Confirmed that the PHP unit tests are passing in my local environment, and that the domains price formatting looks correct in Gutenboarding, too.

Unrelated to this PR, I noticed that there's an HTML entity in the launch flow title at the top right in French. Not sure if this has been logged already?

![image](https://user-images.githubusercontent.com/14988353/98627645-cc887d00-2368-11eb-929f-4635a26d9f02.png)

2020-11-10 07:13 UTC, p-jackson commented
Yes the encoding issue has been reported before
p1603168892409400-slack-CRWCHQGUB?thread_ts=1603159534.397200&cid=CRWCHQGUB

It should be fixed now too I think, so not sure why it still appear broken. Maybe someone on dotorg still needs approve it, but I thought @deBhal said the fix should already be deployed for simple sites. Maybe he knows more?

2020-11-10 21:23 UTC, merged