CRO pricing page i5: Add foldable FAQ's section
Automattic/wp-calypso pull request #47422
Opened 2020-11-13 20:27 UTC by elliottprogrammer

### Changes proposed in this Pull Request

This PR adds a new `FoldableFAQ` component to Calypso and displays a new FAQ section on the Plans page for Calypso (blue) and Cloud(green).

#### Implementation Notes
- I added the new FoldableFAQ component to the Calypso Docs, UI components section located here: 
- http://calypso.localhost:3000/devdocs/design
- Search for "`FoldableFAQ`".
- (You may need to restart your local Calypso build for this to work correctly.  There are some new files that need to be pulled into the build, I think)

### Testing instructions

- Download the PR
- Run both Calypso and Jetpack cloud concurrently
- Select the `i5 - Saas table design` variant of the a/b test `jetpackConversionRateOptimization`
- Visit the _Plans_ page
- In both platforms, check:
    - Verify that the FAQ section is there at the bottom of the page.
    - Verify that the FAQ's are functioning properly. Dropdowns are opening/closing etc..
    - Check that is matches the Figma design (Link in Asana)
    - Check that the new FAQ's are not showing for other a/b variants.

Fixes 1196341175636977-as-1199149328812610

2020-11-13 20:32 UTC, elliottprogrammer commented on client/jetpack-connect/store-footer.tsx
> +	const JetpackFAQComponent = getJetpackCROActiveVersion() === 'i5' ? JetpackFAQi5 : JetpackFAQ;
This is not ideal, will try to deal with this as we know better what we're doing with all these iterations soon.

2020-11-13 20:47 UTC, monsieur-z requested changes
Looking great on desktop! Design is off on mobile though.
<img width="375" alt="Screen Shot 2020-11-13 at 3 46 25 PM" src="https://user-images.githubusercontent.com/1620183/99119634-80874380-25c7-11eb-8f84-475b9a630abd.png">

2020-11-13 20:51 UTC, monsieur-z commented on client/my-sites/plans-features-main/jetpack-faq-i5/index.tsx
> +	const getHelpLink = ( context: string ) => {
This function could benefit from being moved out of the component, so that there's only one instance of it.

2020-11-13 20:53 UTC, elliottprogrammer commented
> Looking great on desktop! Design is off on mobile though.

Doh!  🤦    I was trying to finish in a hurry and totally forgot about mobile! 🤣
Ok thanks!  I'll get it fixed up on mobile 👍

2020-11-16 14:09 UTC, monsieur-z approved these changes
LGTM! 🚢

2020-11-16 14:19 UTC, monsieur-z commented
@elliottprogrammer, as I'm working on adding Track events in the plans page, I realized it would be good to detect collapse/expand events for the FAQ.

2020-11-16 15:11 UTC, elliottprogrammer commented
> @elliottprogrammer, as I'm working on adding Track events in the plans page, I realized it would be good to detect collapse/expand events for the FAQ.

@monsieur-z , Ok yes, adding tracks events now 👍

2020-11-16 15:45 UTC, monsieur-z commented
Thanks @elliottprogrammer! It works well. I encountered this error in the console.
<img width="572" alt="Screen Shot 2020-11-16 at 10 44 06 AM" src="https://user-images.githubusercontent.com/1620183/99274896-dbec4800-27f8-11eb-93ba-f5228cd78c1c.png">

Renaming `faqID` to `faq_id` would probably solve it.

2020-11-16 16:09 UTC, elliottprogrammer commented
> Thanks @elliottprogrammer! It works well. I encountered this error in the console.

Thanks very much for catching this @monsieur-z !  Ok fixed. 👍

2020-11-16 16:44 UTC, merged

2020-11-16 17:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5208058

Thank you @elliottprogrammer for including a screenshot in the description! This is really helpful for our translators.

2020-11-25 12:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5208058).