My home: Remove subheadings
Automattic/wp-calypso pull request #47530
Opened 2020-11-17 21:34 UTC by lcollette

#### Proposed changes

Removing the subheadings on My home to decrease the visual clutter on the screen.

**Before:**
![Screen Shot 2020-11-17 at 1 05 40 PM](https://user-images.githubusercontent.com/181733/99450713-f7795080-28d5-11eb-8540-001bb6a04160.png)

**After:**

![Screen Shot 2020-11-17 at 1 05 20 PM](https://user-images.githubusercontent.com/181733/99450760-0cee7a80-28d6-11eb-98d8-6475d5376a62.png)

#### Testing instructions

- Visit My home as a new user, as a returning user, and on each of our plan types.
- Notice the lack of subheadings.
- Does the screen flow? Is any spacing off?

2020-11-17 21:43 UTC, sixhours requested changes, later dismissed
This does look so much cleaner!

I noticed the bottom spacing between the main card area and the secondary/tertiary cards is off:

<img width="1112" alt="Screen Shot 2020-11-17 at 4 41 42 PM" src="https://user-images.githubusercontent.com/2124984/99454013-d162a900-28f3-11eb-8cba-6d2573639baa.png">

2020-11-18 06:26 UTC, krymson24 commented
@lcollette such a subtle change, but I love it!

Alignment fixed:
<img width="1742" alt="Screen Shot 2020-11-18 at 1 25 06 AM" src="https://user-images.githubusercontent.com/66652282/99493289-f92a2f00-293c-11eb-8148-cd31ff2c9c13.png">

The rest:
<img width="1235" alt="Screen Shot 2020-11-18 at 1 26 10 AM" src="https://user-images.githubusercontent.com/66652282/99493371-17902a80-293d-11eb-9bc7-f8bed5e4125f.png">

2020-11-18 06:27 UTC, krymson24 submitted a review, later dismissed

2020-11-18 06:27 UTC, krymson24 commented on client/my-sites/customer-home/cards/features/stats/index.jsx
> +
Unnecessary space? Not blocking though

2020-11-18 16:48 UTC, rickybanister commented
So much better.

There are some other minor spacing issues, but unrelated to this change:

The height of the stats header area that says 'View' is not as tall as the quick links header. 
The padding in the main card is larger than the rest of the cards, but not enough to feel entirely intentional.

2020-11-27 15:41 UTC, kwight commented
@lcollette Does this need anything else? I've dismissed the stale reviews and approvals so we're fresh again – let us know in Serenity if you need any getting it done 👍

2020-12-07 16:41 UTC, sirbrillig commented
I... think that the rebase might have gotten confused 😅

2020-12-15 21:48 UTC, lcollette commented
@sixhours Might I get a review on this before I merge?

2020-12-15 21:59 UTC, sixhours approved these changes
Looks good! 🚢

2020-12-16 22:33 UTC, merged