Add search to onboarding language picker
Automattic/wp-calypso pull request #47812
Opened 2020-11-26 20:15 UTC by saramarcondes

#### Changes proposed in this Pull Request

* Adds search to the language picker
* Updates the onboarding language picker to use search

#### Testing instructions

* Verify that `/new?flags=gutenboarding/language-picker` (click the language picker in the upper right-hand corner) matches the spec from @olaolusoga and @ollierozdarz here: p9oQ9f-kT-p2
* Verify that search works as expected (it should filter exactly the same as the previous search implementation from the Calypso language picker)
    * You should be able to search in English for any language
    * You should be able to search for any language in the language that you have selected
* Verify that selecting a new language and saving works
* Verify that selecting a new language and dismissing the modal without apply changes does not save the new language selection

2020-11-27 16:07 UTC, yuliyan requested changes
Thank you for working on this, @saramarcondes.

Tested the language picker following your instructions and everything seems to be working as expected, except searching by localized language name, due to `i18nLocale` being removed from `react-i18n` just recently. 

Also noticed that the search bar is missing the border on mobile. Is that expected?
![image](https://user-images.githubusercontent.com/2722412/100467574-5e1f1b00-30db-11eb-947a-685d36ecc9ad.png)

2020-11-27 16:07 UTC, yuliyan commented on client/landing/gutenboarding/onboarding-block/language/index.tsx
> +	const { __, i18nLocale } = useI18n();
`i18nLocale` has been removed in https://github.com/Automattic/wp-calypso/commit/2c8ffc9a6b2a4225cbf9752f16827369b8df37ff. Would it make sense to use `currentUser` instead to get the locale slug?

2020-11-27 16:07 UTC, yuliyan commented on packages/language-picker/src/style.scss
> +		white-space: nowrap;
This seems to be causing the title to overflow out of the screen on mobile.
![image](https://user-images.githubusercontent.com/2722412/100464581-8d7f5900-30d6-11eb-808b-2f33a72dc151.png)

2020-11-27 16:07 UTC, yuliyan commented on packages/language-picker/package.json
> +		"lodash": "4.17.20",
I think it might be better use compatible versions here, i.e. `^4.17.20`. Let's have someone else confirm this.

2020-11-27 16:07 UTC, yuliyan commented on packages/language-picker/src/language-picker.tsx
> +				return lg;
Nitpick: Returning `lg` seems a bit confusing to me. It might be cleaner if it simply returns `true`. What do you think?

2020-11-27 16:07 UTC, yuliyan commented on packages/language-picker/src/language-picker.tsx
> +						onSearchClose={ () =>
Can be memoized with `useCallback`.

2020-11-27 16:07 UTC, yuliyan commented on packages/language-picker/src/language-picker.tsx
> +						onSearchClose={ () =>
Can be memoized with `useCallback`.

2020-11-27 16:36 UTC, saramarcondes commented on packages/language-picker/package.json
> +		"lodash": "4.17.20",
This was a mistake, good catch

2020-11-27 16:46 UTC, saramarcondes commented on client/landing/gutenboarding/onboarding-block/language/index.tsx
> +	const { __, i18nLocale } = useI18n();
I wonder why the compiler didn't catch this to let me know 🤔 I'll update this to use `currentUser`.

2020-11-30 09:24 UTC, yuliyan approved these changes
I left just one small remark, but besides that - LGTM.

2020-11-30 09:24 UTC, yuliyan commented on client/landing/gutenboarding/onboarding-block/language/index.tsx
> +const LOCALIZED_LANGUAGE_NAMES_FALLBACK_LOCALE = 'en';
Let's use `config( 'i18n_default_locale_slug' )` here instead.

2020-11-30 10:28 UTC, tyxla requested changes
Thanks for the solid work here @saramarcondes!

Unfortunately I'm unable to build this locally, and getting this error:

![](https://cldup.com/aruWOtHT89.png)

What can we do to use as little as possible from `lodash`? Use `language.name.normalize("NFD").replace(/[\u0300-\u036f]/g, "")` or something instead of `deburr` and a custom `.filter()` + `some()` or something similar instead of `intersection()`?

2020-11-30 11:33 UTC, yuliyan commented
> Unfortunately I'm unable to build this locally, and getting this error:

Seems like I've skipped running `yarn install` when I tested earlier. Testing again after `yarn install`, I confirm I'm getting the same error.

2020-12-05 16:59 UTC, saramarcondes commented
@tyxla and @yuliyan I'm able to reproduce the error, however I've removed as much of lodash as possible from the `language-picker` and `search` packages and the error persists. Unfortunately the search package depends on lodash's `debounce`. This isn't easily replacable without hand-spinning our own debounce which seems unwise, but I'm open to that if y'all think it is best.

Otherwise, I'm not sure how to fix the issue with the lodash versions. I've checked all the WP scope packages and they are the same versions as elsewhere in the repository. Likewise, the lodash version used by the `search` package is the same as is used by other packages.

Any ideas about how to fix this? I've tried everything I know to try and am officially stuck.

2020-12-07 14:50 UTC, tyxla commented
> @tyxla and @yuliyan I'm able to reproduce the error, however I've removed as much of lodash as possible from the `language-picker` and `search` packages and the error persists. Unfortunately the search package depends on lodash's `debounce`. This isn't easily replacable without hand-spinning our own debounce which seems unwise, but I'm open to that if y'all think it is best.
> 
> Otherwise, I'm not sure how to fix the issue with the lodash versions. I've checked all the WP scope packages and they are the same versions as elsewhere in the repository. Likewise, the lodash version used by the `search` package is the same as is used by other packages.
> 
> Any ideas about how to fix this? I've tried everything I know to try and am officially stuck.

I think we can just revert the lodash dependency changes; unless there's anything I'm missing, I believe we don't need any of those. Reverted those in https://github.com/Automattic/wp-calypso/pull/47812/commits/1685b698b6e140c2664a1d63a5814fa02f54e36a

2020-12-07 15:58 UTC, tyxla commented
> Any ideas about how to fix this? I've tried everything I know to try and am officially stuck.

In https://github.com/Automattic/wp-calypso/pull/47812/commits/d36d25b9772c90e4661eb805160a9fa0a53dd811 I've added the search package as a reference in the TS configuration - I think this should do the job for us. 

Alternatively, I think we should be able to achieve the same thing by declaring `@automattic/search` a dependency for the entire Calypso app, but I generally don't prefer that approach.

2020-12-07 16:00 UTC, a8ci18n commented on packages/language-picker/src/language-picker.tsx
> +						<div className="language-picker-component__languages-label">{ __( 'languages' ) }</div>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **48** times:
`translate( 'Languages', { context: 'Help topic'} )` *ES Score: 10*

2020-12-14 18:06 UTC, saramarcondes commented
> In d36d25b I've added the search package as a reference in the TS configuration - I think this should do the job for us.

Thanks for doing this @tyxla. Why does this fix the lodash error?

2020-12-15 13:15 UTC, tyxla commented
> > In [d36d25b](https://github.com/Automattic/wp-calypso/commit/d36d25b9772c90e4661eb805160a9fa0a53dd811) I've added the search package as a reference in the TS configuration - I think this should do the job for us.
> 
> Thanks for doing this @tyxla. Why does this fix the lodash error?

Actually, this fixed the TS error that I (and calypso.live) was having when attempting to build it. And the lodash revert in https://github.com/Automattic/wp-calypso/commit/1685b698b6e140c2664a1d63a5814fa02f54e36a fixed the lodash issues IIRC.

2020-12-15 13:16 UTC, tyxla approved these changes
I'd suggest rebasing and re-testing quickly before shipping (it's been 10 days since it was rebased), but other than that this LGTM and feels ready to 🚢

2020-12-15 16:59 UTC, merged