Plugin Browser: Move the manage and install buttons
Automattic/wp-calypso pull request #47930
Opened 2020-12-01 19:11 UTC by sixhours

#### Changes proposed in this Pull Request

* We're going to start slowly aligning the current plugin browser experience with new designs as much as we can; my thought is to do this in incremental PRs.
* This PR moves the Install and Manage buttons up next to the page heading, as we do on My Home.
* Adds a subheading to the FormattedHeader (my copy probably needs polish!)

**Before**

<img width="1678" alt="Screen Shot 2020-12-01 at 2 05 55 PM" src="https://user-images.githubusercontent.com/2124984/100785218-582c8100-33de-11eb-93d0-e6e67246fb91.png">

**After**

<img width="1666" alt="Screen Shot 2020-12-01 at 2 05 24 PM" src="https://user-images.githubusercontent.com/2124984/100785249-6084bc00-33de-11eb-8182-c487d59720de.png">

#### Testing instructions

* Switch to this PR 
* Check out `/plugins` on a simple site
* Note visual differences. Make sure the buttons still work! :) 
* Check on mobile device/small screens to make sure there are no visual issues with having the buttons in the header area

2020-12-01 22:45 UTC, blackjackkent approved these changes
LGTM!

FWIW I think the copy sounds fine to me.

2020-12-01 22:52 UTC, krymson24 approved these changes

2020-12-02 15:43 UTC, mmtr requested changes
I think there is a small regression for Jetpack sites and the "install plugin" button gets duplicated after going to the management screen. I also think the "manage plugins" button shouldn't be displayed in this instance.

<img width="982" alt="Screen Shot 2020-12-02 at 16 41 08" src="https://user-images.githubusercontent.com/1233880/100894896-440b8100-34bd-11eb-9015-df1a85b89731.png">

To reproduce:
- Switch to a JP site.
- Go to Tools > Plugins.
- Click on Manage plugins.

2020-12-02 15:47 UTC, mmtr commented
Also noted the Featured section is missing for Jetpack sites, and gets replaced with an empty Recommended section

Before | After
--- | ---
<img width="976" alt="Screen Shot 2020-12-02 at 16 46 06" src="https://user-images.githubusercontent.com/1233880/100895558-fe02ed00-34bd-11eb-9330-fa90821c04b4.png"> | <img width="976" alt="Screen Shot 2020-12-02 at 16 46 12" src="https://user-images.githubusercontent.com/1233880/100895577-01967400-34be-11eb-8adc-aabf346c5013.png">

2020-12-02 15:52 UTC, mmtr commented
The labels are also missing from the buttons when viewed on small viewports:

Before | After
--- | ---
<img width="355" alt="Screen Shot 2020-12-02 at 16 51 07" src="https://user-images.githubusercontent.com/1233880/100896223-b2047800-34be-11eb-856b-49b00a59e6c7.png"> | <img width="389" alt="Screen Shot 2020-12-02 at 16 51 13" src="https://user-images.githubusercontent.com/1233880/100896251-b6c92c00-34be-11eb-994e-e24053eabece.png">

2020-12-02 16:49 UTC, sixhours commented
Aha, I checked on a Jetpack site but it was an external site (not Atomic); completely forgot to check Atomic. I wondered if there were scenarios I was missing. It couldn't be this easy. ;) Will look into all those things and work on this more, thanks @mmtr !

2020-12-02 19:35 UTC, a8ci18n commented on client/my-sites/plugins/main.jsx
> +				<span className="plugins__button-text">{ translate( 'Add plugin' ) }</span>
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2020-12-02 20:32 UTC, sixhours commented
> Also noted the Featured section is missing for Jetpack sites, and gets replaced with an empty Recommended section

This happens on `trunk`, too, so I don't think it's related to these changes: 

<img width="1087" alt="Screen Shot 2020-12-02 at 3 31 11 PM" src="https://user-images.githubusercontent.com/2124984/100927923-89c34c00-34b3-11eb-8bf6-1b8109bf6f8a.png">

2020-12-02 20:45 UTC, sixhours commented
I've fixed the duplicate headers issue for Jetpack and will update the above screenshots to reflect the changes.

Mobile looks pretty rough with two buttons:

<img width="307" alt="Screen Shot 2020-12-02 at 3 43 03 PM" src="https://user-images.githubusercontent.com/2124984/100929179-381bc100-34b5-11eb-97cc-9f99fa18c848.png">

@lcollette @sfougnier @JanaMW27 Do you have thoughts on how we should handle this going forward? Stack the buttons maybe? We're using this pattern on My Home, but with only one button so it's not an issue there.

2020-12-03 08:34 UTC, scottsweb commented
Just took it for a spin, looking good. 

![Screenshot 2020-12-03 at 09 27 46](https://user-images.githubusercontent.com/411945/100983613-d78a9380-3549-11eb-8109-fc8323dae90b.png)

When in the "manage" view, it became a little confusing to see these two buttons together. I am wondering if the first button should be "browse plugins", or alternatively, the second button could become "upload plugin"?

As mentioned above, the recommended section is also empty for me, but that is outside the scope of this PR.

Stacking the buttons at 100% or going 50% 50% with them on the smallest viewports might be nice, but I only seem to get the overflown text at really small sizes (~320px).

2020-12-03 15:19 UTC, sixhours commented
> When in the "manage" view, it became a little confusing to see these two buttons together. I am wondering if the first button should be "browse plugins", or alternatively, the second button could become "upload plugin"?

Great point. I updated the "Add plugin" button to "Browse plugins" since I think that's a more accurate descriptor. :)

2020-12-03 15:30 UTC, a8ci18n commented on client/my-sites/plugins/main.jsx
> +				<span className="plugins__button-text">{ translate( 'Browse plugins' ) }</span>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **28** times:
`translate( 'Browse all plugins', { context: 'button label'} )` *ES Score: 6*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/plugin-button-placement)

2020-12-04 14:59 UTC, mmtr commented
Nice! It looks much better now ❤️ 

> Do you have thoughts on how we should handle this going forward? Stack the buttons maybe?

I think that'd be great. I quickly prototyped something in that direction with the dev tools and it looks great IMO:

<img width="324" alt="Screen Shot 2020-12-04 at 15 57 05" src="https://user-images.githubusercontent.com/1233880/101178642-88c42300-3649-11eb-9af3-f171e7be56f6.png">

2020-12-04 18:31 UTC, blackjackkent commented
+1 for the stacking idea, I think. That looks really nice and clean.

2020-12-04 19:53 UTC, sixhours commented
<img width="400" alt="Screen Shot 2020-12-04 at 2 52 35 PM" src="https://user-images.githubusercontent.com/2124984/101208617-6da0e580-3640-11eb-8588-e390104f4c5b.png">
<img width="409" alt="Screen Shot 2020-12-04 at 2 52 58 PM" src="https://user-images.githubusercontent.com/2124984/101208619-6e397c00-3640-11eb-9099-2c7c1b405c6f.png">

Updated to display buttons in rows for small screen sizes.

2020-12-07 10:07 UTC, mmtr approved these changes

2020-12-08 17:59 UTC, merged