Modularise notices state
Automattic/wp-calypso pull request #48054
Opened 2020-12-04 15:20 UTC by sgomes

This PR is one of many working on modularising state in Calypso. This one handles notices state.

For more details on state modularisation, see the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and p4TIVU-9lM-p2.

Note: I added reviewers that GitHub suggested. Please feel free to ignore the review request or pull in someone else if you're not comfortable reviewing this PR. Thank you!

Fixes #42460.

#### Changes proposed in this Pull Request

* Modularise notices state

#### Testing instructions

Unfortunately, `notices` state gets loaded pretty early on in the boot process, through the email verification page middleware. As such, it's not easy to test the automated loading process, but it should be enough to smoke-test notices functionality in order to ensure that it continues to work correctly. I did so with a cart notification, but there are probably easier methods.

2020-12-04 15:22 UTC, sgomes commented
Note: the linting errors are expected, since I'm modifying the root reducer, which uses linting errors to point out unmodularised state in an attempt to prevent more of it from being created.

2020-12-07 13:12 UTC, tyxla requested changes
This is testing well and the code looks sensible. Nice work 💯 

A couple of things before we ship it:

* With the notices reduxification, you can't just dispatch a raw `NOTICE_CREATE` or `NOTICE_REMOVE` anymore. That's expected, but we need to change the example in https://github.com/Automattic/wp-calypso/blob/trunk/client/state/http/README.md because it will no longer work as shown there. Ideally, we should be using one of the corresponding notice action creators. What do you think?
* The PR needs a rebase.

Finally, can the failing desktop e2e tests be related?

2020-12-07 13:39 UTC, jsnajdr commented
> you can't just dispatch a raw NOTICE_CREATE or NOTICE_REMOVE anymore.

@tyxla What happened to the `NOTICE_CREATE` actions? They can't be dispatched as raw objects, even if I add all the required action field? Does that mean they are thunks now or something like that?

2020-12-07 13:43 UTC, sgomes commented
> > you can't just dispatch a raw NOTICE_CREATE or NOTICE_REMOVE anymore.
> 
> @tyxla What happened to the `NOTICE_CREATE` actions? They can't be dispatched as raw objects, even if I add all the required action field? Does that mean they are thunks now or something like that?

They can still be dispatches as raw objects, but if you're doing that manually you should import from `calypso/state/notices/init` to ensure that state is initialised first. Using the action creator neatly does it for you.

2020-12-07 13:45 UTC, tyxla commented
> > you can't just dispatch a raw NOTICE_CREATE or NOTICE_REMOVE anymore.
> 
> @tyxla What happened to the `NOTICE_CREATE` actions? They can't be dispatched as raw objects, even if I add all the required action field? Does that mean they are thunks now or something like that?

The idea is that if you want to dispatch a `NOTICE_CREATE` action, you should use one of the dedicated action creators, because that will ensure we've loaded the relevant reducer. We can still dispatch them as raw objects if you really need to, you just need to have imported the `state/notices/init` wherever you're doing that.

2020-12-07 13:46 UTC, tyxla commented
Oops, @sgomes beat me to it 😉

2020-12-07 13:48 UTC, sgomes commented
Rebased and modified the docs as per your suggestion, @tyxla!

Waiting for E2E tests to run again, to see if they're still failing.

2020-12-07 13:50 UTC, jsnajdr commented
> you should use one of the dedicated action creators, because that will ensure we've loaded the relevant reducer.

I see, makes perfect sense 🙂 Thank you both for answering.

2020-12-07 13:53 UTC, tyxla commented
> Rebased and modified the docs as per your suggestion, @tyxla!
> 
> Waiting for E2E tests to run again, to see if they're still failing.

Thanks, @sgomes! We can also remove the `NOTICE_CREATE` action type import from the example FWIW 😅

2020-12-07 13:55 UTC, sgomes commented
> > Rebased and modified the docs as per your suggestion, @tyxla!
> > Waiting for E2E tests to run again, to see if they're still failing.
> 
> Thanks, @sgomes! We can also remove the `NOTICE_CREATE` action type import from the example FWIW 😅

Haha, I rely on `eslint` too much, and then miss the obvious in files that don't get linted 😅

2020-12-07 14:00 UTC, tyxla approved these changes
LGTM, thank you 🚢

2020-12-07 14:33 UTC, sgomes commented
The E2E test failures are still here. I see a lot of checkout timeouts, which I think are unrelated, but I've restarted them to see what happens.

2020-12-07 14:42 UTC, sgomes commented
Looks like lots of other PRs and commits to `trunk` are seeing the same E2E failures, so it's likely flakiness. Since @tyxla confirmed this tests well, I'm going to go ahead and merge this.

2020-12-07 14:43 UTC, sgomes commented
Thank you for the review, @tyxla! 👍

2020-12-07 14:43 UTC, merged