Add zoom in/out/reset to WP Desktop View menu
Automattic/wp-calypso pull request #48188
Opened 2020-12-09 21:12 UTC by nsakaimbo

### Description

This PR adds zoom in/out/reset items to the Desktop's `View` menu (also triggered by the global default shortcuts `CMD +` (zoom in), `CMD -` (zoom out) and `CMD 0` (reset zoom). (Note: use `CTRL` instead of `CMD` on Windows/Linux).

<p align="center">
<img width="226" alt="zoom-menu-mac" src="https://user-images.githubusercontent.com/8979548/101687799-3f4c4d00-3a28-11eb-98cb-cba997cfce9a.png">
</p>

### To Test

Build the app locally ([instructions](https://github.com/Automattic/wp-calypso/blob/trunk/desktop/README.md)) or download a built artifact from this PR.

2020-12-09 21:51 UTC, wp-desktop requested changes, later dismissed
WordPress Desktop CI Failure for job "wp-desktop-mac".

@nsakaimbo please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/968841). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2020-12-09 23:55 UTC, codebykat approved these changes
Summing up from Slack DM, this code looks great. We had to handle a couple special cases in Simplenote Electron that you might want to duplicate (here or in a follow-up PR):

Numpad +/- keys ➡️ https://github.com/Automattic/simplenote-electron/pull/2404

Support `ZoomIn` with and without Shift ➡️  https://github.com/Automattic/simplenote-electron/blob/d69d454a2d1f835c909ce2c923ec22477a16b897/desktop/menus/view-menu.js#L132

2020-12-10 00:00 UTC, nsakaimbo commented
Thanks for the review and for pointing out those enhancements, @codebykat!

I amended the default `zoomIn` shortcut in eb2d169524b54cf8bf1bf40ede35c8478c9cf4df, and integrated identical numeric keypad support in eef921c3f4f525f29de701b3862ff0505d704503.

2020-12-10 00:08 UTC, codebykat commented
I didn't build the app to test, but since I wrote this code, I give it a 👍

2020-12-10 00:46 UTC, merged