Plans Page: Display tiered pricing for products that have it
Automattic/wp-calypso pull request #48698
Opened 2021-01-06 20:19 UTC by ChaosExAnima

#### Changes proposed in this Pull Request

* Creates a new selector that leverages the newly exposed pricing tiers in D54957-code.
* Updates product card component to allow "from" and tooltip to be added.
* Links two to show tiers in products that have them.

#### Screenshots
<img width="355" alt="Screen Shot 2021-01-06 at 3 09 25 PM" src="https://user-images.githubusercontent.com/1760168/103815742-d01b4600-5031-11eb-8109-8b780d88126f.png">
<img width="385" alt="Screen Shot 2021-01-06 at 3 04 02 PM" src="https://user-images.githubusercontent.com/1760168/103815743-d0b3dc80-5031-11eb-9ddd-b6965d5e4d58.png">

#### Testing instructions

* Visit either a site's plan page or the standalone version.
* View a product with tiers such as Jetpack Search.
* For a site:
  * Verify that the price is accurate for the site's number of records. 
* For no site:
  * Verify that pricing matches designs and works on smaller screen sizes.
  * Verify link and prices are accurate.

Fixes 1164141197617539-as-1199720441821497.

2021-01-06 20:35 UTC, eeeeevon13 approved these changes
looks good to me

2021-01-07 15:04 UTC, elliottprogrammer requested changes
@ChaosExAnima, loading the plans page _without a site in context_ works and looks great! 👍

But when loading the plans page _with a site in context_ (and the site contains > 100 records), I'm expecting the Search card to display a higher price amount ($8.33) and also show the tool tip with the higher pricing tier and number of records in the site, but instead I'm seeing the lowest pricing tier ($4.17) and without any tooltip showing. 
Can you duplicate? or maybe I'm missing something?

Screenshots:
<img width="964" alt="Markup 2021-01-07 at 09 31 25" src="https://user-images.githubusercontent.com/11078128/103907378-330eea80-50cf-11eb-9adb-4b92ea058f52.png">

<img width="1147" alt="Markup 2021-01-07 at 09 36 55" src="https://user-images.githubusercontent.com/11078128/103907408-3dc97f80-50cf-11eb-928c-4f4786f2ef3f.png">

2021-01-07 16:26 UTC, ChaosExAnima commented
Hey @elliottprogrammer! I believe that's an API issue, not related to this work. I've tested with a blog my friend has that has 400+ posts and it works great. Looking at the site in question, it seems it's had Jetpack Search before but that only indexed ~80 posts, so maybe that's it? I'd recommend checking out what the `/site/[siteid]/products` endpoint returns in your network tools to verify what tier it thinks you are in. Alternatively, feel free to add me to the site and I can investigate! 😄

2021-01-07 16:54 UTC, elliottprogrammer approved these changes
> Looking at the site in question, it seems it's had Jetpack Search before but that only indexed ~80 posts, so maybe that's it? I'd recommend checking out what the /site/[siteid]/products endpoint returns in your network tools to verify what tier it thinks you are in. Alternatively, feel free to add me to the site and I can investigate! 

Yep, thanks for confirming this after I added you to the site. 👍  I'm still going to try to test with a site that returns a response of > 100 records, but in the meantime you said you tested with another site so I trust that it's all good.  LGTM!!  😁

2021-01-07 17:21 UTC, elliottprogrammer commented
Ok yes, I tested with a different site that had 110 records and the Jetpack Search Card showed the price ($8.33) of the higher tier! 🎉 So yep, confirmed, the correct price displays depending on the number of records. 👍 🙂

2021-01-07 18:30 UTC, merged

2021-01-07 19:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5398075

Thank you @ChaosExAnima for including a screenshot in the description! This is really helpful for our translators.

2021-01-15 09:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5398075).