Plans: Add 'you own this product' marker to cards owned on the selected site
Automattic/wp-calypso pull request #48933
Opened 2021-01-14 21:08 UTC by mattgawarecki

#### Changes proposed in this Pull Request

Partially fixes `1196341175636977-as-1199527862646253`.

* Add a 'You own this product' descriptor in place of the price for products the selected site currently owns.

#### Testing instructions

##### Calypso Blue

* Select a site that owns no products and visit the **Plans** page.
* Verify that all prices are displayed as they currently are in production.
* Select a site that owns at least one product listed on the **Plans** page.
* Verify that for each owned product, that product's price is replaced with a line that says "You own this product." See reference mock-up (attached below) to verify the appearance is as expected.

##### Calypso Green

* Follow the same steps as for Calypso Blue, but for scenarios that require a selected site, do the following:
  * Log in with your Jetpack account.
  * Go to `/pricing/:site_slug?site=:site_slug`, where `:site_slug` is your site's URL-safe slug.

#### Screenshot

<img width="353" alt="image" src="https://user-images.githubusercontent.com/670067/104648822-590d2f80-5679-11eb-934b-59bd008977fd.png">

#### Reference mock-up

<img width="229" alt="image" src="https://user-images.githubusercontent.com/670067/104649261-1861e600-567a-11eb-895a-85962990eac6.png">

2021-01-15 13:04 UTC, rcanepa commented
How is ownership defined? What if I own Jetpack Security Daily, should I see the `You own this product` marker on the Jetpack Backup Daily card?

For instance, here is a site I own that has Jetpack Premium. One can see that several product cards have the CTA button labeled as `Manage subscription` which signals, I think, some kind of ownership. Should we include these cases as owned as well?

![calypso localhost_3000_plans_rcanepag-pressable-test1 mystagingwebsite com](https://user-images.githubusercontent.com/3418513/104730422-c9b75900-5718-11eb-9b6e-0025f11bad3a.png)

cc @eeeeevon13

2021-01-15 20:02 UTC, mattgawarecki commented
I've got an update ready to push if needed, which will apply "You own this product" to anything directly owned or included in the current plan. If we really want to go above and beyond, I can also change the copy to "Part of your current plan" for those specific cases.

2021-01-18 12:33 UTC, rcanepa approved these changes
I'm approving it because it does what it's supposed to do. 

@eeeeevon13 did you had a chance to take a look at this?

2021-01-26 15:53 UTC, keoshi requested changes
I have two notes but this is looking good!

1. I have the same concerns that @rcanepa mentioned and I think it's best to be clear about ownership in particular, so your suggestion for the copy @mattgawarecki makes all the sense to me.
2. Have Search in one of my sites and noticed we're still showing the estimation note — we should remove this and the button should line up nicely again:

![image](https://user-images.githubusercontent.com/390760/105868641-4d612780-5fee-11eb-8175-acda164ccb8b.png)

2021-01-26 18:48 UTC, mattgawarecki commented
@keoshi Updated to address feedback 🙂 Can y'all test again?

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/670067/105889848-40373f00-5fd4-11eb-8ec0-8d657b07840f.png">

2021-01-27 09:06 UTC, keoshi approved these changes
This looks excellent. I really like the distinction between `You own this product` and `Part of your current plan` — could be really helpful in transitioning customers from legacy plans to the new offer, or at least make the differences between them extra clear.

For some reason I'm still seeing all the prices in Calypso Green, despite the notices being correctly displayed:

![image](https://user-images.githubusercontent.com/390760/105968238-bbedc600-607e-11eb-859b-9ef1092a020a.png)

I'm using this URL by the way: `https://cloud.jetpack.com/pricing/mutelife.com?site=mutelife.com`

One final thing, for future reference we should update the PR description and screenshots to reflect the latest changes — let me know if I can help with that.

2021-01-27 13:42 UTC, mattgawarecki commented
@keoshi

> For some reason I'm still seeing all the prices in Calypso Green, despite the notices being correctly displayed:
> [ image ]
> I'm using this URL by the way: `https://cloud.jetpack.com/pricing/mutelife.com?site=mutelife.com`

First, just to double-check: sometimes local/testing environments will redirect to `cloud.jetpack.com` when they first load, which would show you a different version of the page than the one in this PR. Are you sure it was that, and not, e.g., `jetpack.cloud.localhost` or `calypso.live`?

Second -- if that *was* a typo and you were looking at the code from this PR, can you walk me through how you got to the pricing page? I wasn't able to reproduce what you show in your screenshot on my own.

> One final thing, for future reference we should update the PR description and screenshots to reflect the latest changes — let me know if I can help with that.

Definitely, can do! 👍

2021-01-27 16:18 UTC, keoshi commented
You're right @mattgawarecki of course. I typed the URL and didn't even notice it. 🤦 

I suspected it was an error on my part and that's why I green lit it above. Don't mind me! :D

2021-01-27 16:50 UTC, merged

2021-01-27 17:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5477081

Thank you @mattgawarecki for including a screenshot in the description! This is really helpful for our translators.

2021-02-05 16:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5477081).