Ensure that we support autorenew management for Titan subscriptions
Automattic/wp-calypso pull request #48961
Opened 2021-01-15 13:38 UTC by daledupreez

#### Changes proposed in this Pull Request

* This adds a check that ensures we show auto-renew management for Titan subscriptions in the purchase/subscription management page

#### Testing instructions

* In terms of setup, make sure you have the following:
   - You have Store Sandbox mode enabled
   - You have a valid Titan (aka Email) subscription
* Navigate to the purchase management page for your subscription (either via Plans -> Billing -> <your purchase> or via Manage -> Domains -> <your domain> -> Manage your email accounts -> Update your billing and payment settings, where the latter path is only accessible if the `titan/phase-2` feature flag is enabled)
* Verify that you can see an autorenew toggle for the subscription
* Confirm that you can enable and disable autorenew via the UI

2021-01-15 13:57 UTC, eltongo commented
I think it may be worth adding some explanation to the dialog that is shown before auto-renew is disabled. I also noticed this with G Suite as well.

Alternatively we may not show this dialog at all.

![image](https://user-images.githubusercontent.com/13062352/104735355-c5536600-5741-11eb-991a-9337c7b0ea63.png)

2021-01-18 08:44 UTC, hambai commented
Yeah, what @eltongo said... This should be done in client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx - I believe we should add a generic `default` option in the `getCopy` method switch statement?

2021-01-18 08:44 UTC, hambai requested changes
let's fix the disabling dialog copy

2021-01-18 10:48 UTC, daledupreez commented
Thanks for the reviews, @eltongo and @hambai!

I've added support  for Titan in the dialog window, and set things up to handle G Suite/Google Workspace as well, but decided the G Suite changes should be handled in a separate PR.

2021-01-18 15:06 UTC, eltongo approved these changes
:shipit:

2021-01-18 18:04 UTC, merged

2021-01-18 19:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5463476

Thank you @daledupreez for including a screenshot in the description! This is really helpful for our translators.

2021-02-01 11:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5463476).