Feat/plans grid copy changes
Automattic/wp-calypso pull request #49397
Opened 2021-01-28 11:34 UTC by ciampo

#### Changes proposed in this Pull Request

* Change copy related to the plans grid

Do not merge this PR until all translations have been completed!

## Testing instructions

### Setup
- prepare your sandbox
- in two separate terminal windows, run:
  - `yarn start` 
  - `cd apps/editing-toolkit && yarn dev --sync`

### Focused Launch

1. Add an _unlaunched_ site created through `/start`to your sandbox
2. Visit `wordpress.com/page/SITE_ID.wordpress.com/home?flags=create/focused-launch-flow`
3. Press "Launch" button, Focused Launch summary view should appear
4. Click on "View all plans" link
  - [ ] Verify that the new copy is correct in the plans details view, according to A/C in #49390

### Step by Step Launch

1. Add an _unlaunched_ site on a _free_ plan created through `/new` to your sandbox
2. Visit `wordpress.com/page/SITE_ID.wordpress.com/home`
3. Press "Launch" button, Step by Step Launch modal should appear.
4. Navigate to the plans step
  - [ ] Verify that the new copy is correct according to A/C in #49390
5. Navigate to the final (checkout) step
  - [ ] Verify that the new copy is correct according to A/C in #49390

### Gutenboarding

1. Visit `/new` and navigate to the plans step
  - [ ] Verify that the new copy is correct in the plans details view, according to A/C in #49390

#### Screenshots

For translators: 

![image](https://user-images.githubusercontent.com/1083581/106131105-87ebd100-6162-11eb-9465-654e32b55f77.png)

![image](https://user-images.githubusercontent.com/1083581/106131180-a651cc80-6162-11eb-95b0-4e9da31bca35.png)

![image](https://user-images.githubusercontent.com/1083581/106131467-ffb9fb80-6162-11eb-8e25-ceed24a76e1f.png)

![image](https://user-images.githubusercontent.com/1083581/106131523-16f8e900-6163-11eb-8ec0-9f1d29428f3a.png)

![image](https://user-images.githubusercontent.com/1083581/106133086-16615200-6165-11eb-8982-ebf9aba74277.png)

Fixes #49390

2021-01-28 11:46 UTC, a8ci18n commented on apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
> +								__( 'per month, billed as %s annually', 'full-site-editing' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **3** times:
`translate( 'per month{{br/}}billed yearly' )` *ES Score: 7*

2021-01-28 11:46 UTC, a8ci18n commented on packages/plans-grid/src/plans-table/plan-item.tsx
> +									: __( 'billed monthly', __i18n_text_domain__ ) ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **28** times:
`translate( 'Billed monthly' )` *ES Score: 14*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/feat/plans-grid-copy-changes)

2021-01-28 12:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5477733

Thank you @ciampo for including a screenshot in the description! This is really helpful for our translators.

2021-02-05 16:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5477733).

2021-02-05 16:56 UTC, ciampo commented on packages/plans-grid/src/plans-table/plan-item.tsx
> +													? fullWidthCtaLabelSelected
Removed unnecessary `sprintf` call, since `fullWidthCtaLabelSelected` doesn't have any placeholder text

2021-02-08 10:04 UTC, StefanNieuwenhuis requested changes
#### Focused Launch - Plans Grid (table variant)
The screenshots for translators don't align with the AC in #49390 and the translations in the code. Can you please update them?

<img width="750" alt="Screenshot 2021-02-08 at 10 49 03" src="https://user-images.githubusercontent.com/12104589/107204342-dae44480-69fc-11eb-8208-8b1ededebfa5.png">

<img width="766" alt="Screenshot 2021-02-08 at 10 46 36" src="https://user-images.githubusercontent.com/12104589/107204346-dc157180-69fc-11eb-998f-d16e87465716.png">

2021-02-08 10:04 UTC, StefanNieuwenhuis commented on apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
> +	const planSummaryCostLabelAnnually = __(
I know that there's a lot of discussion going on about `i8n` and how to implement methods properly, so it's no biggie if it's not possible but can't we "merge" `planSummaryCostLabelAnnually` & `planSummarCostLabelMonthly` into 1 `const` by creating a ternary based on `planProduct.billingPeriod`?

2021-02-08 10:04 UTC, StefanNieuwenhuis commented on packages/plans-grid/src/plans-accordion-item/index.tsx
> +	const planItemPriceLabelAnnually = __( 'billed as %s annually', __i18n_text_domain__ );
Same here (see my previous comment).

2021-02-08 10:04 UTC, StefanNieuwenhuis commented on packages/plans-grid/src/plans-table/plan-item.tsx
> +	const planItemPriceLabelAnnually = __( 'per month, billed as %s annually', __i18n_text_domain__ );
Same here (see comment above)

2021-02-08 10:09 UTC, ciampo commented on apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
> +	const planSummaryCostLabelAnnually = __(
I'm afraid we can't — the whole point of keeping these variables separate is to somehow avoid an optimisation from terser that breaks `i18n` (see p1612522813165500/1612255293.049500-slack-C013QHLF28Y)

2021-02-08 10:10 UTC, ciampo commented on packages/plans-grid/src/plans-accordion-item/index.tsx
> +	const planItemPriceLabelAnnually = __( 'billed as %s annually', __i18n_text_domain__ );
Same as https://github.com/Automattic/wp-calypso/pull/49397/files/2d137c3873faedb724b186c106063d507fabed6c#r571922139

2021-02-08 10:10 UTC, ciampo commented on packages/plans-grid/src/plans-table/plan-item.tsx
> +	const planItemPriceLabelAnnually = __( 'per month, billed as %s annually', __i18n_text_domain__ );
Same as https://github.com/Automattic/wp-calypso/pull/49397/files/2d137c3873faedb724b186c106063d507fabed6c#r571922139

2021-02-08 10:26 UTC, ciampo commented
> The screenshots for translators don't align with the AC in #49390 and the translations in the code. Can you please update them?

@StefanNieuwenhuis I've updated the screenshots, and I've [replied](https://github.com/Automattic/wp-calypso/pull/49397#discussion_r571922139) to your comment —  can you please take another look?

2021-02-08 10:29 UTC, StefanNieuwenhuis commented on apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
> +	const planSummaryCostLabelAnnually = __(
Thanks for elaborating. Makes sense and I hope we find a solution in the future.

2021-02-08 10:32 UTC, StefanNieuwenhuis approved these changes

2021-02-08 10:34 UTC, ciampo commented
On hold until all strings are translated

2021-03-01 09:02 UTC, ciampo commented
@Automattic/i18n There seems to be an issue with the translations on this PR — Everything should already be translated, but I did one last check before merging and found out that the copy is still appearing in english (the same issue was flagged on a different PR, https://github.com/Automattic/wp-calypso/pull/49290#issuecomment-787778243)

Can you help debugging what's the issue?

2021-03-01 19:11 UTC, ciampo commented
@StefanNieuwenhuis, I pushed some changes so that the UI will display the old text until the new text is fully translated. This is necessary for ETK related changes

2021-03-02 16:10 UTC, yansern approved these changes
Tested on Focused Launch & Step By Step Launch. LGTM.

2021-03-03 16:08 UTC, merged