Display a "purchase success" notice in Customer Home
Automattic/wp-calypso pull request #49451
Opened 2021-01-29 06:55 UTC by niranjan-uma-shankar

…sful

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #

2021-01-29 08:38 UTC, a8ci18n commented on client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
> +		return translate( '%(sublabel)s: %(monthlyPrice)s / month × %(monthsPerBillPeriod)s', {
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2021-01-29 15:24 UTC, michaeldcain requested changes
Left a comment about the translation string. Could you also make sure to [add a test](https://github.com/Automattic/wp-calypso/blob/fix%2Fshow-post-purchase-success-notice/client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js#L41) for the new behavior?

2021-01-29 15:24 UTC, michaeldcain commented on client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
> +		return translate( '%(sublabel)s: %(monthlyPrice)s / month × %(monthsPerBillPeriod)s', {
I _think_ that it's actually more common in English to [not have a space before and after the `/`](https://www.grammarly.com/blog/slash/#__lottie_element_2) ([similar example](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/email/titan-mail-quantity-selection/index.jsx#L244)). Could you remove both and add a comment?

2021-01-29 17:32 UTC, sirbrillig commented on client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
> +		return { d: 'purchase-success' };
As already mentioned, since this function is 100% covered by tests, it would be great if you could add a test to cover this new behavior!

2021-02-02 15:56 UTC, a8ci18n commented on client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
> +		return translate( '%(sublabel)s: %(monthlyPrice)s/month × %(monthsPerBillPeriod)s', {
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2021-02-02 16:53 UTC, niranjan-uma-shankar commented
This branch got a bit polluted, so reopened a new PR in https://github.com/Automattic/wp-calypso/pull/49612. Closing this one.

2021-02-02 16:53 UTC, closed without merging