Media Library: Display File Size for Individual Items
Automattic/wp-calypso pull request #49500
Opened 2021-01-30 21:00 UTC by Aurorum

#### Changes proposed in this Pull Request

* Allows users to see the size of each file they upload

#### Testing instructions

You'll need to apply Automattic/jetpack#18637 for this to work!

Visit the Media Library and open a file, then verify that the "File Size" is displayed neatly in the corner which accurately corresponds to the size stated in WP-Admin. 

<img width="1443" alt="Screenshot 2021-01-30 at 20 51 09" src="https://user-images.githubusercontent.com/43215253/106367803-3f3c3f80-633d-11eb-8b99-6a7ef70fa67f.png">

Fixes #49492

cc @sgomes

2021-01-30 21:11 UTC, a8ci18n commented on client/post-editor/media-modal/detail/detail-file-info.jsx
> +						<th>{ this.props.translate( 'File Size' ) }</th>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **141** times:
`translate( 'File size:' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/pull/49500)

2021-02-03 11:46 UTC, jeherve requested changes
You'll probably need to avoid displaying the field when size is set to 0, like when that data is missing (old versions of Jetpack, images missing some metadata for some reason).

2021-02-03 12:05 UTC, Aurorum commented
Fixed, thank you! :)

2021-02-03 12:15 UTC, a8ci18n commented on client/post-editor/media-modal/detail/detail-file-info.jsx
> +				<th>{ this.props.translate( 'File Size' ) }</th>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **141** times:
`translate( 'File size:' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/pull/49500)

2021-03-11 23:40 UTC, obenland commented
@jeherve Would you be available for another review on this one?

2021-03-12 10:38 UTC, jeherve approved these changes
This tests well for me now. 👍

2021-03-12 14:55 UTC, tjcafferkey commented
Hey @Aurorum thank you so much for wrangling this. It appears since the release of your other PR (thank you for that too) there are some conflicts that need to be resolved.

Is this something you have the time to do? Please let me know if not.

2021-03-12 16:28 UTC, Aurorum commented
Hi, those conflicts should be resolved now!

2021-03-12 16:41 UTC, jeherve approved these changes

2021-03-19 12:00 UTC, tjcafferkey commented
@Aurorum would you be able to update this branch with the latest changes from `trunk` please? 

There's some changes to the tests which are needed before we can merge this change.

Thank you!

2021-03-19 15:21 UTC, Aurorum commented
Sure thing, done! :)

2021-03-19 15:30 UTC, jeherve approved these changes

2021-03-19 16:23 UTC, merged

2021-03-19 16:24 UTC, BogdanUngureanu commented
Hey @Aurorum, thank you for your contribution! I've just merged your changes. :)