Nav Unification: Announcement Modal
Automattic/wp-calypso pull request #49593
Opened 2021-02-02 10:40 UTC by tjcafferkey

## Work in progress

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes https://github.com/Automattic/wp-calypso/issues/47049

2021-02-03 14:41 UTC, getdave commented
@tjcafferkey What can I do to _force_ the modal to appear again?

2021-02-03 15:03 UTC, tjcafferkey commented
@getdave one quick way (and the only way I am aware of at the moment) to achieve this would be to open Redux dev tools and dispatch the following action:

```js
{
    type: "PREFERENCES_SET",
    key: "nav-unification-modal-[user_id]",
    value: 0
}
```

Here's a video of me doing the same thing in 2832d-pb

2021-02-03 18:08 UTC, cpapazoglou commented on client/blocks/nav-unification-modal/index.jsx
> +import * as React from 'react';
Minor: I would lean towards `import React from 'react';`

2021-02-03 18:12 UTC, cpapazoglou commented on client/blocks/nav-unification-modal/index.jsx
> +const Page = ( { heading, content, image } ) => {
Good job on abstracting `Page`. Minor: Since it's used from `Modal` would it make sense to move it above?

2021-02-03 18:19 UTC, cpapazoglou commented on client/blocks/nav-unification-modal/style.scss
> +$wpcom-modal-breakpoint: 600px;
Is there any reasoning for `wpcom` in the naming? And if so, would it provide any value documenting it inline?

2021-02-03 18:22 UTC, cpapazoglou requested changes
Thanks @tjcafferkey for working on this 🎉!
I can confirm that:
- the modal shows up on load 
- it doesn't show up if I click "Confirm" in the last slide. 
- doesn't show up for accounts with `nav-unification` disabled or `cloud.jetpack.com`

Generally it seems fine, let's take care though of the breakpoint 600-740 where I see the following

![](https://cln.sh/oJYjqr+)
![](https://cln.sh/es8IVq+)

Maybe it worths switching to the vertical layout for <800px.

Also, left some minor comments inline.

2021-02-04 10:24 UTC, tjcafferkey commented
@cpapazoglou thanks for reviewing! I've resolved all of your concerns 😄 

As for the breakpoint of the modal, I've fixed this with `overflow: hidden;`. I didn't think it warranted using the vertical layout at such a large breakpoint (open to revisiting this again if you think otherwise). Please see the screenshot below for how it looks now.

<img width="677" alt="Screenshot 2021-02-04 at 10 19 10" src="https://user-images.githubusercontent.com/8639742/106879508-216f3180-66d3-11eb-8b4b-0a493dbd2f9f.png">

2021-02-04 10:39 UTC, cpapazoglou commented
> @cpapazoglou thanks for reviewing! I've resolved all of your concerns 😄
> 
> As for the breakpoint of the modal, I've fixed this with `overflow: hidden;`. I didn't think it warranted using the vertical layout at such a large breakpoint (open to revisiting this again if you think otherwise). Please see the screenshot below for how it looks now.
> 
> <img alt="Screenshot 2021-02-04 at 10 19 10" width="677" src="https://user-images.githubusercontent.com/8639742/106879508-216f3180-66d3-11eb-8b4b-0a493dbd2f9f.png">

Thanks for resolving the feedback! I confirm that it works as expected not, 🚢 !

2021-02-04 10:39 UTC, cpapazoglou approved these changes

2021-02-05 10:39 UTC, merged

2021-02-05 11:44 UTC, mmtr commented
Good job here, @tjcafferkey! After seeing this on production, I noted that this may need a few more improvements. See https://github.com/Automattic/wp-calypso/issues/47049#issuecomment-773981967

2021-02-05 11:58 UTC, simison commented on client/blocks/nav-unification-modal/index.jsx
> +	const hasPreferences = useSelector( hasReceivedRemotePreferences );
Would you also need to ensure preferences are queried? 🤔  (There's `QueryPreferences` component.)

2021-02-05 12:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5494918

Hi @tjcafferkey, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `A new way to navigate`
- `Introducing a single site management experience for WordPress.com.`
- `Everything in one place`
- `Manage your entire site from the sidebar, all without ever leaving your dashboard.`
- `Customize the appearance of your navigation from your account settings.`

Thank you in advance!

2021-02-11 09:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5494918).

2021-03-05 18:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5494918).