Jetpack Plans: Make multisite incompatible products disabled.
Automattic/wp-calypso pull request #49892
Opened 2021-02-09 19:59 UTC by elliottprogrammer

### Changes proposed in this Pull Request

This PR makes multisite incompatible products and plans disabled (and translucent) with a message "Not available for multisite WordPress installs"

Multisite incompatible products are all Jetpack Backup and Jetpack Scan products and all _plans_ which include Backup and/or Scan products.

Fixes: 1164141197617539-as-1199895424508971

### Testing instructions

* Checkout and run this PR in both Calypso blue and green concurrently.
* Select a multisite connected site (or create a multisite JN site if you don't already have one in your account)
* Go to the Calypso blue Plans page: `calypso.localhost:3000/plans/:site`
* Verify that all Jetpack products/plans (other than Anti-Spam, Site Search, and CRM Entrepreneur) are disabled (and translucent) and display the message, "Not available for multisite WordPress installs".  (See screenshot below)
* Go to Calypso green Plans page `jetpack.localhost:3001/pricing/:site` and verify the same as above.
* Select a non-multisite site and verify the plans/products are not disabled.

**Calypso green showing disabled multisite products**
![screenshot-jetpack-cloud-localhost-3001-pricing-exact-shrike-jurassic-ninja-1612899781699](https://user-images.githubusercontent.com/11078128/107419175-7c46c580-6ae5-11eb-8772-a8e643c27eb0.png)

2021-02-10 13:47 UTC, rcanepa approved these changes
Code changes look good and the three plans pages work as expected.

Nice job!

2021-02-10 16:54 UTC, keoshi reviewed
This is looking really good and testing flawlessly on my end.

One question I still have is if we should show the buttons at all on unavailable products. In my mind, having them visible makes me feel that I can somehow purchase them, while not having them paints a clearer picture IMO. Pinging @eeeeevon13 for her expert thoughts on this.

Buttons | No buttons
--|--
![image](https://user-images.githubusercontent.com/390760/107542892-94d7de00-6bc0-11eb-9b2d-ee5583287742.png) | ![image](https://user-images.githubusercontent.com/390760/107542878-90132a00-6bc0-11eb-8e06-2d9cf14e3eee.png)

2021-02-10 16:56 UTC, eeeeevon13 commented
@keoshi I think the buttons should go away.

2021-02-10 17:00 UTC, keoshi commented
Two more nitpicks:

- We should probably left-align that piece of text if we end up going with no buttons.
- Can we prevent widows on the new text? Can we join “WordPress installs” rather than having “installs” on its own line?

2021-02-10 17:01 UTC, keoshi requested changes
Let's go without buttons, and do the tiny adjustments mentioned above if possible.

2021-02-11 14:14 UTC, elliottprogrammer commented
@keoshi, yep sounds good!  Thanks for your feedback, great suggestions. I removed the disabled buttons as well as left-aligned and preventWidows on the message. 👍 

<img width="1090" alt="Screenshot on 2021-02-11 at 09-07-34" src="https://user-images.githubusercontent.com/11078128/107647431-255a0100-6c49-11eb-9706-a69bf1194a7f.png">

2021-02-11 14:17 UTC, keoshi approved these changes
This is looking absolutely great!! Thank you, @elliottprogrammer 🙌

2021-02-11 15:04 UTC, merged

2021-02-11 16:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5513308

Thank you @elliottprogrammer for including a screenshot in the description! This is really helpful for our translators.

2021-02-19 17:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5513308).