Set align-items property to flex-end as Safari is stretch as default
Automattic/wp-calypso pull request #49935
Opened 2021-02-10 11:38 UTC by tjcafferkey

#### Changes proposed in this Pull Request

* Specify `align-items: flex-end` for the sake of Safari as their default is `stretch` for the same property.

#### Testing instructions

* Visit the Calypso.live link on Safari
* Remove your user preference via the debug badge (bottom right) for `nav-unification-modal`
* Observe the image aspect ratio in Safari

<table>
<tr>
	<td>Before</td>
	<td>After</td>
<tr>
	<td>
		<img src="https://user-images.githubusercontent.com/8639742/107505109-21b87280-6b94-11eb-93ed-fa00f0cfde81.png" />
	</td>
	<td>
	<img src="https://user-images.githubusercontent.com/8639742/107505127-29781700-6b94-11eb-85bc-383c280c9d2f.png" />
	</td>
</table>

Fixes to https://github.com/Automattic/wp-calypso/issues/49770

2021-02-10 12:33 UTC, tjcafferkey commented
The background color of the image, and that of the area the image sites in appear as different shades of blue. I think this is down to the compression process the image goes through but will look into it.

It might be worth getting some transparent background copies of these images. If you're happy with me doing so I will attempt this myself to avoid additional work for you @sfougnier?

2021-02-10 12:42 UTC, cpapazoglou requested changes
This works on Safari desktop. On iPhone I cannot login (obviously not related to this PR).

What I noticed, is the different background. Can we change it to `#c8d9e8` so that it matches the photo?

![](https://cln.sh/Clf7wJ+)

2021-02-10 13:44 UTC, tjcafferkey commented
@cpapazoglou I'm going to fix this transparency issue in a separate PR now. Do you think we can approve and merge this?

2021-02-10 14:37 UTC, cpapazoglou approved these changes

2021-02-10 14:38 UTC, cpapazoglou commented
LGTM! @sfougnier would you like to give it a spin?

2021-02-10 15:04 UTC, getdave approved these changes
Thanks for following up with this 👍 

I tested this locally in Safari desktop `Version 14.0.3 (16610.4.3.1.4)` and the images looked good to me.

<img width="808" alt="Screenshot 2021-02-10 at 15 02 21" src="https://user-images.githubusercontent.com/444434/107527874-263f5400-6bb1-11eb-9832-9dc44bb5dc6d.png">

@sfougnier FYI on this fix.

2021-02-10 15:04 UTC, getdave commented on client/blocks/nav-unification-modal/style.scss
> +	// Safari default for align-items is stretch
```suggestion
	// Preserve image aspect ratio on Safari (default for align-items is stretch)
```

This provides the "why" for future devs.

2021-02-10 15:34 UTC, tjcafferkey commented on client/blocks/nav-unification-modal/style.scss
> +	// Safari default for align-items is stretch
Thanks. I've just updated that, good shout.

2021-02-10 15:59 UTC, sfougnier commented
Works fine for me on Safari. I'm not sure if there's a more overarching ticket for this, but I have some issues with the typographic padding and the placement of the image on mobile. This should follow the welcome tour in the editor: 

Note the header line height and padding between it and the paragraph text
<img width="1125" alt="Screen Shot 2021-02-10 at 10 55 36 AM" src="https://user-images.githubusercontent.com/67021691/107535238-8ec90980-6b8e-11eb-98d8-f8d36deb21c1.png">

Note the position of the image on mobile
<img width="494" alt="Screen Shot 2021-02-10 at 10 55 40 AM" src="https://user-images.githubusercontent.com/67021691/107535240-8f61a000-6b8e-11eb-8889-eed92b22a25d.png">

Before we push this we need to update the copy and take another look at the image assets. Is there any info you can share with me for the aspect ratio/pixel dimensions for the image on mobile?

2021-02-11 09:09 UTC, tjcafferkey commented
@sfougnier sure, we can address all of those issues not a problem.

The image is beneath the text as that's how it was shown here on the designs 28594-pb

I will fix this in this PR so it's consistent with Whats New, however we can open further issues to address the typography problems.

2021-02-11 10:16 UTC, tjcafferkey commented
Failing E2E tests are unrelated. Merging and deploying.

2021-02-11 10:20 UTC, merged