Update copy
Automattic/wp-calypso pull request #50588
Opened 2021-03-01 14:42 UTC by getdave

Fixes https://github.com/Automattic/wp-calypso/issues/50202

#### Changes proposed in this Pull Request

* Update copy on WPAdmin toggle under Account Settings to better reflect intent of toggle.

#### Testing instructions

*

2021-03-01 15:29 UTC, cpapazoglou commented on client/me/account/main.jsx
> +										}
Something goes wrong here 😜!

2021-03-01 15:30 UTC, cpapazoglou requested changes
❤️ This is failing to build for me ❤️!

2021-03-01 16:08 UTC, cpapazoglou approved these changes

2021-03-01 16:09 UTC, cpapazoglou commented
It works as expected, I will leave it up to Saul for the final call!

2021-03-01 16:16 UTC, getdave commented on client/me/account/main.jsx
> +										}
Ha! Good spot :)

2021-03-01 16:28 UTC, sfougnier commented
> The PR doesn't match the design because the design isn't inline with the current Calypso interface.

Apologies - working fast and must have added an old mock-up.

<img width="741" alt="Screen Shot 2021-03-01 at 11 20 44 AM" src="https://user-images.githubusercontent.com/67021691/109526063-2c25a800-7a80-11eb-9448-d9e9f170a51c.png">

I'm not sure about making "show advanced dashboard pages" as the section label. It becomes a little disassociated with the toggle action. 

<img width="996" alt="Screen Shot 2021-03-01 at 11 26 37 AM" src="https://user-images.githubusercontent.com/67021691/109526822-fdf49800-7a80-11eb-9dd2-6c0f8bf8c82e.png">

Can it be placed back into the toggle with the description text, like so?

2021-03-02 09:31 UTC, getdave commented
> Can it be placed back into the toggle with the description text, like so?

Yes it can! Done. I hope that's more what you were expecting?

2021-03-02 15:19 UTC, sfougnier commented
>  I hope that's more what you were expecting?

Yeah, looking good! Thanks.

2021-03-03 09:56 UTC, getdave commented
Merging based on https://github.com/Automattic/wp-calypso/pull/50588#pullrequestreview-600903831

2021-03-03 09:57 UTC, merged