Help: Style Sibyl results differently
Automattic/wp-calypso pull request #50671
Opened 2021-03-02 20:03 UTC by sixhours

#### Changes proposed in this Pull Request

* Add a prop so we know we're in the Sibyl context when viewing HelpResults.
* Show the icon on the left rather than the right and compact the search result

**Before**

**After**

#### Testing instructions

* Forthcoming

Fixes #50543

2021-03-02 20:57 UTC, sixhours commented
Hey hey @mattwondra 👋 How can I test the Q&A results locally or on wpcalypso? Is there a config variable I need to set?

2021-03-02 21:40 UTC, mattwondra commented
@sixhours It should be on by default in all environments... It's triggered by words in your support request, so if you go to /help/contact and just type the word "css" into the "How can we help?" input, that ought to trigger some suggestions.

2021-03-02 21:42 UTC, sixhours commented
> @sixhours It should be on by default in all environments... It's triggered by words in your support request, so if you go to /help/contact and just type the word "css" into the "How can we help?" input, that ought to trigger some suggestions.

Yay, it worked! I tried "Domains" and I think it worked on production but not in my test environment. 😅 Will test this out and update the PR.

2021-03-02 22:51 UTC, mattwondra requested changes
@sixhours Thanks for picking this up so quickly! I'm still seeing some visual bugs here:

<img width="1065" alt="Screen Shot 2021-03-02 at 4 43 46 PM" src="https://user-images.githubusercontent.com/518059/109725639-0cbd7680-7b77-11eb-89ac-1e2cf9056456.png">

- The text still has `max-width: 65%;` on larger browser widths, causing unnecessary line-wrapping.
- The text should be spaced a little further from the icon.
- The text should probably not be bold.

The second two items look good in the screenshot you dropped on the PR description, but they didn't look like that in the browser at all.

2021-03-03 15:33 UTC, sixhours commented
> @sixhours Thanks for picking this up so quickly! I'm still seeing some visual bugs here:

Helps if I commit the CSS changes rather than leaving them on my local copy. 🙃 But I think I still need to fix the 65% width, will do that now!

2021-03-03 15:38 UTC, sixhours commented
This should be looking much better:

<img width="757" alt="Screen Shot 2021-03-03 at 10 37 08 AM" src="https://user-images.githubusercontent.com/2124984/109830466-85badd80-7c0c-11eb-9e7e-972852221549.png">

2021-03-03 20:57 UTC, mattwondra approved these changes
> Helps if I commit the CSS changes rather than leaving them on my local copy. 

Been there! 😆 

Looking much better! There's still one nitpick I missed earlier: The `h2` and `p` both have margin on them, which is making the space on the bottom of the cards larger than the space on the top. Minor thing, but tightening it up would make it really look polished.

I'd fix it myself but I'm not sure if my solution would cause other visual bugs in other places `< HelpResult>` is used. My best guess is that it makes most sense to:
- Remove the margin on the `h2`
- Add top `margin` on the `p` to space it away from the `h2`
- Only render the `p` if there's actually content in `helpLink.description`

What do you think? Approving because if you think this is worth fixing and take care of it, I'm sure it'll be fine to ship.

Thanks again!

2021-03-05 15:26 UTC, merged

2021-03-17 23:28 UTC, obenland commented
The following CSS rule seems to have unintended side effects on the site picker in https://wordpress.com/help/contact:

  `.help-contact-form .gridicon {
	margin-right: 16px;
}`

![image](https://user-images.githubusercontent.com/1398304/111551475-89d31900-873d-11eb-98aa-d7af8a1c27f9.png)

@sixhours Would you mind doing a follow-up when you get a chance?