Stats: Display Number of "Best Views Ever"
Automattic/wp-calypso pull request #51234
Opened 2021-03-19 15:10 UTC by Aurorum

#### Changes proposed in this Pull Request

I'm not actually sure why the line of code causing the issue was introduced to begin with since it hasn't been touched for several years, but I've hunted around and it doesn't seem to affect anything else, so this should be fine. The value is already here, so I think this definitely was intended to be displayed at some point.

https://github.com/Automattic/wp-calypso/blob/edad5f7ffaba7fbbf84b665ce826850dd5a2b960/client/my-sites/stats/all-time/index.jsx#L108

#### Testing instructions

* Verify that a number appears next to "Best views ever" on the Insights page

<img width="364" alt="Screenshot 2021-03-19 at 15 06 15" src="https://user-images.githubusercontent.com/43215253/111801347-c5e4b600-88c4-11eb-915f-77e01aca1a58.png">

cc @cpapazoglou - sorry for missing this initially!

Related to #51116

2021-03-22 07:49 UTC, cpapazoglou commented
👋 @Aurorum, I am afraid that we have awaken the linters 😢 ! Can you please check the following so that  `ci/circleci: lint —` tests pass? 

```
org.eslint.wpcalypso/jsx-classname-namespace - /home/circleci/wp-calypso/client/my-sites/stats/stats-tabs/tab
line 66, col 26, Error - className should follow CSS namespace guidelines (expected stats-tabs__ or tab__ prefix) (wpcalypso/jsx-classname-namespace)

org.eslint.wpcalypso/jsx-classname-namespace - /home/circleci/wp-calypso/client/my-sites/stats/stats-tabs/tab
line 67, col 26, Error - className should follow CSS namespace guidelines (expected stats-tabs__ or tab__ prefix) (wpcalypso/jsx-classname-namespace)

org.eslint.jsx-a11y/click-events-have-key-events - /home/circleci/wp-calypso/client/my-sites/stats/stats-tabs/tab
line 71, col 4, Error - Visible, non-interactive elements with click handlers must have at least one keyboard listener. (jsx-a11y/click-events-have-key-events)

org.eslint.jsx-a11y/no-noninteractive-element-interactions - /home/circleci/wp-calypso/client/my-sites/stats/stats-tabs/tab
line 71, col 4, Error - Non-interactive elements should not be assigned mouse or keyboard event listeners. (jsx-a11y/no-noninteractive-element-interactions)

org.eslint.wpcalypso/jsx-classname-namespace - /home/circleci/wp-calypso/client/my-sites/stats/stats-tabs/tab
line 80, col 12, Error - className should follow CSS namespace guidelines (expected stats-tabs__ or tab__ prefix) (wpcalypso/jsx-classname-namespace)
```

2021-03-22 07:54 UTC, cpapazoglou commented
I did my own digging too and it seems that the only place where `children` are used
https://github.com/Automattic/wp-calypso/pull/51234/files#diff-7555785d4b8418100519c02a0514903e7a7be6cf2fe15ea6758bef43c0ac163dL36

is in the `all-time` component https://github.com/Automattic/wp-calypso/blob/edad5f7ffaba7fbbf84b665ce826850dd5a2b960/client/my-sites/stats/all-time/index.jsx#L111

It seems safe allowing to show the `value` there.

2021-03-22 08:12 UTC, cpapazoglou requested changes
Works great! Let's just address the lint issues first.

2021-03-22 18:56 UTC, Aurorum commented
The Lint issues appear to be a little more tricky than I hoped! The className ones are straight-forward, but I'm not entirely sure how to resolve the others because it seems like they're inevitable whenever a list is clickable. A couple of other places just disable them, so I've done that too, but I recognise that isn't the most ideal solution - is there something else more preferable?

https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/components/token-field/suggestions-list.jsx#L101-L109

2021-03-23 09:31 UTC, cpapazoglou commented
> The Lint issues appear to be a little more tricky than I hoped! The className ones are straight-forward, but I'm not entirely sure how to resolve the others because it seems like they're inevitable whenever a list is clickable. A couple of other places just disable them, so I've done that too, but I recognise that isn't the most ideal solution - is there something else more preferable?
> 
> https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/components/token-field/suggestions-list.jsx#L101-L109

Thanks for resolving feedback so quick. Yes `onclick` in `li` isn't so good. Let's go on with disabling the rule over there.

2021-03-23 09:33 UTC, cpapazoglou approved these changes

2021-03-23 09:40 UTC, merged