Jetpack: update Backup success image
Automattic/wp-calypso pull request #51310
Opened 2021-03-23 12:43 UTC by keoshi

#### Changes proposed in this Pull Request

* Update the Backup success image to the standard Material icon `cloud_done_24px` instead of using a custom icon.

#### Testing instructions

* Fire up this PR.
* Go to Calypso Green: http://jetpack.cloud.localhost:3000/
* Select a site with a Backup plan, and previous successful backups.
* Ensure you see the new icon.

#### Screenshots

Before | After
--|--
![image](https://user-images.githubusercontent.com/390760/112147791-026e2580-8bd5-11eb-80d1-b960a2d223df.png) | ![image](https://user-images.githubusercontent.com/390760/112147800-0437e900-8bd5-11eb-96c9-79555eb9c7f5.png)

2021-03-24 13:26 UTC, monsieur-z approved these changes
LGTM! You might need to rebase with `trunk` to make the checks pass. I had similar issues recently.

2021-03-24 14:40 UTC, jeffgolenski requested changes

2021-03-24 14:40 UTC, jeffgolenski commented on client/components/jetpack/daily-backup-status/status-card/icons/cloud-success.svg
> +<svg width="50" height="50" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M40.313 20.583C38.895 13.396 32.582 8 25 8c-6.02 0-11.25 3.417-13.854 8.417C4.875 17.083 0 22.396 0 28.833c0 6.896
Do we want `fill="#fff"` inline within the svg code or should we be keeping all style values in the css? Either way the change looks good to me!

2021-03-24 14:52 UTC, keoshi commented on client/components/jetpack/daily-backup-status/status-card/icons/cloud-success.svg
> +<svg width="50" height="50" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M40.313 20.583C38.895 13.396 32.582 8 25 8c-6.02 0-11.25 3.417-13.854 8.417C4.875 17.083 0 22.396 0 28.833c0 6.896
That hasn't changed with this PR and we're already using `fill="#069E08"` for the cloud itself. Plus, we can always override these via CSS if they end up being used in a new scenario where the default values don't work in our favor.

2021-03-26 17:06 UTC, jeffgolenski approved these changes
I hereby deem thee, on this last Friday of March in the year 2021, APPROVED for mergification into the great Jetpack Abyss. Carry forth with your head held high @keoshi. You have done a great service.

2021-03-26 17:29 UTC, merged