SEO: Twitter Preview - Wrap Long Text
Automattic/wp-calypso pull request #51659
Opened 2021-04-02 20:38 UTC by Aurorum

#### Changes proposed in this Pull Request

* Ensures that the "Social Previews" feature wraps text properly for Twitter (I verified that it did with Facebook and Google already)

#### Testing instructions

Verify that the Twitter preview under the SEO tab wraps with a long string, and there is no impact to regular sorts of phrases.

**Before:**
<img width="691" alt="Screenshot 2021-04-02 at 21 32 03" src="https://user-images.githubusercontent.com/43215253/113452082-362e2400-93fb-11eb-9692-3388ab010cef.png">

**After:**
<img width="650" alt="Screenshot 2021-04-02 at 21 31 58" src="https://user-images.githubusercontent.com/43215253/113452091-39c1ab00-93fb-11eb-8c4a-c942101668f2.png">

cc @cpapazoglou
 
Fixes Automattic/jetpack#19396

2021-04-02 20:41 UTC, Aurorum commented
I recognise that this is a very minor change, but looking at #45156, should I update `package.json` and the Changelog too? 
cc @cpapazoglou

2021-04-05 07:21 UTC, jeherve commented
> should I update package.json and the Changelog too?

2021-04-05 10:36 UTC, Aurorum commented
Thank you! I updated both of those. :)

2021-04-05 17:28 UTC, samiff requested changes
Hey @Aurorum 👋 

I'm not seeing quite the same thing on my end, post social preview:

![Screen Shot 2021-04-05 at 11 18 07 AM](https://user-images.githubusercontent.com/15803018/113603108-bb365a80-9600-11eb-84f7-2c821a367cfb.png)

I'm not up to date with CSS Grid, but I wonder if one of those elements needs its width constrained? We'd also want to make sure things look good when previewing from `wordpress.com/marketing/traffic/example.com` since the elements are a bit different:

![Screen Shot 2021-04-05 at 11 24 22 AM](https://user-images.githubusercontent.com/15803018/113603872-b7570800-9601-11eb-8c03-9e0651e5f1c0.png)

2021-04-05 18:03 UTC, Aurorum commented
Hmm, that's strange! I wonder if there's something else causing this, since I can't actually reproduce the issue on the Marketing page presently (even without this change) either on Chrome or Safari. 

<img width="1786" alt="Screenshot 2021-04-05 at 18 52 47" src="https://user-images.githubusercontent.com/43215253/113606626-2e12f600-9640-11eb-8641-0f3aaac36bbd.png">

My "Social Previews" is a bit different too (where this change does fix the issue).

<img width="1992" alt="Screenshot 2021-04-05 at 19 00 21" src="https://user-images.githubusercontent.com/43215253/113607538-37509280-9641-11eb-9800-b71cb7ea7e99.png">

Are you aware if there's a way to get a screen that's more familiar to yours? I can't see anything which is causing the discrepancy, but for what it's worth, I've been trying a WP.com Atomic site and a Jetpack 9.5 one.

2021-04-06 20:10 UTC, samiff commented
@Aurorum Thanks for the screenshots, seems like things behave a bit differently when no Site Icon or featured image on a post is set.

With Site Icon set and your change applied it looks good:

![Markup on 2021-04-06 at 13:52:17](https://user-images.githubusercontent.com/15803018/113771408-8e597480-96e0-11eb-9e53-fd2634b5a4a0.png)

But with no Site Icon, the text runs out:

![Markup on 2021-04-06 at 13:59:20](https://user-images.githubusercontent.com/15803018/113771481-a5986200-96e0-11eb-97cc-79b2899990df.png)

Similarly a post with a featured image set looks good:

![Markup on 2021-04-06 at 13:55:35](https://user-images.githubusercontent.com/15803018/113771536-b8ab3200-96e0-11eb-9abb-aec26122f1aa.png)

And without the image:

![Markup on 2021-04-06 at 13:57:23](https://user-images.githubusercontent.com/15803018/113771573-c5c82100-96e0-11eb-9fa1-a5a582a9a055.png)

> Are you aware if there's a way to get a screen that's more familiar to yours in terms of how the icons are positioned above the preview?

They adjust that way on more narrow viewports, don't think it's related here.

2021-04-06 22:33 UTC, Aurorum commented
Thank you for spotting that! I've added a commit which should resolve it now. Could you please try testing it again?

2021-04-07 20:29 UTC, merged

2021-04-07 20:52 UTC, samiff commented
@Aurorum That worked great for me, thanks for working on it 👍  Change has been merged and deployed 🥳