WIP: Add validation for alternativeEmail. Start with availability
Automattic/wp-calypso pull request #51676
Opened 2021-04-05 13:38 UTC by olaseni

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2021-04-09 14:46 UTC, hambai requested changes
Okay I tested this and it works but I think we should fix the busy state of the Continue button which I believe breaks because of the async `handleContinue`

2021-04-09 14:46 UTC, hambai commented on client/my-sites/email/titan-mail-add-mailboxes/index.jsx
> +	handleContinue = async () => {
I think this breaks the "busy" state of the button and feels a bit off - you click on the button and something is happening but there is no visual feedback

2021-04-13 10:01 UTC, daledupreez reviewed
Functionally, this is working as described, though I have some small suggestions.

I am going to hold off approving until we finalise the API changes.

2021-04-13 10:01 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +					'Please supply an email address on a different domain than {{strong}}%(domain)s{{/strong}}',
I think it would be more helpful to express this using a message more like:
`This email address must be on a different domain. Please use a different email address.`

I think  telling the user that the address must be on a different domain is more explicit.

2021-04-13 10:01 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +		return e.statusCode !== 409;
Should we not check for other 4xx errors?
If we can't add email, the address is technically not available either...

2021-04-13 10:01 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +	! result && onMailboxesChange && onMailboxesChange( mailboxes );
Nit: I'd prefer this to be more explicit.
```suggestion
	if ( ! result && onMailboxesChange ) {
		onMailboxesChange( mailboxes );
	}
```

2021-04-13 10:01 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +const getMailboxRequiredStringOrArrayValue = () =>
Why the additional type? I am also confused because the name doesn't feel accurate, as the string value is still required -- the only array is in the `error` field.

Furthermore, I don't actually see where we're making `error` into an array.

2021-04-13 10:01 UTC, daledupreez commented on client/lib/wpcom-undocumented/lib/undocumented.js
> + * @param emailAddress The ful email address
Nit: typo
```suggestion
 * @param emailAddress The full email address
```

2021-04-13 10:01 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +	mailbox.mailbox.error = translate( '{{strong}}%(email)s{{/strong}} already exists.', {
I think this would be clearer if we simply state the address is already in use (which is different than it already existing). I've also added a comment to the back end API review to make it easier to identify the existing mailbox/forward/group type.
```suggestion
	mailbox.mailbox.error = translate( '{{strong}}%(email)s{{/strong}} is already in use.', {
```
I also think we should add a translator comment to indicate that `email` is a partial email address.

2021-04-13 16:28 UTC, olaseni commented on client/lib/titan/new-mailbox.js
> +const getMailboxRequiredStringOrArrayValue = () =>
The translate function returns an array sometimes i.e. a mix of strings and components which React knows how to render. However when arrays are returned for a string prop a validation error is thrown in the console.

2021-04-13 19:11 UTC, daledupreez approved these changes
Other than the naming issue and fixing the explicit check for `'OK'`, I think this is looking good!

2021-04-13 19:11 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +	const promisified_responses = Promise.all(
Nit that I missed previously: the variable name should be `promisifiedResponses`.

2021-04-13 19:11 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +		return { available: status === 200 && message === 'OK', message, mailbox: mailboxes[ index ] };
We should not rely on `message === 'OK'` here, as that may fail for other languages. I think relying solely on the response code should be enough.

2021-04-13 19:11 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +const getMailboxRequiredStringOrArrayValue = () =>
:TIL: Now I understand why there is a `TranslateResult` type for TypeScript code. It may be worth seeing if you can declare that as the alternate type, TBH.

Regardless, I think the function name is still inaccurate. I'd prefer something like `getMailboxRequiredStringValueWithTranslatedError()` -- as I mentioned previously, the _value_ is not an array.

2021-04-13 19:11 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +					'This email address must be on a different domain than {{strong}}%(domain)s{{/strong}}. Please use a different email address.',
The use of "on a different" domain feels weird to me, though I can't specify why!

It may be worth using something like the following:
```suggestion
					'This email address must use a different domain than {{strong}}%(domain)s{{/strong}}. Please use a different email address.',
```
I know this repeats "use" but I think that's better than using "be on". 😐

2021-04-13 19:11 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +				'%(mailbox)s is the local part of an email address. %(message)s is a message that gives context to why the mailbox is not available',
It may also be worth noting that `%(message)s` should be translated.

2021-04-13 19:11 UTC, daledupreez commented on client/lib/titan/new-mailbox.js
> +const decorateMailboxWithExistenceError = ( mailbox, message ) => {
Maybe call this `decorateMailboxWithAvailabilityError`?

2021-04-13 19:11 UTC, daledupreez commented on client/lib/wpcom-undocumented/lib/undocumented.js
> +				domain
Did the linter make this happen? This multi-line display is not what I'd expect.

2021-04-13 19:16 UTC, olaseni commented on client/lib/titan/new-mailbox.js
> +		return { available: status === 200 && message === 'OK', message, mailbox: mailboxes[ index ] };
Good catch. This was from a time before I hooked in translations.

2021-04-13 19:19 UTC, olaseni commented on client/lib/titan/new-mailbox.js
> +	const promisified_responses = Promise.all(
Fixed

2021-04-14 13:35 UTC, merged

2021-04-14 14:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5705163

Thank you @olaseni for including a screenshot in the description! This is really helpful for our translators.

2021-04-22 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5705163).