ci(wp-desktop): Update Chrome and Chromedriver
Automattic/wp-calypso pull request #51710
Opened 2021-04-06 12:13 UTC by scinos

#### Changes proposed in this Pull Request

* Update Chrome to 87
* Update chromedriver to 11 to match our Electron version

#### Testing instructions

* Verify Desktop e2e tests still pass

2021-04-06 12:15 UTC, scinos commented on .teamcity/_self/projects/DesktopApp.kt
> +				sudo Xvfb ${'$'}{DISPLAY} -screen 0 1280x1024x24 &
Once this is merged, we can move this to the base docker image.

2021-04-06 12:15 UTC, scinos commented on desktop/e2e/tests/e2e.js
> +		'goog:chromeOptions': {
Docs: https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver#3-connect-to-chromedriver

2021-04-06 12:39 UTC, wp-desktop requested changes
WordPress Desktop CI Failure for job "wp-desktop-mac".

@scinos please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/1025513). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

2021-06-04 08:22 UTC, scinos commented
This is a comment

2021-06-04 08:22 UTC, scinos commented
This is a comment

2021-06-04 08:34 UTC, scinos commented
<!--calypso.live-watermark-->This is a new message

2021-06-04 08:41 UTC, scinos commented
<!--calypso.live-watermark-->nThis is a new message

2021-06-04 08:41 UTC, scinos commented
<!--calypso.live-watermark-->
This is a new message

2021-06-04 08:49 UTC, scinos commented
<!--calypso.live-watermark-->
This is a new message with "things"
 and
 ## Things

2021-06-04 08:49 UTC, scinos commented
<!--calypso.live-watermark-->
This is a new message with "things"
 and
 ## Things

2021-06-04 08:52 UTC, scinos commented
<!--calypso.live-watermark-->
This is a new message with "things"
 and
 ## Things

2021-06-04 09:42 UTC, scinos commented
<!--calypso.live-watermark-->
Link to live branch is being generated...
Please wait a few minutes and refresh this page.

2021-11-03 07:59 UTC, closed without merging