Account settings: autosave interface settings on change
Automattic/wp-calypso pull request #52168
Opened 2021-04-21 17:29 UTC by blackjackkent

#### Changes proposed in this Pull Request

* This PR addresses concerns that the need to click a "Save" button in the "Interface Settings" section of `/me/account` is unintuitive compared to other autosaving controls in other parts of Calypso.
* All three controls in "Interface Settings" -- Interface Language, Dashboard Appearance, and Dashboard Color Scheme -- now autosave on change, and the save button has been removed as it is no longer necessary.

#### Testing instructions

* Check out this PR and navigate to http://calypso.localhost:3000/me/account
* Verify that you can change your interface language and have it autosave and automatically refresh to display with the updated language.
* Verify that you can toggle "Show advanced dashboard pages" on and off and have it autosave immediately.
* Verify that you can change your dashboard color scheme and have it autosave immediately.

Related to #51464

2021-04-21 18:56 UTC, mreishus commented
I found odd behavior if you make additional clicks while there are outstanding requests. 
Here, I have Aquatic selected, and make three clicks: Blue, Classic Blue, and Classic Bright. After the second and third clicks, the system changes my selection back to Blue.
So I would expect my color setting to go Aquatic -> Blue -> Classic Blue -> Classic Bright, but it actually goes Aquatic -> Blue -> Classic Blue -> Blue -> Classic Bright -> Blue.

https://user-images.githubusercontent.com/937354/115606507-673a9f80-a2a9-11eb-9f98-9f004da30367.mp4

2021-04-21 19:36 UTC, blackjackkent commented
> I found odd behavior if you make additional clicks while there are outstanding requests.
> Here, I have Aquatic selected, and make three clicks: Blue, Classic Blue, and Classic Bright. After the second and third clicks, the system changes my selection back to Blue.
> So I would expect my color setting to go Aquatic -> Blue -> Classic Blue -> Classic Bright, but it actually goes Aquatic -> Blue -> Classic Blue -> Blue -> Classic Bright -> Blue.

Good catch! I have updated the PR so that all three fields in Interface Settings get disabled while in the process of submitting a change, so a user can't stack multiple changes at once. (This was already set up properly for the Language dropdown so it makes sense to apply it to all three anyway.)

2021-04-21 20:38 UTC, mreishus commented
That looks good. 

Found one more minor issue; if I open the language switcher, but don't switch a language and press Apply, an error message displays: "No settings were provided to the endpoint to set.". Personally, I understand this isn't a big deal and wouldn't care if it happened to me, but I can imagine a less tech-savvy person worrying when they saw an error message with technical jargon like 'endpoint' that they don't understand.


https://user-images.githubusercontent.com/937354/115617826-80e2e380-a2b7-11eb-96d5-35ab821ff1f4.mp4

2021-04-22 19:09 UTC, kwight commented
Wow, this is all fantastic @blackjackkent , great work. 🎉 

I do see the same as @mreishus regarding submitting the same language value; can do a check for the previous and new value, and just perform a modal close if they're the same (rather than sending off the request)? That should make this all ✨ for me.

2021-04-22 20:34 UTC, blackjackkent commented
Yep, very good catch @mreishus . I pushed an update that should address this (it turned out to require a slightly gnarly reworking of the `isLanguageChanged` value which needed to more thoroughly handle the possibility of switching between variants of the same language). Let me know if this all looks good!

2021-04-22 21:21 UTC, mreishus requested changes
* :heavy_check_mark: English -> Spanish works correctly
* :heavy_check_mark: English -> English does not cause an error
* :x: English -> Français de Belgique is not triggering a switch in my testing.

Video:

https://user-images.githubusercontent.com/937354/115786481-7e02f400-a386-11eb-8909-ef331742b8e8.mp4

My debugging code:
```javascript
		console.log( {
			languageHasChanged,
			originalLanguage,
			newLanguage,
			nlpls: newLanguage.parentLangSlug,
			nlls: newLanguage.langSlug,
			firstExpression:
				newLanguage.parentLangSlug &&
				newLanguage.parentLangSlug === originalLanguage &&
				newLanguage.langSlug !== originalVariant,
			secondExpression: ! newLanguage.parentLangSlug && newLanguage.langSlug !== originalLanguage,
		} );

```
Placed right after [this block](https://github.com/Automattic/wp-calypso/blob/9cf455713890c574947461c99a48a78f97e85fd6/client/me/account/main.jsx#L209-L218)

And debugging output:
```javascript
{
  "languageHasChanged": false,
  "originalLanguage": "en",
  "newLanguage": {
    "value": 478,
    "langSlug": "fr-be",
    "name": "Français de Belgique",
    "wpLocale": "fr_BE",
    "parentLangSlug": "fr",
    "calypsoPercentTranslated": 99,
    "isTranslatedIncompletely": false,
    "territories": [
      "155"
    ],
    "revision": 60524
  },
  "nlpls": "fr",
  "nlls": "fr-be",
  "firstExpression": false,
  "secondExpression": false
}
```

2021-04-22 22:36 UTC, blackjackkent commented
Thank you so much for catching all this, and for the debugging info attachment. This is an unexpectedly convoluted little element. :P

I *think* I've finally got this solidified, and have tested the following edge cases and can't think of any more:

* Base language to base language (i.e. Spanish to English) - save
* Base language to variant of same language (i.e. Spanish to Chilean Spanish) - save
* Base language to variant of different language (i.e. Spanish to Belgium French) - save
* Variant language to base of same language (i.e. Chilean Spanish to Spanish) - save
* Variant language to base of different language (i.e. Chilean Spanish to French) - save
* Variant language to different variant of same language (i.e. Chilean Spanish to Mexican Spanish) - save
* Variant language to variant of different language (i.e. Chilean Spanish to Belgian French) - save
* Base language unchanged (i.e. English to English) - no-op
* Variant language unchanged (i.e. Chilean Spanish to Chilean Spanish) - no-op

All of the above seem to work with the latest set of changes, but I would definitely appreciate a fresh pair of eyes to both double-check I didn't miss any cases and let me know if there's an obvious way to reduce down the extremely gnarly logical statement powering this particular check.

2021-04-23 15:48 UTC, mreishus commented
What's committed is working for me :+1: I do agree the `if` statement is pretty gnarly, and gave a shot at making a simpler alternative:
```diff
diff --git a/client/me/account/main.jsx b/client/me/account/main.jsx
index f0fbd4749e..935689c669 100644
--- a/client/me/account/main.jsx
+++ b/client/me/account/main.jsx
@@ -203,21 +203,15 @@ class Account extends React.Component {
 
                const localeVariantSelected = isLocaleVariant( value ) ? value : '';
 
-               const originalLanguage = this.getUserOriginalSetting( 'language' );
-               const originalVariant = this.getUserOriginalSetting( 'locale_variant' );
-               const newLanguage = getLanguage( value );
-               const newLanguageIsBase = ! newLanguage.parentLangSlug;
-               const newLanguageIsVariant = newLanguage.parentLangSlug !== null;
-               const languageHasChanged =
-                       ( newLanguageIsBase &&
-                               ( newLanguage.langSlug !== originalLanguage ||
-                                       ( newLanguage.langSlug === originalLanguage && originalVariant ) ) ) ||
-                       ( newLanguageIsVariant &&
-                               ( newLanguage.parentLangSlug !== originalLanguage ||
-                                       newLanguage.langSlug !== originalVariant ) ) ||
-                       ( typeof empathyMode !== 'undefined' &&
-                               empathyMode !== this.getUserOriginalSetting( 'i18n_empathy_mode' ) );
-               if ( languageHasChanged ) {
+               const originalSlug =
+                       this.getUserSetting( 'locale_variant' ) || this.getUserSetting( 'language' ) || '';
+
+               const languageHasChanged = originalSlug !== value;
+               const empathyModeHasChanged =
+                       typeof empathyMode !== 'undefined' &&
+                       empathyMode !== this.getUserOriginalSetting( 'i18n_empathy_mode' );
+
+               if ( languageHasChanged || empathyModeHasChanged ) {
                        this.props.markChanged();
                }
 
```
This seems to be working for me, any thoughts on this approach?

2021-04-23 16:59 UTC, blackjackkent commented
@mreishus This is a great refinement; thank you! I've pushed a change with the updated code.

2021-04-23 17:40 UTC, mreishus commented
@Automattic/serenity Anyone else want to take a look? I don't feel comfortable signing off on code I contributed :)

2021-04-23 19:21 UTC, sixhours requested changes
I tested this and ran into an issue with the "Community Translator" checkbox, which probably appears for the mag 16 (maybe all non-English?):

<img width="730" alt="Screen Shot 2021-04-23 at 3 11 00 PM" src="https://user-images.githubusercontent.com/2124984/115919535-f204d100-a446-11eb-9781-3003883be446.png">

There's no save confirmation when I check or uncheck the box, so there's no indicator the setting has been saved.

2021-04-26 17:14 UTC, sixhours approved these changes
Hurrah! Working like a dream now. 👍

2021-04-26 17:21 UTC, merged