Earn: Fix Refer-a-Friend Link for Other Languages
Automattic/wp-calypso pull request #52299
Opened 2021-04-26 16:58 UTC by Aurorum

#### Changes proposed in this Pull Request

* Fixes the Refer-a-Friend link for languages other than English

#### Testing instructions

The link structure on the `/earn` page should now be slightly different, with the language prefix being placed before the "wordpress.com".

**Before:** https://wordpress.com/fr/refer-a-friend/eA86JowiXYNPzqnAJyA7/ (invalid)
**After:** https://fr.wordpress.com/refer-a-friend/eA86JowiXYNPzqnAJyA7/ (valid)

<img width="553" alt="Screenshot 2021-04-26 at 17 50 53" src="https://user-images.githubusercontent.com/43215253/116121333-685c3a00-a6b8-11eb-8b82-b414eb6ef00b.png">

I've also already verified that all the languages marked under `magnificentNonEnLocales` are compatible with this page!

cc @taggon, @akirk, @lsl

Fixes #52281

2021-04-27 05:37 UTC, lsl commented
Thanks for the PR @Aurorum! :wave:

Unfortunately we won't be able to merge this PR as is. Its a bit annoying but the `localizeUrl` function is actually working the way it should be.

There is a bunch of internal WordPress.com stuff at play here. In essence: The correct, localized, URL we want shown to users on `https://wordpress.com/earn` is something like this: `https://wordpress.com/fr/create-blog-referral/<token>`

There is likely a bug with the way we manage the localized redirects in this case. (Our internal site mapping isn't seeing the redirect to the new page in the same way the english one does) - @dlind1 / @jaswrks maybe you want to look at this? (note: I don't know if this is actually fixable, redirects might be happening too far after mapping)

And I was about to suggest we update the english url in the earn component so the link produced doesn't require a redirect but it looks like that is not hard coded and instead [fetched from the API.](https://github.com/Automattic/wp-calypso/blob/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/my-sites/earn/refer-a-friend/index.tsx#L55) - @jaswrks is this just a slug update in `lib/peer-referrals/class-peer-referrals.php`? That might be an easier fix.

2021-04-27 05:42 UTC, lsl requested changes
There isn't anything you can do here but I'm adding "request changes" to the PR so nobody merges this without seeing the PR comment above!

2021-04-27 05:42 UTC, lsl commented on packages/i18n-utils/src/localize-url.tsx
> +	'wordpress.com/refer-a-friend/': setLocalizedUrlHost( 'wordpress.com', magnificentNonEnLocales ),
Its best if we don't map specific files like this. I think in this case we need to update the referral link we send from the backend to support localization better.

2021-04-27 05:42 UTC, lsl commented on packages/i18n-utils/src/test/localize-url.js
> +	} );
Thanks for adding tests! makes it much easier to see what you're trying to do here.

2021-04-27 09:11 UTC, Aurorum commented
Thanks @lsl! Given that `localizeUrl` is the only function which can be touched in Calypso's codebase and it'd be preferable to change the actual URL, I'll close this PR. :)

2021-04-27 09:11 UTC, closed without merging

2021-04-28 19:29 UTC, dlind1 commented
@lsl @Aurorum 
I think that it was missed in the subdomain=>subfolder migration and I have a fix ready in D60747-code.