Sidebar My Sites: Simplifies expanded logic and expands only when a child is selected on desktop.
Automattic/wp-calypso pull request #52739
Opened 2021-05-11 07:36 UTC by cpapazoglou

#### Changes proposed in this Pull Request

* Simplifies expanded logic by consolidating the code to 1 variable.
* Relies on `childIsSelected` for desktop breakpoints

#### Testing instructions

**Desktop**
- Select a Jetpack site and expand "Upgrades" & "Jetpack".
- Now select a WPCOM site.
- Only one (the last) menu should display as expanded.

**Mobile**
- Select a Jetpack site and expand "Upgrades" & "Jetpack".
- Now select a WPCOM site.
- Both sections should be displayed as expanded.
- Clicking an other (Calypso) menu should just expand and not redirect.
- Clicking a submenu item should redirect and collapse the rest of the menus.

Before | After
-------|------
![](https://cln.sh/ZDUJgh+) | ![](https://cln.sh/snAvJ3+)

Fixes #52727

2021-05-11 13:54 UTC, mmtr requested changes
I think there is a regression on mobile viewports.

To reproduce: 
- On Chrome, open the dev tools, toggle the device toolbar and select a mobile device.
- Go to `/activity-log`.
- Select a simple site.
- Open the sidebar (Click on the "W" button).
- Note how the submenus are hidden.

This branch | Production
--- | ---
<img width="826" alt="Screen Shot 2021-05-11 at 15 50 34" src="https://user-images.githubusercontent.com/1233880/117827168-0d5a4380-b271-11eb-92a8-3f85c3e5e771.png"> | <img width="957" alt="Screen Shot 2021-05-11 at 15 50 28" src="https://user-images.githubusercontent.com/1233880/117827194-11866100-b271-11eb-97d2-e443c9518aa7.png">

2021-05-12 09:31 UTC, cpapazoglou commented
This PR will also resolve issues when you may land to another Calypso section without interacting with the sidebar

Steps to Repro:
- Pick an Atomic site
- Go to Setting-> General-> Jetpack
- Click "View your site's backups activity
- You will be landed to Jetpack-> Activity Log but Settings submenu will be still expanded
![](https://cln.sh/mrDcPq+)

props: @olaolusoga

2021-05-12 09:34 UTC, cpapazoglou commented
> I think there is a regression on mobile viewports.
> 
> To reproduce:
> 
> * On Chrome, open the dev tools, toggle the device toolbar and select a mobile device.
> * Go to `/activity-log`.
> * Select a simple site.
> * Open the sidebar (Click on the "W" button).
> * Note how the submenus are hidden.
> 
> This branch	Production
> <img alt="Screen Shot 2021-05-11 at 15 50 34" width="826" src="https://user-images.githubusercontent.com/1233880/117827168-0d5a4380-b271-11eb-92a8-3f85c3e5e771.png">	<img alt="Screen Shot 2021-05-11 at 15 50 28" width="957" src="https://user-images.githubusercontent.com/1233880/117827194-11866100-b271-11eb-97d2-e443c9518aa7.png">

Good catch @mmtr! This was a good opportunity to further simplify the logic 43659cb!

2021-05-12 14:08 UTC, mmtr approved these changes
Nice lines diff count! Works perfectly.

2021-05-13 07:24 UTC, merged