Jetpack Cloud Pricing: Fix Jetpack Free button does not respect site protocol.
Automattic/wp-calypso pull request #52754
Opened 2021-05-11 16:08 UTC by elliottprogrammer

#### Changes proposed in this Pull Request

- Added the site's `wp_admin` query arg to the Jetpack redirects coming from the plugin: D61244-code
- If the Pricing page is coming from Jetpack Redirect: source=`jetpack-connect-plans` or source=`jetpack-nav-site-only-plans`, this PR utilizes the 'wp_admin' query arg to build the "Jetpack Free" button url that points back to the site's /wp-admin page.

#### Testing instructions

1. First apply patch D61244-code and point `jetpack.com` to your sandbox IP.
2. Checkout this PR and run `yarn start-jetpack-cloud`.
3. Starting with a brand new self-hosted site, using **http://** (_not https://_)
    - (this is kinda the tricky part because jurassic ninja runs on https only, so we can't use a JN site for testing.  For me, I happen to already own an old site that utilizes http-only so I was able to do my testing with that. Otherwise I suppose you could use your Jetpack plugin docker environment with a jurassic-tube or ngrok tunnel to an non-https domain.  And I suppose there are other ways too, but I'm not sure what they are off hand.  If you know of a better way to quickly spin up a new http-only WordPress site, please let me know. :)
4. Install Jetpack and start the connection process.
    - *Bonus points for utilizing site-only connection.
5. Upon successful connection, you'll be redirected to `https://cloud.jetpack.com/pricing/...`
6. Verify that the query arg `wp_admin` exists in the `cloud.jetpack.com/pricing/...` url and that the query arg value is the site's non-https wp-admin url. For example: `...&admin_url=http%3A%2F%2Fyoursite.com%2Fwp-admin%2F`
7. In the url, change `https://cloud.jetpack.com/` to `https://jetpack.cloud.localhost:3000/`
8. At the bottom of the page, the "Jetpack Free" button should point to the site's non-https wp-admin recommendations url. ie.-  `http://yoursite.com/wp-admin/admin.php?page=jetpack#/recommendations`.

Related to 1164141197617539-as-1200255987445623

Fixes https://github.com/Automattic/wp-calypso/issues/52394

2021-05-12 17:50 UTC, rcanepa approved these changes
LGTM. It worked as expected.

2021-05-13 14:57 UTC, monsieur-z requested changes
I believe `siteWpAdminUrl` should not be passed as is if the site is not a Jetpack site. Otherwise it could reintroduce the issue fixed in #52644.

2021-05-13 15:46 UTC, rcanepa commented
> I believe `siteWpAdminUrl` should not be passed as is if the site is not a Jetpack site. Otherwise it could reintroduce the issue fixed in #52644.

I think this PR won't reintroduce that regression only because this new way of constructing the URL happens if the URL includes the `admin_url` query parameter. In any other case, it defaults to whatever `getJetpackRecommendationsUrl` returns. So, if there is no site in context (and no `admin_url` in the URL), the current behavior won't be affected by these changes.

To test this, I started Calypso Blue and visited `http://calypso.localhost:3000/jetpack/connect/store?source=jetpack-connect-plans&cta_id=masthead-install-page-9&cta_from=home`. I saw that Jetpack Free's link pointed to `http://calypso.localhost:3000/jetpack/connect` even when my primary site was a Simple site.

@monsieur-z, do you think that my assessment of the situation is correct?

2021-05-13 18:42 UTC, monsieur-z commented
> @monsieur-z, do you think that my assessment of the situation is correct?

Absolutely, @rcanepa.

It might be good to add a test case for this update in `client/components/jetpack/card/jetpack-free-card/test/button.jsx` @elliottprogrammer, but this is not a blocker.

2021-05-13 20:45 UTC, elliottprogrammer commented
Yes @monsieur-z , good idea.  I added a test case. 👍

2021-05-13 20:45 UTC, merged