Domain suggestions are not displayed when moves back from checkout page
Automattic/wp-calypso pull request #52798
Opened 2021-05-12 18:03 UTC by taggon

#### Changes proposed in this Pull Request

* This PR fixes the bug that domain suggestions are not displayed in the signup flow when you moves back from the checkout page.

#### Testing instructions

1. Create a new website from https://wordpress.com/start/new . The bug happens for both new and existing users.
1. Select a paid plan and proceed to the checkout page.
1. Click on the browser back button.
1. The domains step should display the suggestions.

Related to #52610

2021-05-17 09:58 UTC, yansern requested changes
I'm adding a suggestion to remove `return`.

Since assertions operate on a "no news is good news" basis, my understanding is that `return` is not required since it is only waiting for an error to be thrown, and all `await` calls throw errors when they fail.

Let me know if there is a use case where `return` is necessary, otherwise, saving a few bytes is nice. :)

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +			return await driverManager.ensureNotLoggedIn( driver );
```suggestion
			await driverManager.ensureNotLoggedIn( driver );
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +			return await createYourAccountPage.enterAccountDetailsAndSubmit(
```suggestion
			await createYourAccountPage.enterAccountDetailsAndSubmit(
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +				return await findADomainComponent.selectDomainAddress( expectedDomainName );
```suggestion
				await findADomainComponent.selectDomainAddress( expectedDomainName );
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +					return this.skip();
```suggestion
					this.skip();
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +			return await pickAPlanPage.selectPremiumPlan();
```suggestion
			await pickAPlanPage.selectPremiumPlan();
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +			return await new SignUpStep( driver ).continueAlong( siteName, passwordForTestAccounts );
```suggestion
			await new SignUpStep( driver ).continueAlong( siteName, passwordForTestAccounts );
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +			return await checkOutPage.enterRegistrarDetails( testDomainRegistarDetails );
```suggestion
			await checkOutPage.enterRegistrarDetails( testDomainRegistarDetails );
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +			return await findADomainComponent.selectFreeAddress();
```suggestion
			await findADomainComponent.selectFreeAddress();
```

2021-05-17 09:58 UTC, yansern commented on test/e2e/specs/specs-calypso/wp-signup-spec.js
> +			return await new DeleteAccountFlow( driver ).deleteAccount( siteName );
```suggestion
			await new DeleteAccountFlow( driver ).deleteAccount( siteName );
```

2021-05-17 12:49 UTC, yansern commented
After pressing Back, the domains page is shown again and the domain suggestions work.

However, there are a two issues:
- the free subdomain suggestion is not shown.
- the existing subdomain "this is your current free site address" at the bottom is missing an address.

What is supposed to be exact behaviour when a user hit back from checkout page?

![image](https://user-images.githubusercontent.com/1287077/118491155-fc04b180-b71e-11eb-9f76-a9da65da7fef.png)

![image](https://user-images.githubusercontent.com/1287077/118491170-feffa200-b71e-11eb-901d-a9c0e1121c86.png)

Also, just supplementing some additional data from IndexedDB if it helps.
![image](https://user-images.githubusercontent.com/1287077/118491212-0921a080-b71f-11eb-8c2c-37d2a9437b83.png)

2021-05-17 13:16 UTC, yansern commented
Based on the conversation on p1621256403375000-slack-C01VA100LEA, I think if the "This is your current free site address" part shows the current user's subdomain, then I think we can consider this issues fixed for now.

The ideal solution is of course, as mentioned in the slack convo, to show a modal as suggested in this issue https://github.com/Automattic/wp-calypso/issues/50435.

2021-05-17 15:16 UTC, niranjan-uma-shankar commented
> the free subdomain suggestion is not shown.

> the existing subdomain "this is your current free site address" at the bottom is missing an address.

This issue is tracked in https://github.com/Automattic/wp-calypso/issues/45905. We would ideally want to allow the user to be able to change their subdomain address,  but I think it would still be good to just show their subdomain in the current free address section and I concur that this would close the issue.


> The ideal solution is of course, as mentioned in the slack convo, to show a modal

Just for the record, there's also more discussion in pau2Xa-1Io/#comment-6756.

2021-05-18 05:16 UTC, taggon commented
> Since assertions operate on a "no news is good news" basis, my understanding is that return is not required since it is only waiting for an error to be thrown, and all await calls throw errors when they fail.

That makese sense. The `return` statments before `await` are not necessary. I removed them all as per your request.

2021-05-24 13:22 UTC, donlair commented
I've been going through this flow a bunch for an unrelated issue and there are a couple items that seem odd to me, but I think they are outside the scope of this particular issue. This PR tests well and improves the flow for people who want to change their domain.

2021-05-27 01:10 UTC, yansern commented
> I've been going through this flow a bunch for an unrelated issue and there are a couple items that seem odd to me, but I think they are outside the scope of this particular issue.

I would say the missing existing subdomain under after pressing back would be an odd issue worth fixing either in this same PR or another PR.

> but I think it would still be good to just show their subdomain in the current free address section and I concur that this would close the issue.

+1 to what @niranjan-uma-shankar said.

2021-05-27 01:11 UTC, yansern approved these changes
I'm tentatively approving this PR.

Considering if we want to limit the scope of the PR to just showing something instead of BSOD when pressing back button, then this PR has served its purpose.

We can then work on https://github.com/Automattic/wp-calypso/pull/52798#issuecomment-849237259 on another PR.

2021-05-27 01:16 UTC, yansern commented
> @yansern That makese sense. The return statments before await are not necessary. I removed them all as per your request.

About this one, I recently learned that there might be an advantage of returning awaits where it helps bring more clarity on stack tracing. https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md

But I still need to test it out myself to see if it really does help within the context of mocha tests.

Not a blocker for this PR.

2021-05-27 15:43 UTC, taggon commented
Rebased

2021-05-28 02:12 UTC, merged