Add webpack filesystem cache
Automattic/wp-calypso pull request #52884
Opened 2021-05-14 19:26 UTC by mreishus

#### Changes proposed in this Pull Request

* Enable [webpack 5 persistent caching](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#persistent-caching)
* I initially included `resolve.fallback.fs: false` to solve an error I was seeing about not being able to resolve the fs package in the terminal, but I removed it and I can't seem to get the error again. So I did remove it from this branch: 635f34510ae92. But it might be needed? That solution was based off the [webpack 4 -> 5 migration guide](https://webpack.js.org/migrate/5/) ("If you are using something like `node.fs: 'empty'` replace it with `resolve.fallback.fs: false.`").
* Benchmarks

I benchmarked by running `yarn && yarn start`, then attempting to visit http://calypso.localhost:3000. This changeset showed a noticeable improvement in overall time on my laptop (~1m50s -> ~1m00s).
Benchmark results:
```
  no cache - try 1
  00m:00s Start
  00m:30s See Emoji Screen
  02m:00s See home screen loaded in browser
  
  no cache - try 2
  00m:00s Start
  00m:30s See Emoji Screen
  01m:42s See home screen loaded in browser
  
  cache - try 1
  00m:00s Start
  00m:30s See Emoji Screen
  01m:04s See home screen loaded in browser
  
  cache - try 2 
  00m:00s Start
  00m:30s See Emoji Screen
  00m:57s see home screen loaded in browser
```

#### Testing instructions

* Benchmark as above
* Also needs testing in other environments+contexts, like CI

2021-05-20 18:33 UTC, griffbrad commented
Just bumping this one for @scinos so it doesn’t fall off the radar.

2021-05-20 19:08 UTC, mreishus commented
If it's too scary for CI/Prod etc I'm totally in favor of adding it for local dev only.

2021-05-20 23:41 UTC, noahtallen commented
The [ICFY failure](https://github.com/Automattic/wp-calypso/pull/52884/checks?check_run_id=2586681849#step:7:530) could be related (not sure). It's about `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`. I re ran the test and it still failed, so it might be related.

This does seem to work ok locally though!

2021-05-21 16:47 UTC, mreishus commented
Rebasing to see if ICFY fails again

2021-05-21 17:07 UTC, scinos commented
Thanks for looking into this!

It is very interesting that you saw an improvement in build time. When we experimented with this feature (#49855) we didn't see any significant improvement (p1611849960065300-slack-C7YPUHBB2). Maybe it is time to run more experiments to see what's the impact.

That being said, webpack's persistent cache replaces [`cache-loader`](https://github.com/webpack-contrib/cache-loader), so eventually we'll need to drop the loader and use the cache _anyway_.

> If it's too scary for CI/Prod etc I'm totally in favor of adding it for local dev only.

I think this is also risky for local dev. If we don't nail the cache invalidation, there is a chance a developer will waste a lot of time loading an old version of the code.

For example, we need to provide a list of env vars that can alter the compilation result so webpack can use them as cache keys (example https://github.com/Automattic/wp-calypso/pull/49855/files#diff-4403f97cf9b9ff966cfc2425845eaab1fc18cb890cb9233459e977d92b214741L401-L408). I'm worried that we don't have a good system to ensure new env vars tha anyone may introduce are added to the list.

2021-05-21 18:19 UTC, mreishus commented
> we didn't see any significant improvement (p1611849960065300-slack-C7YPUHBB2)
I also didn't see any improvement with the memory cache, or the reload after change. Where I see the improvement is speeding up the emoji screen on initial build only.. unsure if your yarn start timings include that or not. It's significant enough that I keep a patch around to apply before I start working on stuff. Will ask some other people to try, too..

2021-05-21 19:41 UTC, mreishus commented
`rg 'process.env' | perl -n -e'/process.env.(\w+)/ && print "$1\n"' | sort | uniq > env_vars.txt`
generates a list like
```
APPIMAGE    
APPLE_DEVELOPER_SHORT_NAME
BABEL_ENV      
BINARY_PATH    
BROWSERLOCALE
BROWSERSIZE
BROWSERSLIST_ENV
BUILD_TRANSLATION_CHUNKS
CALYPSO_DOCTOR_SKIP
...
```

2021-06-14 09:51 UTC, scinos commented
I think we can start with a 'mild' version of this cache: use `type:'memory'` instead of `type:'filesystem'`.

The reason is that a `filesystem` cache needs a very good strategy for invalidations if we want to persist it between builds (note: webpack recommends [cleaning the cache on every install](https://webpack.js.org/guides/build-performance/#persistent-cache)). 

A `memory` cache is only alive as long as the process started by `yarn start` is alive. It should give us some improvements on recompiations (although in my local tests it only shows a 10% improvement)

2021-06-14 09:52 UTC, scinos requested changes

2021-06-14 09:52 UTC, scinos commented on client/webpack.config.js
> +	cache: { type: 'filesystem' },
```suggestion
	cache: { type: 'memory' },
```

2021-06-21 13:28 UTC, scinos commented
Update: I'm experimenting with a `filesystem` cache in https://github.com/Automattic/wp-calypso/pull/53867.

In my laptop it improves both `yarn build-client-evergreen` and `yarn start` a lot (3x and 8x faster, respectively) when the cache is full, and there is a small performance hit with the cache is cold (~5% slower in both cases)

2021-06-23 15:39 UTC, mreishus commented
In my limited testing, adding the memory type cache did not improve anything. I'm happy to close this, unless you want to add it @scinos

2021-06-23 15:40 UTC, closed without merging