Nav Unification: Fix dashboard appearance check when loading the editor
Automattic/wp-calypso pull request #52911
Opened 2021-05-17 09:25 UTC by pablinos

In #51108 we introduced a check to determine if the dashboard appearance
option was on, and if so, redirect to `wp-admin` rather than load the
Gutenframe. This also affected any links to the editor.

Unfortunately, there was a misinterpretation of user settings. Where we
can technically read the `calypso_preferences` from user settings, we
should be using the alternative `/me/preferences` endpoint. One of the
reasons for this is that the user token to access settings can become
stale, requiring people with 2FA active to input an auth code. That in
turn means that the request to access user settings fails and when
loading the editor, we wait for a timeout before continuing.

This creates an unacceptable delay when loading the editor as noted
in #52651 which this fixes by swapping to using the 'preferences' part
of the store, rather than user settings.

#### Testing instructions

As noted in #52561, it's possible to get into a state where hard refreshing the editor will result in a blank screen for around 10 seconds, as the call to user settings fails and we wait for the timeout. This might only be for people with 2FA where the access token has expired.

Whether the bug can be replicated or not, we need to ensure that with this change there is not a long delay with a blank screen as the editor loads. 

* Load the editor, on a site.
* Hard refresh by holding shift while refreshing the browser
* You can also try clearing the `calypso` local storage and refreshing again.
* You may find that there is a long delay with a blank screen as the editor loads.
* Switch to this branch, and go through the same procedure.
* Observe that everything functions the same, but any delay in loading the editor is gone
* Go to /me/account and turn an the Dashboard Appearance setting
* Now all links to the editor should default to `wp-admin`

Related to #52651

2021-05-17 18:52 UTC, retrofox commented
Tested and I was able to reproduce all tests here

- [x] Load the editor, on a site.
- [x] Hard refresh by holding shift while refreshing the browser
- [x] You can also try clearing the calypso local storage and refreshing again.
- [x] You may find that there is a long delay with a blank screen as the editor loads.
- [x] Switch to this branch, and go through the same procedure.
- [x] Observe that everything functions the same, but any delay in loading the editor is gone
- [x] Go to /me/account and turn an the Dashboard Appearance setting
- [x] Now all links to the editor should default to wp-admin

2021-05-20 21:58 UTC, noahtallen requested changes
Awesome, thanks for looking into this! Unfortunately, the editor doesn't seem to load for me (at least within 20-30 seconds) 🤔 Not sure what's up, though, since prod is loading.


https://user-images.githubusercontent.com/6265975/119053855-877a7e80-b97b-11eb-84d6-621242f3498f.mov

2021-05-21 06:19 UTC, pablinos commented
That's weird, it doesn't look like it's loading anything. Can you edit other posts and pages apart from the homepage?

I'll try it with a newer test site, maybe it's something related to the homepage editor.

2021-05-21 06:29 UTC, pablinos commented
It's working for me. I notice there is an error in your console that I don't get. However the E2E tests are failing in TeamCity, and I've been trying to fix those. Perhaps the same editor loading problem is occurring there.


https://user-images.githubusercontent.com/96462/119092208-0ddba280-ba06-11eb-9ae7-495b24084c5d.mov

2021-05-21 16:52 UTC, pablinos commented
So it turns out that if you haven't previously set the `linkDestination` preference, the default was `null` so we ended up waiting forever for the value to change. 

For now, I've fixed this by setting a default, but this makes the waiting code kind of obsolete. We should really set a default on the server, wait a short time for the value to be available in the frontend, and if the time limit is reached, then use the default.

Currently, there will be situations where the value hasn't been fetched from the server but we don't wait and use the default, but this shouldn't be common and I think is something we can live with for now.

@noahtallen Would you mind taking another look when you get a chance?

2021-05-21 21:14 UTC, noahtallen approved these changes
This is working great for me now with wp-admin pages turned on and turned off.

2021-05-21 21:15 UTC, noahtallen commented
I'm going to move forward with merging this because I noticed we were getting some customer reports about this problem.

2021-05-21 21:15 UTC, merged

2021-05-21 21:31 UTC, noahtallen commented
One thing that I did notice is that when turning "wp-admin pages" from "on" to "off", the change doesn't take effect when loading the editor until I do a hard refresh. Might be worth investigating in a follow-up :)