Prevent users from purchasing additional mailboxes when the associated subscription expires/is expiring
Automattic/wp-calypso pull request #53189
Opened 2021-05-26 12:06 UTC by olaseni

#### Changes proposed in this Pull Request

* The email plan page checks the expiry status of the plan's subscription to determine if the user should be allowed to purchase additional mailboxes.
* In the event that the subscription is very close to expiry or expired, a renew button is shown instead.

#### Testing instructions

* Checkout this branch locally or use the Calypso live branch
* View the email plan page for any email subscription i.e. Professional Email, or Google Workspace
* Confirm that a renewal button is displayed for the following scenarios:
    * The subscription is almost expired ( within the month window )
    * The subscription has expired

2021-05-27 16:20 UTC, stephanethomas requested changes
A gentle reminder to add screenshots of the changes 🙂. This is what I see for that new option:

<img width="488" alt="screenshot" src="https://user-images.githubusercontent.com/594356/119858613-eceae400-bf14-11eb-8af1-c69219782db5.png">

It appears as a button, which feels really weird. Looking at `RenewButton` it seems we don't need all the features it provides, so I believe we could just use a regular `VerticalNavItem` and call `handleRenewNowClick()` when it is clicked.

> In the event that the subscription is very close to expiry or expired, a renew button is shown instead.

We are the May 27th today, and I was presented with this new button whereas my Titan subscription is supposed to expire on June 8th. That seems way too early to force users to renew. Looking quickly at `needsToRenewSoon()`, it seems it's even worse as we will basically show that button all the time for Titan subscriptions.

2021-05-27 16:20 UTC, stephanethomas commented on client/my-sites/email/email-management/home/email-plan.jsx
> +					subscriptionId={ parseInt( purchase.id, 10 ) }
I would suggest this shorter and clearer approach:

```suggestion
					subscriptionId={ Number( purchase.id ) }
```

2021-05-27 16:20 UTC, stephanethomas commented on client/my-sites/email/email-management/home/email-plan.jsx
> +			<VerticalNavItem { ...addMailboxProps }>{ translate( 'Add new mailbox' ) }</VerticalNavItem>
This label should be `Add new mailboxes` per https://github.com/Automattic/wp-calypso/pull/53161.

2021-05-27 16:20 UTC, stephanethomas commented on client/my-sites/email/email-management/home/email-plan.jsx
> +					customLabel={ translate( 'Renew now to add new mailboxes' ) }
I think `Renew to add new mailboxes` is enough but I'll leave it up to you.

2021-05-27 16:20 UTC, stephanethomas commented on client/my-sites/email/email-management/home/email-plan.jsx
>  		const addMailboxProps = this.getAddMailboxProps();
As far I can see `addMailboxProps` is only ever used once, so we could simply inline `this.getAddMailboxProps()`:

```javascript
			<VerticalNavItem { ...this.getAddMailboxProps() }>{ translate( 'Add new mailbox' ) }</VerticalNavItem>
```

2021-05-30 17:55 UTC, daledupreez commented on client/my-sites/email/email-management/home/email-plan.jsx
> +			<VerticalNavItem { ...addMailboxProps }>{ translate( 'Add new mailbox' ) }</VerticalNavItem>
Please make sure the translations are in for the other PR before merging this one with the updated string.

2021-06-01 13:01 UTC, stephanethomas approved these changes
I've tested it with a Titan subscription, and it worked great 👍.

2021-06-01 13:01 UTC, stephanethomas commented on client/my-sites/email/email-management/home/email-plan.jsx
> +		if ( ! selectedSite || ! purchase ) {
`selectedSite` is always provided (it's a required prop), we can remove it from this condition.

2021-06-01 13:01 UTC, stephanethomas commented on client/my-sites/email/email-management/home/email-plan.jsx
> +		handleRenewNowClick( purchase, selectedSite.slug, {
Maybe add a blank line above 🙂?

2021-06-01 17:43 UTC, merged

2021-06-01 18:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5971840

Thank you @olaseni for including a screenshot in the description! This is really helpful for our translators.

2021-06-11 11:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5971840).