Fix: incorrect description of the Live Chat feature
Automattic/wp-calypso pull request #53241
Opened 2021-05-28 04:33 UTC by taggon

#### Changes proposed in this Pull Request

* Update the description of the Live Chat feature on the plans page of My Home to sync up with the plans signup step.

#### Testing instructions

* Visit My Home of your free plan site.
* Select the _Pay annually_ tab.
* Make sure Live Chat feature varies as follows:
  * Premium plan: _Live Chat 24X5_ - Live chat is available 24 hours a day from Monday through Friday.
  * Business and E-commerce plans: _Live Chat 24X7_ - Live chat is available 24/7.
    ![Plans_‹_FreePlan_—_WordPress_com](https://user-images.githubusercontent.com/212034/119929807-2bd27580-bfb9-11eb-978a-90f208577748.jpg)

Closes #53238

2021-05-28 06:04 UTC, yansern approved these changes
24/5 displayed as expected.

2021-05-28 07:15 UTC, niranjan-uma-shankar requested changes
I suggest adding the "String freeze" label and waiting for translations to complete, but otherwise LGTM.

Here's the display in `fr` locale with the tooltip content untranslated:

<img width="451" alt="Screenshot 2021-05-28 at 11 13 51 AM" src="https://user-images.githubusercontent.com/1269602/119944935-ea849a80-bfa5-11eb-9851-8a0dede86b8e.png">

2021-05-28 08:50 UTC, taggon commented
@niranjan-uma-shankar thanks. I added the label. 😄

2021-05-28 09:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5955950

Thank you @taggon for including a screenshot in the description! This is really helpful for our translators.

2021-05-31 11:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5955950).

2021-05-31 11:41 UTC, taggon commented
@niranjan-uma-shankar Could you remove the change request? I already added the `String Freeze` label to this PR.

2021-05-31 11:59 UTC, niranjan-uma-shankar approved these changes
LGTM

2021-06-04 01:53 UTC, merged