New Onboarding: Update tracks events for design selection
Automattic/wp-calypso pull request #53418
Opened 2021-06-04 15:22 UTC by StefanNieuwenhuis

### Changes proposed in this Pull Request
Use the `getSelectedDesign` selector directly in the `<Design/>` component to get the proper values for the selected design.

### Testing instructions
1. Check out this branch and `yarn && yarn start`.
2. Open a browser and go to `/new`.
3. Open the network tab in DevTools and make sure to preserve the log.
4. Create a new site with an empty page (blank canvas design).
5. After selecting a design, go to the next step
6. Filter the network tab with `selected_design` and inspect the query params
7. Ensure that:
    * [ ] `selected_design` is equal to the selected design.

fixes #52667

2021-06-04 15:52 UTC, razvanpapadopol commented on client/landing/gutenboarding/onboarding-block/designs/index.tsx
> +	} );
```suggestion
	}, [] );
```
Missing deps array

2021-06-04 15:53 UTC, razvanpapadopol commented on client/landing/gutenboarding/onboarding-block/designs/index.tsx
> +	const { getSelectedDesign, hasPaidDesign, getRandomizedDesigns } = useSelect( ( select ) => {
`getSelectedDesign` and `getRandomizedDesigns` are named like they are some callable functions. Should we use `selectedDesign` and `randomizedDesigns` instead?

2021-06-04 17:08 UTC, razvanpapadopol requested changes
The solution still doesn't fix the original issue (previous selected design is being logged).

> Open a browser and go to /new.

The URL should be `/new?fresh` to reset the Onboard store and log the `selected_design: undefined` when selecting a design for the first time.

2021-06-08 08:52 UTC, StefanNieuwenhuis commented on client/landing/gutenboarding/onboarding-block/designs/index.tsx
> +	const { getSelectedDesign, hasPaidDesign, getRandomizedDesigns } = useSelect( ( select ) => {
I suspected the selector of causing the issue and I removed `selectedDesign` & `randomizedDesigns` to keep the code consistent (I use `getSelectedDesign` in `useTrackStep` directly). 

Now that the issue still persists, I'll revert these changes.

2021-07-02 16:15 UTC, alshakero commented
Was [the issue](https://github.com/Automattic/wp-calypso/pull/53418#pullrequestreview-676504454) above addressed?

2021-08-05 14:03 UTC, StefanNieuwenhuis commented
> The solution still doesn't fix the original issue (previous selected design is being logged).
> 
> > Open a browser and go to /new.
> 
> The URL should be `/new?fresh` to reset the Onboard store and log the `selected_design: undefined` when selecting a design for the first time.

We might have encountered a similar issue in https://github.com/Automattic/wp-calypso/pull/54646#pullrequestreview-722329391.

2025-06-19 18:40 UTC, closed without merging