VAT: add tracks events to details form
Automattic/wp-calypso pull request #53487
Opened 2021-06-07 22:26 UTC by michaeldcain

This adds Tracks events to the VAT details form submission, submission result, and Happiness link click.

Includes #53133, will need to be rebased after it merges.

2021-06-07 22:36 UTC, a8ci18n commented on client/me/purchases/billing-history/receipt.jsx
> +				<strong>{ translate( 'Vendor VAT Details' ) }</strong>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **38** times:
`translate( 'Vendor VAT #:' )` *ES Score: 6*

2021-06-08 23:28 UTC, sirbrillig requested changes
I get `Uncaught TypeError: Cannot read property 'type' of undefined` when I follow the instructions. I highlighted what I think the problem is. It's a little confusing since there's two different versions of `recordTracksEvent`.

2021-06-08 23:28 UTC, sirbrillig commented on client/me/purchases/vat-info/index.tsx
> +import { recordTracksEvent } from '@automattic/calypso-analytics';
Here you're importing the raw `recordTracksEvent` but that version does not require a redux dispatch and [the README says not to use it if you can](https://github.com/Automattic/wp-calypso/blob/37b6bf1332e3ee7ba149f99df4d7506afa82eda5/packages/calypso-analytics/README.md#L19) I think you actually want:

```
import { recordTracksEvent } from 'calypso/state/analytics/actions';
```

2021-06-09 01:45 UTC, sirbrillig approved these changes
👍  Works as described and the code looks good, although it will need a rebase before it merges... I'm surprised there's no conflicts actually. 🤔  Approving anyway.

2021-06-09 04:58 UTC, sirbrillig commented
Oh, I think I know what might have happened. You need to manually remove the already-merged commits in an interactive rebase. (The most annoying part about us using a squash and merge strategy on this repo... otherwise git would do this for us.)

2021-06-09 15:48 UTC, merged