Plans: Split jetpack-plans 'utils' into separate files
Automattic/wp-calypso pull request #53560
Opened 2021-06-09 19:01 UTC by mattgawarecki

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

2021-06-09 19:41 UTC, mattgawarecki commented on client/my-sites/plans/jetpack-plans/plans-filter-bar/get-highest-annual-discount.ts
> +};
This function is the only change in logic inside this refactor PR -- I moved the logic to calculate the discount for an individual slug into its own function, for readability sake.

2021-06-09 20:31 UTC, monsieur-z commented
@mattgawarecki, once test is failing (`getHighestAnnualDiscount › returns null if highest discount would round to 0%`).

2021-06-09 20:40 UTC, monsieur-z requested changes
I believe the `client/my-sites/plans/jetpack-plans/checkout.ts` requires the `page` module to be imported.

2021-06-10 14:51 UTC, monsieur-z approved these changes
Code changes look good. The pricing page tested well in all 3 environments, and all unit tests pass. There's a failing e2e test on mobile, but which doesn't seem related to this PR.

Thanks for taking care of that!

2021-06-10 15:29 UTC, merged