Preferences: Memoize pref handlers to prevent unnecessary re-renders
Automattic/wp-calypso pull request #53757
Opened 2021-06-16 19:32 UTC by mattgawarecki

#### Changes proposed in this Pull Request

* Encapsulate the logic to choose a correct preference handler in a `useMemo`, to reduce unnecessary re-renders when the Preferences Helper is visible.
* Encapsulate the `unsetPreference` action in a `useCallback`, to reduce unnecessary re-renders when the Preferences Helper is visible.
* Make the `Preference` component functional (as opposed to class-based).

#### Testing instructions

* In a local testing environment, start Calypso Blue.
* Open the Preferences Helper by going to the bottom right corner, hovering over the environment name, and then hovering over **PREFERENCES** in the menu that pops out.
* Verify that you're able to manage your user preferences just as in production: deleting should be possible for all items, and altering should be possible for all but the most complex data types.

#### Reference captures

2021-06-21 20:23 UTC, a8ci18n commented on client/lib/preferences-helper/string-preference.tsx
> +						{ translate( 'reset' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **10** times:
`translate( 'Reset ' )` *ES Score: 9*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/unnecessary-renders-in-prefs-helper)

2021-06-21 21:22 UTC, cbauerman requested changes
<img width="1591" alt="Screen Shot 2021-06-21 at 2 20 38 PM" src="https://user-images.githubusercontent.com/2810519/122829547-ff4e0880-d29b-11eb-9855-6ff92b06456d.png">

Something changed styling-wise, this window shouldn't be _quite_ so wide 😛

2021-06-22 08:42 UTC, tyxla reviewed
I haven't reviewed it thoroughly yet, but several questions and thoughts come to mind at first glance:

* I really appreciate the Lodash refactors 🙌 
* Do we really want to add translations here? The preferences helper (and all of the environment badge tools) are not available in production, so wouldn't that be a waste of time and money for translation? 
* If we're overhauling the visual part, is it a good time to adopt `@wordpress/components`? Would that save us most of the styles necessary?
* Going through the code and the PR description, it seems like this one includes several PRs. Does it make sense to split it into better-defined logical pieces of changes?

2021-06-23 05:37 UTC, jsnajdr commented on client/lib/preferences-helper/boolean-preference.tsx
>  						disabled={ value === localValue }
This `disabled` prop is always `false` and can be omitted, because the entire buttons fragment is rendered only when `value !== localValue`

2021-06-23 05:37 UTC, jsnajdr commented on client/lib/preferences-helper/boolean-preference.tsx
> +						className="preferences-helper__preference-save"
Does the `__preference-save` need to always contain the `preference` word? It's already in the prefix, so the class names seem too wordy to me.

2021-06-23 05:37 UTC, jsnajdr commented on client/lib/preferences-helper/preference-list.js
> +	const sortedPreferenceItems = useMemo( () => {
Does the `useMemo` perform any useful optimization here? I think it doesn't. The `PreferenceList` component doesn't have any props and rerenders only when the `preferences` selector returns a new value. But then `sortedPreferenceItems` needs to be re-calculated, despite the `useMemo`. If the `preferences` value doesn't change, `PreferenceList` is never rerendered and the memoized value never has a chance to be used.

2021-06-23 05:40 UTC, jsnajdr commented
> If we're overhauling the visual part, is it a good time to adopt `@wordpress/components`?

This is something I was experimenting with when writing the `AuthHelper` for switching between OAuth and cookies. The Calypso helpers' UI is very primitive and would deserve to be rewritten using standard components: popovers, forms...

2021-06-23 13:06 UTC, sarayourfriend commented
If you end up deciding to re-write using `@wordpress/components`, feel free to reach out to the @Automattic/team-calypso-components squad ❤️

2021-06-23 17:38 UTC, mattgawarecki commented
>     * Going through the code and the PR description, it seems like this one includes several PRs. Does it make sense to split it into better-defined logical pieces of changes?

On reflection, I think @tyxla's right. I'll be taking everyone's feedback into account here, but I'm closing this PR and making some more focused ones to replace it.

2021-06-23 17:38 UTC, closed without merging