My Home: Restyle the stats card
Automattic/wp-calypso pull request #54008
Opened 2021-06-25 02:27 UTC by roo2

Update the style of the stats card to match the new my-home designs in https://github.com/Automattic/wp-calypso/issues/53213

I added hover and focus states to the stats link.
I also kept the font size at 14px to match the quick links which were set as 16px in the design but then changed to be 14px

<img width="450" alt="Screen Shot 2021-06-25 at 2 16 50 PM" src="https://user-images.githubusercontent.com/22446385/123359455-1acd5200-d5c1-11eb-81e4-54bcf6402c8c.png">
<img width="553" alt="Screen Shot 2021-06-25 at 2 16 35 PM" src="https://user-images.githubusercontent.com/22446385/123359491-1d2fac00-d5c1-11eb-8f63-ac30ad14a16b.png">

2021-06-28 03:53 UTC, p-jackson reviewed
Code's good 👍 
Here's some visual things I noticed

<img width="703" alt="desktop" src="https://user-images.githubusercontent.com/1500769/123577608-443be700-d828-11eb-9357-0d26b59d97b1.png">

The "Views" heading should move left, and stat highlight box should have the same round corners as the other cards.
In the mockup the numbers had been removed from the y-axis, but I'm guessing that's an oversight since I think they're important.

<img width="443" alt="mobile" src="https://user-images.githubusercontent.com/1500769/123577807-9c72e900-d828-11eb-91ac-fc35416b0017.png">

Interesting case on mobile here ^^^
Should the internal padding inside those stat boxes match the padding that's used everywhere else? The content of the box is centre aligned so it's not as bit a deal, but I'm guessing this will be quite common because most post titles are going to be longer than the space allows.
Maybe it's not a big deal, since it does take away precious space from the post title. What do you think @jeffgolenski

2021-06-28 04:02 UTC, autumnfjeld approved these changes
I can see the hover effects on "See all stats" box and a small decrease in padding.  

BEFORE 
![image](https://user-images.githubusercontent.com/5665959/123578401-1bf8bc00-d819-11eb-8d83-d0a46188a122.png)


AFTER
![image](https://user-images.githubusercontent.com/5665959/123578392-156a4480-d819-11eb-9495-fd7802397e54.png)

2021-06-28 16:41 UTC, jeffgolenski commented
Good eye @p-jackson. 

We should definitely keep the padding consistent here. IMO I don't think the top post title is useful here as it stands since it already cuts off any realistic title. In the medium term work I'm exploring a better stats area for my home anyway. So perhaps in the near future we'll be improving this entire area.

2021-06-28 21:26 UTC, autumnfjeld requested changes, later dismissed
I just saw Phil's & Jeff's comments, so defer to them and not my approval.

2021-06-29 10:40 UTC, roo2 commented
I pushed changes to hopefully address all of that feedback and tidy up the appearence of the stats chart on different breakpoints.
#### Mobile
<img width="454" alt="Screen Shot 2021-06-29 at 10 31 18 PM" src="https://user-images.githubusercontent.com/22446385/123783485-83eaf780-d92a-11eb-997e-326c41f5247a.png">

#### Tablet
<img width="721" alt="Screen Shot 2021-06-29 at 10 29 21 PM" src="https://user-images.githubusercontent.com/22446385/123783512-89e0d880-d92a-11eb-8095-a2d2961b9c17.png">

#### Desktop
<img width="677" alt="Screen Shot 2021-06-29 at 10 38 26 PM" src="https://user-images.githubusercontent.com/22446385/123783683-c01e5800-d92a-11eb-9263-8f6d28b2454c.png">

2021-06-29 20:10 UTC, jeffgolenski commented
Looks great from a design perspective @roo2. We'll just need to ensure we ship it in conjunction with the short term style changes so it doesn't stand out like this: 

![Screen Shot 2021-06-29 at 4 09 32 PM](https://user-images.githubusercontent.com/214813/123860919-89c5e600-d8f4-11eb-8762-26310cb8206b.png)

Thanks for the quick work here!

2021-06-30 02:52 UTC, p-jackson commented
Found another weird thing

The "See all stats" button looks fine when you shrink the desktop browser down to mobile width
<img width="487" alt="smalldesktop" src="https://user-images.githubusercontent.com/1500769/123894588-8729c600-d9b2-11eb-94b5-08a53ae7fa9e.png">


But for some reason, when you enable proper mobile emulation the height of the button is wrong
<img width="487" alt="mobile" src="https://user-images.githubusercontent.com/1500769/123894637-9b6dc300-d9b2-11eb-948e-1840ee58888f.png">

I looked in the inspector for a couple seconds and didn't see where the issue was coming from. Maybe there's some CSS class that's added when the user-agent is specifically mobile?

2021-06-30 05:29 UTC, roo2 commented
good catch @p-jackson, it was the default padding from `.card` which was removed from larger screens but not mobile, I pushed a simple fix.

2021-06-30 05:47 UTC, p-jackson approved these changes
LGTM!

Thanks for squashing all the nitty gritty bits.

Now we just need to get #54059 done!

> [We'll just need to ensure we ship it in conjunction with the short term style changes](https://github.com/Automattic/wp-calypso/pull/54008#issuecomment-870883053)

Luckily #54059 looks fine without this PR so it can go first I guess.

2021-07-01 12:18 UTC, roo2 commented
<img width="537" alt="Screen Shot 2021-07-02 at 12 17 03 AM" src="https://user-images.githubusercontent.com/22446385/124123014-de22be80-daca-11eb-973a-9a7bd2d4d86b.png">
I'm just fixing an issue with the stats card when it's empty and has the stats help CTA

2021-07-01 21:16 UTC, roo2 commented
I fixed the issue with the no traffic state by adding another class to the `<Card>`
<img width="548" alt="Screen Shot 2021-07-02 at 9 14 25 AM" src="https://user-images.githubusercontent.com/22446385/124190343-36cb7900-db16-11eb-8093-54f6d2c58e3e.png">
<img width="585" alt="Screen Shot 2021-07-02 at 9 14 19 AM" src="https://user-images.githubusercontent.com/22446385/124190352-3a5f0000-db16-11eb-8f7f-96f0a5fce073.png">
<img width="607" alt="Screen Shot 2021-07-02 at 9 14 11 AM" src="https://user-images.githubusercontent.com/22446385/124190356-3b902d00-db16-11eb-8146-a48a69df7717.png">

2021-07-01 22:05 UTC, p-jackson approved these changes
👍 LGTM @roo2

2021-07-01 22:56 UTC, merged