Help: Update Forums "Meta Information" Message
Automattic/wp-calypso pull request #54052
Opened 2021-06-26 11:18 UTC by Aurorum

#### Changes proposed in this Pull Request

* This implements the changes outlined by @supernovia in https://github.com/Automattic/wp-calypso/pull/52979#issuecomment-866346708

I should note that there will probably need to be another change made to this file when the next Jetpack release is out, since then we can be more confident as to whether or not a piece of data is "Unknown". I'd recommend looking at the discussion in #52979 for greater context about this change.

#### Testing instructions

When submitting a Forums message through the Help form, verify that it follows a format identical to the one outlined in https://github.com/Automattic/wp-calypso/pull/52979#issuecomment-866346708. You can see this example here, though please note I've fixed the site URL error in this thread but I just didn't want to make a new one: https://wordpress.com/forums/topic/testing-proposed-forums-feature/

**Before:**
<img width="834" alt="Screenshot 2021-05-20 at 19 43 49" src="https://user-images.githubusercontent.com/43215253/119032131-bc9ac700-b9a3-11eb-904c-16a2c3f06399.png">

**After:**
<img width="849" alt="Screenshot 2021-06-26 at 12 17 05" src="https://user-images.githubusercontent.com/43215253/123511310-71499780-d678-11eb-9cdc-cc4198869639.png">

cc @sixhours

Related to #52979

2021-06-26 11:26 UTC, a8ci18n commented on client/me/help/help-contact/index.jsx
> +			blogHelpMessage = translate( 'Site: %(siteUrl)s.', {
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **10** times:
`translate( 'Site: %(siteURL)s' )` *ES Score: 7*

2021-07-09 20:00 UTC, sixhours requested changes
I started testing this out! I selected one of my sites, and entered my own site, and did *not* opt to hide it in either case, but it shows up like this:

<img width="497" alt="Screen Shot 2021-07-09 at 3 57 39 PM" src="https://user-images.githubusercontent.com/2124984/125130125-72de7b00-e0ce-11eb-9128-abff031183e9.png">

2021-07-09 20:00 UTC, sixhours commented on client/me/help/help-contact/index.jsx
> +					'\nWP.com: ' +
For maximum context for translators, this should probably be wrapped for translation as one whole "sentence" ie. `translate( 'WP.com: %s' )` where `%s` is the status.

2021-07-09 20:00 UTC, sixhours commented on client/me/help/help-contact/index.jsx
> +			blogHelpMessage += '\nCorrect account: ' + correctAccountMessage;
Same here, "Correct account:" is not ready for translation, and we should probably treat "Correct account: [Status]" as a complete sentence for the best context.

2021-07-09 20:00 UTC, sixhours commented on client/me/help/help-contact/index.jsx
> +				blogHelpMessage += '\nWP.com: ' + this.translateForForums( 'Yes' );
For maximum context for translators, this should probably be wrapped for translation as one whole "sentence" ie. `translate( 'WP.com: %s' )` where `%s` is the status.

2021-07-11 13:28 UTC, Aurorum commented
Thanks for spotting those translation errors @sixhours! They should be fixed with the latest commit. :)

2021-07-12 14:04 UTC, sixhours approved these changes
<img width="736" alt="Screen Shot 2021-07-12 at 9 53 40 AM" src="https://user-images.githubusercontent.com/2124984/125300304-e57e6f00-e2f7-11eb-9516-ebca1bb702f6.png">

I wouldn't consider this a blocker, but I found I can end up in this state with the "I need help with a different site" box unchecked but the text input for it showing, so it's confusing as to which URL is being submitted. A bit edge-case-y but could result in the wrong URL getting passed to the forums.

To reproduce:

* Submit an initial support request with the "I need help with a different site" box checked and the text input filled in
* Click the "Back" arrow once your request is submitted; you'll be brought to the `/help` screen
* Click "Contact Support" and see the above

Also a couple tiny nitpicks about punctuation that are obviously not blockers. :)

2021-07-12 14:04 UTC, sixhours commented on client/me/help/help-contact/index.jsx
> +				blogHelpMessage += this.translateForForums( '\nWP.com: Unknown \nJetpack: %s.', {
Nitpick, I think you can nix the period here.

2021-07-12 14:04 UTC, sixhours commented on client/me/help/help-contact/index.jsx
> +			blogHelpMessage += this.translateForForums( '\nCorrect account: %s.', {
Same for the period here.

2021-07-12 14:05 UTC, sixhours commented on client/me/help/help-contact/index.jsx
> +				blogHelpMessage += this.translateForForums( '\nWP.com: Unknown \nJetpack: %s.', {
Also I don't think you need to include the newline in the translation; if you do, add a translator comment so folks know it's not part of the language.

2021-07-12 14:05 UTC, sixhours commented on client/me/help/help-contact/index.jsx
> +			blogHelpMessage += this.translateForForums( '\nCorrect account: %s.', {
And the newline. :)

2021-07-13 19:01 UTC, Aurorum commented
Thanks @sixhours! Both those issue should be fixed now; I figured it just made sense to reset the states on submitting the form (so the message textbox will also be empty again).

2021-07-13 21:14 UTC, sixhours approved these changes
I think this is good to go! I'll plan to deploy it tomorrow. :) Thanks @Aurorum !!

2021-07-14 14:18 UTC, merged

2021-07-15 16:42 UTC, supernovia commented
Ahhhh! I missed a week of notifications because I was out on vacation & had other stuff to finish before and catch up with after. I still have other items I need to get through, tbh!

But I noticed this change yesterday and I love it! Thank you @Aurorum  &  @sixhours!

2021-07-15 20:36 UTC, Aurorum commented
Thanks @supernovia, I hope you had a nice vacation! As always, please feel free to let me know if there's any other tweaks to this that would be helpful. :)

2021-07-20 00:19 UTC, supernovia commented
Thank you!!!