Plans: Adapt Jetpack Free card so its code can be re-used
Automattic/wp-calypso pull request #54259
Opened 2021-07-02 19:52 UTC by mattgawarecki

Relates to `1200412004370260-as-1200532973279652`.

#### Changes proposed in this Pull Request

* Extract the core implementation of `JetpackFreeCard` and `JetpackFreeCardButton` into a new component, `ProductWithoutPrice`, that can be re-used for Jetpack CRM Free (or other free products in the future).
* Re-write `JetpackFreeCard` to use `ProductWithoutPrice`.
* Move `JetpackFreeCard` under the `my-sites/` hierarchy, since that's the only place it's used.
* Re-write the existing unit tests from `JetpackFreeCardButton` so that they test the `useJetpackFreeButtonProps` hook.

#### Testing instructions

* Evaluate styles, implementation, and unit test code, ensuring they're readable and intuitive.
* Verify that in all Calypso experiences, the "Get started for free" button on the Jetpack Free product card looks and behaves exactly the same as in production.
* Verify that all unit tests still pass.

2021-07-02 19:53 UTC, mattgawarecki commented on client/components/jetpack/card/product-without-price/style.scss
> +.product-without-price--full-width {
This `--full-width` variant will become important as I build the PR to add Jetpack CRM Free to the bottom grid row.

2021-07-02 20:03 UTC, mattgawarecki commented on client/my-sites/plans/jetpack-plans/types.ts
> +	fullWidth?: boolean;
This property is what triggers the activation of the `--full-width` style variant I mentioned earlier.

2021-07-05 17:17 UTC, monsieur-z requested changes
It looks good to me code wise, and the pricing page behaves as expected. One test is failing, though.

2021-07-06 13:52 UTC, monsieur-z approved these changes
Looking good now! Thanks for taking the time to do this.

2021-07-06 14:04 UTC, merged