Activity Log: Extract 'Share this event' into separate component
Automattic/wp-calypso pull request #54420
Opened 2021-07-09 19:42 UTC by mattgawarecki

Since the `ActivityCard` component has grown quite large, I thought it might be nice to start extracting bits and pieces from it and converting them from a class-based to a function-based structure.

#### Changes proposed in this Pull Request

##### Refactor

* Extract the `renderShareButton` method from `ActivityCard` into a new component called `ShareActivity`.
* Remove extracted code from `ActivityCard`, replacing it with instructions to render an instance of `ShareActivity`.

##### Bugfixes (incidental)

* Alter `ActivityCard` CSS and markup to ensure the 'Share this event' button is visible on all Activity cards where it's applicable, as long as the `jetpack/activity-log-event-sharing` flag is enabled.
* Update parameters passed to Tracks events for event sharing so they're tracked properly, with both the current site ID and the shared event's rewind ID.

#### Testing instructions

In either Calypso Blue or Calypso Green, visit the Activity Log; alternatively, Backup page for a site with Backup Real-time.

##### Share button refactor and screen positioning

**Expected behavior:** 'Share this event' button is located at the right side of the ActivityCard header, beside the time display.
**Actual behavior:** 'Share this event' button is not visible on any Activity card.

* Verify that the 'Share this event' button is visible on non-summarized Activity cards and looks/functions intuitively. Test specifically for click-out behavior, invalid email input, and various screen sizes.

##### Share button analytics tracking

**Expected behavior:** Tracks events are emitted when the 'Share this event' button is clicked and when an event is shared, with valid and correct parameters for the current site ID and selected event's rewind ID.
**Actual behavior:** Tracks events are emitted, but sometimes without the selected event's rewind ID. Site ID is always included, but the parameter name is incorrectly formatted as `siteId` instead of `site_id`, and its value is always rendered as `[object Object]`.

* Verify that when you click the 'Share this event' button and a popover is displayed, a Tracks event `calypso_activity_share_popup` is emitted with parameters for `site_id` and `rewind_id`.
* Verify that when you input an invalid email address, you are unable to share the event and the email field is put into an error state.
* Verify that when you input a valid email address, the event is sent successfully and two Tracks events are emitted with parameters for `site_id` and `rewind_id`, and those parameters have the correct (integer) values:
  * `calypso_activity_share_request`
  * `calypso_activity_event_share_success`

#### Reference screenshots

##### Activity card list (before / after)

<img width="500" alt="image" src="https://user-images.githubusercontent.com/670067/125127940-eb3f3f00-e0c2-11eb-8728-f944ba260a11.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/670067/125127816-b9c67380-e0c2-11eb-9970-c5978af1cf8a.png">

##### Share button popover

<img width="369" alt="image" src="https://user-images.githubusercontent.com/670067/125128059-11fd7580-e0c3-11eb-8003-acb9cc1200d3.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/670067/125128363-9223db00-e0c3-11eb-8308-8269eb850a8c.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/670067/125128435-a9fb5f00-e0c3-11eb-87aa-5b66796eed29.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/670067/125128530-c26b7980-e0c3-11eb-9286-f26d668bc5be.png">

2021-07-12 15:33 UTC, monsieur-z requested changes
Everything tested well from a user standpoint. However, the `calypso_activity_share_request` event is dispatched without any site or rewind id.

Despite what's mentioned in the instructions, the feature flag `jetpack/activity-log-sharing` is only activated for cloud development and staging. Is that expected?

Finally, being able to submit the email form on pressing the Enter key would be welcome. But definitely a nice-to-have.

2021-07-13 20:27 UTC, mattgawarecki commented
> Everything tested well from a user standpoint. However, the `calypso_activity_share_request` event is dispatched without any site or rewind id.

Fixed (pending re-review) -- thanks and good catch 🙂 

> Despite what's mentioned in the instructions, the feature flag `jetpack/activity-log-sharing` is only activated for cloud development and staging. Is that expected?

I actually hadn't look too closely to see the environments for which the flag is enabled. I think I heard this started as a HACK week project; perhaps there wasn't enough time to fully test and deploy for everyone?

> Finally, being able to submit the email form on pressing the Enter key would be welcome. But definitely a nice-to-have.

I agree -- added, can you test this as well?

2021-07-14 13:08 UTC, monsieur-z commented
> I think I heard this started as a HACK week project; perhaps there wasn't enough time to fully test and deploy for everyone?

Unfortunately I don't know about that.

2021-07-14 13:09 UTC, monsieur-z approved these changes
Everything tests well now!

2021-07-14 13:12 UTC, merged

2021-07-14 15:02 UTC, mattgawarecki commented
@jessefriedman @atanas-dev @keoshi I've already deployed this PR, but I'd love to get your feedback regarding what's left before we feel safe exposing this (awesome!) feature to all our customers. Are there any outstanding issues with it? The only one I'm aware of is the possibility of people sending lots of emails in a short time period, which I'm willing to help with in a separate PR.

2021-07-15 11:02 UTC, keoshi commented
Thanks for the ping @mattgawarecki ! I don't have all the details and from what I can remember @atanas-dev brought up some of the technical concerns to systems, but sending X emails was definitely one of them. We even discussed limiting to 10 emails a day, but I don't know where we landed with that.

2021-07-15 12:22 UTC, jessefriedman commented
We settled on a 5 email per day limit. I think that’s the only outstanding
item.

On Thu, Jul 15, 2021 at 7:02 AM Filipe Varela ***@***.***>
wrote:

> Thanks for the ping @mattgawarecki <https://github.com/mattgawarecki> ! I
> don't have all the details and from what I can remember @atanas-dev
> <https://github.com/atanas-dev> brought up some of the technical concerns
> to systems, but sending X emails was definitely one of them. We even
> discussed limiting to 10 emails a day, but I don't know where we landed
> with that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Automattic/wp-calypso/pull/54420#issuecomment-880602960>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANLHYRMAE4RRQC5TPCM3MTTX255ZANCNFSM5ADKZH3A>
> .
>
-- 
*Jesse Friedman*
Director of Innovation for Jetpack Business
Automattic <http://automattic.com/> | Jetpack <http://jetpack.com/> |
WordPress.com <http://wordpress.com/>