Jetpack site-less Checkout: Add site-less redirect to the product purchase route
Automattic/wp-calypso pull request #54857
Opened 2021-07-23 21:25 UTC by cbauerman

#### Changes proposed in this Pull Request

* `/purchase-product/jetpack_search/*` -> `/checkout/jetpack/jetpack_search_*`

#### Testing instructions

1. Boot branch
2. Verify navigating to `/purchase-product/jetpack_search/monthly` redirects to `/checkout/jetpack/jetpack_search_monthly`
3. Verify navigating to `/purchase-product/jetpack_search/yearly` redirects to `/checkout/jetpack/jetpack_search`
4. Verify `/purchase-product/wpcom_search/yearly` and `/purchase-product/wpcom_search/monthly` do not redirect

2021-07-23 21:40 UTC, rcanepa commented on client/my-sites/purchase-product/controller.js
> +	isJetpackProductSlug,
`isJetpackProductSlug` relies on `JETPACK_PRODUCTS_LIST` which uses `JETPACK_SEARCH_PRODUCTS`. The latter is defined as:
```
export const JETPACK_SEARCH_PRODUCTS = <const>[
	PRODUCT_JETPACK_SEARCH,
	PRODUCT_JETPACK_SEARCH_MONTHLY,
	PRODUCT_WPCOM_SEARCH,
	PRODUCT_WPCOM_SEARCH_MONTHLY,
];
```

🙃

2021-07-23 21:41 UTC, rcanepa requested changes
> Verify navigating to /purchase-product/jetpack_search/monthly redirects to /checkout/jetpack/jetpack_search_monthly
> Verify navigating to /purchase-product/jetpack_search/yearly redirects to /checkout/jetpack/jetpack_search

Yes, both work as expected!

> Verify /purchase-product/wpcom_search/yearly and /purchase-product/wpcom_search/monthly do not redirect

They do redirect to checkout 🙁

2021-07-23 22:11 UTC, cbauerman commented
> 
> 
> > Verify /purchase-product/wpcom_search/yearly and /purchase-product/wpcom_search/monthly do not redirect
> 
> 
> 
> They do redirect to checkout 🙁 

I did not push my last set of changes :P I'll do that and ask for a re-review

2021-07-26 15:53 UTC, cbauerman commented
@rcanepa the changes I was wiring the test instructions are now in the brach, ready for re-review.

2021-07-26 16:22 UTC, rcanepa approved these changes
LGTM now. Everything works as expected!

2021-07-26 16:49 UTC, merged