Change domain search page title to "Search for a domain"
Automattic/wp-calypso pull request #55034
Opened 2021-07-29 18:00 UTC by leonardost

#### Changes proposed in this Pull Request

This PR updates the layout of domain suggestions cards in the domain registration search page. This corresponds to task 8 of pcYYhz-e4-p2, which is part of a redesign of many parts of the domains pages.

#### Testing instructions

TBD

2021-08-04 11:41 UTC, poligilad-auto requested changes
Nice work @leonardost! Excuse me for the long list but these are a lot of changes :) 

General comments:

1. Make the additional domains (below the two suggested ones) vertically aligned. Seems like this can be done by removing `margin-bottom: 8px;` from `.domain-registration-suggestion__title-wrapper`.
2. Make `.domain-registration-suggestion__domain-title-name`  `var(--studio-gray-60);`.
3. Make `.domain-registration-suggestion__domain-title-tld`  `var(--studio-gray-90);`.
4. Make `.domain-registration-suggestion__domain-title`  `$font-body`.
5. All the _select buttons_ should be 40px high, not sure why they are all 31px now.
6. We have this strange _loading_ state for all the select buttons when clicking on one. Can we get rid of the loading state altogether?
7. _Close match etc._ should be `$font-body-small`.

**Align price display with onboarding:**
When the first year is free it should look like this. Wanted to double check this with you @kelliepeterson 
![image](https://user-images.githubusercontent.com/83961704/128172095-d98e19e2-6442-42a5-902d-a99b09ba113b.png)

1. Make .`domain-product-price__free-text` font-size `$font-body-small`, font-weight `500`., color: `var( --color-success-60 );`.
2. Make `.domain-product-price__price` `$font-body-small` and with a strikethrough.

When the domain is paid for it should look like this:
![image](https://user-images.githubusercontent.com/83961704/128173592-64e6a21a-d8c2-4720-a67b-c003c1e28fe3.png)

1. Make the domain price `font-weight 500`.
2. Make the /year `$font-body-small`.

Domains on sale:
Should look like this. Wanted to double check this with you @kelliepeterson.
![image](https://user-images.githubusercontent.com/83961704/128173684-d9a1b47f-1afd-41b0-8f89-cab005cdebf6.png)

1. The badge: make the background color  `var(--color-warning-10);`.
2. Put the _sale badge_ after the _best alternative badge_.
3. Make `.domain-product-price__sale-price` font-weight 600 & color `var( --studio-orange-50 );`
4. Change the copy.

For mobile: 
1. Just noticed when I see _best alternative_ & the _sale_ badge that it breaks the layout.

I'll go over it again afterwards and also checkout mobile more in depth.

Thank you!

2021-08-04 20:59 UTC, delputnam approved these changes
From a code perspective, this LGTM. Nice job on keeping changes here separate from the reskinned /start flow. 😅

2021-08-05 22:09 UTC, leonardost commented
Hi @poligilad-auto, thank you for the thorough review! I think I addressed all your observations 😄 

I have two questions:

- I've changed the button behavior to only show the "busy" state on the button we click on, all the others are disabled. It looks like this:

https://user-images.githubusercontent.com/5324818/128427084-779a6aeb-362e-48fd-a8cd-9a95fe55b154.mp4

Do you think that looks fine or is it still weird?

- I'm not sure about the copy for domains on sale. Do you think we should remove the "Renews at" text? Will users understand the value below is the renewal price for the first year afterwards? What do you think @kelliepeterson?

<img width="1067" alt="Screen Shot 2021-08-05 at 19 06 41" src="https://user-images.githubusercontent.com/5324818/128427475-7ec0d089-30ef-4e95-84cb-50d2d22588d3.png">

2021-08-09 09:12 UTC, poligilad-auto commented
Thanks for all the changes @leonardost, looking much better.

**Some small clarifications:**
1. When the domain is free: "Free for the first year" should be `$font-body-small`. The price below should be font-weight 400.
2. For the sale price: The sale price should stay `$font-body`, but the text "for the first year" should be `$font-body-small`. The text below should all be`$font-body-small` and with a strikethrough. That aligns with the way we display the price when the domain is free. The strikethrough price indicates the regular price and the sale price is above. I think that's clear. @kelliepeterson have any thoughts?
![image](https://user-images.githubusercontent.com/83961704/128682980-f3ca5f45-1715-48d8-bab4-fcbf461a9ef4.png)

> I've changed the button behavior to only show the "busy" state on the button we click on, all the others are disabled. It looks like this:

That's a setup in the right direction :) I'm not fan of this type of loading state, it's a bit outdated. 
For this I want to ask, do we actually need a loading state or could we just move on to the next step here? We barely use this in Dotcom, I only noticed it in the checkout.

Also, I noticed that we see the "In cart" button + the cart on top for one second before moving on, could we not show this and just move on to the next step?

**One other small thing:**
With the two "recommended" domains, when we have no explanations below the domain name isn't aligned to the center, cause there is some extra padding there.

2021-08-09 22:06 UTC, leonardost commented
Hey @poligilad-auto, I've fixed the layout observations you made, could you take another look?

> That's a setup in the right direction :) I'm not fan of this type of loading state, it's a bit outdated.

I feel you, I'm not a huge fan either 😄 I believe it's possible to skip the loading state and go straight to the next step, but I'm afraid it'd be more complicated than the previous updates. When we click the "Select" button, we do an availability check for the domain on the backend - if for whatever reason it isn't available (TLD on maintenance, already registered, etc.) a notice is shown for the user and they have to choose another one before proceeding.

<img width="1052" alt="Screen Shot 2021-08-09 at 18 53 48" src="https://user-images.githubusercontent.com/5324818/128779465-15af5589-daef-49f4-80f0-c4e63176bb45.png">

The shopping cart issues are somewhat similar, but related to the shopping cart code.

Changing those would involve moving or reworking some of the logic, which might get messy 😅 would it be ok if we postpone these improvements to a later iteration?

2021-08-10 08:16 UTC, poligilad-auto commented
Hey @leonardost,
Thanks for the changes and the explanation!

> Changing those would involve moving or reworking some of the logic, which might get messy 😅 would it be ok if we postpone these improvements to a later iteration?

Yes, sure. Let's postpone. It's not a big issue.

**All the changes are looking great, just 1 small thing to change and 1 thing I spotted on mobile:**
![image](https://user-images.githubusercontent.com/83961704/128832160-48721eca-814b-48ee-89e0-7a2e94c9ca7c.png)
1. Sale price: can you make the "/year" also `$font-body-small`
2. In mobile view can we make the domain name for the 2 suggested domains `$font-title-small`. They look to similar to the other results now.

That's it!

2021-08-10 17:48 UTC, leonardost commented
Hi @poligilad-auto, thanks for the review! I've fixed these two last observations now.

2021-08-11 07:55 UTC, poligilad-auto approved these changes
Nice job @leonardost 👌

2021-08-11 22:21 UTC, merged

2021-08-11 23:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6402588

Thank you @leonardost for including a screenshot in the description! This is really helpful for our translators.

2021-08-19 21:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6402588).

2021-10-22 11:46 UTC, tyxla commented on client/components/domains/domain-registration-suggestion/index.jsx
> +		title = this.renderDomainParts( domain );
Nit: I've noticed that we always overwrite the previous value of `title` here, so the previous line is actually unnecessary. and we can directly make it a `const` here. Is this something you'd like to follow up with?

2021-10-22 12:17 UTC, delputnam commented on client/components/domains/domain-registration-suggestion/index.jsx
> +		title = this.renderDomainParts( domain );
Oh! Good catch @tyxla. Thank you! I'll add a task for us (Nomado) to fix this.

2021-10-22 12:20 UTC, tyxla commented on client/components/domains/domain-registration-suggestion/index.jsx
> +		title = this.renderDomainParts( domain );
Thanks a bunch, @delputnam! 🙌  No rush FWIW.