Domains: Update domain search empty state and input placeholder
Automattic/wp-calypso pull request #55254
Opened 2021-08-06 17:45 UTC by rafaelgalani

#### Changes proposed in this Pull Request
This PR adds the new empty content state on the domain search page.
The illustration for the domains' empty content and an animated placeholder on the search bar were also added.

#### Testing instructions
- Visit `/domains/add` page and select a domain for testing;
- Check that the empty content state is shown if there's no search term input;
- Check that the search bar has a placeholder that changes the TLD with a typing animation.

#### Preview

**No search term**

![image](https://user-images.githubusercontent.com/18705930/128550559-836a2240-8c26-4bc6-8d15-00cd8c3d4af7.png)

**Search term shorter than the minimum allowed**

![image](https://user-images.githubusercontent.com/18705930/128550633-f999c6cc-fe8d-4e78-86dc-bcc40cbfe2bd.png)

**Search bar animated placeholder**

https://user-images.githubusercontent.com/18705930/128550939-437f5c3e-dd9c-438a-9d7a-4c71db7bf26a.mov

2021-08-10 07:57 UTC, poligilad-auto requested changes
Hey @rafaelgalani, cool animation with the TLD's!

Some changes:
1. Make the illustration smaller: 180px wide.
2. Add in the text bellow, like in the design.

![image](https://user-images.githubusercontent.com/83961704/128829318-4345dfd3-915d-46a5-a21a-0d9e862802a6.png)

Regarding the list of TLD's: I think it's better if we start off with the "Recommended endings" and then move on to the rest of the list.

Question: I assume wrapping the elements together, the search bar and the illustration are a separate task?

2021-08-10 14:09 UTC, rafaelgalani commented
@poligilad-auto Thanks for the review!

> Add in the text bellow, like in the design.

Should the text be always displayed, or only in the empty state?

> Regarding the list of TLD's: I think it's better if we start off with the "Recommended endings" and then move on to the rest of the list.

Hmm... This might be possible, but it would add more complexity to this PR, so I think it would be better if we did this in a separate follow up PR. 

> Question: I assume wrapping the elements together, the search bar and the illustration are a separate task?

Yes! That will be done in a separate PR.

2021-08-10 15:03 UTC, rafaelgalani commented
@poligilad-auto I'll be adding the text on the empty state as we talked.
Here's the result. I will also update the previews as well: 

![image](https://user-images.githubusercontent.com/18705930/128890390-ba8bc518-41f3-411c-97d9-9eaa9a8a4b7f.png)

2021-08-11 03:25 UTC, delputnam commented
@rafaelgalani For Poli's suggestion to "start off with the 'Recommended endings'"...what would you think about doing something like created a hardcoded list of like 5-6 "top" TLDs, add those to the top of the list, and remove them from the rest of the list. Since this is basically a form of placeholder text, I'd be ok with a hardcoded list if you are?  ...just a thought.

2021-08-11 03:28 UTC, delputnam commented
@poligilad-auto This also affects /start/domains, is this ok?

Also, for /start/domain/domain-only, it looks like this:

<img width="1260" alt="Screen Shot 2021-08-10 at 11 26 53 PM" src="https://user-images.githubusercontent.com/1379730/128965058-e12c2570-3c20-4b4f-982d-0de5ed432af0.png">

I just wanted to see if that is ok.

2021-08-11 03:31 UTC, delputnam approved these changes
Approving this from a code perspective. Nice job on the typer component too. :-) 

Let's make sure that we don't need to make any more changes for what is shown for onboarding and new sites before we deploy though.

2021-08-11 04:55 UTC, rafaelgalani commented
@delputnam 
Thanks for the review!

>Let's make sure that we don't need to make any more changes for what is shown for onboarding and new sites before we deploy, though.

I already have these committed locally. I'll push them, and then it's up to Poli 😸 
It's looking like this: 

Domain-only flow:

![image](https://user-images.githubusercontent.com/18705930/128971026-7686e9de-02d0-4205-ae64-772e241b9368.png)

Start: 

![image](https://user-images.githubusercontent.com/18705930/128971450-c461ca02-7b18-42a9-a5ca-bc81966c232b.png)

I just adjusted the CSS. I didn't change the initial state of these flows... Should I replace them with the empty content component as well?

---

> Since this is basically a form of placeholder text, I'd be ok with a hardcoded list if you are

The `useTyper` hook doesn't have these options implemented (typing in a fixed order, callbacks, etc.)
So we'd have to implement these... I think the PR can get too big, and it'd also take some more time if we were to add this; that's why I suggested adding these in a separate one 😄 
But apart from that, I think that's OK. As long as we don't keep reusing the list elsewhere... 😅

2021-08-11 08:14 UTC, poligilad-auto commented
Hey @rafaelgalani, I'm not seeing your changes yet, so I'll review once it's live.

**For the onboarding flows, I rather not make these changes as is because they weren't designed for those screens**.

What we could do:
1. for the start flow: have the functionality to clear the search and go back to the original starting state (not ours). Including their place holder text "Type the domain you want here".
2. For the blue flow: have the functionality to clear the search and go back to the original starting state. 
WDYT?

Also I'm noticing some layout issues with the "X" icon in the search bar and the filter icon with this PR. Actually I'm not sure it's this PR, but this is what I'm seeing :)

This is this PR:
![image](https://user-images.githubusercontent.com/83961704/128994007-4c8593bc-d4f9-49a4-9981-124a6b6f824a.png)

And this is the untouched onboarding screen:
![image](https://user-images.githubusercontent.com/83961704/128994058-b85ce08e-bb1a-492f-aa5e-e40808b6711f.png)

2021-08-11 15:58 UTC, rafaelgalani commented
> **For the onboarding flows, I rather not make these changes as is because they weren't designed for those screens**.

@poligilad-auto 
OK, reverting it back. It would be nice if we could get these changes merged though... 😸 

> Also I'm noticing some layout issues with the "X" icon in the search bar and the filter icon with this PR. Actually I'm not sure it's this PR, but this is what I'm seeing :)

Well... I don't know. The PR didn't had the latest `trunk` changes. I rebased on `trunk` - I just check that it is fine on my end, it should be fine for you as well.

2021-08-11 18:57 UTC, delputnam commented
@rafaelgalani I've checked that your fixes to remove the effects of this PR from /start/domain and /start/domains works as expected.  I think we can go ahead and merge this one.  I wasn't able to replicate the issues with the placement of the "X" and the filter icon. So, let's go ahead and deploy this one now.  If we need some additional tweaks, we can open a new PR to handle them.

2021-08-11 19:10 UTC, merged

2021-08-12 05:26 UTC, hambai commented
Just a note that when you rebased this PR some minor changes for the filter button were lost (it was supposed to be placed outside the `Search` component). I'll fix that in #55197 though so no worries