Marketing Survey: Add survey for improved Jetpack cancellation flow
Automattic/wp-calypso pull request #55286
Opened 2021-08-09 13:25 UTC by IanRamosC

#### Changes proposed in this Pull Request

* This component adds the survey that will be used as a step of the new Jetpack cancellation flow via Calypso.
* This PR is related to/ a sub-part of https://github.com/Automattic/wp-calypso/pull/54669 which introduces a new cancellation flow for Jetpack plans/ products

#### Testing instructions

The visual output of this component can be seen by testing PR #54669
* Either check out the branch from PR #54669 locally or use the Calypso live link on that branch to get a preview. 
* Review the testing instructions on PR #54669 to check the visual output
* Make sure it looks like the screenshot below

![image](https://user-images.githubusercontent.com/5714212/128713392-47930dd5-6d9b-4f68-aa84-804bb8f5184a.png)

2021-08-09 13:34 UTC, a8ci18n commented on client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-survey.tsx
> +						placeholder={ translate( 'share your experience' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **27** times:
`translate( 'share your experience…' )` *ES Score: 9*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/survey-for-improved-jetpack-cancellation-flow)

2021-08-12 14:16 UTC, jboland88 requested changes
A few changes outlined in the comments :)
I also noticed that the first and second steps in the cancellation flow look visually different - I think it may be best to define some of the styles that will apply to all the steps in the `cancel-jetpack-form/style.scss` file - some of this styling may be something that is easier done after the smaller sub-parts of this feature are already merged and we are preparing the final PR to enable the new cancellation flow since styling is broken up across different PRs at the moment.

2021-08-12 14:16 UTC, jboland88 commented on client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-survey.tsx
> +			onAnswerChange( answerId, surveyAnswerText );
I think the way that the surveys are recorded, the "text" field is intended for only a custom typed response, here the question text is passed back to the parent component unless it is the `customAnswerText`. Maybe an empty string should be passed if the custom answer is not used.
This seems to be the case in the product cancellation now in `cancel-purchase-form/index.js`: https://github.com/Automattic/wp-calypso/blob/b294868a28ac029094e06c9b9714b0b34a057db9/client/components/marketing-survey/cancel-purchase-form/index.jsx#L171-L190

2021-08-12 14:16 UTC, jboland88 commented on client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-survey.tsx
> +	const [ customAnswerText, setCustomAnswerText ] = useState< string >( '' );
Having the selected answer ID and text here as well as in the state of the parent component may be redundant - would it make sense to pass these values as props?

2021-08-12 14:16 UTC, jboland88 commented on client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-survey.tsx
> +					customAnswerInputRef?.current?.focus();
Nice - I appreciate the auto-focus of the field 👍

2021-08-12 14:16 UTC, jboland88 commented on client/components/marketing-survey/cancel-jetpack-form/style.scss
> +	&__card {
It looks like we need to make the styling for the first and second steps in the cancellation flow more visually consistent. The modal padding, card size and font sizes look to be different between the two steps. Some classes like `.cancel-jetpack-form__step-headline` that are already defined here can be used - maybe defining other styles for all steps in this file would be a better pattern to bring consistency.

2021-08-12 14:16 UTC, jboland88 commented on client/components/marketing-survey/cancel-jetpack-form/jetpack-cancellation-survey.tsx
> +			<FormattedHeader
What do you think about using `.cancel-jetpack-form__step-headline` here to have the headlines look the same between all steps in the cancellation flow?

2021-08-20 20:38 UTC, jboland88 approved these changes
This LGTM 👍  Thanks for the revisions!

2021-08-24 13:05 UTC, merged

2021-08-24 14:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6471374

Thank you @IanRamosC for including a screenshot in the description! This is really helpful for our translators.

2021-09-05 15:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6471374).