Make PeopleProfile a function component and use react-query to fetch external contributors
Automattic/wp-calypso pull request #55537
Opened 2021-08-16 19:33 UTC by naxoc

#### Changes proposed in this Pull Request
I'm hoping to use react-query on the `PeopleProfile` component for another PR I'm working on, and I needed the component to be a functional one for that reason. I don't want to do too much in one PR so it becomes unmanageable, so this PR makes the component functional and introduces a react-query version that gets external contributors. 

Note that there are still other components using the existing `requestExternalContributors` data-getter. It became a little hairy to change them all in one go, so I'm starting with this one. It's not ideal to have both, but it is a good way to make incremental changes. The external contributors call is a good candidate for react-query I think.

This PR also fixes a warning thrown on all `people/team` pages. It mostly looks something like this: 
`Warning: Cannot update a component ('Connect(Localized(PeopleListSectionHeader))') while rendering a different component ('Connect(Localized(WithLocalizedMoment(PeopleProfile)))'). To locate the bad setState() call inside 'Connect(Localized(WithLocalizedMoment(PeopleProfile)))', follow the stack trace as described in https://fb.me/setstate-in-render
    in Connect(Localized(WithLocalizedMoment(PeopleProfile))) (created by PeopleListItem)
...
`

#### Testing instructions
- Verify that the warning mentioned above is gone
- Check that the people listing on `people/team` is behaving like it always has.

2021-08-17 09:05 UTC, AllTerrainDeveloper commented
Hello! Nice work! It looks good to me, but as we are revisiting the component, removing the _Fragment import_ and using the shorthand notation for Fragment is worthy. I know it was already there, but as our Creed says... [I won’t just work on things that are assigned to me](https://automattic.com/creed/wont-just-work/) 🙂 

```
<Fragment>
	<div className="people-profile__role-badge role-contractor">
		{ translate( 'Contractor', {
			context: 'Noun: A user role',
		} ) }
	</div>
	<div className="people-profile__role-badge-info">
		<InfoPopover position="top right">
			{ translate( 'This user is a freelancer, consultant, or agency.' ) }
		</InfoPopover>
	</div>
</Fragment>
```

That piece of code, located in line 217 (I can't comment on it as you didn't do any changes to it)
can be simplified like:
```
<>
	<div className="people-profile__role-badge role-contractor">
		{ translate( 'Contractor', {
			context: 'Noun: A user role',
		} ) }
	</div>
	<div className="people-profile__role-badge-info">
		<InfoPopover position="top right">
			{ translate( 'This user is a freelancer, consultant, or agency.' ) }
		</InfoPopover>
	</div>
</>
```

And therefore you can remove the import that imports the Fragment component 🎉

2021-08-17 09:07 UTC, AllTerrainDeveloper commented on client/my-sites/people/people-profile/index.jsx
> +import React, { Fragment } from 'react';
```suggestion
import React from 'react';
```

I've left a comment in the conversation tab, where you can check how to remove this Fargment import 🙂

2021-08-17 09:10 UTC, AllTerrainDeveloper requested changes
Looks good to me! But I've left a comment with a nitpick 🙂

2021-08-17 09:10 UTC, AllTerrainDeveloper commented on client/my-sites/people/people-profile/index.jsx
> -import React, { Component, Fragment } from 'react';
```suggestion
import React from 'react';
```

I've left a comment in the conversation tab, where you can check how to remove this Fragment import 🙂

2021-08-17 09:22 UTC, AllTerrainDeveloper approved these changes
Looks good to me!

2021-08-17 09:36 UTC, naxoc commented
Thanks for the review :) I want to make sure that having both the https://github.com/Automattic/wp-calypso/blob/trunk/client/state/data-getters/request-external-contributors.js and the new `useExternalContributorsQuery` will not be an issue when data is mutated with the old getter? I'm pretty sure it should be OK and that react-query fetches data often enough that it would work, but I wanted to make sure.

2021-08-18 09:06 UTC, naxoc commented
@jsnajdr I'm adding you as a reviewer – I'm wondering if it is OK with the mix of `react-query` and the `http` query is OK here? See the comment above :)

2021-08-18 17:50 UTC, jsnajdr commented on client/my-sites/people/people-profile/index.jsx
> +		siteId,
While rewriting to a functional component, it would be great to also migrate the HOCs to hooks: `useSelector`, `useTranslate`, `useLocalizedMoment`.

By the way, the `...ownProps` bit is redundant. You only need to return `{ siteId }`, the one prop you retrieved from Redux. The rest of `ownProps` will be merged in by `connect` automatically.

2021-08-18 17:50 UTC, jsnajdr commented on client/my-sites/people/people-profile/index.jsx
> +	}, [ user, externalContributors ] );
There doesn't need to be an effect or state here. We're merely computing a value from props:
```js
const isExternalContributor = externalContributors && externalContributors.includes( user?.linked_user_ID ?? user?.ID );
```
That can be done right in the render function.

2021-08-18 17:50 UTC, jsnajdr commented on client/data/external-contributors/use-external-contributors.js
> +	return useQuery(
It's possible that the `siteId` is null. The previous code guarded against that by calling the `requestExternalContributors` conditionally.

In React Query, we handle this condition by adding an `enabled: !! siteId` option to `useQuery`. See for example the `useUsersQuery` hook.

2021-08-18 17:50 UTC, jsnajdr commented on client/my-sites/people/people-profile/index.jsx
> +	const siteId = getSelectedSiteId( state );
The `siteId` prop used to be passed from the parent component, and the component didn't need to retrieve it from Redux itself. As the usages of `PeopleProfile` haven't changed, `siteId` continues to be passed even now. So why add `getSelectedSiteId` now? The component doesn't need it -- it doesn't need to be connected to Redux at all after this PR.

2021-08-18 17:54 UTC, jsnajdr commented
> I want to make sure that having both the [data getter] and the new `useExternalContributorsQuery` will not be an issue

It would be an issue if the `PeopleProfile` page used the `requestExternalContributorsAddition` or `...Removal` getter. Then the React Query getter wouldn't know about the change and wouldn't update the list.

But on this particular page, it's not an issue -- no additions or removal are not done in its UI, it merely reads the list.

2021-08-20 10:11 UTC, jsnajdr approved these changes
Looks good except two little suggestions :+1: Thanks for working on this and for addressing the feedback!

2021-08-20 10:11 UTC, jsnajdr commented on client/my-sites/people/people-profile/index.jsx
> +	moment: PropTypes.func.isRequired,
The `translate` and `moment` props are no longer there, they've been replaced by hook calls inside the component function.

2021-08-20 10:11 UTC, jsnajdr commented on client/my-sites/people/people-profile/index.jsx
> +		role = 'undefined' === typeof role ? getRole() : role;
This can be written more conveniently as `getRoleBadgeClass = ( role = getRole() ) => {`. Same in the `getRoleBadgeText` method.

2021-08-20 11:10 UTC, naxoc commented
Thanks for the review Jarda!

2021-08-20 12:18 UTC, merged