Add/activity log display rules from api
Automattic/wp-calypso pull request #55542
Opened 2021-08-16 20:35 UTC by mattgawarecki

Resolves `1200412004370260-as-1200706668146547`.

#### Changes proposed in this Pull Request

* Update the data-getter endpoint for Activity Log display rules to match the endpoint in `D65474-code`.
* Update application state logic to accommodate the shape of the API response in `D65474-code`.

#### Testing instructions

For extra context, check out #54900 and #55298.

##### Prerequisites

1. Create or select a connected Jetpack site to use for testing this PR.
2. Set up a sandbox for the WordPress.com API and ensure that `D65474-code` is applied to it.
3. Follow the relevant testing instructions in `D65474-code` to add a Backup or Security Tier 1 or Tier 2 subscription to your site.
4. Create a DNS alias on your local machine so that `public-api.wordpress.com` points to the sandbox you set up in step 1.
5. Enable the `activity-log/display-rules` feature flag, either by modifying `development.json`/`jetpack-cloud-development.json` or by adding `flags=activity-log/display-rules` to your browser URL's query string.
6. Open your browser's development tools to the Network panel to monitor XHR requests.

##### New behavior

7. Visit the Activity Log page in Calypso (Blue or Green).
8. Verify you see an outgoing request to `/wpcom/v2/sites/<site id>/rewind/policies`, and that it returns a success response.
9. Verify that if you added a Tier 1 subscription, the `activity_log_limit_days` field has a value of `30`; or, if you selected a Tier 2 subscription, it has a value of `365`.
10. In your browser's console, execute `state.activityLog.displayRules[ state.ui.selectedSiteId ]` and examine the result:
  * the `status` field should equal `success`; and
  * the `visibleDays` field should match the value of `activity_log_limit_days` from the network response in step 8.
11. Test that on sites with a Tier 1 subscription and more than 30 days of Activity history, you see a notice at the 30-day mark with instructions on how to upgrade your storage (see #54900, #55298).

##### Existing behavior

If you'd like to test for regressions:

12. Remove the Tier 1/Tier 2 subscription from your site. Wait up to 5 minutes for back-end caches to update.
13. Refresh the Activity Log page.
14. Verify you see a successful network request like in step 7, albeit with no data for `activity_log_limit_days`.
15. Verify the application state now reflects a `visibleDays` value of `null`.
16. Verify there are no unexpected errors in the browser console.

2021-08-16 20:46 UTC, a8ci18n commented on client/components/activity-card-list/visible-days-limit-upsell/index.tsx
> +							'Restore backups older than %(visibleDays)d day',
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **15** times:
`translate( 'Restore backups older than %(days)d day', 'Restore backups older than %(days)d days' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/activity-log-display-rules-from-api)

2021-08-16 20:46 UTC, a8ci18n commented on client/components/activity-card-list/visible-days-limit-upsell/index.tsx
> +							'Your activity log spans more than %(visibleDays)d day. Upgrade your backup storage to access activity older than %(visibleDays)d day.',
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **14** times:
`translate( 'Your activity log spans more than %(days)d day. Upgrade your backup storage to access activity older than %(days)d day.', 'Your activity log spans more than %(days)d days. Upgrade your backup storage to access activity older than %(days)d days.' )` *ES Score: 9*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/activity-log-display-rules-from-api)

2021-09-01 14:06 UTC, monsieur-z commented on client/state/rewind/selectors/get-activity-log-visible-days.ts
> +	return state.rewind?.[ siteId as number ]?.polices?.activityLogLimitDays ?? undefined;
There's a typo here: it should be `policies`.

2021-09-01 14:10 UTC, monsieur-z requested changes
There's a typo that needs to be fixed (see previous comment). Other than that, in Calypso blue (haven't checked in Cloud), I only see about 20 items before the upsell.

<img width="1064" alt="Screen Shot 2021-09-01 at 10 05 51 AM" src="https://user-images.githubusercontent.com/1620183/131686440-909b33af-73fc-4c1d-9277-549be4173aac.png">

2021-09-01 15:59 UTC, mattgawarecki commented
@monsieur-z

> There's a typo that needs to be fixed (see previous comment).

Fixed! Thanks for catching that, it slipped through during my refactor yesterday.

> Other than that, in Calypso blue (haven't checked in Cloud), I only see about 20 items before the upsell.

I had an inverted conditional that I fixed in 61b2f1f, so this should be resolved now 👍 If your site's Activity Log doesn't span for an entire 30 days, the upsell in Calypso Blue should no longer be visible.

2021-09-02 17:30 UTC, mattgawarecki commented
**NOTE:** Yesterday we discovered a gap in the API where new Security and Backup plans aren't having their Activity Log events retained for the correct amount of time. Until this gap is resolved, apply `D66240` to a WordPress.com sandbox and alias `public-api.wordpress.com` to point to this sandbox for testing.

2021-09-02 20:05 UTC, mattgawarecki commented
Update to my last comment: `D66240-code` has been deployed to production WordPress.com.

2021-09-03 19:14 UTC, cbauerman commented
`state.rewind[ state.ui.selectedId ].policies` should be `state.rewind[ state.ui.selectedSiteId ].policies`

2021-09-06 18:53 UTC, merged