Domains: Update Domain Transfer checkout page
Automattic/wp-calypso pull request #55675
Opened 2021-08-24 05:39 UTC by rafaelgalani

#### Changes proposed in this Pull Request
This PR implements the changes on the domain transfer checkout page layout. 
Here's a comparison of how they looked before vs. how they're looking now: 

#### Desktop

##### Before
<img width="900" alt="before - desktop" src="https://user-images.githubusercontent.com/18705930/129769526-cb639bc4-1a05-42b3-8c3b-5265156914fa.png">

##### After
<img width="900" src="https://user-images.githubusercontent.com/18705930/130561747-778f106a-683b-4e67-913c-41b5ed58d5a8.png"/>

#### Mobile
##### Before
<img width="400" alt="before - mobile" src="https://user-images.githubusercontent.com/18705930/129769644-05a8a46d-880e-47dd-b2e4-135da58cf5d2.png">

##### After
<img width="400" src="https://user-images.githubusercontent.com/18705930/130561805-4443b06f-aeff-490e-b8a1-3c0e9bef7587.png"/>

#### Testing instructions
 - Add a domain transfer to the cart;
 - Checkout and confirm that the new "thank you" page looks like this. 

_(If you already have a domain mapped and you have the receipt ID, you can bypass the checkout by going to `/checkout/thank-you/:your-site/:receipt-id` 😉)_

2021-08-27 11:51 UTC, poligilad-auto requested changes
Looks good @rafaelgalani. On mobile the only thing I would change is making sure the area with the black strip has the same padding as the content area below it. So then if the text is too long it will go to the next line and keep the icon aligned to the first line of text, like a bullet point.

![image](https://user-images.githubusercontent.com/83961704/131123067-9011493b-a084-4451-a45c-81087b98f225.png)

Also you mentioned that the additions I made to the designs will go in a separate PR?

2021-08-30 16:57 UTC, rafaelgalani commented
@poligilad-auto OK, adding the changes 😄 

> Also you mentioned that the additions I made to the designs will go in a separate PR?

No 😸 
Since they're simple enough (only a few sections), they can go into this one.

2021-08-30 21:35 UTC, rafaelgalani commented
Rebasing on `trunk`.

2021-08-31 17:05 UTC, rafaelgalani commented
@poligilad-auto Here's how it looks now: 

#### Desktop
![image](https://user-images.githubusercontent.com/18705930/131545656-d79d54d1-aaca-4404-9497-3a7c0339aa16.png)

#### Mobile
![image](https://user-images.githubusercontent.com/18705930/131545710-30a73913-e6fa-4d86-bebf-ab0159d54257.png)

2021-09-01 07:00 UTC, poligilad-auto approved these changes

2021-09-01 20:36 UTC, delputnam approved these changes
Really good job on this one.  Thanks for sticking with it!

2021-09-01 20:36 UTC, delputnam commented on client/my-sites/checkout/checkout-thank-you/domains/style.scss
> +    			height: auto;
Super minor nit: indention spacing.

2021-09-01 20:56 UTC, rafaelgalani commented on client/my-sites/checkout/checkout-thank-you/domains/style.scss
> +    			height: auto;
Totally missed that 🤨 
Thanks!

2021-09-08 19:18 UTC, merged

2021-09-08 20:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6576301

Thank you @rafaelgalani for including a screenshot in the description! This is really helpful for our translators.

2021-09-16 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6576301).