Add account-only SSO signup flow
Automattic/wp-calypso pull request #55713
Opened 2021-08-25 14:47 UTC by donlair

#### Changes proposed in this Pull Request

* This PR adds a case for user-only account flow for Jetpack SSO.
* It's a follow-up to #54715, which was reverted due to a regression.
* This PR fixes that regression by making `redirect` an optional dependency.
* Details about the regression are at p58i-b21-p2.

#### Testing instructions

* Checkout this PR and start Calypso
* Open TBD Jurassic Ninja site setup with SSO in an Incognito window.
* Click "Log in with WordPress.com"
* Click "Create a new account" and confirm that you're taken to /start/account/PARAMS
* Grab that path, including params, and paste add it onto calypso.localhost:3000
* Confirm that you're taken through the user-only flow and redirected to the expected site.
* Test the core signup, account, and site creation flow to ensure those still work as expected.

Related to #54715

2021-08-25 16:01 UTC, donlair commented
@bluefuton @niranjan-uma-shankar @southp this PR is follow-up to the SSO patch that broke the signup flow a few weeks ago. Could y'all take a look at this when you get a chance and confirm that it looks good to you? Thanks!

2021-08-30 12:58 UTC, niranjan-uma-shankar requested changes

2021-08-30 12:58 UTC, niranjan-uma-shankar commented on client/signup/steps/user/index.jsx
> +	getRedirectToAfterLoginUrl() {
There seems to be another function in this file with the same name `getRedirectToAfterLoginUrl(). Could we please roll over the changes from this new function to the existing function?

2021-09-02 17:28 UTC, donlair commented
Good catch @niranjan-uma-shankar! I've updated the file to fix the issue you found.

2021-09-06 14:39 UTC, niranjan-uma-shankar approved these changes
LGTM 🚢

2021-09-07 15:42 UTC, merged