Jetpack Backup: Get real storage info from the WPCOM API
Automattic/wp-calypso pull request #55968
Opened 2021-09-02 20:17 UTC by mattgawarecki

Resolves `1200412004370260-as-1200706668146543`.
Requires #55542.

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

#### Reference captures

2021-09-08 20:03 UTC, a8ci18n commented on client/components/backup-storage-space/usage-display.tsx
> +	const loadingText = translate( 'Calculating…', {
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Calculating price' )` *ES Score: 8*

2021-09-09 10:50 UTC, Luchadores commented
Hey @mattgawarecki 👋 Thank you for the ping. This is looking great. I only have one thing to note here. 
On the My Plan page, we're missing the Backup icon. If we don't want to display it, I would align the storage information to the left with the Free icon above. 

Here is how it looks in design:
![image](https://user-images.githubusercontent.com/10038976/132672892-7bd1eaec-c333-4c77-a4a5-a81406258695.png)

2021-09-09 12:47 UTC, mattgawarecki commented
> I only have one thing to note here. On the My Plan page, we're missing the Backup icon.

Yup, duly noted! I plan to resolve this in another PR (see "Known Issues" in my description) 👍

2021-09-09 13:47 UTC, monsieur-z commented on client/components/backup-storage-space/hooks.ts
> +			return translate( '%(usedUnitAmount).1fGB used', '%(usedUnitAmount).1fGB used', {
I don't see `usedUnitAmount` in the args. Could it be a mistake?

2021-09-09 13:55 UTC, monsieur-z requested changes
Code changes look sensible.

I'm seeing what's expected with a Backup tier. However, the storage indicator is not displayed for a site with a Security tier, even though the `size` endpoint is called (actually twice from the `My plan` section, in that case).

Also, since it's difficult to test the various levels of storage, it would be nice to have some units tests for files likes `client/components/backup-storage-space/hooks.ts` or `client/components/backup-storage-space/storage-usage-levels.ts`.

2021-09-10 14:13 UTC, monsieur-z approved these changes
Changes look good!

2021-09-10 14:53 UTC, Luchadores approved these changes
Giving this green light as well. 🙌

2021-09-10 18:20 UTC, merged

2021-09-10 19:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6581570

Thank you @mattgawarecki for including a screenshot in the description! This is really helpful for our translators.

2021-09-17 16:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6581570).