(WIP) Jetpack: Add VideoPress to pricing grid
Automattic/wp-calypso pull request #56103
Opened 2021-09-08 14:24 UTC by roundhill

#### Changes proposed in this Pull Request

* Adds VideoPress as a new `Free` product to the pricing grid
* Moves CRM card to the bottom area alongside `Jetpack Free`

#### Testing instructions

* View `/pricing`, and you should see VideoPress as an option.
* Clicking the `Get VideoPress` link should take you to the VideoPress details page.
* If you've purchased VideoPress (not testable yet), the card should not be visible.

Related to pxWta-Zz-p2

2021-09-08 14:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +			i18n.translate( 'Live chat is available 24 hours a day from Monday through Friday' ),
:warning: This change will be queued for retranslation. We'll display the English text until then.

2021-09-08 14:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getDescription: () => i18n.translate( 'Live chat is available 24/7' ),
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2021-09-08 14:33 UTC, a8ci18n commented on client/my-sites/plans/jetpack-plans/slug-to-selector-product.ts
> +				belowPriceText: translate( 'from %(minPrice)s - %(maxPrice)s/month', {
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'from %(minPrice)s - %(maxPrice)s' )` *ES Score: 8*

2021-09-08 14:33 UTC, a8ci18n commented on packages/calypso-products/src/translations.js
> +	const videoPress = translate( 'Get VideoPress' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Get started with VideoPress' )` *ES Score: 7*

2021-09-14 16:24 UTC, a8ci18n commented on packages/calypso-products/src/translations.js
> +	const videoPressTagLine = translate( 'High-quality, ad-free video for WordPress' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **26** times:
`translate( 'Host fast, high-quality, ad-free video.' )` *ES Score: 7*

2021-09-14 18:21 UTC, a8ci18n commented on client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx
> +								description: translate( 'High-quality, ad-free video' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **26** times:
`translate( 'Host fast, high-quality, ad-free video.' )` *ES Score: 9*

2021-09-17 13:52 UTC, pgk commented
Overall it tested as expected for me. I guess we might want to have all checks pass before we merge

2021-09-17 13:58 UTC, pgk requested changes
Code-wise it LGTM, let's fix those tests though

2021-09-21 14:06 UTC, monsieur-z commented
Hi @roundhill! I'm seeing a different card than what's shown in the screenshot when I run the branch locally. I applied the patches mentioned in [here](https://github.com/Automattic/jetpack/pull/21006) to my sandbox. Did I maybe miss something?
<img width="352" alt="Screen Shot 2021-09-21 at 9 57 03 AM" src="https://user-images.githubusercontent.com/1620183/134185770-fffce340-0181-43b8-ac54-eb0592bb4591.png">

2021-09-21 14:44 UTC, roundhill commented
> Hi @roundhill! I'm seeing a different card than what's shown in the screenshot when I run the branch locally. I applied the patches mentioned in [here](https://github.com/Automattic/jetpack/pull/21006) to my sandbox. Did I maybe miss something?

Oh, yes the original screenshot is outdated. @robertbpugh sent some changes to the card copy over slack, and wanted to show the price instead of `Free`.

2021-09-22 20:36 UTC, jgcaruso reviewed
This tested well for me too.

2021-09-28 17:35 UTC, roundhill commented
@pgk a rebase got the tests working 👍

2021-10-01 21:03 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Built into WordPress editor' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **1** times:
`translate( 'Built into WordPress Editor' )` *ES Score: 10*

2021-10-05 16:39 UTC, pgk approved these changes
tests passed!

2021-10-05 21:53 UTC, merged

2021-10-05 22:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6731177

Thank you @roundhill for including a screenshot in the description! This is really helpful for our translators.

2021-10-14 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6731177).