Quick Start: Prevent blocked users from scheduling an appointment
Automattic/wp-calypso pull request #56203
Opened 2021-09-13 13:27 UTC by niranjan-uma-shankar

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2021-09-15 16:11 UTC, klimeryk requested changes
Thank you so much on working on this - so many places to update and it's a huge help that you took this on 🙇 

I've ran into some issues while testing, though:

> Scenario 1

Despite verifying that the API definitely returned `true` for `is_happychat_blocked` and the `client/state/data-layer/wpcom/concierge/initial/from-api.js` correctly "transformed" it, when it reached `me/concierge`, the state was missing the `concierge.isHappychatBlocked` field and as a result, I did not get the expected message:

<img width="758" alt="Screenshot 2021-09-15 at 15 59 25" src="https://user-images.githubusercontent.com/3392497/133468907-73f614db-983a-44ba-b885-c324555333c5.png">

> Scenario 2

Works as expected 👍 

> Scenario 3

While the upsell disappeared, a new nudge appeared in its place! 😅 

<img width="1072" alt="Screenshot 2021-09-15 at 15 51 54" src="https://user-images.githubusercontent.com/3392497/133469040-da63a35d-ea2e-4db7-a1fe-536867a19dde.png">

Looks like it's the same problem as above with the state missing the `isHappychatBlocked` property 🤔 
I've tried refreshing many times, double-checking everything, but I definitely get the correct field from the API, it just gets lost somewhere before reaching the state 🤔

2021-09-16 12:26 UTC, a8ci18n commented on client/me/concierge/shared/no-available-times.js
> +							'We add new sessions daily, so please check back soon for more options. In the meantime, consider attending one of our expert webinars on a wide variety of topics designed to help you build an
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'If you don’t see a day or time that works for you, please check back soon for more options! In the meantime, consider attending one of our expert webinars on a wide variety of topics designed to help you build and grow your site. {{externalLink}}View webinars{{/externalLink}}.' )` *ES Score: 6*

2021-09-16 13:37 UTC, niranjan-uma-shankar commented
Thanks for testing @klimeryk .

> Looks like it's the same problem as above with the state missing the isHappychatBlocked property 

You're right, there was a state issue and I've fixed it. The PR is now ready for review again :)

2021-09-16 16:03 UTC, klimeryk commented
Thanks for all the updates, @niranjan-uma-shankar! I'm afraid the state is still causing some troubles:

```
Uncaught Error: When called with an action of type "CONCIERGE_INITIAL_UPDATE", the slice reducer for key "isUserBlocked" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
```

Unfortunately, it errors out and gets stuck in loading state :( Maybe try without state rehydration (http://calypso.localhost:3000/me/purchases?flags=force-sympathy) if your state has that key 🤔 I'd love to help more, but my Redux foo is definitely nowhere near your level, so it's probably best if you take a look at it yourself 🙇‍♂️

2021-09-16 20:49 UTC, niranjan-uma-shankar commented
> Unfortunately, it errors out and gets stuck in loading state 

That's strange. Could you please confirm if you have D66745-code applied and that your hosts file is pointing to sandbox? The console error and stuck at loading state will happen if your hosts file is pointing to production, but shouldn't happen when pointed to sandbox. I can dig into this again after your confirmation.

2021-09-17 12:32 UTC, klimeryk approved these changes
> That's strange. Could you please confirm if you have D66745-code applied and that your hosts file is pointing to sandbox?

Argh, that was indeed the issue! Sorry for the noise, I could have sworn I applied the patch (but maybe I forgot to sandbox public-api?).

Either way, I've retested and now it works perfectly 💖 (tested both blocked and not blocked cases)

2021-09-20 16:40 UTC, merged

2021-09-20 17:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6638024

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

2021-10-01 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6638024).