Chore/convert esm/calypso color schemes
Automattic/wp-calypso pull request #56232
Opened 2021-09-14 05:21 UTC by scinos

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2021-09-17 05:52 UTC, scinos commented
@ockham, `git blame` says you added those colors. Could you help verifying this works as expected please?

I did some checks comparing CSS files before and after, and everything seems to work.

2021-09-17 06:29 UTC, scinos commented
Notifications styles are wrong because we hit https://github.com/postcss/postcss-custom-properties/issues/255.

Moving to draft until it is fixed upstream.

2021-09-22 05:18 UTC, scinos commented
> Notifications styles are wrong because we hit postcss/postcss-custom-properties#255.

I end up working around that bug by providing a JSON export. This was only used in `apps/notifications`, and looking at the bundled CSS the output is the same.

2021-09-22 21:22 UTC, noahtallen requested changes
When I test notifications via the admin bar on the front end, the background is transparent:

Tested like so:
1. install notifications to my sandbox (`install-plugin.sh notifications chore/convert-esm/calypso-color-schemes`)
2. sandbox `widgets.wp.com` (I also have the test site sandboxed, but I don't think that matters.)
3. Access the the test site (on the front end) and open notifications via the adminbar


![Screenshot from 2021-09-22 14-18-00](https://user-images.githubusercontent.com/6265975/134423505-a3303ce2-9de4-4015-b226-852362290153.png)

2021-09-23 03:57 UTC, scinos commented
Interestingly, the latest build (#1.12494) didn't add the label `notifications-release-build`, because nothing has changed compared with the latest deployed build, which is exactly what we would expect if the package conversion was working.

But took me a few minutes to realize why I wasn't getting the changes in my sandbox :)

2022-02-21 08:29 UTC, closed without merging