[Draft] Emails: Inbox placeholder for calypso
Automattic/wp-calypso pull request #56270
Opened 2021-09-15 09:55 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

This pull request is just a draft for feedback. It adds a new entry in calypso for Inbox menu item in the calypso sidebar menu.
I am not quite sure if the flag has been quite invasive, as it will be in every call to get admin menu. Any advise?

#### Testing instructions

This change won't be visible without extra backend code, so you can't really test it right now.

1. Go to a simple site, add at the end of the URL the next flag: ?flags=sidebar/inbox
2. Check that there is indeed a new menu item, between Stats and Upgrades
3. Check that you can navigate to it, and you will see just a "Inbox" placeholder

![image](https://user-images.githubusercontent.com/5689927/133412213-09c585c7-814d-44f5-b7fe-acc1fbdece89.png)

Related to {1200182182542585-as-1200979289212216}

2021-09-15 16:08 UTC, AllTerrainDeveloper commented
As per the Asana task, I've moved all the logic within the `my-site/email/inbox` group folder, as the path URL is like `/email/inbox`

2021-09-16 14:03 UTC, olaseni commented on client/my-sites/email/inbox/controller.js
> +export default {
For consistency we often define `/email` controllers here: [client/my-sites/email/controller.js ](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/email/controller.js)

2021-09-16 14:13 UTC, olaseni requested changes
I left some comments about placements. While these work, some of your code duplicates things and isn't consistent.

2021-09-16 14:13 UTC, olaseni commented on client/sections.js
> +	{
We don't need to define a new section for this, since it's namespaced under `/email`

2021-09-16 14:13 UTC, olaseni commented on client/my-sites/email/inbox/paths.js
> +export const inboxManagementPrefix = '/email';
Paths are similarly conventionally defined here: [client/my-sites/email/paths.js](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/email/paths.js)

2021-09-16 14:13 UTC, olaseni commented on client/my-sites/email/inbox/index.js
> +import page from 'page';
This also should be specified here: [client/my-sites/email/index.js](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/email/index.js)

2021-09-16 14:48 UTC, closed without merging

2021-09-16 14:48 UTC, AllTerrainDeveloper commented
I've closed it as the branch name was not accurate. It might lead to concussions in the future