Redirect premium themes URL to main themes page
Automattic/wp-calypso pull request #56430
Opened 2021-09-21 14:36 UTC by claudiucelfilip

#### Changes proposed in this Pull Request

More info: pNEWy-e9X-p2#comment-53613

#### Testing instructions

* Go to `/themes/premium`
* You should be redirected to `/themes`

2021-09-21 20:07 UTC, danielwrobert requested changes
I believe this should be a `301` redirect.

Instead of `res.redirect( redirectUrl );` it would be `res.redirect( 301, redirectUrl );`

See the [menus redirect](https://github.com/Automattic/wp-calypso/blob/trunk/client/server/pages/index.js#L646) above for an example.

2021-09-22 08:26 UTC, claudiucelfilip commented
> I believe this should be a `301` redirect.
> 
> Instead of `res.redirect( redirectUrl );` it would be `res.redirect( 301, redirectUrl );`
> 

Thanks for tip!
Redirection should now be 301.

2021-09-22 09:12 UTC, jsnajdr commented
The redirect should be in the `client/my-sites/themes/index.node.js` module, where there already are other theme-specific redirects. Doing section-specific work in the section's code is preferrable to a global place like the `server/pages` module is.

2021-09-22 10:05 UTC, jsnajdr commented
There is also `/themes/free` URL that should be probably redirected, too, because the `:tier(free|premium)` lost all meaning and not used anymore.

And then there are more complicated URLs like `/themes/travel/premium/filter/global-styles` that have `:vertical`, `:tier` and `:filter` URL params and we should redirect to versions without the `:tier`.

2021-09-22 15:40 UTC, claudiucelfilip commented
@jsnajdr Thanks for the tips!
I moved the redirect to the themes' `index.nodex.js` files.
I also included the other routes which rely on the `(free|premium)` tier type.

2021-09-23 17:35 UTC, danielwrobert approved these changes
LGTM! 🚀 

Tests as described.

2021-09-24 10:28 UTC, merged