Add/jetpack sale coupon
Automattic/wp-calypso pull request #56523
Opened 2021-09-23 21:52 UTC by IanRamosC

#### Changes proposed in this Pull Request
Context: pbNhbs-16p-p2

* Adds the data layer and redux store for the Jetpack Coupon Sale
* Adds a Sale Banner on cloud.jetpack.com/pricing
* Removes the Introductory pricing banner if there's a sale running
* Changes the discount percentage based on the discount of the sale (ideally this should use the `sale_cost` property of a product, but it's not on the scope for this change)

#### Testing instructions

* For unit tests: `yarn test-client client/state/marketing/test`
* TBD

Related to #

2021-09-24 23:42 UTC, cbauerman requested changes
With a quick glance through everything looks good. However, the design of the query component means that if a sales coupon is not returned it will continue to slam the endpoint trying to get one:
<img width="499" alt="Screen Shot 2021-09-24 at 4 30 50 PM" src="https://user-images.githubusercontent.com/2810519/134749683-91558274-9c81-4851-b670-b895af413555.png">

We should make sure that there is some handling for errors or empty results. Otherwise it looks pretty good, but I will be sure to take a bit of a closer look first thing next week.

2021-09-27 15:21 UTC, IanRamosC commented
> However, the design of the query component means that if a sales coupon is not returned it will continue to slam the endpoint trying to get one:

Great catch. It seems like the action that calls the http handler is being dispatched multiple times. I'll debug how I set up the actions and try to find the issue.

2021-09-27 15:45 UTC, IanRamosC commented
> > However, the design of the query component means that if a sales coupon is not returned it will continue to slam the endpoint trying to get one:
> 
> Great catch. It seems like the action that calls the http handler is being dispatched multiple times. I'll debug how I set up the actions and try to find the issue.

It seems like it was an issue with the completely empty response that the API was returning in case we didn't have a coupon - which is not really an error but doesn't have a response, then the action creator seems to be passing the action back to the `registerHandler` and it just dispatches that action again, making the current request always call itself again.
And that happens because the aPI should be returning an empty `[ coupon => null ]` instead of an empty response. I'm pushing a change to the API in a few minutes.

2021-09-27 16:59 UTC, IanRamosC commented
@cbauerman, the API change I referred to in the previous comment is already in review, and will be live as soon as it's aceppted. When it's live, the front-end code will stop hammering the API multiple times. Also, I've added a few other minor changes to the frontend code.

2021-09-27 17:05 UTC, a8ci18n commented on client/jetpack-cloud/sections/pricing/sale-banner/index.tsx
> +							{ translate( 'Get %(discount)d%% off your first year of Jetpack', {
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **1** times:
`translate( 'Get %d%% off your first year of Jetpack' )` *ES Score: 6*

2021-09-27 20:01 UTC, cbauerman approved these changes
Looks good! I initially tested without pulling the newest changes but you already anticipated the need to hide the banner for a `null` coupon 👍 LGTM

2021-09-27 20:07 UTC, merged

2021-09-27 21:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6669008

Thank you @IanRamosC for including a screenshot in the description! This is really helpful for our translators.

2021-10-06 16:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6669008).