Plans: Add highlighting for designated product features
Automattic/wp-calypso pull request #56595
Opened 2021-09-27 20:22 UTC by mattgawarecki

Resolves `1200412004370260-as-1200788956056656`.

#### Changes proposed in this Pull Request

* Add support for an `isHighlighted` function to force highlighting for a given feature on all product cards.
* Enable highlighting for certain features on Backup, Security, and Complete if the `jetpack/only-realtime-products` feature flag is enabled.

#### Testing instructions

*

#### Reference screenshots (Mock / Implementation)

2021-09-27 20:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Search up to 100k records' ),
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2021-09-27 20:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'CRM Entrepreneur bundle' ),
:warning: This change will be queued for retranslation. We'll display the English text until then.
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **8** times:
`translate( 'CRM: Entrepreneur' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/highlighted-jetpack-product-features)

2021-09-27 20:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'All Backup features' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'All Jetpack Backup features' )` *ES Score: 7*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/highlighted-jetpack-product-features)

2021-09-27 20:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Scan (real-time & automated)' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Scan (real-time, automated)' )` *ES Score: 12*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/highlighted-jetpack-product-features)

2021-09-27 20:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'All Security features' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'All Security Daily features' )` *ES Score: 7*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/highlighted-jetpack-product-features)

2021-10-05 14:27 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( '1TB of backup storage' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **3** times:
`translate( '1TB of storage' )` *ES Score: 7*

2021-10-07 19:52 UTC, a8ci18n commented on client/my-sites/plans/jetpack-plans/storage-tier-upgrade/hooks/use-get-storage-upgrade-product.ts
> +							text: translate( '30-day activity log' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Activity log: 30-day archive' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/highlighted-jetpack-product-features)

2021-10-07 19:52 UTC, a8ci18n commented on client/my-sites/plans/jetpack-plans/storage-tier-upgrade/hooks/use-get-storage-upgrade-product.ts
> +							text: translate( 'Real-time backups (as you edit)' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Real-time backups &mdash; we save as you edit' )` *ES Score: 6*

2021-10-11 18:44 UTC, eeeeevon13 requested changes
I'd go with a green star so it's not directly associated with the sale language (in yellow). Also please ensure we are using the star icon from the WordPress design library (not material design).



--



--

2021-10-11 20:26 UTC, mattgawarecki commented
Updated. Here's a screenshot of what it should look like now, with the star's color set to Jetpack Green 50%.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/670067/136851447-c804ad14-f797-406e-8bc8-08673ae7cacd.png">

2021-10-13 15:21 UTC, monsieur-z approved these changes
LGTM!

2021-10-13 15:44 UTC, merged