WIP: Onboarding: Give your blog a name step
Automattic/wp-calypso pull request #56611
Opened 2021-09-28 11:41 UTC by arthur791004

#### Changes proposed in this Pull Request

* TBD

##### Desktop

<img src="https://user-images.githubusercontent.com/13596067/135079783-15684d44-4b56-4041-b8f6-f139fc0411ae.png" width="600"  />

##### Mobile

<img src="https://user-images.githubusercontent.com/13596067/135079810-5468c5e8-c360-47e2-8249-e24660a9a048.png" />

#### Testing instructions

* Go to `/start/setup-site?flags=signup/hero-flow&siteSlug=<your_site>`

Related to https://github.com/Automattic/wp-calypso/issues/55603

2021-09-28 11:49 UTC, a8ci18n commented on client/signup/steps/site-options/site-options.tsx
> +					{ translate( 'Blog name' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **40** times:
`translate( 'Blog Name:' )` *ES Score: 9*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/feat/give-your-blog-name)

2021-10-04 05:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6719804

Thank you @arthur791004 for including a screenshot in the description! This is really helpful for our translators.

2021-10-06 22:15 UTC, roo2 requested changes
Looking good, I had some unrelated bugs frustrate my testing. The only change I think we need to make is allowing the user to proceed without entering wither tagline or site description, since they are both optional.

2021-10-06 22:15 UTC, roo2 commented on client/signup/steps/intent/index.tsx
> +		EXCLUDE_STEPS[ intent ].forEach( ( step ) => flows.excludeStep( step ) );
I like this solution 👍 pdgK6S-bZ-p2

2021-10-06 22:15 UTC, roo2 commented on client/signup/steps/intent/index.tsx
> +		flows.resetExcludedSteps();
I see that we use excludeStep for excluding other steps in various functions in step-actions.js. I worry about if there's potential for this to interfere with other flows when using the browser back button etc. I'll try to investigate and work out if this is currently possible.

2021-10-06 22:15 UTC, roo2 commented on client/signup/steps/site-options/site-options.tsx
> +				disabled={ Object.values( formValues ).every( ( value ) => ! value ) }
Since both of the fields say "Optional", I think that we need to enable the button even if neither fields have been entered

2021-10-07 02:12 UTC, arthur791004 commented on client/signup/steps/site-options/site-options.tsx
> +				disabled={ Object.values( formValues ).every( ( value ) => ! value ) }
I also make this button always enabled before but I found this EuqfSnWpfYx8fgiBlVmbuA-fi-2312%3A1985 show the disabled style. I'll ask @ollierozdarz about this one.

2021-10-07 02:19 UTC, arthur791004 commented on client/signup/steps/intent/index.tsx
> +		flows.resetExcludedSteps();
Yes, so I change to reset the steps we exclude in this step at `useBranchSteps` hooks in this PR: https://github.com/Automattic/wp-calypso/pull/56725. Should I need to change here?

2021-10-07 02:53 UTC, arthur791004 commented on client/signup/steps/site-options/site-options.tsx
> +				disabled={ Object.values( formValues ).every( ( value ) => ! value ) }
Confirmed and remove the disabled props!

2021-10-07 07:27 UTC, roo2 commented on client/signup/steps/intent/index.tsx
> +		flows.resetExcludedSteps();
ahh nicely handled 🎉 hmm with the branching, yep, I think it makes sense to merge this first as is and then rebase https://github.com/Automattic/wp-calypso/pull/56725 on top of it 👍

2021-10-07 07:28 UTC, roo2 approved these changes
LGTM!

2021-10-07 07:42 UTC, merged

2021-10-07 08:05 UTC, arthur791004 commented on client/signup/steps/intent/index.tsx
> +		flows.resetExcludedSteps();
Yep, I've rebased #56725 on top of trunk!

2021-10-08 15:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6719804).