Plans: Add new copy for tier 1 & 2 storage upgrades
Automattic/wp-calypso pull request #56714
Opened 2021-09-30 20:27 UTC by mattgawarecki

Resolves `1200412004370260-as-1201090224957164`.

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

#### Reference screenshots

2021-09-30 20:38 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Search up to 100k records' ),
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2021-09-30 20:38 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'CRM Entrepreneur bundle' ),
:warning: This change will be queued for retranslation. We'll display the English text until then.
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **8** times:
`translate( 'CRM: Entrepreneur' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-09-30 20:38 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'All Backup features' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'All Jetpack Backup features' )` *ES Score: 7*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-09-30 20:38 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Scan (real-time & automated)' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Scan (real-time, automated)' )` *ES Score: 12*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-09-30 20:38 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'All Security features' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'All Security Daily features' )` *ES Score: 7*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-09-30 20:38 UTC, a8ci18n commented on client/my-sites/plans/jetpack-plans/storage-tier-upgrade/hooks/use-get-storage-upgrade-product.ts
> +							text: translate( '30-day activity log' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Activity log: 30-day archive' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-09-30 20:38 UTC, a8ci18n commented on client/my-sites/plans/jetpack-plans/storage-tier-upgrade/hooks/use-get-storage-upgrade-product.ts
> +							text: translate( 'Real-time backups (as you edit)' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Real-time backups &mdash; we save as you edit' )` *ES Score: 6*

2021-09-30 20:38 UTC, a8ci18n commented on client/my-sites/plans/jetpack-plans/storage-tier-upgrade/hooks/use-get-storage-upgrade-product.ts
> +							text: translate( '1TB backup storage' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'Backup (1TB)', { context: 'Jetpack Backup Solution'} )` *ES Score: 6*

2021-10-01 17:30 UTC, rcanepa commented
There is one unit test failing:
![image](https://user-images.githubusercontent.com/3418513/135662723-1a083815-8998-4495-aeff-e5b07809ecc2.png)

2021-10-01 17:49 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( '1TB of backup storage' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **2** times:
`translate( '1TB of storage' )` *ES Score: 7*

2021-10-01 18:22 UTC, mattgawarecki commented
> There is one unit test failing: ![image](https://user-images.githubusercontent.com/3418513/135662723-1a083815-8998-4495-aeff-e5b07809ecc2.png)

Argh, you're right! I forgot about those functions. Fixing the broken bits now. 👍

2021-10-04 16:48 UTC, robertf4 commented
This needs a rebase due to the merge of https://github.com/Automattic/wp-calypso/pull/56552.

2021-10-04 19:43 UTC, mattgawarecki commented
> This needs a rebase due to the merge of #56552.

Absolutely! Done.

2021-10-05 15:31 UTC, ederrengifo requested changes
A couple of issues were found:

- When the customer reaches the TIER 2 purchase (Step 5) and they only see one column, that layout breaks the footer:
<img width="993" alt="Screen Shot 2021-10-05 at 10 28 37" src="https://user-images.githubusercontent.com/10525007/136054197-83b47271-db50-41eb-96b4-cd424afa6f66.png">
- I don't see the "Save 20%" label next to the "Bill yearly" option from the designs. We might have decided to remove it at some point so would be good to investigate if that was the case.

2021-10-05 19:41 UTC, mattgawarecki commented
> A couple of issues were found:

@ederrengifo Thanks for letting me know about these, and for making sure they're documented. I'm happy to report these are actually addressed in two separate PRs, since it turns out they're not immediately due to any changes in this one:

>     * When the customer reaches the TIER 2 purchase (Step 5) and they only see one column, that layout breaks the footer:

This will be resolved in #56802.

> - I don't see the "Save 20%" label next to the "Bill yearly" option from the designs. We might have decided to remove it at some point so would be good to investigate if that was the case.

We shipped a fix for this just moments ago, in #56801. 👍

2021-10-05 20:12 UTC, a8ci18n commented on client/my-sites/plans/jetpack-plans/storage-tier-upgrade/hooks/use-get-storage-upgrade-product.ts
> +							text: translate( '10GB backup storage' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **18** times:
`translate( '10GB storage' )` *ES Score: 6*

2021-10-06 16:39 UTC, robertf4 approved these changes
Looks good to me, and tests well.

2021-10-08 12:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Site Search up to 100k records' ),
:warning: This change will be queued for retranslation. We'll display the English text until then.
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Search: up to 100k records' )` *ES Score: 10*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-10-08 12:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( '30-day archive & activity log' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Activity log: 30-day archive' )` *ES Score: 11*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-10-08 12:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( '1-year archive & activity log' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Activity log: 1-year archive' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-10-08 12:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Real-time cloud backups' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **22** times:
`translate( 'Real-time backups' )` *ES Score: 6*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-10-08 12:33 UTC, a8ci18n commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Real-time malware scanning' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **18** times:
`translate( 'Real-Time Malware Scanning' )` *ES Score: 13*

2021-10-08 12:33 UTC, a8ci18n commented on packages/calypso-products/src/plans-list.js
> +			'Easy-to-use, comprehensive WordPress site security including backups, malware scanning, and spam protection.'
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Jetpack Security provides easy-to-use, comprehensive WordPress site security including backups, malware scanning, and spam protection' )` *ES Score: 10*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-10-08 12:33 UTC, a8ci18n commented on packages/calypso-products/src/translations.js
> +		'Save every change with real-time backups and get back online quickly with one-click restores.'
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'Real-time backups save every change and one-click restores get you back online quickly' )` *ES Score: 9*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/storage-upgrade-cards-copy)

2021-10-11 14:47 UTC, merged

2021-10-11 15:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6761129

Thank you @mattgawarecki for including a screenshot in the description! This is really helpful for our translators.

2021-10-21 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6761129).