Add gutenboarding import module
Automattic/wp-calypso pull request #56789
Opened 2021-10-05 15:04 UTC by bogiii

#### Changes proposed in this Pull Request
Changes introduce a new Gutenboarding step named "import". The step lives on `/new/import` path. In this stage, idea is to provide UI without business logic. There is a `gutenboarding/import` feature flag which is only turn on for the development purpose.

For now, the only available import step is `Ready` and it can be reached by adding query param `?step=ready`.

#### Testing instructions
Manual testing:
- turn on `gutenboarding/import` feature from [config/development.json](https://github.com/Automattic/wp-calypso/blob/add/gutenboarding-import/config/development.json)
- go to the path `/new/import?step=ready`
- resize the screen to see how it looks on mobile

Related to #

2021-10-05 15:16 UTC, a8ci18n commented on client/landing/gutenboarding/onboarding-block/import/ready/index.tsx
> +						<NextButton>{ __( 'Import your content' ) }</NextButton>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Import Your Content' )` *ES Score: 11*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/gutenboarding-import)

2021-10-05 15:16 UTC, a8ci18n commented on client/landing/gutenboarding/onboarding-block/import/ready/platform-details.tsx
> +							<Icon size={ 20 } icon={ check } /> { __( 'Static pages' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'All static pages' )` *ES Score: 7*

2021-10-07 10:37 UTC, vishnugopal requested changes
Hey great work! The design looks sweet, and also responsive, nice!

Please:
* Add a few screenshots and cc @ollierozdarz so that he can take a quick look at this before merge.
* Fix the preview being generated stage, since that'll be the most common case: 

<img width="1407" alt="CleanShot 2021-10-07 at 16 02 05@2x" src="https://user-images.githubusercontent.com/533/136368322-a4c3116d-31c2-4939-aa55-8e42f23b5197.png">

* Teamcity [has a pretty strange error](https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6800684?) that will possibly go away on a fresh build:

```
  ● [WPCOM] Gutenboarding: Language: (mobile) @parallel › Change Language › Acquire intent is displayed in Hebrew
    expect(received).toBe(expected) // Object.is equality
    Expected: "האתר שלי נקרא"
    Received: "私のサイトの名前は"
      46 |     it( `Acquire intent is displayed in ${ language }`, async function () {
      47 |       const text = await gutenboardingFlow.getSiteTitleLabel();
    > 48 |       expect( text ).toBe( labelText );
         |                      ^
      49 |     } );
      50 |   } );
      51 | } );
```

* All the suggestion for the localization bot look like no-brainers, so please execute them!

2021-10-07 10:37 UTC, vishnugopal commented on client/landing/gutenboarding/onboarding-block/import/index.tsx
> +				<ReadyNoUrlStep platform={ data.platform } website={ data.website } />
Will `ReadyNoUrl` have a website prop?

2021-10-07 10:37 UTC, vishnugopal commented on client/landing/gutenboarding/onboarding-block/import/index.tsx
> +				<ReadyNotStep platform={ data.platform } website={ data.website } />
Will `ReadyNotStep` require any of these props?

2021-10-08 08:14 UTC, bogiii commented on client/landing/gutenboarding/onboarding-block/import/index.tsx
> +				<ReadyNoUrlStep platform={ data.platform } website={ data.website } />
Good catch, the ReadyNoUrl component doesn't need that prop. It was a copy/paste oversight.

Thanks!

2021-10-08 08:14 UTC, bogiii commented on client/landing/gutenboarding/onboarding-block/import/index.tsx
> +				<ReadyNotStep platform={ data.platform } website={ data.website } />
Good catch, the ReadyNot component doesn't need any props. It was a copy/paste oversight.

Thanks!

2021-10-11 08:35 UTC, bogiii commented
Hey @ollierozdarz,

You can check the current state of screens on the following links:
- https://container-xenodochial-mayer.calypso.live/new/import?step=ready
- https://container-xenodochial-mayer.calypso.live/new/import?step=ready-no-url
- https://container-xenodochial-mayer.calypso.live/new/import?step=ready-not
- https://container-xenodochial-mayer.calypso.live/new/import?step=scanning

cc @vishnugopal

2021-10-11 18:59 UTC, a8ci18n commented on client/landing/gutenboarding/onboarding-block/import/list/index.tsx
> +						<Title>{ __( 'Import your content from another platform' ) }</Title>
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'Import content from another website or platform.' )` *ES Score: 7*

2021-10-12 15:33 UTC, a8ci18n commented on client/landing/gutenboarding/onboarding-block/import/capture/index.tsx
> +				placeholder={ __( 'Enter your site address' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Enter your new site address' )` *ES Score: 7*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/gutenboarding-import)

2021-10-13 17:17 UTC, a8ci18n commented on client/landing/gutenboarding/onboarding-block/import/capture/index.tsx
> +					placeholder={ __( 'Enter your site address' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Enter your new site address' )` *ES Score: 7*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/gutenboarding-import)

2021-10-21 07:29 UTC, vishnugopal commented
Just a note that we are deprecating this PR in [favor of these ones](https://github.com/Automattic/wp-calypso/issues/57131).

2021-12-09 14:22 UTC, closed without merging