Inbox upsell: Page view tracker and other tracking improvements
Automattic/wp-calypso pull request #56905
Opened 2021-10-08 14:49 UTC by olaseni

#### Changes proposed in this Pull Request

This is a follow-up of #56786. The effort essentially rectifies some comments and refines logic to make it easier to find stuff.

- Installs a page view tracker
- Click event tracker for new mailbox upsells
- Refines some JavaDoc
- Removes long IFs
- Extracts constants

#### Testing instructions

NOTE: You can confirm that track events are fired by using the browser's developer console, the network panel, and looking for requests for `*/t.gif` and checking out the URL query parameters.

* Navigate to the `/inbox` using a site with mailboxes
* Confirm the existence of a `calypso_page_view` event on page load
* Click on the upsell button at the bottom of the street
* Confirm that a `calypso_inbox_new_mailbox_upsell_click` event was fired

Also test out these flows:
 * Load the Inbox
 * Click on the "Create a new mailbox" button
 * From this point, test both of the following flows:
   - **Google**
     = Open an existing Google subscription
     = Verify the URL still includes the `source` URL parameter
     = Click on "Add new mailboxes"
     = Verify the URL still includes the `source` URL parameter
     = Click on the Cancel button
     = Verify that the `source` field is included in the Tracks event for the click
     = Click on "Add new mailboxes" again
     = Fill in enough data for the "Continue" button to be enabled
     = Click on the Continue button
     = Verify that the click event includes the `source` field
   - **Professional Email**
    = Open an existing Professional Email subscription
    = Verify the URL still includes the `source` URL parameter
     = Click on "Add new mailboxes"
     = Verify the URL still includes the `source` URL parameter
     = Click on the Cancel button
     = Verify that the `source` field is included in the Tracks event for the click - _Note: this is NOT currently true_
     = Click on "Add new mailboxes" again
     = Click on the Continue button
     = Verify that the click event includes the `source` field
 * Navigate to Upgrades -> Emails
 * Repeat the steps above, except we need to verify that `source` is not present in the URL and in the Tracks events

Related to #56786

2021-10-11 13:09 UTC, daledupreez commented on client/my-sites/email/email-providers-comparison/index.jsx
> +			source: source === INBOX_SOURCE ? source : null,
Why not just send `source,` on this line?

2021-10-11 13:09 UTC, daledupreez commented on client/my-sites/email/email-providers-comparison/index.jsx
> +			source: source === INBOX_SOURCE ? source : null,
As above, why not just `source,`?

2021-10-11 13:09 UTC, daledupreez commented on client/my-sites/email/gsuite-add-users/index.jsx
> +			...( source === INBOX_SOURCE && {
How does the `...` operator act on `false`?

2021-10-11 13:26 UTC, olaseni commented on client/my-sites/email/email-providers-comparison/index.jsx
> +			source: source === INBOX_SOURCE ? source : null,
I also wondered the same. The previous logic only sent source when it was `inbox`, but I guess it doesn't hurt to send it as is, and differentiate when measuring.

2021-10-11 13:36 UTC, olaseni commented on client/my-sites/email/gsuite-add-users/index.jsx
> +			...( source === INBOX_SOURCE && {
The second statement isn't evaluated in that case. More context [here](https://www.google.com/search?client=safari&rls=en&q=short-circuit+evaluation&ie=UTF-8&oe=UTF-8) and [here](https://stackoverflow.com/questions/11704267/in-javascript-how-to-conditionally-add-a-member-to-an-object)

2021-10-11 13:36 UTC, olaseni commented on client/my-sites/email/gsuite-add-users/index.jsx
> +			...( source === INBOX_SOURCE && {
However, it's moot, because it doesn't seem like a bad idea to always send the source.

2021-10-12 07:41 UTC, daledupreez requested changes
Overall, this seems to be working, but I do have a concern about where we're adding `source` for the Professional Email _Add New Mailboxes_ page, and I am not sure if it's OK to drop the `product` field from the two _Add New Mailboxes_ pages.

I also want to call out that the testing instructions should go into more depth around the other flows that need testing as a result of these changes. I tested the following flows:
 * Load the Inbox
 * Click on the "Create a new mailbox" button
 * From this point, test both of the following flows:
   - **Google**
     = Open an existing Google subscription
     = Verify the URL still includes the `source` URL parameter
     = Click on "Add new mailboxes"
     = Verify the URL still includes the `source` URL parameter
     = Click on the Cancel button
     = Verify that the `source` field is included in the Tracks event for the click
     = Click on "Add new mailboxes" again
     = Fill in enough data for the "Continue" button to be enabled
     = Click on the Continue button
     = Verify that the click event includes the `source` field
   - **Professional Email**
    = Open an existing Professional Email subscription
    = Verify the URL still includes the `source` URL parameter
     = Click on "Add new mailboxes"
     = Verify the URL still includes the `source` URL parameter
     = Click on the Cancel button
     = Verify that the `source` field is included in the Tracks event for the click - _Note: this is NOT currently true_
     = Click on "Add new mailboxes" again
     = Click on the Continue button
     = Verify that the click event includes the `source` field
 * Navigate to Upgrades -> Emails
 * Repeat the steps above, except we need to verify that `source` is not present in the URL and in the Tracks events

I also noticed that the Back buttons are dropping the `source` field. I am pretty sure that's an existing issue, but I do want to flag it.

2021-10-12 07:41 UTC, daledupreez commented on client/my-sites/email/titan-add-mailboxes/index.jsx
> -			eventProps.product = 'inbox';
Do we want to lose the `product` field here? That's not explicitly documented as an expectation.

2021-10-12 07:41 UTC, daledupreez commented on client/my-sites/email/gsuite-add-users/index.jsx
> -			eventObject.product = 'inbox';
Is it intentional that we're removing `product` here? That wasn't called out in the PR description.

2021-10-12 07:41 UTC, daledupreez commented on client/my-sites/email/titan-add-mailboxes/index.jsx
> -			eventProps.product = 'inbox';
Also, I think we should be adding `source` in `recordClickEvent()`, which is where we're handling this for Google.

By adding it here, we're only getting `source` added for clicks on the Add/Continue button, and not any other buttons.

2021-10-12 16:47 UTC, olaseni commented on client/my-sites/email/gsuite-add-users/index.jsx
> -			eventObject.product = 'inbox';
The `product` = '**inbox**' in all the cases, and only when `source` = '**inbox**' .

It looked like we were duplicating the `inbox` value. It seems to me like it's enough to know the source to figure that the event comes from the Inbox. Am I missing something?

2021-10-12 21:39 UTC, olaseni commented
Apologies about more extensive testing instructions. I'll note that for next time.

> I also noticed that the Back buttons are dropping the source field. I am pretty sure that's an existing issue, but I do want to flag it.

Yes, it's an existing issue. The browser history and back button works fine, but the custom back buttons aren't actually using history and outside the scope of this PR.

2021-10-13 10:24 UTC, daledupreez approved these changes
Tested and looks good to me!

Getting the network traffic didn't work very well given the number of pages involved, so I don't have evidence of testing. (I also don't have the new Tracks event plugin working yet.)

In retrospect, it may have been worth splitting the page view tracking into a separate PR to get that easy/quick change shipped sooner.

> Apologies about more extensive testing instructions. I'll note that for next time.

For this time, it would have been good to update the instructions, even if it was just copy and pasting my steps.

2021-10-13 13:53 UTC, merged