Emails: Unify minimal possible code to fix 15px gap in the top of thank you pages
Automattic/wp-calypso pull request #56934
Opened 2021-10-11 11:40 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

After closing previous PR regarding of too many things being fixed in one change request, this PR just fixes the 15px gap in the top of thank you page, unifying the minimum possible code for domains and emails.

Thank you page hero card has a small 15px gap between MasterBar and the Thank you page itself. The fix just adds into the equation the MasterBar height

In addition this Pull Request is unifying the two only styles that ThankYou component uses for the 15px gap.

It also fix some regression added previously, where the buttons were not full width on mobile designs. Everything is documented in the screenshots.

#### Testing instructions

1. Go to Upgrades -> Emails
2. Buy or add a mailbox (Professional Email)
3. Check the thank you page is not showing an empty gap in the top side as per the below table.

#### Emails

BEFORE | AFTER
------------ | -------------
![before-emails](https://user-images.githubusercontent.com/5689927/136783563-bda11900-1bb7-476b-a2d2-229fb5ee4329.gif) | ![new fix gap](https://user-images.githubusercontent.com/5689927/137287753-c255269a-851a-4b95-82b5-05b1d604ea6f.gif)

BEFORE | AFTER
------------ | -------------
![new fix gap setup old](https://user-images.githubusercontent.com/5689927/137299168-c4c42de4-8351-4b30-8548-60246c1ac2ae.gif) | ![new fix gap setup](https://user-images.githubusercontent.com/5689927/137299218-8fcef34a-68e2-4c37-aa3c-d68ebc11b439.gif)

#### Domains

To test the domain Thank you Page please, refer to this [Pull Request](https://github.com/Automattic/wp-calypso/pull/55675). This view should remain unchanged. We want to avoid regression issue, the screenshots below proves that everything should be equivalent after this PR.

BEFORE | AFTER
------------ | -------------
![before-domains](https://user-images.githubusercontent.com/5689927/136783703-9ba842ed-88d9-4013-9590-725840e91f82.gif) | ![domains-regression](https://user-images.githubusercontent.com/5689927/136783779-4c6f0e47-4484-443a-808e-d733e4dc10af.gif)

#### Remarks

This issue is not replicable with old purchases, or reloading the site. In this case the order of stylesheet loading is different and makes not possible to replicate the issue.

Related to {1200182182542585-as-1201165030390295}

2021-10-11 11:40 UTC, AllTerrainDeveloper commented on client/components/thank-you/style.scss
> +	@include breakpoint-deprecated( '>660px' ) {
Neede this deprecated one as there were a gap in this specific breakpoint.

2021-10-11 11:41 UTC, AllTerrainDeveloper commented on client/my-sites/email/titan-set-up-thank-you/style.scss
> +		width: auto;
Additional fix as I found this bug while developing the 15px gap fix.

2021-10-13 23:23 UTC, olaseni requested changes
I had some concerns about changing styles for core components without reference to the effects on units that use them.

There's also a case where retracted styles had unintended effects.

2021-10-13 23:23 UTC, olaseni commented on client/components/thank-you/index.tsx
> -	margin-top: calc( -79px + var( --masterbar-height ) );
I'm wary of changing styles for core components especially when they have been used in multiple places.

2021-10-13 23:23 UTC, olaseni commented on client/components/thank-you/style.scss
> +}
Similarly I'm wary of changing styles for this core component. This style is very generic and will affect all components that import this.

Have we confirmed that this change is desirable?

2021-10-13 23:23 UTC, olaseni commented on client/my-sites/email/titan-set-up-thank-you/style.scss
> -.thank-you__container {
Removing this style has consequences for the component in some scenarios. For instance, when setting up the first mailbox for an existing subscription i.e. using the `<TitanSetUpThankYou/>` component. The right and left margins disappear.

<img width="1200" alt="Screenshot 2021-10-13 at 11 01 24 PM" src="https://user-images.githubusercontent.com/277661/137220441-c87b597a-5437-40de-965e-7f92f6ed31b5.png">

2021-10-14 10:23 UTC, AllTerrainDeveloper commented
Thank you! A few things I've applied your suggestion in this [Pull Request](https://github.com/Automattic/wp-calypso/pull/57017), which I had to fix (the reason of more changes in the commit)

- Logo was being partly hidden by top bar
- Text was going off screen in the sides of the screen

I've updated screenshots too to reflect the new changes.

2021-10-14 10:24 UTC, AllTerrainDeveloper commented on client/components/thank-you/style.scss
> +	padding-top: calc( -33px + var( --masterbar-height ) );
Needed as logo was being partly hidden by master bar.

2021-10-14 10:25 UTC, AllTerrainDeveloper commented on client/my-sites/checkout/checkout-thank-you/domains/style.scss
> +			padding-bottom: 35px;
Same thing, Logo was being partly hidden by master bar under small screen devices.

2021-10-14 10:27 UTC, AllTerrainDeveloper commented on client/my-sites/email/titan-set-up-thank-you/style.scss
> +}
This avoid the text to be offscreen on small devices. I had to use deprecated breakpoint, otherwise there were a gap where the component had white gap in the left/right sides.

2021-10-14 14:44 UTC, olaseni approved these changes
There seems to be a duplicate rule. Otherwise, good.

2021-10-14 14:44 UTC, olaseni commented on client/my-sites/email/titan-set-up-thank-you/style.scss
> +	padding-top: calc( -33px + var( --masterbar-height ) );
This looks like a duplicate rule.

2021-10-18 07:43 UTC, AllTerrainDeveloper commented on client/my-sites/email/titan-set-up-thank-you/style.scss
> +	padding-top: calc( -33px + var( --masterbar-height ) );
Retested after last commit to remove the rule duplication 🙂 

![image](https://user-images.githubusercontent.com/5689927/137688939-be694c4f-64b8-4b01-b250-06a0abdfc51b.png)

2021-10-18 09:39 UTC, merged