Emails: Thank you page for Professional Email when buying domain
Automattic/wp-calypso pull request #56949
Opened 2021-10-12 09:34 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

This Pull Request adds the necessary code to show Thank You component after checking out a Domain with a Professional Email.

#### Testing instructions

**Test 1**

1. Go to Upgrades -> Domains
2. Click on the button Add a domain for this site -> Search for a domain
3. When asked to add an Email, fill in necessary fields and click "Add"
4. Buy with credits

**Expected result**
You should see a Thank you page, congratulating the purchase of the domain with CTA's to go to Inbox.
![image](https://user-images.githubusercontent.com/5689927/137749966-fdfdd2e8-1a77-4b3f-b148-243690cf7a1f.png)

**Test 2**

1. Go to Upgrades -> Domains
2. Click on the button Add a domain for this site -> Search for a domain
3. When asked to add an Email, press the SKIP button
4. Buy with credits

**Expected result**
You should see a Thank you page, congratulating the purchase of the domain with CTA's to add professional email.
![image](https://user-images.githubusercontent.com/5689927/137878580-f6054fa7-c523-4152-992e-054d18ec2f63.png)

**Test 3**

0. Have an external domain on a domain provider different than WPCOM.
1. Go to Upgrades -> Domains
2. Click on the button Add a domain for this site -> Use a domain I own
3. Buy with credits

**REMARKS**
If you are not allowed to map domains to the site, you need to sandbox and change the function: `function is_exempt_from_domains_with_plans_only( $current_user = false )` to return always true

**Expected result**
You should see a Thank you page, congratulating the purchase of the domain mapping with CTA's to add professional email.
![image](https://user-images.githubusercontent.com/5689927/137878423-bc16d1a3-44b5-4cd2-9d4f-a2cd15d3bf1f.png)

**Test 4, regression test**
1. Go to Upgrades -> domains
2. Click on the button Add a domain for this site -> Use a domain I own
3. Type the domain you own and start a transfer domain
4. But with credits

**Expected result**
You should see a thank you page, congratulating about the domain being transferred like this:
![image](https://user-images.githubusercontent.com/5689927/137762816-b299f180-4c9d-4a46-866d-7412bf0d8809.png)

**Test 5**
Repeat those tests where you have bought Professional Email, but this time buy a Google Workspace, then the thank you page shouldn't have the step to go to inbox.

Example:
![image](https://user-images.githubusercontent.com/5689927/137911706-2d8b4918-a9b6-4626-8efd-f2a38d8d4cd1.png)

**REMARKS**
Thank you component shown in Test 1 & 2 will replace the old one below
It will replace this thank you page:
![image](https://user-images.githubusercontent.com/5689927/136932599-979fabd9-43b2-4574-bf6f-b863a8c58d1f.png)

Related to {1200182182542585-as-1201102838390955}

2021-10-12 12:51 UTC, michaeldcain approved these changes
This works well from a Payments perspective. I'd love to see this design rolled out to all Thank You pages - I'll create an issue to track that work.

As an aside, I noticed that there's a white bar above the header on the desktop view:
<img width="1190" alt="Screen Shot 2021-10-12 at 8 42 37 AM" src="https://user-images.githubusercontent.com/942359/136959249-66b82220-a7bf-41a2-87c5-cc94c0babce0.png">

Also, the vertical padding on the header doesn't look right on mobile:
<img width="364" alt="Screen Shot 2021-10-12 at 8 47 15 AM" src="https://user-images.githubusercontent.com/942359/136959357-e772282a-5859-4efc-82c9-8155adc8bd92.png">

Can we make sure that those get cleaned up? If not in this PR than in another right after. /cc @saygunnyc

2021-10-13 09:34 UTC, AllTerrainDeveloper commented
> This works well from a Payments perspective. I'd love to see this design rolled out to all Thank You pages - I'll create an issue to track that work.
> 
> As an aside, I noticed that there's a white bar above the header on the desktop view: <img alt="Screen Shot 2021-10-12 at 8 42 37 AM" width="1190" src="https://user-images.githubusercontent.com/942359/136959249-66b82220-a7bf-41a2-87c5-cc94c0babce0.png">
> 
> Also, the vertical padding on the header doesn't look right on mobile: <img alt="Screen Shot 2021-10-12 at 8 47 15 AM" width="364" src="https://user-images.githubusercontent.com/942359/136959357-e772282a-5859-4efc-82c9-8155adc8bd92.png">
> 
> Can we make sure that those get cleaned up? If not in this PR than in another right after. /cc @saygunnyc

Thank you for the review! The gap in the header is already awaiting review 🙂  in this [pull request](https://github.com/Automattic/wp-calypso/pull/56358).

2021-10-13 10:37 UTC, daledupreez requested changes
@AllTerrainDeveloper, I believe we need new content here to support actions for the domain the user just purchased. As per the designs in mZXo4ZagpIMWtu526c17W5-fi-2081%3A3348, the content needs to include a way for the user to manage their domain. 

For this specific use case, we also want to replace the "Get Professional Email" CTA from the design with the "Go to Inbox" CTA we have in place for Professional Email (which you already have here).

To handle this, it may be worth extending the existing `DomainThankYou` component to support this additional use case, rather than using `TitanSetUpThankYou`.

2021-10-15 10:06 UTC, daledupreez requested changes
Thanks for switching over to the domain template!

The big issue right now is that we are using the template/content for a domain mapping + email, when we also need content for a domain registration + email. The actions for a domain mapping and a domain registration are very different. :-/

2021-10-17 16:29 UTC, a8ci18n commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
> +			stepTitle: translate( 'Get Professional Email' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **18** times:
`translate( 'Why get Professional Email?' )` *ES Score: 9*

2021-10-19 08:38 UTC, stephanethomas commented
![image](https://user-images.githubusercontent.com/5689927/137751158-09f740e6-1bfe-42e2-b198-4d2a048b1045.png)

I'm not a big fan of this heading:

> Get Professional Email

As far as I understand the user will be redirected to the `Email Comparison` page if they click the corresponding CTA, and this page is going to show both Titan and Google Workspace. I don't see a good reason to tailor that heading for a specific email solution on this `Thank You` page, and would suggest the following copy instead: 

> Get a professional email

2021-10-19 09:07 UTC, AllTerrainDeveloper commented
> ![image](https://user-images.githubusercontent.com/5689927/137751158-09f740e6-1bfe-42e2-b198-4d2a048b1045.png)
> 
> I'm not a big fan of this heading:
> 
> > Get Professional Email
> 
> As far as I understand the user will be redirected to the `Email Comparison` page if they click the corresponding CTA, and this page is going to show both Titan and Google Workspace. I don't see a good reason to tailor that heading for a specific email solution on this `Thank You` page, and would suggest the following copy instead:
> 
> > Get a professional email

It's a good point Stéphane, I'm happy to address it (and therefore address also the non-primary style for Add Email)

2021-10-19 09:47 UTC, daledupreez reviewed
I had a _lot_ of comments here, and I think there are some items that need decisions before I dive into testing.

2021-10-19 09:47 UTC, daledupreez commented on client/assets/images/illustrations/domain-success.svg
> +<svg width="260" height="150" viewBox="0 0 260 150" fill="none" xmlns="http://www.w3.org/2000/svg">
It may be worth calling this `domain-registration-success.svg` to better differentiate it from `domain-connected-success.svg` and `domain-transferred-success.svg` in the same directory.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
> +	hasProfessionalEmail: boolean;
In a follow-up PR, we should add logic to handle the case where the user has purchased Google Workspace for the domain. For that case, we don't want to show the "Add Email" CTA _and_ we don't want to show the "Go to Inbox" CTA due to the time it generally takes for the Google provisioning process to complete.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-mapping.tsx
> +import * as React from 'react';
Why do we need this import? I don't see `React` referenced in the file.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-mapping.tsx
> +	const professionalEmail = buildCtaForProfessionalEmail(
Nit: it may be worth calling this `professionalEmailStep` to be slightly clearer as to what the entity is.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-mapping.tsx
>  import { DomainThankYouParams, DomainThankYouProps } from '../types';
Nit: should this not be `import type`?

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
> +import { DomainThankYouParams, DomainThankYouProps } from '../types';
Should this not be `import type`?

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
> +import domainConnectedSuccess from 'calypso/assets/images/illustrations/domain-success.svg';
I think this should be `domainSuccess` or `domainRegisteredSuccess` instead of `domainConnectedSuccess`.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
> +import * as React from 'react';
Why do we need this import? I don't see `React` referenced below.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
> +	const professionalEmail = buildCtaForProfessionalEmail(
As above, I think this variable should be called `professionalEmailStep`.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
> +		thankYouImage: { alt: translate( 'Domain Connected' ), src: domainConnectedSuccess },
The alt text should be `Domain Registered`, and the variable name should also reflect that this is a registration.
```suggestion
		thankYouImage: { alt: translate( 'Domain Registered' ), src: domainConnectedSuccess },
```

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
> +} from '../types';
Should this not be `import type`?

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
> +export function buildCtaForProfessionalEmail(
I think this should be called `buildStepForProfessionalEmail`, as we're technically returning a `ThankYouNextStepProps` type here (even if that's wrapped by the `DomainThankYouProps` type definition).

It may also be worth calling it `buildDomainStepForProfessionalEmail` to make the domain relationship more explicit in the name.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
> +	source: string,
Maybe this should be called `domain_type` and match the `DomainThankYouType` values? That way we're enforcing more type safety on callers.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
> +			stepKey: `domain_${ source }_whats_next_view_posts`,
Should this not be `domain_${ source }_whats_next_get_professional_email`?

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/index.tsx
> +		stepKey: `domain_${ source }_whats_next_plugin_setup_view_inbox`,
Not sure that we need the `plugin` here -- maybe using `email` would be better?

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +		let wasDomainMappingOrRegistration = false;
It may be cleaner to simply use a single `wasDomainProduct` flag here. I'll share the logic possibilities in the code below.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +		let hasProfessionalEmail = false;
Might it be better to call this `wasTitanEmailProduct` to align with the existing variable names?

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +				purchases.some( isDomainRegistration ) || purchases.some( isDomainMapping );
Two notes here:
1. As noted above RE variable naming it might be simpler to use one `wasDomainProduct` variable.
2. Might it not be better to use a single `.some()` call that applies the `||` within the `.some()` function? We do this in the logic above?
```suggestion
				purchases.some(
					( purchase ) => isDomainMapping( purchase ) || isDomainTransfer( purchase ) || isDomainRegistration( purchase )
				);
```

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +			);
If we shift to a single `wasDomainProduct` variable, we can clean this logic up as follows:
```suggestion
		} else if ( wasDomainProduct ) {
			const [ purchaseType, predicate ] = this.domainPurchaseType( purchases );
			const [ , domainName ] = findPurchaseAndDomain( purchases, predicate );

			const inboxPurchase = this.getProfessionalEmailFromPurchase(
				purchaseType,
				purchases
			);
```

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +		}
It might be cleaner to capture the `filter` output in a variable.
```suggestion
		const titanMailPurchases = purchases.filter( isTitanMail );
		if ( titanMailPurchases.length > 0 ) {
			return titanMailPurchases[ 0 ];
		}
```

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +	getProfessionalEmailFromPurchase( wasDomainMappingOrRegistration, purchases ) {
Nit: I think this should be `getProfessionalEmailPurchaseFromPurchases()` to match the arguments and return type.

I am also concerned that there is no way of knowing that we're not going to return an object if we didn't buy the right kind of domain. I think it may be better to move that piece of logic into the calling code, because that filter step doesn't really match what the rest of the function does.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +	domainPurchaseType( purchases ) {
I think this should be called `getDomainPurchaseType( purchases )` to reflect that we're returning purchase type data.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +		if ( purchases.some( isDomainMapping ) && purchases.some( isDomainRegistration ) ) {
Tiny nit: it may be worth using `const hasDomainMapping = purchases.some( isDomainMapping );` to avoid calling that `.some()` function twice, but that may also be an unnecessary optimisation.

2021-10-19 09:47 UTC, daledupreez commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +			const inboxPurchase = this.getProfessionalEmailFromPurchase(
Nit: I would prefer if we called this `titanPurchase` or `professionalEmailPurchase`.

2021-10-19 10:04 UTC, AllTerrainDeveloper commented on client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
> +	hasProfessionalEmail: boolean;
Probably it needs tweaking already, I don't think it's a good idea to show that user needs professional Email when they just bought Google Workspace?

2021-10-19 10:08 UTC, AllTerrainDeveloper commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-mapping.tsx
>  import { DomainThankYouParams, DomainThankYouProps } from '../types';
I also removed the relative path, it's copy-paste from the sibling template.

2021-10-19 10:18 UTC, AllTerrainDeveloper commented on client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
> +	hasProfessionalEmail: boolean;
@daledupreez Is it better to just show "go to inbox" when the user has Google Workspace?

EDIT: Ok I just got that Google Workspace takes time to provision. Makes sense to do not show this step at all.

2021-10-19 11:04 UTC, a8ci18n commented on client/my-sites/checkout/checkout-thank-you/domains/thank-you-content/domain-registration.tsx
> +		thankYouImage: { alt: translate( 'Domain Registered' ), src: domainRegisteredSuccess },
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **38** times:
`translate( 'Registered Domain' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/thank-you-page-when-buying-domain-with-professional-email)

2021-10-19 11:29 UTC, AllTerrainDeveloper commented on client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
> +	hasProfessionalEmail: boolean;
I've added a new prop to show inbox/add email step. Not sure anyway if it's the best solution

2021-10-20 17:10 UTC, olaseni requested changes
The thank you page isn't shown when you purchase an additional mailbox for Google Workspace. It already works for Professional Email, so let's fix that.

Additionally, while we don't show the button/link to go the inbox/email view after purchasing Google Workspace, because of the time it takes to provision, I think it's generally okay to show that view for additional mailboxes though.

I have a few other comments, but other than that, we are looking almost good to go.

2021-10-20 17:10 UTC, olaseni commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +			wasGSuiteOrGoogleWorkspace = purchases.some( isGSuiteOrGoogleWorkspace );
This excludes additional mailboxes purchased for Google Workspace. Let's add that scenario as we do the same for Professional Email.

Right now what happens is when one purchases additional mailboxes for Google Workspace, the new UX isn't shown.

2021-10-20 17:10 UTC, olaseni commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +		let wasTitanEmailProduct = false;
It might be more meaningful to add an action to this variable names to make it easier to glean the intent without digging further into the code.

Perhaps `wasDomainProductPurchased`, `wasGSuiteOrGoogleWorkspacePurchased`, `wasTitanEmailProductPurchased`?

2021-10-20 17:10 UTC, olaseni commented on client/my-sites/checkout/checkout-thank-you/index.jsx
> +					hideProfessionalEmailStep={ wasGSuiteOrGoogleWorkspace }
Don't forget to include the scenario where we add additional mailboxes for Workspace as well

2021-10-20 17:10 UTC, olaseni commented on client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
> +} from 'calypso/my-sites/checkout/checkout-thank-you/domains/types';
Why did we switch this reference ONLY to the absolute import?

2021-10-20 17:10 UTC, olaseni commented on client/my-sites/checkout/checkout-thank-you/domains/domain-thank-you.tsx
> +	includeInbox: string;
Looks we didn't really need this prop.

2021-10-20 17:48 UTC, stephanethomas commented
> Additionally, while we don't show the button/link to go the inbox/email view after purchasing Google Workspace, because of the time it takes to provision, I think it's generally okay to show that view for additional mailboxes though.

I have mixed feeling about this. I agree that provisioning additional Google Workspace mailboxes takes less time than provisioning a new Google Workspace account (there are less steps in this asynchronous process after all). However, while it's difficult to predict the amount of time it will take (it is a factor of the number of mailboxes purchased), it is certainly not immediate. I would personally stay on the safe side, and provide a link that direct users to the `Email Plan` page instead.

2021-10-20 18:41 UTC, daledupreez commented
> The thank you page isn't shown when you purchase an additional mailbox for Google Workspace. It already works for Professional Email, so let's fix that.

I think we should handle that in a follow-up PR for two reasons:
 * The main driver for this PR was updating the Thank You page for the domain purchase flow to ensure Professional Email users can quickly access their webmail - this use case seems to be addressed
 * Re-testing this entire PR is going to be time-consuming - it will be faster for us to ship all the working pieces as-is and tackle the Google-specific elements in a follow-up. (I don't believe that functionality is currently in the Thank You pages, so I think we're OK.)

@olaseni, given my thinking above, do you think it's OK to merge this with the known gaps?

2021-10-21 08:24 UTC, AllTerrainDeveloper commented
I agree with Dale in the way of creating a new task for the inbox in Workspace. My point is that in the current task for this PR was mentioned only to add the new UI component to the domain registration flow, and ended up to be including also the mapping domain scenario. Now adding a new scenario will be 3 tasks for the price of one 😆

2021-10-21 15:56 UTC, olaseni commented
> > The thank you page isn't shown when you purchase an additional mailbox for Google Workspace. It already works for Professional Email, so let's fix that.
> 
> I think we should handle that in a follow-up PR for two reasons:
> 
> * The main driver for this PR was updating the Thank You page for the domain purchase flow to ensure Professional Email users can quickly access their webmail - this use case seems to be addressed
> * Re-testing this entire PR is going to be time-consuming - it will be faster for us to ship all the working pieces as-is and tackle the Google-specific elements in a follow-up. (I don't believe that functionality is currently in the Thank You pages, so I think we're OK.)
> 
> @olaseni, given my thinking above, do you think it's OK to merge this with the known gaps?

I'm totally on board with working on the additional mailboxes scenario in another PR @AllTerrainDeveloper @daledupreez

2021-10-21 15:57 UTC, olaseni approved these changes

2021-10-21 16:26 UTC, merged

2021-10-21 17:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6868435

Thank you @AllTerrainDeveloper for including a screenshot in the description! This is really helpful for our translators.

2021-10-21 17:52 UTC, worldomonation commented
Filed #57239 to fix the broken Domain: Add test in Pre-Release E2E tests.

2021-10-28 15:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6868435).