Fix plugins-browser-list placeholders
Automattic/wp-calypso pull request #56966
Opened 2021-10-12 19:26 UTC by gcsecsey

#### Changes proposed in this Pull Request

* Refactored the logic of showing placeholders to cover all cases correctly
* Added a required prop to the test mock

#### Testing instructions

* Go to Calypso live
* Click on the "See All" button on the top right of the "Popular" or "New" sections and do a sanity check, the initial render should show the placeholder as before
* Scroll down and validate that the placeholders are being appended to the plugins list
* Search for a plugin
* Do a sanity check, the initial render should show the placeholder as before
* Navigate to other pages with the pagination control, and validate that the placeholders are displayed in place of the whole list

| Event, `props` | Before | After |
| ----- | ------ | ----- |
| Initial render (works as before), `plugins = [], showPlaceholders = false, paginated = false` | ![calypso localhost_3000_plugins_popular_gcsecseyfree wordpress com](https://user-images.githubusercontent.com/11555574/137014719-19e44b4f-e395-443d-a9e7-0aeaf37ecb1b.png) | ![calypso localhost_3000_plugins_popular_gcsecseyfree wordpress com](https://user-images.githubusercontent.com/11555574/137014719-19e44b4f-e395-443d-a9e7-0aeaf37ecb1b.png) |
| Initial render (works as before), `plugins = [], showPlaceholders = false, paginated = true` | ![calypso localhost_3000_plugins_popular_gcsecseyfree wordpress com_s=woocommerce](https://user-images.githubusercontent.com/11555574/137014863-6778857f-399a-421f-834e-881070810917.png) |  ![calypso localhost_3000_plugins_popular_gcsecseyfree wordpress com_s=woocommerce](https://user-images.githubusercontent.com/11555574/137014863-6778857f-399a-421f-834e-881070810917.png) |
| Requesting next page, `plugins = [ {...}, {...}, {...} ], showPlaceholders = true, paginated = true` | ![wordpress com_plugins_gcsecseyfree wordpress com_s=woocommerce (1)](https://user-images.githubusercontent.com/11555574/137015423-bcdccc16-be24-446c-a2ed-1cd58bdb1d0f.png) |  ![calypso localhost_3000_plugins_popular_gcsecseyfree wordpress com_s=woocommerce (1)](https://user-images.githubusercontent.com/11555574/137015347-7849c41e-5c46-45f7-843d-84e1ad3f4573.png) |
| Requesting next page, `plugins = [ {...}, {...}, {...} ], showPlaceholders = true, paginated = false` | ![wordpress com_plugins_gcsecseyfree wordpress com_s=woocommerce (2)](https://user-images.githubusercontent.com/11555574/137015624-e3da8de1-6195-42f7-b1f4-ca1644cae44d.png) | ![calypso localhost_3000_plugins_popular_gcsecseyfree wordpress com (1)](https://user-images.githubusercontent.com/11555574/137016045-27c0309b-cd75-467a-b9e4-e246504fe609.png) |

Fixes #56793

2021-10-13 09:16 UTC, cpapazoglou commented on client/my-sites/plugins/plugins-browser-list/index.jsx
> +		return this.renderPlaceholdersViews();
Can we simplify the logic here by avoiding nested if statements? Also, it feels weird that there is a `return this.renderPlaceholdersViews();` outside the the `if ( showPlaceholders ) {` condition.

2021-10-13 09:20 UTC, cpapazoglou requested changes
Thanks for revisiting this @gcsecsey! 

I tested this following your testing instructions and works well. I just found an instance where it doesn't work as expected though:

1. Go to `/plugin/:siteId`
2. Click "Engagement"
3. Go back or click "Plugins" from the sidebar

You will notice that "Featured" section will show some placeholder below the results already shown.

![SS 2021-10-13 at 12 20 16](https://user-images.githubusercontent.com/12430020/137105195-89a52767-66a9-40f6-a092-486892fdbee5.gif)

Also, I have added a comment about simplifying the logic.

2021-10-15 16:31 UTC, gcsecsey commented
The e2e pipeline failed on one of the editor tests, so I've tried restarting it manually.

2021-10-15 16:34 UTC, gcsecsey commented on client/my-sites/plugins/plugins-browser-list/index.jsx
> +		return this.renderPlaceholdersViews();
I've managed to simplify the logic a bit by introducing the `variant` prop and creating different variants for the different loading methods, please take a look at the new changes! 🙂

2021-10-18 06:56 UTC, cpapazoglou reviewed
Just FYI, we prefer rebasing instead of merging 

> Make sure your branch merges cleanly and consider rebasing against trunk to keep the branch history short and clean.

https://github.com/Automattic/wp-calypso/blob/c90a58a5cc567aadf3bda8bd4072b466bad2ff38/docs/CONTRIBUTING.md#L88

2021-10-18 06:57 UTC, cpapazoglou commented on client/my-sites/plugins/plugins-browser-list/README.md
> +  | InfiniteScroll | Appends placeholder at the end of the list while the next page is loading |
Great job!

2021-10-18 07:12 UTC, cpapazoglou approved these changes
Tested it and works well under all circumstances!
Thanks for adding tests too!

LGTM, 🚢 !

2021-10-18 07:12 UTC, cpapazoglou commented on client/my-sites/plugins/plugins-browser-list/index.jsx
>  	}
Thanks for simplifying the logic! It's far better than before 🎉 !

2021-10-18 07:31 UTC, gcsecsey commented on client/my-sites/plugins/plugins-browser-list/README.md
> +  | InfiniteScroll | Appends placeholder at the end of the list while the next page is loading |
Thanks! :)

2021-10-18 08:25 UTC, merged