Emails: Remove EmailsHome placeholder when it's being loaded from Inbox screen
Automattic/wp-calypso pull request #57031
Opened 2021-10-14 16:13 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

Remove the placeholder shown in the EmailHome component when this component is being loaded from Inbox screen

#### Testing instructions

1. Do an initial load for Inbox (ensure nothing is cached)
2. Check that we are not showing this placeholder while loading.

If you are not able to see the loading screen after clearing caches, this method works well.

1. Navigate to Inbox or Upgrades -> Emails for the site
2. Copy the current URL
3. Open the browser developer tools and navigate to the IndexedDB section (it's under the Application tab in Chrome)
4. Clear the calypso_store database and immediately close the tab
5. Open a new tab and paste in the URL from above

![image](https://user-images.githubusercontent.com/5689927/137356244-6f4bcd0e-79bc-4ed2-b8c1-21b071adf443.png)

3. Check that the new placeholder is this one:
![image](https://user-images.githubusercontent.com/5689927/137871512-0e17a130-32a8-496c-965b-e03cc68cf3ca.png)

Related to {1200182182542585-as-1201164484498606}

2021-10-18 13:35 UTC, stephanethomas commented
I wasn't able to reproduce that issue in production, could you let me know the exact process to get that placeholder displayed?

2021-10-18 17:02 UTC, AllTerrainDeveloper commented
> I wasn't able to reproduce that issue in production, could you let me know the exact process to get that placeholder displayed?

It's a bit tough sometimes, I could replicate it a few times (after MANY tries) as it depends on how long it takes to load the subscriptions. You should have a site with many subscriptions, that takes a long to load, then clear all browsers cache (or navigate into incognito mode) to the site, and go to Inbox direcly.

2021-10-19 08:48 UTC, daledupreez approved these changes
LGTM!

For testing, I noticed this on a site that had a large number of test subscriptions on it, as it is my primary testing site. I reproduced the issue by doing the following:
* Navigate to Inbox or Upgrades -> Emails for the site
* Copy the current URL
* Open the browser developer tools and navigate to the IndexedDB section (it's under the Application tab in Chrome)
* Clear the `calypso_store` database and immediately close the tab
* Open a new tab and paste in the URL from above

These steps were pretty reliable for me to see the loading screens.

### Evidence of testing

#### Inbox


https://user-images.githubusercontent.com/3376401/137875769-e0112987-20b7-4418-81e8-cec050942a16.mov

#### Upgrades -> Emails

https://user-images.githubusercontent.com/3376401/137875785-6c887619-c2cf-428f-a6e8-5ec228440b0d.mov

_Side note: my site is **really** slow to load due to the number of subscriptions and the number of Google Workspace and G Suite subscriptions on the site._

2021-10-19 08:48 UTC, daledupreez commented on client/my-sites/email/email-management/email-home.jsx
> +import ProgressLine from "calypso/my-sites/email/inbox/mailbox-selection-list/progress-line";
Nit: this should be in the section above, not after the style import.

2021-10-19 08:53 UTC, stephanethomas commented
Note some linting tests failed.

> Do an initial load for Inbox (ensure nothing is cached)

Could you add the url you've used (it's always a good idea to mention this)? I'm trying to understand why we end up in the `EmailManagementHome` component since the Inbox should be located on a different route.

Did you use an Atomic site by the way (the screenshot is cropped unfortunately)? Maybe it's easier to reproduce that issue with this type of site? 

![image](https://user-images.githubusercontent.com/5689927/137871512-0e17a130-32a8-496c-965b-e03cc68cf3ca.png)

Why are we showing `Loading your email subscriptions` instead of `Loading your mailboxes`?

As a closing, I'm not a big fan of changing the behavior of a component based on a specific flow and this `source` prop. If we're showing the wrong placeholder, maybe that's because the `EmailManagementHome` component does too much. Or it's possible we don't handle redirects/routes correctly ?

2021-10-19 09:12 UTC, stephanethomas commented
> Or it's possible we don't handle redirects/routes correctly ?

Isn't the following line the culprit?

https://github.com/Automattic/wp-calypso/blob/164f3a95c94fa64b3590a4c1f8b0ddbd7d7583b6/client/my-sites/email/inbox/index.jsx#L99

That is, if the list of domains has not loaded yet we then display the `EmailManagementHome` component. I believe we should refactor this code so that we check if domains have loaded, and display [this placeholder](https://github.com/Automattic/wp-calypso/blob/164f3a95c94fa64b3590a4c1f8b0ddbd7d7583b6/client/my-sites/email/inbox/mailbox-selection-list/index.jsx#L245).

Honestly, we should also be redirecting to the `Emails` page instead of rendering the `EmailManagementHome` component as otherwise we are going to deal with this kind of problems all the time.

2021-10-19 10:04 UTC, daledupreez requested changes
> > Or it's possible we don't handle redirects/routes correctly ?
> 
> Isn't the following line the culprit?
> 
> https://github.com/Automattic/wp-calypso/blob/164f3a95c94fa64b3590a4c1f8b0ddbd7d7583b6/client/my-sites/email/inbox/index.jsx#L99
> 
> That is, if the list of domains has not loaded yet we then display the `EmailManagementHome` component. I believe we should refactor this code so that we check if domains have loaded, and display [this placeholder](https://github.com/Automattic/wp-calypso/blob/164f3a95c94fa64b3590a4c1f8b0ddbd7d7583b6/client/my-sites/email/inbox/mailbox-selection-list/index.jsx#L245).
> 
> Honestly, we should also be redirecting to the `Emails` page instead of rendering the `EmailManagementHome` component as otherwise we are going to deal with this kind of problems all the time.

I think @stephanethomas is correct on this one -- we should actually detect when we have no domains and show a placeholder in that situation, rather than loading what is technically an unrelated component while we're waiting for data.

2021-10-19 15:25 UTC, AllTerrainDeveloper commented
When revisiting the review, please, can we discuss if the wording when awaiting the domains is correct? I am totally confused if it should be about loading inbox, or loading subscriptions :)

2021-10-20 10:07 UTC, stephanethomas approved these changes
@daledupreez was nice enough to provide detailed testing instructions, would you mind updating the description of your pull request with them?

This pull request works fine except for one thing: it's possible to see two placeholders, i.e. the one from `InboxManagement` when domains are loading and the one from `MailboxSelectionList` when mailboxes are loading.

Since the labels are the same, one can only notice a jump in the progress bar. I don't think that's a big deal though, and feel we don't need to address this:

![video](https://user-images.githubusercontent.com/594356/138073306-9f019e6b-fa7d-4172-baeb-2d1048b78367.gif)

2021-10-20 10:07 UTC, stephanethomas commented on client/my-sites/email/inbox/index.jsx
> +			isRequestingSiteDomains( state, selectedSiteId )
Do we really want to check if we're fetching the list of domains? If something triggers a refetch then we will display the placeholder instead of the current list of mailboxes, something sub-optimal in term of user experience. For example, refreshing the page will show the list of mailboxes, then the placeholder, then the list again.

2021-10-20 10:08 UTC, stephanethomas commented
> can we discuss if the wording when awaiting the domains is correct? I am totally confused if it should be about loading inbox, or loading subscriptions :)

I think `Loading your mailboxes` is perfect.

2021-10-20 10:14 UTC, AllTerrainDeveloper commented on client/my-sites/email/inbox/index.jsx
> +			isRequestingSiteDomains( state, selectedSiteId )
Hmmm, good point! I think you are right. Something out of scope might trigger a request and we will show a loading screen, when probably it does not need to be presented to the user this action, feels like an interruption for him. I like it!

2021-10-20 11:14 UTC, AllTerrainDeveloper commented
> > can we discuss if the wording when awaiting the domains is correct? I am totally confused if it should be about loading inbox, or loading subscriptions :)
> 
> I think `Loading your mailboxes` is perfect.

I've added your suggestion about not showing the loader when something triggers domain fetching :) Are we good to go?

2021-10-20 13:13 UTC, stephanethomas commented
Yes, all good 🚢

2021-10-21 09:53 UTC, merged