ETK: Site Editor overrides - remove unnecessary css rule and file.
Automattic/wp-calypso pull request #57034
Opened 2021-10-14 18:07 UTC by Addison-Stavlo

#### Changes proposed in this Pull Request

We previously hid the "Browse all templates" button in the site editor as part of the effort to remove the navigation sidebar on dotcom.  Recently, css added to core has overridden our `display: none` due to specificity and has caused the menu to reappear.  After team discussions, we have decided to keep the button visible and are removing the css that hid it.

#### Testing instructions

* Patch this ETK build to your sandbox.
* Smoke test, there should be no visible changes.

Related to #

2021-10-14 18:53 UTC, vindl requested changes
I'd prefer if we don't do this for two reasons:

1. We are using a hacky CSS way to hide the sidebar, which is fragile and can break on updates.
2. Given that Browse All Templates is not as prominent now, I think it's better to keep it for advanced users.

To expand on the above. Universal themes already ship additional templates aside from the `index` or `page`, which wouldn't be editable otherwise.

In addition to that, we already override the W button to exit the editor, which was arguably the most prominent problem with the current Browsing Sidebar in core (not being able to find a way to exit to the dashboard).

2021-10-14 19:39 UTC, Addison-Stavlo commented
> I'd prefer if we don't do this for two reasons:

This makes sense to me.  I have updated the PR to remove the unnecessary css rule and file instead.  This is no longer urgent as it causes no change in functionality.

2021-10-14 22:31 UTC, vindl approved these changes

2021-10-15 12:20 UTC, Addison-Stavlo commented
Oops, one more change pushed as I noticed a php warning.  We were still calling `wp_enqueue_style` for a style file that was no longer being built. 😅

2021-10-15 16:17 UTC, creativecoder approved these changes
Looks good, no visible changes I can see (as expected from the testing instructions).

Thanks for cleaning this up!

2021-10-15 16:37 UTC, merged