Fix: Mobile web styling of the domain picker
Automattic/wp-calypso pull request #57048
Opened 2021-10-15 00:10 UTC by enejb

#### Changes proposed in this Pull Request

This PR fixes some of the stylings on the /start/domains screen for mobile web users. 
Currently, there seems to be inconsistency in the horizontal spacing. Between the "recommended" domains and the free. 

See:
![Screenshot_2021-10-15_at_14-15-11_Create_a_site_—_WordPress_com](https://user-images.githubusercontent.com/115071/137794231-df585cb4-c8e6-4385-822a-d42eacd29803.png)

#### Testing instructions

Visit /start/domains on responsive screen or iPhone simulator and notice that it looked more as expected. (The indentation doesn't seem off) 

Before:

<img src="https://user-images.githubusercontent.com/115071/137410080-86f8a9af-855e-4bac-b280-bd536a2e40ea.png" width="300" />
<img src="https://user-images.githubusercontent.com/115071/137410800-5fc67450-e4b3-4f54-916b-4eeefadcbde2.png" width="300" />

After:
<img src="https://user-images.githubusercontent.com/115071/137410047-5096e166-3b7d-42eb-97c9-3967a6264893.png" width="300" />

Fixes https://github.com/Automattic/wp-calypso/issues/57009

2021-10-18 13:29 UTC, niranjan-uma-shankar requested changes
@enejb Could you please provide more context on the design changes made in this PR?

Listing below the ones I observed:

1. The border-radius property has been removed for the featured domain section in desktop resolution. Was this intentional? 

**Before**

<img width="118" alt="Screenshot 2021-10-18 at 5 18 11 PM" src="https://user-images.githubusercontent.com/1269602/137739001-bf447adf-064c-40b4-b1c7-e9dc0ed0139d.png">

**After**
<img width="138" alt="Screenshot 2021-10-18 at 5 18 05 PM" src="https://user-images.githubusercontent.com/1269602/137738985-664e2d71-166e-43b6-9f9d-41795a757966.png">

2. In mobile resolution, the domains in the featured domain section have been extended to full width:

**Before**
Featured domain box

<img width="364" alt="Screenshot 2021-10-18 at 5 21 13 PM" src="https://user-images.githubusercontent.com/1269602/137739999-220e5d0e-69f8-4d2c-9b7c-18cf7daf0705.png">

**After**
Featured domain extended full width


<img width="359" alt="Screenshot 2021-10-18 at 5 30 46 PM" src="https://user-images.githubusercontent.com/1269602/137741503-b3e05ba5-5366-4f60-af30-c301ad53d1b3.png">

3. Quoting from the testing instructions in this PR:

> Visit /start/domains on responseive screen or iPhone similator and notice that it looked more as expected. (The indentation doesn't seem off)

With the full width implementation, the indentation still seems off. In the current production version, the white box surrounding the domain suggestion is aligned with the search input box. I guess this might look like it's not indented properly:

<img width="240" alt="Screenshot 2021-10-18 at 5 28 14 PM" src="https://user-images.githubusercontent.com/1269602/137740921-90cb5706-2aac-4a94-ae6b-d520dc77737c.png">

However, in this PR I would have expected the "Recommended" tag and domain name to be aligned with the search input box, but that's not the case:
<img width="312" alt="Screenshot 2021-10-18 at 5 25 43 PM" src="https://user-images.githubusercontent.com/1269602/137740763-4b301beb-201c-4b0c-af1e-f5c18da47361.png">


cc'ing @ollierozdarz in case you have thoughts to share.

2021-10-18 13:29 UTC, niranjan-uma-shankar commented on client/components/domains/featured-domain-suggestions/style.scss
> +	@include break-mobile {
This affects the featured domain suggestions indentation on desktop:

**Before**
<img width="1021" alt="Screenshot 2021-10-18 at 5 04 36 PM" src="https://user-images.githubusercontent.com/1269602/137736589-9660c7ce-a1c5-4b70-9440-3867cdb3fb20.png">

**After**

<img width="1008" alt="Screenshot 2021-10-18 at 5 04 43 PM" src="https://user-images.githubusercontent.com/1269602/137737132-a53dfbfd-7d4b-4c7a-a17c-457e0d6e4194.png">

2021-10-18 19:34 UTC, enejb commented
Thanks for the review @niranjan-uma-shankar 
I tried to provide a bit more context in the description. 

I think the main thing that this PR is trying to address is the horizontal spacing on mobile. We (@yaelirub  and I) thought that the "recommended" domains section should match the ones following the recommended ones. 

The other responsive views look great as designed and should stay the same. Currently, they don't anymore in this PR :( - I will fix that now.  (Thanks for catching that)

2021-10-18 23:51 UTC, enejb commented
@niranjan-uma-shankar  Do you mind taking another look when you have the chance?

2021-10-19 11:13 UTC, niranjan-uma-shankar approved these changes
LGTM

2021-10-19 18:24 UTC, merged