Onboarding: Adjust styles of design picker according to feedback
Automattic/wp-calypso pull request #57053
Opened 2021-10-15 06:20 UTC by arthur791004

#### Changes proposed in this Pull Request

According to the Pod sync document, we need to refine some styles of Design Picker as followed
- [x] Design picker
  - [x] Hover needs dark border
  - [x] Hovering anywhere in the card link to the preview, but the ‘Start..’ button should still do as intended.
- [x] Design preview
  - [x] Device icons look shrunken
  - [x] Theme name in header is too big
  - [x] Pressing < Back takes you to the intent screen, not to the design picker as intended.

##### Hover on the design and its border is dark
![image](https://user-images.githubusercontent.com/13596067/137441490-3f1e7602-58fa-44ab-b2d7-8dccf505758d.png)

##### Current theme name and devices icon
![image](https://user-images.githubusercontent.com/13596067/137441517-49ec560f-f4c4-4b71-8fc5-aac8b5a01657.png)

#### Testing instructions

* Go to `/start/setup-site?flags=signup/hero-flow&siteSlug=<your_site>`
* Select build intent
* Play with design picker and its preview to check the above behavior is correct

Related to https://github.com/Automattic/wp-calypso/issues/56957

2021-10-20 07:48 UTC, roo2 requested changes
I left have some feedback, the main thing is that the blank canvas is not clickable on desktop

https://user-images.githubusercontent.com/22446385/138050669-ef881bb4-8b3b-476e-b993-d9e4eb039393.mov

2021-10-20 07:48 UTC, roo2 commented on packages/design-picker/src/components/index.tsx
> +	if ( isBlankCanvas ) {
On Desktop, I'm not able to select blank canvas

2021-10-20 07:48 UTC, roo2 commented on client/signup/steps/design-picker/index.jsx
> +			const locale = ! userLoggedIn ? getLocaleSlug() : '';
I don't understand this ternary. For a logged in user, this will resolve to the empty string`''`. At least currently, the design picker should only be shown to logged in users. so I'm not sure if this check is even neccessary here?

2021-10-20 07:48 UTC, roo2 commented on client/signup/steps/design-picker/preview-toolbar.jsx
> +								size={ device === 'computer' ? 36 : 24 }
I think it would be more elegant to give each device a `size` property here

2021-10-20 07:48 UTC, roo2 commented on packages/design-picker/src/components/style.scss
> +	.design-picker__design-option-header {
hmm this is a smaller version of the `preview-toolbar__browser-header` class used by the preview. I see why you didn't make it shared though because of the other class just being defined in `client/signup` 🤷 if you can see a way to share code that would be nice, but otherwise it's fine.

2021-10-20 07:57 UTC, arthur791004 commented on client/signup/steps/design-picker/index.jsx
> +			const locale = ! userLoggedIn ? getLocaleSlug() : '';
I just follow the current behavior to get the locale for the back URL. I think we should keep this behavior consistent no matter design picker will be shown to non-logged-in users or not

2021-10-20 08:58 UTC, arthur791004 commented on packages/design-picker/src/components/style.scss
> +	.design-picker__design-option-header {
I think it might be better to have a component named `WebPreviewHeader` or `BrowserHeader` in the `WebPreview` component and we can re-use it between `PreviewToolbar` and `DesignPicker`. But the `WebPreview` is the calypso component rather than the general component inside `@automattic/components`. So I prefer to keep the current implementation.

2021-10-20 08:58 UTC, arthur791004 commented on packages/design-picker/src/components/index.tsx
> +	if ( isBlankCanvas ) {
Oops...I've fixed the problem. Thank you 👍

2021-10-22 07:59 UTC, roo2 approved these changes
retested and LGTM!

2021-10-22 07:59 UTC, roo2 commented on client/signup/steps/design-picker/index.jsx
> +			const locale = ! userLoggedIn ? getLocaleSlug() : '';
ok, I see that it's the current behavior and it doesn't break anything since the stepUrls do not actually need a localeSlug to work correctly. I suspect that it's either not necessary or not working as expected in all of these places but I can look into that separately to this PR 👍

2021-10-22 08:46 UTC, merged