i18n: Fix translations on the Use my domain screen
Automattic/wp-calypso pull request #57064
Opened 2021-10-15 13:29 UTC by sdnunca

#### Changes proposed in this Pull Request

* Adds dynamic getters to the translated properties of `optionInfo` objects so that `__` is called every time they are accessed, to make sure the text is refreshed when translations are loaded.

#### Testing instructions
1. Change your user language to a non-English language.
1. Go to https://wordpress.com/domains/add/use-my-domain/{site-URL}
1. Enter a test domain name, such as example.com.
1. Make sure the mapping options are translated:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/23708351/137494796-a0d5017a-66e5-4c32-8119-b35557c19d89.png">

Related to #325-gh-Automattic/i18n-issues

2021-10-15 14:19 UTC, yuliyan reviewed
The `Use a domain I own` title on the initial screen and the `Suggested setup` title, when you select the `Connection your domain` option, still appear untranslated.

2021-10-15 14:19 UTC, yuliyan commented on client/components/domains/use-my-domain/utilities/option-info.js
> +	transferSupported,
I suppose, these were extracted as separate constants for better readability?

2021-10-15 16:26 UTC, delputnam commented
@sdnunca Thanks for the PR. Is this the recommended way to ensure that the correct text is rendered after the translated strings are loaded?

It feels redundant to have to list all of the strings twice.  Is there a better way we (@Automattic/nomado) could have handled this to avoid this issue?

2021-10-15 16:50 UTC, rafaelgallani commented
@sdnunca Thanks for the PR!
I was working on it as a part of #56366, so I had already addressed the points commented by @yuliyan. 
I'll cherry-pick and change them a bit to make them similar to your commits and push them to your branch 😄

2021-10-20 00:34 UTC, sdnunca commented
@delputnam The redundant strings felt weird to me as well. I've updated the PR to use getters directly when creating the object. 

@rafaelgalani Thank you so much for your work on this. Apologies for the inconvenience, I was not aware you're already looking into this. 

@yuliyan Do you see any potential issues with using getters this way? I've double checked to make sure the strings are still extracted correctly and it seems fine.

2021-10-20 12:40 UTC, yuliyan commented
> @yuliyan Do you see any potential issues with using getters this way? I've double checked to make sure the strings are still extracted correctly and it seems fine.

@sdnunca, IIRC, initially I got some build errors with the getter syntax and had to switch to `Object.defineProperty` with the duplicated strings, but that doesn't seem to be applicable anymore. I don't think there'll be any problems, so it looks like a nice improvement!

2021-10-27 19:17 UTC, rafaelgallani commented
Rebasing on `trunk`

2021-10-27 19:20 UTC, rafaelgallani commented
@yuliyan Could you please take one last look at it again? I'll merge this PR since some other developments we're doing depend on it.
I just rebased it with the latest `trunk` changes. I tested it again and it looks good to me both code and translation-wise. 😄

2021-10-28 10:25 UTC, yuliyan requested changes
@rafaelgalani, I'm getting reference errors when I go to `domains/add/use-my-domain/`, likely due to used undefined `__` dependency in [use-my-domain/index.js](https://github.com/Automattic/wp-calypso/blob/bf1c5f852b73c4840964daf255a0902aeafca65d/client/components/domains/use-my-domain/index.jsx).

2021-10-28 10:25 UTC, yuliyan commented on client/components/domains/use-my-domain/index.jsx
> +	}, [ domainName, mode, inputMode, __ ] );
I think you forgot to call `useI18n` hook and as a result `__` is not defined in the scope.

2021-10-28 10:25 UTC, yuliyan commented on client/components/domains/connect-domain-step/constants.ts
> +Object.defineProperties( stepsHeading, {
`Object.defineProperties` here could probably be avoided if you use the getter syntax, similar to how it's been done in [use-my-domain/utilities/option-info.js](https://github.com/Automattic/wp-calypso/blob/bf1c5f852b73c4840964daf255a0902aeafca65d/client/components/domains/use-my-domain/utilities/option-info.js)

2021-10-28 10:25 UTC, yuliyan commented on client/components/domains/connect-domain-step/page-definitions.js
> +		name: labels[ stepSlug.SUGGESTED_LOGIN ](),
~~I don't think this would work - `labels[ stepSlug.SUGGESTED_LOGIN ]` will only be called once during the initial property definition, whereas it's expected `__` to be always executed when property is accessed.~~
I missed the `Object.defineProperties` loop at the bottom. However, I think this can also be simplified using the getter syntax.

2021-10-28 16:06 UTC, rafaelgallani commented on client/components/domains/use-my-domain/index.jsx
> +	}, [ domainName, mode, inputMode, __ ] );
That's weird - even weirder that this is not even coming from this PR, anyway, just added it, thanks 😄

2021-10-28 16:07 UTC, rafaelgallani commented
@yuliyan Done! Thanks for your review. Can you please take one last look? 😄 
I re-tested it and it all looks good - everything correctly translated.

2021-10-29 12:46 UTC, yuliyan approved these changes
Tested again and it seems to be working fine. I couldn't spot any issues, so it LGTM 🚀

2021-10-29 15:20 UTC, rafaelgallani commented
@yuliyan Thank you! Merging 🚀

2021-10-29 15:21 UTC, merged