Help Center: Add help center modal
Automattic/wp-calypso pull request #57086
Opened 2021-10-17 16:05 UTC by razvanpapadopol

#### Changes proposed in this Pull Request

* Add Help Center behind a feature flag
* Use the content from `/help` page

#### Testing instructions

* Open the live link and add `?flags=help-center-modal` to the URL to enable the feature flag
* Open Help FAB and click on "More Help" button
* Explore the Help Center modal
  * Contact and upsell offers will redirect you to the correct page
  * Going back using the browser Back button will open the Help Center modal
  * All the links to support resources will open externally, similar as they do on `/help`

#### Demo

https://user-images.githubusercontent.com/14192054/138083916-f89decec-d061-4952-942c-634e8b7826be.mov

2021-10-20 13:51 UTC, poligilad-auto commented
Looking cool @razvanpapadopol!

A few comments:
1. Could we align this with how the "W" looks in the onboarding reskin? So 24px, var(--color-text) and top & left margins.
![image](https://user-images.githubusercontent.com/83961704/138104868-0a73c630-aec9-46cc-8510-0f9343767345.png)
2. I think you are using the "close-small" icon. Can we use "close" instead. It's really small now.
![image](https://user-images.githubusercontent.com/83961704/138104800-3dff4404-0476-4a08-a1c2-87e9986bc03a.png)
3. Can you change the background color to: #fdfdfd like in the onboarding reskin.
4. Was thinking that after scrolling a bit we could add a bottom border (1px solid var(--studio-gray-5);) to the header, currently it just cuts the content of the page in a strange way.
![image](https://user-images.githubusercontent.com/83961704/138106076-f4695064-7b26-4119-846d-bb6d542b07c9.png)

2021-11-04 06:13 UTC, razvanpapadopol commented
Thanks for the feedback, @poligilad-auto!

I've implemented the suggested changes (you can check again with live link) except for this one:

> I think you are using the "close-small" icon. Can we use "close" instead. It's really small now.

The close icon is part of the standard `@wordpress/components` modal and there are already a few occurrences of this component on WordPress.com. However, the icon change may be proposed upstream in Gutenberg.

1. The editor checkout modal when you press on the Upgrade button for a premium block while being on a free plan.
<img width="1127" alt="Screenshot 2021-10-22 at 11 23 41" src="https://user-images.githubusercontent.com/14192054/140265563-93e5ef9c-2ba6-47fd-8832-7c742a1dc971.png">
<img width="1245" alt="Screenshot 2021-10-22 at 11 22 58" src="https://user-images.githubusercontent.com/14192054/140265573-cf16545d-23e6-4748-b41f-baffdb3edfc4.png">

2. The page picker modal when you try adding a new page to your site.
<img width="1209" alt="Screenshot 2021-10-22 at 11 19 32" src="https://user-images.githubusercontent.com/14192054/140265581-38766890-dad8-436c-9e04-c53d99409a60.png">

2021-11-04 09:56 UTC, StefanNieuwenhuis requested changes
Great job @razvanpapadopol! I left some comments that I would like you to address. Thanks so much already 🙏

2021-11-04 09:56 UTC, StefanNieuwenhuis commented on client/layout/index.jsx
> +	}
This feels more like a utility function to me. WDYT about moving it to `utils.ts` and add a unit test?

2021-11-04 09:56 UTC, StefanNieuwenhuis commented on client/layout/style.scss
> +}
Why do we have to remove the vertical scroll?

2021-11-04 09:56 UTC, StefanNieuwenhuis commented on client/blocks/help-center-modal/style.scss
> +	}
See my previous comment. I think this one can be moved to a mixin as well.

2021-11-04 09:56 UTC, StefanNieuwenhuis commented on client/blocks/editor-checkout-modal/style.scss
> +	}
Since we're using the same styling in the help center modal, we can create a mixin and use it in both. WDYT?

2021-11-04 09:56 UTC, StefanNieuwenhuis commented on client/blocks/help-center-modal/style.scss
> +	// See https://github.com/Automattic/wp-calypso/pull/47601#discussion_r530570891
Created https://github.com/Automattic/wp-calypso/issues/57639 to keep track.

2021-11-04 09:56 UTC, StefanNieuwenhuis commented on client/blocks/editor-checkout-modal/index.tsx
> +			icon={ <Icon icon={ wordpress } size={ 29 } /> }
The `<Icon/>` accepts any `number` for the size attribute but the [docs](https://wordpress.github.io/gutenberg/?path=/docs/components-icon--sizes) a fixed range is proposed. 

Do we want, for the sake of consistency, to use the _defaults_ (e.g. `28` or `32`) or defer from it?

2021-11-05 10:05 UTC, poligilad-auto commented
> The close icon is part of the standard @wordpress/components modal and there are already a few occurrences of this component on WordPress.com. However, the icon change may be proposed upstream in Gutenberg.

Thanks for that explanation @razvanpapadopol. I wasn't aware of those. We do have other modals in Calypso that have a bigger X button, but I realize that you are using that specific component. Maybe I can suggest to improve this in Gutenberg, It does feel very small for a full screen modal.

Regarding the header with the line, could we add it to the header after the user scrolls X distance? It would make it a bit more elegant. 

Also, could we have the modal close when clicking on the "W"? We have similar behaviour in some of the onboarding screens.

2022-06-27 13:26 UTC, razvanpapadopol commented
This integration is not relevant anymore. See pdtkmj-9r-p2 for the all-new Help Center!

2022-06-27 13:26 UTC, closed without merging