Disabling monthly billing on Premium and Personal plans
Automattic/wp-calypso pull request #57255
Opened 2021-10-22 02:13 UTC by donlair

#### Changes proposed in this Pull Request

* The PR implements a test for disabling the monthly option for Premium and Personal plans on the plans page in the signup flow.
* Context for this test is available at p58i-bkW-p2.
* I'll update this PR with a link to the experiment post when it's up.

Here's a screenshot of the design provided by @lucasmdo:

<img width="1035" alt="disable-monthly-test" src="https://user-images.githubusercontent.com/35781181/138381933-6ba75f21-9ab0-49ea-ab5c-8ca1c41fc520.png">

#### Testing instructions

* Checkout this PR and start Calypso.
* Add yourself to the test variant for the Explat test named `disabled_monthly_personal_premium`.
* Navigate to the `/start/new` flow and continue to the Plans step.
* Click the Monthly tab and confirm that Personal and Premium are not selectable.
* Click back to the Annual tab and confirm that they are selectable.
* Add yourself to the control variant and confirm that it still works as expected.

Related to #

2021-10-22 05:23 UTC, southp requested changes
It looks like a great start already. :)

On the mobile version, the Personal and Premium plans are still available, with Premium being labeled as popular:
![image](https://user-images.githubusercontent.com/1842898/138397091-4b0fa779-e988-41ea-8b8d-563b5a886a6c.png)

Also, even if disabling it from the plans step, users can still update the term from the checkout page. I'm fine with skipping this for this particular experiment though, but would like to raise it :)
![image](https://user-images.githubusercontent.com/1842898/138397428-c9cce660-1dc4-4f18-8117-43f3c32e17d3.png)

2021-10-22 05:23 UTC, southp commented on client/my-sites/plan-features-comparison/header.jsx
> +		if ( disabledClasses ) return null;
Let's add braces here even if it's a one-line conditional body statement :) 
I believe the majority of calypso are still following WordPress coding standard, so that will make this more consistent with others: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#blocks-and-curly-braces. 

Braces also tend to be better for future maintenance to prevent the posterity from falling into something like Apple's infamous SSL security issue: https://blog.codecentric.de/en/2014/02/curly-braces/

2021-10-22 05:23 UTC, southp commented on client/signup/steps/plans/index.jsx
> +				disableMonthlyExperiment={ true }
This looks like the only difference between `treatmentPlanDisplay` and `defaultPlanDisplay`. Can we simply alter this flag based on the assigned variation? e.g. using `loadExperimentAssignment()` could be a way: https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/controller.js#L296 .

2021-10-22 05:23 UTC, southp commented on client/my-sites/plan-features-comparison/index.jsx
> +				} else popular = popularPlanSpec && planMatches( plan, popularPlanSpec );
The same as the above. Let's add braces here as well :)

2021-10-22 05:23 UTC, southp commented on client/my-sites/plans-features-main/index.jsx
> +			disableMonthlyExperiment = false,
A new prop should be added to `propTypes` declaration of this component as well.

2021-10-22 05:23 UTC, southp commented on client/my-sites/plan-features-comparison/index.jsx
> +			return {
This can be just `return 'plan-monthly-disabled-experiment';`. Or we can rewrite the whole function as:
```
getDisabledClasses( planName ) {
    return {
        'plan-monthly-disabled-experiment': this.props.monthlyDisabled && [ 'personal-bundle-monthly', 'value_bundle_monthly' ].includes( planName),
    }
}
```

2021-10-22 05:23 UTC, southp commented on client/my-sites/plan-features-comparison/header.jsx
> +				<div className={ classNames( 'not-available-with-monthly-disclaimer' ) }>
No need to call `classNames()` if it's a constant string :)

2021-10-25 15:51 UTC, donlair commented
Good catches, thanks @southp - this is ready for you to take another look!

2021-10-26 10:06 UTC, southp commented on client/my-sites/plan-features-comparison/index.jsx
> +		return {
Sorry that I've made a mistake when I share the snippet with you :( 
This has caused you to have to access `plan-monthly-disabled-experiment` key for every occurrence, which is not my original intent :( :(

What I missed was the `className()` call:
```
return classNames( {
    'plan-monthly-disabled-experiment':
				this.props.monthlyDisabled &&
				[ 'personal-bundle-monthly', 'value_bundle_monthly' ].includes( planName ),
		};
} );
```
That way this function will simply return the class name string or null, and the code referring to its returned value will be simpler.

2021-10-26 10:06 UTC, southp commented on client/signup/steps/domains/index.jsx
> +		loadExperimentAssignment( 'disabled_monthly_personal_premium' );
Since [loadExperimentAssignmet()](https://github.com/Automattic/wp-calypso/blob/trunk/packages/explat-client/src/create-explat-client.ts#L29) will assign a variation to eligible users, that means those flows that don't have the Plans step will also be assigned to this experiment while they are not seeing the variations. This could skew our data more or less. 

Sorry that I wasn't aware of limitation of the that my suggestion would force you to write this way.  :(  Let's remove it, and I'll share more of my thoughts in the comment below.

2021-10-26 10:06 UTC, southp commented on client/signup/steps/plans/index.jsx
> +			experiment = dangerouslyGetExperimentAssignment( 'disabled_monthly_personal_premium' );
Following up the comment about removing `loadExperimentAssignment()` above, we should keep the Explat logics within the plans step here. Since it's an async function, I'm seeing two options here:

1. Use it's `Promise`. e.g. 
```
loadExperimentAssignement( 'disabled_monthly_personal_premium' )
.then( ... )
.catch( ... )
```
2. Just revert it back to using `<Experiment>` component and see how we can dedupe the property setting code of `defaultExperience` component and `treatmentExperience` component.

What do you think?

2021-10-26 12:40 UTC, southp approved these changes

2021-10-27 02:16 UTC, southp approved these changes
Works as expected and LGTM 🚢

2021-10-27 10:03 UTC, merged