E2E: extend iframed Gutenberg editor timeout to 60000ms.
Automattic/wp-calypso pull request #57282
Opened 2021-10-22 16:38 UTC by worldomonation

#### Changes proposed in this Pull Request

This PR extends the timeout used while waiting for the iframed Gutenberg editor to load in Calypso.

Key changes:
- extend the timeout from the default value of 30000ms to 60000ms.

#### Testing instructions

- [x] stress test
  - [x] mobile https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6883054
  - [x] desktop https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/6883052
- [x] normal test
  - [x] mobile
  - [x] desktop

Fixes #57254.

2021-10-25 15:45 UTC, dpasque requested changes
Question about moving where we target this timeout!

2021-10-25 15:45 UTC, dpasque commented on packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
>  		const frame = await this.getEditorFrame();
Looking at the issue, I'm not actually sure this change will fix the issue! It timed out looking for the `editorFrame` selector, which is happens in this function call!

I think the safest thing to do would actually be to move the `page.waitForLoadState` call above this `getEditorFrame` call, and then in `getEditorFrame`, extend the timeout there to perhaps 60 seconds?

2021-10-25 16:14 UTC, worldomonation commented on packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts
>  		const frame = await this.getEditorFrame();
Interesting - the stress test passed 100 iterations of starting a new post, so I am surprised that it didn't reveal the flaw with my logic.

I've pushed a new iteration of the stress test in fefa1566c32586ce44ef4f9aebd400fdcbb49ae5.

2021-10-25 19:20 UTC, worldomonation commented
Updated links to stress test. Both `mobile` and `desktop` passed.

2021-10-26 13:45 UTC, dpasque approved these changes
🚀

2021-10-26 17:20 UTC, merged