Jetpack Pricing: Adjust layout to account for VideoPress.
Automattic/wp-calypso pull request #57362
Opened 2021-10-26 19:51 UTC by robertf4

#### Changes proposed in this Pull Request

This PR adjusts the layout of the Jetpack pricing page to account for the addition of VideoPress.

![image](https://user-images.githubusercontent.com/42627630/139122671-0461982b-6a87-454c-bff8-106b27df81ed.png)

#### Testing instructions

In Jetpack Cloud:
1. Visit `jetpack.cloud.localhost:3001/pricing?flags=jetpack/only-realtime-products` and view the page at varying widths, verifying that the layout adjusts appropriately.
2. Visit `jetpack.cloud.localhost:3001/pricing`, verifying that the pricing page has not changed.

In Calypso:
1. Visit `calypso.localhost:3000/plans/:site?flags=jetpack/only-realtime-products` and view the page at varying widths, verifying that the layout adjusts appropriately.
2. Visit `http://calypso.localhost:3000/plans/agreeable-nurse.jurassic.ninja`, and verify that the pricing page has not changed.

Related to #1200412004370260-as-1201245515881797

2021-10-28 14:42 UTC, monsieur-z requested changes
Looks good when the flag is set. However, the regression testing showed that the "More products" header is now missing.
![screenshot](https://user-images.githubusercontent.com/1620183/139279464-202b3d62-cef1-457c-8be9-6af4d567004c.png)

2021-10-28 14:44 UTC, monsieur-z commented on client/my-sites/plans/jetpack-plans/product-grid/index.tsx
> +			return (
I believe the lack of a `key` attribute for the elements in these 2 returns is raising a React warning.

2021-10-28 17:16 UTC, mattgawarecki commented
I'm noticing some discrepancies in the page from @jeffgolenski's design mocks. Can we get those call-to-action buttons aligned and both using a green background color, with the "Start for Free" displayed in the area we use for prices?

(Note: Marketing requests that we keep the wording as "Start for free" instead of "Starting at Free")

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/670067/139303845-5d9f9b58-978e-4a91-978c-366573e15db9.png">

2021-10-28 17:25 UTC, mattgawarecki commented
> I'm noticing some discrepancies in the page from @jeffgolenski's design mocks.

Ah -- I see now that we have a separate task for these appearance changes, `1200412004370260-as-1201272180272104`. Feel free to disregard for now.

2021-10-29 18:06 UTC, robertf4 commented on client/my-sites/plans/jetpack-plans/product-grid/index.tsx
> +			return (
Good catch, fixed.

2021-10-29 18:07 UTC, robertf4 commented
> the regression testing showed that the "More products" header is now missing

@monsieur-z good catch, I have fixed this.

2021-11-01 13:39 UTC, monsieur-z approved these changes
Looking good now, but the regression testing is hard to do since the copy was recently updated across the page. I can take another look at it after you do a rebase, if you'd like.

2021-11-01 15:28 UTC, jeffgolenski approved these changes
Structure looks good! Thanks for the quick turnaround. I'll await the next PR that addresses the content within the CRM card. Thanks @robertf4 !

2021-11-01 15:30 UTC, monsieur-z commented
Confirming that after the rebase, the page looks good with the changes. The regression testing confirmed that the page looked as in production as well in that instance.

Definitely something that can be addressed later: the spacing above the features list in the VideoPress card on desktop looks a bit off:
![screenshot](https://user-images.githubusercontent.com/1620183/139697402-088bfbda-baed-426b-9cbf-ad328f02d755.png)

2021-11-01 15:33 UTC, merged