`QueryUserPurchases`: refactor away from `UNSAFE_*`
Automattic/wp-calypso pull request #57382
Opened 2021-10-27 08:34 UTC by flootr

#### Changes proposed in this Pull Request

* `QueryUserPurchases`: refactor away from `UNSAFE_*`

#### Testing instructions

* Go to `/me/purchases` and verify you see a request to `/me/purchases`
* Navigate away and go back, there shouldn't be another request (there may be other `/sites/<siteId>/purchases` requests though)

`QueryUserPurchases` is used in a bunch of other places, too, e.g. on `/home/<siteSlug>`. Behaviour should generally be the same as described above.

2021-10-27 08:50 UTC, jsnajdr approved these changes
:+1:

2021-10-27 08:50 UTC, jsnajdr commented on client/components/data/query-user-purchases/index.jsx
> +	if ( userId && ! isFetching && ! hasLoaded ) {
The `userId` is always the `getCurrentUserId( state )`. The selector could be called inside the query component and the query component could be rendered without props, as `<QueryUserPurchases />`. That would remove a lot of repetitive code from the usage places.

2021-10-27 08:55 UTC, flootr commented on client/components/data/query-user-purchases/index.jsx
> +	if ( userId && ! isFetching && ! hasLoaded ) {
Totally agree! Let me add another commit, would like to include that change in this PR 👍🏻

2021-10-27 10:51 UTC, tyxla approved these changes
LGTM, just have 1 question.

2021-10-27 10:51 UTC, tyxla commented on client/components/data/query-user-purchases/index.jsx
> +	const isFetching = isFetchingUserPurchases( getState() );
Theoretically whether we'll make a new request relies on these 2 selectors, but since they're not dependencies of the `useEffect` call below, the request might or might not happen if their returned values change. Is that expected behavior?

2021-10-27 11:35 UTC, jsnajdr commented on client/components/data/query-user-purchases/index.jsx
> +	const isFetching = isFetchingUserPurchases( getState() );
That's a good question, the behavior really seems to be changing. The new version with hooks will do any request only on mount, given the request is not already pending or done. But will never do any request on update. After the `PURCHASES_REMOVE` action is dispatched and the list is cleared, the old version would refetch the list immediately, but the new one won't. That's done after cancelling a purchase or after changing a payment method.

To get the original behavior, we should run the `useEffect` without any dependencies, to run after each render. Most of the time it should very quickly select from Redux and decide to do nothing.

2021-10-27 12:43 UTC, flootr commented on client/components/data/query-user-purchases/index.jsx
> +	const isFetching = isFetchingUserPurchases( getState() );
Great catch @tyxla 👍🏻 fixed in https://github.com/Automattic/wp-calypso/pull/57382/commits/54770b640830df411c56b0bcbdc3d3c5c6b95a48

2021-10-27 13:13 UTC, flootr commented on client/components/data/query-user-purchases/index.jsx
> +	if ( userId && ! isFetching && ! hasLoaded ) {
@jsnajdr I added https://github.com/Automattic/wp-calypso/pull/57382/commits/1d1a5c88e87db05dfdf683a5e865ce3be02499d5, let me know what you think.

2021-10-27 13:55 UTC, jsnajdr approved these changes
Looks good :+1:

2021-10-27 13:55 UTC, jsnajdr commented on client/me/account-close/main.jsx
> -			currentUserId: user && user.ID,
In this component, I don't see the `user` prop being used. Seems we can stop passing it, and call only `getCurrentUserId`.

2021-10-27 13:55 UTC, jsnajdr commented on client/my-sites/marketing/tools/index.tsx
> +			{ ! purchases && <QueryUserPurchases /> }
This could be an unconditional `<QueryUserPurchases />`. The component does all the necessary checks internally.

2021-10-27 13:55 UTC, jsnajdr commented on client/my-sites/marketing/ultimate-traffic-guide/index.js
> +			{ ! purchases && <QueryUserPurchases /> }
Can be unconditional, too.

2021-10-28 07:36 UTC, tyxla requested changes
Thanks for taking this so far 👍  Makes a lot more sense without all the extra checks.

We seem to be removing a selector that's still in use.

The rest is nits and optional suggestions.

2021-10-28 07:36 UTC, tyxla commented on client/components/data/query-user-purchases/README.md
> +`<QueryUserPurchases />` is a React component used in managing network requests purchases of the current user.
Should we also rename the query component now? I think it makes sense to be called `QueryCurrentUserPurchases`. Might be longer, but it makes sense to additionally clarify by name because we also have `QuerySitePurchases`.

2021-10-28 07:36 UTC, tyxla commented on client/me/purchases/manage-purchase/change-payment-method/index.tsx
> -import { getCurrentUserId, getCurrentUserLocale } from 'calypso/state/current-user/selectors';
Seems like `getCurrentUserLocale` is still in use?

2021-10-28 07:36 UTC, tyxla commented on client/my-sites/domains/domain-management/list/list-all.jsx
> -			user,
Let's also remove the related `PropType`.

2021-10-28 08:13 UTC, jsnajdr commented on client/components/data/query-user-purchases/README.md
> +`<QueryUserPurchases />` is a React component used in managing network requests purchases of the current user.
I don't know, I like shorter names and don't find the "user" vs "current user" distinction very confusing. The domain model of Calypso is that there is one logged-in user with many sites, so it's quite clear what "user" refers to and it's the sites that need to be clarified: "current site" or a "site" with ID?

We also have `QueryUserDevices`, `QueryUserSettings`, `QueryUserConnection` and they all query something about the current user, mostly through some `/me/*` endpoint.

2021-10-28 08:13 UTC, jsnajdr commented on client/me/purchases/manage-purchase/change-payment-method/index.tsx
> -import { getCurrentUserId, getCurrentUserLocale } from 'calypso/state/current-user/selectors';
Fixed in c12dfb6.

2021-10-28 08:14 UTC, jsnajdr commented on client/my-sites/domains/domain-management/list/list-all.jsx
> -			user,
Fixed in c12dfb6.

2021-10-28 09:12 UTC, tyxla commented on client/components/data/query-user-purchases/README.md
> +`<QueryUserPurchases />` is a React component used in managing network requests purchases of the current user.
I like your rationale here. It's definitely not a precedent throughout Calypso, so let's keep it as it is.

2021-10-28 09:13 UTC, tyxla approved these changes
This tests well and the code looks great. Thanks! 🚢

2021-10-28 09:15 UTC, merged