Migrate updateSiteFrontPage to a thunk
Automattic/wp-calypso pull request #57425
Opened 2021-10-28 11:35 UTC by jsnajdr

Migrates the `updateSiteFrontPage` action to a thunk, for two reasons:
- it's part of the `state/sites` state, which is used also in widget apps like Inline Help, and it's the only action there that requires the data layer to be present
- the entrypoint bundle size should be slightly smaller

2021-10-28 13:21 UTC, tyxla requested changes
Thanks for tackling this one 🙌 

I'm getting an error when trying to set the front page for a page in `/pages/:site`:

![](https://cldup.com/3EmdlAD_bt.png)

I assume it's because if of the way we're passing `dispatch` as an argument.

I've also left some questions.

2021-10-28 13:21 UTC, tyxla commented on client/state/sites/actions.js
> +		.catch( () => {} );
In case of an error, should we revert to the previous settings locally?

2021-10-28 13:21 UTC, tyxla commented on client/state/sites/actions.js
> +function isPageOnFront( show_on_front ) {
I see this resembles the option name, however I don't see a good reason to disobey our coding standards with regards to variable naming. Perhaps we could rename it to `showOnFront`?

2021-10-28 13:21 UTC, tyxla commented on client/state/sites/actions.js
> +	dispatch( { type: SITE_FRONT_PAGE_UPDATE, siteId, frontPageOptions } );
Do we really need the optimistic update here? I don't see it in the previous version?

2021-10-28 13:21 UTC, tyxla commented on client/state/sites/actions.js
> +export const updateSiteFrontPage = ( siteId, frontPageOptions ) => ( { dispatch } ) => {
I assume you meant:

```suggestion
export const updateSiteFrontPage = ( siteId, frontPageOptions ) => ( dispatch ) => {
```

2021-10-28 14:01 UTC, jsnajdr commented on client/state/sites/actions.js
> +export const updateSiteFrontPage = ( siteId, frontPageOptions ) => ( { dispatch } ) => {
Oh yes, silly typo and sloppy testing on my side 🙁 Fixed.

2021-10-28 14:04 UTC, jsnajdr commented on client/state/sites/actions.js
> +	dispatch( { type: SITE_FRONT_PAGE_UPDATE, siteId, frontPageOptions } );
There was an optimistic update in the data layer version. The `SITE_FRONT_PAGE_UPDATE` does hit the reducer, updating the state, and at the same time triggers a REST request because the action type has a data layer handler registered. Then, when response arrives, we dispatch `SITE_FRONT_PAGE_UPDATE` again, with `dispatch( bypassDataLayer( updateSiteFrontPage() ) )`. This time we only hit the reducer, and avoid triggering a request again.

2021-10-28 14:05 UTC, jsnajdr commented on client/state/sites/actions.js
> +function isPageOnFront( show_on_front ) {
Renamed in 276b014783.

2021-10-28 14:05 UTC, jsnajdr commented on client/state/sites/actions.js
> +	dispatch( { type: SITE_FRONT_PAGE_UPDATE, siteId, frontPageOptions } );
In any case, I don't think we really need the optimistic update. I'll take a closer look at that.

2021-10-28 14:06 UTC, jsnajdr commented on client/state/sites/actions.js
> +		.catch( () => {} );
If we keep the optimistic update, then yes, we should revert when the optimism turns out to be unwarranted.

2021-10-29 09:49 UTC, jsnajdr commented on client/state/sites/actions.js
> +	dispatch( { type: SITE_FRONT_PAGE_UPDATE, siteId, frontPageOptions } );
@tyxla I tested all the places where this is used -- pages list and iframed editor with `?new-homepage` -- and decided to remove the optimistic update. Doing the simple `request().then(receiveResponse)` is sufficient.

In the Pages list, there is now a little delay between clicking "Set as Homepage" and the "Homepage" label appearing, and that's all. Ready for a final review.

2021-10-29 10:24 UTC, tyxla commented on client/state/sites/actions.js
> +	dispatch( { type: SITE_FRONT_PAGE_UPDATE, siteId, frontPageOptions } );
I agree with removing the optimistic update 👍  Thanks!

2021-10-29 10:27 UTC, tyxla approved these changes
LGTM, thank you 🚢

2021-10-29 10:29 UTC, merged