Disabled Spellcheck for usernames during account closure
Automattic/wp-calypso pull request #57465
Opened 2021-10-29 05:09 UTC by spraveenitpro

#### Changes proposed in this Pull Request

Disable Spelling check on username when entered during the final step of Account closure in safari 14.1.2:

![](https://d.pr/i/5i2f0c+)
[Direct Link](https://d.pr/i/5i2f0c+)

#### Testing instructions

1. Goto [this page](https://wordpress.com/me/account/close) for closing account and in the final step enter the username for confirmation in safari 14.1.2
2. You will notice that safari autocorrects the username for spelling
3. I have disabled the spellcheck [like this](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) for the `FormTextInput` component

Related to #55563
Request review from @tyxla

2021-10-29 11:18 UTC, tyxla requested changes
Thanks for working on this! I think it needs some polishing - I've left a comment.

2021-10-29 11:18 UTC, tyxla commented on client/me/account-close/confirm-dialog.jsx
> +							spellcheck="false"
`spellcheck` is not a valid React prop according to the [React docs](https://reactjs.org/docs/dom-elements.html#html-attributes).

If you're looking at the browser console, you'll also see a warning:

![](https://cldup.com/FhqwbobPjS.png)

2021-10-29 18:11 UTC, spraveenitpro commented on client/me/account-close/confirm-dialog.jsx
> +							spellcheck="false"
Not sure what I was thinking, Just fixed this with[ this example](https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/packages/components/src/suggestions/docs/example.jsx). I have checked the console also. Thanks for your infinite patience. 🙌🏽

2021-11-01 11:04 UTC, tyxla approved these changes
LGTM 👍  Thanks for also fixing the error in the prop value type (`"false"` -> `false`).

I'm going to ship this one for you.

2021-11-01 11:15 UTC, merged

2021-11-02 12:47 UTC, spraveenitpro commented
Thank you @tyxla I have to write a post with all your suggestions to sum them up, Let me finish the other one too. 🙌🏽

2021-11-02 12:52 UTC, tyxla commented
> write a post with all your suggestions to sum them up

Sounds awesome, looking forward to reading that one 😍  Thanks!