Plans: Update styling for Jetpack CRM card to match other product cards
Automattic/wp-calypso pull request #57553
Opened 2021-11-02 15:16 UTC by mattgawarecki

Resolves `1200412004370260-as-1201272180272104`.
Relates to #57362.

#### Changes proposed in this Pull Request

* Split the `JetpackCrmFreeCard` component into two versions: one with, and one without, the price display.
* Add styling rules for the new displayed-price version of the CRM Free card to match other product cards.
* Add support for easier custom styling on the `JetpackProductCard` component.
* Add a property for `abovePriceText` on the `JetpackProductCard` component.
* Add support for the `hideSavingLabel` prop on free product price displays.

#### Testing instructions

***NOTE:** Please test this PR in both Calypso Blue and Calypso Green, for both wide and narrow screen layouts.*

1. Visit the pricing page in any non-production environment.
2. Verify the product grid still renders correctly and flows naturally as the screen resizes.
3. Verify the Jetpack CRM Free card still shows up to the right of the VideoPress product card, and that its styles match the other product cards.
4. Verify the Jetpack CRM Free card's price display and copy are aligned appropriately compared to other product cards.

#### Reference screenshots

<img height="250" alt="Screen Shot 2021-11-01 at 15 02 55" src="https://user-images.githubusercontent.com/670067/139875298-28084619-e210-403e-883c-7e10e480e5d7.png"> <img height="250" alt="Screen Shot 2021-11-01 at 15 03 12" src="https://user-images.githubusercontent.com/670067/139875300-3024acc7-7f5c-4b5d-9dc8-266895a2c6e3.png">

<img height="250" alt="Screen Shot 2021-11-01 at 15 10 43" src="https://user-images.githubusercontent.com/670067/139875307-fb441ba3-680e-4322-96f1-fcc3cb2840ac.png"> <img height="250" alt="Screen Shot 2021-11-01 at 15 03 31" src="https://user-images.githubusercontent.com/670067/139875303-f3d68ef8-4be6-4809-91bd-75643a3648b4.png">

2021-11-03 12:43 UTC, monsieur-z requested changes
Card and code look good.

As for the grid, the Jetpack Free card doesn't take the full height at medium size viewport:
<img width="842" alt="Screen Shot 2021-11-03 at 8 36 30 AM" src="https://user-images.githubusercontent.com/1620183/140061857-b4fa948f-a742-4cef-aea5-ad6416f47322.png">

2021-11-03 15:29 UTC, mattgawarecki commented
As for the grid, the Jetpack Free card doesn't take the full height at medium size viewport: <img alt="Screen Shot 2021-11-03 at 8 36 30 AM" width="842" src="https://user-images.githubusercontent.com/1620183/140061857-b4fa948f-a742-4cef-aea5-ad6416f47322.png">

@jeffgolenski I wonder what we can do to address this so that the Free card doesn't look wonky next to other cards. I tried stretching the card out vertically in the screenshot below, but as you can see, the buttons don't line up. Should Free also have a "Start for Free" price display to match CRM Free?

<img width="837" alt="image" src="https://user-images.githubusercontent.com/670067/140091268-878e1274-bcfa-4103-9338-37f9918a1838.png">

2021-11-04 13:09 UTC, monsieur-z requested changes
It now looks good on medium viewport, but the Free card is not arranged in 2 columns on wider screens anymore.
<img width="1064" alt="Screen Shot 2021-11-04 at 9 08 29 AM" src="https://user-images.githubusercontent.com/1620183/140318932-0737b488-9633-4b24-b7b1-6600f9810a39.png">

2021-11-04 17:39 UTC, jeffgolenski commented
@mattgawarecki Here's a really quick mock. During that middle breakpoint when the 2 columns looks like this...

![Screen Shot 2021-11-04 at 1 20 59 PM](https://user-images.githubusercontent.com/214813/140390813-53a7ec26-e8fe-4485-8e81-6cc8e921b9cd.png)

Can you make CRM and Jetpack Free both span 100% and stack like this? (keep all the same styles that currently exist, just change the structure)

![Screen Shot 2021-11-04 at 1 37 28 PM](https://user-images.githubusercontent.com/214813/140390872-5a80d296-b0a5-424d-bfe2-e5c045625079.png)

When the small mobile breakpoint kicks in, we'll keep it exactly as you have it now.

2021-11-05 19:16 UTC, mattgawarecki commented
@jeffgolenski Okie dokie, it took a hot minute but I think I've got it! I updated the PR so you can see the changes live as well, but here are some screenshots:

#### Calypso Green

<img height="250" alt="Screen Shot 2021-11-05 at 13 30 51" src="https://user-images.githubusercontent.com/670067/140565798-81460650-a99e-4d18-b301-eddf1522b993.png"> <img height="250" alt="Screen Shot 2021-11-05 at 13 30 33" src="https://user-images.githubusercontent.com/670067/140565796-e5a17aa7-b175-420c-b9f3-c1c3e70b917f.png"> <img height="250" alt="Screen Shot 2021-11-05 at 13 30 09" src="https://user-images.githubusercontent.com/670067/140565795-48722d4b-5c16-45dd-a5b3-7e81db81f1ea.png">

#### Calypso Blue

<img height="185" alt="Screen Shot 2021-11-05 at 13 35 40" src="https://user-images.githubusercontent.com/670067/140565800-d315b0f8-dcc7-4f0e-a370-c62034ffc83d.png"> <img height="185" alt="Screen Shot 2021-11-05 at 13 35 25" src="https://user-images.githubusercontent.com/670067/140565799-c119204c-1338-4607-85eb-99abce2fc247.png">

2021-11-05 20:23 UTC, jeffgolenski commented
@mattgawarecki Just gave it a go! Looks good on every viewport! Ship it!

2021-11-08 14:50 UTC, jeffgolenski approved these changes

2021-11-08 15:20 UTC, monsieur-z approved these changes
LGTM!

2021-11-08 15:47 UTC, merged

2021-11-08 16:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6950343

Thank you @mattgawarecki for including a screenshot in the description! This is really helpful for our translators.

2021-11-19 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6950343).