Emails: Remove ToS warning in domain management list
Automattic/wp-calypso pull request #57767
Opened 2021-11-08 16:31 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

It removes the pending ToS warning in the domains management screen

#### Testing instructions

Have a site with Google Workspace subscription where you have not accepted the ToS (buy, log in, don't click on accept ToS)

You should not see any warning above the domain lists:
![image](https://user-images.githubusercontent.com/5689927/140780191-f05d03bf-bd2c-4203-9c79-3e618efd745a.png)

For reference:
![image](https://user-images.githubusercontent.com/5689927/140780560-4a1a2b7d-0ba1-4acb-9e19-eed5a7d21427.png)

Extra test:
If you have several domains at the same time with not accepted ToS you should not see either any message.

Related to 1200182182542585-as-1201257638729675

2021-11-09 16:32 UTC, stephanethomas requested changes
I've spotted a regression during testing, that we should address.

2021-11-09 16:32 UTC, stephanethomas commented on client/my-sites/domains/components/domain-warnings/index.jsx
> -			'pendingGSuiteTosAcceptanceDomains',
There are two places where we need to remove that rule (an [example](https://github.com/Automattic/wp-calypso/blob/fc1c2034600e49a8dbe0172d9894adac6b766a4b/client/my-sites/domains/domain-management/list/index.jsx#L93)).

2021-11-09 16:32 UTC, stephanethomas commented on client/my-sites/domains/components/domain-warnings/index.jsx
> -			/>
I'm afraid that removing all this code leads to a regression - the `PendingGSuiteTosNotice` component is indeed responsible for rendering the notice in the sidebar when `isCompact` set to `true` (and the idea is to keep it):

![image](https://user-images.githubusercontent.com/594356/140963938-7aa5a87c-53aa-4b23-aa93-f05a698e41ef.png)

I'm not sure if that would be the best approach but maybe we could extract [that code](https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/my-sites/domains/components/domain-warnings/pending-gsuite-tos-notice.jsx#L85-L106) here?

2021-11-12 13:59 UTC, olaseni requested changes

2021-11-12 13:59 UTC, olaseni commented on client/my-sites/domains/components/domain-warnings/index.jsx
> +		if ( domains.length === 0 || ! this.props.isCompact ) {
This isn't the best place to limit rendering on the domain mgmt list. This is rather central.

It seems to me that it's better to limit rendering at the places where the component is called, like [here for instance](https://github.com/Automattic/wp-calypso/blob/fc1c2034600e49a8dbe0172d9894adac6b766a4b/client/my-sites/domains/domain-management/list/index.jsx#L93)

2021-11-15 14:39 UTC, daledupreez requested changes
I think we're approaching this incorrectly. The issue we're trying to address is that there are two kinds of G Suite ToS notices:
* One displayed when none of the admin users for the subscription have accepted the subscription-level ToS
* One displayed when one or more users haven't logged in and accepted their user-level ToS

We are only trying to hide warnings for the second case, as we're not getting reliable data from Google. As a result, I think we need to update the component _and_ some callers to avoid showing warnings for the case where `hasPendingGSuiteUsers( domain )` is true -- we only want warnings when `isPendingGSuiteTOSAcceptance( domain )` is true.

2021-11-17 10:45 UTC, AllTerrainDeveloper commented
> hasPendingGSuiteUsers

Thank you for the great explanation

2021-11-17 10:45 UTC, AllTerrainDeveloper commented
> I think we're approaching this incorrectly. The issue we're trying to address is that there are two kinds of G Suite ToS notices:
> 
> * One displayed when none of the admin users for the subscription have accepted the subscription-level ToS
> * One displayed when one or more users haven't logged in and accepted their user-level ToS
> 
> We are only trying to hide warnings for the second case, as we're not getting reliable data from Google. As a result, I think we need to update the component _and_ some callers to avoid showing warnings for the case where `hasPendingGSuiteUsers( domain )` is true -- we only want warnings when `isPendingGSuiteTOSAcceptance( domain )` is true.

Thank you for the great explanation

2021-11-19 07:43 UTC, daledupreez approved these changes
LGTM! I tested with a suspended domain that had multiple pending users. The domain was removed from the list after accepting the ToS for one user, though there were still other pending users.

I think we also need to remove the warnings for pending users in the email management pages, but that can be handled in a follow-up PR.

2021-11-19 07:50 UTC, daledupreez commented
As a side note, I think it may be worth clarifying the intent of this PR, as we're not removing all warnings for Google.

We are specifically removing the warning when one or more mailbox-level ToS have not been accepted. We will continue to show a warning when the subscription-level (or account-level) ToS have not been accepted.

2021-11-25 10:42 UTC, merged