Emails: Remove warning for user level ToS acceptance from email management header
Automattic/wp-calypso pull request #58284
Opened 2021-11-19 13:33 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

We are showing a user level warning at a "Account level". This means that in the email management header we are showing a warning that should be only displayed at user/mailbox level.

#### Testing instructions

- Buy a Google Workspace subscription
- Accept ToS
- Create a new mailbox

Expected:
![image](https://user-images.githubusercontent.com/5689927/142629639-34e7390d-f557-4bfb-838a-7ee52cc296bc.png)

Actual:
![image](https://user-images.githubusercontent.com/5689927/142630923-c64d2872-1c11-4625-9467-f4525a263afe.png)

Related to {1200182182542585-as-1201399344994999}

2021-11-22 12:30 UTC, daledupreez requested changes

2021-11-22 12:30 UTC, daledupreez commented on client/my-sites/email/email-management/home/email-plan-header.jsx
> +					) }
I think this is the wrong approach -- I think we need to update `resolveEmailPlanStatus()` to remove the logic in that function which returns an error when `hasPendingGSuiteUsers( domain )` is true.

2021-11-22 17:25 UTC, AllTerrainDeveloper commented
Thank you Dale ❤️

2021-11-23 08:03 UTC, daledupreez approved these changes
I've tested and this part of the patch is working as expected: I didn't see a warning on the email home/listing page or the domain-specific email management page, even though I confirmed that the domain had pending users.

However, there is still a gap that we need to address: we're still showing a mailbox-level warning, despite the fact that the data we're using to identify this state is often inaccurate. That can be handled in a follow-up PR, however.

2021-11-25 10:54 UTC, merged