Domains: Add advanced transfer options card
Automattic/wp-calypso pull request #58426
Opened 2021-11-23 20:11 UTC by leonardost

### Changes proposed in this Pull Request

WIP

This is part of the domain management redesign project described in pcYYhz-m2-p2.

### Testing instructions

TBA

2021-11-24 20:06 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
> +		const disabledLockLabel = __( 'Transfer lock off' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Transfer lock: off' )` *ES Score: 12*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/advanced-transfer-options-component)

2021-11-24 20:06 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
> +		const enabledLockLabel = __( 'Transfer lock on' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Transfer lock: on' )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/advanced-transfer-options-component)

2021-11-24 20:06 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx
> +					{ __( 'Get authorization code' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **14** times:
`translate( 'Get domain authorization code' )` *ES Score: 7*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/advanced-transfer-options-component)

2021-12-01 20:02 UTC, hambai requested changes
I believe we can simplify this PR and not keep all those new actions, action creators and reducers in the global state. We should be able to just use local component state for `isRequestingTransferCode` and `isLockingOrUnlockingDomain`. I also think that we can safely assume that if we got a success from the api endpoint we can just update the global state for the domain lock status and not make additional api call to get the updated status?

2021-12-02 19:42 UTC, leonardost commented
Thanks for the review @hambai! You're definitely right, not everything needs to be in redux or in the global state. I started from the existing code and didn't even think about doing things more simply, so thanks for the discussion yesterday 🙇 

Now there's only one action to update the lock status of the domain when the API call is successful, so there's a lot less boilerplate 🙂 would love if you could take another look at this.

2021-12-07 06:06 UTC, rafaelgalani reviewed
Nice job! I tested and all the visual changes were reflected, and the authorization code button also worked as expected. LGTM.

But there was a single point where I have noticed something weird:

![image](https://user-images.githubusercontent.com/18705930/144974915-89539c55-33f8-4a5f-b7f3-576846d401f8.png)

I wasn't able to turn off the transfer lock for my domain. 
I believe that's _probably_ because I marked the 60-day transfer lock when I previously updated (a few days ago) the domain's contact info. There's also the transfer's card message confirming it:

![image](https://user-images.githubusercontent.com/18705930/144975205-f7b3c600-2da6-4e7d-ba87-93925eea7525.png)

I think it might be a good idea to disable the button when the domain is in this state, otherwise, it might get some users confused.

2021-12-07 12:46 UTC, leonardost commented
Thanks for the review @rafaelgalani and nice catch! I'll add a check for the 60-day transfer lock 👍

2021-12-08 18:51 UTC, merged

2021-12-08 19:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7030084

Thank you @leonardost for including a screenshot in the description! This is really helpful for our translators.

2021-12-17 13:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7030084).