Updating styles to make sure that the free plan link is white instead of gray
Automattic/wp-calypso pull request #58883
Opened 2021-12-07 01:40 UTC by chickee0311

#### Changes proposed in this Pull Request

The link to the free plan shows on the blue plans grid is displaying in gray instead of white, making it hard to read. These changes update styling to address this issue. See: https://github.com/Automattic/wp-calypso/issues/58806

#### Testing instructions

- Start at https://wordpress.com/start/import/from-url?ref=compare%2Fwix-lp
- Add in the URL https://mikael393.wixsite.com/website-8 or other sample site
- Pick any free domain
- See the plans grid & free link on top
- Ensure that link to free plan is white

- Visit https://wordpress.com/start/plans 
- Ensure that there has been no change to the free plan link 
<img width="836" alt="Screen Shot 2021-12-08 at 10 38 41 AM" src="https://user-images.githubusercontent.com/48809176/145256838-7425602f-1637-425d-acff-a3f1e001c7d4.png">

#### Related to #58806

2021-12-07 05:20 UTC, jdc91 requested changes
Hey @chickee0311 I couldn't see the fix when dev testing this on calypso live 🤔 
I think the issue is a small typo in the class name.

2021-12-07 05:20 UTC, jdc91 commented on client/signup/steps/plans/style.scss
> +		.formatted-header__subtitle .button.is.borderless {
I think the classes `is.borderless` should be changed as `is-borderless`

2021-12-08 07:09 UTC, aneeshd16 commented
Thanks for this change! This may also affect the existing plans page (https://wordpress.com/start/plans). It'll be great if we can add that to the testing instructions. 🙂

2021-12-14 21:36 UTC, chickee0311 commented
Closing this as this was recently fixed in addressing other signup flows

2021-12-14 21:36 UTC, closed without merging