Domains: Create redesigned domain settings page sidebar
Automattic/wp-calypso pull request #59092
Opened 2021-12-11 01:37 UTC by rafaelgalani

#### Changes proposed in this Pull Request
Adds the sidebar elements to the new domain settings page. 
This is part of the domain management redesign project described in pcYYhz-m2-p2.

#### Preview
<img width="420" src="https://user-images.githubusercontent.com/18705930/145658879-a48c7b35-d93d-4deb-8179-d12f76a5d1a1.png" />
<img width="420" src="https://user-images.githubusercontent.com/18705930/145658883-52f3efc5-e955-4ed4-8962-10b8c6bd0a58.png" />
<img width="420" src="https://user-images.githubusercontent.com/18705930/145658890-0af8b6c1-2af9-41a4-8c0b-476444b54e91.png" />
<img width="420" src="https://user-images.githubusercontent.com/18705930/145658899-d8e0a7f1-b7f8-4ef4-9ebc-c430734f9440.png" />
<img width="420" src="https://user-images.githubusercontent.com/18705930/145658955-3396e5de-845d-41c2-aa5e-c1d4debe8780.png" />

#### Testing instructions

- Build this branch locally or open the live Calypso link
- Go to "Upgrades > Domains"
- Select one of your registered domains or domain connections
- If you're in the live Calypso link, please append `?flags=domains/settings-page-redesign` to your URL to enable the appropriate feature flag
- Please check that:
  - The sidebar is shown as in the screenshots and as described in the redesign (hlVh2q24ad6MCwlwNnE9PQ-fi-600%3A53742)
  - Email count works as expected;
  - All buttons redirect to the correct page;
  - Transfer card is not rendered if the domain is a transfer;
  - Delete/cancel button is not rendered if the purchase is not removable (_follows the same logic as in the [`RemovePurchase`](https://github.com/Automattic/wp-calypso/commit/3cb00c240c54273de0c372daa7afe3dff7ab946c) component_);
  - The cards' labels change according to the domain type: connection, transfer, etc);
  - Mobile view looks correct as shown in the screenshot above;
  - No other elements have been affected by the changes, and also make sure that the page without the feature flag looks the same as before.

2021-12-11 01:41 UTC, a8ci18n commented on client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx
> +									{ translate( 'Delete this domain' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **25** times:
`translate( 'Delete this Domain' )` *ES Score: 8*

2021-12-11 01:41 UTC, a8ci18n commented on client/my-sites/domains/domain-management/components/domain/domain-info-card/email/index.tsx
> +			ctaText={ translate( 'Add professional email' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'Add Professional Email' )` *ES Score: 9*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/feature/update-domain-management-columns)

2021-12-11 02:01 UTC, rafaelgalani commented
☝🏻 Rebase on `trunk`

2021-12-13 17:26 UTC, rafaelgalani commented
☝🏻 Rebase on `trunk` - and one little improvement 😄

2021-12-13 18:18 UTC, leonardost requested changes
Tested and LGTM, nice job! I've left some minor comments in the code. The only other thing I noticed is that for domains being transferred, the email card shouldn't be shown and the option to cancel the transfer is missing:

Current page:
<img width="983" alt="Screen Shot 2021-12-13 at 15 15 32" src="https://user-images.githubusercontent.com/5324818/145866474-bb775250-cd49-47fb-9f27-187ca2106205.png">

Design document:
<img width="1201" alt="Screen Shot 2021-12-13 at 15 16 04" src="https://user-images.githubusercontent.com/5324818/145866517-3957f6f3-45a4-42c5-a56c-c88a286e0874.png">

That can be addressed in a later PR too if you prefer 🙂

2021-12-13 18:18 UTC, leonardost commented on client/my-sites/domains/domain-management/components/domain/domain-info-card/index.tsx
> +export default DomainInfoCard;
Nice generic component, I like it 🙂

2021-12-13 18:18 UTC, leonardost commented on client/my-sites/domains/domain-management/components/domain/domain-info-card/delete/index.tsx
> +	if ( ! isLoadingPurchase && ! purchase ) return null;
I'm thinking about this condition - shouldn't it be `isLoadingPurchase || ! purchase`? Because the reverse condition to show the card would be `! isLoadingPurchase && purchase`, is that correct?

2021-12-13 18:18 UTC, leonardost commented on client/my-sites/domains/domain-management/components/domain/domain-info-card/delete/index.tsx
> +	if ( ! isLoadingPurchase && ! purchase ) return null;
Otherwise, if `isLoadingPurchase` is `true`, this card would be shown, is that right?

2021-12-13 19:20 UTC, rafaelgalani commented on client/my-sites/domains/domain-management/components/domain/domain-info-card/delete/index.tsx
> +	if ( ! isLoadingPurchase && ! purchase ) return null;
You're right, my bad. I meant to use `isLoadingPurchase || ! purchase`. Thanks!

2021-12-14 13:52 UTC, leonardost approved these changes
Thanks for the updates, tested again and LGTM! 💯 

I noticed that if I reload while in the domain settings page (as opposed to accessing the page via the domains list) sometimes the delete card isn't loaded:

![Markup on 2021-12-14 at 10:45:12](https://user-images.githubusercontent.com/5324818/146010330-48ff978f-2ee1-4a51-a95b-428c890fe24e.png)

That's probably due to the `purchase` not being loaded in that case. I'll fix that in the PR I'm working on right now (#59180), so don't worry about that 👍

2021-12-14 16:58 UTC, rafaelgalani commented
> Thanks for the updates, tested again and LGTM! 💯
> 
> I noticed that if I reload while in the domain settings page (as opposed to accessing the page via the domains list) sometimes the delete card isn't loaded:
> 
> ![Markup on 2021-12-14 at 10:45:12](https://user-images.githubusercontent.com/5324818/146010330-48ff978f-2ee1-4a51-a95b-428c890fe24e.png)
> 
> That's probably due to the `purchase` not being loaded in that case. I'll fix that in the PR I'm working on right now (#59180), so don't worry about that 👍

@leonardost Alright, I'll pin that - just in case it's something we need to work in the future.

2021-12-14 17:04 UTC, merged

2021-12-14 18:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7041209

Thank you @rafaelgalani for including a screenshot in the description! This is really helpful for our translators.

2021-12-28 15:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7041209).