Import onboarding: show getting started video while import is in progress
Automattic/wp-calypso pull request #59122
Opened 2021-12-13 14:40 UTC by bogiii

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2021-12-14 06:08 UTC, vishnugopal requested changes
I feel there is one obvious problem here. If the site has a previously successful import, the page redirects to Hooray without starting any new imports.

https://cln.sh/yyXwZL

Note that the HTTP request references a previous import:

```
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"importId":"61b72a77188fd","siteId":200173241,"type":"wix","importStatus":"importSuccess","customData":{"sourceAuthors":[{"login":"admin","name":"Site Admin"}],"title":"Free Website Builder | Create a Free Website | Wix.com"},"progress":{"post":{"completed":0,"total":0},"page":{"completed":2,"total":3},"attachment":{"completed":33,"total":33},"comment":{"completed":0,"total":0}}}}
```

2021-12-14 08:07 UTC, vishnugopal approved these changes
Approved, see discussion here: p1639466977390300-slack-C01A60HCGUA

2021-12-14 15:34 UTC, merged

2021-12-14 17:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7041125

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

2021-12-24 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7041125).