Theme Showcase: Re-add prices
Automattic/wp-calypso pull request #59149
Opened 2021-12-13 20:53 UTC by nelsonec87

#### Changes proposed in this Pull Request

* Re-add premium themes prince refs - Revert changes from #58677 

- Re-add individual theme price on theme sheet
- Re-add individual theme price and upsell icon/tooltip on multi-theme views
- Re-add related tests/snapshots

#### Testing instructions

* Sandbox the API and on your sandbox, comment out the retired themes filter on line 194 of `public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-themes-v1-2-endpoint.php`
* Visit `/themes/siteurl.wordpress.com/?flags=themes/premium` to enable the feature flag
* Edit your local calypso and add `theme.retired = false;` on or around line 827 of `/client/my-sites/theme/main.jsx`
* Click on the Premium filter to show only Premium themes; you should be able to see all retired premium themes in the Showcase now
* You should be able to see individual price information when viewing all premium themes in the Showcase
* Clicking on any premium theme should show the theme sheet, which should have an individual price as well.

<img width="1154" alt="Screen Shot 2021-11-30 at 2 15 20 PM" src="https://user-images.githubusercontent.com/2124984/144112818-856735b9-56ff-4c25-9042-9e3c46c96f68.png">
<img width="1449" alt="Screen Shot 2021-11-30 at 2 15 39 PM" src="https://user-images.githubusercontent.com/2124984/144112832-a3a43fef-7b00-4760-bbae-6e755924b5b0.png">

Related to #59125

2021-12-13 22:17 UTC, sixhours approved these changes
This looks good! I think I see some weirdness around prices still displaying for upgraded sites, but obviously they were there before since this is just a reversal of what we removed. 🙃 Let's merge this and fix any remaining bugs in separate PRs.

2021-12-13 22:30 UTC, nelsonec87 commented
There's a code style error:

```
'url' import is restricted from being used. Node's `url` is deprecated. Please consider migrating to `lib/url` (see `client/lib/url/README.md`). (no-restricted-imports)
```

It's the same lib that was that before. I'm not sure if I should ignore it for now or refactor the code.

2021-12-14 15:43 UTC, mreishus requested changes
I'm seeing prices when I visit the theme showcase, but when I add `?flags=themes/premium`, the prices are no longer there.

2021-12-14 15:49 UTC, mreishus commented
Wait a second. I believe the Flag ON behavior is correct, but the flag OFF behavior is not:
* Flag ON, viewing site with premium plan: *Prices do not display* :heavy_check_mark: 
* Flag ON, viewing site with free plan: *Prices display* :heavy_check_mark: 
* Flag OFF, viewing site with premium plan: *prices display* :grey_question:

2021-12-14 16:35 UTC, mreishus commented
Maybe it doesn't matter if all premium themes are hidden? @sixhours do you have an opinion here?

2021-12-14 16:42 UTC, sixhours commented
> Maybe it doesn't matter if all premium themes are hidden? @sixhours do you have an opinion here?

That's my thought, too. I just did a test with Free, Premium, and Business plans, and I think the behavior is expected with the exception of Premium plans with the flag off -- but that shouldn't be an issue because folks who have a premium plan should not see the new premium themes until after launch, and the flag will be on then. 

There may be an edge case where an existing premium plan user has a retired premium theme active. I'll test that scenario, but that means this bug would already have been in production. 

My test results with screenshots:

| * | Flag On | Flag Off |
----------------------
| Free | <img width="2378" alt="flag-free" src="https://user-images.githubusercontent.com/2124984/146041059-c6712a63-6b7c-4506-924f-d2d6b1abbf9e.png"> | <img width="2381" alt="noflag-free" src="https://user-images.githubusercontent.com/2124984/146041114-d0549dc2-5ca1-45ed-8f91-2b56203bd473.png"> |
| Premium | <img width="2378" alt="flag-premium" src="https://user-images.githubusercontent.com/2124984/146040615-513d23a3-408e-44a7-bff3-32319e9713bd.png"> | <img width="2376" alt="noflag-premium" src="https://user-images.githubusercontent.com/2124984/146040705-9170f71f-e7e5-45d4-ac03-ad74fb32177e.png"> |
| Business | <img width="2374" alt="flag-business" src="https://user-images.githubusercontent.com/2124984/146040979-8b1a8a06-1d22-4800-a189-7e60561fe4ff.png"> | <img width="2377" alt="noflag-business" src="https://user-images.githubusercontent.com/2124984/146040883-7447781e-796f-42b2-a5ba-c8ba50b1f8ee.png"> |

2021-12-14 16:51 UTC, sixhours commented
> There may be an edge case where an existing premium plan user has a retired premium theme active. I'll test that scenario, but that means this bug would already have been in production.

Tested this and I think it's a non-issue -- the retired theme doesn't appear in the search results (thus no price shown) and the individual theme sheet shows a retired notice, no price.

2021-12-14 17:25 UTC, mreishus approved these changes

2021-12-14 18:33 UTC, merged