Plugin Details: check how the description of paid plugins renders
Automattic/wp-calypso pull request #59181
Opened 2021-12-14 13:52 UTC by gcsecsey

#### Changes proposed in this Pull Request

* Added the `useWPCOMPlugin` hook to fetch paid plugin data
* Plugin data is now fetched either from the WPorg or WPcom API, based on the `isMarketplaceProduct` selector

#### Testing instructions

###### WPorg plugins
* Go to a WPorg plugin page (eg. `/plugins/woocommerce`)
* Check for regressions

##### WPCom plugins
* Go to a WPcom plugin page (eg. `/plugins/woocommerce-subscriptions`)
* Verify that the description is formatted correctly
* Verify that fields are displayed as below:
  ![calypso localhost_3000_plugins_woocommerce-subscriptions_gcsecseyfree wordpress com](https://user-images.githubusercontent.com/11555574/146011207-6a978cdc-e7af-4e5c-90ff-539e3fda6739.png)

#### Known issues

In the WPcom API reponse, there are some fields missing compared to the WPorg API. This cause UI elements to not render on the page:

```json
"banners": {
        "high": "",
        "low": ""
},
"num_ratings": 3812,
"ratings": {
        "1": 323,
        "2": 83,
        "3": 83,
        "4": 157,
        "5": 3166
},
"requires": "5.6",
"requires_php": "7.0",
"tags": {
        "e-commerce": "e-commerce",
        "sales": "sales",
        "sell": "sell",
        "store": "store",
        "woo": "woo"
},
"tested": "5.8.2",
```

I'll add create an issue to track these differences and add a minimal set of fields, so the UI elements render similarly to WPorg plugins.

Closes #57756

2021-12-14 15:08 UTC, cpapazoglou requested changes
Looks and works good! 

I just left two minor comments.

2021-12-14 15:08 UTC, cpapazoglou commented on client/my-sites/plugins/plugin-details.jsx
> +import { isEmpty } from 'lodash';
There is an initiative to refactor away from `lodash` p4TIVU-9Bf-p2.

It seems we haven't yet implemented an `isEmpty` method here though 
https://github.com/Automattic/wp-calypso/blob/8864b8e706d10bc428a5b4c9a5e29aeef3f872fc/packages/js-utils/src/index.ts#L1-L5

Do you think you can use plain JS for the `isEmpty` check? Or do we need to implement the method so that we cover more cases?

2021-12-14 15:08 UTC, cpapazoglou commented on client/my-sites/plugins/plugin-details.jsx
> +		// ( ! isMarketplaceProduct && ( isWporgPluginFetching || ! isWporgPluginFetched ) ) ||
should we remove this comment?

2021-12-14 15:47 UTC, gcsecsey commented on client/my-sites/plugins/plugin-details.jsx
> +import { isEmpty } from 'lodash';
There's no need to implement the method, I can use an `Object.values().length` check in this case. 👍

2021-12-15 09:25 UTC, cpapazoglou approved these changes
LGTM! 🚢 !

2021-12-15 09:25 UTC, cpapazoglou commented on client/my-sites/plugins/plugin-details.jsx
> +	} = useWPCOMPlugin( props.pluginSlug, { enabled: isProductListFetched && isMarketplaceProduct } );
Great use of `useQuery` here!

2021-12-15 09:32 UTC, merged