Domains: Update Domain Management contact information section
Automattic/wp-calypso pull request #59194
Opened 2021-12-14 16:51 UTC by rafaelgalani

#### Changes proposed in this Pull Request
TBD

#### Testing instructions
TBD

2021-12-14 16:55 UTC, a8ci18n commented on client/my-sites/domains/domain-management/contacts-privacy/contacts-card.jsx
> +			? translate( 'Privacy protection on' )
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Privacy protection: on' )` *ES Score: 10*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-14 16:55 UTC, a8ci18n commented on client/my-sites/domains/domain-management/contacts-privacy/contacts-card.jsx
> +			: translate( 'Privacy protection off' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Privacy protection: off' )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-14 16:55 UTC, a8ci18n commented on client/my-sites/domains/domain-management/settings/index.tsx
> +			? translate( 'privacy protection on' )
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Privacy protection: on' )` *ES Score: 10*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-14 16:55 UTC, a8ci18n commented on client/my-sites/domains/domain-management/settings/index.tsx
> +			: translate( 'privacy protection off' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Privacy protection: off' )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-16 01:19 UTC, a8ci18n commented on client/my-sites/domains/domain-management/contacts-privacy/contacts-card.tsx
> +			? translate( 'Privacy protection on' )
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Privacy protection: on' )` *ES Score: 10*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-16 01:19 UTC, a8ci18n commented on client/my-sites/domains/domain-management/contacts-privacy/contacts-card.tsx
> +			: translate( 'Privacy protection off' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Privacy protection: off' )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-16 20:24 UTC, leonardost requested changes
This is looking great, nice job! 👍  I tested with some different domains and found only one issue when viewing a domain where I'm not the owner - the loading state never resolves because the `whois` query returns an error. I've left a fix suggestion in the code. Other than that, works great! 😄

2021-12-16 20:24 UTC, leonardost commented on client/my-sites/domains/domain-management/settings/index.tsx
> +	const getContactInformationAccordion = () => {
I think there might be a problem here when viewing domains of which we are not owners - the `requestWhois` query will return an error, and the component's loading state will never be resolved. A quick and dirty fix would be adding a condition at the start of this method to check if the current user can manage this domain, something like

```
if ( ! domain.currentUserCanManage ) {
	return (
		<Accordion title="Contact information">
			<ContactsPrivacyInfo
				domains={ props.domains! }
				selectedSite={ props.selectedSite }
				selectedDomainName={ props.selectedDomainName }
			></ContactsPrivacyInfo>
		</Accordion>
	);
}
```

This duplicates some code, but I couldn't think of anything more elegant at the moment 😅

2021-12-17 17:22 UTC, rafaelgalani commented
Changing base as the folder structure/methods usage in #59334 is more adequate - also to avoid a future conflict resolution when rebasing 😄

2021-12-17 17:25 UTC, a8ci18n commented on client/my-sites/domains/domain-management/settings/cards/contact-information/contacts-card.tsx
> +			? translate( 'Privacy protection on' )
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Privacy protection: on' )` *ES Score: 10*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-17 17:25 UTC, a8ci18n commented on client/my-sites/domains/domain-management/settings/cards/contact-information/contacts-card.tsx
> +			: translate( 'Privacy protection off' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Privacy protection: off' )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-17 20:20 UTC, a8ci18n commented on client/my-sites/domains/domain-management/settings/index.tsx
> +			? translate( 'Privacy protection on', { textOnly: true } )
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **23** times:
`translate( 'Privacy protection: on' )` *ES Score: 10*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-17 20:20 UTC, a8ci18n commented on client/my-sites/domains/domain-management/settings/index.tsx
> +			: translate( 'Privacy protection off', { textOnly: true } );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **21** times:
`translate( 'Privacy protection: off' )` *ES Score: 11*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/domain-management-contact-information)

2021-12-20 09:46 UTC, gius80 commented on client/my-sites/domains/domain-management/settings/cards/contact-information/contacts-card.tsx
> +								a: <a href={ PRIVACY_PROTECTION } />,
I noticed that previous component had` target="blank"` for this link, maybe we can maintain the same approach here.

```suggestion
								a: <a href={ PRIVACY_PROTECTION } target="_blank" rel="noopener noreferrer" />,
```

2021-12-20 09:46 UTC, gius80 commented on client/my-sites/domains/domain-management/settings/cards/contact-information/contacts-card.tsx
> +						a: <a href={ PUBLIC_VS_PRIVATE } />,
Same as https://github.com/Automattic/wp-calypso/pull/59194/files#r772218992

2021-12-20 09:47 UTC, gius80 commented
I re-checked, now everything looks ok! Good job! 🤙

I Left just a couple of nitpicky comments.

2021-12-21 05:08 UTC, merged

2021-12-21 06:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7052628

Thank you @rafaelgalani for including a screenshot in the description! This is really helpful for our translators.

2022-01-06 11:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7052628).