More Informative Scan: Layout fixes
Automattic/wp-calypso pull request #59282
Opened 2021-12-16 01:57 UTC by miguelxpn

#### Changes proposed in this Pull Request

* Layout fixes for header card
* Layout spacing fixes for Calypso Green
* Stop showing the low threat cards if no low threats are present
* Make entire low threat card clickable like the other threat cards

#### Testing instructions

*

Related to #

2021-12-16 02:02 UTC, a8ci18n commented on client/components/jetpack/threat-dialog-new/index.tsx
> +					{ action === 'fix' && translate( 'Jetpack will fix the %(severity)s threat:', {
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2021-12-16 02:31 UTC, a8ci18n commented on client/components/jetpack/threat-dialog-new/index.tsx
> +						translate( 'Jetpack will fix the %(severity)s threat:', {
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2021-12-16 17:14 UTC, bhoop requested changes
The layouts seem good, the only suggestion I'd have would be regarding the messaging for ignoring threats: the message "Jetpack will ignore the `$severity` threat:" works well for critical threats, but for others it seems a little clunky ("Jetpack will ignore the low threat:"). Could we either remove the severity altogether from that message (since it's displayed next to the threat anyway), or use a message like "Jetpack will ignore the low-risk threat"?

2021-12-16 17:54 UTC, miguelxpn commented
> The layouts seem good, the only suggestion I'd have would be regarding the messaging for ignoring threats: the message "Jetpack will ignore the `$severity` threat:" works well for critical threats, but for others it seems a little clunky ("Jetpack will ignore the low threat:"). Could we either remove the severity altogether from that message (since it's displayed next to the threat anyway), or use a message like "Jetpack will ignore the low-risk threat"?

You're right, it's redundant since we show the threat anyway so I removed it.

2021-12-16 19:13 UTC, bhoop approved these changes
👍

2021-12-16 19:18 UTC, merged

2021-12-16 20:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7045060

Hi @miguelxpn, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Jetpack will ignore the threat:`
- `Jetpack will ignore the threat.`

Thank you in advance!

2021-12-24 10:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7045060).