Emails: Comparison table additions
Automattic/wp-calypso pull request #59535
Opened 2021-12-23 14:59 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

Code added to show features in the newly created component for the email providers comparison.

This code does not add mobile support yet. It will added in a further pull request in order to do not make huge reviews.

#### Testing instructions

1. Go to a site with domains without email subscription
2. Click on 'Add email' for the desired site
3. Once you are in the comparison page, add at the end the following flag: `?flags=emails/new-email-comparison`
4. Click then in the "see how they compare" in the top of the screen

![image](https://user-images.githubusercontent.com/5689927/147257346-bec925ab-4f58-42fc-85dd-dc53d64177f8.png)

Related to {1200182182542585-1201539393037967}

2021-12-23 15:04 UTC, a8ci18n commented on client/my-sites/email/email-providers-in-depth-comparison/data.ts
> +	subtitle: translate( 'Integrated email solution for your WordPress.com site' ),
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'Integrated email solution for your WordPress.com site.' )` *ES Score: 10*

2021-12-23 16:40 UTC, stephanethomas commented
> There is a property that shows/hides the first column, if we show the first columnist looks like this:
> 
> ![image](https://user-images.githubusercontent.com/5689927/147257927-d3f3d160-f083-4491-a43f-9a7f3b61b22d.png)

Is this something that was designed in the mockups? Or maybe you wanted to propose that option to @saygunnyc? Otherwise, I would vote for removing that feature (and the corresponding code) if we have no plan to use it 🙂.

2021-12-23 17:16 UTC, stephanethomas commented
Would you mind sharing the corresponding mockup in the description? I've find one that does not match what you've implemented exactly:

![image](https://user-images.githubusercontent.com/594356/147272518-b155a74c-5648-49f9-a667-988c1ed2c5ab.png)

I'm also worried of the approach taken to render this table (where we cycle through features and then email providers) as it will be very difficult to modify to match the mockup for mobile devices. I also wonder if we could use [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) to help with that.

2021-12-23 17:18 UTC, stephanethomas requested changes
While this works, I've left several comments regarding this first iteration.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/index.tsx
> +				{ translate( 'See how they compare' ) }{ ' ' }
Why do we need that white space?

```suggestion
				{ translate( 'See how they compare' ) }
```

Can't we achieve the same thing with CSS?

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/index.tsx
> +				className="email-providers-in-depth-comparison__main"
As a general rule, we should avoid creating classes that we don't use. So let's remove that one (and any other one in the same case).

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/index.tsx
> +				showFeatureNames={ false }
For the records, I've left a comment about that feature [here](https://github.com/Automattic/wp-calypso/pull/59535#issuecomment-1000416172).

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-stacked-comparison/style.scss
> +
There is an unnecessary blank line here.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-stacked-comparison/style.scss
> +
There is an unnecessary blank line here as well.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/data.ts
> +import emailForwarding from 'calypso/assets/images/email-providers/forwarding.svg';
`emailForwardingLogo` is probably a more descriptive name.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/data.ts
>  	header: 'Professional Email',
Unlike Google Workspace, we should localize the name of Professional Email. We can actually call `getTitanProductName()` for that.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/data.ts
>  	header: 'Google Workspace',
Thinking about it more, we should call `getGoogleMailServiceFamily()` instead of hardcoding that string.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/data.ts
> +	support: translate( '24/7 support via email' ),
We could probably order all those props alphabetically. That way the order is predictable (and the same for each email solution), and it's easier to find what you look for.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/index.tsx
>  	);
I would add plenty of blank lines so it's easier to read this block of code, and understand how it is structured:

```javascript
const translate = useTranslate();

return (
  <>
    <h1 className="email-providers-in-depth-comparison__header wp-brand-font">
      { translate( 'See how they compare' ) }{ ' ' }
    </h1>

    <ComparisonTable
      className="email-providers-in-depth-comparison__main"
      emailProviders={ [
        professionalEmailFeatures,
        googleWorkspaceFeatures,
        emailForwardingFeatures,
      ] }
      showFeatureNames={ false }
    />

    <div className="email-providers-in-depth-comparison__button-container">
      <Button className="email-providers-in-depth-comparison__button" primary>
        { translate( 'Get started' ) }
      </Button>
    </div>
  </>
);
```

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/data.ts
> -	selectCallback: noop,
Why did you remove `selectCallback` but still have it defined in `EmailProviderFeatures` (and still use it in `ComparisonTable`)?

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/data.ts
> +import googleWorkspaceIcon from 'calypso/assets/images/email-providers/google-workspace/icon.svg';
We could rename `googleWorkspaceIcon` to `googleWorkspaceLogo` so it is consistent with imports from the two other email solutions.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/comparison-table/index.tsx
> +	learnMore: string | null;
Similarly to another comment, maybe we could order all those props alphabetically.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/comparison-table/index.tsx
> +	);
I don't see a good reason not to inline that code below - it's not very long.

2021-12-23 17:18 UTC, stephanethomas commented on client/my-sites/email/email-providers-in-depth-comparison/comparison-table/index.tsx
> +		);
That seems convoluted to me, what if we simply pass that code when the list of features is defined?

```javascript
export const professionalEmailFeatures: EmailProviderFeatures = {
  logo: <Gridicon icon="my-sites" />,
};

export const googleWorkspaceFeatures: EmailProviderFeatures = {
  logo: <img src={ googleWorkspaceIcon } />,
};
```

2021-12-23 18:00 UTC, AllTerrainDeveloper commented on client/my-sites/email/email-providers-in-depth-comparison/index.tsx
> +				{ translate( 'See how they compare' ) }{ ' ' }
Ups, this seems to be the auto fix from PhpStorm, it sometimes adds that space when running the fixer.

2022-01-10 18:00 UTC, saygunnyc commented
Hey, @AllTerrainDeveloper, I am having a hard time understanding this screenshot. 

![147257346-bec925ab-4f58-42fc-85dd-dc53d64177f8](https://user-images.githubusercontent.com/78876323/148814452-d97c8125-484b-4ade-b9ab-5b5ac4db9ea4.png)

As @stephanethomas shared the screenshots [above](https://github.com/Automattic/wp-calypso/pull/59535#issuecomment-1000434098), over the new Email Onboarding on Inbox menu item, we don't display Email Forwarding as it's not a part of the Inbox experience. There are other design discrepancies as well. – Alignments, spacings, colors, etc. 

Please go through these 2 posts for further information. 
- https://titanp2.wordpress.com/2021/10/08/new-horizons-expedition-1-email-onboarding/
- https://titanp2.wordpress.com/2021/11/24/new-horizons-expedition-2-checking-out-with-multiple-mailboxes/

The only place where we planned for displaying Email Forwarding over a comparison is the newly designed [Emails Landing Page](https://emailprovidersp2.wordpress.com/2021/12/22/email-solutions-and-professional-email-landing-pages/) where the context is different. We may use a shared component if it helps with implementation however we should keep in mind that the contents might change depending on context. – Number of columns, raws, etc.


Let me know if you need any other clarifications or need help with unpacking styles from Figma. Happy to do another detailed review once we have some more progress.

cc @poligilad-auto

2023-09-22 09:41 UTC, closed without merging