P2 signup: add 'post-email confirmation' step
Automattic/wp-calypso pull request #59573
Opened 2021-12-27 14:26 UTC by annemirasol

#### Changes proposed in this Pull Request

* Part of the revised P2 signup flow project (p9lV3a-2MW-p2). 
* Signup flow: display an extra step after a user has verified their email.
* See p9lV3a-2Lp-p2#comment-3599 for details about this step.

#### Testing instructions

1. Check that verified users are skipped over:
    a. While logged in as a verified user, visit `calypso.localhost:3000/start/p2-new`. Since your user account is already verified, you should go straight to the `p2-site` step.
2. Check that unverified users are made to go through the confirmation steps:
    a. In incognito mode, visit `calypso.localhost:3000/start/p2-new` and sign up for a new acccount, using an email address that you have access to.
    b. After signing up, you should get the "Confirm your email address" step. Do not close this window.
    c. Copy the verification link and paste it in a browser tab, within the same incognito session.
    d. Reload the window in 2b. You should get the "Email confirmed" step.

2021-12-27 14:30 UTC, a8ci18n commented on client/signup/steps/p2-email-confirmed/index.jsx
> +			headerText={ translate( 'Email confirmed' ) }
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **28** times:
`translate( 'Email confirmed!' )` *ES Score: 10*

2021-12-28 07:51 UTC, a8ci18n commented on client/signup/steps/p2-confirm-email/index.jsx
> +				isEmailVerified ? translate( 'Email confirmed' ) : translate( 'Check your email' )
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **28** times:
`translate( 'Email confirmed!' )` *ES Score: 10*

2021-12-28 11:15 UTC, unDemian requested changes
> Not sure if I'm missing something, since I've tried it twice, but I can only verify the account if I login first in the new tab and only afterwards paste the activation link. 

Hmm, that's weird. Sounds like the second tab doesn't share your logged in session with the signup flow tab? After creating an acccount, you should be automatically logged in as that account, so it's surprising that it prompts you to log in.

When you go to wordpress.com in the second tab, does it show you are logged out?

> However the issue is that reloading the "Check your email" page after I activate the account remains the same. If in the other tab I logout or I don't login in the first place reloading "Check your email" redirects me to http://calypso.localhost:3000/start/p2-new/user

`http://calypso.localhost:3000/start/p2-new/user` is what a logged out user would get. If you had manually logged out via the second tab, this makes sense.

When you activated your account, did it redirect you to `wordpress.com/read?verified=1` and showed a notice like this?
<img width="371" alt="Screen Shot 2021-12-28 at 11 45 32 PM" src="https://user-images.githubusercontent.com/730823/147583230-41ebb468-6093-4836-bcd1-1a77967a8e47.png">

Also, sorry I forgot to put that you will need to build with `ENABLE_FEATURES=no-force-sympathy yarn start`. Not doing this shouldn't have caused being stuck on the "Check your email" page, but it may cause skipping the "Email confirmed" page when you reload post-activation, since state rehydration might be skipped.

2021-12-28 16:01 UTC, annemirasol commented
Here's a recording of what I'm seeing, if it helps: https://d.pr/v/sqIQQG

2021-12-29 07:49 UTC, unDemian commented
Not sure what is happening, https://d.pr/v/yFH1oo but I still cannot reproduce it 🙁

2021-12-29 08:47 UTC, annemirasol commented
> Not sure what is happening, https://d.pr/v/yFH1oo but I still cannot reproduce it 🙁

Ahh I see now. Please turn off the Chrome incognito's third-party cookies blocking, as there'd be trouble due to `calypso.localhost:3000` vs `wordpress.com` cookies. TIL logging in wouldn't work from calypso.localhost:3000 if third-party cookies are blocked. 


<img width="631" alt="Screen Shot 2021-12-29 at 4 40 51 PM" src="https://user-images.githubusercontent.com/730823/147643611-bdbecad3-7d76-40c9-9a17-7f7d23bc770e.png">

2021-12-29 09:27 UTC, unDemian approved these changes
Looking good!

> Ahh I see now. Please turn off the Chrome incognito's third-party cookies blocking, as there'd be trouble due to calypso.localhost:3000 vs wordpress.com cookies. 

Great catch.

2021-12-30 10:02 UTC, merged

2021-12-30 11:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7066240

Thank you @annemirasol for including a screenshot in the description! This is really helpful for our translators.

2022-01-06 11:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7066240).