Fix confirm transfer dialog copy for connected domains
Automattic/wp-calypso pull request #60090
Opened 2022-01-14 16:12 UTC by gius80

## Changes proposed in this Pull Request

This PR fixes the confirmation dialog text for the `transfer-domain-to-another` action, for registered domain (see p2MSmN-8Th-p2)

At the moment, the confirmation popup wrongly mentions:

- `registered domain` as `mapped domain`.
- `domain mapping subscription` instead of `domain connection subscription`.
- even if a site had a plan, the domain would still be renewed separately.

**Case A (user with flag `NON_PRIMARY_DOMAINS_TO_FREE_USERS`)**

![A - Before](https://user-images.githubusercontent.com/2797601/149545085-5db89019-eebd-44cc-bda4-ccddcf03e227.png)

![A - After](https://user-images.githubusercontent.com/2797601/149545099-1df10d23-8aed-4080-b987-4b91ab422c28.png)

**Case B (user without flag `NON_PRIMARY_DOMAINS_TO_FREE_USERS`)**

![B - Before](https://user-images.githubusercontent.com/2797601/149545739-6267b128-79a0-4885-b7e8-067cef7ca539.png)

![B - After](https://user-images.githubusercontent.com/2797601/149545145-59181886-9275-4f44-abaf-f6628ebad909.png)

## Testing instructions

- Build this branch locally or open the live Calypso link
- Navigate to the transfer page for a registered domain, in a planned plan (`domains/manage/[:REGISTERED_DOMAIN/transfer/other-site/[:PAID_PLAN]`)
- Click the `Transfer - To another WordPress.com site` card cta, and select a free plan
- Ensure the Confirm Dialog copy is the same as the screenshots above

2022-01-14 16:17 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
> +						"The target site doesn't have a paid plan, so you'll have to pay the full price for a " +
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'The target site doesn't have a paid plan, so you'll have to pay the full price for a domain mapping subscription when the domain mapping next renews. You will not be able to set it as primary either. If you upgrade the target site to a paid plan, these features are included in the plan.' )` *ES Score: 6*

2022-01-14 17:43 UTC, delputnam requested changes
@gius80 let me know if you need some help understanding the different cases here (I know it's confusing).

2022-01-14 17:43 UTC, delputnam commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
>  							'If you upgrade the target site to a paid plan, these features are included in the plan.'
This is the text where we should change the reference from "mapping" to "connection".

2022-01-14 17:43 UTC, delputnam commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
> +					) }
This text should refer to moving a registered domain to a site without a plan. So, something like: "The target site doesn't have a paid plan, so you won't be able to set this domain as primary on the site."

2022-01-14 17:43 UTC, delputnam commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
>  				) }
This text should change the reference from "mapping" to "connection".

2022-01-14 17:43 UTC, delputnam commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
> +			</p>
I don't think this case would matter when the user doesn't have the `NON_PRIMARY_DOMAINS_TO_FREE_USERS` flag and is transferring a domain (as opposed to a domain connection).

2022-01-17 09:57 UTC, gius80 commented
> @gius80 let me know if you need some help understanding the different cases here (I know it's confusing).

Thanks @delputnam, it would be very useful 🙏

2022-01-17 16:49 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
> +				'Do you want to transfer domain connection of {{strong}}%(domainName)s{{/strong}} ' +
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'Do you want to transfer mapping of {{strong}}%(domainName)s{{/strong}} to site {{strong}}%(targetSiteTitle)s{{/strong}}?' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/domain-transfer-dialog-text)

2022-01-17 16:49 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
> +			: translate( 'Confirm Domain Connection Transfer' );
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **18** times:
`translate( 'Transfer this domain connection' )` *ES Score: 7*

2022-01-17 16:49 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-user/transfer-domain-to-other-user.jsx
> +				'Do you want to transfer the domain connection of {{strong}}%(domainName)s{{/strong}} ' +
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Do you want to transfer the domain mapping of {{strong}}%(domainName)s{{/strong}} to {{strong}}%(selectedUserDisplay)s{{/strong}}?' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/domain-transfer-dialog-text)

2022-01-17 16:49 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-user/transfer-domain-to-other-user.jsx
> +			? translate( 'Transfer domain connection' )
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **18** times:
`translate( 'Transfer this domain connection' )` *ES Score: 10*

2022-01-17 16:49 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-user/transfer-domain-to-other-user.jsx
> +							'Please choose an administrator to transfer domain connection of {{strong}}%(domainName)s{{/strong}} to.',
:ok: This change will be queued for retranslation. We'll use the existing translations in the meantime.

2022-01-17 16:49 UTC, a8ci18n commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-user/transfer-domain-to-other-user.jsx
> +							'You can transfer this domain connection to any administrator on this site. If the user you want to ' +
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **20** times:
`translate( 'You can transfer this domain to any administrator on this site. If the user you want to transfer is not currently an administrator, please {{a}}add them to the site first{{/a}}.' )` *ES Score: 8*
See 1 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/fix/domain-transfer-dialog-text)

2022-01-17 17:09 UTC, gius80 commented
@delputnam I fixed previous issues and I also replaced "domain mapping" references with "domain connection" in the _transfer to user_ section.

2022-01-17 18:06 UTC, delputnam approved these changes
Thank you so much for updating all of the other mentions of "mapping" as well! 🙇 

Once you add the condition to check the value of `this.props.primaryWithPlansOnly` on that last warning, I think this is good to merge.

2022-01-17 18:06 UTC, delputnam commented on client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
>  		);
This should only be returned when `this.props.primaryWithPlansOnly` is `true`.

So I think we can do something like:
```
		if ( this.props.primaryWithPlansOnly ) {
			return (
				<p>
					{ this.props.translate(
						"The target site doesn't have a paid plan, so you won't be able to set this domain as primary on the site."
					) }
				</p>
			);
		}

		return null;
```

2022-01-18 09:54 UTC, merged

2022-01-18 10:21 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7088236

Thank you @gius80 for including a screenshot in the description! This is really helpful for our translators.

2022-01-28 10:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7088236).