Bring back crossed out UI to show the first-year discount.
Automattic/wp-calypso pull request #60184
Opened 2022-01-18 11:37 UTC by claudiucelfilip

#### Changes proposed in this Pull Request

More context: pdgrnI-he-p2
This brings back the crossed-out UI to show the first-year discount on the /plans page.
<img width="257" alt="Screenshot 2022-01-13 at 5 35 17 PM (1)" src="https://user-images.githubusercontent.com/2749938/149906985-ff6ca838-0ecb-44b8-934b-04b708f9ceee.png">

#### Testing instructions

* Create or Log in to an account that benefits from 1st-year promotional pricing (more info p7DVsv-9lB-p2)
* Go to the /plans page
* Under the `Pay annually` tab you should be able to see the crossed-out discounted prices with the saving % calculation
<img width="480" alt="Screenshot on 2022-01-18 at 13-34-41" src="https://user-images.githubusercontent.com/2749938/149930250-a7acdbd0-32f0-441d-bfa3-a3367d4f2e88.png">

* Make sure there're no related JS errors in the console.

2022-01-20 05:52 UTC, niranjan-uma-shankar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix discount pricing bug in Calypso's /plans page](https://trello.com/c/7YeR2dVL/393-fix-discount-pricing-bug-in-calypsos-plans-page)

2022-01-20 06:23 UTC, niranjan-uma-shankar requested changes
1. If the account is on a yearly paid plan, then we don't need to show the annual plan savings because we don't show the monthly/annual toggle.

<img width="1131" alt="Screenshot 2022-01-20 at 10 01 31 AM" src="https://user-images.githubusercontent.com/1269602/150283855-5c369f22-4d17-484f-ad3d-827828dc28f1.png">

2. If the account is on a monthly paid plan, then the annual plan savings is being calculated with pro-rated credits included. I think we should exclude the pro-rated annual plan price while calculated the savings. We already do this for the monthly plans tab (notice in the GIF below how the savings figure is different for monthly plans tab and annual plans tab), so can we use the same % savings figure for the annual plans tab too?

![strikeoutprice](https://user-images.githubusercontent.com/1269602/150284644-a27b0fb7-8be7-4523-9f90-c1e1cc318306.gif)

3. Looks like this change also brings back the strike out price UI when pro-rated credits are applied which is good news.

2022-01-24 11:12 UTC, claudiucelfilip commented
@niranjan-uma-shankar Thanks for the thorough review. 
> 1. If the account is on a yearly paid plan, then we don't need to show the annual plan savings because we don't show the monthly/annual toggle.

I've hidden it now based on the `isEligibleForWpComMonthlyPlan`, also used in the `IntervalTypeToggle`.

> 2. If the account is on a monthly paid plan, then the annual plan savings is being calculated with pro-rated credits included. I think we should exclude the pro-rated annual plan price while calculated the savings. We already do this for the monthly plans tab (notice in the GIF below how the savings figure is different for monthly plans tab and annual plans tab), so can we use the same % savings figure for the annual plans tab too?

I must have missed the inconsistencies with the accounts I was using. The annual figures should now match the ones from the monthly after using the same variables.

2022-01-31 09:39 UTC, niranjan-uma-shankar approved these changes
LGTM 🚢

2022-02-01 08:46 UTC, merged