G Suite: Retire Finish Setup notices shown when users have not accepted Google ToS yet
Automattic/wp-calypso pull request #60460
Opened 2022-01-25 16:49 UTC by stephanethomas

WIP.

2022-01-26 11:04 UTC, stephanethomas commented on client/lib/emails/email-provider-constants.js
> -export const EMAIL_WARNING_TYPE_ACTION_REQUIRED = 'action_required';
This particular constant was never used.

2022-01-28 14:06 UTC, AllTerrainDeveloper commented
I am not sure but the test is not fully working for me...

### EOT

**Domains**

Before
![image](https://user-images.githubusercontent.com/5689927/151560196-6f838b05-dc7e-42a1-99a1-5c98a0750b8e.png)

After
![image](https://user-images.githubusercontent.com/5689927/151560226-7f941096-dc9b-4493-98fa-69905570f892.png)

**Emails**
Before
![image](https://user-images.githubusercontent.com/5689927/151560458-24ca3bd7-ed3f-4be2-9d0c-2c619b9a8f1a.png)

After
![image](https://user-images.githubusercontent.com/5689927/151560511-8a56852d-6ae3-4193-92d8-7854fa2c937a.png)

2022-01-28 14:07 UTC, AllTerrainDeveloper requested changes
@stephanethomas seems that I have failing test. We can discuss it on Monday :)

2022-01-28 22:25 UTC, leonardost commented
I noticed yesterday that I had some domains with "Action required" status but no highlighted actions shown in the domain settings page, so thank you @stephanethomas for this fix 🙂 looks good from the domains' side, but I got the same results as Daniel in the emails screen:

| Before | After |
| ------ | ------ |
| <img width="1071" alt="Screen Shot 2022-01-28 at 19 17 38" src="https://user-images.githubusercontent.com/5324818/151629757-fb502ce4-7f7a-449d-ba90-e11000de822b.png"> | <img width="1077" alt="Screen Shot 2022-01-28 at 19 17 43" src="https://user-images.githubusercontent.com/5324818/151629766-0b96a4c4-2b20-4ad8-9295-93123edc0454.png"> |
| ------ | ------ |
| <img width="1080" alt="Screen Shot 2022-01-28 at 19 20 19" src="https://user-images.githubusercontent.com/5324818/151629819-9e96d9a0-7638-41b5-9714-ada11980edf5.png"> | <img width="1077" alt="Screen Shot 2022-01-28 at 19 20 25" src="https://user-images.githubusercontent.com/5324818/151629831-c03bccca-2a76-43db-bbe5-eed5fadc2907.png"> |

2022-01-31 09:14 UTC, stephanethomas commented
I think you're getting a different behavior because you didn't apply the server-side patch D73732-code. That's my fault though, I've only mentioned that patch in the description, and forgot about the testing instructions. I've updated them now.

2022-01-31 12:49 UTC, AllTerrainDeveloper commented
@stephanethomas this is not working as expected, I'll approve but you need to rebase first :) 

### EOT

![image](https://user-images.githubusercontent.com/5689927/151796334-8c6c254f-ede8-4c93-b91f-0f3e47a5c0ee.png)

2022-01-31 12:49 UTC, AllTerrainDeveloper approved these changes

2022-01-31 15:38 UTC, merged