App Banner: Use the current route to display open up the iOS Gutenberg editor correctly
Automattic/wp-calypso pull request #60643
Opened 2022-01-28 23:41 UTC by enejb

#### Changes proposed in this Pull Request

This PR intends to fix the App banner that appears in the Gutenberg editor. 
Hopefully this will fix 
1. The link in the banner should open up the correct for the correct post type: page or post
2. The link in the banner should open up for the correct site
3. The link in the banner should open up for the correct post id

#### Testing instructions

Use the QR code provided. 
Does clicking the banner open the page in the mobile app as expected. 

Related to #

2022-01-29 00:17 UTC, enejb commented
In my testing, this worked as expected that the app doesn't support paths that contain the id of the post or page.

2022-01-31 20:00 UTC, emilylaguna requested changes
👋  Unfortunately in my testing I could not get the button to open in the WPiOS editor with the correct post on the correct site. 

I tested:
- Opening an existing post and tapping the open in app button
- Creating a new post and tapping the open in app button

https://user-images.githubusercontent.com/793774/151863859-9f134925-e528-4fb8-b3d4-ed5b51b4463d.MP4

Let me know if I am doing something wrong.

2022-01-31 20:00 UTC, emilylaguna commented on client/state/selectors/should-display-app-banner.ts
> +	// const dismissedUntil = getPreference( state, APP_BANNER_DISMISS_TIMES_PREFERENCE );
Are we changing to always show the CTA?

2022-01-31 20:00 UTC, emilylaguna commented on client/blocks/app-banner/index.jsx
> +	// }
Do we need this commented code here?

2022-01-31 20:00 UTC, emilylaguna commented on client/blocks/app-banner/index.jsx
> +	const paths = currentRoute.split( '/' );
Can we add some comments on what this function is doing?

2022-02-01 21:10 UTC, enejb commented on client/state/selectors/should-display-app-banner.ts
> +	// const dismissedUntil = getPreference( state, APP_BANNER_DISMISS_TIMES_PREFERENCE );
No just for easier testing of this.

2022-02-11 21:13 UTC, enejb commented
@emilylaguna Can you take another look. 
I fixed the issue that you found. The links should open now as expected in the correct site. 

However, linking to a specific page or post doesn't quite work as expected and updates to the app will need to be made.

2022-02-14 20:46 UTC, emilylaguna reviewed
Hey @enejb, when I open the editor, and then tap open in app from the CTA I am brought to the and the correct site is selected for the post on iOS 🥳 .

However, when I try on Android the post editor is opening but the site is not being selected correctly. Is it intended to also work there as well?

2022-02-14 20:54 UTC, enejb commented
No this is only meant to address the iOS browser for now.

2022-02-14 20:55 UTC, emilylaguna approved these changes
👍 LGTM!

2022-02-14 21:53 UTC, merged