get author parameter from plugin search query
Automattic/wp-calypso pull request #60679
Opened 2022-01-31 17:11 UTC by gcsecsey

Using quotes to delimit long author names. Adds the author query parameter to the WPOrg request.

#### Changes proposed in this Pull Request

* getting the author name from the search query
* using the author name in the WPOrg plugin query
* using the author name in the WPCom plugin query

#### Testing instructions

* TBD

Closes #57749

2022-02-11 15:16 UTC, cpapazoglou requested changes
Looks good to me, added a comment for making it work in wporg directory.

2022-02-11 15:16 UTC, cpapazoglou commented on client/lib/wporg/index.js
>  		query[ 'request[browse]' ] = category;
In case of `author` search the `request[browse]` shouldn't be added.

`https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request%5Bauthor%5D=Yoast&request%5Bpage%5D=1&request%5Bper_page%5D=24&request%5Bfields%5D=icons%2Clast_updated%2Crating%2Cactive_installs%2Ctested%2C-downloaded%2C-ratings%2C-requires%2C-requires_php%2C-tags%2Ccontributors%2C-added%2C-donate_link%2C-homepage&request%5Blocale%5D=es_ES`

works as expected (author search, searches in the author array)

cc: @WBerredo , @gcsecsey

2022-02-11 18:46 UTC, WBerredo commented on client/lib/wporg/index.js
>  		query[ 'request[browse]' ] = category;
Thanks for the finding.

Fixed at https://github.com/Automattic/wp-calypso/pull/60679/commits/db5810031a7de8ae9e2aca0ed2197f88aa9e9f46

2022-02-15 10:24 UTC, cpapazoglou approved these changes
LGTM!

Let's just address the feedback in D74695-code

2022-02-18 16:04 UTC, cpapazoglou approved these changes
LGTM!

2022-02-18 16:16 UTC, cpapazoglou commented
E2E Tests are failing for unrelated reasons.

2022-02-21 19:35 UTC, WBerredo commented
WP.com change deployed at: r240456-wpcom

2022-02-21 19:36 UTC, merged