VideoPress: Add support for retrieving "Original" video url for newly transcoded videos
Automattic/wp-calypso pull request #60900
Opened 2022-02-07 20:27 UTC by jgcaruso

This PR adds a new field to VideoPress Media Library entries to give the user access to their originally uploaded source video, now that we will be returning a "Compatibility" video format in the "URL" field to ensure videos uploaded to VideoPress can be shared and used anywhere on their site and be compatible with the most web browsers.

See pxWta-1bH-p2

#### Changes proposed in this Pull Request

* Add a new `Original URL` field to the detail modal for VideoPress videos where the "URL" field now returns the "Compat" video format (for easy sharing everywhere).

#### Testing instructions

* Apply D74381-code to your wpcom sandbox (if it hasn't already been deployed, ensure entire stack is either deployed or on your sandbox)
* upload a video to a site with VideoPress support 
* Open the video in the Media Library in Calypso
* The video should have an "Original URL" field (with a `yoursite.files.wordpress.com` host), and the "URL" field should have a `*_1080p_compat.mp4` file extension (with a `videos.files.wordpress.com` host)
* Open an older video from your media library, the "Original URL" field should not be present and the "Original URL" field should have the source video in it (with a `yoursite.files.wordpress.com` host)
* Do the same test with a Jetpack site, however in all cases the host should always be `videos.files.wordpress.com`

2022-02-22 13:35 UTC, thedebian requested changes
Worked fine on a wpcom simple site, however, I don't have an original URL populated on Jetpack on a new video upload: 

![Capture d’écran 2022-02-22 à 14 33 39](https://user-images.githubusercontent.com/1420594/155142713-ad785605-c967-4b8e-8539-d951863bd8fa.png)

2022-02-23 21:30 UTC, jgcaruso commented
> Worked fine on a wpcom simple site, however, I don't have an original URL populated on Jetpack on a new video upload:
> 
> ![Capture d’écran 2022-02-22 à 14 33 39](https://user-images.githubusercontent.com/1420594/155142713-ad785605-c967-4b8e-8539-d951863bd8fa.png)

Thanks for testing a Jetpack site, I hadn't actually tried that.

This issue is a little weird... The request actually goes directly to the jetpack site, not to wpcom. So to address it I've done the following:
1. If original url value is empty, I'm now hiding the field (new commit on this PR)
2. The code that adds the `original_url` to the response needs a IS_WPCOM check, and that has been added to D74381-code. BUT in order to test it, you will need to manually add the change in `public.api/rest/class.json-api-endpoints.php` to the equivalent file in your Jetpack site while having https://github.com/Automattic/jetpack/pull/22652 applied as well 😁  This code change should sync over automatically once D74381-code is deployed though since it is flagged as "Touches Jetpack Files", so I've not added it to that PR just to avoid any potential conflicts.

2022-02-25 09:21 UTC, thedebian approved these changes
Worked fine with the Jetpack patch applied to projects/plugins/jetpack/class.json-api-endpoints.php 👍

2022-09-13 18:02 UTC, jgcaruso commented
Abandoning for reasons given in pbFulr-Cp-p2

2022-09-13 18:02 UTC, closed without merging