Fix domain search results for long domain names
Automattic/wp-calypso pull request #60950
Opened 2022-02-09 10:31 UTC by gius80

## Changes proposed in this Pull Request

This PR fixes layout issues when entering long domain name in domain search signup step (white reskinned version).

<img width="1354" alt="152833214-f5d58cce-6e75-4581-9213-b84d174261a3" src="https://user-images.githubusercontent.com/2797601/153179783-53cb24bf-a569-4105-aef9-475d67b1d18b.png">

![domain-desktop-after](https://user-images.githubusercontent.com/2797601/153179721-705d5ede-ec11-4400-8d69-3aa06a1d509b.png)

![domain-after-mobile](https://user-images.githubusercontent.com/2797601/153179714-4254652d-ca2d-4aed-a43d-abc3c9baf92c.png)

## Testing instructions

- Build this branch locally or open the live Calypso link
- Navigate to `/start/domain`
- Enter a very long domain and verify that issues mentioned above has been fixed

2022-02-10 22:47 UTC, leonardost requested changes
Thanks for these updates! This looks great for long domain names, but it seems the layout is a little different for smaller names:

- Before:

<img width="960" alt="Screen Shot 2022-02-10 at 19 17 08" src="https://user-images.githubusercontent.com/5324818/153506862-68b6558c-d741-4cd4-aa67-e4e865798301.png">

- After:

<img width="975" alt="Screen Shot 2022-02-10 at 19 16 53" src="https://user-images.githubusercontent.com/5324818/153506886-7a02ac52-88a8-4181-bbf4-0128bb315aa3.png">

I tried finding a simple solution, but my CSS skills were not enough 😂 

Mobile view looks correct 👍

2022-02-10 22:47 UTC, leonardost commented on client/components/domains/featured-domain-suggestions/style.scss
> +    align-self: baseline;
Minor: these spaces should be replaced by tabs - dunno why the linter didn't catch this 🤔

2022-02-11 11:24 UTC, gius80 commented
> Thanks for these updates! This looks great for long domain names, but it seems the layout is a little different for smaller names:

I finally found a solution that works with both long and short names.😅 

Thanks @leonardost for noticing this 🙂

<img width="1037" alt="Schermata 2022-02-11 alle 12 24 02" src="https://user-images.githubusercontent.com/2797601/153583474-632c95d2-5cdc-4f0b-b6a3-c72b11007312.png">

2022-02-11 15:23 UTC, leonardost approved these changes
Awesome @gius80, this looks really nice! Great job! 😄

I always get lost when dealing with nested flex boxes and trying to get them to do what I want 😂

2022-02-11 15:56 UTC, merged