Welcome Tour: Removed checks for translations
Automattic/wp-calypso pull request #61034
Opened 2022-02-11 14:42 UTC by escapemanuele

#### Changes proposed in this Pull Request

Removed checks used while waiting for translations of the [new slide](https://github.com/Automattic/wp-calypso/pull/59498) introduced in the Welcome Tour.

#### Testing instructions

*  Checkout branch
* `yarn dev --sync` from `apps/editing-toolkit` to sync the welcome tour to the sandbox
* Check that the slide "Find your way" (6th on desktop) is correctly showing on desktop
* Change language in [https://wordpress.com/me/account](https://wordpress.com/me/account)
* Check that translations exist

Related to #59498

2022-02-11 15:43 UTC, alshakero approved these changes
Thanks for the initiative! LGTM.

2022-02-11 15:45 UTC, alshakero requested changes
It seems tests need some modifications.

2022-02-11 22:49 UTC, escapemanuele commented
@alshakero I modified the tests. To be honest, they weren't really helpful, as the locale passed to `getTourSteps` is only used in `createInterpolateElement`( "Congratulations!" slide, so no use in testing "en" and "nl" for "Find your Way" slide!).

While I changed that, I added basic tests for all tests 👍

2022-02-15 00:28 UTC, alshakero approved these changes
Gorgeous now!

2022-02-15 08:45 UTC, merged