Plugins: Improve messaging for Jetpack Scan detected errors
Automattic/wp-calypso pull request #61068
Opened 2022-02-14 09:55 UTC by epeicher

When uploading a plugin, it is scanned using Jetpack. The previous message
was unclear so it has been improved to a clearer message.

#### Changes proposed in this Pull Request

* Change the error message when Jetpack Scan reports a failure from
  > Upload problem: Invalid plugin. 

  to

  > The uploaded file is identified as malicious.

|Before | After|
|-------|------|
|<img width="1583" alt="image" src="https://user-images.githubusercontent.com/3519124/153840359-a0c4d1ce-1b85-48c3-9460-547499b7da19.png">|<img width="1595" alt="image" src="https://user-images.githubusercontent.com/3519124/153840101-aa333bc9-c794-42eb-b986-ad99c23640d9.png">|

#### Testing instructions

* In an Atomic site, go to  https://wordpress.com/plugins/upload
* Upload a plugin that fails, for example, this one: https://d.pr/f/0qHYDR/AxAmR8epYe

Related to #
Solves issue #58942

2022-02-14 12:30 UTC, cpapazoglou requested changes
Tested this and works as advertised. 

Can we also do the extra mile here by changing the error message in the main content and providing the user an alternative for uploading the plugin through WP Admin?

Prior art here

https://github.com/Automattic/wp-calypso/blob/08c583c6287e59734ad43ec1fc9692ed5cf73bde/client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx#L336-L350

2022-02-14 21:15 UTC, cpapazoglou commented on client/my-sites/marketplace/pages/marketplace-plugin-install/index.tsx
> +						'This plugin is identified as malicious. If you want to install the plugin, please continue by uploading the plugin again from WP Admin.'
```suggestion
						'This plugin is identified as malicious. If you still insist to install the plugin, please continue by uploading the plugin again from WP Admin.'
```

2022-02-14 21:19 UTC, cpapazoglou approved these changes
Thanks for addressing the feedback! That's a great improvement in UX!

Just left a minor comment regarding copy.

2022-02-15 09:00 UTC, merged

2022-02-15 10:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7141787

Thank you @epeicher for including a screenshot in the description! This is really helpful for our translators.

2022-02-25 12:28 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7141787).