Fix remove mobile app banner if previous flow was onboarding
Automattic/wp-calypso pull request #61134
Opened 2022-02-15 20:55 UTC by enejb

#### Changes proposed in this Pull Request

Removed the App Banner for the site editor if the user experienced the onboarding flow. 

See p1644591908914389-slack-C01DF571R5Y

#### Testing instructions

* Create a new site and select a template that has FSE enabled.

2022-02-16 07:35 UTC, simison commented
>  if the user experienced the onboarding flow.

Won't this remove it for everyone everywhere? Most new customers went through this flow, and few went through specific flows like "domains", "premium", "themes", "business", etc

2022-02-16 13:07 UTC, escapemanuele commented
> Won't this remove it for everyone everywhere?

Maybe we should also check for `currentFlowName` to be `setup-site`?

2022-02-21 13:30 UTC, escapemanuele commented on client/state/ui/selectors/app-banner-is-visible.js
> +	}
Hi @enejb, should we check here for the current flow name to be 'setup-site' and at the same time for the previous flow name to be 'onboarding' ?

2022-02-28 17:28 UTC, emilylaguna requested changes
@enejb I gave this another test and the banner is correctly hidden. However I'm thinking we should only apply the flow name check for the editor only. 

The reason I say that is because in my testing if the user enters the editor then goes to another section, or goes home the flow name will stay setup-site which means we won't show the banner at all. The only way I managed to reset the flow is by going back to the editor and finishing the post. 

If we move the flow check to the `should-display-app-banner` we are able to check both the section and the flow. 

Thoughts?

2022-03-03 19:08 UTC, enejb commented
@escapemanuele and @simison.

This approach does work anymore. I am not sure why exactly. `getCurrentFlowName( state )` returns an empty string.
Is there a redirect that is clearing the browser state? 
Since we don't have signup flow data anymore. 

@emilylaguna do you think we should use `isUserRegistrationDaysWithinRange()` and see if the user recently joined and only show them the notice if it has been a couple of days? 

Do you have any thoughts there?

2022-03-03 19:10 UTC, enejb commented
Users that create have a site already might end up in with this notice if they go through the flow which is not desiredable as well.

2022-03-03 23:13 UTC, emilylaguna approved these changes
Looks good to me, and is working well.

🚢

2022-03-03 23:13 UTC, merged