Site Settings: refactor and update support links
Automattic/wp-calypso pull request #61175
Opened 2022-02-16 19:33 UTC by arcangelini

## Changes proposed in this Pull Request
This started out as a simple PR to update the links to the support guide links and during the process, I decided to refactor a few things and make it a little cleaner and more uniform. Here are the major changes I made:
<img width="1075" alt="Markup 2022-02-16 at 20 25 07" src="https://user-images.githubusercontent.com/33258733/154340516-ff3062ed-11e7-4778-8827-6af059a65649.png">

#### Main Index
* Moved section headings within the appropriate components
* Removed unused props
* Added `siteIsAutomatedTransfer` prop to the sections that needed to provide the different support links based on that context.

#### Composing section
* Removed unnecessary connect to the store
* Removed unused props
* Added section header
* Changed `Latex` and `Shortcodes` components from class components to functions
* Updated support links
<img width="1629" alt="Markup 2022-02-16 at 20 30 35" src="https://user-images.githubusercontent.com/33258733/154341299-b10edddf-9b27-4075-ab37-45ecc50f86b1.png">

#### Content Types
* Extrapolated each fieldset into a component `BlogPosts`, `Testimonials`, and `Portfolios`.
* I tried to convert the index from a class to a function but was not successful with the autosave/update feature so I left this as a class.
* Updated support links
<img width="1626" alt="Markup 2022-02-16 at 20 31 05" src="https://user-images.githubusercontent.com/33258733/154341550-329fdc1f-a392-4ab0-8dad-636149a3ced1.png">

#### Masterbar (only in self-hosted Jetpack sites)
* Added section header

#### Media (only in self-hosted Jetpack sites)
* Added section header

#### Publishing Tools
* Updated support links
* Replaced the generic HTML elements with the standardized Form components to make things consistent
* Adjusted section header
<img width="1637" alt="Markup 2022-02-16 at 20 32 00" src="https://user-images.githubusercontent.com/33258733/154341592-bac4933f-8969-4c2c-be66-c217aa246cd9.png">

#### Theme Enhancements
* Changed from class to function component
* Removed unused props
* Updated support links
<img width="1636" alt="Markup 2022-02-16 at 20 29 05" src="https://user-images.githubusercontent.com/33258733/154341085-912db1c4-e187-4c9d-8e74-f0af75fa7f62.png">

#### Widgets
* Removed unused props
* Changed from class to function component

## Testing instructions
* Pull branch and launch calypso with `yarn start`
* Go to Settings ⇢ Writing
* Adjust all settings and options and verify they update correctly
* Visually inspect for errors (there are slight variations due to the update to match styling)
* Click the `( i )` and make sure the link goes to Jetpack links on JPOP only sites and WPCOM for Simple and AT sites
* Repeat this process with each version - Simple, AT, and JPOP site
* I tested side-by-side with the live version. After a change in my test environment, I would refresh my live version to make sure the changes applied to the site settings.

Fixes #59977

2022-02-16 19:44 UTC, a8ci18n commented on client/my-sites/site-settings/theme-enhancements.jsx
> +							"Adds names for CSS preprocessor use, disabling the theme's CSS, or custom image width."
:information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **19** times:
`translate( 'Adds options for CSS preprocessor use, disabling the theme's CSS, or custom image width.' )` *ES Score: 10*

2022-02-25 10:29 UTC, arcangelini commented
Fixed a typo I noticed in a couple of the URLs and rebased it to fix all TeamCity tests. 🤞

2022-02-25 14:24 UTC, alshakero requested changes
Wow nice refactor!

So, I reviewed this. It's a good example of a PR that is pretty hard to review. If you remember us discussing hard reviews, I mentioned migrating to TypeScript as an example of a tough review because it makes git diffing completely useless; git can't tell which line is which, so it just renders two big code blocks; green and red.

Moving components from class to function is quite the similar in that since. It's pretty hard for me to tell apart the logic changes against the janitorial changes.

Janitorial changes should be in their own dummy PR, zero logic change, just doing the single janitorial task; this way I don't review line by line, and I'd trust the author didn't engineer anything new. 

Found two tiny issues.

2022-02-25 14:24 UTC, alshakero commented on client/my-sites/site-settings/custom-content-types/portfolios.jsx
> +						: 'https://jetpack.com/support/custom-content-types/#portfolios'
This link seems incorrect, because `#privacy` will be added to it it will look like this: `#portfolios#privacy`.

2022-02-25 14:24 UTC, alshakero commented on client/my-sites/site-settings/composing/markdown.jsx
> +					siteIsJetpack && ! isAtomic
I'm not sure about this condition. The markdown info has an incorrect privacy link on simple sites.

2022-02-27 14:57 UTC, arcangelini commented
Thanks @alshakero for the tips and patience in reviewing this. I think I have a much better understanding of how to avoid this moving forward and will try to keep this more concise.

I updated the logic and tested every link on a JPOP, Atomic, and Simple site to make sure it all lines up. Everything should be correct now.

2022-03-14 12:49 UTC, alshakero approved these changes
LGTM now.

2022-03-14 13:07 UTC, merged

2022-03-14 15:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7180711

Thank you @arcangelini for including a screenshot in the description! This is really helpful for our translators.

2022-03-24 23:33 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7180711).