Add VideoPress JWT-based auth.
Automattic/wp-calypso pull request #61262
Opened 2022-02-18 18:00 UTC by pgk

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2022-03-31 19:16 UTC, jgcaruso requested changes
Works as described!

Tested with a wpcom simple site and the selected privacy option persists when changed, and the video requests a jwt when privacy is set to `private`.

Just requesting changes because when testing with a Jetpack site the dropdown also appears even though we aren't ready to release this for Jetpack. Left a note about 2 possible places to fix this.

2022-03-31 19:16 UTC, jgcaruso commented on client/post-editor/media-modal/detail/detail-fields.jsx
> +	);
We should stop this from being `true` for jetpack sites until the functionality is enabled there.

We can either fix that here, or in the api endpoint where we add the feature `wp-content/admin-plugins/wpcom-billing/store-product-list.php` line 1275.

2022-04-01 10:56 UTC, pgk commented on client/post-editor/media-modal/detail/detail-fields.jsx
> +	);
Oh nice catch, I think we are better off fixing this at the endpoint

2022-04-01 13:23 UTC, pgk commented on client/post-editor/media-modal/detail/detail-fields.jsx
> +	);
Actually fixing here instead :D

2022-04-01 13:25 UTC, pgk commented
> when testing with a Jetpack site the dropdown also appears even though we aren't ready to release this for Jetpack.

Fixed that and edited the test plan to include that test.

2022-04-01 14:16 UTC, thedebian approved these changes
Working great ! Jetpack site didn't display the checkbox too. Code looks good. :shipit:

2022-04-01 15:36 UTC, merged

2022-04-01 17:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7214398

Hi @pgk, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Site Default`

Thank you in advance!

2022-04-12 10:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7214398).