Stepper Flow: Build the intent capture step
Automattic/wp-calypso pull request #61402
Opened 2022-02-23 09:35 UTC by escapemanuele

#### Changes proposed in this Pull Request

Build the intent capture step

#### Testing instructions

* Checkout branch
* `yarn start`
* Go to `http://calypso.localhost:3000/stepper/intent`

Related to #60810
Fixes #60810

2022-02-23 11:54 UTC, alshakero requested changes
That's pretty good! Left some comments. I think we can start with the CSS now. It would be great if you could make it identical to https://wordpress.com/start/setup-site/intent?siteSlug=SITE_URL&loading_ellipsis=1

2022-02-23 11:54 UTC, alshakero commented on client/landing/stepper/declarative-flow/example-flow.ts
>  };
This file should remain untouched as an example.

Can you create another flow called `siteSetup` please?

2022-02-23 11:54 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/types.ts
> +	goToPage: ( page: StepPath ) => void;
```suggestion
	goToStep: ( step: StepPath ) => void;
```

2022-02-24 11:29 UTC, arcangelini reviewed
Everything is working for me. I had two thoughts that I don't think apply to the actual step but more to the component.

1. In the name change PR the `intent-screen.tsx` became `onboarding-component.tsx` is this correct? Or should it actually be `intent-screen.tsx` because that is the component its exporting.
2. Will there always be a need for `SelectAltItem` or would it be beneficial to make this optional?

2022-02-24 11:29 UTC, arcangelini commented on client/landing/stepper/declarative-flow/internals/steps-repository/build.tsx
> +			<h1>Domains step</h1>
I know this is just a placeholder, but I think this should be: `<h1>Build step</h1>`

2022-02-24 18:00 UTC, alshakero approved these changes
Looks perfect! Addressed some issues directly to save time.

2022-02-24 18:05 UTC, merged