Disable domain actions for domains at auction
Automattic/wp-calypso pull request #61479
Opened 2022-02-25 10:40 UTC by gius80

## Changes proposed in this Pull Request

This PR disables some actions for domain in aftermarketAuction state.

You can apply this patch in your sandbox to get a domain in auction (D75409-code).

| ![settings](https://user-images.githubusercontent.com/2797601/155700217-c0a59619-7bdc-4dc4-a72a-9289974f761e.png) |
|:--:|
| <b>Domain settings</b> |

| ![transfer](https://user-images.githubusercontent.com/2797601/155700225-0d20595e-4d97-4de4-b520-6a09f5fb6c8b.png) |
|:--:|
| <b>Transfer page</b> |

| ![transfer-to-other-site](https://user-images.githubusercontent.com/2797601/155700239-089a0e73-dfb0-4023-9640-716271b75176.png) |
|:--:|
| <b>Transfer to another site</b> |

| ![transfer-to-other-user](https://user-images.githubusercontent.com/2797601/155700256-26a8deb0-8c4e-484a-b901-2deb411d4b80.png) |
|:--:|
| <b>Transfer to another user</b> |

## Testing instructions

- Build this branch locally or open the live Calypso link
- Select a domain that has `aftermarketAuction` property set to `true`
  - In _Settings page_, verify that the Renew button and the Auto-renew toggle are not displayed
  - In _Settings page_, verify that the transfer card (right column) is not displayed
  - In _Transfer page_, verify that the notice is displayed
  - In _Transfer page_ (to another user), verify that the notice is displayed
  - In _Transfer page_ (to another site), verify that the notice is displayed

2022-03-03 23:48 UTC, leonardost requested changes, later dismissed
LGTM, tested and works as expected!
There's only one auto-renew toggle in the domains list that I believe we should hide before shipping this:
![Markup on 2022-03-03 at 20:41:17](https://user-images.githubusercontent.com/5324818/156672287-3fad7781-d0ba-4b68-b95a-f25fe3d334a0.png)

2022-03-04 09:02 UTC, gius80 commented
> LGTM, tested and works as expected!
There's only one auto-renew toggle in the domains list that I believe we should hide before shipping this:

Good catch! Thanks! 😉

2022-03-04 17:11 UTC, delputnam approved these changes
Changes LGTM. 👍

2022-03-07 08:24 UTC, merged

2022-03-07 10:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7170614

Thank you @gius80 for including a screenshot in the description! This is really helpful for our translators.

2022-03-18 10:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7170614).