Writing Settings: Hide infinite scroll toggle if theme does not support it
Automattic/wp-calypso pull request #61624
Opened 2022-03-02 19:43 UTC by jeyip

Calypso would always display the infinite scroll setting, regardless of whether or not the theme actually supported infinite scroll. We refactored underlying code to evaluate theme tags before rendering an infinite scroll toggle.

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to https://github.com/Automattic/wp-calypso/issues/61202

2022-03-04 18:14 UTC, creativecoder requested changes
While testing, I'm seeing cases of the Infinite Scroll toggle not show up, even when it's should because the theme supports it.

This seems to be because the redux store doesn't yet have the theme data for checking the tags. You should be able to replicate this by clearing Calypso's state cache (in IndexDB) and then going directly to `/settings/writing/{site}`.

So I think we need to preload the current theme in the Settings > Writing page to make this work in all cases. Adding the `<QueryCanonicalTheme />` component might do it, but I haven't looked closely.

2022-03-04 18:48 UTC, creativecoder commented
One slight concern I have with this approach is if there are users are used to looking for this setting, and then it's disappears, they may wonder what happened and then think something is broken...

but if we're not going to be adding infinite scroll support for our newer themes, do think it's better to remove the setting when it doesn't work, and normalize this being a deprecated feature.

---

Another thing we need to think about: Atomic sites may have themes that support infinite scroll but don't have the theme tag.
[The Jetpack documentation](https://jetpack.com/support/infinite-scroll/) points to using `add_theme_support` to register the feature, and non-WP.com themes that use it (I don't know if there are any) may not have added the theme tag.

I think this means we either need to

- Use theme supports detection to trigger hiding or showing the infinite scroll feature (unfortunately I don't see an easy way to get at the theme support features within Calypso, doing a quick search, without adding it to an API endpoint), OR
- Leave the Jetpack settings alone (at least for now), and have them always display, in case the theme supports the feature.

2022-03-04 19:59 UTC, jeyip commented
> but if we're not going to be adding infinite scroll support for our newer themes, do think it's better to remove the setting when it doesn't work, and normalize this being a deprecated feature.

That's the impression I got from themes folks.

> Another thing we need to think about: Atomic sites may have themes that support infinite scroll but don't have the theme tag.
[The Jetpack documentation](https://jetpack.com/support/infinite-scroll/) points to using add_theme_support to register the feature, and non-WP.com themes that use it (I don't know if there are any) may not have added the theme tag.

That's a great point. Thanks for bringing this up 🙏 

> I think this means we either need to

> - Use theme supports detection to trigger hiding or showing the infinite scroll feature (unfortunately I don't see an easy way to get at the theme support features within Calypso, doing a quick search, without adding it to an API endpoint), OR
> - Leave the Jetpack settings alone (at least for now), and have them always display, in case the theme supports the feature.

Totally agree. I'll take a closer look soon.

2022-03-11 20:10 UTC, jeyip commented
@creativecoder I'm planning to leave the jetpack settings alone to get this fix out sooner rather than later, even if only for a subset of users.

Then I'll immediately circle back with investigation and work on a new API endpoint, at which point we'll be able to disable the jetpack settings accordingly. Let me know if that sounds good.

2022-03-17 23:51 UTC, jeyip commented
I found an existing endpoint for theme supports on dotcom `wp-content/rest-api-plugins/endpoints/sites-theme-support.php`. I'm investigating now @creativecoder

2022-03-19 02:18 UTC, jeyip commented
@creativecoder 

I'm testing theme supports and I'm seeing that on a jetpack enabled site, if the theme does not support infinite scroll, then the `infinite-scroll` theme support will always be false, regardless of what option a user selects.

This can be verified by doing the following:
1. Enable a theme without infinite scroll support on a jetpack site ( Ex. twentytwentytwo )
2. Navigate to `wp-content/rest-api-plugins/endpoints/sites-theme-support.php` in the dotcom codebase
3. Add the `infinite-scroll` theme support query to the endpoint response

```
$result[ 'theme_support' ] = array(
	'align-wide' => get_theme_support( 'align-wide' ),
	'gutenberg'  => get_theme_support( 'gutenberg' ),
	'infinite-scroll' => get_theme_support( 'infinite-scroll' ),
);
```

4. Sandbox the public API
5. Navigate to https://developer.wordpress.com/docs/api/console/ and select `WP REST API` and `wpcom/v2` from the respective dropdown menus
6. Execute a GET request at `/sites/{$your_jetpack_site_slug}/theme-support`
7. Verify that, no matter which infinite scroll setting you select, the infinite-scroll theme support is always false
8. Enable a theme with infinite scroll support ( Ex. Dara )
9. Execute another GET request
10. Verify that the infinite scroll support is no longer false

There are a few conclusions I'm drawing from this. 
- It appears as if the jetpack infinite scroll setting is misleading
- We can safely rely on either the infinite scroll theme support or infinite scroll theme tag to conditionally hide the setting

2022-03-22 19:42 UTC, creativecoder commented
> There are a few conclusions I'm drawing from this. It appears as if the jetpack infinite scroll setting is misleading. It won't enable any theme support unless the given theme also supports infinite scrolling. We can safely rely on either the infinite scroll theme support or infinite scroll theme tag to conditionally hide the setting.

Thanks for persisting with this @jeyip. That all sounds right to me. I think the theme supports flag is our best indicator, as the theme may or may not have the correct tag if it's from the dotorg repo. I don't see any reason the Calypso setting for infinite scroll should be showing at all if no theme support is registered for it.

My understanding is that all themes on Simple sites used to support infinite scrolling, which is probably why this setting is always visible. But that's definitely not true any longer.

2022-03-31 20:23 UTC, jeyip commented
> Thanks for persisting with this @jeyip. That all sounds right to me. I think the theme supports flag is our best indicator, as the theme may or may not have the correct tag if it's from the dotorg repo.

@creativecoder Makes sense to me 👍 I created a phab diff to include the infinite-scroll support in the theme supports endpoint D77958-code. When it's merged, we can update this PR to conditionally display the infinite scroll toggle based off the endpoint response.

2022-04-15 00:53 UTC, jeyip commented
@creativecoder This is ready for review again

2022-04-18 19:44 UTC, creativecoder reviewed
In testing, unfortunately this still isn't working as intended, here's what I found

- Atomic/Jetpack sites never see infinite scroll settings
- Some themes that support infinite scroll aren't showing the settings

---

It looks like there are 2 things that need to be addressed.

First, the API change in D77958-code only returns the correct data for Simple sites, since wpcom has no direct knowledge of the Jetpack/Atomic site's theme code.

I looks like the endpoint to use is `public-api.wordpress.com/wp/v2/sites/{site}/themes?status=active`, which provides the list of theme supports for the current theme, and works for both Simple and Jetpack sites.

Second, I think we need to check both theme tags and theme supports for infinite-scroll. Browsing around our wpcom themes code, I don't see any consistency. Some use a tag, some register theme support, and some do both, some seem to use neither but still  support the feature 🤯.

(Ideally we'd update the theme code to be correct, but sadly that doesn't seem worth the effort at this point).

2022-05-26 16:22 UTC, jeyip commented
We're currently prioritizing work on integrating google fonts with dotcom. Will return to this when more time frees up. https://github.com/Automattic/themes/pull/6010

2023-04-03 17:21 UTC, jeyip commented
closing this for now -- will reopen when we we're able to reprioritize the issue

2023-04-03 17:21 UTC, closed without merging