Fixed CSS margins for the Jetpack notice banner
Automattic/wp-calypso pull request #61765
Opened 2022-03-09 13:48 UTC by paulopmt1

#### Changes proposed in this Pull Request

* Fixed Jetpack notices spacing:

![Screenshot 2022-02-16 at 15-23-36 Plugins ‹ test — WordPress com](https://user-images.githubusercontent.com/811776/154195867-a1c411a4-6be8-4113-bf8d-b740ff9ae392.png)

#### Testing instructions

1. Open the plugin screen with a Jetpack (non atomic) site, likely needs a free plan. [Jurassic.ninja](https://jurassic.ninja/) sites work. You should see the top spacing between Jetpack notice banner and Header:

![image](https://user-images.githubusercontent.com/1044309/157453681-16fdbe6d-2f4f-46b6-8301-622a1ba0e45b.png)

The space should match our other notices:

![Screenshot 2022-02-16 at 16-38-22 Plugins ‹ test — WordPress com](https://user-images.githubusercontent.com/811776/154203104-5098aee9-ab9e-434c-a8ba-0fc6ca8ac53e.png)

2. Please test on mobile too. You should see the following result:

![image](https://user-images.githubusercontent.com/1044309/157453995-e08103d4-200e-499c-8e97-63db3324d959.png)

Related to https://github.com/Automattic/wp-calypso/issues/61142

2022-03-09 15:40 UTC, WBerredo requested changes
Is it possible to also check the distance from the Jetpack banner to the section title (new, featured)?

It seems to be a bigger distance than the other notices.

2022-03-09 17:08 UTC, paulopmt1 commented
Good catch @WBerredo!

Now it's fixed, please check if it looks good to you:

Mobile:

![image](https://user-images.githubusercontent.com/1044309/157492783-1eed622f-0f1a-452b-8804-d9e343d5e18f.png)

Desktop:

![image](https://user-images.githubusercontent.com/1044309/157493198-7dd92093-b281-4dfd-9cf7-49ffa2a8d1cb.png)

2022-03-09 17:32 UTC, WBerredo approved these changes
Thanks for the changes.

LGTM 🚀

2022-03-09 19:23 UTC, merged

2022-10-07 08:51 UTC, tyxla commented
Just wanted to point out that when targeting components that exist throughout the entire app, it's a good idea to be careful about where we intend to introduce the changes. 

In this case, we wanted to introduce them just to the plugins section, but unintentionally, we did it everywhere. So when someone loads the plugins section, the additional styles would be loaded and the upsell nudge would end up broken for any subsequent route.

The way to address this is to assess where we want to apply the changes, and then reflect that specificity in the corresponding stylesheet.

Seems like this has been partially broken for over half a year 😅 I've filed a fix in https://github.com/Automattic/wp-calypso/pull/68744, but just wanted to give y'all a heads up.

2022-10-07 13:28 UTC, allilevine commented
> Seems like this has been partially broken for over half a year 😅 I've filed a fix in #68744, but just wanted to give y'all a heads up.

Thanks @tyxla! We'll keep this in mind for future CSS targeting.

2022-10-07 13:59 UTC, paulopmt1 commented
Thanks for fixing it and the description @tyxla! I'll keep this in mind for future CSS changes.