[WIP] Plugins: Use Breadcrumb component from Domains
Automattic/wp-calypso pull request #61851
Opened 2022-03-11 15:35 UTC by epeicher

The Breadcrumb will be taken from the Domains component and it will be
added to generic components and used it in other areas.

Remaining things to do:
- [ ] Use the common component in all the domains code
- [ ] Ensure the compact functionality works as expected
- [ ] Decide if using external styles or styled components

#### Changes proposed in this Pull Request

* TBD

#### Testing instructions

* TBD

Fixes #61143

2022-03-16 10:02 UTC, cpapazoglou requested changes
Thanks for working on this @epeicher. The changes seem working in the Plugin pages

Some notes regarding UI/UX:
1. There unwanted padding to the left and a border
![CleanShot 2022-03-16 at 10 50 22@2x](https://user-images.githubusercontent.com/12430020/158552228-409930d2-90b4-4847-9e46-a7e3df6dcc8a.png)

2. Mobile breakpoint is triggered to late, causing the header to be cramped 
<img width="842" alt="CleanShot 2022-03-16 at 10 54 41@2x" src="https://user-images.githubusercontent.com/12430020/158552888-6a3625af-12b8-4396-a84d-399844000dd3.png">
can we use the breakpoint `breadcrumb` originally used for just showing `Back`?

3. Search results has no link. The same happens if you follow another category first like clicking "Browse All" in Premium plugins.
![CleanShot 2022-03-16 at 10 56 39@2x](https://user-images.githubusercontent.com/12430020/158553292-878065dc-3122-4e40-ae4f-944e09f56293.png)

I also left some comments regarding the code.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/fixed-navigation-header/index.tsx
> +				<Breadcrumb items={ navigationItems } mobileItem={ mobileItem } />
`compact` was used to handle **when** the breadcrumb should show the `mobileItem`. This was dictated by the page rather than the `breadcrumb` component because each page might have different amount of header components taking up space and thus needing to fallback to `mobile` earlier.

https://github.com/Automattic/wp-calypso/blob/4114fcd7a30c10b9c02fecf25a84512236c3cdb9/client/my-sites/plugins/plugins-browser/index.jsx#L283

Doing so, we could have avoided cases like this (already in production)
![CleanShot 2022-03-16 at 11 09 47@2x](https://user-images.githubusercontent.com/12430020/158555739-20824b4f-af84-4b91-b20f-40b4e24f2304.png)

I believe that by making `mobileItem` optional and only adding it in breakpoints dictated by the page will solve that problem.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/fixed-navigation-header/index.tsx
> +	}
Thanks for trying to handle it in an abstract - automated way but `FixedNavigationHeader` should neither have an _opinion_ for the breadcrumbs nor use `useTranslate` thus making it a not pure component https://medium.com/technofunnel/working-with-react-pure-components-166ded26ae48

Also, there is already logic for adding specific `mobileItem` from the domain pages themselves

https://github.com/Automattic/wp-calypso/blob/af49fc7325532c45020fc629b68d5fb90d531e2d/client/my-sites/domains/domain-management/dns/add-dns-record.jsx#L66-L72

I think we can totally remove this, and manage it on the page level

https://github.com/Automattic/wp-calypso/blob/4114fcd7a30c10b9c02fecf25a84512236c3cdb9/client/my-sites/plugins/main.jsx#L439-L441

https://github.com/Automattic/wp-calypso/blob/4114fcd7a30c10b9c02fecf25a84512236c3cdb9/client/my-sites/plugins/plugin-details.jsx#L246

https://github.com/Automattic/wp-calypso/blob/4114fcd7a30c10b9c02fecf25a84512236c3cdb9/client/my-sites/plugins/plugins-browser/index.jsx#L280-L284

https://github.com/Automattic/wp-calypso/blob/366b921bfeb3f93b537dab584cf2c2c19dc4f2b8/client/my-sites/woocommerce/landing-page.tsx#L157

Perhaps, passing a single `breadcrumb` object to the `FixedNavigationHeader` rather than multiple breadcrumb related props.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/style.scss
> +	display: none;
It seems that the breakpoints are used here to `show` and `hide` elements in which case we can utilise `isWithinBreakpoint` in JS to render or not the component rather than depending on CSS.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/style.scss
> +}
we can remove this since it's not used in the component and also doesn't make sense dictating the space around a component from within the component.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/index.tsx
> +			<div>
Let's try removing that `div` wrapper.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/index.tsx
> +				<div className="breadcrumb__content">
Let's try removing that `breadcrumb__content` wrapper.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/index.tsx
> +				</div>
Buttons should not be part of the `Breadcrumb`. Buttons can be dictated by the page and render themselves in an `ActionsContainer` in the `FixedNavigationHeader`.

https://github.com/Automattic/wp-calypso/blob/376ae1b1f4199ca3585ca6fbf349a52d75af2d23/client/components/fixed-navigation-header/index.tsx#L119

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/index.tsx
> +				{ renderBackArrow() }
```suggestion
				{ mobileItem.showBackArrow && mobileItem.href && (
					<a className="breadcrumb__item" href={ mobileItem.href }>
						<Icon className="breadcrumb__back-arrow" icon={ chevronLeft } size={ 20 } />
					</a>
				) }
```

I wonder if inlining would help with readability and avoid us using extraneous functions.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/style.scss
> +}
As noted, `FixedNavigationHeader` should correctly render the buttons.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/index.tsx
> + */
All that info should be moved in the README.

2022-03-16 10:02 UTC, cpapazoglou commented on client/components/breadcrumb/index.tsx
> +					<Icon className="breadcrumb__back-arrow" icon={ chevronLeft } size={ 20 } />
Let's use `Gridicon` over `Icon` or at least one of these components.

2022-03-16 13:11 UTC, epeicher commented
Thank you very much for your comments @cpapazoglou! I am going to address all of them in the following changes so I will not reply to each comment individually.

The approach of the `Domains` component used does not seem to work here according to your comments so I am going to re-write the component based on the original `Plugins` code and apply the `Domains` UI styles from domains on top.

2022-03-16 17:05 UTC, epeicher commented on client/components/breadcrumb/index.tsx
> +					<Icon className="breadcrumb__back-arrow" icon={ chevronLeft } size={ 20 } />
After trying to use `Gridicon` here I have identified that I cannot use the same pixels as they are different icons. Are we happy with this result?
![CleanShot 2022-03-16 at 18 02 53@2x](https://user-images.githubusercontent.com/3519124/158646950-3140f80d-a9de-48a1-97bc-ae6235e20918.png)

2022-03-17 10:47 UTC, epeicher commented
@cpapazoglou Please note that the subsequent changes have been done in the following PR
- #61995

So please review the changes there and we will close this PR after emerging the linked one #61995

2022-03-18 12:32 UTC, epeicher commented
Done as part of
- https://github.com/Automattic/wp-calypso/pull/61995

2022-03-18 12:32 UTC, closed without merging