Emails: Show suspended account on suspended Professional Email accounts
Automattic/wp-calypso pull request #61910
Opened 2022-03-14 13:30 UTC by AllTerrainDeveloper

#### Changes proposed in this Pull Request

This pull request adds a small error icon when there is any email account suspended for Professional Email.
I am setting this as a draft as I would like to know if we should keep allowing the user to Add new mailboxes/manage them. If so I will grey out/remove those options.

#### Testing instructions

Checkout locally this branch
Have (or create) Professional Email subscription
Sandbox your public api
Open your sandbox and look for your account using wpsh. You can create a Titan manager instance, then look for the account by its domain name.
Then update the account status to suspended.
Check that you see those error notices in the email management section and also in the emails Home Screen.

| Emails home  | Email management |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/5689927/158181655-6659da50-2287-4cb7-9044-2599bed9a21e.png) | ![image](https://user-images.githubusercontent.com/5689927/158181545-d60a9db3-8bef-42d9-b877-0ea4e28427ed.png) |

Related to {1198996432807005-as-1201373094310942}

2022-03-14 17:17 UTC, stephanethomas commented on client/lib/titan/is-suspended-account.ts
> +}
I wonder if we shouldn't call that selector `isSubscriptionSuspended()` since it actually looks at the status of the subscription.

2022-03-15 08:28 UTC, AllTerrainDeveloper commented on client/lib/titan/is-suspended-account.ts
> +}
You are right, I named it based on the task description. But it makes a lot of sense to call it `isSubscriptionSuspended()`

2022-03-15 08:45 UTC, AllTerrainDeveloper commented
Now I am raising the question here, @stephanethomas agreed with me via Slack about removing some options if the user has the subscription suspended.

![image](https://user-images.githubusercontent.com/5689927/158338651-9b646179-36a6-4d86-9e98-e5cd24e153ea.png)

I can't see where we set the account to suspended, seems to me that we are not setting it in a regular or normal flow, so I can't really know which actions the user should take if the account is suspended. @daledupreez mentioned that one of the reasons is expiry date, but I can't even see that looking into wpcom.

2022-03-15 08:54 UTC, stephanethomas requested changes
I've got two concerns with those changes. First, we don't provide a way for users to act on this issue: how can they make their email account active again? Ideally, we should show a message (explaining why their account is suspended) and a CTA on the `Email Plan` page - like we do for Google Workspace (when a user hasn't accepted the ToS yet):

![image](https://user-images.githubusercontent.com/594356/158340303-8f2aeba5-bbb0-4c3e-a99a-00ec663f689c.png)

And second, we should implement the same logic for Google Workspace.

As an aside, we should prevent users from adding new mailboxes if an account is suspended but this is something that we can tackle in another round.

2022-03-15 08:54 UTC, stephanethomas commented on client/lib/titan/is-subscription-suspended.ts
> +}
I think we could probably refer to Titan in the name of this selector like we do for other selectors, e.g. `isTitanSubscriptionSuspended`.

2022-03-15 08:54 UTC, stephanethomas commented on client/my-sites/email/email-management/home/utils.js
> +				text: translate( 'Suspended account' ),
This doesn't match your screenshots, and should be `Account suspended`.

2022-03-15 12:58 UTC, AllTerrainDeveloper commented
@stephanethomas I've solved the renaming suggestions, but is not clear to me if the other changes should be done in this PR or in a follow up

2022-03-15 13:34 UTC, stephanethomas commented
> but is not clear to me if the other changes should be done in this PR or in a follow up

We can leave Google Workspace for another pull request but we should implement the message and CTA in this one. By the way, I think we may change the error message shown on the `Emails` page from `Account Suspended` to `Action Required` because of this CTA.

2022-03-18 16:00 UTC, AllTerrainDeveloper commented
I think we need to add the warning via server side to correctly show the CTA, and be aligned with how the rest of the warnings are displayed (because they are added via backend). I've added the needed code for it, but it won't show up any code until we add the needed code in the backend.

2023-09-22 09:42 UTC, closed without merging