Added Tracks events to design picker upgrade buttons
Automattic/wp-calypso pull request #62140
Opened 2022-03-22 18:19 UTC by nelsonec87

#### Changes proposed in this Pull Request

Added Tracks events to design picker upgrade buttons:
- `calypso_design_picker_grid_upgrade_button` for the grid button
- `calypso_design_picker_preview_upgrade_button` for the preview page button

#### Testing instructions

I'm not sure what's the best way to test it since the design picker is only showing Free themes.
What I did was hard code `true` to the `shouldUpgrade` variable, so the "Upgrade" button would show instead of the "Start with" button.
After going through the flow, upgrading, and waiting a few minutes, it's possible to see the events on Tracks Live page.
![image](https://user-images.githubusercontent.com/3801502/159549000-b5219870-2a5a-4415-bad8-e63d996910c6.png)

Closes #62074

2022-03-22 21:01 UTC, sixhours requested changes
I tested this by going to the Build flow rather than the Sell flow; we show all the themes there, and the events fire as expected. 🥳 

This looks like a good start! I would update the event names to follow the Tracks naming guidelines in the FG and for consistency with other events on the design step: PCYsg-4S2-p2

For additional props, it would be helpful to include the user's `intent` as well (`sell`, `write`, `build`). Eventually I expect we'll have some premium themes in the `sell` intent, too. :) 

You should be able to see these events firing in your browser console using `localStorage.debug="calypso:analytics*"`; there's some discussion about getting it working in Slack right now in case you run into trouble: p1647973955970369-slack-C0Q664T29

2022-03-22 21:01 UTC, sixhours commented on client/signup/steps/design-picker/index.jsx
> +		recordTracksEvent( 'calypso_design_picker_grid_upgrade_button', {
The FG has naming conventions for new Tracks events: PCYsg-4S2-p2 

For consistency with other signup events, this should end with an action (ie. `_click`), something like `calypso_signup_design_upgrade_button_click`

2022-03-22 21:01 UTC, sixhours commented on client/signup/steps/design-picker/index.jsx
> +		recordTracksEvent( 'calypso_design_picker_preview_upgrade_button', {
Similarly, this could be`calypso_signup_design_preview_upgrade_button_click`

2022-03-22 21:01 UTC, sixhours commented on client/signup/steps/design-picker/index.jsx
> +			theme: design?.theme,
Nitpick, I would use `design` rather than `theme` as the key here since we've used the same terminology for other Tracks event props in signup.

2022-03-22 21:01 UTC, sixhours commented on client/signup/steps/design-picker/index.jsx
> +			theme: design?.theme,
Same for this, `design` as the key rather than `theme` for consistency with other Tracks events.

2022-03-23 07:55 UTC, arthur791004 commented
> I'm not sure what's the best way to test it since the design picker is only showing Free themes.

The design picker also shows premium themes such as “Alonso”
![image](https://user-images.githubusercontent.com/13596067/159650248-5720abe0-a1ad-424b-9783-f2238304503f.png)

2022-03-23 07:59 UTC, arthur791004 commented on client/signup/steps/design-picker/index.jsx
> +			theme: design?.theme,
In the design picker, we have already had `getEventPropsByDesign` function to collect props we want, so we could just use that function to keep the properties consistent.

2022-03-23 08:01 UTC, arthur791004 commented on client/signup/steps/design-picker/index.jsx
> +		recordTracksEvent( 'calypso_design_picker_grid_upgrade_button', {
Agree 👍

2022-03-23 08:08 UTC, arthur791004 commented on client/signup/steps/design-picker/index.jsx
> +			theme: design?.theme,
Hmmm...AFAIK we use `theme` as the key in design picker for a long time 🤔

2022-03-23 12:00 UTC, nelsonec87 commented on client/signup/steps/design-picker/index.jsx
> +		recordTracksEvent( 'calypso_design_picker_grid_upgrade_button', {
👍

2022-03-23 12:00 UTC, nelsonec87 commented on client/signup/steps/design-picker/index.jsx
> +		recordTracksEvent( 'calypso_design_picker_preview_upgrade_button', {
👍

2022-03-23 12:04 UTC, nelsonec87 commented on client/signup/steps/design-picker/index.jsx
> +			theme: design?.theme,
I ended up (re)using the `getEventPropsByDesign` function. It's the same used by the `submitDesign` and `previewDesign` events. It gets theme information, flow and intent.

2022-03-23 12:05 UTC, nelsonec87 commented
> The design picker also shows premium themes such as “Alonso” 

I've been working with the sell intent for some time, I was blind to the other intents! 🤦‍♂️

2022-03-23 12:06 UTC, nelsonec87 commented on client/signup/steps/design-picker/index.jsx
> +			theme: design?.theme,
Same as the other event :)

2022-03-23 13:36 UTC, sixhours commented on client/signup/steps/design-picker/index.jsx
> +			theme: design?.theme,
> Hmmm...AFAIK we use theme as the key in design picker for a long time 🤔

Ahh, I was seeing `selected_design` in the props, for example. But using `getEventPropsByDesign` makes more sense, so whatever comes with that is 👌

2022-03-23 13:41 UTC, sixhours approved these changes
Works a charm!
<img width="1584" alt="Screen Shot 2022-03-23 at 9 41 15 AM" src="https://user-images.githubusercontent.com/2124984/159713136-e390a20d-399c-4b30-b772-8dc252d0debc.png">
<img width="1512" alt="Screen Shot 2022-03-23 at 9 40 34 AM" src="https://user-images.githubusercontent.com/2124984/159713138-a3eb9490-8747-4eda-8f8b-469bb6ffb63b.png">

2022-03-23 19:28 UTC, merged

2022-03-24 04:05 UTC, arthur791004 commented
Nice 👍