Document stepper
Automattic/wp-calypso pull request #62219
Opened 2022-03-24 16:13 UTC by alshakero

#### Changes proposed in this Pull Request

This documents the changes in this [PR](https://github.com/Automattic/wp-calypso/pull/61732).

2022-03-25 14:58 UTC, escapemanuele requested changes
Great description of the framework! Only a few changes to make and then we can ship that!

2022-03-25 14:58 UTC, escapemanuele commented on client/landing/stepper/README.md
> +It has been tricky for us to create flows that input-driven steps. Stepper makes it easy by allowing flows to create their own two hooks `useSteps`, and `useStepNavigation`. These hooks have access t
`create flows that` ... `input-driven steps`: missing something
`to the state of of the flow`: double of

2022-03-25 14:58 UTC, escapemanuele commented on client/landing/stepper/README.md
> +		return { goNext, goBack, goToStep };
goToStep is not defined in the example

2022-03-25 14:58 UTC, escapemanuele commented on client/landing/stepper/README.md
> +1. **Small API**: when steps have such little API surface area. They can be reused easily.
API surface area, they can

2022-03-25 14:58 UTC, escapemanuele commented on client/landing/stepper/README.md
> +When creating new code, it's highly-encouraged to put it packages, whether existing like `onboarding` or new packages that you create. This allows us to create flows in the future that live in wp-adm
put it _into_ packages

2022-03-25 15:15 UTC, escapemanuele commented on client/landing/stepper/README.md
> +The stepper framework is a new framework for quickly spinning up sign up flows. It's meant to make non-linearly easy without sacrificing agility ✨.
Maybe `non-linearity`?

2022-03-25 15:53 UTC, arcangelini approved these changes
Just some nit-picky comments and suggestions. Great work on this.

2022-03-25 15:53 UTC, arcangelini commented on client/landing/stepper/README.md
> +<img src="https://user-images.githubusercontent.com/17054134/159939643-4a3a7893-ab38-4223-ba5d-5dfe64282f07.png" alt="Stepper logo" width="400">
Haha I love the logo 👍 👍

2022-03-25 15:53 UTC, arcangelini commented on client/landing/stepper/README.md
> +The stepper framework is a new framework for quickly spinning up sign up flows. It's meant to make non-linearly easy without sacrificing agility ✨.
```suggestion
The stepper framework is a new framework for quickly spinning up sign-up flows. This is a non-linear solution that doesn't sacrifice agility ✨. 
```

This is a bit wordy and doesn't read well. Just a suggestion.

2022-03-25 15:53 UTC, arcangelini commented on client/landing/stepper/README.md
> +Steps shouldn't have any props other than `navigation` prop which contains the return value of `useStepNavigation`. This object (`navigation`) allows the step to `submit` when done or to move to othe
```suggestion
Steps shouldn't have any props other than the `navigation` prop which contains the return value of `useStepNavigation`. This object (`navigation`) allows the step to `submit` when done or to move to other steps or to `goNext`, `goBack`, etc..
```

I think this needs a 'the'

2022-03-25 15:53 UTC, arcangelini commented on client/landing/stepper/README.md
> +All the state should be either the onboarding store, or in the internal state of the step. This creates a flat data tree that is exactly one level deep. This allows the steps to be easy to make and t
```suggestion
All the state should be either in the onboarding store or the internal state of the step. This creates a flat data tree that is exactly one level deep and allows steps to be easily created and re-used.
```

Another wording suggestion.

2022-03-25 15:53 UTC, arcangelini commented on client/landing/stepper/README.md
> +
```suggestion

To maintain the reusability and simplicity of this framework it is important that flow-specific styling changes be made to a `flow` stylesheet or in `global.scss`. Each step should have the basic styling necessary to operate on its own just like a package.
```

Maybe best to add something about styling as well?

2022-03-28 20:43 UTC, merged

2022-03-28 20:43 UTC, alshakero commented
Thanks a lot guys! Perfect feedback.