Update/plugin details available on sites
Automattic/wp-calypso pull request #62353
Opened 2022-03-29 20:32 UTC by WBerredo

#### Changes proposed in this Pull Request

* Show on "available on" sites only sites which eligible plans
* Add a new section on Plugin Details for sites that needs an upgrade

#### Testing instructions
* Set a site as atomic but without a business or e-commerce plan
* Go to a Markeplace Plugin Details page: Ex: `/plugins/woocommerce-subscriptions`
* See if the plugin appears on the list called *Upgrade needed*
* Click on `Upgrade and activate`
* See if the following items where added to the cart: The selected plugin and a business plan.

#### Demo
| Plugin Details  | Cart |
| ------------- | ------------- |
|<img width="1231" alt="Screen Shot 2022-03-29 at 15 57 12" src="https://user-images.githubusercontent.com/5039531/160701551-1da4db55-0446-4873-be08-8a406aa25679.png">|<img width="558" alt="Screen Shot 2022-03-29 at 16 18 19" src="https://user-images.githubusercontent.com/5039531/160701589-c9e2bb8a-88fa-4aef-9a27-87a615ee3bce.png">|

---
Fixes #61522

2022-03-30 09:32 UTC, epeicher approved these changes
I have tested and it works as advertised.

LGTM!

2022-03-30 09:44 UTC, epeicher commented
In a different scenario, when a **site is selected** without a business or e-commerce plan and the user clicks on _`Purchase and activate`_ on a Premium plugin, the same message described in https://github.com/Automattic/wp-calypso/issues/61522 is displayed:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/3519124/160801946-d0a377c5-5a00-4235-bab2-35f94542120c.png">



Is that expected behaviour?

2022-04-04 11:53 UTC, epeicher commented
I have tested and I have found one unexpected scenario. I have an eCommerce site that should be listed in the `Available on` list but it is not in the first load. When I click on `Upgrade and activate` for that site and then cancel the checkout. The item is correctly listed. Please see video below:

https://user-images.githubusercontent.com/3519124/161537572-6a39a2e3-ce80-475a-8047-4f8774954ddc.mp4

After looking at the code, it seems that the `state.sites.features` [read in the following selector](https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/state/selectors/get-site-features.js#L8-L9) are not correctly populated in the first load but they are populated in following loads of the screen. 

More investigation is required to find the root cause

2022-04-04 11:56 UTC, epeicher requested changes
The `availableOnSites` field does not seem to be correct in the first load. Please see [this comment](https://github.com/Automattic/wp-calypso/pull/62353#issuecomment-1087460821) for further details.

2022-04-04 13:05 UTC, WBerredo commented
@epeicher you are right, this PR depends on #62472 as mentioned in the description. Sorry for not making it clearer.

2022-04-07 09:36 UTC, gcsecsey requested changes
> In a different scenario, when a site is selected without a business or e-commerce plan and the user clicks on Purchase and activate on a Premium plugin, the same message described in https://github.com/Automattic/wp-calypso/issues/61522 is displayed:

I've also tested both scenarios, and haven't received any errors, but found some differences. When checking out, different plans get added to the cart next to the product:
 
| Checking out from all sites view | Checking out from selected site |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/11555574/162168980-b77220fe-18e2-4192-88a0-9a7304a97c2c.png) | ![image](https://user-images.githubusercontent.com/11555574/162168767-df5abd84-c8de-4e33-b2e6-6b9d3252b311.png) |

> After looking at the code, it seems that the state.sites.features [read in the following selector](https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/state/selectors/get-site-features.js#L8-L9) are not correctly populated in the first load but they are populated in following loads of the screen.

I've cherry-picked the commit from #62472 onto this branch, and as @WBerredo mentioned before, that solves this issue, the list looks OK on the first load:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/11555574/162169377-42ff024e-7aeb-491a-96d6-23c4e4313601.png">

2022-04-07 09:36 UTC, gcsecsey commented on client/my-sites/plugins/plugin-install-button/index.jsx
> +			  ) },${ product_slug }?redirect_to=/marketplace/thank-you/${ plugin.slug }/${
To add the correct plan on every checkout, just like in `plugin-details-CTA/index.jsx`, I think we should add the `eligibleForProPlan` selector and param here:
```suggestion
			: `/checkout/${ selectedSite.slug }/${ businessPlanToAdd(
					selectedSite?.plan,
					billingPeriod,
					eligibleForProPlan
			  ) },${ product_slug }?redirect_to=/marketplace/thank-you/${ plugin.slug }/${
```

2022-04-07 14:25 UTC, WBerredo commented on client/my-sites/plugins/plugin-install-button/index.jsx
> +			  ) },${ product_slug }?redirect_to=/marketplace/thank-you/${ plugin.slug }/${
You are right, we actually already solved this issue on trunk but as this PR is quite old it is not solved here yet. Thanks for pointing this.

2022-04-07 15:01 UTC, WBerredo commented on client/my-sites/plugins/plugin-install-button/index.jsx
> +			  ) },${ product_slug }?redirect_to=/marketplace/thank-you/${ plugin.slug }/${
Fixed at https://github.com/Automattic/wp-calypso/pull/62353/commits/e6fbd01bb9d7c9e90e5eb195912cad33296ca790

2022-04-07 15:17 UTC, gcsecsey approved these changes
I've re-tested the changes, now I'm getting upgraded to the Pro plan from both flows. 👍

2022-04-07 15:44 UTC, epeicher approved these changes
I have tested and it works as advertised.

LGTM!

2022-04-07 15:50 UTC, merged

2022-04-07 16:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7219300

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

2022-04-14 10:34 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7219300).