Stepper: Fixed missing style in stepper web preview
Automattic/wp-calypso pull request #62559
Opened 2022-04-06 13:19 UTC by escapemanuele

#### Changes proposed in this Pull Request

In the Stepper we are adding the `WebPreview` component from `import WebPreview from 'calypso/components/web-preview/content';`, but the WebPreview scss file was imported only in `calypso/components/web-preview/component`,  used in `start` but not in `stepper`

With this PR we moved the scss import in `calypso/components/web-preview/content`.

| Before  | After |
| ------------- | ------------- |
| ![Screen Capture on 2022-04-06 at 15-12-44](https://user-images.githubusercontent.com/52076348/161982708-d06c4c22-0479-4a90-a533-b299d0941014.gif) | ![Screen Capture on 2022-04-06 at 15-10-14](https://user-images.githubusercontent.com/52076348/161982432-887a61ec-801d-4436-a4b4-de229df380cf.gif) |

#### Testing instructions

* Checkout branch
* `yarn start`
* Go to `http://calypso.localhost:3000/stepper/designSetup?siteSlug=SITE-SLUG`
* Preview a design
* You should be able to see the design in all the devices

2022-04-06 13:29 UTC, alshakero reviewed
Wow, brilliant idea!

I think this makes my changes in this [PR](https://github.com/Automattic/wp-calypso/pull/62407/files) redundant. Can you please verify that and remove my changes if so?

2022-04-06 15:02 UTC, escapemanuele commented
@alshakero, removed the CSS not used and fixed a bug in the Spinner Line, should be good now!

2022-04-06 16:23 UTC, alshakero requested changes
The spinner line seems broken. It's floating high above until it disappears.

2022-04-06 16:55 UTC, escapemanuele commented
@alshakero are you sure you tested with the last changes? I'm trying but I see it behaving correctly!
I also tried with `https://container-practical-goodall.calypso.live/stepper/designSetup?siteSlug=YOURSLUG.wordpress.com` (Calypso live)

2022-04-07 08:55 UTC, alshakero approved these changes
You're right. I didn't pull. Looks perfect now.

2022-04-07 09:28 UTC, merged