Stepper framework: Add import flow
Automattic/wp-calypso pull request #62759
Opened 2022-04-14 07:49 UTC by bogiii

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2022-04-21 05:52 UTC, vishnugopal approved these changes
Code looks great and most functionality works fine. Found a possible tiny bug:

https://user-images.githubusercontent.com/533/164383525-6ef9e722-9a36-4c57-ae0e-c15de774600d.mp4

2022-04-21 13:19 UTC, alshakero requested changes
Super excited for this one! thanks a lot!

Left some comments, mostly optional but would be greatly appreciated if addressed. These are the first flows to join stepper, and I'm trying to create good examples for the dozen flows that will follow; most people will look at the code and copy.

2022-04-21 13:19 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +	);
Trying to avoid Calypso state when possible:

```suggestion
	const isAtomicSite = site?.options?.is_automated_transfer;
```

2022-04-21 13:19 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +	const BASE_ROUTE = 'import';
I'd put this outside the component, it never changes.

2022-04-21 13:19 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +	}
```suggestion
	const shouldHideSkipBtn = currentRoute !== 'import'
```

2022-04-21 13:19 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +	};
I think we only need this because we're creating a tiny router below.

2022-04-21 13:19 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +			</div>
I'm confused as to why we're hacking our own router here. Would it be hard to make these individual steps? Maybe with a common wrapper ImportWrapper or something if they share some logic? They're already neatly compartmentalized components. 

When we make the individual steps we get 1) free routing 2) free reusability 3) smaller files that are easier to understand.

2022-04-21 13:19 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +				hideSkip={ shouldHideSkipBtn() }
```suggestion
				hideSkip={ shouldHideSkipBtn }
```

2022-04-21 13:19 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
> +	| 'import/ready/preview'
Unless it's a deal breaker for you, I'd aim to maintain the flatness of the steps. As in change `import/list` to `import-list`, `import-ready`, etc.. 

I entirely agree these steps are part of `import`, but it would be nice to establish a sense of flat steps-repository; every step is simple a nice component connected to the store. This makes every step directly reusable in other flows when we inevitably create them.

```suggestion
	| 'import-list'
	| 'import-ready'
	| 'import-ready-not'
	| 'import-ready-wpcom'
	| 'import-ready-preview'
```

Then you'll be free from navigation magic as well, you won't need to remove trailing slashes.

2022-04-26 21:21 UTC, bogiii commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +	}
Agree! I've added a shorthanded version.

2022-04-26 21:33 UTC, bogiii commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +	const BASE_ROUTE = 'import';
👍

2022-04-26 21:37 UTC, bogiii commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/index.tsx
> +			</div>
I did not pay extra attention, a similar setup already exists in the linear framework, so I just took the same logic.

Agree with you, and I'll try to separate it into individual steps using existing routing logic.

Thanks!

2022-04-26 21:42 UTC, bogiii commented on client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
> +	| 'import/ready/preview'
My idea was to reuse the same route structure as we have on `/start/import/{STEP}/{SECTION}`, but it's not a deal-breaker to update routes as you proposed (it's always good to be consistent).

2022-04-27 21:30 UTC, bogiii commented
> Code looks great and most functionality works fine. Found a possible tiny bug:
> 
>  CleanShot.2022-04-21.at.11.20.43.mp4

Thanks for discovering! It has been fixed.

2022-04-27 21:40 UTC, bogiii commented on client/landing/stepper/declarative-flow/internals/steps-repository/index.ts
> +	| 'import/ready/preview'
It has been updated. I've changed slashes routes to the camel case pattern to follow existing route patterns.

`import/ready/preview` -> `importReadyPreview`

2022-05-02 13:27 UTC, bogiii commented
@alshakero, could you please take one more look to confirm?

I would like to merge it soon.

2022-05-02 21:08 UTC, alshakero approved these changes
Honestly thank you so much for this! Looks great now!

2022-05-02 21:08 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/import/helper.ts
> +		( platform === 'wordpress' && isEnabled( 'onboarding/import-from-wordpress' ) )
```suggestion
		['blogger', 'medium', 'squarespace', 'wix', 'wordpress'].some(platform => isEnabled( `onboarding/import-from-${platform}` ) )
```

2022-05-03 11:18 UTC, merged