P2 signup flow: add step indicator, logout link
Automattic/wp-calypso pull request #63055
Opened 2022-04-26 15:27 UTC by annemirasol

#### Changes proposed in this Pull Request

* Add step indicators to the following steps: 
    * `user` (Step 1 of 3), 
    * `p2-confirm-email` (Step 2 of 3)
    * `p2-complete-profile` (Step 3 of 3)
* Add a logout button to the `p2-join-workspace` step.
* Fix some CSS issues
    * hover state of "Change username" button in the P2 login screen
    * fix non-existent hover color variables for `p2-complete-profile` 

#### Testing instructions
`ENABLE_FEATURES=no-force-sympathy yarn start` if testing on local.

* Go through the signup flow as a new user (if on incognito, please turn of "Block third-party cookies" while testing on calypso.localhost:3000)
* Verify that the step indicators are shown
* Verify that the logout button is shown and works as expected

#### Screens
<img width="800" alt="Screen Shot 2022-04-26 at 11 42 32 PM" src="https://user-images.githubusercontent.com/730823/165339737-08a14108-e5e6-42a7-b48a-49bf1e17a4ec.png">

Related to 4740-gh-Automattic/p2

2022-04-26 19:52 UTC, unDemian requested changes
I think there is a bug on the complete profile step
![Markup on 2022-04-26 at 10:51:23 PM](https://user-images.githubusercontent.com/2129455/165380970-2315ec0e-f2b4-48bc-8366-19fa3fb7102a.png)

2022-04-27 10:10 UTC, annemirasol commented
> I think there is a bug on the complete profile step ![Markup on 2022-04-26 at 10:51:23 PM]

Thanks for catching. Fixed!

<img width="608" alt="Screen Shot 2022-04-27 at 6 08 51 PM" src="https://user-images.githubusercontent.com/730823/165495543-5d0d8b56-4acd-4ace-847a-e058c7624d99.png">

2022-04-28 05:57 UTC, unDemian approved these changes
Looks good to me

2022-04-28 08:47 UTC, merged

2022-04-28 09:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7247776

Thank you @annemirasol for including a screenshot in the description! This is really helpful for our translators.

2022-05-10 10:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7247776).