Anchor: Add Error Step layout specific to Anchor flow
Automattic/wp-calypso pull request #63308
Opened 2022-05-04 20:46 UTC by valterlorran

#### Changes proposed in this Pull Request

* Adds a button to `Continue` and link to go `Back to Anchor.fm`, when the users fall on the Error Step on the Anchor.fm flow.

<img width="1167" alt="Screen Shot 2022-05-04 at 17 32 55" src="https://user-images.githubusercontent.com/1234758/166822238-f3bdb332-5116-4373-9ed2-00157e7e52c7.png">

#### Testing instructions

* Access `/setup/error?anchor_podcast=<podcast-id>` and you'll see the Error Step with the buttons to `Continue` and the link to go `Back to Anchor.fm`.

Related to #63216

2022-05-05 14:06 UTC, sixhours commented on client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx
> +						<span>{ __( 'Continue' ) }</span>
Are these `span`s necessary?

2022-05-05 14:06 UTC, sixhours requested changes
This is looking good! Couple things:

* I would update the button style to look like the other Continue buttons across the flow
* The error message needs to be updated to reflect the correct error message for Anchor sites (this one references a "store", for example).

2022-05-06 18:44 UTC, valterlorran commented on client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx
> +						<span>{ __( 'Continue' ) }</span>
No, I removed, thanks! 👍

2022-05-09 14:52 UTC, sixhours approved these changes
Looks good! 👍
<img width="1492" alt="Screen Shot 2022-05-09 at 10 52 34 AM" src="https://user-images.githubusercontent.com/2124984/167436967-bb451943-f6d5-4fb9-a0f9-f9ad5fc73572.png">

2022-05-09 17:36 UTC, merged

2022-05-10 02:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7303601

Thank you @valterlorran for including a screenshot in the description! This is really helpful for our translators.

2022-05-19 10:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7303601).