HelpCenter: article styling
Automattic/wp-calypso pull request #63362
Opened 2022-05-05 22:47 UTC by arcangelini

## Changes proposed in this Pull Request

Applying styling to embed article result for help-center. This does not apply to other places where inline-help is being used.

<img width="410" alt="Markup 2022-05-06 at 00 45 45" src="https://user-images.githubusercontent.com/33258733/167037107-51396d16-2816-4897-bdb7-ff817982459c.png">

<img width="411" alt="Markup 2022-05-06 at 00 46 11" src="https://user-images.githubusercontent.com/33258733/167037175-1a6ef6b0-4ccc-413f-a3bd-001c8342555e.png">

## Testing instructions

1. Pull branch & `cd apps/editing-toolkit && yarn dev --sync`
2. Login to sandboxed site
3. Check help-center article from editor

Fixes #63275

2022-05-06 08:34 UTC, escapemanuele requested changes
Very well done! Those articles will be really beautiful to read!
Some things to address that I noticed, while I continue to test this 👍

2022-05-06 08:34 UTC, escapemanuele commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 20;
Missing px here

2022-05-06 08:34 UTC, escapemanuele commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 16;
Same as above

2022-05-06 08:34 UTC, escapemanuele commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 14;
Same as above

2022-05-06 08:34 UTC, escapemanuele commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 16;
Same as above

2022-05-06 08:34 UTC, escapemanuele commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 14;
Same as above

2022-05-06 08:34 UTC, escapemanuele commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 14;
Same as above

2022-05-06 08:49 UTC, alshakero reviewed
Added to Emanuele comments.

2022-05-06 08:49 UTC, alshakero commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 20;
Adding `px` will make the bloody linter complain. 
```suggestion
		font-size: $font-title-small;
```

2022-05-06 08:49 UTC, alshakero commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 16;
```suggestion
		font-size: $font-body;
```

2022-05-06 08:49 UTC, alshakero commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 14;
```suggestion
		font-size: $font-body-small;
```

2022-05-06 08:49 UTC, alshakero commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 16;
```suggestion
		font-size: $font-body;
```

2022-05-06 08:49 UTC, alshakero commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 14;
```suggestion
		font-size: $font-body-small;
```

2022-05-06 08:49 UTC, alshakero commented on client/blocks/inline-help/inline-help-center-content.scss
> +		font-size: 14;
```suggestion
		font-size: $font-body-small;
```

2022-05-06 14:21 UTC, poligilad-auto commented
Looking much better @arcangelini!
I changed some small things for the titles, to align them better.

A few missing things:
1. h1 should be "$font-title-medium", weight 600 (Changed this a bit, but It's still appearing big for some reason > the change you made isn't working).
2. h2 should be "$font-title-small", weight 600
3. h3 should be "$font-body", weight 600
4. h4 should be "$font-body", weight 500
5. h5 should be "$font-body-small", weigth 500
6. h margins: the top & bottom margin for h5 is really big. Let's try to have margin "8px 0" for h2 > h5. That should be much better.
7. “Table of contents” title should be: $font-body. (sorry I made a mistake here).
8. "Table of contents" content text should be $font-body-small.
9. "Table of contents" remove this ol's margin:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/83961704/167135360-586b913d-274e-4287-9ade-989a5d75c5e2.png">
10. Something weird is going on with both buttons. I guess it's related to: "Can .wp-block-button be styled the same as .button-primary?"
<img width="395" alt="image" src="https://user-images.githubusercontent.com/83961704/167135673-98989eae-ba2c-4e59-af6e-3781a34b1983.png">
11. .wp-block-separator should be full width, now it's appearing only in the middle.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/83961704/167135888-f0927d1a-c01e-4586-b7da-34f1094395c3.png">
12. Remove this padding
<img width="437" alt="image" src="https://user-images.githubusercontent.com/83961704/167136028-76e7cf24-e4e7-4b6b-baca-8b3d488e95d0.png">
13. Can we use the exact same style for "back" as in the contact from header? Both icons for "back" & "external link" should be Gutenberg icons, they are currently Gridicons. The "external link" icon should be 20px.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/83961704/167137294-13519958-a7b6-498f-b5d8-e5b2e7b07593.png">
14. Make all "ol"s $font-body-small.
15. Can we make the BG behind the icon grey as well? This example is from "Use a Domain You Already Own (Domain Connection)"
<img width="479" alt="image" src="https://user-images.githubusercontent.com/83961704/167147206-ee6bf301-96aa-4965-b2a6-b485af5935f9.png">
16. ".support-article-dialog__header" remove the margin-bottom.




--


<br class="Apple-interchange-newline">

2022-05-10 09:54 UTC, arcangelini commented
@poligilad-auto I believe I got everything covered. Please let me know if I missed anything. I also addressed your comments from here: https://github.com/Automattic/wp-calypso/issues/63275#issuecomment-1119604364

2022-05-10 22:08 UTC, merged