Video-UI: Adding support to intent prop
Automattic/wp-calypso pull request #63377
Opened 2022-05-06 14:32 UTC by valterlorran

#### Changes proposed in this Pull Request

* Add the intent prop to the Video-UI component to allow us to track events with the intent.

#### Testing instructions

* The intent prop is not being used yet in this PR.
* To test it, I created unit tests for the components, which can be run with the following commands:
```
node 'node_modules/.bin/jest' './client/components/videos-ui/test/index.jsx' -c './test/client/jest.config.js' -t 'Video-UI'
```
```
node 'node_modules/.bin/jest' './client/components/videos-ui/test/video-player.jsx' -c './test/client/jest.config.js' -t 'Video player'
```

Related to #58247

2022-05-09 14:11 UTC, andres-blanco requested changes
Tests are passing! 

But when I go through the `/start` flow the `intent` property is `undefined`:
<img width="2428" alt="image" src="https://user-images.githubusercontent.com/375980/167428490-47f61a07-8548-4f17-9400-27039dccd83b.png">

To get to the UI this is the flow you should follow:
* Go to `/start`
* Set up a free site
* Select the `Write` intent
* Click on `Watch blogging videos`

2022-05-09 18:12 UTC, andres-blanco commented
@valterlorran Can you update this PR description with testing instructions to trigger the actual track and see the intent property being sent?

2022-05-09 19:26 UTC, valterlorran commented
@andres-blanco I only added the support for the intent prop in this PR, I'm not using it yet. My intention was to do another PR using this prop on the onboarding flow. Let me know if you think that would be more helpful if it was only one PR to solve the issue.

2022-05-10 11:52 UTC, andres-blanco approved these changes
LGTM

2022-05-10 11:53 UTC, andres-blanco commented
> @andres-blanco I only added the support for the intent prop in this PR, I'm not using it yet. My intention was to do another PR using this prop on the onboarding flow. Let me know if you think that would be more helpful if it was only one PR to solve the issue.

Ok, I thought it would be used somewhere, go ahead and merge :)

2022-05-10 12:44 UTC, merged