Jetpack Agency Dashboard: Add disconnect flow to Jetpack Cloud
Automattic/wp-calypso pull request #63432
Opened 2022-05-09 21:34 UTC by robertf4

#### Changes proposed in this Pull Request

This PR adds the disconnect flow found in Calypso at `/settings/disconnect-site` to cloud.jetpack.com for use with the Agency Dashboard.

#### Testing instructions

1. Visit `jetpack.cloud.localhost:3001/settings/disconnect-site/:site_slug?type=down` for a site that is connected to Jetpack and verify that the page shows.
2. Click the "Disconnect Jetpack" option.
3. Verify that you are taken to `jetpack.cloud.localhost:3001/settings/disconnect-site/confirm/:site_slug?type=down`.
4. Click the "Stay connected" option.
5. Verify that you are taken to `jetpack.cloud.localhost:3001/dashboard` and that your site is not disconnected.
6. Return to the confirmation page.
7. Click the "Disconnect" option.
8. Verify that you are taken to `jetpack.cloud.localhost:3001/dashboard` and that your site is disconnected.

Related to #

2022-05-10 05:50 UTC, manzoorwanijk reviewed
For some reason, the page is blank for me 🤔.
- The site is connected 
- There is not error in Console 

<img width="1281" alt="Screenshot 2022-05-10 at 11 18 02 AM" src="https://user-images.githubusercontent.com/18226415/167557139-d562a4bf-9480-4cd4-9855-7f19fd08e265.png">

2022-05-10 15:36 UTC, rcanepa commented
I could see the disconnect site UI, but some actions didn't work as expected:
- The `<- Back` button at the bottom took me to `http://jetpack.cloud.localhost:3000/settings/manage-connection/:site-slug`, which does not exist.
- The `Stay connected` button also took me to `http://jetpack.cloud.localhost:3000/settings/manage-connection/:site-slug`.

On the other hand, the disconnection button worked as expected (the site was properly disconnected).

2022-05-10 17:41 UTC, robertf4 commented
> For some reason, the page is blank for me 🤔.

@manzoorwanijk I'm not able to reproduce this. Could you try running `yarn distclean`, then `yarn install`, then `yarn start-jetpack-cloud-p`? Sometimes this fixes such issues.

2022-05-10 17:42 UTC, robertf4 commented
> I could see the disconnect site UI, but some actions didn't work as expected:

Good catches, I've pushed fixes for both issues.

2022-05-10 19:53 UTC, rcanepa requested changes
From a user perspective, things work as expected now, both in WPCOM and Jetpack cloud. However, the Unit tests check is not passing due to some TS error.

2022-05-10 20:03 UTC, robertf4 commented
> However, the Unit tests check is not passing due to some TS error.

Thanks, I was actually looking into that. The issue was that the redirectNonJetpack HOC was written in a way that TypeScript couldn't infer the prop types correctly, and it would have been too much for this PR to resolve it so I simply disabled type checking for those props.

2022-05-11 06:56 UTC, manzoorwanijk commented
> 1. settings/disconnect-site/:site_slug?type=down

Yes, that fixed it. Thank you.

<img width="845" alt="Screenshot 2022-05-11 at 12 25 35 PM" src="https://user-images.githubusercontent.com/18226415/167787556-a2513e40-7ead-4df4-b9ef-2e497bd46555.png">

2022-05-11 15:54 UTC, rcanepa approved these changes
Everything looks good to me now!

2022-05-12 06:09 UTC, yashwin approved these changes
LGTM - works as expected.

2022-05-13 15:27 UTC, merged