Help Center: Allow forum ticket with no site
Automattic/wp-calypso pull request #63614
Opened 2022-05-13 14:00 UTC by escapemanuele

Submit forum ticket without site

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2022-05-13 14:42 UTC, alshakero requested changes
Since there is a chance that the user already passed the URL in the field, we can use that info.

2022-05-13 14:42 UTC, alshakero commented on packages/help-center/src/components/help-center-contact-form.tsx
> +					disabled={ isLoading || ( mode !== 'FORUM' && ! supportSite ) || ! message }
Can we move this check into a function? `isCTAdisabled` or something? Because we have another condition that we'll add soon (requiring the subject).

2022-05-13 14:42 UTC, alshakero commented on packages/data-stores/src/support-queries/use-submit-forums-topic.ts
> +		}
```suggestion
		} else if( selfDeclaredURL ) {
			blogHelpMessages.push( `Self-declared URL: ${ selfDeclaredURL }` );
		}
```

2022-05-13 15:51 UTC, escapemanuele commented
Thanks @alshakero, I addressed your suggestions 👍

2022-05-16 15:24 UTC, alshakero approved these changes
Perfect!

2022-05-16 16:05 UTC, merged