Upwork Support: Use feature checks instead of plan checks
Automattic/wp-calypso pull request #63623
Opened 2022-05-13 21:09 UTC by obenland

I'm having a bit of trouble with this one.

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Related to #

2022-05-13 21:10 UTC, obenland commented
@mattwondra Is it expected that customers with Premium plans that contain live support would instead be re-routed to upwork support in cases where they don't also have a site with business plan and up?

I'm trying to make sense of this selector and how a feature check could work here but I'm not sure how.
I would have assumed I could just check if they have any site with live-support, but the Premium plan doesn't allow for that without breaking back compat.

2022-05-16 14:44 UTC, mattwondra commented
@obenland 👋 I'm no longer on the HappOps team, so @Automattic/happops-devs will be better suited to give current feedback on questions like this. Here's what I can tell you though:

- Upwork is a service that helps us support users in some non-English locales, by letting them get ticket (email) support in their own language through contracted translators.
- Users are eligible for Upwork if they are in one of our enabled locales.
- However, we don't use Upwork for users in our higher-paid plans, because we prefer to give them live chat support directly from our HEs. So users with Business/eCommerce plans are not eligible for Upwork ticket support.
- We offer users support based on their highest plan across all their sites. So you're correct, that if a user has a Premium plan, but also has Business/eCommerce plan, they are not eligible for Upwork (because we want them routed to live chat, even if they're asking a question about their Premium site).

Hope that's helpful but let me know if I can clarify anything else!

2022-05-16 14:53 UTC, obenland commented
Ah, apologies, thanks for providing that context regardless!

With the Premium plan offering live-chat support, should this check be extended to include that plan? If so we could check if any site has live-chat support to make the decision feature-based.

2022-05-16 15:02 UTC, mattwondra commented
You should probably check with HappOps about that question (#happiness-operations in Slack). I'm not sure how the recent WPCOM plan changes impact our support flows.

Based on the flows I know — no you should not opt Premium out of Upwork eligibility. Both Premium and (legacy) Personal plans are offered live chat support, but if the user is in an Upwork locale we still give them localized ticket support instead, because we believe it will be a better support experience. So Upwork eligibility is not directly related to whether the user has live chat support.

If you have a hard requirement to make this a feature-based check rather than a plan-based check, it sounds like there needs to be a new feature specifically for Upwork. I suspect you'll run into the same issue with Directly support as well.

2022-05-16 19:17 UTC, mreishus commented on client/state/selectors/is-eligible-for-upwork-support.ts
> +	);
It took me a moment to understand this logic, may I recommend a comment?

```diff
diff --git a/client/state/selectors/is-eligible-for-upwork-support.ts b/client/state/selectors/is-eligible-for-upwork-support.ts
index 82e3e78a59..e9a79d6741 100644
--- a/client/state/selectors/is-eligible-for-upwork-support.ts
+++ b/client/state/selectors/is-eligible-for-upwork-support.ts
@@ -16,6 +16,8 @@ export default function isEligibleForUpworkSupport( state: AppState ): boolean {
                return false;
        }
 
+       // If any site has the WPCOM_FEATURES_UPWORK_SUPPORT_EXEMPT feature, the
+       // user is not eligible for Upwork Support.
        return ! Object.values( getSitesItems( state ) ).some( ( { ID } ) =>
                siteHasFeature( state, ID ?? 0, WPCOM_FEATURES_UPWORK_SUPPORT_EXEMPT )
        );
```

or

```diff
diff --git a/client/state/selectors/is-eligible-for-upwork-support.ts b/client/state/selectors/is-eligible-for-upwork-support.ts
index 82e3e78a59..f0ab6f3bcb 100644
--- a/client/state/selectors/is-eligible-for-upwork-support.ts
+++ b/client/state/selectors/is-eligible-for-upwork-support.ts
@@ -16,7 +16,8 @@ export default function isEligibleForUpworkSupport( state: AppState ): boolean {
                return false;
        }
 
-       return ! Object.values( getSitesItems( state ) ).some( ( { ID } ) =>
-               siteHasFeature( state, ID ?? 0, WPCOM_FEATURES_UPWORK_SUPPORT_EXEMPT )
+       // To be eligible for Upwork, all of a user's sites must not have the WPCOM_FEATURES_UPWORK_SUPPORT_EXEMPT feature.
+       return Object.values( getSitesItems( state ) ).every(
+               ( { ID } ) => ! siteHasFeature( state, ID ?? 0, WPCOM_FEATURES_UPWORK_SUPPORT_EXEMPT )
        );
 }
```

2022-05-16 19:35 UTC, mreishus commented
Since Calypso by default only loads the selected site's features, on my main account with a variety of sites, I'm seeing different results based on what sites I've let calypso load.

Examples:

- `http://calypso.localhost:3000/stats/ads/day/<prosite>` --> "SUPPORT_CHAT_OVERFLOW" (Good)
- `http://calypso.localhost:3000/me` --> "SUPPORT_UPWORK_TICKET"  (Expected to see chat overflow)
- `http://calypso.localhost:3000/stats/ads/day/<freesite>` ---> "SUPPORT_UPWORK_TICKET" (Expected to see chat overflow)
- `http://calypso.localhost:3000/stats/ads/day/<freesite>` -> Switch sites to a Pro site -> Switch sites back to a free site ----> "SUPPORT_CHAT_OVERFLOW" (Good)

2022-05-16 20:02 UTC, obenland commented
whoa, nice catch! It looks like that's based on `getSitesItems()` returning an empty object, so this might not be a regression?
Should components that use the selector query all sites when they mount, to fix that?

2022-05-16 20:16 UTC, mreishus approved these changes
Ah, right, it's not a regression since the same bug existed before. The logic in this PR is working well in combination with D80779-code (which should be deployed before this PR is).

> Should components that use the selector query all sites when they mount, to fix that?

I think it could be a good fix. One danger would be we'd want to make sure we don't have the opposite problem (fetching features too often). For `<InlineHelpContactView>` I don't think that's a danger, but I'm not familiar with the other uses of `getSitesItems`.

2022-05-18 16:53 UTC, klimeryk requested changes
Thanks for improving the check - glad to see more feature checks (versus plan, upgrades, etc. checks that cause more work long-term).

However, as @mreishus mentioned in https://github.com/Automattic/wp-calypso/pull/63623#issuecomment-1128058725, there's indeed a regression here.

To reproduce, I checked a test user of mine with Spanish locale. On production, they get live chat (or live chat overflow) support variations. However, on this PR, they get the Upwork variation.
That's because we check now for the features flags - which are loaded from a separate call _per site_. The previous check was using the `plan` object that is returned for the more general `sites` call. In other words, we always have plan info for all sites, but we only have features for a given site if we explicitly loaded it first. So the check "if any site has this feature" is pretty flawed, cause often it will only be operating on very partial data.

As a result, this causes a regression and crucial change of behavior. This is a blocker for deploying this as-is. I'm not sure what's the fix here. Adding features to the sites endpoint? It's already a hot spot and I'd be wary of adding more stuff there 🤔 But if we already have plan info there, maybe it's possible.That's definitely a scope creep, though 😓

2022-05-18 16:53 UTC, klimeryk commented on client/state/selectors/is-eligible-for-upwork-support.ts
> +	);
I'd prefer to avoid comments like this - they quickly go out of date and cause more confusion than help.

Would it be possible to rewrite the code so that it's more readable instead? Maybe just extracting the sites items to a variable would help?

```suggestion
const sites = Object.values( getSitesItems( state ) );
return ! sites.some( ( { ID } ) =>
		siteHasFeature( state, ID ?? 0, WPCOM_FEATURES_UPWORK_SUPPORT_EXEMPT )
	);
```

If that's not enough, we can extract the callback to a separate function (in the same file should be fine) so that the `return` statement would simply read:
```
return ! sites.some( hasUpworkSupportExempt );
```

2022-05-18 16:53 UTC, klimeryk commented on client/state/selectors/test/is-eligible-for-upwork-support.js
> +						111: { data: { active: [ 'upwork-support-exempt' ] } },
Can we use the `WPCOM_FEATURES_UPWORK_SUPPORT_EXEMPT` constant here instead? That will ensure no magic string and it will make the code more future-proof (if we want to change the underlying string or the feature altogether).

2022-05-18 16:53 UTC, klimeryk commented on client/state/selectors/test/is-eligible-for-upwork-support.js
> +						222: { data: { active: [ 'live-support' ] } },
Similar comment as above about using a constant - and it actually seems to show the issue. The actual string should be `live_support` 😅 (yay for no consistency - of course, not your fault, these have been established long time ago)
https://github.com/Automattic/wp-calypso/blob/09c24573994ff390e63f6af24e679a73c002925c/packages/calypso-products/src/constants/features.ts#L222

2022-05-18 16:53 UTC, klimeryk commented on client/state/selectors/test/is-eligible-for-upwork-support.js
> +						111: { data: { active: [ 'live-chat' ] } },
Not sure we have a `live-chat` feature at all - did you mean `live_support` or one of the `live-chat-*` ones?

2022-05-18 19:37 UTC, mreishus commented
Something like this queries features for all sites:
```jsx
import { useSelector } from 'react-redux';
import QuerySiteFeatures from 'calypso/components/data/query-site-features';
import getSites from 'calypso/state/selectors/get-sites';

export default function QueryAllSiteFeatures() {
	const sites = useSelector( getSites );
	const allSiteIds = sites.map( ( site ) => site.ID );
	return <QuerySiteFeatures siteIds={ allSiteIds } />;
}

// <QueryAllSiteFeatures />
```
Unfortunately, it kicks off one HTTP request per site, which makes for 100+ requests for me, since I have so many sites:
![2022-05-18_14-30](https://user-images.githubusercontent.com/937354/169141062-0d09fb6a-9f32-4427-b83c-ee51d5d98557.png)

**Ideas**:
* Modify sites endpoint to return features
* Modify features endpoint to allow multiple sites to be queried in one request; strategically use `<QueryAllSiteFeatures>` in files like `client/me/help/help-contact/index.jsx`†
* Modify features endpoint to add a "return all features for all my sites" function without having to specify siteids; strategically use `<QueryAllSiteFeatures>`
* Make a new API endpoint that calculates the support level and returns that value without having to send all the features to calypso
* Other?

----

†_I see these files as needing access to the 'features for all sites' data:_

- `client/me/help/help-contact/index.jsx`
- `client/blocks/inline-help/inline-help-contact-view.jsx`
- `client/components/marketing-survey/cancel-purchase-form/index.jsx`
- `client/my-sites/checkout/composite-checkout/components/checkout-help-link.tsx`

2022-05-18 21:27 UTC, obenland commented
> Make a new API endpoint that calculates the support level and returns that value without having to send all the features to calypso

I like this one the best. With support levels being user-based they'll always be tough to map to site features

2022-05-23 16:40 UTC, obenland commented
@klimeryk I decided to forego any more foundational changes here and accept that support will need its own (new) approach

2022-05-25 12:32 UTC, klimeryk approved these changes
Thanks for bearing with this code and some legacy decisions 🙇 Apologies for the possibly frustrating experience here.
I've tested and works as expected 👍

2022-05-25 12:32 UTC, klimeryk commented on client/state/selectors/is-eligible-for-upwork-support.ts
> +	// If any site has an Upwork Support exemption, the user is not eligible.
See what I mean be comments getting obsolete? ;) Even before deploy 😬 
(I'm half-joking - this patch has been through so many iterations, that I fully understand a leftover of previous version got through)
I'd vote for simply no comment - the code seems straightforward enough.

2022-05-25 14:35 UTC, obenland commented
> Apologies for the possibly frustrating experience here.

Not at all! Thanks for taking the time and preventing me from heading down the wrong path!

2022-05-25 15:04 UTC, merged