Added the scan now button to view of results that include threats
Automattic/wp-calypso pull request #63690
Opened 2022-05-16 21:18 UTC by jwidavid

#### Changes proposed in this Pull Request

* Adds a manual "Scan now" button to the views where threat results are found.

Fixable Before             |  Fixable After
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/8845655/168682508-4a4f29d3-ca7c-414f-b646-eec9cb2b61b5.png)  |  ![](https://user-images.githubusercontent.com/8845655/168682611-9220103d-56f9-4590-b8ca-97b61cbe6312.png)

Non-Fixable Before             |  Non-Fixable After
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/8845655/168683019-91f69e85-0797-4aac-be2e-e663c795d83d.png)  |  ![](https://user-images.githubusercontent.com/8845655/168683056-a2981fd6-1728-466b-8c7d-0ca3aefb97dd.png)

#### Testing instructions

* Add a non-fixable threat such as an EICAR to random file in contents to a test site (I recommend the [Threat Tester](https://github.com/Automattic/jetpack-threat-tester) on a Jurassic Ninja site)
* Run a scan from Calypso 
* Notice the missing "Scan now" button
* Add a fixable threat such as modified core file threat
* Run a new scan, notice that the "Scan now" button is still missing
* Switch to this branch
* Run steps 1-4 again, but now notice the present Scan buttons
* Try the scan buttons to ensure they operate as expected

2022-05-20 01:04 UTC, nateweller requested changes
Works exceptionally, just needs a few small tweaks on mobile. 

I would recommend giving it a new, unique class name separate from the existing `scan__retry-bottom`.

<img width="637" alt="Screen Shot 2022-05-19 at 7 02 57 PM" src="https://user-images.githubusercontent.com/10933065/169428162-62d1079f-a798-4ade-a5f5-749e4da09e94.png">

<img width="435" alt="Screen Shot 2022-05-19 at 7 02 46 PM" src="https://user-images.githubusercontent.com/10933065/169428160-46d67f28-e01d-4655-9aba-74e1b37fbd4b.png">

2022-05-20 13:31 UTC, jwidavid commented
> Works exceptionally, just needs a few small tweaks on mobile.

@nateweller Ah, of course! It's been a while since I've done front-end / visual work - can't believe I forgot to check this over mobile. Will fix it today.

2022-05-24 18:05 UTC, nateweller requested changes
I like that we have a new specific class name for the secondary button now. There's still some minor layout issues on screen widths in the 770px - 805px range.

Could we potentially keep the buttons below the auto-fix message until the 960 breakpoint instead?

<img width="773" alt="Screen Shot 2022-05-24 at 12 00 35 PM" src="https://user-images.githubusercontent.com/10933065/170102419-39113df5-7b5d-4c11-9f28-c2fb9c9b173a.png">

<img width="802" alt="Screen Shot 2022-05-24 at 12 00 24 PM" src="https://user-images.githubusercontent.com/10933065/170102415-9c077d3d-92a1-4486-86b9-ae27299fb8ac.png">

2022-05-25 21:28 UTC, nateweller approved these changes
Beautiful! I made one more minor adjustment to fix the paragraph alignment on desktop, looks good to go.

Approved :+1:

2022-05-26 13:18 UTC, merged