Help Center: Show error if submitting ticket fails
Automattic/wp-calypso pull request #63760
Opened 2022-05-18 12:37 UTC by escapemanuele

#### Changes proposed in this Pull Request

![image](https://user-images.githubusercontent.com/52076348/169039433-cbce455a-8b8e-42d1-9e45-064d5df64f5e.png)

- Introduced an error shown to the user if the request for submitting to forums (as a free user) or sending an email fails.
- In FORUM and EMAIL the subject is now required, without that the request would fail.
- Moved `FormInputValidation` to `@automattic/components`, as we needed to use it from the help center package

#### Testing instructions

Don't be scared of the huge number of files, 99% is only changing the import! 

* checkout the branch
* `yarn dev --sync` from `apps/editing-toolkit`
* open the help center
* check that the subject is now required in EMAIL and FORUM
* `yarn start`
* check that there are no errors for the import changes ([http://calypso.localhost:3000/devdocs/design/form-fields](http://calypso.localhost:3000/devdocs/design/form-fields) could be a nice place to check)

Related to #

2022-05-18 15:38 UTC, alshakero reviewed
Brilliant work. "moved to a package" 🎵 to my ears.


Left two tiny notes.

2022-05-18 15:38 UTC, alshakero commented on packages/components/src/forms/form-input-validation/index.tsx
> +			</span>
I think these two (icon and childen) need to be in their own elements to fix this vertical alignment issue:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/17054134/169083287-ec0f8ef4-4071-42ec-a29a-52600672f31e.png">

2022-05-18 15:38 UTC, alshakero commented on packages/help-center/src/components/help-center-contact-form.tsx
> +						text={ __( 'Something went wrong, please try again later', __i18n_text_domain__ ) }
```suggestion
						text={ __( 'Something went wrong, please try again later.', __i18n_text_domain__ ) }
```

2022-05-18 15:38 UTC, alshakero commented on packages/help-center/src/components/help-center-contact-form.tsx
> +		);
Can we make this a switch around `mode`? We'll need it for Directly support soon.

2022-05-18 17:26 UTC, klimeryk commented on packages/help-center/src/components/help-center-contact-form.tsx
> +			( mode !== 'CHAT' && ! subject ) ||
Shouldn't this check for `subject` be also for `EMAIL`? From my testing it was also a required field for the endpoint.

2022-05-19 10:01 UTC, escapemanuele commented on packages/help-center/src/components/help-center-contact-form.tsx
> +			( mode !== 'CHAT' && ! subject ) ||
Yes @klimeryk , the current code checks for the subject presence if the mode is different from `CHAT`, so `EMAIL` and `FORUM` :) 

It could be a little confusing written like this, so in a bit I'll push a refactor of this.

2022-05-19 13:31 UTC, escapemanuele commented
Should have addressed everything @alshakero 👍

2022-05-19 14:25 UTC, alshakero requested changes
The alignment still looks off and it seems we lost the red color:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/17054134/169318321-626f5b88-9d7d-484c-8e31-6260f280377d.png">

2022-05-19 14:25 UTC, alshakero commented on packages/help-center/src/components/help-center-contact-form.tsx
> +		}
Truly beautiful.

2022-05-19 16:50 UTC, escapemanuele commented
Thanks for catching that, I must have forgot to deploy something 🤔

2022-05-24 22:42 UTC, alshakero approved these changes
Looks and works great! Thanks for moving Form fields to a package.

2022-05-24 22:49 UTC, merged

2022-05-25 01:16 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7329987

Thank you @escapemanuele for including a screenshot in the description! This is really helpful for our translators.

2022-06-02 14:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7329987).