Testing new copy on the signup plans page
Automattic/wp-calypso pull request #64239
Opened 2022-06-01 13:46 UTC by donlair

#### Proposed Changes

This PR includes copy changes to the the plans page shown in signup. The intent is to present each plan on its own merits, rather than shining such a negative light on Starter.

Here's a screenshot of the page:
![screencapture-calypso-localhost-3000-start-plans-2022-06-03-15_04_27](https://user-images.githubusercontent.com/35781181/171932502-4c9d2e7b-88da-41e0-8c74-b91209fb822c.png)

It is setup as an Explat test and restricted to EN + US so translations and local currency aren't an issue.

#### Testing Instructions
* Checkout this PR and start it locally.
* Assign yourself to the treatment in Explat experiment  `pricing_packaging_plans_page_copy_test`
* Navigate to signup in your local Calypso.
* You should see the updates on the plans step in Calypso.
* Try multiple viewports.
* Navigate to the plans page inside the the product to ensure it displays properly there as well.

*

Related to #

2022-06-03 20:09 UTC, michaeldcain requested changes
Overall, this works as described and look good. There's an issue nesting a paragraph inside a paragraph that should be straightforward to fix. I also dropped some style suggestions to tighten up the list, but you don't have to make those if you don't want to.

2022-06-03 20:09 UTC, michaeldcain commented on client/my-sites/plans-comparison/plans-comparison-col-header.tsx
> +		margin-left: 1rem;
```suggestion
		font-size: 0.875rem;
		margin-left: 1rem;
```

2022-06-03 20:09 UTC, michaeldcain commented on client/my-sites/plans-comparison/plans-comparison-col-header.tsx
> +		font-weight: 500;
```suggestion
		font-weight: 500;
		margin-bottom: 0.75rem;
```

2022-06-03 20:09 UTC, michaeldcain commented on client/my-sites/plans-comparison/plans-comparison-col-header.tsx
> +			<PlanDescription>
`PlanDescription` is a [styled paragraph tag](https://github.com/Automattic/wp-calypso/pull/64239/files#diff-b6b238d910a038a06ac8f6dedcccf8ba75991602a186b797fbf9d59d771fb9ceR38), so this technically nests a paragraph inside a paragraph, which is against HTML spec. You can update `const PlanDescription = styled.p` to `const PlanDescription = styled.div` to get around this for the test, although that might require some style adjustment.

2022-06-03 20:35 UTC, donlair commented
Thanks for the suggestions @michaeldcain, I incorporated them and it definitely looks better.

2022-06-03 20:41 UTC, michaeldcain approved these changes
The changes look good to me!

2022-06-06 12:18 UTC, gmovr approved these changes
Tested and looks good to me! 🚀  Adding some screenshots of various viewports (tested mobile, tablet and desktop). 
<img width="649" alt="Screenshot 2022-06-06 at 14 16 30" src="https://user-images.githubusercontent.com/52675688/172159218-7ae4c8ef-836e-4c5e-881a-b5c081d4aa28.png">
<img width="947" alt="Screenshot 2022-06-06 at 14 16 44" src="https://user-images.githubusercontent.com/52675688/172159223-ec56b913-93a2-43e9-b1c9-e059064f2c86.png">
<img width="1494" alt="Screenshot 2022-06-06 at 14 16 53" src="https://user-images.githubusercontent.com/52675688/172159227-d1b5feb6-8588-4b38-b4d5-1d51db9954da.png">

2022-06-06 12:25 UTC, merged

2022-06-06 14:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7360478

Thank you @donlair for including a screenshot in the description! This is really helpful for our translators.

2022-06-07 17:13 UTC, emilyaudela commented
@donlair I know that this might be moot due to the plan revert, but we noticed that there are a few hard-coded prices in the strings: 

- Available for $50+ each 
- Available for +$2/month
- Remove ads for +$2 per month

Could we use dynamic pricing instead, so pricing/currency is accurate for different users?

2022-06-07 17:18 UTC, donlair commented
@emilyaudela sure! for the purpose of the test, Explat is limited this version of the screen to just US+EN users so it's accurate for everybody who sees it.

2022-06-07 17:53 UTC, emilyaudela commented
Thanks! FYI, my translators (not in US, not EN) are seeing this live in calypso. So maybe the experiment hasn't been limited by geo/lang yet?

2022-06-07 18:15 UTC, donlair commented
> Thanks! FYI, my translators (not in US, not EN) are seeing this live in calypso. So maybe the experiment hasn't been limited by geo/lang yet?

Hmm, that shouldn't be happening, I'll take another look. Thanks for the heads up @emilyaudela !

2022-06-16 12:35 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7360478).