"Add new subscription" open the payment modal
Automattic/wp-calypso pull request #64460
Opened 2022-06-08 16:53 UTC by lukaszwilczakwilnet

#### Proposed Changes

For page /earn/payment-plans if user add hash #add-new-payment-plan to URL then modal with add new plan will be opened on page load

#### Testing Instructions

Go to page /earn/payment-plans/YOUR_SITE/
Check if page loads without opened modal popup.
Go to page /earn/payment-plans/YOUR_SITE/#add-new-payment-plan
Verify if page loads with opened modal popup to add new paid plan.

Related to # https://github.com/Automattic/jetpack/pull/24670

2022-06-09 08:32 UTC, dsas requested changes

2022-06-09 08:32 UTC, dsas commented on client/my-sites/earn/memberships/products.jsx
> +		showAddEditDialog: window.location.hash === '#add-new-payment-plan',
For sites which have a stripe connection but no current paid WordPress.com plan this will show the Add Payment modal, but they shouldn't be allowed to see this - they don't get the button to launch the modal.

The code should check the hasStripeFeature prop as well as the window hash.

2022-06-10 08:46 UTC, lukaszwilczakwilnet commented on client/my-sites/earn/memberships/products.jsx
> +		showAddEditDialog: window.location.hash === '#add-new-payment-plan',
Condition is added in line 115.

2022-06-10 10:25 UTC, Copons approved these changes

2022-06-13 16:45 UTC, merged