Emails: Add to the JITM modal the possibility to show a different image based on the icon property
Automattic/wp-calypso pull request #64979
Opened 2022-06-27 11:32 UTC by AllTerrainDeveloper

#### Proposed Changes

* Allows the JITM modal to change its sidebar image

#### Testing Instructions

1. It needs to be done by applying the patch D83166-code (and following its instructions)
2. Assert that the image is as follows
3. Test that the previous JITM keeps working as before (We don't provide icon property)

For Embedded Inbox launch
![image](https://user-images.githubusercontent.com/5689927/175931138-b9b16d8b-a6b1-4dc9-add8-f6cd6b9b0b6d.png)

For plans (Not providing icon property in the JITM engine
![image](https://user-images.githubusercontent.com/5689927/175931683-b6c87b23-121e-4a82-970c-5543a537bb52.png)

Related to 1200182182542585-as-1202476537751009

2022-06-27 12:10 UTC, stephanethomas commented on client/blocks/jitm/templates/modal.jsx
> +				return 'list of available plans — premium, business, and ecommerce plans';
Those strings should be localized (I suspect they only appear in screen readers).

2022-06-27 12:14 UTC, stephanethomas commented
Unfortunately there is an issue with this image - it's in English:

![image](https://user-images.githubusercontent.com/594356/175938323-ce1836ec-b799-4dd6-9954-b9d9548cdcab.png)

That's not an easy thing to fix though, as I don't think generating images for every language we support is going to work.

/cc @semihakocer

2022-06-27 12:45 UTC, stephanethomas requested changes
Putting aside the image which is not localized, I've also noticed this weird bug where the cross in the modal would be highlighted when the JITM appears, and its tooltip would be cropped (I'm on Windows with Chrome if that helps):

<img width="622" alt="01" src="https://user-images.githubusercontent.com/594356/175944303-91706a0c-2b0d-4908-9d7d-26a943d03dfd.png">

It's unrelated to your changes but we may want to escalate this issue to Marketing.

2022-06-27 13:25 UTC, AllTerrainDeveloper commented on client/blocks/jitm/templates/modal.jsx
> +				return 'list of available plans — premium, business, and ecommerce plans';
Yes, only for screen readers. Addressed

2022-06-27 13:26 UTC, AllTerrainDeveloper commented
@stephanethomas Thank you! I've addressed your concerns and I'm pinging the team in order to warn them about the close text in the modal

2022-06-27 13:28 UTC, AllTerrainDeveloper commented
> Unfortunately there is an issue with this image - it's in English:
> 
> ![image](https://user-images.githubusercontent.com/594356/175938323-ce1836ec-b799-4dd6-9954-b9d9548cdcab.png)
> 
> That's not an easy thing to fix though, as I don't think generating images for every language we support is going to work.
> 
> /cc @semihakocer

We've decided to target for now only English speakers. Thanks for catching that too!

2022-06-27 17:35 UTC, stephanethomas commented on client/blocks/jitm/templates/modal.jsx
> +				return translate( 'list of available plans — premium, business, and ecommerce plans', {
I would suggest the following text, so we don't have to update it when we launch new plans (it's already stale 😁):
```suggestion
				return translate( 'List of available WordPress.com plans', {
```

2022-06-28 09:27 UTC, stephanethomas commented on client/blocks/jitm/templates/modal.jsx
> +import Inbox from './inbox.svg';
Thinking about it more, we could name this file `embedded-inbox` so it is less generic and more consistent with the name of the icon.

2022-06-28 09:28 UTC, stephanethomas commented on client/blocks/jitm/templates/modal.jsx
> +	const getClassName = () => {
We may want to name this `getModalClassName()` to be more consistent with `getModalImage()` and `getModalAltText()`.

2022-06-28 09:29 UTC, stephanethomas commented on client/blocks/jitm/templates/modal.jsx
> +							<div className="modal__sidebar">{ modalImage }</div>
This variable doesn't look necessary, we could inline everything:

```suggestion
							<div className="modal__sidebar">
								<img className={ getClassName() } src={ getModalImage() } alt={ getModalAltText() } />
							</div>
```

2022-06-28 09:37 UTC, stephanethomas approved these changes
I had a number of minor suggestions but otherwise it's all good!

2022-06-28 11:23 UTC, AllTerrainDeveloper commented
@stephanethomas I've added all your suggestions :)

2022-06-28 13:40 UTC, merged

2022-06-28 14:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7404182

Thank you @AllTerrainDeveloper for including a screenshot in the description! This is really helpful for our translators.

2022-07-11 03:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7404182).