Google Sign-in: enable  on every environment
Automattic/wp-calypso pull request #65161
Opened 2022-07-01 18:45 UTC by sejas

#### Proposed Changes

* Enable `migration/sign-in-with-google` in all the environments.

#### Testing Instructions

- Make sure the flows described in #65086 is still working. (Pop-up)
- Make sure the flows described in  #64957 is still working. (Redirect)
---

- Related to #64538

2022-07-04 16:29 UTC, zaguiini requested changes
Changes looking good. We'll need to edit `client/components/social-buttons/google.js` to [fix unit tests](https://teamcity.a8c.com/viewLog.html?buildId=8165286&buildTypeId=calypso_RunAllUnitTests):

```diff
diff --git a/client/components/social-buttons/google.js b/client/components/social-buttons/google.js
index c249563159..717c8aa8b2 100644
--- a/client/components/social-buttons/google.js
+++ b/client/components/social-buttons/google.js
@@ -104,7 +104,7 @@ class GoogleLoginButton extends Component {
 	}
 
 	async loadGoogleIdentityServicesAPI() {
-		if ( ! window.google?.accounts.oauth2 ) {
+		if ( ! window.google?.accounts?.oauth2 ) {
 			await loadScript( 'https://accounts.google.com/gsi/client' );
 		}
 

```

2022-07-04 17:17 UTC, sejas commented
> Changes looking good. We'll need to edit `client/components/social-buttons/google.js` to [fix unit tests](https://teamcity.a8c.com/viewLog.html?buildId=8165286&buildTypeId=calypso_RunAllUnitTests):

@zaguiini Done!, The Tests are green now.
Thanks for catching the issue. 🙌

2022-07-04 17:21 UTC, zaguiini approved these changes
Works for me! Let's way for p1656952389723039-slack-C4EUDHL80 so we can merge and deploy the changes.

2022-07-11 07:36 UTC, xknown approved these changes
LGTM

2022-07-11 12:35 UTC, merged