Plans Step: fix design alignment issues
Automattic/wp-calypso pull request #65188
Opened 2022-07-04 09:21 UTC by mtias

The current plan design has issues in different locales, where the plan price and button actions don't align well and create a sloppy stair effect. This adds a flex wrapper and ensure the bottom section is aligned.

Before:
<img width="1051" alt="Screenshot 2022-07-02 at 11 10 26" src="https://user-images.githubusercontent.com/548849/177124581-f40952d3-86ba-423e-8ecc-b6abc7b2981d.png">

After:
<img width="1192" alt="Screenshot 2022-07-04 at 11 17 40" src="https://user-images.githubusercontent.com/548849/177124606-2ddc77d6-dae7-4fc5-920e-fce3c1bcde10.png">

2022-07-04 10:16 UTC, gmovr approved these changes
Thanks for sorting this! These changes look good to me. Tested in ES and EN. 🚢

2022-07-04 10:50 UTC, gmovr requested changes
I tested initially in Safari and Chrome on mobile/desktop. But when testing in Firefox on large viewports, it overlaps the table in the signup flow.
<img width="1133" alt="Screenshot 2022-07-04 at 12 42 37" src="https://user-images.githubusercontent.com/52675688/177140119-eae04bfe-4332-405f-af57-db83a92b9d4c.png">
<img width="1338" alt="Screenshot 2022-07-04 at 12 44 43" src="https://user-images.githubusercontent.com/52675688/177140129-21560dfa-4e7a-4656-9940-c0c842784e6c.png">
<img width="1312" alt="Screenshot 2022-07-04 at 12 48 49" src="https://user-images.githubusercontent.com/52675688/177140133-16cb1e0c-6306-49a5-b6d2-d749dee25c34.png">

2022-07-14 11:42 UTC, chriskmnds commented
Rebased and cleaned up some conflicts. Let's do some testing to make sure nothing was done wrong there 😬 cc @gmovr 

Also, I see some errors in the console concerning the use of `:first-child`/`:nth-child` in the styles. @ciprianimike can you maybe take a look? 🙏 

e.g. 
<img width="760" alt="Screenshot 2022-07-14 at 2 41 49 PM" src="https://user-images.githubusercontent.com/1705499/178974595-3bad26d4-8510-4856-a121-d07950a3bfbd.png">

2022-07-14 11:44 UTC, gmovr commented
Awesome! I'll take it for a spin with the experiment from https://github.com/Automattic/wp-calypso/pull/65126 as well 👍

2022-07-14 11:55 UTC, gmovr commented
Tested visually in Chrome and Firefox. Also on mobile viewports + with and without experiment assigned.
![Screenshot 2022-07-14 at 13 53 50](https://user-images.githubusercontent.com/52675688/178976748-30f1bb99-7ec0-4a68-bc37-0cec2f6a7332.png)
![Screenshot 2022-07-14 at 13 48 52](https://user-images.githubusercontent.com/52675688/178976761-cdf1e547-810d-42db-b596-d090c42c1af5.png)
![Screenshot 2022-07-14 at 13 47 47](https://user-images.githubusercontent.com/52675688/178976764-2459cae6-daf3-4b17-b610-098f7bdeed8a.png)
![Screenshot 2022-07-14 at 13 47 26](https://user-images.githubusercontent.com/52675688/178976768-c337e6c0-9853-42a5-bf60-78688a80fb98.png)

2022-07-14 13:13 UTC, gmovr approved these changes
Changes look good to me! Tested in Firefox and Chrome again in various viewports. 🚀

2022-07-14 13:33 UTC, merged