Plugin Details: Manage plugin actions
Automattic/wp-calypso pull request #66054
Opened 2022-07-28 15:32 UTC by WBerredo

#### Proposed Changes

* Add activate/deactivate button on CTA area
* Use the autoupdate toggle on the CTA area
* Add a Manage plugin menu with options(settings, remove) on the CTA area.

#### Testing Instructions
 
* Enable the feature flag `plugins/plugin-details-layout`*
* Go to an already installed plugin page (`plugins/{plugin_slug}/{site}`)
* Check the actions on the sidebar as the screenshots bellow
* Test the follow actions to see if they area working: `activate`, `deactivate`, `autoupdate toggle`, `remove`, `settings` (if applicable)

| Active | Deactivated | Menu with options |
| ------------- | ------------- |------------- |
|<img width="341" alt="Screen Shot 2022-07-28 at 11 18 12" src="https://user-images.githubusercontent.com/5039531/181577921-b422e4be-3a0c-4d5e-adba-abd727e2a6ef.png">|<img width="341" alt="Screen Shot 2022-07-28 at 11 18 22" src="https://user-images.githubusercontent.com/5039531/181577581-9725020a-48dc-4050-82e7-bc9960b881ce.png">|<img width="393" alt="Screen Shot 2022-07-28 at 11 22 00" src="https://user-images.githubusercontent.com/5039531/181577716-b25d0b64-e7f6-42ce-a79b-c2438a3fa8a1.png">|
---

\* To enable this feature flag add `?flags=plugins/plugin-details-layout` to the end of your URL or past the following code on the developer tools console `document.cookie = 'flags=plugins/plugin-details-layout;max-age=1209600;path=/'`

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have you sent any new strings for translation (PCYsg-1vr-p2) ASAP?

----

Fixes #65611
Fixes #63887

2022-07-29 09:01 UTC, cpapazoglou requested changes
Thanks Wesley, looks working as expected.

- left a minor translator comment
- can we add a loader in the sidebar to avoid content flashing?

![CleanShot 2022-07-29 at 11 59 49](https://user-images.githubusercontent.com/12430020/181724132-6ae360c5-0935-4b96-95e4-afe2d2316086.gif)

2022-07-29 09:01 UTC, cpapazoglou commented on client/my-sites/plugins/plugin-details-CTA/index.jsx
> +								{ translate( 'Enable autoupdate.' ) }
```suggestion
								{ translate( 'Enable autoupdates.' ) }
```
just using plural here.

2022-08-01 19:02 UTC, WBerredo commented on client/my-sites/plugins/plugin-details-CTA/index.jsx
> +								{ translate( 'Enable autoupdate.' ) }
Fixed at https://github.com/Automattic/wp-calypso/pull/66054/commits/ab174b95e0c024b43e1b6391826c270f1b33c70c

2022-08-01 19:04 UTC, WBerredo commented
I updated the behavior to keep showing the placeholder until we have all the necessary data. Let me know your opinions on it.

![Kapture 2022-08-01 at 12 14 48](https://user-images.githubusercontent.com/5039531/182225494-0a9f9b0d-4b18-45b6-8bbc-6133bb93346c.gif)


<img width="1090" alt="Screen Shot 2022-08-01 at 12 11 57" src="https://user-images.githubusercontent.com/5039531/182225316-bfeab6fa-0a0b-4e6d-aef4-353259ad3c6b.png">

2022-08-02 08:17 UTC, cpapazoglou approved these changes
LGTM!

2022-08-02 08:18 UTC, cpapazoglou commented
I have restarted some flaking e2e tests.

2022-08-03 15:01 UTC, merged

2022-08-03 16:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7463232

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

2022-08-12 16:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7463232).