Checkout: Always show monthly price in variant dropdown
Automattic/wp-calypso pull request #66066
Opened 2022-07-28 22:24 UTC by sirbrillig

#### Proposed Changes

Suggested by @lucasmendes-design, this PR changes the checkout product term variant picker to display monthly prices for each product variant rather than the product's subtotal.

Before:

<img width="566" alt="Screen Shot 2022-07-28 at 6 23 26 PM" src="https://user-images.githubusercontent.com/2036909/181647319-660a4bc5-5acf-4d2e-b377-4566042a71d5.png">

After:

#### Testing Instructions

- Add a product that has term variants to your shopping cart (eg: any legacy plan like Premium).
- Visit checkout and verify that the term variant picker shows the prices as monthly no matter which term is selected.

2022-07-28 23:07 UTC, dylanrevisited approved these changes
I tried with different currencies and it works as expected. Code also looks fine.

2022-07-29 00:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7459223

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

2022-07-29 14:20 UTC, DavidRothstein commented
With this change, I really can't tell if I'm paying $48 up front, vs. being billed $4/month for the next year.  That's true in your above screenshot, and probably even more so in the screenshot below (with the dropdown closed, which is how most users will see it):

![Screenshot from 2022-07-29 10-14-29](https://user-images.githubusercontent.com/235183/181779211-b9040a0d-c2c9-45b5-aae4-fe0cfa55a8a5.png)

We already know people get confused about this on the Plans page, and we **really** have to make sure the confusion doesn't continue into checkout.  This is especially important with the rise of "Buy Now, Pay Later" and everything else that blurs the distinction between how much you owe and how much you're actually going to be charged.

I think if we want to show the per-month cost in checkout, we need to be more clear about the total cost.  For example, with the current design, something along the lines of `$4/month x 12 = pay $48 now`.  However, it may be better to first figure out where the final design is going, because there may be different ways to accomplish that in the final design.

2022-07-29 14:21 UTC, DavidRothstein requested changes
I think this does need more work, based on the above.

2022-07-29 19:05 UTC, lucasmendes-design commented
We can also try this copy to be clearer. 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/98343583/181827633-542ebab6-cb3a-4315-9b3f-09bfce0a07dc.png">

We can also be inspired by the example below. 
"Billed as one payment of ..."

But as you can see the main information is the price per month. It's highlighted and also bigger on both pages! More examples [here](https://github.com/Automattic/wp-calypso/issues/65968#issuecomment-1196178900) 

Another example from Grammarly 
1. Plans page.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/98343583/181825208-0ae2ff0e-e064-4b02-bd9d-c5a961c64883.png">

2. Checkout page. 
<img width="739" alt="image" src="https://user-images.githubusercontent.com/98343583/181825261-3eaa5b2b-ba6b-4b7a-b578-42eb5db83b7e.png">

<img width="369" alt="image" src="https://user-images.githubusercontent.com/98343583/181825325-9fff8833-4a42-47b4-b007-2408d4d54505.png">

cc: @DavidRothstein @sirbrillig

2022-07-29 19:35 UTC, lucasmendes-design commented
In general, I was just tweaking this section, we can also revamp the whole thing. Let me know how I can help you :) 
![image](https://user-images.githubusercontent.com/98343583/181831470-3260053b-d209-4e34-bf26-28a8ab2215b5.png)

2022-07-29 20:14 UTC, sirbrillig commented
The problem with adding additional text inside the term variant options is that they don't have a lot of horizontal space. Here's what it would look like if we used already-translated strings that include both monthly and actual price. You can see how they wrap in an unpleasant way.

<img width="566" alt="Screen Shot 2022-07-29 at 4 04 16 PM" src="https://user-images.githubusercontent.com/2036909/181835694-370fbaf1-6155-4255-8432-010b7d8b0c66.png">

And here's a more minimal version that uses new strings at desktop width, which looks ok, but then look at their mobile width versions.

<img width="563" alt="Screen Shot 2022-07-29 at 4 06 07 PM" src="https://user-images.githubusercontent.com/2036909/181835846-630a92ed-9112-42ab-a351-beb6a3448c05.png">
<img width="374" alt="Screen Shot 2022-07-29 at 4 06 35 PM" src="https://user-images.githubusercontent.com/2036909/181835856-6ff0f1e3-db08-427f-80b5-c4f14e2ff243.png">

This is not an easy problem to solve. How about this compromise? The biennial version is not perfect at small widths but maybe we could hide the "Save X%" text using a breakpoint.

<img width="558" alt="Screen Shot 2022-07-29 at 4 12 06 PM" src="https://user-images.githubusercontent.com/2036909/181836417-c7886073-db2c-42a6-bd4d-532c4477c33d.png">
<img width="372" alt="Screen Shot 2022-07-29 at 4 11 54 PM" src="https://user-images.githubusercontent.com/2036909/181836463-deb2850f-3d20-4d09-8f6b-f9c8c97a0d99.png">

2022-08-01 15:21 UTC, DavidRothstein commented
I think something like the last screenshot above could probably work, although ideally we'd remove the second "$8/month" when the dropdown is closed (since it doesn't have the same caveat and is a bit repetitive anyway), i.e. something more like the following instead?

Closed:

![closed](https://user-images.githubusercontent.com/235183/182182006-1d871d28-c61c-4c61-afa1-3b628931c1cb.png)

Open:

![open](https://user-images.githubusercontent.com/235183/182182045-c904616c-89e7-4f7f-998d-6914b9457b14.png)

I agree that fitting meaningful text **inside** the dropdown could be difficult at mobile widths -- it is one reason it could make sense to think about this as part of the larger redesign that's been discussed (since it sounds like it might not even wind up as a dropdown in the end).

2022-08-01 18:14 UTC, sirbrillig commented
Thanks, friends. I've pushed a change that I think is pretty decent. What do you think?

<img width="563" alt="Screen Shot 2022-08-01 at 1 58 48 PM" src="https://user-images.githubusercontent.com/2036909/182214506-e2de2fc1-7de7-41ca-8d50-964e2778d258.png">

<img width="376" alt="Screen Shot 2022-08-01 at 1 59 08 PM" src="https://user-images.githubusercontent.com/2036909/182214547-b3588490-ae81-4e24-ae0e-4f36018ac6dd.png">

2022-08-01 21:12 UTC, DavidRothstein commented
The first case looks good.

The case with the first-year discount is definitely complicated -- thanks for thinking of testing that.  Besides the layout being a little funny, the $10.95/month doesn't match the $299.40 per year; the first includes the discount but the second doesn't.  (I also noticed that if you add a coupon, it reduces the $10.95/month further...)

This is a little tricky because I think the whole point of the "Plan Subscription" line in the first place was to show the **non-discounted** price (i.e. the actual **subscription** price they would pay in future years, once they are billed again) so now we're kind of trying to do multiple things with that line at the same time.

For comparison, this is roughly what they would have seen on the Plans page before going to checkout:

![Screenshot from 2022-08-01 17-06-47](https://user-images.githubusercontent.com/235183/182247106-bf5dcb23-a053-422b-9462-fccad337e633.png)

2022-08-02 14:48 UTC, sirbrillig commented
Good point. The two numbers in that string should use the same calculation. 🤔 

In my mind, the subtext "x/month, billed Y annually" should refer to the subscription price. The variant picker text, however, is essentially an upsell so it can have the discounted price. Let me see how that looks.

2022-08-02 15:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7459223).

2022-08-02 16:17 UTC, sirbrillig commented
Here's what it looks like now:

<img width="508" alt="Screen Shot 2022-08-02 at 12 16 14 PM" src="https://user-images.githubusercontent.com/2036909/182423340-57e0a673-43be-411c-9220-2932cc493722.png">

2022-08-02 20:23 UTC, DavidRothstein commented
I know there's not much of a way to fit this in the dropdown, but the `$10.95/month` option would make more sense to me as something like:

>~~$24.95/month~~ $10.95/month _First year discount_

Otherwise you have a situation where you select something that just says "$10.95" but then you see "$24.95" after you select it.

Also, and this is probably obvious, but the above screenshot shows that the "Discount for first year" text is now pretty far away from the price that it's supposed to be labeling.  Overall it just seems a bit like the current design and layout can't quite handle what we're trying to do with it :frowning_face:

2025-07-21 14:24 UTC, closed without merging