Add basic link in bio intro step
Automattic/wp-calypso pull request #66086
Opened 2022-07-29 12:38 UTC by renancarvalho

#### Proposed Changes
Add basic initial link in bio step

#### Testing Instructions
 - Pull this branch and Run `yarn start`
 - Navigate to http://calypso.localhost:3000/setup/linkInBioIntro?flow=link-in-bio

You should see a page very similar to this:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/2653810/181758078-d0691bb4-efea-4191-953b-97fb9ccf81e4.png">

Related to #66085
Fixes #66085

2022-07-29 12:54 UTC, escapemanuele requested changes
Well done @renancarvalho 🚀 🎸 
While we see how to deal with the large image, could be nice to fix translations 😄

2022-07-29 12:54 UTC, escapemanuele commented on client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-intro/intro.tsx
> +				Link in Bio
Remember about translations, look at how `@wordpress/react-i18n` is used in other steps 😄

2022-07-29 12:54 UTC, escapemanuele commented on client/landing/stepper/declarative-flow/internals/steps-repository/link-in-bio-intro/intro.tsx
> +				Get Started
Here as well

2022-07-29 14:03 UTC, escapemanuele approved these changes
Wonderful, thanks for making the changes!

2022-07-29 15:11 UTC, merged

2022-07-29 16:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7459574

Thank you @renancarvalho for including a screenshot in the description! This is really helpful for our translators.

2022-08-01 07:27 UTC, emilyaudela commented
Hi there! We got a [note](https://a8c.slack.com/archives/CEM18K8LT/p1659250069036569) from one of our translators that it's hard to translate this phrase because it's been separated into 2 [separate strings](https://translate.wordpress.com/deliverables/de/7459574/). Would it be possible to put the two parts in one string, instead of splitting it into 2 strings? So it would read `<span>Let’s set up your</span> Link in Bio`.

2022-08-01 07:49 UTC, renancarvalho commented
> Hi there! We got a note from one of our translators that it's hard to translate this phrase because it's been separated into 2 [separate strings](https://translate.wordpress.com/deliverables/de/7459574/). Would it be possible to put the two parts in one string, instead of splitting it into 2 strings? So it would read `<span>Let’s set up your</span> Link in Bio`.

Hi @emilyaudela, thank you for getting in touch, Yes, this is being handled on this PR https://github.com/Automattic/wp-calypso/pull/66102 which I believe will be merged very soon.
Thank you.

2022-08-01 14:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7459574).