VideoPress Onboarding: Save title and site description when site is created
Automattic/wp-calypso pull request #66185
Opened 2022-08-02 21:51 UTC by roundhill

Fixes setting the site title and description (aka tagline) for the site. I created a new api request for creating the site and title, and setting the description via a separate api call after the site is created. There did not appear to be a way to set the description via the `sites/new` endpoint so it needed to be done separately.

**To Test**
 * Create a new site via `/start/videopress`.
 * Set a title and a description.
 * Complete your purchase.
 * Your site should have the title and tagline that you set!

2022-08-03 08:10 UTC, thedebian approved these changes
Working well 👌
![Capture d’écran 2022-08-03 à 10 08 26](https://user-images.githubusercontent.com/1420594/182557580-8ba68ae4-b667-4cc8-9ba2-2a5d07c567de.png)

2022-08-03 13:14 UTC, pgk requested changes
I am refactoring this a bit, I think that some steps need to happen sequentially.

2022-08-03 13:14 UTC, pgk commented on client/lib/signup/step-actions/index.js
> +			fetchSitesAndUser( siteSlug, () => callback( undefined, providedDependencies ), reduxStore );
I am not sure if the callback should be called here or in the post to settings request. It feels like that is the actual place it should be called, because something might fail when sending the description and the title.

2022-08-03 13:14 UTC, pgk commented on client/lib/signup/step-actions/index.js
> +			if ( siteDescription ) {
Also, this is happening concurrently with the `fetchSitesAndUser` call, but I think that they should be happening sequentially. Which means that this api call should be nested in the fetchSites and user call

2022-08-03 14:22 UTC, pgk approved these changes
I can approve my changes :P

2022-08-03 21:09 UTC, roundhill commented
- [ ] Bug: If you leave the site description blank there's a nasty js error that causes the signup flow to die.

2022-08-04 12:12 UTC, pgk commented
> * [x]  Bug: If you leave the site description blank there's a nasty js error that causes the signup flow to die.

should be ok now!

2022-08-04 14:28 UTC, roundhill commented
> should be ok now!

Yes, thank you!

2022-08-04 14:28 UTC, merged