Whats New: Working in Atomic
Automattic/wp-calypso pull request #66254
Opened 2022-08-04 09:39 UTC by escapemanuele

#### Proposed Changes

* This PR reintroduces the `What's New Modal` in Atomic sites. It wasn't working before because of usual API problems in atomic sites (requests need to pass through Jetpack)
![image](https://user-images.githubusercontent.com/52076348/182814881-561551ad-e8ab-4772-a21a-987ad0a82936.png)
* Fixed the `useHasSeenWhatsNewModal` query in Atomic, used to determine if to show the dot next to the Help Center
![image](https://user-images.githubusercontent.com/52076348/182815614-6a0adda9-8f7a-464f-a189-8edede271164.png)

#### Testing Instructions

* Checkout branch
* `yarn dev --sync` in `apps/editing-toolkit`
* Check that the query works in simple and atomic sites

Related to #65973 
Fixes #65973

2022-08-04 10:04 UTC, alshakero reviewed
Look good. Great work. Makes me even more assured about supporting options in Atomic sites soon. Can you test with Jetpack disabled? @arcangelini found yesterday that many things break.


I don't expect the help-center to function without jetpack, but please test if the anything other than that breaks.

2022-08-04 10:04 UTC, alshakero commented on packages/whats-new/src/index.tsx
> +						path: `/wpcom/v2/block-editor/whats-new-list`,
No locale here?

2022-08-04 11:22 UTC, escapemanuele commented on packages/whats-new/src/index.tsx
> +						path: `/wpcom/v2/block-editor/whats-new-list`,
Great catch! Added in the last commit 👍

2022-08-04 15:23 UTC, heavyweight commented on apps/editing-toolkit/editing-toolkit-plugin/whats-new/class-wp-rest-wpcom-block-editor-whats-new-dot-controller.php
> +		$this->namespace                       = 'wpcom/v2';
Minor formatting issues here

2022-08-04 16:11 UTC, alshakero reviewed
Code looks great and like the passing tests now. I will test tomorro.w

2022-08-04 16:15 UTC, alshakero requested changes

2022-08-04 16:15 UTC, alshakero commented on packages/wpcom-proxy-request/src/index.js
> +}
`wpcom-proxy-request` shouldn't know about simple and atomic sites, I think we should:

1. Rename the function to `canAccessWpcomApis`.
2. Remove the boolean and use it wherever `shouldTargetWpcom` is used, even though I don't think we need the boolean. All simple sites match `wpcomAllowedOrigins` anyway.

2022-08-04 17:03 UTC, escapemanuele commented
Thanks @alshakero! Starting from your suggestion, I refactored the use of `shouldTargetWpcom` and removed much of the `isSimpleSite` usage!

2022-08-04 20:34 UTC, noahtallen commented
> Can you test with Jetpack disabled?

Is it possible to disable Jetpack on Atomic sites?

2022-08-04 21:42 UTC, alshakero commented
> Is it possible to disable Jetpack on Atomic sites?

Yes, it seems like it 🙃 .@arcangelini SAYS HEs can disable JP during debugging. But I can't find how. Any ideas Tony?

2022-08-04 22:54 UTC, noahtallen commented
Maybe just on the atomic developer sites? It doesn't seem to be possible on my normal atomic site

2022-08-04 23:39 UTC, arcangelini commented
Yes, you have to use CLI to do so. It's part of the troubleshooting steps for some plugin/jetpack issues.

2022-08-05 07:22 UTC, escapemanuele commented
Should be doable at yourwebsite.com/_cli and then using the command 'wp plugin deactivate jetpack'

2022-08-09 17:49 UTC, heavyweight approved these changes

2022-09-07 10:04 UTC, alshakero approved these changes
So freaking neat. 

1. What's new bubble ✅ 
2. English ✅ 
3. Spanish ✅ 
4. Atomic and Simple ✅

2022-09-07 12:30 UTC, merged