Sites Management Dashboard: disable display mode toggle action while saving
Automattic/wp-calypso pull request #66473
Opened 2022-08-10 19:13 UTC by zaguiini

#### Proposed Changes

Fixes #66381.

In my first iteration I tried setting the `disabled` prop in the `Button` but turns out that affects the element visually for a few milliseconds. I think that disabling the pointer events while the save preference request is in progress for the radio group a better experience.

#### Testing Instructions

Try switching really quick between display modes on SMD and check that the race condition when saving the preference is gone.

2022-08-10 20:06 UTC, danielbachhuber approved these changes
It does fix the immediate issue, but it makes the buttons feel laggy/broken if you do try to quickly toggle for some reason.

Ideally, the buttons would always be immediately responsive. Is it a correct assumption that it's not possible to achieve this because we don't have a mechanism for: 1) canceling the existing requests in process, and 2) sending along the final state?

2022-08-11 01:41 UTC, p-jackson requested changes
It does solve the problem but I think there are a couple of issues:
- If the button is disabled then it should be visually and semantically disabled
- Not allowing the user to switch preferences while they wait for network traffic feels like an artificial limitation, why shouldn't they be able to change their mind quickly?

I think another option would be to use regular old component state as the definitive value for the mode rather than the server value. I've prototyped that idea here: https://github.com/Automattic/wp-calypso/pull/66482. `useSitesDisplayMode` now behaves like `useState` except that it persists data behind the scenes (but ignores the server response). The diff is a bit bigger because the state has to be high enough in the component tree so that everyone can use it (something like `recoil.js` would be ideal)

Another alternative would be to improve the preferences store in Redux so that successful responses from the server are ignored when the user has re-saved a preference in the meantime.

We should either:
- Make the button properly disabled
- Re-jig how the preference state works

2022-08-11 02:44 UTC, vykes-mac commented
I was thinking along a similar line @p-jackson , instead of using server value use some in memory value to store the display mode and save in the background without using the async await. So when user switch the in memory value is updated and use to switch display while the actual value is saved in the background.

2022-08-11 17:13 UTC, zaguiini commented
Thanks for the feedback @p-jackson @vykes-mac, I will come up with something!

2022-08-11 17:40 UTC, zaguiini commented
@Automattic/build team, I've committed changes and I think it looks a whole lot better! Thanks for the prompt and helpful feedback 👍

2022-08-11 20:25 UTC, danielbachhuber approved these changes
👍 Works much better — great work!

2022-08-11 20:30 UTC, merged

2022-08-12 11:33 UTC, sejas commented
Great work, using just a local state and dispatching the change in the "background".
Very smart keeping the state in the parent so the tiles and the filter share the same value. 👍