[Jetpack Agency] Add contact person and company website fields
Automattic/wp-calypso pull request #66981
Opened 2022-08-25 11:35 UTC by kallehauge

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-08-25 15:35 UTC, atanas-dev requested changes
2 minor fixes needed - otherwise looks good 👍

2022-08-25 15:35 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/company-details-form/index.tsx
> +					<FormLabel htmlFor="name">{ translate( 'Contact first and last name' ) }</FormLabel>
```suggestion
					<FormLabel htmlFor="contactPerson">{ translate( 'Contact first and last name' ) }</FormLabel>
```

2022-08-25 15:35 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/company-details-form/index.tsx
> +					<FormLabel htmlFor="name">{ translate( 'Company website' ) }</FormLabel>
```suggestion
					<FormLabel htmlFor="companyWebsite">{ translate( 'Company website' ) }</FormLabel>
```

2022-08-26 00:02 UTC, kallehauge commented on client/jetpack-cloud/sections/partner-portal/company-details-form/index.tsx
> +					<FormLabel htmlFor="name">{ translate( 'Contact first and last name' ) }</FormLabel>
🙏

2022-08-26 00:02 UTC, kallehauge commented on client/jetpack-cloud/sections/partner-portal/company-details-form/index.tsx
> +					<FormLabel htmlFor="name">{ translate( 'Company website' ) }</FormLabel>
🙏

2022-08-26 12:59 UTC, atanas-dev approved these changes
LGTM

2022-08-29 14:25 UTC, merged

2022-08-29 16:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7503763

Thank you @kallehauge for including a screenshot in the description! This is really helpful for our translators.

2022-09-08 11:38 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7503763).