Features: Add signup flow related features for Newsletter and Link in Bio
Automattic/wp-calypso pull request #67053
Opened 2022-08-26 17:01 UTC by heavyweight

### Context for translation

| Newsletter Plans  | Link in Bio Plans |
| ------------- | ------------- |
|  <img width="1031" alt="Screenshot 2022-08-26 at 18 58 44" src="https://user-images.githubusercontent.com/7000684/186955520-9f3c8239-4b45-4c25-9e1c-de3dd23b3e19.png">  |  <img width="959" alt="Screenshot 2022-08-26 at 18 59 17" src="https://user-images.githubusercontent.com/7000684/186955566-0966ecd8-0561-4f87-a7db-2b5cfe41a9f2.png"> |

#### Proposed Changes

* We need to customize the plans page based on the user's signup flow.
* For Newsletter and Link in Bio we need to show custom features.

#### Testing Instructions
- Will Add

2022-08-26 17:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7498000

Thank you @heavyweight for including a screenshot in the description! This is really helpful for our translators.

2022-09-01 12:28 UTC, renancarvalho approved these changes
Worked fine! Tested tailored flows and `/start/domain/domain-only`
Good job! 🎖️

2022-09-01 12:39 UTC, alshakero requested changes
Code looks good. I have a hunch that it's over-complicated, but it works great in the tailored and normal flows, so let's ship (code-wise). Just noting some outdated copy.

**Newsletter:** 
This phrase: https://www.figma.com/file/BcUdhLlhAp7UHtQHNTI4zA/v1.-Tailored-Onboarding-%26-Launchpad?node-id=4495%3A210304

**LiB:**
https://www.figma.com/file/BcUdhLlhAp7UHtQHNTI4zA/v1.-Tailored-Onboarding-%26-Launchpad?node-id=4174%3A148599

2022-09-01 12:39 UTC, alshakero commented on packages/calypso-products/src/plans-list.tsx
> +		),
this `+` might cause translation issues. Let's keep it one string.

2022-09-01 14:51 UTC, alshakero approved these changes
Tested and regession-tested and looks great. 🚢

2022-09-01 15:34 UTC, merged

2022-09-01 16:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7498000).

2022-09-02 09:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7498000).