Condensed Features Experiment
Automattic/wp-calypso pull request #67151
Opened 2022-08-30 09:10 UTC by niranjan-uma-shankar

#### Proposed Changes

* Implements an A/B test on the signup plans step.
* The changes here try out a different visual treatment of plan features.
* Read pbxNRc-1WS for more information.

**Annual**

<img width="1496" alt="Screenshot 2022-09-01 at 6 03 45 PM" src="https://user-images.githubusercontent.com/1269602/187933762-db722dc7-07b4-483a-9ac9-9616a20fc1f7.png">

**Monthly**

<img width="1555" alt="Screenshot 2022-09-01 at 6 03 54 PM" src="https://user-images.githubusercontent.com/1269602/187933797-8e50a4e3-3bd8-4bb4-b966-b916e859fe78.png">

#### Testing Instructions

 
* Assign yourself to treatment of the experiment `calypso_signup_plans_step_optimize_202208_v1` in Abacus.
* Signup for a new account and verify that the plans step UI matches the one shown in screenshots above.
* Verify that mobile view is unchanged - this experiment is only for desktop, so mobile view should have no UI changes.
* Verify that non-EN is unaffected
* Verify that control version in unaffacted.
* Verify that you can continue to complete signup and create a site / complete a purchase.

2022-09-01 14:30 UTC, claudiucelfilip commented on client/my-sites/plan-features-comparison/index.jsx
> +					<li className={ classes }>{ this.renderFeatureItem( currentFeature, mapIndex ) }</li>
I'm getting a warning about missing "key" prop. We should probably add it to the `li` and maybe to the `div` below.

2022-09-01 14:40 UTC, claudiucelfilip approved these changes
Works as described.
LGTM

2022-09-01 18:11 UTC, donlair requested changes
I added some requests for copy tweaks but the PR works as expected. I think this is ready to launch once those updates are in-place.

2022-09-01 18:11 UTC, donlair commented on client/lib/plans/features-list.js
> +		getTitle: () => 'Priority chat and email support, 24X7.',
Change to `24/7 live chat support`

2022-09-01 18:11 UTC, donlair commented on client/lib/plans/features-list.js
> +			'Install WordPress Plugins. Choose among thousands of plugins to easily add forms, bookings, or custom fields.',
Change to `Install WordPress plugins`

2022-09-01 18:11 UTC, donlair commented on client/lib/plans/features-list.js
> +		getTitle: () => 'Unlimited premium themes for your site',
Change to `Unlimited premium themes`

2022-09-01 18:11 UTC, donlair commented on client/lib/plans/features-list.js
> +		getTitle: () => 'SFTP (Secure File Transfer Protocol) and Database access.',
Change to `SFTP and Database Access`

2022-09-01 18:11 UTC, donlair commented on client/lib/plans/features-list.js
> +		getTitle: () => 'Advanced social media marketing tools',
Change to `Advanced social media tools`

2022-09-01 18:11 UTC, donlair commented on client/lib/plans/features-list.js
> +		getTitle: () => 'Monetize your website with ads',
Change to `Earn money from ads`

2022-09-01 18:11 UTC, donlair commented on client/lib/plans/features-list.js
> +		getTitle: () => i18n.translate( 'Advanced Search Engine Optimisation (SEO) tools' ),
Change to `Advances SEO tools`

2022-09-05 14:21 UTC, niranjan-uma-shankar commented on client/my-sites/plan-features-comparison/index.jsx
> +					<li className={ classes }>{ this.renderFeatureItem( currentFeature, mapIndex ) }</li>
Fixed.

2022-09-05 14:24 UTC, merged

2022-09-05 18:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7512076

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

2022-09-16 10:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7512076).