Plugin Management: Update button style in Jetpack Cloud
Automattic/wp-calypso pull request #67359
Opened 2022-09-04 14:47 UTC by vitozev

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-09-06 15:36 UTC, grbicsanja approved these changes
LGTM!

2022-09-06 19:18 UTC, vitozev commented
@yashwin, can we easily trigger an update when we click this link?

<img width="215" alt="image" src="https://user-images.githubusercontent.com/1749918/188720395-55b2b5a3-37dc-4420-ade6-f04199c9f65c.png">

2022-09-06 21:26 UTC, rcanepa commented
Without having reviewed the code yet, I noticed that the current version is not always the right one. For instance, on one of my sites, Jetpack needs an update, but the row shows the same version for both the current and the new one.

![image](https://user-images.githubusercontent.com/3418513/188741575-db7cbfbe-664a-4645-b67a-0dabe7aede98.png)

As one can see in the screenshot, the currently installed version is 11.2-beta, but the table row says it is 11.3. Also, when I refresh the page, sometimes I see 11.2-beta appearing for less than a second before it gets replaced with 11.3.

2022-09-07 02:21 UTC, rcanepa commented on client/my-sites/plugins/plugin-management-v2/update-plugin/index.tsx
> +				<span className="update-plugin__current-version">{ plugin?.version }</span>
For some reason, `plugin.version` sometimes does not hold the current version of the plugin, but the target one.

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/3418513/188774308-aa31a3c8-2a7c-43aa-b4e1-37b537fc009c.png">

2022-09-07 02:22 UTC, rcanepa requested changes
Overall, code changes and the way things work seem reasonable to me. However, to ship these changes, we need to fix the part where we show the current and the target version of a plugin. As I mentioned a couple of times, for some reason, we are showing the same version in both places.

2022-09-07 12:33 UTC, rcanepa approved these changes
LGTM now. Thanks for making these last-minute changes. 🙇

2022-09-07 12:34 UTC, merged

2022-09-07 14:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7515395

Thank you @vitozev for including a screenshot in the description! This is really helpful for our translators.

2022-09-16 10:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7515395).