Add bulk action warning notices
Automattic/wp-calypso pull request #67465
Opened 2022-09-06 19:27 UTC by oikeme

Adding warning notice modals for bulk actions in the Edit All view when managing multiple plugins

#### Proposed Changes

* Adding a modal with a warning notice whenever bulk actions are being done using the Edit All view when managing plugins.

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-09-07 06:09 UTC, vitozev commented
**Screenshots**

![image](https://user-images.githubusercontent.com/1749918/188801259-58cb265e-dd3f-43c4-8eee-e63a60fbd8a8.png)

![image](https://user-images.githubusercontent.com/1749918/188800867-ca226ade-ccc4-458f-b701-54065ae5bc34.png)

![image](https://user-images.githubusercontent.com/1749918/188800906-bddd2a43-bc21-4872-93c8-8512047f1361.png)

![image](https://user-images.githubusercontent.com/1749918/188800944-daf5171d-cdee-48e8-8397-35b48b8fee02.png)

![image](https://user-images.githubusercontent.com/1749918/188800977-7a0b34fc-d0e2-487c-8fd0-bf0aa3220cd0.png)

2022-09-07 06:26 UTC, vitozev approved these changes
Great job, @oikeme ! All these changes are working as expected. I tested both Calypso Blue and Calypso Green – all confirmation modals are displayed, and the messages are correct ones. 

The code changes are easy to follow and looks great too!

2022-09-07 07:09 UTC, yashwin requested changes

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
>  							p: <p />,
I think we can remove the below line since we don't have any p tag

`p: <p />,`

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
>  							p: <p />,
I think we can remove the below line since we don't have any p tag

`p: <p />,`

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
>  							p: <p />,
I think we can remove the below line since we don't have any p tag

`p: <p />,`

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
>  							p: <p />,
I think we can remove the below line since we don't have any p tag

`p: <p />,`

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
> +					translate( 'Activate %(numberOfPlugins)d %(plugins)s', {
I feel like translations like these might cause an issue.

We can use

```
const translationArgs = {
   args: { count }, 
   count,
};
```
and

```
translate(
    'Activate on %(count)s plugin',
    'Activate on %(count)s plugins', // plural form
    translationArgs
 )
```

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
> +					translate( 'Deactivate %(numberOfPlugins)d %(plugins)s', {
Same here as above

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
> +						args: {
Same here as above

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
> +						args: {
Same here as above

2022-09-07 07:09 UTC, yashwin commented on client/my-sites/plugins/plugins-list/index.jsx
> +						args: {
Same here as above

2022-09-07 10:31 UTC, vitozev approved these changes
Thank you, @yashwin for making these changes! I just tested all bulk actions and messages are displayed correctly (plural/singular forms works as expected as well).

Let's merge this one.

2022-09-07 11:10 UTC, merged

2022-09-07 13:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7515232

Hi @oikeme, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Activate %(pluginsCount)d plugin`
- `Deactivate %(pluginsCount)d plugin`
- `Enable autoupdates for %(pluginsCount)d plugin`
- `Disable autoupdates for %(pluginsCount)d plugin`
- `Update %(pluginsCount)d plugin`

Thank you in advance!

2022-09-07 13:20 UTC, vitozev commented
@oikeme, I added the screenshots.

2022-09-21 12:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7515232).