(WIP) Videopress onboarding v2: domain selection
Automattic/wp-calypso pull request #67596
Opened 2022-09-09 10:11 UTC by thedebian

#### Proposed Changes
TBD

#### Testing Instructions
TBD

Fixes 1293-gh-Automattic/greenhouse

2022-09-09 20:21 UTC, roundhill requested changes
Worked well but can the display strings be localized?

2022-09-09 20:21 UTC, roundhill commented on client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
> +						Make your video site shine with a custom domain. Not sure yet ?{ ' ' }
Localize these strings?

2022-09-13 08:06 UTC, thedebian commented on client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx
> +						Make your video site shine with a custom domain. Not sure yet ?{ ' ' }
I added them in #67596 👍

2022-09-13 09:24 UTC, pgk approved these changes
worked as expected!

2022-09-13 10:03 UTC, merged