VideoPress Onboarding V2: Intro View
Automattic/wp-calypso pull request #67613
Opened 2022-09-09 18:56 UTC by roundhill

#### Proposed Changes

* Adds styles and a few tweaks to some props to get "powered by VideoPress" displaying at the bottom of the intro view.

<img width="1116" alt="Screen Shot 2022-09-09 at 12 50 04 PM" src="https://user-images.githubusercontent.com/789137/189423026-317c583f-7ee9-426e-8199-2abb43f629b0.png">
<img width="239" alt="Screen Shot 2022-09-09 at 12 50 39 PM" src="https://user-images.githubusercontent.com/789137/189423041-a4bd0d4f-e261-43b3-8e16-af1a1aea546f.png">

#### Testing Instructions

* Load up `setup/intro?flow=videopress`.
* Verify styles match the design.
* Try different screen sizes.
* Note: the button doesn't take you to the next step but I think we haven't set that up yet?
* Try a different flow like `setup/intro?flow=newsletter` and verify it still has `Jetpack powered` in the footer area.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to pxWta-1z5-p2

2022-09-12 13:19 UTC, jgcaruso approved these changes
Code looks good and site matches designs!

Only note, "powered by" is missing in landscape mode for mobile devices but it seems to be like that for "link in bio" as well.

<img width="997" alt="Screen Shot 2022-09-12 at 9 18 10 AM" src="https://user-images.githubusercontent.com/4081020/189664955-267170e3-2400-4164-8a25-6881e019be60.png">

2022-09-14 18:46 UTC, jgcaruso commented
I think this is a duplication of work (or at least partially) of what is being done in https://github.com/Automattic/wp-calypso/pull/67736

Might want to confirm which one should stay or not before merging either one.

2022-09-15 16:32 UTC, roundhill commented
> Might want to confirm which one should stay or not before merging either one.

We got this sorted out.

@eduardozulian is going to push a few CSS fixes to this by tomorrow.

2022-09-15 17:19 UTC, jgcaruso requested changes

2022-09-15 17:19 UTC, jgcaruso commented on client/landing/stepper/declarative-flow/internals/steps-repository/patterns/styles.scss
> +		.step-container__powered-by {
Is this change still needed now that a separate control is being used?

2022-09-15 17:19 UTC, jgcaruso commented on client/landing/stepper/declarative-flow/internals/steps-repository/intro/styles.scss
> +		.step-container__powered-by {
Looks like another left over css change from before the merge?

2022-09-17 18:43 UTC, evilluendas commented
I've just pushed a couple of very small tweaks to the position of the triangles on mobile, and made the progress bar background (in just this step) dark so it doesn't stand out so much.

I've noticed that this branch's Newsletter flow is slightly different to the one in trunk, but I imagine it's that they've already merged updates to trunk.

I'd like to update the poster for the video so it uses the first frame of the clip, but we can change that directly, right?

2022-09-21 14:28 UTC, roundhill commented
> I'd like to update the poster for the video so it uses the first frame of the clip, but we can change that directly, right?

Yes, just DM me the image!

2022-09-21 14:59 UTC, jgcaruso requested changes
Looks good! Video plays, page looks nice in different screen sizes.

When testing the Jetpack flow though it looks like the font colour for the main text and "Jetpack Powered" was changed from black to white (dev on left, prod on right -- ignore the font alignment difference, the windows were just different heights)

<img width="2087" alt="Screen Shot 2022-09-21 at 10 52 32 AM" src="https://user-images.githubusercontent.com/4081020/191538448-23f197c7-b605-45f1-a5b2-1f560d25fb82.png">

Not a blocker but the video also seems to take a couple seconds to start. That is probably something we'll need to optimize in the player if its possible (or maybe its like that for me because of sandboxing).

2022-09-21 21:49 UTC, roundhill commented
> When testing the Jetpack flow though it looks like the font colour for the main text and "Jetpack Powered" was changed from black to white (dev on left, prod on right -- ignore the font alignment difference, the windows were just different heights)

Fixed via 8e52744!

> Not a blocker but the video also seems to take a couple seconds to start. That is probably something we'll need to optimize in the player if its possible (or maybe its like that for me because of sandboxing).

When we get the poster image added it might help?

2022-09-21 22:01 UTC, roundhill commented
Bug? Our footer looks higher than the other flows:

<img width="1141" alt="Screen Shot 2022-09-21 at 4 00 52 PM" src="https://user-images.githubusercontent.com/789137/191618358-c8827ce1-f6b9-4606-a9f3-ca1daab92b8b.png">

Or were you happy with that positioning @evilluendas?

2022-09-22 13:24 UTC, jgcaruso commented
> When we get the poster image added it might help?

Hmm, do we show poster image for autoplay + no controls? It should also already have one by default, but something from the middle of the page.

This is probably something where that "facade" diff you were working on would come in handy. Because if the black screen is because of the video info request we won't even know what the poster is yet to check.

2022-09-22 13:31 UTC, jgcaruso approved these changes
`newsletter` flow text colour is fixed, everything else looks good to me!

2022-09-22 14:38 UTC, roundhill commented
> This is probably something where that "facade" diff you were working on would come in handy. Because if the black screen is because of the video info request we won't even know what the poster is yet to check.

Totally, maybe we should revisit the facade!

2022-09-22 14:39 UTC, merged