PlanFeatures: replace margin left based on vw, instead use translateX
Automattic/wp-calypso pull request #67665
Opened 2022-09-12 14:42 UTC by heavyweight

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-09-12 15:06 UTC, heavyweight commented
Hey @klimeryk
I couldn't reproduce the horizontal scrollbar issue with 13' Macbook and Firefox but managed to reproduce it with browserstack. Can you try this PR calypso live link to see if the issue is fixed for you?

2022-09-12 15:15 UTC, alshakero commented on client/my-sites/plan-features-comparison/style.scss
> +		.plan-features-comparison__item-annual-plan-container,
Is this change intentional?

2022-09-12 16:19 UTC, heavyweight commented on client/my-sites/plan-features-comparison/style.scss
> +		.plan-features-comparison__item-annual-plan-container,
Good catch.
Got a linter hint and the formatting of the css fooled me in the intention. There was no visible difference with this but its bad css styling making all items in monthly view orange by default and later overwriten. Pushed a fix.

2022-09-13 12:18 UTC, alshakero requested changes
The plans step is squished in non-tailored flows.

Before: 
![wordpress com_start_plans](https://user-images.githubusercontent.com/17054134/189898974-cbc4a3fd-28e8-4eb7-9be3-14eb39bde2df.png)

After:
![container-heuristic-liskov calypso live_start_](https://user-images.githubusercontent.com/17054134/189899042-ad0c37b3-ff7f-41ce-9008-19f829bde6e1.png)

2022-09-14 12:38 UTC, alshakero approved these changes
Tested tailored and non-tailored flows. On Mobile and Desktop. All works as expected.

2022-09-14 12:54 UTC, klimeryk approved these changes
Thanks for the fix - confirmed the horizontal scroll bar on the plans page is gone 👍 

Two small visual issues I noticed that I wanted to note - most likely unrelated to this PR:

There's a scrollbar in the description field - I understand it's because it's a text field? But looks a bit weird/out of place. And it's hard to navigate that field even if I do use it as a text field, with multiple lines, cause I cannot change its size.
<img width="401" alt="Screenshot 2022-09-14 at 12 50 20" src="https://user-images.githubusercontent.com/3392497/190158897-3d4c20ff-d887-4482-8a53-d68488d10931.png">

The hover state of the domain selection step looks cut off on the sides for non-featured domains:

https://user-images.githubusercontent.com/3392497/190159113-3836a635-c8a8-4693-828d-d57cca515d5f.mov

2022-09-14 12:57 UTC, heavyweight commented
Will open GH issues for Igor's feedback since they are not related to the PR

2022-09-14 12:57 UTC, merged