(WIP) Adding new launchpad flow for VideoPress!
Automattic/wp-calypso pull request #67692
Opened 2022-09-12 19:51 UTC by roundhill

#### Proposed Changes

* Adds a new launchpad checklist for VideoPress/Videomaker onboarding:

<img width="1291" alt="Screen Shot 2022-09-12 at 1 48 08 PM" src="https://user-images.githubusercontent.com/789137/189742556-7af17835-3f37-4e5f-9dac-04cbcaa89004.png">

* Can't test end-to-end yet until we have the site creation/Videomaker activation working.
* Related: D87583-code.

#### Testing Instructions

* For now you can start with http://calypso.localhost:3000/setup/intro?flow=newsletter and when you get to the launchpad, change the `flow=newsletter` query parameter to `flow=videopress` to see the VideoPress launchpad.
* Better test steps coming soon 🗡️ 

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

2022-09-22 08:27 UTC, thedebian requested changes
Code looks good.
When I uploaded a video, the launchpad task wasn't updated, so I couldn't go further and click on "launch site"
![Capture d’écran 2022-09-22 à 10 25 17](https://user-images.githubusercontent.com/1420594/191697478-4cc6e81d-29f2-490c-99f3-2fb0bdbd5be1.png)

2022-10-05 14:25 UTC, jgcaruso approved these changes
Tested alongside D87583-code and it worked as expected!

I could be completely wrong about the casing of `site` in the various actions, so those comments are not blocking at all.

2022-10-05 14:25 UTC, jgcaruso commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
> +						title: translate( 'Set up your Video Site' ),
```suggestion
						title: translate( 'Set up your Video site' ),
```
Not entirely sure about this, but to match the casing of the initial launch page, `site` is lowercased there as well.

2022-10-05 14:25 UTC, jgcaruso commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
> +						title: translate( 'Launch Video Site' ),
```suggestion
						title: translate( 'Launch Video site' ),
```
Another "not entirely sure about" comment, even though it looks odd, should `site` be lowercased?

2022-10-05 14:25 UTC, jgcaruso commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/translations.tsx
> +			translatedStrings.sidebarTitle = translate( 'Your Video Site is ready to launch!' );
```suggestion
			translatedStrings.sidebarTitle = translate( 'Your Video site is ready to launch!' );
```
here also?

2022-10-05 22:00 UTC, merged