Pattern Assembler update a11y
Automattic/wp-calypso pull request #67716
Opened 2022-09-13 09:06 UTC by bangank36

## Proposed Changes

* TBD

## Testing Instructions

* TBD

## Reference

Related to #67632

2022-09-19 08:38 UTC, miksansegundo requested changes
I have found that we can achieve the same goals without the new component and without breaking the linter rule. I tested and pushed my suggestions to [another branch](https://github.com/Automattic/wp-calypso/commit/71bb3b7c54ff44a873ea2775c0b41a557d705f3b). It looks cleaner IMO.

2022-09-19 08:38 UTC, miksansegundo commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
> +			tabIndex={ show ? 0 : -1 }
I think we do not have to break the rule `jsx-a11y/no-noninteractive-tabindex` becase we can put the logic `tabIndex={ show ? 0 : -1 }` in the interactive element (the `div` for each pattern):
```
<div
  aria-label={ item.name }
  tabIndex={ show ? 0 : -1 }
  className="pattern-selector__block-list-item" // We'll use it to focus the first item
  ...
``` 

When the pattern selector is shown, we can find the first element in the list to set the focus:

```
useEffect( () => {
  if ( show ) {
    const firstItem = patternSelectorRef.current?.querySelector(
      '.pattern-selector__block-list-item'
    ) as HTMLElement;
    firstItem?.focus();
  }
}, [ show ] );
```

2022-09-19 08:38 UTC, miksansegundo commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-layout.tsx
> +							<PatternListItem
I think the code can be simplified and we won't have to create a new component to handle the focus. We can use `:focus-within` ([docs](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within)) in the `li` in the same way we use `:hover` to show/hide the pattern action bar without handling the focus in JS:

```css
li {
  &:hover,
  &:focus-within {
    .pattern-action-bar {
      opacity: 1;
    }
  }
}
```

2022-09-19 09:39 UTC, bangank36 commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
> +			tabIndex={ show ? 0 : -1 }
Is there a problem if the pattern is focused even when we use the mouse (like clicking on the "Add a header")?

2022-09-19 09:41 UTC, bangank36 commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-layout.tsx
> +							<PatternListItem
Look how far I've gone when I missed a simple CSS fix for this matter! Thank you! At least I got to know how to use disjoint unions on type

2022-09-19 09:55 UTC, miksansegundo commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
> +			tabIndex={ show ? 0 : -1 }
I see what you mean. The focus on the first element can be confusing for users that use the mouse to open the pattern selector. Maybe better if we use your approach for this case.

2022-09-20 03:00 UTC, miksansegundo approved these changes
I added comments to improve the code a little more. Let me know what you think.

2022-09-20 03:00 UTC, miksansegundo commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
> +		show && patternSelectorRef.current?.focus();
Can we use a regular if for more clarity? I like inline conditional, but in a previous review of mine, we agreed to avoid them. 

```
if ( show ) {
  patternSelectorRef.current?.focus();
  patternSelectorRef.current?.removeAttribute( 'tabindex' );
}
```

2022-09-20 03:00 UTC, miksansegundo commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
> +				'pattern-selector--active': show,
If we are not using the class `pattern-selector--active`, shall we remove it?

2022-09-20 03:00 UTC, miksansegundo commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-action-bar.tsx
> +						tabIndex={ disableMoveUp ? -1 : 0 }
I tested with/without the `tabIndex` in the Buttons and got the same result. Can we remove them? I think the prop `disable` is working fine so the element cannot get focused.

2022-09-20 03:00 UTC, miksansegundo commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-action-bar.tsx
> +						tabIndex={ disableMoveDown ? -1 : 0 }
I think this `tabIndex` is not doing anything. Is there a reason for them?

2022-09-20 03:10 UTC, bangank36 commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-action-bar.tsx
> +						tabIndex={ disableMoveDown ? -1 : 0 }
No, you are right about disabled attribute

2022-09-20 03:11 UTC, bangank36 commented on client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/pattern-selector.tsx
> +		show && patternSelectorRef.current?.focus();
Thanks for reminder!

2022-09-20 03:46 UTC, miksansegundo commented
LGTM 🙌

2022-09-20 04:00 UTC, merged