Videopress onboarding v2 : plan selection refined
Automattic/wp-calypso pull request #67916
Opened 2022-09-16 13:59 UTC by thedebian

#### Proposed Changes

TBD

#### Testing Instructions

TBD

2022-09-21 19:20 UTC, jgcaruso requested changes
Something might be broken here... I never get to the "Choose a Plan" page.

It walks me through the following steps:
1. I paste in `/setup/chooseAPlan?flow=videopress`
2. I get redirected to `/setup/intro?flow=videopress`
3. I click next
4. I fill out my site details
5. I choose a domain (free *.wordpress.com)
6. I get sent to the Checkout page and `Premium` is in my cart ready to be purchased

2022-09-21 19:20 UTC, jgcaruso commented on client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-plan/index.tsx
> +											/>
was `disabledLabel` intentionally removed here?

_This comment makes more sense when looking at it with the side-by-side changes_

2022-09-22 08:03 UTC, thedebian commented on client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-plan/index.tsx
> +											/>
Absolutely :)

2022-09-22 14:14 UTC, jgcaruso approved these changes
After applying the patch I was able to view the "choose a plan" page, looks good!

Selecting the plan sends me to `setup/completingPurchase?flow=videopress` but the screen is blank. Not sure if this is just not implemented yet or something else might be broken?

Otherwise, code looks good and testing other flows continue to work as expected (ex `Popular` text still shows on the regular choose a plan flow)

2022-09-22 15:19 UTC, thedebian commented
> Selecting the plan sends me to `setup/completingPurchase?flow=videopress` but the screen is blank. Not sure if this is just not implemented yet or something else might be broken?

Yep, nothing to see here for now, it'll be replaced with site creation/checkout

2022-09-22 15:19 UTC, merged