Add initial changes for cropping tool
Automattic/wp-calypso pull request #67918
Opened 2022-09-16 15:19 UTC by renancarvalho

## Proposed Changes

(WIP) Add a new design for the cropping icon tool. 
@alshakero, I tried to implement most of the design changes without change much of the component behaviour, It is not 100% how the design is, but I am afraid of doing too many changes on the imageCropping component. Let me know what you think. This is still a Work in Progress.

## Testing Instructions
- Pull this branch and run yarn start
- Navigate to `/setup/intro?flow=link-in-bio or flow=newsletter`
- Go to setup step and check the image upload tool

Related to #67848
Fixes #67848

2022-11-10 18:40 UTC, alshakero requested changes
Let's add an `svh` for every `vh` rule.

2022-11-10 18:40 UTC, alshakero commented on client/components/site-icon-with-picker/style.scss
> +	min-height: 85vh;
Let's add `svh` for iPhones.

2022-11-11 12:29 UTC, alshakero requested changes
One more vh.

2022-11-11 12:29 UTC, alshakero commented on client/components/site-icon-with-picker/style.scss
> +		min-height: 60vh;
vh.

2022-11-11 15:43 UTC, merged

2022-11-11 17:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7621157

Hi @renancarvalho, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: ` Apply `

Thank you in advance!

2022-11-18 12:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7621157).