[WIP] Marketplace: Update PlanFeaturesComparison layout
Automattic/wp-calypso pull request #67958
Opened 2022-09-19 07:07 UTC by candy02058912

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-09-19 22:57 UTC, lupus2k commented on client/my-sites/plan-features-comparison/actions.jsx
> +			<PlanFeaturesActionSuggestion { ...props } />
To avoid errors on `/start/plan`: 
```suggestion
			{ props.isInMarketplace && <PlanFeaturesActionSuggestion { ...props } /> }
```

2022-09-19 22:58 UTC, lupus2k approved these changes
After fixing [this](https://github.com/Automattic/wp-calypso/pull/67958/files#r974750733), LGTM!

2022-09-20 03:19 UTC, lsl requested changes
Please get https://github.com/Automattic/wp-calypso/pull/67891 merged first. I'm not really sure modifying this component makes sense for us yet.

2022-09-22 08:50 UTC, candy02058912 commented
Will be closing this for now since we're still making fixes to go a more minimal approach.

2022-09-22 08:50 UTC, closed without merging