Update the auto-renew toggle to use a link on Purchase Details
Automattic/wp-calypso pull request #68105
Opened 2022-09-21 14:11 UTC by dzver

This component is used in several places. All other places should remain intact.

The change will replace the Toggle component with an On/Off button in the middle of the Auto-renew ON copy.

#### Proposed Changes

- The Auto-renew toggle should be visible as a link on the purchase details page.
- There should be no link if the user doesn't own the upgrade
- Domain Management and Email Management that also use this toggle should be unaffected

https://user-images.githubusercontent.com/82778/191526566-15ec4e91-48d5-4919-9acc-6a58fbd31202.mov

#### Testing Instructions

* Buy a plan, domain, and email with the store sandbox
* Go to /me/purchases, then to a purchase detail of one of these upgrades (or any other)
* Try clicking on the new link and make sure the auto-renew goes on and off
* Go to Domain Management. Make sure the toggle is unchanged there
* Go to Email Management. Make sure the toggle is also unchanged
* Add another user to your test site. Make sure they see no clickable toggles anywhere

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-09-22 02:53 UTC, southp commented
I've confirmed that it works as the test plan described. The code also looks good to me, but there is one accessibility issue: I can't focus on the new anchor-like button by tabbing, and the cursor doesn't change into a clickable pointer when hovering the mouse cursor onto it:

![on-anchor-pointer](https://user-images.githubusercontent.com/1842898/191647654-933e9b4d-7249-4f1e-8dfb-8556eb3e0271.gif)

I suppose the both might be the same issue, so the above screencast only demonstrates the cursor part :)

2022-09-22 08:10 UTC, southp approved these changes
The fix works. LGTM 🚢

2022-09-22 08:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7542517

Thank you @dzver for including a screenshot in the description! This is really helpful for our translators.

2022-09-22 21:10 UTC, DavidRothstein requested changes
I think this one clearly needs more discussion: pebzTe-j5-p2#comment-471

2022-09-23 13:51 UTC, DavidRothstein approved these changes
This approval does not actually mean I reviewed it (I didn't), but just trying to remove my "Changes requested" following the recent update to the PR -- this seems to be the only way to do it :smile:

2022-09-23 13:55 UTC, DavidRothstein commented
> recent update to the PR

Which changed the modal title that is shown after clicking "ON" from "Before you go..." to "Turn off auto-renew" (for future reference).

2022-09-23 14:10 UTC, merged

2022-09-23 14:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7542517).

2022-09-30 10:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7542517).