VP Onboarding: clear onboarding site options on flow start and flow completion
Automattic/wp-calypso pull request #68162
Opened 2022-09-22 14:45 UTC by jgcaruso

#### Proposed Changes

* clear out the site title and description on starting a new flow or completing a flow (landing on Launchpad)

#### Testing Instructions

* visit `setup/intro?flow=videopress`
* Click `Setup your video site`
* Enter a title and description, press `Continue`
* Return to `setup/options?flow=videopress`
* Your title and description should be populated
* Visit `setup/intro?flow=videopress` then click `Continue`
* Your title and description should be cleared out
* Go through the flow to the launchpad
* Try to return to `setup/options?flow=videopress`
* Your title and description should be cleared out (even though this backwards motion may not be totally allowed)

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to # 1341-gh-Automattic/greenhouse

2022-09-23 07:28 UTC, thedebian requested changes
Looking good, it's only missing the domain part, you can access it with
`const { setDomain } = useDispatch( ONBOARD_STORE );` 
(see `client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx`)

2022-09-26 11:41 UTC, pgk approved these changes
Works as expected! We can do the domain reset in a separate pr too, not a stopper

2022-09-26 14:32 UTC, jgcaruso commented
> Looking good, it's only missing the domain part, you can access it with `const { setDomain } = useDispatch( ONBOARD_STORE );` (see `client/landing/stepper/declarative-flow/internals/steps-repository/choose-a-domain/index.tsx`)

I've added the clearing of the Domain as well.

2022-09-26 15:14 UTC, thedebian approved these changes

2022-09-26 16:10 UTC, merged