Tailored Flows-Newsletter: Jetpack logo should be stuck to the bottom
Automattic/wp-calypso pull request #68290
Opened 2022-09-26 16:05 UTC by escapemanuele

#### Proposed Changes

Jetpack logo should be stuck to the bottom (not floating)

#### Testing Instructions

* Go to `http://calypso.localhost:3000/setup/intro?flow=newsletter`
* Check on desktop and mobile that the jetpack logo is on the bottom

Fixes #68213

2022-09-26 17:20 UTC, alshakero requested changes
Love a clean fix! Just please ensure the Y coordinate of the logo is the same in intro and setup steps.

2022-09-28 14:52 UTC, arcangelini approved these changes
Well done sir. Tested and looks good.

2022-09-28 15:12 UTC, merged

2022-09-29 02:13 UTC, arthur791004 commented on client/landing/stepper/declarative-flow/internals/global.scss
> +			flex-direction: column;
@escapemanuele Hiya! I'm curious why do we need this? I made the **ALL** step with a horizontal layout broken...

See p1664411235927349-slack-CRWCHQGUB

2022-09-29 02:22 UTC, arthur791004 commented on client/landing/stepper/declarative-flow/internals/global.scss
> +		@media ( min-width: 660px ) {
Is there any reason we need to specify the width rather instead of using something like `@include break-small`?

2022-09-29 02:42 UTC, arthur791004 commented
Reverted as it made the ALL step with a horizontal layout broken. See p1664411235927349-slack-CRWCHQGUB