Update features on plan change
Automattic/wp-calypso pull request #68791
Opened 2022-10-07 21:13 UTC by DustyReagan

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-10-10 23:31 UTC, obenland commented
Instead of changing the feature check, could we find a way to refresh the site's features similar to how the plan seems to get updated after checkout?

2022-10-13 06:20 UTC, lsl commented
This is pretty broken, are there any issues shipping this and fixing the approach later?

2022-10-13 06:21 UTC, lsl approved these changes
Not really sure how this works but seems to fix the issue.

2022-10-13 08:21 UTC, cpapazoglou requested changes
As Konstantin also suggested would using a `<QuerySiteFeatures siteIds={ [ siteId ] } />` component update the features and make `siteHasFeature` work without adding anything else?

BTW, thanks for your testing instructions that are testing fore regressions!

2022-10-13 17:38 UTC, DustyReagan commented
> As Konstantin also suggested would using a <QuerySiteFeatures siteIds={ [ siteId ] } /> component update the features and make siteHasFeature work without adding anything else?

Thanks @obenland, and @cpapazoglou for pointing out `QuerySiteFeatures`. I've been trying to get it to work using that component, but haven't had much luck. I'm stuck wondering about how `const hasAtomicFeature` is assigned a value when created and then used inside a `useEffect`. How does that `hasAtomicFeature` value get updated using `QuerySiteFeatures`?

2022-10-13 20:11 UTC, obenland commented
Discussed the PR and possible solutions in Slack (p1665685849250559-slack-CKZHG0QCR). I think keeping the Ref implementation but using it with a feature check is probably the easiest fix here.

2022-10-13 20:34 UTC, paulopmt1 approved these changes
LGTM. With this fix, I was not able to reproduce the issue with free plugins. Good job!

2022-10-13 20:36 UTC, merged