Jetpack Cloud: Update Jetpack Social Pricing
Automattic/wp-calypso pull request #68896
Opened 2022-10-11 10:23 UTC by pablinos

#### Proposed Changes

Now that the Jetpack Social plan has launched, this removes the placeholder plan from the pricing page, along with the custom 'Coming soon!' label.

#### Testing Instructions

- Using the live branch or local version of Jetpack Cloud
- go to `/pricing`
- Check that the Social product doesn't display 'Coming soon!' and that the Get link takes you to the checkout for the plan.
- Also check that the 'More about Social' link opens the modal with the product information

**Before**

<img width="624" alt="image" src="https://user-images.githubusercontent.com/96462/195065824-aee60257-b3a2-465b-aa64-4a5593ca1dc9.png">

**After**

<img width="624" alt="image" src="https://user-images.githubusercontent.com/96462/195065902-66b596a5-56e0-4a96-a0a5-7fbe949ae185.png">

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

2022-10-11 10:50 UTC, danielpost requested changes
<img width="404" alt="image" src="https://user-images.githubusercontent.com/1713699/195071024-4cf5ece3-b4dd-4ae0-a3c4-b2529da4f9bc.png">

The pricing info on the modal seems wrong (90% off for the first year).

2022-10-11 10:56 UTC, elliottprogrammer commented
When we initially made Social an "external" product and added the "Coming soon" tag, we also moved the Social card's position next to the CRM product.
Therefore, one last step that we'll want to do here is move the order of the Social card back to where it was; from it's current position back to the _first_ position under the "All products" heading, as described here: p1HpG7-i4a-p2#comment-57125

So the order should look like this:

Social | Boost
-- | --
Scan | Anti Spam
Search | CRM
Backup | VideoPress

I suppose this could be done in a separate PR, but it might make more sense to just include it here. Whatever you think, it's your call. 🙂

2022-10-11 14:19 UTC, pablinos commented
Thanks @elliottprogrammer. I'm always happy to promote Jetpack Social first! I've changed the order in 7293744

2022-10-11 14:22 UTC, pablinos commented
> The pricing info on the modal seems wrong (90% off for the first year).

Nice spot! It's a bit hacky still, but I've made the label conditional on the discount duration. That's a bit of a magic number, either 1 or undefined, so I've taken it to be the number of months for the offer, with the default being a year.

2022-10-11 19:06 UTC, elliottprogrammer approved these changes
Tested and works as expected. Code looks good. I don't see any issues. 🙂
LGTM! 👍

2022-10-12 08:50 UTC, danielpost approved these changes

2022-10-12 08:54 UTC, merged

2022-10-12 09:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7576046

Thank you @pablinos for including a screenshot in the description! This is really helpful for our translators.

2022-10-21 08:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7576046).