Jetpack Search: don't change jetpack_search to wpcom_search
Automattic/wp-calypso pull request #69505
Opened 2022-10-27 04:55 UTC by trakos

#### Proposed Changes

Currently, when purchasing a Jetpack Search plan on wpcom site (simple or atomic), we automatically change the product slug from jetpack_search to wpcom_search, and from jetpack_search_monthly to wpcom_search_monthly.

In this PR I'm removing that swap, as we now want to use jetpack_search variant for both Jetpack and wpcom sites.

#### Testing Instructions

* Wait for backend changes to be released (or sandbox public-api with diff D90829-code applied, if you're from A8C).
* Visit `http://calypso.localhost:3000/checkout/<your-site>/jetpack_search`, where your-site is base URL of simple or atomic site.
* Verify that the purchased product is Jetpack Search, and not WPCOM Search (for instances in payments admin).
* Next, verify that the site with this plan behaves the same as with WPCOM Search, for both simple and atomic.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

2022-10-27 04:56 UTC, trakos commented
Marking as blocked/draft until D90829-code is merged.

2022-10-27 18:53 UTC, gibrown reviewed
Uncertain, but do we also need to fix it here: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/purchase-product/controller.js#L87

2022-10-27 20:09 UTC, mattgawarecki commented
These code changes jibe with what I tried in my own experiments on the issue. Once everything's ready for review, I'll swing back around for a final pass with functional testing. 👍

2022-10-27 20:23 UTC, trakos commented
Thanks for the reviews!

> Uncertain, but do we also need to fix it here: https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/purchase-product/controller.js#L87

I think that part is only responsible for swapping `jetpack_search` to `jetpack_search_monthly` and `wpcom_search` to `wpcom_search_monthly` and back, depending on the interval.

By the way, I've only removed auto-swapping from jetpack_search to wpcom_search, but I didn't remove support for the wpcom_search product slug. Checkout for wpcom_search won't swap to jetpack_search.  There are still some references to wpcom_search around. Plugin always uses `jetpack_search` slug regardless of whether a site is wpcom or jetpack when directing to checkout.

I thought that this is a safer approach, since I was afraid of breaking manual renewals or some more obscure flows if we'd remove support for wpcom variant alltogether.

2022-11-08 22:47 UTC, gibrown requested changes
Cool, I think this is ready for review, and is probably one of the blockers to testing on wpcom sites. From what I see/understand the code looks good.

I tried testing it though and it does require that we first ship D90829

I think once that is shipped we can retest and merge this.

2022-11-09 10:08 UTC, trakos commented
I've shipped D90829-code, so this should be ready for review. You can use the provided calypso.live link to purchase `jetpack_search`: `<calypso.live for this PR>/checkout/<your-simple-site-url>/jetpack_search`. Before my changes the site would get wpcom_search product, now it will be jetpack_search.

2022-11-09 15:06 UTC, gibrown approved these changes
LGTM

2022-11-09 18:37 UTC, merged