Email open stats card in stats dashboard
Automattic/wp-calypso pull request #69526
Opened 2022-10-27 15:58 UTC by JuanLucha

#### Proposed Changes

This PR adds a new card in the stats dashboard: the Emails Open tab. This tab indicates the number of people opening each email sent for new post. See the screenshot:

<img width="613" alt="Screenshot 2022-10-26 at 17 19 51" src="https://user-images.githubusercontent.com/3832570/198337237-deab0e0b-51fb-4f58-89e4-cb4b13f963ec.png">

It also adds a feature flag ('newsletter/stats') for shielding the development while this is done.

#### Testing Instructions

As the endpoint is returning mocked data at this point, the testing instructions are:

- pull this PR code locally
- start the development environment with `yarn start`
- go to your local calypso url (`http://calypso.localhost:3000` most likely?)
- go to the stats page
- you should see the `Emails open` card.
- stop the development environment.
- go to `config/development.json` and set the feature flag (`newsletter/stats`) to `false`
- start the development environment again (`yarn start`)
- go to the stats page again
- you shouldn't see the `Emails open` card anymore

Related to https://github.com/Automattic/wp-calypso/issues/69431

2022-10-27 22:52 UTC, phcp requested changes
Overall looks good, just added a few suggestions.

2022-10-27 22:52 UTC, phcp commented on client/my-sites/stats/stats-strings.js
> +		value: translate( 'Views', { context: 'Stats: module row header for number of post views.' } ),
Should this one be "Opens" instead of Views?

2022-10-27 22:52 UTC, phcp commented on config/development.json
> +		"newsletter/stats": false
Usually, the flags are using a more generic label in the first part. In this case, the opposite `stats/newsletter` would fit better.

2022-10-27 22:52 UTC, phcp commented on config/development.json
> +		"newsletter/stats": false
The flags are also sorted alphabetically. Same for the other envs.

2022-11-04 11:14 UTC, yansern commented
This is great for POC (proof of concept). However, we need to have a more realized product planning to move forward. Temporaily putting this PR on hold.

2022-11-11 17:54 UTC, jeffgolenski commented
@keoshi Just noting that this is being done within the stats dashboard. I'm going to update our Traffic page redesign to accommodate it @JuanLucha @phcp . Just looping in @saygunnyc since I saw he's also consulting on it. I'll add a comment to the Newsletter Stats PT once I update our design p2 post. Thanks y'all cc @ebinnion

2022-11-14 18:48 UTC, saygunnyc commented
@jeffgolenski, @keoshi We haven't yet kicked off the design for this project. But I'm really glad to see you guys are taking a look at this 🙌  as we had conversations about how the new stats work should inform this. While this was proposed by the Apex team as a starting point, we also discussed introducing an Email stats tab in the future for more in-depth information briefly as an FYI.

2023-01-03 09:30 UTC, JuanLucha commented
Closing because it's being handled in a different branch / PR, as part of a more elaborate release plan. Thanks all for the review. All the suggestions are being used in the next PRs for this matter. 🙇

2023-01-03 09:30 UTC, closed without merging