Implement white login for all /log-in routes
Automattic/wp-calypso pull request #69598
Opened 2022-10-29 07:09 UTC by niranjan-uma-shankar

#### Proposed Changes

* Adds the white login background for all `/log-in` routes.

#### Testing Instructions

* TBD

2022-10-31 13:56 UTC, simison commented
#### "or visit site" -link

With URL like `/log-in?site=SITE_SLUG&redirect_to=%2Fhome%2FSITE_SLUG` we add "or visit SITE" link which is too close to the title in reskin:

<img width="587" alt="Screenshot 2022-10-31 at 15 18 55" src="https://user-images.githubusercontent.com/87168/199017369-af68c220-faaf-4180-9c23-cb4e1ca196ca.png">

Original:

<img width="540" alt="Screenshot 2022-10-31 at 15 18 52" src="https://user-images.githubusercontent.com/87168/199017389-58ac29d5-f1f3-48b5-91f8-9305b58e187e.png">

Might've been pre-existing and thus not a blocker.

####  Jetpack connection shouldn't get redesign

We should leave Jetpack (and Woo, Sensei, Gravatar?) flows out for the first deploy, and handle each of the branded connection flows separately to make scope a bit smaller and more manageable.

Test:
- Create a new Jetpack site (e.g. using Jurassic Ninja)
- Connect Jetpack, but in make sure you're not logged in at .com in the same browser session
- Replace the following `https://wordpress.com/log-in/jetpack?site` URL with your local dev or Calypso Live link.
- Alternatively you can open `/log-in/jetpack?site` directly without params but your testing will be limited.

2022-11-04 23:28 UTC, niranjan-uma-shankar commented
Thanks for the review @simison . I've fixed the issues you reported, and the PR is ready for another review.

2022-11-17 11:25 UTC, simison approved these changes
Looking good now!

Tested regular login paths as well as "return to site" and Jetpack, desktop and mobile.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/87168/202434024-ff79de8e-a248-43f7-938f-f7ced2fd3898.png">

2022-11-17 13:56 UTC, simison requested changes
Tested also WooCommerce.com login path (start from woocommerce.com/start and choose "login").

There are some styles leaking into this page so Woo also has to be excluded.

**Before**

<img width="1201" alt="Screenshot 2022-11-17 at 15 55 21" src="https://user-images.githubusercontent.com/87168/202465040-713770a3-9613-4b3d-aa53-884dca09e238.png">


**After**

<img width="1198" alt="Screenshot 2022-11-17 at 15 55 25" src="https://user-images.githubusercontent.com/87168/202465007-203d7c98-b45a-48a5-80eb-0fed0ed02721.png">

2022-11-18 04:29 UTC, niranjan-uma-shankar commented
> There are some styles leaking into this page so Woo also has to be excluded.

I had already excluded Woo [in this line](https://github.com/Automattic/wp-calypso/pull/69598/files#diff-70d559b4bf87a9a87b3867b04d7c4ced71385c5bf21e7dc804f1da27b963b64dR174) but the style ordering is somehow affected. Looks like the only effect is that the login button disabled state color is not getting applied - I pushed in a change to fix this. 

**Production** ([Link](https://wordpress.com/log-in/en-gb?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dcd777c81e02dfc76d4d0dae2f1a9a55e19d8acff84cfac13d1f0c410ee615d26%26redirect_uri%3Dhttps%253A%252F%252Fwoocommerce.com%252Fwc-api%252Fwpcom-signin%253Fnext%253Dstart%26blog_id%3D0%26wpcom_connect%3D1%26authorize%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login&client_id=50916&signup_url=%2Fstart%2Fwpcc%2Foauth2-user%3Fref%3Doauth2%26oauth2_redirect%3Dhttps%253A%252F%252Fpublic-api.wordpress.com%252Foauth2%252Fauthorize%252F%253Fresponse_type%253Dcode%2526client_id%253D50916%2526state%253Dcd777c81e02dfc76d4d0dae2f1a9a55e19d8acff84cfac13d1f0c410ee615d26%2526redirect_uri%253Dhttps%25253A%25252F%25252Fwoocommerce.com%25252Fwc-api%25252Fwpcom-signin%25253Fnext%25253Dstart%2526blog_id%253D0%2526wpcom_connect%253D1%2526authorize%253D1%2526wccom-from%2526calypso_env%253Dproduction%2526jetpack-code%2526jetpack-user-id%253D0%2526action%253Doauth2-login%26oauth2_client_id%3D50916))

<img width="1269" alt="Screenshot 2022-11-18 at 9 58 41 AM" src="https://user-images.githubusercontent.com/1269602/202616984-fcc4729a-61ff-4ad3-9493-69e3fb48cf4f.png">

**This PR**
<img width="1299" alt="Screenshot 2022-11-18 at 9 58 55 AM" src="https://user-images.githubusercontent.com/1269602/202617006-c84c0b23-e428-4970-85c6-78e7f5760ed0.png">

2022-11-18 08:47 UTC, simison commented
> Looks like the only effect is that the login button disabled state color is not getting applied - I pushed in a change to fix this.

There were some tiny typographic changes as well that are still present; size and thickness of the heading most notably. I also think "font smoothing" isn't getting applied on new version because everything looks slightly thicker. Anti-aliasing was enabled in https://github.com/Automattic/wp-calypso/pull/54196 — you can read more at p58i-aHm-p2

2022-11-18 08:49 UTC, simison commented on client/layout/logged-out.jsx
> +			Boolean( currentQuery?.client_id ) === false;
Should you include `isJetpackWooDnaFlow` or `isWoo` check here too?

2022-11-18 09:50 UTC, simison commented
Looking closer, font aliasing seems to be active but something is wrong with font file. 


```css
.woo * {
    font-family: proxima-nova,sans-serif;
}
```

**This PR**
<img width="619" alt="Screenshot 2022-11-18 at 11 41 08" src="https://user-images.githubusercontent.com/87168/202670974-5a0dbefe-7d22-43b7-8f31-789156839cbf.png">

**Production**
<img width="640" alt="Screenshot 2022-11-18 at 11 41 05" src="https://user-images.githubusercontent.com/87168/202670979-50608afa-f9a2-4839-b21f-2308d028d5f4.png">

Note the differences in "G" and "e" and [compare with sample](https://fonts.adobe.com/fonts/proxima-nova). Production is correct.

I also don't see "proxima-nova" font get loaded anywhere in Networks tab, in HTML nor in [Calypso codebase](https://github.com/Automattic/wp-calypso/search?q=proxima-nova).

(Aside, fallback list is just "sans-serif" instead of [more complete list](https://github.com/Automattic/wp-calypso/blob/8ad918cd9844179f1195cb227e3815e58a9ed4ed/packages/typography/styles/variables.scss#L10-L11).)

2022-11-18 12:18 UTC, simison commented on client/login/magic-login/index.jsx
> +				{ this.renderGutenboardingLogo() }
Nit and we can leave for another PR; let's rename this to something generic to remove "gutenboarding".

2022-11-18 12:45 UTC, niranjan-uma-shankar commented
> Note the differences in "G" and "e" and [compare with sample](https://fonts.adobe.com/fonts/proxima-nova). Production is correct.

Looks like this is seen with the calypso.live link but when I use local calypso, then I don't see any difference in the UI between production and this PR, as shown in the screenshots [here](https://github.com/Automattic/wp-calypso/pull/69598#issuecomment-1319529421).

2022-11-18 13:15 UTC, simison commented
Nice, just had the same thought that it might be just calypso.live stopping the font from loading. All good from my side then!

2022-11-18 13:15 UTC, simison approved these changes

2022-11-21 03:45 UTC, merged