Pre Cancellation Modal - add tracking events
Automattic/wp-calypso pull request #69685
Opened 2022-11-02 06:21 UTC by ciprianimike

#### Proposed Changes

Add tracking events to the Pre Cancellation Modal,

#### Feature Flags:
- URL query: ?flags=pre-cancellation-modal
- Shell command: ENABLE_FEATURES=pre-cancellation-modal yarn start

#### Testing Instructions
1. Visit the Calypso purchases page: http://calypso.localhost:3000/me/purchases
2. Select different plans and verify the Tracking events bound to the Pre Cancellation Modal buttons.

#### Screenshot
<img width="674" alt="Screenshot 2022-11-02 at 07 20 56" src="https://user-images.githubusercontent.com/5706607/199413183-c6ec54e5-6b8f-4b2b-8d3b-739456ab65bb.png">

#### Related to https://github.com/Automattic/martech/issues/1222

2022-11-04 04:01 UTC, southp requested changes

2022-11-04 04:01 UTC, southp commented on client/me/purchases/pre-cancellation-dialog/index.tsx
> +import { recordTracksEvent } from 'calypso/state/analytics/actions';
Here is a great case that how the same naming with different semantics can be really confusing, even if they are from the different modules :)

To your surprise the Tracks event won't fire here. You can verify it by running `localStorage.setItem('debug', 'calypso:analytics');` in the console and watch the User Messages tab upon clicking the buttons. 

The reason is that `recordTracksEvent()` from `calypso/state/analytics/actions` is a redux action that needs to bind to a redux state to work. A typical way is to use `connect` from `react-redux` package to "connect" it as a component prop. Here is a good example: https://github.com/Automattic/wp-calypso/blob/trunk/client/components/marketing-survey/cancel-purchase-form/step-components/business-at-step.jsx#L76 . It's the best when we absolutely want to decouple this function from external dependencies, which is a typical case when we write unit tests for a component by Jest or Enzyme.

So what if we don't want it to be a prop but just a regular function? You will need to import it from `calypso/lib/analytics/tracks` instead, e.g. https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/anchor-fm-design-picker.tsx#L10

It's up to you to choose which way you prefer here :)

2022-11-04 04:19 UTC, southp commented
One more thing: once we deploy it, let's make sure to register the new events following the instruction here: PCYsg-mUj-p2

2022-11-04 10:48 UTC, ciprianimike commented
@southp thanks for the info. I pushed a commit, verified the two e events and registered them.
Here the 2 PRs:
- Event [calypso_pre_cancellation_modal_cancel_plan](https://github.com/Automattic/tracks-events-registration/pull/1169)
- Event [calypso_pre_cancellation_modal_keep_plan](https://github.com/Automattic/tracks-events-registration/pull/1168)

I opted for the function approach, to keep the component simpler.

https://user-images.githubusercontent.com/5706607/199954941-c1ae0937-df10-40b1-a5d7-cd1f962c98d0.mp4

2022-11-05 17:37 UTC, ciprianimike commented
@southp james the updated PRs for tracking events are here:
- Cancel plan event: https://github.com/Automattic/tracks-events-registration/pull/1170
- Keep plan event: https://github.com/Automattic/tracks-events-registration/pull/1170

I added other attributes to allow colleagues to better profile the behavior of the new modal window.

2022-11-07 12:14 UTC, southp approved these changes
This looks pretty good. Thanks for the update @ciprianimike

2022-11-09 15:04 UTC, merged