Stats: Swapping Search and Countries components
Automattic/wp-calypso pull request #69841
Opened 2022-11-08 04:03 UTC by grzegorz-cp

#### Proposed Changes

* using a feature flag and replacing `Search` and `Countries` StatsModules with the recently created component with horizontal bars
* extending horizontal bar and stats card components to accept a hero item placed before the component's header (e.g. world map), allowing for items that don't have any click interaction
* adding a component to render country flags

#### Testing Instructions

* Navigate to the main Stats page either on a local instance or the test URL from the comment below
* append ?flags=stats/new-stats-module-component to the URL
* verify that `Search` component has horizontal bars
* verify that `Countries` component has horizontal bars

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #69044

2022-11-08 20:06 UTC, jsnmoon requested changes
Changes look reasonable, but I'm running into this bug with the Search module:

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/4044428/200664147-220e5a43-6fd4-45a4-b97a-ce28c8d0833a.png">

2022-11-09 00:48 UTC, jsnmoon approved these changes
Looks good! Ship whenever you're ready.

2022-11-09 00:48 UTC, jsnmoon commented on client/my-sites/stats/stats-list/stats-list-card.jsx
> +	} );
```suggestion
    // Search doesn't have items sorted by value when there are 'Unknown search terms' present.
	const barMaxValue = Math.max( ...data?.map( item => item.value ).filter( Number.isFinite ) );
```

A little code golf for fun 🙂 
(Warning: Hasn't been checked for edge cases!)

2022-11-09 00:50 UTC, grzegorz-cp commented on client/my-sites/stats/stats-list/stats-list-card.jsx
> +	} );
Oh, I like it! Thanks, I'll merge and test.

2022-11-09 03:32 UTC, merged