Jetpack pricing: add open-source section
Automattic/wp-calypso pull request #70034
Opened 2022-11-15 15:12 UTC by monsieur-z

### Changes proposed in this Pull Request

This PR adds a section mentioning open-source to the Jetpack pricing page.

Context: document linked in p1HpG7-j1R-p2

### Testing instructions

- Spin-up the pricing page in Cloud, using the live link below, or by running this branch locally
- Check that the open-source section looks like the capture below

### Screenshots
<img width="1036" alt="Screen Shot 2022-11-15 at 10 11 11 AM" src="https://user-images.githubusercontent.com/1620183/201954689-4f5d8d51-3bec-4890-825f-66bacef79902.png">

2022-11-15 15:20 UTC, monsieur-z commented on client/my-sites/plans/jetpack-plans/open-source/style.scss
> +	font-size: 1.5rem !important;
Not ideal, but `h2` in Calypso blue have a high specificity.

2022-11-15 15:20 UTC, monsieur-z commented on client/my-sites/plans/jetpack-plans/product-store/need-more-info/style.scss
> -	background-color: var(--color-surface);
A white background looked odd in Calypso blue.

2022-11-15 15:33 UTC, keoshi requested changes
Hey, @monsieur-z — this is looking good both on desktop and mobile!

The only notes I have are in relation to the typography in the title. Could we maybe approximate the weight and size to the “Need more info?” heading so that this section is more consistent with the rest of the page?

Before | After
--|--
Calypso Blue
<img width="942" alt="image" src="https://user-images.githubusercontent.com/390760/201959199-4393c8c3-87cb-438b-bbd7-153b2f60cfe0.png"> | <img width="893" alt="image" src="https://user-images.githubusercontent.com/390760/201959558-8fc4bf64-d026-4120-8613-8c6f3e04f0de.png">
Calypso Green
<img width="817" alt="image" src="https://user-images.githubusercontent.com/390760/201959252-9b84b13b-1938-4f1c-b7c4-4ac1bf792bde.png"> | <img width="804" alt="image" src="https://user-images.githubusercontent.com/390760/201959931-14b5b582-9a34-4310-bc36-4fce7a8f9a6d.png">

Thanks for doing this!

2022-11-15 20:03 UTC, monsieur-z commented
> Hey, @monsieur-z — this is looking good both on desktop and mobile!
> 
> The only notes I have are in relation to the typography in the title. Could we maybe approximate the weight and size to the “Need more info?” heading so that this section is more consistent with the rest of the page?
> 
> Before	After
> Calypso Blue	
> <img alt="image" width="942" src="https://user-images.githubusercontent.com/390760/201959199-4393c8c3-87cb-438b-bbd7-153b2f60cfe0.png">	<img alt="image" width="893" src="https://user-images.githubusercontent.com/390760/201959558-8fc4bf64-d026-4120-8613-8c6f3e04f0de.png">
> Calypso Green	
> <img alt="image" width="817" src="https://user-images.githubusercontent.com/390760/201959252-9b84b13b-1938-4f1c-b7c4-4ac1bf792bde.png">	<img alt="image" width="804" src="https://user-images.githubusercontent.com/390760/201959931-14b5b582-9a34-4310-bc36-4fce7a8f9a6d.png">
> Thanks for doing this!

Sure thing!

2022-11-15 22:25 UTC, elliottprogrammer approved these changes
Tested in Calypso blue and green. Everything looks all good to me. Code looks good, I don't see any issues.
LGTM! 👍

2022-11-15 22:53 UTC, keoshi approved these changes
Looks great to me! 🚢

2022-11-16 14:00 UTC, merged

2022-11-16 16:25 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7626331

Thank you @monsieur-z for including a screenshot in the description! This is really helpful for our translators.

2022-11-24 20:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7626331).