Make "Issue x license" button sticky when scrolled below the viewport
Automattic/wp-calypso pull request #70335
Opened 2022-11-23 13:34 UTC by yashwin

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

2022-11-24 06:23 UTC, yashwin commented on client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
> -		padding: 2;
I removed this as it didn't have any effect.

2022-11-28 18:59 UTC, jeffgolenski commented
@yashwin! Tremendous work my friend. I just have 2 pieces of feedbackand I think we'll be good to go. Here's a video of my test walkthrough:

https://user-images.githubusercontent.com/214813/204356821-a6856321-3ea8-443a-ad42-5486dad6c542.mov

1. Small detail. The drop shadow leaks over into the sidebar on the x-axis. Shown here:
![Screen Shot 2022-11-28 at 1 48 48 PM](https://user-images.githubusercontent.com/214813/204357988-5eedb07b-6b5a-42c2-a23a-901ac114c9b9.png)


I think we can fix this by changing line 61 to `box-shadow: 2px 2px 2px 0 rgb(0 0 0 / 8%);` Which will leave us with this:

![Screen Shot 2022-11-28 at 1 55 55 PM](https://user-images.githubusercontent.com/214813/204358118-1a7486de-80ed-4a2b-8a3e-5ea7f3c268b8.png)


2. Bigger issue: After I click "add" on a site, that entire row stays highlighted and all other rows are grayed out. The highlight is good, but keeping all other rows grayed out makes them look disabled. Can we ensure the opacity of all other rows remains at 100% so folks know they can select other "add" buttons? Any row that shows "Selected" can continue to be highlighted with the drop shadow as you currently have! 

3. Unsure if this is just a testing bug, but I'm noticing that if I try and click "Add" on a second site it takes me right to the licenses screen instead of allowing me to continue selecting products. 

Thank you sir!

2022-11-28 19:01 UTC, jeffgolenski requested changes

2022-11-28 19:01 UTC, jeffgolenski commented on client/jetpack-cloud/sections/agency-dashboard/sites-overview/style.scss
> +		box-shadow: 0 4px 4px 0 rgb(0 0 0 / 8%);
Let's change this to `box-shadow: 2px 2px 2px 0 rgb(0 0 0 / 8%);` so the shadow doesn't "bleed" into the sidebar, please!

2022-11-29 10:24 UTC, yashwin commented
Thanks for the review, @jeffgolenski.

> 1.  The drop shadow leaks over into the sidebar on the x-axis. 

I have updated the box-shadow

<img width="1678" alt="Screenshot 2022-11-29 at 3 48 37 PM" src="https://user-images.githubusercontent.com/10586875/204503025-f47703dc-c154-44a0-98df-0ae37108337a.png"> 

> 2. After I click "add" on a site, that entire row stays highlighted

I agree, but this was as per the [design](NjsJ3dtmoE6xOulWfT0sE5-fi-2870%3A51828&t=nSIerj2CxJnlCZNL-0). Let me know if we still need to change this. I'll create a new ticket to address this.

> 3.  I'm noticing that if I try and click "Add" on a second site it takes me right to the licenses screen instead of allowing me to continue selecting products.

I see the confusion here. But, this is as per the [design](NjsJ3dtmoE6xOulWfT0sE5-fi-2873%3A56710&t=nSIerj2CxJnlCZNL-0) too. I'm happy to create a ticket if this behavior needs to change. 

Thanks again for your wonderful review!

2022-11-29 22:09 UTC, jeffgolenski commented
@yashwin 

> I agree, but this was as per the [design](https://github.com/Automattic/wp-calypso/pull/NjsJ3dtmoE6xOulWfT0sE5-fi-2870%3A51828&t=nSIerj2CxJnlCZNL-0). Let me know if we still need to change this. I'll create a new ticket to address this.

Absolutely. Now that we're seeing it live I think we should modify. Hypothetical designs sometimes need refinement once we see them in action! Just to clarify:

The rows should stay highlighted when a customer clicks "add" to add a license. All rows that show the "Selected" label should remain with the shadow. No rows should have their opacity reduced... like so...

![issue multiple licenses](https://user-images.githubusercontent.com/214813/204658020-441e7b38-8b46-4d7d-8ea9-5ee44f7d83fc.png)

> I see the confusion here. But, this is as per the [design](https://github.com/Automattic/wp-calypso/pull/NjsJ3dtmoE6xOulWfT0sE5-fi-2873%3A56710&t=nSIerj2CxJnlCZNL-0) too. I'm happy to create a ticket if this behavior needs to change.

Just dropping a quick video to help me explain the issue better! Sorry if I was unclear! A customer should be able to click "add" on as many sites / products as they want and then proceed to the next screen when ready.


https://user-images.githubusercontent.com/214813/204659118-eddc3364-2e62-4b5b-a0d5-0d6e6bda36c7.mov

2022-11-30 06:57 UTC, yashwin commented
@jeffgolenski, thanks for the clarification and design.

> The rows should stay highlighted when a customer clicks "add" to add a license. All rows that show the "Selected" label should remain with the shadow. No rows should have their opacity reduced... like so...

Sure, I have created a ticket - 1202619025189113-as-1203462995555473 to address this.

> A customer should be able to click "add" on as many sites/products as they want and then proceed to the next screen when ready.

I see what you are mentioning here. This is something that was decided as V2 of this feature. You can follow the discussion - p1HpG7-i8q-p2#comment-57484

2022-11-30 16:01 UTC, jeffgolenski commented
Brilliant. Thanks for all your hard work, as always @yashwin 

> This is something that was decided as V2 of this feature. You can follow the discussion -

Isn't adding multiple products the point the this project though? If we only allow them to select and proceed with 1 license from this screen I think we've just added an extra step?

2022-12-02 06:30 UTC, yashwin commented
> If we only allow them to select and proceed with 1 license from this screen I think we've just added an extra step?

We are currently allowing multiple licenses per site, not multiple licenses for multiple sites.

2022-12-02 19:09 UTC, jeffgolenski commented
@yashwin 

> We are currently allowing multiple licenses per site, not multiple licenses for multiple sites.

Ohhhh. Okay. That makes sense now. I was unaware of that. Please carry on.

2022-12-12 09:08 UTC, vitozev approved these changes
LGTM! It looks like there are some tests failing, once we fix them, we can ship this PR.

2022-12-12 09:57 UTC, merged