Stats: Deprecate feature flag "stats/new-main-chart" within shared components
Automattic/wp-calypso pull request #70564
Opened 2022-11-30 03:56 UTC by dognose24

#### Proposed Changes

* Introduce prop isLegacy to component `StatsNavigation`.
* Refactor component `StatsDatePicker` with the short title.
* Refactor component `StatsPeriodNavigation` with the new structure.
* Refactor component `Delta` with new suffix styles.
* Refactor modernized `StatsNavigation` styles.
* Refactor modernized `FormattedHeader` styles.
* Remove the modernized page header styles file.

#### Testing Instructions

> Note: The instructions to show the Store and Ads pages can be found at https://github.com/Automattic/wp-calypso/pull/69661 and https://github.com/Automattic/wp-calypso/pull/69743.

* Spin up this change with the Calypso Live link.
* Navigate to the Stats `Traffic`, `Insights`, `Store`, and `Ads` pages.
* Ensure the styles are the same as the previous ones.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #70209

2022-12-06 23:28 UTC, jsnmoon requested changes
The changes look reasonable, but this PR needs testing instructions for the Google My Business tab of Calypso Stats.

2022-12-06 23:28 UTC, jsnmoon commented on client/my-sites/google-my-business/stats/index.js
> +				/>
How can I test this?

2022-12-09 08:52 UTC, dognose24 commented on client/my-sites/google-my-business/stats/index.js
> +				/>
@jsnmoon Thanks for the information `p1670518452086579-slack-C0438NHCLSY` about making the `Google My Business` tab appear, which I have updated to the test instructions. I have tested this PR on the `Google My Business` page, and it works as expected. 🙇🏼

<img width="1091" alt="截圖 2022-12-09 下午4 50 59" src="https://user-images.githubusercontent.com/6869813/206662663-c39d8b07-06f0-48f1-8a1e-d314c7e9ece3.png">

2022-12-10 00:14 UTC, jsnmoon requested changes
Looks good! I want to do one more review after merge conflicts have been resolved, given the large size of this PR.

2022-12-12 04:25 UTC, dognose24 commented
> Looks good! I want to do one more review after merge conflicts have been resolved, given the large size of this PR.

Of course! The [trunk merging](https://github.com/Automattic/wp-calypso/pull/70564/commits/c899d64d0333b9541aa787cede2e71ffcbe0cfb5) has been done.

2022-12-13 00:18 UTC, jsnmoon requested changes
This change appears to add non-functional period navigation buttons to [the Stats Overview pages](https://wordpress.com/stats/day).

|Before|After|
|-|-|
|<img width="1060" alt="image" src="https://user-images.githubusercontent.com/4044428/207193676-18300f05-6983-4b30-90c5-ee05e22bf739.png">|<img width="1076" alt="image" src="https://user-images.githubusercontent.com/4044428/207193440-75f5baf7-cf50-4a99-8571-5bf3163d2318.png">|

Is this caused by this PR? If so, could we prevent the period buttons from rendering on the overview pages?

2022-12-13 07:10 UTC, dognose24 commented
> This change appears to add non-functional period navigation buttons to [the Stats Overview pages](https://wordpress.com/stats/day).

The period navigation buttons appeared there intentionally. I think it was missing due to the [feature flag](https://github.com/Automattic/wp-calypso/pull/70564/files#diff-c48db36d0f71bd2871975d28a9aaeca7d92c3bcfc04e227e1eddee46109dd285L58).

> Is this caused by this PR? If so, could we prevent the period buttons from rendering on the overview pages?

No. The period navigation buttons were broken because of the [routes I tried to fix in another PR](https://github.com/Automattic/wp-calypso/pull/70613).

Since #70613 is merged into the trunk, I believe everything in this PR will be fine after merging the trunk.

2022-12-13 20:33 UTC, jsnmoon approved these changes
Looks great. Thanks for your patience!

2022-12-13 21:46 UTC, merged