Start: Restore 'Back to My Home' back button behavior
Automattic/wp-calypso pull request #70827
Opened 2022-12-06 15:16 UTC by danielbachhuber

## Proposed Changes

Adds a `sourceSiteSlug` query parameter to restore 'Back to My Home' back button behavior when a user clicks 'Add new site' from the Site Switcher.

The behavior was removed in https://github.com/Automattic/wp-calypso/pull/70760 because our original `siteSlug` query parameter started causing unexpected buggy behavior. The logic was originally added with https://github.com/Automattic/wp-calypso/pull/64292

See some discussion in pdKhl6-1ly-p2

## Testing Instructions

1. Navigate to My Home for one of your sites.
2. Click on 'Switch sites' to open the Site Switcher.
3. Click on 'Add new site' at the bottom of the Site Switcher.
4. On `/start`, verify the in-page back button says 'Back to My Home'
5. Click on the 'Back to My Home' button and verify you're returned to the original site.
6. Grep the codebase to verify there are no other entry points with `source=my-home`.

Note: some lovely caching wonkiness can occur if you repeat the steps for a second site (without refreshing the page): https://github.com/Automattic/wp-calypso/pull/68727#issuecomment-1271241893 We can pretend that doesn't exist.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/36432/205947767-9e66c0b6-39d9-4f0a-8981-525374b9ff76.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/36432/205948869-81db26b8-bc4b-402b-b692-fff4ef038e84.png">

2022-12-08 03:30 UTC, p-jackson requested changes
The "Back to My Home" behaviour is still broken when launching from the My Home checklist.

1) Go to My Home of an unlaunched site
2) Launch from the checklist
3) Taken to `/start/launch-site?siteSlug={{ siteSlug }}&source=my-home&hide_initial_query=yes`
4) Launching works because `siteSlug` is present in the URL, but the back button is broken because `sourceSiteSlug` is missing.

https://user-images.githubusercontent.com/1500769/206349603-11337a73-89fe-449e-b2fe-96605f3456c9.mov

2022-12-08 03:30 UTC, p-jackson commented on client/signup/steps/domains/index.jsx
> +			} else if ( 'my-home' === source && sourceSiteSlug ) {
Sometimes we have `source=my-home` _and_ it's a launch flow. When that happens we're using the `siteSlug` param instead of `sourceSiteSlug`, and the back button breaks.

2022-12-08 03:48 UTC, p-jackson commented
To quote a wise man

> What a horrible, awful bug

I can think of a couple fixes.

The quick and dirty one is to do something like `const sourceSiteSlug = queryObject.sourceSiteSlug || queryObject.siteSlug`, so that our back button logic works with either flavour of query param. When we're crafting our URLs that navigate to the signup flow we just have to be careful about which query param we choose to use.

I call this dirty because I think it leaves everything just as confusing as it currently is.

I think a clearer—but much more verbose—fix would be to completely separate the `siteSlug` and `sourceSiteSlug` params.
- `siteSlug` (and its cousin `siteId`) always refer to the currently selected site. It's present for flows where having a selected site makes sense e.g. launch and post-site-creation setup
- `sourceSiteSlug` always refers to the site the user came from, and always in conjunction with the `source` param.

[I tried the changes out on this branch if you want to see what I mean](https://github.com/Automattic/wp-calypso/compare/improve/start-restore-back-to-my-home...improve/start-restore-back-to-my-home-2).

The downside is that there are cases where both `siteSlug` _and_ `sourceSiteSlug` params are needed (and are identical). For instance launching from general settings requires both params to be used.

On the upside it decouples the signup framework from the dashboard pages that link to it. For instance, the signup framework implicitly has knowledge that if it is linked to from General Settings then it must be a launch flow. By having two params we can do arbitrary things like launch site A from site B's dashboard.

2022-12-08 08:08 UTC, p-jackson commented
> I think a clearer—but much more verbose—fix would be to completely separate the `siteSlug` and `sourceSiteSlug` params.

I think @southp is saying something similar in his proposed fix, see line 619: https://github.com/Automattic/wp-calypso/pull/70919/files#diff-1ee63778838c31a9ed28f17a1a7139d6304a844cfba059c5ffcd128b175208d3R619

2022-12-08 22:25 UTC, danielbachhuber commented
Thanks for the review, @p-jackson !

@southp restores the original behavior in his pull request, so I'm going to close in favor of that: https://github.com/Automattic/wp-calypso/pull/70919

I think a more involved fix needs to be more holistic: p58i-dEi-p2#comment-56448

2022-12-08 22:25 UTC, closed without merging

2022-12-13 10:34 UTC, wojtekn commented
I've noticed another flow that has some issues:

1. Navigate to `/sites`
2. Click on 'Add new site'
3. Click on "Back to Sites"
4. Click on the first site on the list
5. Click on 'Switch site' to open the Site Switcher.
6. Click on 'Add new site' at the bottom of the Site Switcher.

See that on `/start` the in-page back button says 'Back to Sites', which is incorrect.

Refresh the page, note that now it correctly shows "Back to My Home".