Update agency company information forms
Automattic/wp-calypso pull request #70971
Opened 2022-12-08 23:48 UTC by oikeme

Update the error message when on the agency sign up form and company update form to indicate when an invalid domain name has been entered.

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

2022-12-13 07:24 UTC, yashwin requested changes
LGTM! It works as described.

However, I have made a couple of minor comments.

2022-12-13 07:24 UTC, yashwin commented on client/state/partner-portal/partner/utils.ts
> +	if ( 'company_website' in details ) {
I'm a bit concerned about the `details` being undefined here. Will `details` always have some value(not undefined)?

2022-12-13 07:24 UTC, yashwin commented on client/state/partner-portal/partner/utils.ts
>   * @param {object} parameters Parameters with errors.
Can we also include `details` here as param?

2022-12-14 06:12 UTC, yashwin approved these changes
LGTM now. Thanks for making the changes.

2022-12-14 23:09 UTC, merged

2022-12-15 01:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7673604

Thank you @oikeme for including a screenshot in the description! This is really helpful for our translators.

2022-12-23 11:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7673604).