Ecommerce Tailored Flow: Fixing ecommerce flow progress bar
Automattic/wp-calypso pull request #71341
Opened 2022-12-19 17:50 UTC by blackjackkent

#### Proposed Changes

* This PR fixes a missing set of config values for the ecommerce flow, allowing it to properly show a progress bar across the top of the screen as steps progress.

Before:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/13437011/208488316-811cd0ed-d604-49c3-8ae2-17a72e65d711.png">

After: 
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/13437011/208487729-9c3453e5-27cf-471b-ac38-98fe0ddd642f.png">

#### Testing Instructions

* Check out this PR to testing environment and navigate to `/setup/ecommerce`
* Navigate through the flow and verify that the progress bar appears and progresses appropriately through each step.

Related to #71244

2022-12-20 12:25 UTC, daledupreez requested changes
The steps here don't seem to be in the right order, so the progress bar jumped around unexpectedly relative to the step I was on.

2022-12-20 12:25 UTC, daledupreez commented on packages/onboarding/src/flow-progress/use-flow-progress.ts
> +import { LINK_IN_BIO_FLOW, LINK_IN_BIO_TLD_FLOW, ECOMMERCE_FLOW } from '../utils/flows';
Extreme nit: I'd prefer this to be in alphabetical order.
```suggestion
import { ECOMMERCE_FLOW, LINK_IN_BIO_FLOW, LINK_IN_BIO_TLD_FLOW } from '../utils/flows';
```
And this is _definitely_ not blocking!

2022-12-20 12:25 UTC, daledupreez commented on packages/onboarding/src/flow-progress/use-flow-progress.ts
> +	},
I believe these steps are out of order, which results in the progress bar jumping around unexpectedly.

When I work through the flow, I see the following order:
1. intro
2. storeProfiler
3. designCarousel
4. domains
5. processing (site creation)
6. checkout (not in our list)
7. checkPlan
8. processing (waitForAtomic)
9. storeAddress
```suggestion
	[ ECOMMERCE_FLOW ]: {
		intro: 0,
		storeProfiler: 1,
		storeAddress: 7,
		domains: 4,
		designCarousel: 3,
		siteCreationStep: 5,
		processing: 5,
		waitForAtomic: 6,
		checkPlan: 5,
	},
```

2022-12-20 16:30 UTC, blackjackkent commented
> I believe these steps are out of order, which results in the progress bar jumping around unexpectedly.

@daledupreez Yep you're super correct. (The designs view in my local environment started erroring out at the end of the day, so I pushed this up with the intention of fixing that and doublechecking this morning, and yes, it is definitely out of order. 😛 That'll teach me to make assumptions.) I've pushed a fix to the step ordering that I think is correct.

2022-12-21 09:23 UTC, daledupreez approved these changes
Re-tested with the updates and everything looks good to me. The only minor gotcha is that we show the `processing` step before and after checkout, so there is no reflection of progress there, but I think that's something we should iterate on separately.

2022-12-21 09:23 UTC, merged