Stats: Adjust post detail layout for FixedNavigationHeader and Highlight cards
Automattic/wp-calypso pull request #71530
Opened 2022-12-27 15:09 UTC by dognose24

#### Proposed Changes

* Adjust `FixedNavigationHeader` to fit the modernized layout (`max-width: 1224px`).
* Add `min-width` to Highlight cards for scrolling on the narrower viewport.
* Modify Highlight card block styles on mobile.

#### Testing Instructions

* Spin up this change with the Calypso Live link.
* Navigate to the Stats `Post Detail` page (`/stats/post/${post-id}/${site-id}`).
* Ensure the post detail page works as previously.
* Append the feature flag `?flags=stats/enhance-post-detail` to the URL.
* Ensure the layout of the fixed navigation header aligns with other Stats pages.

| Before | After |
| --- | --- |
| <img width="1483" alt="截圖 2022-12-27 下午10 32 37" src="https://user-images.githubusercontent.com/6869813/209685157-17a02195-50b8-4523-ae8e-1c2b74340f8e.png"> | <img width="1478" alt="截圖 2022-12-27 下午10 32 57" src="https://user-images.githubusercontent.com/6869813/209685253-f4b735e5-ef63-4194-9339-b8231a845fa6.png"> |

* Ensure the Highlight cards look reasonable on narrower and mobile viewports.

| Narrower | Mobile |
| --- | --- |
| <img width="738" alt="截圖 2022-12-27 下午10 49 20" src="https://user-images.githubusercontent.com/6869813/209685390-6da62705-3be2-49cb-b51e-95db09782d68.png"> | <img width="610" alt="截圖 2022-12-27 下午10 48 37" src="https://user-images.githubusercontent.com/6869813/209685463-64dd37c1-9107-4ae9-bce6-ff79b510bcc5.png"> |

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #70671

2022-12-29 21:49 UTC, jsnmoon requested changes
Unfortunately, this change appears to break the post details page when the feature flag is disabled:

|Production|Without Feature Flag (Broken)|With Feature Flag|
|-|-|-|
|<img width="1074" alt="image" src="https://user-images.githubusercontent.com/4044428/210013918-e55b04e2-4418-4d49-a3f4-7dd7d97578c6.png">|<img width="1526" alt="image" src="https://user-images.githubusercontent.com/4044428/210013963-540e5eca-4dd5-4155-981d-f28c0f220ceb.png">|<img width="1268" alt="image" src="https://user-images.githubusercontent.com/4044428/210014009-169df818-e1a5-4e6e-a287-5167b8d86e2d.png">|

Note these visual regressions:
- Chart's y-axis labels flowing outside of the container
<img width="72" alt="image" src="https://user-images.githubusercontent.com/4044428/210014114-0f4f1d29-95ed-4c47-8520-bade28fbc756.png">

- Tables taking up the entire width `#primary.layout__primary` instead of being limited to a maximum width of 1224px.
<img width="239" alt="image" src="https://user-images.githubusercontent.com/4044428/210014144-d3cce42d-f284-47de-a416-5bae3645b8e8.png">

2023-01-03 03:31 UTC, dognose24 commented
> Unfortunately, this change appears to break the post details page when the feature flag is disabled:

> Note these visual regressions:

All fixed in [7127bb0](https://github.com/Automattic/wp-calypso/pull/71530/commits/7127bb0e118db2166bc709d56edbc80a3bf6357d).

2023-01-03 16:02 UTC, keoshi approved these changes
LGTM!

2023-01-03 22:14 UTC, jsnmoon approved these changes
Feel free to ship the PR after removing some extraneous code that could be pruned from the `StatsPostDetail` component.

2023-01-03 22:14 UTC, jsnmoon commented on client/my-sites/stats/stats-post-detail/index.jsx
> +					) }
```suggestion
					<PostDetailHighlightsSection siteId={ siteId } postId={ postId } post={ post } />
```

2023-01-03 22:14 UTC, jsnmoon commented on client/my-sites/stats/stats-post-detail/index.jsx
> +							) }
```suggestion
```

2023-01-03 22:14 UTC, jsnmoon commented on client/my-sites/stats/stats-post-detail/index.jsx
> +							{ isFeatured && <PostDetailTableSection siteId={ siteId } postId={ postId } /> }
```suggestion
							<PostDetailTableSection siteId={ siteId } postId={ postId } />
```

2023-01-03 22:14 UTC, jsnmoon commented on client/my-sites/stats/stats-post-detail/index.jsx
> +							) }
```suggestion
```

2023-01-04 08:26 UTC, dognose24 commented
> removing some extraneous code that could be pruned from the StatsPostDetail component.

They were pruned in [6fefb6e](https://github.com/Automattic/wp-calypso/pull/71530/commits/6fefb6e0dda09483b25e12bfad30e6821bb2c444).

2023-01-04 20:25 UTC, jsnmoon approved these changes

2023-01-04 21:08 UTC, jeffgolenski commented
@dognose24 Another wonderful addition. Thanks for this. The only issue I'm seeing right now is that the All-time stats box breaks the layout when the title is too long. 

Example: This post title in english occupies 3 lines, which pushes the card to break the balance with the card next to it

![Screen Shot 2023-01-04 at 4 04 01 PM](https://user-images.githubusercontent.com/214813/210649932-46fe7650-6a24-40c5-8423-144b4c60d1af.png)

Can we:

- [ ] Limit the displayed title to 48 characters max (not including spaces) and then insert an ellipsis "..." when it hits that max character count?

So it looks like this...
![Screen Shot 2023-01-04 at 4 04 41 PM](https://user-images.githubusercontent.com/214813/210650200-bbef79e9-5979-4735-a5db-23fc7288b597.png)

cc @keoshi

2023-01-05 02:52 UTC, dognose24 commented
> @dognose24 Another wonderful addition. Thanks for this. The only issue I'm seeing right now is that the All-time stats box breaks the layout when the title is too long.

@jeffgolenski Thanks for your feedback! Sounds like an excellent plan for the mobile layout! I will move them to the task and tackle them in the follow-up PR.

2023-01-05 02:56 UTC, merged