Stats Page Redesign: Update table row hover colors
Automattic/wp-calypso pull request #71686
Opened 2023-01-04 22:42 UTC by annacmc

#### Proposed Changes

* This PR updates the stats module tables row hover color to the primary color set in its lightest tint

#### Testing Instructions

* Visit the Calypso Live branch.
* Navigate to the Annual Insights page at `/stats/day/annualstats/[SiteURL]`
* Confirm that the table rows highlight 

![Screen Capture on 2023-01-04 at 16-32-02](https://user-images.githubusercontent.com/30754158/210662829-d0cc9db7-d6dc-406f-9021-0603231fc782.gif)

**Question:** Do we want the hover/highlight to extend to include the `year` row?  Up until now it hasn't, but I think maybe it could look better if we did. Would love some other input to this! cc @keoshi @jeffgolenski 

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

2023-01-04 23:23 UTC, jsnmoon requested changes
Could we apply the hover color to the year `th` as well? We'll need to target it with a more specific selector to accomplish this. Here's what I'm thinking:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/4044428/210668592-615fa938-14c3-433e-9054-9b8477f5e174.png">

2023-01-05 02:06 UTC, annacmc commented
> Could we apply the hover color to the year `th` as well? We'll need to target it with a more specific selector to accomplish this. Here's what I'm thinking:
> 
> <img alt="image" width="1067" src="https://user-images.githubusercontent.com/4044428/210668592-615fa938-14c3-433e-9054-9b8477f5e174.png">

Totally! Thanks @jsnmoon  - should be looking better now :)

2023-01-05 21:50 UTC, jsnmoon requested changes
The latest changes don't quite nail the desired behavior when hovering over a darker background:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/4044428/210885315-c6d9e3b4-7b13-48ca-9c86-ad274f86e7fa.png">

I've left a change recommendation inline that should fix this issue.

2023-01-05 21:50 UTC, jsnmoon commented on client/my-sites/stats/stats-module/style.scss
> +		.stats-module & tbody tr:hover th {
```suggestion
		.stats-module & tbody tr:hover th:first-child {
```

Applying a more specific selector here should force `th` elements to use the desired background, like so:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/4044428/210886514-a0440f7a-da25-4a24-9b3e-faf19144807c.png">

2023-01-05 22:57 UTC, jsnmoon approved these changes
🚢 🚢 🚢

2023-01-06 00:48 UTC, merged