Stats: Extended number component with default formatter
Automattic/wp-calypso pull request #71743
Opened 2023-01-06 00:47 UTC by grzegorz-cp

#### Proposed Changes

* adding a default number formatter to Calypso components
* importing the formatter in Stats components and replacing it in places where it was used previously

#### Testing Instructions

* no visual changes should be present
* go to Stats page and check that the numbers on the page look correctly for your region
* Examples of affected places: components with the horizontal bar, All-time highlights section on the Insights page

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #71639

2023-01-06 04:28 UTC, a8ck3n approved these changes
Tests well for me.

2023-01-06 16:04 UTC, dognose24 commented on packages/components/src/shortened-number/formattedNumber.tsx
> +const formatedNumber = ( number: number | null ) => formatNumber( number );
Just nitpicking, is this variable supposed to be `formattedNumber`? 😄

2023-01-06 16:04 UTC, dognose24 reviewed
I left a message, which is not a blocker.

2023-01-06 20:38 UTC, jsnmoon requested changes

2023-01-06 20:38 UTC, jsnmoon commented on packages/components/src/shortened-number/stories/index.stories.jsx
> +import formttedNumber from './../formattedNumber';
```suggestion
import formattedNumber from '../formattedNumber';
```

Fixes a typo and an unnecessarily verbose relative directory.

2023-01-06 20:38 UTC, jsnmoon commented on packages/components/src/shortened-number/formattedNumber.tsx
> +function formatNumber( number: number | null ) {
```suggestion
export default function formattedNumber( number: number | null ) {
```

Could we directly export this function instead?

2023-01-06 20:38 UTC, jsnmoon commented on packages/components/src/shortened-number/formattedNumber.tsx
> +const FORMATTER = new Intl.NumberFormat();
This file should be dash-cased (`formatted-number.tsx`).

2023-01-06 20:38 UTC, jsnmoon commented on packages/components/src/shortened-number/formattedNumber.tsx
> +const FORMATTER = new Intl.NumberFormat();
Perhaps we could rename this folder to be `number-formatters`?

2023-01-08 23:15 UTC, grzegorz-cp commented
Thanks team, I applied the changes.

2023-01-10 02:41 UTC, jsnmoon approved these changes
Let's ship this! Thanks for indulging my nitty feedback :)

2023-01-10 17:06 UTC, dognose24 approved these changes
LGTM!

2023-01-10 20:33 UTC, merged