Add user came through info to happy chat
Automattic/wp-calypso pull request #71751
Opened 2023-01-06 07:57 UTC by chihsuan

#### Proposed Changes

* Add `cameThrough` field to happychat `getUserInfo`

We want to add WooCommerce.com context to Happychat.

1. When requested from mobile app, `Customer came through store setup on Woo mobile app`
2. When requested via browser (applies to all browsers including desktop or mobile), `Customer came through store setup on Woo browser`

#### Testing Instructions

* 

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to  https://github.com/woocommerce/team-ghidorah/issues/139

2023-01-09 12:21 UTC, alshakero approved these changes
LGTM 👍🏼

2023-01-10 05:45 UTC, ilyasfoo requested changes
Thanks for working on this one, @chihsuan!

It seems the URL parameter was replaced when I go from domains step to checkout. The end URL was `http://calypso.localhost:3000/checkout/ilyastest39.wordpress.com?signup=1#step2`, so `ref` was no longer available and `cameThrough` parameter would be null.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/3747241/211470640-b0b06518-b220-4dc6-bc25-2ec3995f90b1.png">

I'm not sure if I'm an edge case, but I think navigation changes could easily break this flow. Should we opt for something more persistent? But it should also only impact a single checkout instance I think.

2023-01-10 06:07 UTC, chihsuan commented
> It seems the URL parameter was replaced when I go from domains step to checkout. The end URL was http://calypso.localhost:3000/checkout/ilyastest39.wordpress.com?signup=1#step2, so ref was no longer available and cameThrough parameter would be null.

@ilyasfoo Sorry, I didn't rebase the branch. `ref` should still exist when you go to checkout. The changes was made in https://github.com/Automattic/wp-calypso/pull/71692.

> I'm not sure if I'm an edge case, but I think navigation changes could easily break this flow. Should we opt for something more persistent? But it should also only impact a single checkout instance I think.

I'm not sure tbh. If we use something more persistent, we need to clear it in some way. 🤔

2023-01-10 07:25 UTC, ilyasfoo approved these changes
Ah, I see. I think this is good enough since `ref` is included into the URL parameter. LGTM! 🚢

2023-01-10 08:41 UTC, merged