feat: Enable Jetpack app banner Android deep links
Automattic/wp-calypso pull request #72393
Opened 2023-01-20 20:51 UTC by dcalhoun

#### Proposed Changes

This reverts commit ef32e6c065650d50fc030a6d6ceca728bb4357f6.

Re-enables Calypso banner deep links for the Android Jetpack app once
https://github.com/wordpress-mobile/WordPress-Android/pull/17742 adds support
for launching the migration experience from deep links.

#### Testing Instructions

* Use an Android device for the following steps.
* Install the WordPress mobile app and log in.
* In your Android browser, navigate to the Calypso Live environment for this PR and log in.
* If the banner is not visible...
  * Connect your Android device to your development machine via USB. 
  * Visit `chrome://inspect/#devices` in Chrome on your development machine.
  * Inspect the Android device's browser.
  * Execute the following in the console: 
      `dispatch( { type: 'PREFERENCES_SET', key: 'appBannerDismissTimes', value: null } );`
* Tap the "Open in the Jetpack app" button.
* Install the Jetpack app.
* **Expected:** After opening the installed app, the migration experience
  begins.

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-01-23 09:11 UTC, ovitrif commented
https://github.com/wordpress-mobile/WordPress-Android/pull/17742 has been merged to `trunk` in time to land in version `21.6` 🚀 .

> **Warning** This should not be merged until https://github.com/wordpress-mobile/WordPress-Android/pull/17742 is published in a Jetpack app release.

@dcalhoun According to this note, my understanding is that merging this PR should be planned after the [Android `21.6` ](https://github.com/wordpress-mobile/WordPress-Android/milestone/247), that's scheduled to proceed on ** February 06, 2023** if nothing blocking is found during beta testing.

2023-01-23 12:30 UTC, dcalhoun commented
> @dcalhoun According to this note, my understanding is that merging this PR should be planned after the [Android `21.6` ](https://github.com/wordpress-mobile/WordPress-Android/milestone/247), that's scheduled to proceed on **February 06, 2023** if nothing blocking is found during beta testing.

Great! Thank you for the note. 🙇🏻

2023-02-15 16:23 UTC, SiobhyB requested changes
@dcalhoun, the links are redirecting to the correct places for me when the Jetpack app is already installed, but things aren't working as expected with a fresh install of the Jetpack app. 

I'm not being directed to the migration flow after tapping the banner links and installing Jetpack. Instead, I'm taken to the login screen even though I'm already logged into the latest beta version of the WordPress app (`21.7-rc-1`).

Is that flow working as expected in your testing?

2023-02-15 16:49 UTC, dcalhoun commented
> @dcalhoun, the links are redirecting to the correct places for me when the Jetpack app is already installed, but things aren't working as expected with a fresh install of the Jetpack app.
>
> I'm not being directed to the migration flow after tapping the banner links and installing Jetpack. Instead, I'm taken to the login screen even though I'm already logged into the latest beta version of the WordPress app (`21.7-rc-1`).
> 
> Is that flow working as expected in your testing?

@SiobhyB I understand this to describe the flow outlined in the "Testing Instructions" section of the PR description. Yes, that flow is working as expected for me. 

<details><summary>Screen capture of successful flow</summary>

https://user-images.githubusercontent.com/438664/219096069-1232e3e0-670a-46b8-b422-68daa1b4992f.mp4

</details>

It is surprising the flow does not function correctly for you. However, [similar oddities did occur](https://github.com/Automattic/wp-calypso/pull/72384#issuecomment-1398787961) during review of the sibling PR. If you remove both the WordPress and Jetpack apps from your device first, does the flow succeed then?

2023-02-15 16:53 UTC, ovitrif commented
> things aren't working as expected with a fresh install of the Jetpack app.

@SiobhyB Interesting, can you please double check the versions / variants of both apps? 🙏 

It's a long shot but I'm wondering if installing the Jetpack app from the Store isn't resulting in a different app in your case 🤔 

Afaik both Jetpack and WordPress can only share data if they have matching Public Key Hash (as a result of signging) 🤔

2023-02-15 16:55 UTC, SiobhyB commented
@ovitrif, @dcalhoun, thanks both! Noting for posterity that we found this is due to the fact that 21.6 has not yet been rolled out to all users. I was being served 21.5 when downloading a fresh copy of the Jetpack app from the Play store, which is why the flow wasn't working for me. We should likely wait until 21.6 is rolled out to 100% of users before merging this.

Slack thread: p1676479350242099-slack-CC7L49W13

2023-02-27 13:54 UTC, SiobhyB approved these changes
Tested again and everything's working perfectly for me now. :) I see the 21.6 release was made available to 100% of users on February 15th, so it seems safe to ship this change now, too.

Thanks to all involved! 🙌

2023-02-28 14:45 UTC, merged