Add Tracks event to ccpa opt-out click
Automattic/wp-calypso pull request #72920
Opened 2023-02-02 15:02 UTC by robertsreberski

#### Proposed Changes

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

2023-02-02 17:39 UTC, gmovr approved these changes
LGTM, I re-ran the e2e, just a flaky test. 🚢

2023-02-03 22:39 UTC, CodeyGuyDylan requested changes
Unless I am misunderstanding the goal here, I believe the event is being triggered incorrectly

2023-02-03 22:39 UTC, CodeyGuyDylan commented on client/lib/analytics/utils/use-do-not-sell.ts
> +			if ( ! isActive ) {
```suggestion
			if ( isActive ) {
```
Correct me if I am wrong, but based on the name `a8c_ccpa_optout` and the description of this PR, we want this event to trigger when somebody "opt's out" by turning **on** the "Do Not Sell or Share My Data" toggle correct?

If so, I think this change should be made, I am only getting the tracks even triggering when I turn the toggle off

2023-02-14 15:43 UTC, CodeyGuyDylan approved these changes
Tests well and LGTM :shipit:

2023-02-15 00:53 UTC, merged