Reading Settings: Fix unexpected dialog displayed on Reading settings page save
Automattic/wp-calypso pull request #73050
Opened 2023-02-07 15:48 UTC by ivan-ottinger

🚧 Work in progress.

Related to #
## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-02-09 11:09 UTC, mashikag requested changes
Great job on finding the root cause and coming up with the solution! I suggested just a slight change to how two statements are written, it should make the code easier to understand. 🙂
Feel free to argue on this one if you do not agree (this should be always implied). 😅

BTW I am now very curious as to what is the other issue that causes the same symptom for `rss_use_excerpt`. 😁

2023-02-09 11:09 UTC, mashikag commented on client/my-sites/site-settings/settings-reading/main.tsx
> +		...( page_on_front ? { page_on_front } : { page_on_front: '' } ),
Spreading seems to be unnecessary here. Based on the new statement we will always end up with `page_on_front` property. 
Previously the spread operator was used because if `page_on_front` was `undefined` (or of falsy value to be more precise) it would not be included in the object returned. See example of what I mean below:
![Screen Shot 2023-02-09 at 11 35 13](https://user-images.githubusercontent.com/2019970/217789093-d8914a3f-2545-4bab-b8e1-7b3d40683f20.png)

With the new statement we will include the `page_on_front` prop in the result object even when it is `undefined`:
![Screen Shot 2023-02-09 at 11 39 24](https://user-images.githubusercontent.com/2019970/217789560-4188a7b5-484e-48f2-bfaf-5456c847115a.png)

Therefore to reduce the complexity of the statement I would suggest dropping the spread operator. It could be re-written as:
```
page_on_front: page_on_front ?? '',
```

The same goes for `page_for_posts` on the line above.

2023-02-09 13:29 UTC, ivan-ottinger commented on client/my-sites/site-settings/settings-reading/main.tsx
> +		...( page_on_front ? { page_on_front } : { page_on_front: '' } ),
Thanks for noticing and sharing the details, Maciej! 🙂 Yes, that makes total sense. I will apply the change in a new commit.

2023-02-09 13:41 UTC, ivan-ottinger commented on client/my-sites/site-settings/settings-reading/main.tsx
> +		...( page_on_front ? { page_on_front } : { page_on_front: '' } ),
Resolved in https://github.com/Automattic/wp-calypso/pull/73050/commits/5c11c1b63ccbba1856381af63850da6b40024506.

2023-02-10 12:55 UTC, mashikag approved these changes
Thanks for addressing my suggestion! 🙇 
I tested locally with the PR applied and the issue is addressed as expected. 👌

2023-02-10 13:54 UTC, merged