Added Banner component to My Plan page
Automattic/wp-calypso pull request #73192
Opened 2023-02-09 22:10 UTC by nelsonec87

Built on top of https://github.com/Automattic/wp-calypso/pull/73191

## Proposed Changes

* Changed the My Plan page to use the Banner component (Same as Plans page)
![image](https://user-images.githubusercontent.com/3801502/217950332-c5de4c4c-6d95-4faf-83cc-015eb1fa2f17.png)

## Testing Instructions

* Open the My Plan page (using a trial site) (`/plans/my-plan/<site-slug>`)
* Check that you see the top banner and the button is working correctly.
* Open the Plans page and check that the Banner is shown without the button.
 
![image](https://user-images.githubusercontent.com/3801502/217950698-7be458d2-54d2-44a0-b4de-4e3ac46bc79b.png)

2023-02-10 08:05 UTC, daledupreez requested changes
This is working, but I think the interface needs to be changed before we ship this.

2023-02-10 08:05 UTC, daledupreez commented on client/my-sites/plans/ecommerce-trial/ecommerce-trial-banner/index.tsx
> +				) }
To align with my other comment about this being passed in as a prop.
```suggestion
				{ props.callToAction } // could also just be { callToAction } if we destructure props
```

2023-02-10 08:05 UTC, daledupreez commented on client/my-sites/plans/ecommerce-trial/ecommerce-trial-banner/index.tsx
> +}
I think the button as a whole should be passed in as a prop -- I think the interface is much simpler if we do that, as the calling context gets to define the styling and behaviour for the button. We already have a problem where the className (and thus the CSS) for the button is specific to the calling context, which is a poor pattern that's likely to break.


```suggestion
interface ECommerceTrialBannerProps {
	callToAction?: JSX.Element | null;
}
```

2023-02-10 18:41 UTC, daledupreez approved these changes
Thanks for restructuring this! I think that's much cleaner and more flexible.

LGTM!

2023-02-10 18:51 UTC, merged

2023-02-10 19:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7807201

Thank you @nelsonec87 for including a screenshot in the description! This is really helpful for our translators.

2023-02-16 01:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7807201).