BackupRetention: Update link to retention setting page
Automattic/wp-calypso pull request #73568
Opened 2023-02-21 04:31 UTC by Initsogar

## Proposed Changes

* Update link on `X days of backups saved` to point to Jetpack Cloud settings page with a `cog` icon.

## Screenshots

![screenshot-jetpack cloud localhost_3000-2023 02 20-23_25_40](https://user-images.githubusercontent.com/1488641/220247560-3d731695-9d0c-40b8-8177-b62c9559e3f7.png)

## Testing Instructions
* **Jetpack Cloud**
  * Start a Jetpack Cloud live branch with a site that has a backup plan with storage limit (like Jetpack Backup 10 GB)
  * Navigate to `VaultPress Backup` section
  * You should see the `Cloud storage space` section and in the down-right corner the `X days of backups saved` label.
  * Ensure it has the cog/gear icon and that it should redirect you to the Settings page when clicking on it.
* **Calypso Blue**
  * Start a Jetpack Cloud live branch with a site that has a backup plan with storage limit (like Jetpack Backup 10 GB)
  * Navigate to `Jetpack` > `VaultPress Backup` section
  * You should see the `Cloud storage space` section and in the down-right corner the `X days of backups saved` label.
  * Ensure it does not have the cog/gear icon and that it should redirect you to the Activity Log in Calypso blue when clicking on it.
    * Given that we don't have this setting available on Jetpack Cloud yet, we couldn't include this link here yet.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-02-22 18:43 UTC, jwebbdev requested changes
Worked as described, just a small change for test description

2023-02-22 18:43 UTC, jwebbdev commented on client/components/backup-storage-space/test/hooks.js
> +	test( 'renders `7 days of backups saved` with link to activity log with site-slug in Jetpack Cloud', () => {
```suggestion
	test( 'renders `7 days of backups saved` with link to settings page with site-slug in Jetpack Cloud', () => {
```

2023-02-22 19:23 UTC, Initsogar commented on client/components/backup-storage-space/test/hooks.js
> +	test( 'renders `7 days of backups saved` with link to activity log with site-slug in Jetpack Cloud', () => {
Done! Thank you :)

2023-02-23 03:05 UTC, jwebbdev approved these changes

2023-02-23 16:15 UTC, merged