[DO NOT MERGE] Jetpack Pro Dashboard: implement backup storage expanded content for large & small screen
Automattic/wp-calypso pull request #73922
Opened 2023-03-01 06:15 UTC by yashwin

Related to 1203940061556608-as-1204076721671719

## Proposed Changes

TBD

## Testing Instructions

TBD

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-16 20:46 UTC, DustinHartzler reviewed
Looks good to me!

I went through all the test examples (activating, deactivating, creating post, etc) and it looks good on desktop and mobile.

I'd only want to verify with @ederrengifo that we want to display all the backup data. The Figma rendering only shows backing up `2 Posts and 1 Page`

One of my WooCommerce sites looks like this (it just mentions a lot of things):
![image](https://user-images.githubusercontent.com/2293077/225748736-ac144b89-71db-4a4e-8291-edb09cb1c21a.png)

I'd assume that's fine based on that's the info coming from the API, but just pointing it out.

2023-03-17 06:20 UTC, yashwin commented
> I'd assume that's fine based on that's the info coming from the API, but just pointing it out.

Thanks for the review, @DustinHartzler. Yes, that's why I put in the note above to be double-sure if we are ok with this.

2023-03-17 14:58 UTC, ederrengifo commented
@DustinHartzler can we use only posts and pages for this MVP? The hypothesis here is that showing only a couple of important items could help to reduce noise. We could adjust later based on the usage, of course, that's why we thought starting with pages and posts would be a good baseline.

2023-03-17 15:00 UTC, ederrengifo requested changes
As I mentioned in the comments, let's start only with posts and pages for the MVP 🙏  Besides that, LGTM!

2023-03-20 06:55 UTC, yashwin commented
@DustinHartzler, @ederrengifo - I have made the changes accordingly. The strings are also translated now.

<img width="343" alt="Screenshot 2023-03-20 at 12 16 57 PM" src="https://user-images.githubusercontent.com/10586875/226266745-9c86c4e1-7fa4-4f52-81b7-1f0f6423876f.png">

2023-03-20 15:10 UTC, DustinHartzler commented
I gave it a look and it shows the latest full backups with only the details for posts and pages - it no longer highlights when plugins have been updated, etc.

I'm comfortable shipping once @ederrengifo gives it the thumbs up.

2023-03-20 22:48 UTC, ederrengifo approved these changes
LGTM! Thank you so much for all the work, looks great!

2023-03-23 05:09 UTC, merged

2023-03-23 08:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7882999

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

2023-03-31 08:35 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7882999).