Creating conversion experiment on paid media signup flow (biannual option)
Automattic/wp-calypso pull request #74131
Opened 2023-03-06 19:33 UTC by donlair

## Proposed Changes

* Replaces the test setup in #72968 with a followup test that replaces the Monthly option with Bi-annually, and removes the Free plan link.
* The experiment name is `paid_media_signup_2023_03_biannual_toggle_hide_free`
* This experiment affects only the paid media signup flow (`onboarding-pm`)

Here's are screenshots showing the page for both tab options:

![CleanShot 2023-03-06 at 14 23 10@2x](https://user-images.githubusercontent.com/35781181/223210762-994acf8f-053c-416c-97b1-ac0d93df1a2a.png)

![CleanShot 2023-03-06 at 14 23 02@2x](https://user-images.githubusercontent.com/35781181/223210770-94e6dccb-2639-4282-b81e-7a3f587cea99.png)

## Testing Instructions

* Checkout this PR and start Calypso locally.
* Navigate to the paid media signup flow (`/start/onboarding-pm`)
* Proceed to the Plans step of the signup flow without assigning yourself to a variant.
* Confirm that you see that Plans step with Annual and Monthly toggle options as well as the Free link (note: `onboarding-pm` doesn't use the 2023 design)
* Confirm that you can select a plan and make it to the checkout page as expected.
* Assign yourself to the treatment variant of this experiment and repeat the flow.
* Confirm that you see Annual and Bi-Annual tab options.
* Click the tabs and confirm that you see the correct prices.
* Click choose a variety of plans and confirm that the correct plan appears on the checkout page.
* Test the `onboarding` flow at `/start` and confirm that the updates to the shared tab code hasn't affected the other flows.

2023-03-08 10:17 UTC, chriskmnds requested changes
Thanks, @donlair. This tests out as per the instructions. The changes look great and show care went into this. Thanks for basically addressing pdgrnI-28f-p2 along  :-)

I left some comments, which seem critical to address before shipping.

Aside (minor/curiosity): why are we running this as an experiment? It seems to have been decided that we won't use AB testing to direct decisions, which this experiment circumvents? Last I know, we will likely ship this change everywhere soon 🤔

2023-03-08 10:17 UTC, chriskmnds commented on client/my-sites/plans-features-main/plan-type-selector.tsx
> +						{ interval === 'annually' && hideDiscountLabel ? null : (
`interval` is never "annually" here. what is the intention of this change?

2023-03-08 10:17 UTC, chriskmnds commented on client/my-sites/plans-features-main/plan-type-selector.tsx
> +							{ interval === '2yearly' ? translate( 'Pay bi-annually' ) : null }
As these changes affect the display globally, and we will be introducing 1-year/2-year toggle everywhere, can we confirm that "Pay annually"/"Pay bi-annually" are the desired labels? The [design mocks](xkhhUlDowF13dRoXJqlRDM-fi-1-95) show "Pay 1 year"/"Pay 2 years" instead. 

Otherwise, we'd need to condition here to show your preferred labels for the variation of this experiment only (ideally, I think).

2023-03-08 18:25 UTC, aaronyan commented
> side (minor/curiosity): why are we running this as an experiment? It seems to have been decided that we won't use AB testing to direct decisions, which this experiment circumvents? Last I know, we will likely ship this change everywhere soon

Hi there! I got an Automattcher for this and thought I'd chime in.

A/B tests can be used to measure the impact of work even if it won't change decisions. I think it's important to measure the impact of changes to critical workflows like the plan page to protect the business and measure the voice of the customer through clickthrough actions and signup and purchase conversions.

2023-03-08 18:49 UTC, chriskmnds commented
> A/B tests can be used to measure the impact of work even if it won't change decisions. I think it's important to measure the impact of changes to critical workflows like the plan page to protect the business and measure the voice of the customer through clickthrough actions and signup and purchase conversions.

Sure @aaronyan. I am only curious how this aligns with Matt asking to pause them entirely (if my reading/memory of this is correct). Assuming we have a decision from higher up to pause AB testing, then is it ok to still run them behind tailored flows? If these don't have any potential to postpone, influence, or even delay shipment, then what's the value really - to come back and say "these numbers told us so?". From what you are saying, we should ignore and continue to AB test - as the only method to measure the impact of changes? (cause who doesn't want to see the impact of changes?)

2023-03-09 03:41 UTC, aaronyan commented
Yeah, it's a really good point that there's a lot of conflicting messaging around how and when to measure impact. I've asked for some [clarity on expectations](p58i-dSn-p2#comment-56996) since I don't think it's fair to ask folks to not run A/B tests while also expecting people to measure impact. There are a few more discussions [here](p58i-dSn-p2#comment-57196) and [here](p58i-dSn-p2#comment-57228)!

I think each team will need to decide for themselves how they want to the measure impact of their work.

2023-03-09 18:45 UTC, donlair commented
Thanks for the review and comments @chriskmnds! Re: experimentation, we've carved out the paid media flow separately from the default flows so that we can test and iterate any changes. Since these flows are being used w/ paid advertising, unexpected impacts of changes can carry a big cost.

I refactored this to use the 2 year tab options implemented in #74207. This is ready for another look when you get a chance!

2023-03-09 20:35 UTC, donlair commented
Hmm... not really sure why those E2E tests are failing, I can't think of a way that they'd be impacted by these changes, can you @chriskmnds?

2023-03-10 10:28 UTC, chriskmnds approved these changes
Thanks again, Don. The e2e failures didn't look related. I rebased the PR, and it looks good to go. Tests out for me, but maybe double check 🚢 

p.s. for cases where tests fail unexpectedly, you can click into the TeamCity page and rerun them. they usually pass the second time around 😬 :

<img width="855" alt="Screenshot 2023-03-10 at 12 20 18 PM" src="https://user-images.githubusercontent.com/1705499/224291666-f7cefcd2-c0bf-45f6-b974-34b748a4000c.png">

2023-03-10 10:31 UTC, donlair commented
Awesome, thanks for the help and the review @chriskmnds!

2023-03-10 10:38 UTC, merged

2023-03-10 12:17 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7851541).