My home upsell: Update copy for yearly plans
Automattic/wp-calypso pull request #74390
Opened 2023-03-13 20:09 UTC by lupus2k

Related to https://github.com/Automattic/dotcom-forge/issues/1949

## Proposed Changes

Update the copy of the My home upsell for yearly plans.

Title: `Make your mark online with a memorable domain name`
Description: `Your plan includes a free domain for the first year. Stake your claim on the web with a domain name that boosts your brand.`

## Screenshots
| Before | After |
| --- | --- |
| ![Image](https://user-images.githubusercontent.com/402286/224171619-5d5e950e-088e-4e9c-adaa-0258e0c1487d.png) | ![image](https://user-images.githubusercontent.com/402286/224820282-ee85d104-474f-4ec7-8a3f-d1f1e21efb0f.png) |

## Testing Instructions
- Using a yearly plan site without custom domains
- You should see the upsell on the home
- The copy should match the suggested

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] ~~[Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?~~
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~~
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] ~~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~~

2023-03-13 20:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7860310

Thank you @lupus2k for including a screenshot in the description! This is really helpful for our translators.

2023-03-14 11:14 UTC, candy02058912 approved these changes
LGTM 👍 Thanks for the quick translation PR!

2023-03-14 11:28 UTC, candy02058912 requested changes
I just noticed that the test needs to be updated to pass with the new copy.

2023-03-14 12:03 UTC, lupus2k commented
> I just noticed that the test needs to be updated to pass with the new copy.

Thanks, @candy02058912, I will update during the day!

2023-03-14 14:27 UTC, paulopmt1 approved these changes
Nice work, LGTM @lupus2k!

2023-03-16 08:20 UTC, candy02058912 approved these changes
LGTM! Thanks for updating it.

2023-03-22 18:42 UTC, merged

2023-03-22 19:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7860310).