Add Apple Silicon link to desktop links and footer
Automattic/wp-calypso pull request #74412
Opened 2023-03-14 10:16 UTC by katinthehatsite

- Fix: https://github.com/Automattic/wp-calypso/issues/74232

## Proposed Changes

* This PR adds Mac (Apple Silicon) link to `https://wordpress.com/me/get-apps` to make it consistent with `https://apps.wordpress.com/`
* This PR also adds Mac (Apple Silicon) link to the section `Also available for:` on `https://wordpress.com/me/get-apps` when that page is accessed from devices other than MacOS

## Testing Instructions

**To test the link to Mac (Apple Silicon) when on MacOS**:

* Ensure that you are using MacOS
* Navigate to `https://wordpress.com/me/get-apps`
* Scroll to the bottom of the page
* Check if the button "Download for Mac (Apple Silicon)" is present alongside "Download for Mac (Intel)":

<img width="792" alt="Screenshot 2023-03-14 at 10 56 41 AM" src="https://user-images.githubusercontent.com/25575134/224964420-a83e5aec-1190-45d3-a3bc-4919fb7aefef.png">

* Click on "Mac (Intel)" and check if the link goes to `https://apps.wordpress.com/d/osx/?ref=getapps` and triggers app download
* Click on "Mac (Apple Silicon)" and check if the link goes to `https://apps.wordpress.com/d/osx-silicon/?ref=getapps` and triggers app download

**To test a modification of the "Also available for" section**:

Note: The modification can't be tested on MacOS because they only show conditionally when you are **not** on MacOs. To check how the code would be executed on other platforms, we can switch `MacIntel` case with another case:

1. Pull changes from GitHub to your local environment
2. In `desktop-download-card.jsx` replace the code on lines 82 - 102 with this one:

```
			case 'Linux i686 on x86_64':
				return {
					firstAvailableLink: this.getLinkAnchorTag( WINDOWS_LINK ),
					secondAvailableLink: this.getLinkAnchorTag( LINUX_TAR_LINK ),
					thirdAvailableLink: this.getLinkAnchorTag( LINUX_DEB_LINK ),
					firstAvailableIcon: this.getPlatformImage( WINDOWS_LINK ),
					secondAvailableIcon: this.getPlatformImage( LINUX_TAR_LINK ),
					thirdAvailableIcon: this.getPlatformImage( LINUX_DEB_LINK ),
				};
			case 'Linux i686':
			case 'MacIntel':
				return {
					firstAvailableLink: this.getLinkAnchorTag( LINUX_DEB_LINK ),
					secondAvailableLink: this.getLinkAnchorTag( WINDOWS_LINK ),
					thirdAvailableLink: this.getLinkAnchorTag( MAC_INTEL_LINK ),
					fourthAvailableLink: this.getLinkAnchorTag( MAC_SILICON_LINK ),
					firstAvailableIcon: this.getPlatformImage( LINUX_DEB_LINK ),
					secondAvailableIcon: this.getPlatformImage( WINDOWS_LINK ),
					thirdAvailableIcon: this.getPlatformImage( MAC_INTEL_LINK ),
					fourthAvailableIcon: this.getPlatformImage( MAC_SILICON_LINK ),
				};
```

2. In `desktop-download-card.jsx` replace the code on lines 119 - 136 with this one:

```
			case 'Linux i686 on x86_64':
				return translate(
					'Also available for: ' +
						'{{firstAvailableLink}}Windows{{/firstAvailableLink}}, ' +
						'{{secondAvailableLink}}Linux (.tar.gz){{/secondAvailableLink}}, ' +
						'{{thirdAvailableLink}}Linux (.deb){{/thirdAvailableLink}}.',
					{ components: this.getTranslateComponents( platform ) }
				);
			case 'Linux i686':
			case 'MacIntel':
				return translate(
					'Also available for: ' +
						'{{firstAvailableLink}}Linux (.deb){{/firstAvailableLink}}, ' +
						'{{secondAvailableLink}}Windows{{/secondAvailableLink}}, ' +
						'{{thirdAvailableLink}}Mac (Intel){{/thirdAvailableLink}}.' +
						'{{fourthAvailableLink}}Mac (Apple Silicon){{/fourthAvailableLink}}.',
					{ components: this.getTranslateComponents( platform ) }
				);
```

3. In `desktop-download-card.jsx` replace the code on lines 149 - 166 with this one:

```
	getAlsoAvailableTextJetpack( platform ) {
		switch ( platform ) {
			case 'Linux i686 on x86_64':
				return translate(
					'{{firstAvailableLink}}{{firstAvailableIcon /}}Windows{{/firstAvailableLink}}' +
						'{{secondAvailableLink}} {{secondAvailableIcon /}} Linux (.tar.gz){{/secondAvailableLink}}' +
						'{{thirdAvailableLink}} {{thirdAvailableIcon /}} Linux (.deb){{/thirdAvailableLink}}',
					{ components: this.getTranslateComponents( platform ) }
				);
			case 'Linux i686':
			case 'MacIntel':
				return translate(
					'{{firstAvailableLink}}{{firstAvailableIcon /}}Linux (.deb){{/firstAvailableLink}}' +
						'{{secondAvailableLink}}{{secondAvailableIcon /}}Windows{{/secondAvailableLink}}' +
						'{{thirdAvailableLink}}{{thirdAvailableIcon /}}Mac (Intel){{/thirdAvailableLink}}' +
						'{{fourthAvailableLink}}{{fourthAvailableIcon /}}Mac (Apple Silicon){{/fourthAvailableLink}}',
					{ components: this.getTranslateComponents( platform ) }
				);
```

4. Save changes and navigate to `https://wordpress.com/me/get-apps`
5. Check if Mac (Intel) and Mac (Apple Silicon) links are present in the **Also available for** section:

<img width="709" alt="Screenshot 2023-03-14 at 11 13 46 AM" src="https://user-images.githubusercontent.com/25575134/224968795-f5b87a83-60b3-49dd-b3a7-9254e2731489.png">

6.  Click on "Mac (Intel)" and check if the link goes to `https://apps.wordpress.com/d/osx/?ref=getapps` and triggers app download
7.  Click on "Mac (Apple Silicon)" and check if the link goes to `https://apps.wordpress.com/d/osx-silicon/?ref=getapps` and triggers app download

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-14 11:19 UTC, sejas requested changes
@katinthehatsite , Awesome PR.

We had to do more changes than I expected in the beginning. Great job! 🥳 .

I tested it and it works as expected.
The only error I saw is we are trying to "join"  to functions on line 189. That will not work.
```
return trackMacIntelClick && trackMacSiliconClick;
```

I also added some suggestions creating a separate case for the Silicon case. I think, It will make the code more readable.

2023-03-14 11:19 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +				return trackMacIntelClick && trackMacSiliconClick;
We cannot "join" these `trackPlatformClick` with `&&`.
The result of `func1 && func2` would be a boolean value.
That would work on the command line, though.

Let's create a new case for `MacSilicon` even if that doesn't exist natively.

```suggestion
				return trackMacIntelClick;
		case 'MacSilicon':
				return trackMacSiliconClick;
```

2023-03-14 11:19 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +				return [ MAC_INTEL_LINK, MAC_SILICON_LINK ];
Good approach! It works, although sometimes we would return an array and some times a string.

Let's create a new synthetic case for the silicon case:

```suggestion
				return MAC_INTEL_LINK;
		case 'MacSilicon':
				return MAC_SILICON_LINK;
```

Or even better, let's create a new constant on the top of the file:
```
const PLATFORM_MAC_SILICON = 'MacSilicon';
```
And then that variable in the rest of the cases and calls.
```suggestion
				return MAC_INTEL_LINK;
		case PLATFORM_MAC_SILICON:
				return MAC_SILICON_LINK;
```

2023-03-14 11:19 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +				/>;
Love it !

2023-03-14 11:19 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +					</>
Having a separate case for the Mac Silicon, we would be more explicit about what we want to show.

```suggestion
				{ platform === 'MacIntel' ? (
					<>
						<Button
							className="get-apps__desktop-button"
							href={ localizeUrl( this.getButtonLink( platform ) ) }
							onClick={ this.getButtonClickHandler( platform ) }
						>
							{ this.getButtonText( platform ) }
						</Button>
						<Button
							className="get-apps__desktop-button"
							href={ localizeUrl( this.getButtonLink( PLATFORM_MAC_SILICON ) ) }
							onClick={ this.getButtonClickHandler( PLATFORM_MAC_SILICON ) }
						>
							{ this.getButtonText( PLATFORM_MAC_SILICON ) }
						</Button>
					</>
```

2023-03-14 11:19 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +	trackMacSiliconClick: () => recordTracksEvent( 'calypso_app_download_mac_silicon_click' ),
Nice addition!

We will need to register this new event: `calypso_app_download_mac_silicon_click`. Let's do it in a huddle 👌 .

2023-03-14 11:19 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +				];
Let's return each value in a separate case.

2023-03-14 11:19 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
>  				);
Well done following the same pattern we were using.

We could consider translating only 'Also available for: ' and returning the rest without any translation.

<img width="507" alt="Screenshot 2023-03-14 at 10 53 44" src="https://user-images.githubusercontent.com/779993/224984424-5df57614-a441-4677-80ef-7eeb892a1535.png">

2023-03-14 14:01 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +	trackMacSiliconClick: () => recordTracksEvent( 'calypso_app_download_mac_silicon_click' ),
Hi @rachelmcr,
@katinthehatsite and I noticed that you have created some funnels using `calypso_app_download_mac_click` event.
We are adding a button to download the Silicon version of the Desktop app, and we wonder if we should create a new event or not. What do you prefer?

1. Use the same event `calypso_app_download_mac_click` for both buttons (Silicon and Intel).
2. Create a new event, `calypso_app_download_mac_silicon_click` for the new button Silicon version.

The page we are editing is: https://wordpress.com/me/get-apps

2023-03-14 14:05 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> -	}
Nice clean up! Good catch noticing this function introduced 6 years ago is not used anymore. 👏

2023-03-14 16:19 UTC, rachelmcr commented on client/blocks/get-apps/desktop-download-card.jsx
> +	trackMacSiliconClick: () => recordTracksEvent( 'calypso_app_download_mac_silicon_click' ),
Thanks for the ping @sejas. I am not monitoring that event or using those funnels anymore, so I don't have a preference on this.

Here's an example of how we used those funnels in the past (internal reference): p9OQAC-gO-p2#comment-790

2023-03-14 16:39 UTC, sejas commented on client/blocks/get-apps/desktop-download-card.jsx
> +	trackMacSiliconClick: () => recordTracksEvent( 'calypso_app_download_mac_silicon_click' ),
Thank you @rachelmcr !

2023-03-15 08:14 UTC, wojtekn commented
@katinthehatsite looks good and works well in Safari on macOS. I was able to download both files.

I also used BrowserStack to test it on the latest Firefox on Windows, and it looked different than in the screenshot attached above (I used a window 1600px wide):

![Screenshot 2023-03-15 at 09 11 20](https://user-images.githubusercontent.com/727413/225246988-9d292641-9082-4d9d-a840-ba0df7ff2e40.png)

Is it expected?

> Navigate to https://wordpress.com/me/get-apps

Not a big deal, but it would be more clear to either provide a link without the domain, provide link using http://calypso.localhost/, or mention Calypso Live.

2023-03-15 12:24 UTC, katinthehatsite commented
> @katinthehatsite looks good and works well in Safari on macOS. I was able to download both files.
> 
> I also used BrowserStack to test it on the latest Firefox on Windows, and it looked different than in the screenshot attached above (I used a window 1600px wide):

> ![Screenshot 2023-03-15 at 09 11 20](https://user-images.githubusercontent.com/727413/225246988-9d292641-9082-4d9d-a840-ba0df7ff2e40.png)
> 
> Is it expected?

Your screenshot is what the code is expected to produce (meaning the order of icons). The reason why mine looked different because I was initially testing it not in Browserstack but by removing some conditions around MacIntel case in the code so that it will show me icons as if I were accessing them from Linux!

Good catch and apologies for the confusion - I will add the corrected screenshot to the PR description!

> > Navigate to https://wordpress.com/me/get-apps
> 
> Not a big deal, but it would be more clear to either provide a link without the domain, provide link using http://calypso.localhost/, or mention Calypso Live.

Noted!

2023-03-15 14:01 UTC, sejas approved these changes
> I also used BrowserStack to test it on the latest Firefox on Windows, and it looked different than in the screenshot attached above (I used a window 1600px wide):

For me it displays all the names in one line for screen widths 1024 or higher.
Tested also in Firefox + Windows

<img width="1020" alt="Screenshot 2023-03-15 at 13 59 00" src="https://user-images.githubusercontent.com/779993/225331455-ccebbebd-5d08-4ad1-95b2-c958a3ab2219.png">

For screens lower than 815px we have the same behaviour on production, using 2 lines for the names:

<img width="812" alt="Screenshot 2023-03-15 at 14 02 13" src="https://user-images.githubusercontent.com/779993/225332423-10b188ac-245c-42de-bda0-7283021e2033.png">


I also renamed `MacOs` to only `Mac` so it's more consistent with the linux version and the buttons in https://apps.wordpress.com/

Tested on Mac and Windows and looking great 👌 .

2023-03-16 09:41 UTC, merged