Plans: update copy for commerce features
Automattic/wp-calypso pull request #74561
Opened 2023-03-17 08:39 UTC by aneeshd16

Fixes Automattic/martech#1624

## Proposed Changes

1. On tablet and above resolutions, under "Commerce Solutions", the Business plan features should be "Available with plugins" or "Available with plugins and themes" instead of the check/dash icon, depending on the feature.
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/5436027/225853466-33a3d67f-1c86-4f6d-b7dc-653be80cd94d.png">

2. On mobile, the same text should be shown as a subtitle for the Business plan.
3. On mobile, under "Commerce Solutions", the subtitle for the Commerce plan features should be "Seamlessly integrated with your plan"
<img width="759" alt="image" src="https://user-images.githubusercontent.com/5436027/225853963-6d81746d-5d11-4d9c-97dd-ee177deb1df1.png">

## Testing Instructions

* Go to `/start/plans` and open the comparison table. 
* Confirm that the above changes are reflected for all resolutions.
* Go to `/plans/<site slug>` and confirm the same.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)? - TBD after the PR is approved.
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-20 02:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7877828

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

2023-03-20 02:20 UTC, southp requested changes
The code in general looks good and the conditional copies are shown according to the test plan perfectly. Three things: 

1. The feature title isn't aligned on mobile when the conditional text is "available with plugins", which spans in one line instead of two:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1842898/226231297-5fc1ab52-80d0-470a-a7d4-b2a24f35b63a.png">
Let's align both the title and the conditional text horizontally :) 

2. I've added "String Freeze" so the strings will hopefully get into the translation pipeline today. 

3. Do you plan to address the H4/LOHP side within Automattic/martech#1624 or a separate issue? I'm asking because the issue will be closed automatically when this PR is merged with or without the H4/LOHP side, so I'm wondering if it's intentional :)

2023-03-20 12:02 UTC, aneeshd16 commented
> 1. The feature title isn't aligned on mobile when the conditional text is "available with plugins", which spans in one line instead of two:
> Let's align both the title and the conditional text horizontally :)

Great catch! I assumed that center aligning this would work well, but it turns out it does not. 🙂 Updated this via https://github.com/Automattic/wp-calypso/pull/74561/commits/6d468fd65422b2912a6be897c8376b22607a1c5a.

> 2. I've added "String Freeze" so the strings will hopefully get into the translation pipeline today.

Thanks! I was planning to do this once the PR was approved.

> 3. Do you plan to address the H4/LOHP side within [Automattic/martech#1624](https://github.com/Automattic/martech/issues/1624) or a separate issue? I'm asking because the issue will be closed automatically when this PR is merged with or without the H4/LOHP side, so I'm wondering if it's intentional :)

Yes, the backend change is also ready: D105259-code

2023-03-21 08:10 UTC, southp commented
Thanks for the fix, @aneeshd16 . There is one more polishing request from @lucasmendes-design in Automattic/martech#1624. Citing it here for easier reference:

> Hi @aneeshd16 , I checked the Calypso live link and noticed that the feature name is not centralized when we have two lines.


![](https://user-images.githubusercontent.com/98343583/226356414-332d6c8e-f703-4f7a-a22d-0caf87ac3ebd.png)

![](https://user-images.githubusercontent.com/98343583/226356648-dc496fe7-a0e6-4387-ad68-175dd25d9b8f.png)

Let's also address this, and I'll retest and re-review this PR afterwards :)

2023-03-22 02:41 UTC, southp approved these changes
Thanks for all the fine-tuning along the way. LGTM :)

2023-03-23 02:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7877828).

2023-03-24 06:47 UTC, aneeshd16 commented
This PR needs updating after a rebase, moving to In-Progress.

2023-03-24 07:22 UTC, aneeshd16 commented
Hi @southp/ @claudiucelfilip, can you please review this one more time? Thanks in advance!

2023-03-27 04:14 UTC, southp approved these changes
@aneeshd16 Sorry for the late response. I've reconfirmed that the layout issues are all fixed. LGTM :)

2023-03-27 06:16 UTC, merged