Stats: Add new Subscribers chart
Automattic/wp-calypso pull request #74568
Opened 2023-03-17 11:48 UTC by a8ck3n

Related to #74404.

## Proposed Changes

Adds a new Subscribers chart to the Traffic page.

## Testing Instructions

Launch the live branch to see the new chart. Currently showing sample data at the top of the page. Will be moved to the bottom of the page and gated behind a feature flag.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-21 02:02 UTC, grzegorz-cp requested changes
Looks good but we can simplify it a bit for now.

2023-03-21 02:02 UTC, grzegorz-cp commented on client/my-sites/stats/subscribers-section/index.jsx
> +	const data = [
Let's start only with this array because it resembles the format Jasper and Anna are adding. In the meantime, if we don't want to worry about mock data from another ticket, we can use the same data as the bar chart.
Since this is already here, let's keep it but focus on one data source. The above two samples are in a different format which might add complexity.

2023-03-21 02:02 UTC, grzegorz-cp commented on client/my-sites/stats/subscribers-section/index.jsx
> +	if ( DATA_TYPE === 'multi' ) {
It's great that you are thinking about multiple data sets, but let's simplify as much as possible for now until we get designs.

2023-03-21 02:02 UTC, grzegorz-cp commented on client/my-sites/stats/subscribers-section/index.jsx
> +	if ( DATA_TYPE === 'single' ) {
A ternary operator would be great for this function.

2023-03-21 08:40 UTC, a8ck3n commented
> Looks good but we can simplify it a bit for now.

Thanks for the feedback @grzegorz-cp! I've simplified things per you comments and pushed up the changes. I'll put this behind a feature flag next and we can go from there.

2023-03-22 01:02 UTC, grzegorz-cp approved these changes
Looks good, thanks for the changes. I just noticed a small issue.

2023-03-22 01:02 UTC, grzegorz-cp commented on client/my-sites/stats/site.jsx
> +				{ /* TODO: Move SubscribersSection comp here */ }
Let's move it here before merging.

2023-03-24 08:22 UTC, merged