Tweaked CSS to fix line shadow
Automattic/wp-calypso pull request #74580
Opened 2023-03-17 15:47 UTC by DustinHartzler

Related to #1202619025189113-as-1203462995555473/f

## Proposed Changes

* Fixed drop shadow when a license is selected in a row:

![image](https://user-images.githubusercontent.com/2293077/225952927-d5912bda-f789-4308-9215-5d9d965a69e9.png)

## Testing Instructions

- Run `fix/jetpack-agency-line-selected-shadow` and `yarn start-jetpack-cloud`
- Open http://jetpack.cloud.localhost:3000/, and you'll be redirected to the /dashboard.
- Select an *(+ Add)* button to select a license for a site. Make sure it looks like the screenshot above

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-20 07:04 UTC, yashwin requested changes
The request was also to remove the opacity/disable state set to the other rows along with this change - https://github.com/Automattic/wp-calypso/pull/70335#issuecomment-1331384897

![204658020-441e7b38-8b46-4d7d-8ea9-5ee44f7d83fc (1)](https://user-images.githubusercontent.com/10586875/226269483-bf4b4a39-1cf5-4dfb-9272-fe039a6c50cc.png)

2023-03-20 15:35 UTC, DustinHartzler commented
Okay, so even though we can only add multiple licenses to one site at a time, we still need to keep all the rows in a non-grayed out state?

Am I understanding this correctly?

2023-03-21 06:47 UTC, yashwin commented
> Okay, so even though we can only add multiple licenses to one site at a time, we still need to keep all the rows in a non-grayed out state?
> 
> Am I understanding this correctly?

Yes, correct

2023-04-19 17:17 UTC, jeffgolenski commented
@yashwin @DustinHartzler I'm just testing this out on the live branch. I'm seeing two things:
1) I can still only select one license at a time. Should that be the case, here?
2) The column width jumps when the pill turns from "add" to "selected." Is there anyway we can avoid that?

The dropshadow looks great though. Nice work there!

2023-04-20 06:43 UTC, yashwin commented
@jeffgolenski - Thanks for the review

> I can still only select one license at a time. Should that be the case, here?

Do you mean you can select licenses from one site at a time? If yes, this is something that was decided as V2 of this feature. You can follow our discussion about the same here - https://github.com/Automattic/wp-calypso/pull/70335#issuecomment-1331718061

> The column width jumps when the pill turns from "add" to "selected." Is there anyway we can avoid that?

Oh yeah. I have created a [ticket](1202619025189113-as-1204438047173015), and it'll be addressed in a separate PR, as this change is not related to the issue.

2023-04-24 14:29 UTC, jeffgolenski commented
@yashwin Sorry. my video didn't upload! 


https://user-images.githubusercontent.com/214813/234027295-8c80779e-b3ae-422c-b12c-db2e0210dbee.mov

> If yes, this is something that was decided as V2 of this feature. You can follow our discussion about the same here

Got it! Thank you.

> Oh yeah. I have created a [ticket](https://github.com/Automattic/wp-calypso/pull/1202619025189113-as-1204438047173015), and it'll be addressed in a separate PR, as this change is not related to the issue.

Awesome. thanks again! 

Carry on!

2023-04-25 14:10 UTC, vitozev commented
Should we fix the jumpy column in this PR?

2023-04-25 15:52 UTC, yashwin commented
@vitozev 

> Should we fix the jumpy column in this PR?

This change must be tested on different screen resolutions with different text sizes and scenarios. I suggest we keep it in a different PR.

2023-04-26 07:19 UTC, yashwin commented
@jeffgolenski & @vitozev 

The jumpy columns issue will be resolved via https://github.com/Automattic/wp-calypso/pull/76269

2023-05-24 12:03 UTC, TheSteveK approved these changes
LGTM

2023-05-25 04:10 UTC, merged