Jetpack Pro Dashboard: show "Not supported on multisite" when a product is not supported on a multisite
Automattic/wp-calypso pull request #74692
Opened 2023-03-21 07:21 UTC by yashwin

Closes https://github.com/Automattic/wp-calypso/issues/73406

## Proposed Changes

This PR makes the following changes

- Show `-` with a tooltip showing `Not supported on multisite` when the product is `Scan`
- Show `-` with a tooltip showing `Not supported on multisite` when the product is `Backup` and does not have a backup subscription https://href.li/?https://wp.me/pbuNQi-1jg

## Testing Instructions

#### Testing Instructions

**Prerequisites**

Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb. Make sure to switch it back to the previous type.

**Instructions**

1. Run `git checkout fix/handle-unsupported-products-for-multisite` and `yarn start-jetpack-cloud`
2. Open http://jetpack.cloud.localhost:3000/, and you'll be redirected to the /dashboard.
3. Add a multisite with a plan that usually would include Backup & Scan, e.g. Complete.
4. Verify that the Backup column shows the clock or check icon and Scan shows `-` and when hovering over, it shows `Not supported on multisite`. We will show the backup as it is if it is already added - https://href.li/?https://wp.me/pbuNQi-1jg
5. Add another multisite without any plan
6. Verify that both Backup &  Scan shows `-` and when hovering over, it shows `Not supported on multisite`.

<img width="332" alt="Screenshot 2023-03-21 at 12 35 56 PM" src="https://user-images.githubusercontent.com/10586875/226539751-e001dcab-de2d-4635-8ea2-97b41879c19b.png">

<img width="435" alt="Screenshot 2023-03-21 at 12 36 06 PM" src="https://user-images.githubusercontent.com/10586875/226539368-021af099-e6ad-4218-b973-389818cb27b6.png">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-21 12:01 UTC, vitozev reviewed
Works as expected! I just noticed one minor issue:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1749918/226600013-3862e3b2-95f7-44c3-aa48-9a36c829b1fa.png">

The "1 available" isn't an actual link for the multisite, is that expected?

2023-03-21 12:59 UTC, yashwin commented
> The "1 available" isn't an actual link for the multisite, is that expected?

Thanks for the review. No, it is not. I have fixed it now - https://github.com/Automattic/wp-calypso/pull/74692/commits/df64857113b2c05300597cc5550f30644a936e2f

2023-03-21 13:26 UTC, vitozev commented on client/jetpack-cloud/sections/agency-dashboard/sites-overview/site-status-content.tsx
> +	let updatedTooltip = tooltip;
What do you think about not introducing a new variable here?

We can do something like this:

```
const { a } = foo; 
let { b } = foo;
```

We can cache the value of `getRowMetaData` and use it on two separate destructuring assignments.

2023-03-21 13:27 UTC, vitozev requested changes
I added one comment that I think will make the code easier to read. WDYT?

2023-03-22 06:07 UTC, yashwin commented
> I added one comment that I think will make the code easier to read. WDYT?

I have made the changes - https://github.com/Automattic/wp-calypso/pull/74692/commits/93fda786fb7cfc757aec4217ec1ad1e10c2314ae

2023-03-22 07:45 UTC, vitozev approved these changes
LGTM!

2023-03-23 06:15 UTC, merged

2023-03-23 08:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7883000

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

2023-03-30 12:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7883000).