Tailored Flows: Improve step titles along flows
Automattic/wp-calypso pull request #74723
Opened 2023-03-21 15:13 UTC by renancarvalho

## Proposed Changes

Newsletter and LiB steps title are mismatching on the spacing to the top of the page, this PR fixes it.

## Testing Instructions
To make it easier, I have installed a chrome extension to help me visualize the spacing on the browser, I would recommend you to install as well, it is quite good. [Page Ruler](https://chrome.google.com/webstore/detail/page-ruler/jcbmcnpepaddcedmjdcmhbekjhbfnlff?hl=en)

- Pull and run this branch or use calypso live links
- Navigate to /setup/newsletter or /setup/link-in-bio
- Enable the extension
- All the titles should be 100px from the top. ( like image attached )
- This pattern should be consistent along the whole flow
- Would be amazing to check other flows just in case :)

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/2653810/226646858-961e3b37-e4cf-4ba6-8ca1-2a5a20c17353.png">

Related to #74662 
[more context ](puPv3-e72-p2)

2023-03-21 15:36 UTC, obenland commented on client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
> +			flowName={ isCopySiteFlow( flow ) ? ( flow as string ) : ( flow as string ) }
Could this be simplified, now that both cases will be the same? Not sure if it would still need the parenthesis.

```suggestion
			flowName={ ( flow as string ) }
```

2023-03-22 09:25 UTC, renancarvalho commented on client/landing/stepper/declarative-flow/internals/steps-repository/domains/index.tsx
> +			flowName={ isCopySiteFlow( flow ) ? ( flow as string ) : ( flow as string ) }
Absolutely! Thank you for reviewing it :)

2023-03-22 10:34 UTC, alshakero requested changes
This seems to have broken the intro step.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/17054134/226876970-a564eccc-29ee-4b3d-93d3-eb42a4cfa3c8.png">

2023-03-23 14:49 UTC, alshakero approved these changes
Looks good this time!

2023-03-23 14:49 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domains/style.scss
> +				margin: 36px 0px 40px 0px;/* stylelint-disable-line length-zero-no-unit */
```suggestion
				margin: 36px 0 40px 0;
```

2023-03-23 15:49 UTC, merged

2023-03-24 06:43 UTC, arthur791004 commented
Hiya! I found this PR made the text of the processing step not in the center. You can visit `/setup/site-setup/processing?siteSlug=<your_site>` to see the processing step.

| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/13596067/227444806-8d6896cd-8891-4ef3-8d9b-c0be1ebd10ee.png) | ![image](https://user-images.githubusercontent.com/13596067/227445317-59b5e3ba-1077-4440-a738-e6a51adbe39b.png) |