Newsletter: Change focus on subscribers and setup
Automattic/wp-calypso pull request #74780
Opened 2023-03-22 14:19 UTC by escapemanuele

On the newsletter flow, Focus state is different in user signup page and subsequent pages with inputs.

This updates the focus state on setup and subscriber steps.

Fixes https://github.com/Automattic/wp-calypso/issues/74583

2023-03-22 14:53 UTC, alshakero requested changes
Looks exactly as spec'd!

The error state in subscribers step looks strange. I'll ask Cris for feedback.

![image](https://user-images.githubusercontent.com/17054134/226943317-f209e6fc-e2bb-4966-a8c9-6afd42b0ead5.png)

2023-03-22 15:33 UTC, escapemanuele commented
Maybe it should follow what is on the signup step that we took as an example for the focus state 🤔 

<img width="468" alt="image" src="https://user-images.githubusercontent.com/52076348/226956229-9e06c519-56d0-4d06-a938-0fe8993927ea.png">

2023-03-22 15:53 UTC, alshakero commented
Yes I agree!

2023-03-22 17:10 UTC, escapemanuele commented
Ok @alshakero, should be better now!

<img width="427" alt="image" src="https://user-images.githubusercontent.com/52076348/226983791-092e2f71-c3f7-41c4-b596-83faf88d6596.png">

2023-03-23 08:56 UTC, alshakero approved these changes
Super ✨

2023-03-23 09:21 UTC, merged