Marketplace Thank You: Update plugin card styles
Automattic/wp-calypso pull request #74792
Opened 2023-03-22 17:08 UTC by epeicher

Resolves #74740

## Proposed Changes

* Update styles for Plugin cards in Marketplace Thank You page

## Testing Instructions

* Go to `/plugins:siteId` and purchase a couple of Marketplace plugins
* Make sure the design of the Thank You page plugin cards matches 5ddl1WFTEnaIatL2WlZp4k-fi-2596%3A11300

|Before | After|
|-------|------|
| ![CleanShot 2023-03-22 at 18 02 35@2x](https://user-images.githubusercontent.com/3519124/226982101-739e1213-9267-4fbe-b199-8c9f5cb35fa2.png) | ![CleanShot 2023-03-22 at 18 07 28@2x](https://user-images.githubusercontent.com/3519124/226983343-22474f4b-d6c6-45ec-9c90-dcf0ee9aa955.png)    |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-23 11:40 UTC, epeicher commented
Hi @vinimotaa , I have implemented the plugin card styles. The scenario with only plugins currently has a `border-top` for all the cards. Removing that border would require adding some extra logic or complex CSS selectors. Do you think this is good for the first iteration?

|Plugins and a Theme | Only plugins|Only a Theme|
|-------|------|------|
|   ![CleanShot 2023-03-23 at 12 39 04@2x](https://user-images.githubusercontent.com/3519124/227192634-8ee8a73d-be2f-4675-b2b6-26711c4a6183.png)     |      ![CleanShot 2023-03-23 at 12 38 40@2x](https://user-images.githubusercontent.com/3519124/227192682-f12d7856-ee76-4914-b692-ffb717c48375.png)  |    ![CleanShot 2023-03-23 at 12 39 23@2x](https://user-images.githubusercontent.com/3519124/227192600-6dfcef4a-c272-4b3b-8bed-c15f557f882e.png)    |

UPDATE: The above will be fixed as part of [the ](https://github.com/Automattic/wp-calypso/pull/74792/commits/f1ac0fc58f3f1628dfdf4212b7045dcae42a79b4)

2023-03-23 12:08 UTC, cpapazoglou requested changes
To be honest, the top border of the first item looked like a glitch to me before reading the comments. I believe fixing it doesn't require enormous effort.

2023-03-23 12:08 UTC, cpapazoglou commented on client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-plugin-section.tsx
> +	border-top: 1px solid var( --studio-gray-5 );
It seems that we need to move the styling to https://github.com/Automattic/wp-calypso/blob/732eadac995183afa5acbabab5dbed64037ad72d/client/components/thank-you/index.tsx#L29-L31

![CleanShot 2023-03-23 at 14 05 01@2x](https://user-images.githubusercontent.com/12430020/227198684-7d97eff2-6621-448f-ba0b-acf596377291.png)

You can try it by visiting `/checkout/gift/thank-you/:site`

2023-03-23 12:08 UTC, cpapazoglou commented on client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-plugin-section.tsx
> +	border-top: 1px solid var( --studio-gray-5 );
Doing this accompanied with a `:first-child` rule should be enough for getting rid of the line of the first element.

2023-03-27 14:32 UTC, epeicher commented on client/my-sites/checkout/checkout-thank-you/marketplace/marketplace-thank-you-plugin-section.tsx
> +	border-top: 1px solid var( --studio-gray-5 );
This should be sorted by [f1ac0fc](https://github.com/Automattic/wp-calypso/pull/74792/commits/f1ac0fc58f3f1628dfdf4212b7045dcae42a79b4) and the merge that includes this commit https://github.com/Automattic/wp-calypso/commit/e05ecee17cefeba722636cd9ef73899d83b056a7 that removes the theme section when there are no themes to display [here](https://github.com/Automattic/wp-calypso/commit/e05ecee17cefeba722636cd9ef73899d83b056a7#diff-ffe5b17b99241dfd054caea592cb72136e81dce734f9f62f5ae1b0ff3843b13dR121)

2023-03-27 14:43 UTC, cpapazoglou approved these changes
Thanks @epeicher, looks stunning now

![CleanShot 2023-03-27 at 17 40 31@2x](https://user-images.githubusercontent.com/12430020/227974808-ec8bc4e9-ca25-4bdd-b2f5-cb0f2f864027.jpg)

2023-03-27 14:51 UTC, merged