Site Assembler: Restyle the font preview to display the entire font name
Automattic/wp-calypso pull request #74879
Opened 2023-03-24 09:35 UTC by arthur791004

Related to pbxlJb-3EX-p2

## Proposed Changes

* People want to see the entire font name of the preview so they're able to know which font we will apply. So, this PR is proposing to restyle the font preview to display the full font name.
* There is an [issue](https://github.com/Automattic/wp-calypso/pull/74268) related to the scrollbar width inside the iframe. Sometimes it sill happens. So, this PR is also proposing to disable scrolling inside the iframe.

## Testing Instructions

* Go to /setup?siteSlug=<your_site>&flags=pattern-assembler/color-and-fonts
  * Note that the site should be the site with a free plan
* Continue until you land on the Design Picker
* On the Design Picker screen, scroll down to the bottom and select BCPA CTA
* On the Pattern Assembler screen
  * Select `Fonts` and verify you're able to see the entire font name

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-24 16:17 UTC, davewhitley requested changes
This is a great improvement! I think this is good to ship until a better design comes along.

If we can change the font size and gap in between the font pairing:
- 14px font size instead of 12px on the secondary font
- row gap of 4px between the 2 fonts looks better to me

<img width="306" alt="Screen Shot 2023-03-24 at 11 15 18 AM" src="https://user-images.githubusercontent.com/618551/227582324-a2fa961d-e0e4-4038-ba9d-077bf3ee32bc.png">

2023-03-27 06:39 UTC, arthur791004 commented
Updated!

✅ 14px font size instead of 12px on the secondary font
✅ row gap of 4px between the 2 fonts looks better to me

![image](https://user-images.githubusercontent.com/13596067/227860228-e24e3192-fb46-442f-9e64-44012c84a85a.png)

2023-03-27 07:56 UTC, taipeicoder approved these changes
LGTM 👍

2023-03-28 05:58 UTC, arthur791004 commented
@davewhitley I'll merge this since your feedback is addressed. Feel free to share your thoughts when you're back from AFK 🙂

2023-03-28 05:58 UTC, merged