Hide variant picker for Akismet Personal plans
Automattic/wp-calypso pull request #74992
Opened 2023-03-27 20:54 UTC by CodeyGuyDylan

## Proposed Changes

This diff removes the product variant picker for Akismet Personal plans, as we are only planning on selling yearly plans for now

## Testing Instructions

TBD

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-03-27 21:33 UTC, sirbrillig approved these changes
I haven't testing (I leave that to your team) but from a Payments perspective this looks good to me! Thanks for adding a test!

2023-03-28 15:58 UTC, DavidRothstein requested changes
>as we are only planning on selling yearly plans for now

@michaeldcain pointed out that the monthly version of this product is already marked as not available to be sold in the server-side code.  So the bug here is actually on the server.  We should never be offering someone a variant in the variant picker that can't actually be purchased, because if they try to buy it, it will fail.

I'll create an issue to fix this server-side.  I don't think you will need any Calypso changes here at all.

2023-03-28 16:02 UTC, DavidRothstein commented
>I'll create an issue to fix this server-side.

Issue created here (should be a very easy fix, I think): https://github.com/Automattic/payments-shilling/issues/1508

2023-03-28 16:32 UTC, robertsreberski reviewed
The PR tests well, but I would address first disabling `ak_personal_monthly` altogether

2023-03-28 16:32 UTC, robertsreberski commented on client/my-sites/checkout/composite-checkout/test/util/index.ts
> +export const akismetPersonalProduct: ResponseCartProduct = {
Should we also add a test case for `product_slug: 'ak_personal_monthy'`?

It's possible to enter checkout also with this product (or am I wrong)? Should we actually offer this product in the first place, if we don't want to sell it?

2023-03-28 17:18 UTC, CodeyGuyDylan commented on client/my-sites/checkout/composite-checkout/test/util/index.ts
> +export const akismetPersonalProduct: ResponseCartProduct = {
I actually just added validation to remove this product on the server side, as well as a test there so I don't think that is necessary here. This whole PR might actually be unnecessary 😄

2023-03-28 17:26 UTC, sirbrillig commented
> Issue created here (should be a very easy fix, I think): https://github.com/Automattic/payments-shilling/issues/1508

D106310-code may make this PR unnecessary.

2023-03-28 17:34 UTC, CodeyGuyDylan commented
Closing this PR as it is probably not needed. Will reopen if necessary

2023-03-28 17:34 UTC, closed without merging