Staging Sites: Customize Privacy section to streamline 'Public' option
Automattic/wp-calypso pull request #75496
Opened 2023-04-10 16:23 UTC by danielbachhuber

See https://github.com/Automattic/dotcom-forge/issues/2105
Related https://github.com/Automattic/wpcomsh/pull/1343

## Proposed Changes

Streamlines the 'Public' option for the Privacy Settings of a Staging Site:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/36432/230943860-1d905933-c581-416c-ad66-07615c8308ce.png">

Non-Staging Sites remain the same:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/36432/230944005-430bd903-a8f7-4d83-9803-d6d0961c1215.png">

## Testing Instructions

1. Create a Business site and take it Atomic.
2. Navigate to 'General Settings' and verify the 'Launch site' UI appears as expected.
3. Launch the site and verify the Privacy settings appear as expected (unchanged).
4. Navigate to 'Hosting Configuration' and create a staging site.
5. Navigate to 'General Settings' for the staging site and verify the new Privacy Settings appear as expected.
6. Spin up a jurassic.ninja site and verify the Privacy Settings appear as expected (unchanged).
7. Create a Personal site and verify the Privacy Settings appear as expected (unchanged).

2023-04-10 23:48 UTC, sejas requested changes
@danielbachhuber , I think we could optimize the code a bit.
What do you think?

It works as expected. The actual value of `blog_public` is overwrited in the backend, but I agree that it's more consistent to change it in the frontend too.

We could consider adding new tests.

2023-04-10 23:48 UTC, sejas commented on client/my-sites/site-settings/form-general.jsx
> +				{ ! isNonAtomicJetpackSite && ! isWpcomStagingSite && (
Could we re-use the same `FormLabel`/`FormRadio` independently if `isWpcomStagingSite`?

Something like this:
```suggestion
				{ ! isNonAtomicJetpackSite && (
```

```diff
					<FormLabel className="site-settings__visibility-label is-public">
						<FormRadio
							name="blog_public"
							value="1"
							checked={
								( wpcomPublicComingSoon && blogPublic === 0 && isComingSoonDisabled ) ||
								( blogPublic === 0 && ! wpcomPublicComingSoon ) ||
								blogPublic === 1
							}
							onChange={ () =>
								this.handleVisibilityOptionChange( {
-									blog_public: 1,
+									blog_public: isWpcomStagingSite ? 0 : 1,
									wpcom_coming_soon: 0,
									wpcom_public_coming_soon: 0,
								} )
							}
							disabled={ isRequestingSettings }
							onClick={ eventTracker( 'Clicked Site Visibility Radio Button' ) }
							label={ translate( 'Public' ) }
						/>
					</FormLabel>
```

2023-04-10 23:48 UTC, sejas commented on client/my-sites/site-settings/form-general.jsx
> +				) }
Then we could avoid duplicating all this logic:

```suggestion
				{ isWpcomStagingSite && (
					<FormSettingExplanation>
						{ translate(
							'Your site is visible to everyone, but search engines are discouraged from indexing. Staging sites cannot be indexed by search engines.'
						) }
					</FormSettingExplanation>
				) }
```

2023-04-13 15:00 UTC, javierarce commented
I like the general approach, but here's an alternative copy for the new option:

`Your staging site is visible to everyone but search engines won't index it.`

2023-04-14 12:37 UTC, danielbachhuber commented
I went with `Your site is visible to everyone, but search engines are discouraged from indexing staging sites.`.

The form seems a bit boogered right now, though 😞 I think I need to give this a really thorough shake with lots of tests.

2023-04-17 10:27 UTC, kriskorn approved these changes
Looks good. Thank you!

2023-04-25 12:55 UTC, sejas approved these changes
@danielbachhuber, Thanks for adding the `<PublicFormRadio />` component.

It works as described.

<img width="730" alt="Screenshot 2023-04-25 at 13 55 25" src="https://user-images.githubusercontent.com/779993/234282869-a5a30196-c4cf-4852-b39a-351675c51198.png">

2023-04-25 13:32 UTC, danielbachhuber commented
@kriskorn @vparkhere Could one of you give this some thorough testing in the calypso.live environment? More specifically, testing with Business + staging sites, but also with Jetpack-connected sites, Simple sites, and maybe P2s. You can compare the behavior in calypso.live with wordpress.com.

2023-04-25 13:44 UTC, kriskorn commented
@danielbachhuber We will do that in a couple of hours and report back afterwards, so expect a comment from me or Victoria in about 4-6 hours.

2023-04-25 16:49 UTC, vparkhere approved these changes
Checked:
1) Jurassic Ninja
2) Atomic
3) Business simple plan 
4) free simple site
5) staging site

Everything looked and worked as expected!

2023-04-25 21:46 UTC, merged

2023-04-25 22:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7949009

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

2023-05-05 12:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7949009).