Happy block first iteration
Automattic/wp-calypso pull request #75620
Opened 2023-04-12 10:25 UTC by escapemanuele

[Context](IceKRdz5qlPYwuqzu6pBgF-fi-1815_26190) - Point 6

This PR creates a new block in the Happy Blocks library, to be used by /support /forums and /learn.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/52076348/231430399-6253637c-5a86-4d09-b5c2-7e703a210e18.png">

## Testing
1. Checkout branch
2. `cd apps\happy-blocks`
3. `yarn dev --sync`

Related to

2023-04-13 10:32 UTC, alshakero requested changes
Great work. I love these for some reason. Left some tiny comments.

2023-04-13 10:32 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/index.php
> +				<?php esc_html_e( 'Your information will be used in accordance with WordPress.com privacy policy.', 'happy-blocks' ); ?>
PP should be a link to https://automattic.com/privacy/

2023-04-13 10:32 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/style.scss
> +.support-content-footer {
Can we wrap this whole this with something that starts with `happy-blocks`?

2023-04-13 10:32 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/style.scss
> +			}
Both of these need some border love (namely color and radius).

![image](https://user-images.githubusercontent.com/17054134/231732729-ba484854-71b7-4701-bd5f-6cdf218e0ecd.png)

2023-04-13 15:37 UTC, escapemanuele commented
Thank you @alshakero, I think I addressed all the feedback ✌️

2023-04-13 15:56 UTC, alshakero requested changes
Super. Left some tiny CSS issues.

2023-04-13 15:56 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/style.scss
> +				color: var(--color-primary-0);
Needs a `border: none` and `cursor: pointer`. And maybe some opacity on hover.

2023-04-13 15:56 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/style.scss
> +					height: 100%;
This ruins the aspect ratio of the picture. One of them should be 100%, I think height.

2023-04-13 15:56 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/style.scss
> +		font-size: 1.25rem;
Needs border-radius.

2023-04-14 09:11 UTC, alshakero approved these changes
Tiny important mistake. Then ship!

2023-04-14 09:11 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/index.php
> +				<input class="support-content-subscribe-email" required="required" type="email" name="email" placeholder="<?php esc_html_e( 'Enter your email address', 'full-site-editing' ); ?>"  id="subscribe-f
Incorrect text-domain. It's from the linter.

2023-04-14 09:11 UTC, alshakero commented on apps/happy-blocks/block-library/support-content-footer/index.php
> +						<?php esc_html_e( 'Search Guides', 'full-site-editing' ); ?>
+1

2023-04-14 11:31 UTC, merged