Launchpad: Add use launchpad checklist hook to launchpad screens
Automattic/wp-calypso pull request #76154
Opened 2023-04-24 19:44 UTC by jeyip

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-04-25 13:49 UTC, agrullon95 requested changes

2023-04-25 13:49 UTC, agrullon95 commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
> +			isEmailVerified
We need to update `getEnhancedTasks()` to determine the task completion statuses based on `launchpadChecklist`.  Task completion status logic was previously relying on `checklist_statuses`.

2023-04-25 15:09 UTC, agrullon95 commented
Im also noticing a delay with the sidebar data loading.


https://user-images.githubusercontent.com/10482592/234320622-1182c100-7e51-460a-b68c-6b2616a5d149.mp4

2023-04-25 21:41 UTC, jeyip commented
> Im also noticing a delay with the sidebar data loading.

Ah interesting. This is because of a delayed connection -- I imagine because of high traffic through a sandboxed public API?

Either way, this is demonstrating an important point -- we now rely on a network request to load the sidebar task list, which may take several seconds. I know we're averse to loading spinners, but I'm unsure how else we'd convey that we're loading data.

@agrullon95 do you have thoughts?

@nuriapenya wondering if you can chime in

2023-04-25 21:43 UTC, jeyip commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/sidebar.tsx
> +			isEmailVerified
I was planning to do this in a follow-up to keep this PR compact. Leaving it as is for the time being doesn't change the resulting behavior, and it keeps this PR compact

2023-04-26 09:39 UTC, Sharpirate commented
> I know we're averse to loading states and loading spinners, but I'm unsure how else we'd convey that we're loading data.

Can we pre-fetch the tasks as part of the loading screen that is shown right before Launchpad?

2023-04-26 10:23 UTC, Sharpirate commented
### Testing
✔️ VideoPress tasks are matching production and behave as expected
✔️ Build tasks are matching production and behave as expected
✔️ Write tasks are matching production and behave as expected

❌ I am seeing a different list of tasks for Newsletter between this branch and prod:

![image](https://user-images.githubusercontent.com/20927667/234547259-a70a076e-fa17-4c5e-a616-345fd5ca66b2.png)

❌ I am unable to launch my Link in Bio site - the launch button never gets enabled even after completing the Add Links task

I've tested without sandboxing the public API and still experienced very long loading times like Anthony.

2023-04-26 20:08 UTC, jeyip commented
@nuria suggested a loading screens similar to what we see in the domains onboarding page p1682518854697819/1682459093.067819-slack-CHN6J22MP

I'll get started implementing it now

2023-04-26 20:54 UTC, agrullon95 commented
I would prefer a loading placeholder (not sure what the correct name is), so user's at least know content is supposed to appear in that area instead of seeing a blank space where the checklist should be.

2023-04-27 07:24 UTC, jeyip commented
Updated the loading status @agrullon95 

![2023-04-27 00 23 16](https://user-images.githubusercontent.com/5414230/234789782-22949e87-73aa-4323-b9c4-052e77ca9c2f.gif)

2023-04-27 09:42 UTC, jeyip commented on packages/help-center/src/hooks/use-launchpad-checklist.tsx
> +		placeholderData: { checklist: [] },
placeholderData doesn't overwrite cached values ( which we _do_ store between sessions in https://github.com/Automattic/wp-calypso/blob/trunk/client/state/query-client.ts#L12-L19 )

2023-04-27 17:14 UTC, agrullon95 commented
@jeyip - I dont see the loading placeholder on the sidebar when I go through the onboarding flow and land on the launchpad.

https://user-images.githubusercontent.com/10482592/234938817-c2959e64-48c3-4d44-94d7-73a6a74bb804.mp4

2023-04-27 18:13 UTC, Sharpirate commented
### Testing

Tested a few different flows and the loading screen works as expected

2023-04-27 19:25 UTC, jeyip commented
**Note:**

If you're testing against production, the current newsletter checklist definitions are incorrect fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Qzh%2Qjcpbz%2Qcyhtva%2Scebqhpgvba%2Siraqbe%2Snhgbznggvp%2Swrgcnpx%2Qzh%2Qjcpbz%2Sfep%2Ssrngherf%2Synhapucnq%2Synhapucnq.cuc%3Se%3Qq27nq3p3%2352%2Q53-og. 

Once the new `jetpack-mu-wpcom` version is released, this will automatically be resolved

2023-04-27 20:30 UTC, jeyip commented
The bug with the newsletter checklist should be resolved @agrullon95 

![2023-04-27 13 29 20](https://user-images.githubusercontent.com/5414230/234983661-c197657b-656e-4e8d-bbda-35f48a648ede.gif)

2023-04-28 10:39 UTC, Sharpirate commented
✔️ Just retested this against `jetpack/trunk` and it works as expected

2023-04-28 15:44 UTC, agrullon95 approved these changes
> The bug with the newsletter checklist should be resolved @agrullon95

I retested the Newsletter, Free, and Write flows. The tasks were marked as completed as I went through them and I'm able to confirm I no longer see the checklist bug for the newsletter flow.

2023-04-28 20:14 UTC, merged