Blog onboarding: Implement write your first post action for design-first flow
Automattic/wp-calypso pull request #77458
Opened 2023-05-26 21:54 UTC by lupus2k

Fixes https://github.com/Automattic/dotcom-forge/issues/2523

## Proposed Changes

Enable `Write a post` on `design-first` flow.

## Tasks

- [x] Reenable write your first post action [in Calypso](https://github.com/Automattic/wp-calypso/pull/77222/commits/d10c4f2284738e34e9650f366b901a824862498c)
- [x] Once we edit the post and click in publish, we want to get redirected back to launchad flow. [Here's how we currently do it](https://github.com/Automattic/wp-calypso/blob/trunk/apps/wpcom-block-editor/src/wpcom/features/redirect-onboarding-user-after-publishing-post.js#L0-L1) for start-writing flow.
- [x] Hide W icon, Welcome tour, Schedule the post & move to trash like we did in the start-writing flow.
- [x] After completing the process, we expect to have it marked as complete in the `design-first` flow
- [ ] Ensure we don't have the verify email warning in the editor: 

![Image](https://user-images.githubusercontent.com/1044309/240428723-ef01c293-19b6-452f-bfea-612f80a5d0e2.png)

## Screenshots
| Before Writing a post | After Writing a post |
| --- | --- |
| ![image](https://github.com/Automattic/wp-calypso/assets/402286/f4b3bd06-fcdf-4a17-80f9-879ce2587542) | ![image](https://github.com/Automattic/wp-calypso/assets/402286/bc95fc8c-a16a-4287-bd5d-363ea82dcd01) |

## Testing Instructions

* As the Jetpack PR to enable the flow is now merged and may not be deployed yet, you can apply this diff D111566-code
* Go to `/setup/design-first` on an account with 0 existing sites.
* Check for the `Write a post` step on Launchpad
* Verify the `Launch your blog` button is enabled without publishing a post (as it is not a required step)
* When Writing a post, check the tasks from the top of the comment.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~~
- [ ] ~~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~~
- [ ] ~~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~~

2023-05-29 09:01 UTC, candy02058912 requested changes
I also noticed that for "Write your first post", we're going to the URL `/post/:siteSlug` (calypsofied) instead of to `:siteSlug/wp-admin/post-new.php`. Mentioning it here to confirm if this is the behavior we're looking for since the testing instructions:
> Before Write a post you have to sandbox the newly created site.

2023-05-29 09:01 UTC, candy02058912 commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
> +						disabled: mustVerifyEmailBeforePosting || isBlogOnboardingFlow( flow || null ) || false,
This is what my launchpad looks like when testing out the flow:
![launchpad](https://github.com/Automattic/wp-calypso/assets/6586048/b0fffdc4-d0d7-4ae5-95b0-49847d92b86a)

It's because `isBlogOnboardingFlow( flow || null )` is `true` since this is the `design-first` flow.

2023-05-29 09:01 UTC, candy02058912 commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
> +						disabled: mustVerifyEmailBeforePosting || isBlogOnboardingFlow( flow || null ) || false,
```suggestion
						disabled: mustVerifyEmailBeforePosting || isStartWritingFlow( flow || null ) || false,
```
I'm thinking keeping it to check `start-writing` is what we intend here since we finish writing before getting into the launchpad.

2023-05-29 13:18 UTC, lupus2k commented on client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/task-helper.ts
> +						disabled: mustVerifyEmailBeforePosting || isBlogOnboardingFlow( flow || null ) || false,
I updated disabling `Write your first post` when the post is published.

2023-05-29 18:39 UTC, lupus2k commented
> I also noticed that for "Write your first post", we're going to the URL `/post/:siteSlug` (calypsofied) instead of to `:siteSlug/wp-admin/post-new.php`. Mentioning it here to confirm if this is the behavior we're looking for since the testing instructions:
> 
> >

Thanks @candy02058912, I fixed it [here](https://github.com/Automattic/wp-calypso/pull/77458/commits/6c297932ece7b234f767a1933db51780ad5b1295)

2023-05-30 09:20 UTC, candy02058912 commented
1. Would like to make sure if this is the intended behavior: after I published the first post, and gets redirected back to the launchpad the "Write your first post" option disappears.

Video:

https://github.com/Automattic/wp-calypso/assets/6586048/155268e5-7daa-460f-99ee-afc471368c62

---


2. When I'm publish the first post, I get this screen:
![this](https://github.com/Automattic/wp-calypso/assets/6586048/e43bb7fc-75dd-423d-af00-cf01fc771b8e)
I remember we removed it for `start-writing`, should we do that here as well?

2023-05-30 09:21 UTC, candy02058912 reviewed
From the PR description

> - [ ] Ensure we don't have the verify email warning in the editor:

Would you like to create a follow-up issue for this and fix it in another PR?

2023-05-30 09:34 UTC, candy02058912 approved these changes
LGTM 👍 Left a comment [here](https://github.com/Automattic/wp-calypso/pull/77458#pullrequestreview-1450501404).
Forgot to sync `editing-toolkit` and `wpcom-block-editor` to my sandbox during my last test.

2023-05-30 15:24 UTC, lupus2k commented
> Would you like to create a follow-up issue for this and fix it in another PR?

I can't reproduce this message, apparently happened when using iframed editor. Asked @paulopmt1 to review and try to reproduce it.

2023-05-30 17:39 UTC, paulopmt1 approved these changes
Everything is working great. 

- I couldn't reproduce the email activation error message anymore.
- Publishing a site is working with or without writing the first post
- Sidebar, welcome tour, and scheduling a post are hidden inside the editor
- After publishing I get redirected back to the launchpad!

Good job @lupus2k!

2023-05-30 19:14 UTC, merged