Plans 2023: Single pricing grid. Clean up old pricing code
Automattic/wp-calypso pull request #77493
Opened 2023-05-29 12:36 UTC by chriskmnds

Related to https://github.com/Automattic/wp-calypso/issues/76766

## Proposed Changes

Tackles the second part from https://github.com/Automattic/wp-calypso/issues/76766:

> Remove the feature flag onboarding/2023-pricing-grid and anything from previous plans code (as it should be unreachable without the flag) e.g. [PlanFeatures](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features) and [PlanFeaturesComparison](https://github.com/Automattic/wp-calypso/tree/trunk/client/my-sites/plan-features-comparison) deleted.

It does not remove the old pricing grids (as they are still in use by two existing flows) but cleans up all the plumbing needed previously to render the new grid along with the old in Signup/start and Stepper.

## Testing Instructions

* TBD

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-05-31 09:23 UTC, aneeshd16 reviewed
Code-wise LGTM! I haven't tested this yet, will do soon.

2023-06-02 01:30 UTC, southp commented
I've gone through the following cases, which is basically the cases outlined in #76768 with some additions

- [x] The flows on the classic signup framework
    - [x] /start/plans
    - [x] /start/hosting
    - [x] /start/domain
    - [x] /start/p2 (confirmed it's intentionally kept as P2 and P2+ plans grid)
    - [x] /start/onboarding-pm (confirmed that it's intentionally the old one)
    - [x] /start/launch-site
    - [x] /start/premium (there is no plans step, so it's just in case :) )
- [x] Stepper flows
    - [x] /setup/newsletter
    - [x] /setup/link-in-bio
    - [x] /setup/videopress (no plan step, so just spot-checking)
    - [x] /setup/domain-upsell
    - [x] /setup/start-writing
    - [x] /setup/design-first
    - [x] /setup/wooexpress 
    - [x] /setup/domain-upsell
- [x] The plan admin page, `/plans/[paid|free]` 

So all the flows that I'm aware of work as expected for me :)  

However, I noticed that the toggle style has now become consistently broken now. It used to be intermittently broken, so I actually consider this a major breakthrough to that nasty bug :D 
In /plans:
<img width="943" alt="截圖 2023-06-02 上午8 47 56" src="https://github.com/Automattic/wp-calypso/assets/1842898/fd6a6c88-01d9-47e2-b9fa-b931c107c79e">
In /start/plans:
<img width="847" alt="截圖 2023-06-02 上午8 49 05" src="https://github.com/Automattic/wp-calypso/assets/1842898/c4acbb79-499e-48c1-a38d-84b32d4642ba">

Let's also fix this as the final touch before shipping this :)

2023-06-02 13:25 UTC, chriskmnds commented
Thanks for testing! 🙌 

> Let's also fix this as the final touch before shipping this :)

Hmm fixing that separately first might make more sense. We can put this PR on hold until the interval toggle styles are fixed unconditionally. Removing the flag might have surfaced the issue more profoundly, but merging stylesheets across several places in the app feels a bit out of scope (we have Stepper, Signup, and Styled components competing on this, more so competing on overriding the base component's styles from what it looks).

2023-06-02 19:29 UTC, jdc91 commented
> toggle style has now become consistently broken now.

@chriskmnds @southp I have previously, investigated this bug, deeply, But I was not able to follow through with the cleanup. And just saw this issue. I was able to fix the issue up to some extend although I might need to explore a bit deeper to see if there is any further cleanup required.

#77758

You can try merging the above PR into this branch and check (I did these changes inside branch update/plans-grid-2023-remove-old but brought it into trunk so that production benefits from this change as well.)

2023-06-03 18:22 UTC, chriskmnds commented
> > toggle style has now become consistently broken now.
> 
> @chriskmnds @southp I have previously investigated(p1676533798563979-slack-C040UAN6TPS) this bug, deeply, But I was not able to follow through with the cleanup. And just saw this issue. I was able to fix the issue up to some extend although I might need to explore a bit deeper to see if there is any further cleanup required.
> 
> #77758 ![image](https://user-images.githubusercontent.com/3422709/242975138-f600b61f-355c-40bd-a0c9-748f5f74af06.png)
> 
> You can try merging the above PR into this branch and check (I did these changes inside branch `update/plans-grid-2023-remove-old` but brought it into trunk so that production benefits from this change as well.)

Thanks. I appreciate that you worked on this, but so did I yesterday (hence has [assigned respective issue](https://github.com/Automattic/martech/issues/1522) to myself). Let's please be mindful of what's assigned/not-assigned when picking up work to do. There are a couple of commits on my local brewing for a PR on this. 🤔

2023-06-03 18:34 UTC, jdc91 commented
My bad @chriskmnds I just saw [the comment](https://github.com/Automattic/wp-calypso/pull/77493#issuecomment-1573732139) on mail and resurrected and worked on the old branch myself. In any case I guess I can help with a review of your PR 👍

2023-06-05 02:02 UTC, southp approved these changes
> Hmm fixing that separately first might make more sense. We can put this PR on hold until the interval toggle styles are fixed unconditionally. Removing the flag might have surfaced the issue more profoundly, but merging stylesheets across several places in the app feels a bit out of scope (we have Stepper, Signup, and Styled components competing on this, more so competing on overriding the base component's styles from what it looks).

@chriskmnds After taking another look today with a fresher mind, I've found your reasoning here making total sense, especially that:

1. There are other high impact tasks that are based on this.
2. To be honest, nothing is severly impacted by this breakage of styling –– the toggle still works; it also won't be visually unappealling enough to be considered a blocking factor.
3. The fixes that you and @jdc91 are working on look much better off as individual fix, rather than further bloating this PR.

Looking back, it should have very obvious that I shouldn't consider it a required fix from the first place, which is a good lesson for me. I've removed the Block label and approved the PR. Let's first deploy this and then move on to the follow-up works based on this 🙇🏼‍♂️

2023-06-07 03:48 UTC, aneeshd16 requested changes
@southp pointed out that this breaks the domain upsell flow, so I'm adding this review to block an accidental merge. I'll be fixing the breakage soon.

2023-06-07 10:31 UTC, aneeshd16 approved these changes

2023-06-07 11:52 UTC, southp approved these changes
Thanks for the fix, @aneeshd16 . LGTM 🚢

2023-06-07 12:29 UTC, merged