Fix conflicting interval toggle styles in plans pages
Automattic/wp-calypso pull request #77758
Opened 2023-06-02 19:17 UTC by jdc91

…file

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-03 19:03 UTC, jdc91 commented
Closed in favour of #77776

2023-06-03 19:08 UTC, chriskmnds commented
@jdc91 https://github.com/Automattic/wp-calypso/pull/77776 is what I had on my end. I approached this from the point of migrating everything to the `IntervalTypeToggleWrapper` component (and whatever remains, if any, should be things specific that can't be done from inside the component - outside of a media query, there shouldn't be any?).

You can take whatever may be useful from there and reuse here, as this looks more complete. (please don't close your PR). I think we should be explicit on why there needs to be both a styled component (with some styles) and additional SASS since we are "fixing" this once and for all.

2023-06-06 08:14 UTC, aneeshd16 requested changes
> There are three approaches
1 - Move all the child selectors shown above to sass. ( This PR )

This approach sounds good to me! Great start!

On `/setup/newsletter/plans`, I see a regression:

| Production | This PR |
|--------|--------|
|<img width="577" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/d975991b-642b-46de-94ba-02b29caff44a">|<img width="578" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/72af7828-5463-470e-9bb7-4ec683947068">| 

The size of the toggle, colours, margins and hover colour is different. I'm not sure but this could be because of the styles in this file: https://github.com/Automattic/wp-calypso/blob/55be137de83f012093a92fe4f7878d1990e03b02/client/landing/stepper/declarative-flow/internals/steps-repository/plans/style.scss#L129

There are also some styles in https://github.com/Automattic/wp-calypso/blob/4910db94dde21aced9111956d87aae3389df408d/client/my-sites/plans-features-main/components/plan-interval-selector/style.scss which I feel can be removed/consolidated so that all styles for the toggle come from a single place.

2023-06-06 16:58 UTC, jdc91 commented
Thanks for pointing out the stepper styles 👍  I have fixed them as well.
<img width="1225" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3422709/15053660-d8eb-4184-96d1-caad38b6aa12">

---

> There are also some styles in https://github.com/Automattic/wp-calypso/blob/4910db94dde21aced9111956d87aae3389df408d/client/my-sites/plans-features-main/components/plan-interval-selector/style.scss which I feel can be removed/consolidated so that all styles for the toggle come from a single place.

You are correct this #74392 should probably use this component 🤔 . I am planning to pick it up in a subsequent PR.
@daledupreez is there a reason to introduce a separate plan selector component for eCommerce trials  in #74392 ? Or can we possibly use the existing component?

2023-06-07 10:34 UTC, aneeshd16 approved these changes

2023-06-07 10:51 UTC, daledupreez commented
> You are correct the change at https://github.com/Automattic/wp-calypso/pull/74392, should probably use this component 🤔 . I am planning to pick it up in a subsequent PR. @daledupreez is there a reason to introduce a separate plan selector component for eCommerce trials in https://github.com/Automattic/wp-calypso/pull/74392 ? Or can we possibly use the existing component?

The second component includes some discount text inline:
<img width="351" alt="Screenshot 2023-06-07 at 12 48 22" src="https://github.com/Automattic/wp-calypso/assets/3376401/e3ec8c6d-a100-498a-9388-769bb80a62fa">

That was something the Woo Express team specifically wanted, as we default the display to monthly for these plans given the price tags, and we want to provide a clear signal that longer-term plans offer notable savings over the monthly options.

So we _could_ consider refactoring them into a single component, but I can't recall how much divergence there was between the two toggles beyond that aspect.

2023-06-07 13:02 UTC, jdc91 commented
I have created a task to track the other task - Automattic/martech#1821 @aneeshd16

2023-06-07 13:50 UTC, merged

2023-06-08 05:43 UTC, chriskmnds commented
I would have requested changes here I'm afraid. :/ 

I don't think we've had _three_ options to reason with here. I think we only had one (and not exactly mentioned). The goal should have been to make this interval toggle independent of environment, with a default state that is known and is what we expect (cause there's only one that is expected of this component at any point of use). To put it differently, [these](https://github.com/Automattic/wp-calypso/pull/77758/files#diff-bad007f09f6802c0aa05c2c5a3215beb51a3d277e86941257d6987142d4954deR2-R4) context-dependent rules should have been removed, and the styles/overrides done within the component's own context (not the environment's). 

Right now we don't even know what the default state is of the respective component. It makes our job for NPM migration not any easier than it was before. Once again, I feel we are patching at the surface, not fixing at the root (I think we've had a similar conversation recently when attempting to fix the grid responsiveness). A grid package will inevitably export an interval selector, just like the original grid package did ([here](https://github.com/Automattic/wp-calypso/tree/trunk/packages/plans-grid/src/plans-interval-toggle)).

It's not hard goal to think in terms of packages, and the sooner we embody that thinking into our workflows, the sooner we'll be doing a much better job at refactors. When we care about self-contained and isolated code (we will always do as long as I'm around), then might help to think in terms of "what if this was living in a package", or "what would this look like in a Storybook demo" - and we'll be attacking the ugly mess that surrounds the current plans grid (that was largely the result of folks _not_ thinking this way) way more effectively.