Stats: Add static page modules show/hide settings
Automattic/wp-calypso pull request #77778
Opened 2023-06-04 14:20 UTC by dognose24

Related to #77718 

## Proposed Changes

* Add modules settings panel with the `Popover` component.

## Testing Instructions

* Spin this change with the live branch link.
* Navigate to Stats > `Traffic` page.
* Ensure the settings button and panel are in line with the design.
* Ensure the toggle buttons work well.

<img width="1303" alt="截圖 2023-06-04 下午10 18 31" src="https://github.com/Automattic/wp-calypso/assets/6869813/db755649-853a-4203-a19b-9911096e44d9">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-05 22:48 UTC, kangzj requested changes
Unfortunately 'Insights', 'Ads' and probably more pages crashed for the PR:

<img width="614" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1425433/0f734717-2f0c-4b31-b83f-9b8e45ef7117">

2023-06-05 22:48 UTC, kangzj commented on client/blocks/stats-navigation/index.js
> +		const isHighlightsSettingsEnabled = config.isEnabled( 'stats/modules-settings' );
```suggestion
		const isHighlightsSettingsEnabled = config.isEnabled( 'stats/module-settings' );
```

2023-06-05 22:48 UTC, kangzj commented on config/client.json
> +	"stats/modules-settings",
```suggestion
	"stats/module-settings",
```

2023-06-05 22:48 UTC, kangzj commented on config/development.json
> +		"stats/modules-settings": true,
```suggestion
		"stats/module-settings": true,
```

2023-06-05 22:48 UTC, kangzj commented on config/horizon.json
> +		"stats/modules-settings": false,
```suggestion
		"stats/module-settings": false,
```

2023-06-05 22:48 UTC, kangzj commented on config/production.json
> +		"stats/modules-settings": false,
```suggestion
		"stats/module-settings": false,
```

2023-06-05 22:48 UTC, kangzj commented on config/stage.json
> +		"stats/modules-settings": false,
```suggestion
		"stats/module-settings": false,
```

2023-06-05 22:48 UTC, kangzj commented on config/test.json
> +		"stats/modules-settings": false,
```suggestion
		"stats/module-settings": false,
```

2023-06-05 22:48 UTC, kangzj commented on config/wpcalypso.json
> +		"stats/modules-settings": false,
```suggestion
		"stats/module-settings": false,
```

2023-06-05 22:49 UTC, kangzj commented on client/blocks/stats-navigation/index.js
> +		isPopoverVisible: false,
IMHO we could use a more meaningful name for Popover - for example `isPageSettingsPopoverVisible` or something?

2023-06-06 00:59 UTC, kangzj approved these changes
:shipit:

2023-06-06 04:28 UTC, merged

2023-06-06 06:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8027187

Thank you @dognose24 for including a screenshot in the description! This is really helpful for our translators.

2023-06-15 23:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8027187).