Add woocommerce core profiler jetpack login screen
Automattic/wp-calypso pull request #77826
Opened 2023-06-06 07:05 UTC by chihsuan

Related to https://github.com/woocommerce/team-ghidorah/issues/215

## Proposed Changes

Add woocommerce core profiler jetpack login screen

* Use `from` query param to check it's from woocommerce core profile flow
* Customize and add styles for the login screen if it's from woocommerce core profile flow

I am still confirming the issue with the label of the username/email field. Except for that everything else is ready for review.

## Testing Instructions

1. Go to woocommerce jetpack login screen `/log-in/jetpack?redirect_to=http%3A%2F%2Fcalypso.localhost%3A3000%2Fjetpack%2Fconnect%2Fauthorize%3Fclient_id%3D219799967%26redirect_uri%3Dhttps%253A%252F%252Fdull-wasp.jurassic.ninja%252Fwp-admin%252Fadmin.php%253Fhandler%253Djetpack-connection-webhooks%2526action%253Dauthorize%2526_wpnonce%253D3f81798d85%2526redirect%253Dhttps%25253A%25252F%25252Fdull-wasp.jurassic.ninja%25252Fwp-admin%25252Fadmin.php%25253Fpage%25253Dwc-admin%26state%3D1%26scope%3Dadministrator%253Ae0a0df66fa6e6d2b7c0969d37fa165d4%26user_email%3Dchi-hsuan.huang%2540automattic.com%26user_login%3Dchihsuanhuang%26jp_version%3D12.1.1%26secret%3DuDAtkilHDeWP4lnJewWTAH5Gv7EQVJxt%26blogname%3DDull%2BWasp%26site_url%3Dhttps%253A%252F%252Fdull-wasp.jurassic.ninja%26home_url%3Dhttps%253A%252F%252Fdull-wasp.jurassic.ninja%26site_icon%26site_lang%3Den_US%26site_created%3D2023-06-05%2B07%253A02%253A54%26allow_site_connection%3D1%26locale%3Den%26_ui%3D42367338%26_ut%3Dwpcom%253Auser_id%26calypso_env%3Dproduction%26_as%3Dwp-cli%26from%3Dwoocommerce-onboarding%26purchase_nonce%3Di5V9KqSt%26_wp_nonce%3De48c9f86a6%26redirect_after_auth%3Dhttps%253A%252F%252Fdull-wasp.jurassic.ninja%252Fwp-admin%252Fadmin.php%253Fpage%253Dwc-admin%26site%3Dhttps%253A%252F%252Fdull-wasp.jurassic.ninja&from=woocommerce-core-profiler`
2. Confirm it matches the design (Y5pUYSJPsGEud1vknUZhi8-fi-739_54872)
3. Click on `No, thanks`
4. Should redirect to Jetpack connection screen (/jetpack/connect/authorize)
 

![Screenshot 2023-06-06 at 15 03 05](https://github.com/Automattic/wp-calypso/assets/4344253/8e1af973-1024-495c-b20a-0e8667e8a5a6)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-07 02:35 UTC, ilyasfoo requested changes
Thanks for working on this one, @chihsuan! A few comments on the UI:

1. I think the labels' font size and weight does not match with figma ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/964ef07f-2886-45dd-a9aa-d1c1bbe97e8c))
1. The loading bar and login button color is in a slightly different tinge of blue ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/8e7a85ca-5406-4913-8f5c-1a9764504e49))
1. The login button font-weight should be `500`
2. The social buttons font-weight should be `600`
3. The terms text line-height should be `16px` ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/de3f88c7-e57f-4559-8777-18fefb72f91d))
4. I think we should set a maximum width for these elements or its container. According to Figma, the width is `405px` ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/b617c851-8cf9-41b8-a83b-93292ff5b369))
5. The label for password in Figma is `Your password`

2023-06-07 02:35 UTC, ilyasfoo commented on client/layout/masterbar/woo-core-profiler.tsx
> +									{ translate( 'No Thanks' ) }
Minor diff
```suggestion
									{ translate( 'No, Thanks' ) }
```

2023-06-07 08:16 UTC, chihsuan commented
> Thanks for working on this one, @chihsuan! A few comments on the UI:
> 
> 1. I think the labels' font size and weight does not match with figma ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/964ef07f-2886-45dd-a9aa-d1c1bbe97e8c))
> 2. The loading bar and login button color is in a slightly different tinge of blue ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/8e7a85ca-5406-4913-8f5c-1a9764504e49))
> 3. The login button font-weight should be `500`
> 4. The social buttons font-weight should be `600`
> 5. The terms text line-height should be `16px` ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/de3f88c7-e57f-4559-8777-18fefb72f91d))
> 6. I think we should set a maximum width for these elements or its container. According to Figma, the width is `405px` ([screenshot](https://github.com/Automattic/wp-calypso/assets/3747241/b617c851-8cf9-41b8-a83b-93292ff5b369))
> 7. The label for password in Figma is `Your password`

Thanks for the review! 👍  @ilyasfoo Fixed in fcc95bdd07ee7155dfbe113ee89391579e5fe11f.

2023-06-07 09:00 UTC, ilyasfoo approved these changes
Awesome, thanks for the fix! It looks great now.


One minor comment, I think the woo logo needs a little bit margin since it's too close to the top:

<img width="494" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/e2920384-cc09-4264-9562-2ac7c65f2e4c">

Pre-approving! 🚢

2023-06-07 09:28 UTC, chihsuan commented
> Awesome, thanks for the fix! It looks great now.
> 
> One minor comment, I think the woo logo needs a little bit margin since it's too close to the top:
> 
> <img alt="image" width="494" src="https://user-images.githubusercontent.com/3747241/243990040-e2920384-cc09-4264-9562-2ac7c65f2e4c.png">
> Pre-approving! 🚢

Thanks, fixed it by changing the "display" style to `flex` in a3549acd9ff2bbf88ba8dbc3f866d26f5f638f71.

2023-06-08 13:35 UTC, adrianduffell approved these changes
Thanks @chihsuan , this is looking nice! 🚀

Pre-approving but have a few questions:

* Will the old design still appear in WC <=7.8? From my testing it seems like It would! Those versions send  `from=woocommerce-onboarding` parameter and trigger the old design 👍  

* I was a bit confused by the instruction to "Click on No, thanks". Shouldn't it redirect the user out of the Jetpack flow?

2023-06-09 02:39 UTC, chihsuan commented
> Pre-approving but have a few questions:
> 
> * Will the old design still appear in WC <=7.8? From my testing it seems like It would! Those versions send  `from=woocommerce-onboarding` parameter and trigger the old design 👍

Yes! 🙂 

> * I was a bit confused by the instruction to "Click on No, thanks". Shouldn't it redirect the user out of the Jetpack flow?

The acceptance criteria describe redirecting to the connection page. @moon0326 Could you please confirm this?

2023-06-14 02:32 UTC, chihsuan commented
> I was a bit confused by the instruction to "Click on No, thanks". Shouldn't it redirect the user out of the Jetpack flow?

Changed to redirect the user back to their site in 6932b84fecd310fb619f32efed3c434707b3038e

p1686630076984819-slack-C01SFMVEYAK

2023-06-14 02:43 UTC, merged

2023-06-14 05:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8044820

Thank you @chihsuan for including a screenshot in the description! This is really helpful for our translators.

2023-06-23 10:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8044820).