Launchpad: Added complementary styles to Customer home launchpad
Automattic/wp-calypso pull request #77857
Opened 2023-06-06 20:18 UTC by nelsonec87

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-07 07:53 UTC, valterlorran commented
@nelsonec87 Are we going to hide the "Launch your site" button to match the Figma design?
<img width="1084" alt="Screen Shot 2023-06-07 at 10 53 12" src="https://github.com/Automattic/wp-calypso/assets/1234758/b159c776-8c8b-4ca2-aa94-8804d2683d33">

2023-06-07 17:02 UTC, nelsonec87 commented
> @nelsonec87 Are we going to hide the "Launch your site" button to match the Figma design? <img alt="Screen Shot 2023-06-07 at 10 53 12" width="1084" src="https://user-images.githubusercontent.com/1234758/243968140-b159c776-8c8b-4ca2-aa94-8804d2683d33.png">

@valterlorran , I've changed to the old checklist so we can check the designs. I believe the tasks are gonna be different in the final checklist.

2023-06-07 18:02 UTC, nelsonec87 commented
@valterlorran , it's hardcoded into the Checklist component to make the last task always a primary Button! 
I've opened a separate issue to track it: https://github.com/Automattic/wp-calypso/issues/77912

2023-06-07 18:55 UTC, nelsonec87 commented
> @valterlorran , it's hardcoded into the Checklist component to make the last task always a primary Button! I've opened a separate issue to track it: #77912

PR: https://github.com/Automattic/wp-calypso/pull/77915

2023-06-09 16:07 UTC, andres-blanco requested changes
shouldn't this be rebased to stop showing the primary button?
Also, I am not sure how to view the checklist without nothing checked, since going to /home redirects to the fullscreen launchpad and forces me to publish the site.

2023-06-09 16:43 UTC, nelsonec87 commented
Hi @andres-blanco, I've rebased as you suggested.
About viewing the checklist with all items unchecked, I'm not sure it's currently possible without changing the data manually:

![image](https://github.com/Automattic/wp-calypso/assets/3801502/4ad54b4b-d014-4fbb-900a-633db7d95f86)

But note that it is not the correct checklist yet. Also, the changes of this PR are not visible to users until the backend changes are ready and merged.

2023-06-09 18:04 UTC, andres-blanco approved these changes
The spacing between the last task-item and the bottom of the container looks of, but since it matches with the Figma we can work on it later if necessary.
<img width="1084" alt="image" src="https://github.com/Automattic/wp-calypso/assets/375980/398e716c-fe04-4629-bec7-49192a366613">

2023-06-09 18:22 UTC, merged

2023-06-09 19:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8035322

Thank you @nelsonec87 for including a screenshot in the description! This is really helpful for our translators.

2023-06-15 23:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8035322).