Move paid subscribers feature into the free plan
Automattic/wp-calypso pull request #77919
Opened 2023-06-07 20:09 UTC by jeyip

Related to https://github.com/Automattic/martech/issues/1744

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-07 20:19 UTC, jeyip commented
@lucasmendes-design Does ordering of the Paid subscribers feature in the free plan column matter? I placed it last in the list of Jetpack feature group.

2023-06-08 05:36 UTC, aneeshd16 requested changes
Works well in the pricing grid! However, this feature should also be checked for all plans in the plan comparison grid:
<img width="1328" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/386f02be-0362-46c1-aee1-b8a79400b1fb">

2023-06-08 13:00 UTC, lucasmendes-design commented
> Does ordering of the Paid subscribers feature in the free plan column matter? I placed it last in the list of the Jetpack feature group.

Yes, I think it matters. Thanks for asking @jeyip :) 

Let's make it first. This is very unique, it's difficult to find competitors that offer these earn features for free. So, let's make it first :)

2023-06-08 17:08 UTC, jeyip commented
Fixed in [6127fd9](https://github.com/Automattic/wp-calypso/pull/77919/commits/6127fd9a38356027d0e75eade11f0fa6321b4def) @aneeshd16 

<img width="1330" alt="Screenshot 2023-06-08 at 10 08 12 AM" src="https://github.com/Automattic/wp-calypso/assets/5414230/8e06a65f-0c6b-43ad-8b89-d16921ba0fe1">

2023-06-08 17:11 UTC, jeyip commented
Unrelated to this PR:

I'm seeing a misaligned jetpack logo for the `Add paid subscriptions and gated content` feature in the plans comparison grid
<img width="1279" alt="Screenshot 2023-06-08 at 10 09 29 AM" src="https://github.com/Automattic/wp-calypso/assets/5414230/1c6986b6-af63-4995-8539-41c7be61c421">

~I'll make a separate tracking issue in a bit~

Scratch that! I see that Aneesh already mentioned the icon misalignment here in https://github.com/Automattic/martech/issues/1824

2023-06-08 17:55 UTC, lucasmendes-design commented
We can also split it into two features. 

- Gated content.
- Paid subscriptions

I think it's two different concepts, am I right?

2023-06-08 17:56 UTC, lucasmendes-design commented
What is the difference between paid subscriptions and paid subscribers? I think it's confusing the term here.

2023-06-08 17:59 UTC, lucasmendes-design commented
Sorry, I see now. Why we have the feature "Add paid subscriptions and gated content" 
<img width="199" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/b623e559-18f8-4983-be60-2649bfcd3e28">

And also a different thing on the /pricing page like "Premium content gating"
<img width="268" alt="image" src="https://github.com/Automattic/wp-calypso/assets/98343583/c1927630-daa6-4cfc-9b66-900cce72b354">

2023-06-08 18:44 UTC, jeyip commented
> What is the difference between paid subscriptions and paid subscribers? I think it's confusing the term here.

> Why do we have the feature "Add paid subscriptions and gated content"?

> And also a different thing on the /pricing page like "Premium content gating"

@lucasmendes-design I didn’t add the `Add paid subscriptions and gated content` feature. It existed before my PR, so I’m unsure why it exists in its current state

If you navigate to [wordpress.com/start/plans](http://wordpress.com/start/plans), you can verify that it's been present in production.

I’m happy to make your suggested changes in a **follow-up** PR, but I imagine we’ll want to consult folks that are responsible for Earn features? If you'd like to proceed, I can make a separate tracking issue.

2023-06-08 19:04 UTC, jeyip commented
I chatted with @lucasmendes-design, and we'll address `Add paid subscriptions and gated content` independently from this PR 🙂

2023-06-12 20:55 UTC, jeyip commented
@aneeshd16 

Gentle nudge 🙂 Was there anything else that needed consideration before moving forward with this PR? Lucas's concerns are being addressed in [a separate PR](https://github.com/Automattic/wp-calypso/pull/78020) and [issue](https://github.com/Automattic/martech/issues/1829)

2023-06-13 03:26 UTC, aneeshd16 approved these changes
Thanks for the ping, @jeyip! This PR is good to go. 🚢

2023-06-13 17:49 UTC, jeyip commented
Waiting to ship because of failing pre-release tests p1686677463734059-slack-C02DQP0FP. The VideoPress onboarding flow is currently broken

2023-06-13 18:04 UTC, merged