Add image-cdn and image-guide to Boost features on checkout
Automattic/wp-calypso pull request #77943
Opened 2023-06-08 07:06 UTC by haqadn

Fixes Automattic/boost-cloud#235

## Proposed Changes

* Added "CDN for images" to the list of Boost features on checkout
* Added "Image optimaization guide" to the list of Boost features on checkout

## Testing Instructions
- Go to https://wordpress.com/checkout/jetpack_boost_yearly and https://wordpress.com/checkout/jetpack_boost_monthly and select a site
- Make sure the new lines are present under "Included with your purchase"

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-08 07:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8030669

Thank you @haqadn for including a screenshot in the description! This is really helpful for our translators.

2023-06-08 14:16 UTC, dlind1 commented on client/my-sites/checkout/composite-checkout/lib/get-jetpack-product-features.ts
> +				translate( 'Image optimaization guide' ),
```suggestion
				translate( 'Image optimization guide' ),
```

2023-06-08 14:17 UTC, dlind1 requested changes, later dismissed
Our translators have noticed a typo there 🙂

2023-06-09 14:02 UTC, dilirity approved these changes
With the typo fixed I think it looks good to merge :shipit:

2023-06-15 23:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8030669).

2023-06-16 01:39 UTC, merged