Hide non-atomic jetpack sites from reader-share site list
Automattic/wp-calypso pull request #78014
Opened 2023-06-09 13:38 UTC by Addison-Stavlo

Related to # p1686313489610819/1686239372.646259-slack-C029GN3KD

## Proposed Changes

* It was noticed that jetpack connected self hosted sites do not work with reader share. the underlying problem is more broad, as they are redirected to the jetpack site's wp-admin when attempting to access the editor in general. We will discuss more how to better resolve this in p2, but for now we may want to hide non-atomic jetpack sites from the reader share list.

## Testing Instructions

* apply this calypso branch
* goto the reader and try to share a post
* search for a non-atomic jetpack connected site in the sites list, verify they are not present.
* search for other sites you would expect to see here and verify they are present.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-09 22:25 UTC, creativecoder requested changes
How about using the `getEditorUrl` selector to construct the editor url? That should should fix the issue.

2023-06-12 12:14 UTC, Addison-Stavlo commented
> How about using the getEditorUrl selector to construct the editor url? That should should fix the issue.

Im not sure i follow what the editorUrl is going to do for us here?  Do you mean to hardcode sending them to their wp-admin editor IFF they are jetpack && non-SSO?

I was thinking we hide them for the time being while they are broken, and try to fix whatever is handling the editor redirect for non-SSO sites in general to send to the editor url that is trying to be accessed instead of base wp-admin. That way it resolves the same issues when trying to enter the editor from calypso page/post lists and other areas than just reader sharing. (this would be a follow up)

2023-06-12 15:17 UTC, Addison-Stavlo commented
Quoting myself from above:
> I was thinking if we want to fix this we try to fix the underlying issue...  I was thinking we could dig into this as a follow up

@creativecoder I was thinking roughly something like https://github.com/Automattic/wp-calypso/pull/78068 - although given editor auth is a high-traffic area and there could be a lot going on there im unsure how much that may need to snowball or raise other considerations, but the approach seems safely limited to the individual case currently. If we can get something like that merged in the short-term then id say we can drop this PR, otherwise id say we merge this as is and follow-up on the other as time fits as I don't think this is seen as a high priority issue to spend much time on (at least my understanding from previous discussions with @davemart-in)

2023-06-13 20:43 UTC, creativecoder commented
@Addison-Stavlo Let's do both!

Ideally we won't need to redirect from Gutenframe, when we know it won't work in the first place, since that's just extra time to load the editor, which already tends to take a long time to load. But agreed that we should have that fallback in place, and I've approved the PR.

In order to help avoid getting to a place where we need a redirect, in the first place, I put together https://github.com/Automattic/wp-calypso/pull/78148, which will go directly to the wp-admin url with non-SSO Jetpack sites.

2025-08-26 18:40 UTC, closed without merging