Subscribers Page: Add "Unsubscribe" confirm dialog
Automattic/wp-calypso pull request #78122
Opened 2023-06-13 12:45 UTC by ivan-ottinger

Closes https://github.com/Automattic/wp-calypso/issues/77733
Closes https://github.com/Automattic/wp-calypso/issues/77734

## Proposed Changes

* Create UnsubscribeModal component and useUnsubscribeModal hook
* Apply modal to Subscribers page

## Testing Instructions

* Apply this PR to your local env
* Go to http://calypso.localhost:3000/subscribers/{site-slug}?flags=subscribers-page
* Click the actions menu of a Free Subscriber row and click on Unsubscribe
* Verify if the modal is displayed as expected
* Click on Unsubscribe and verify if the list is updated
* Click the actions menu of a Paid Subscriber row and click on Unsubscribe
* Verify if the modal is displayed as expected
* Click on Manage paid subscribers and check if the earns page is opened on a new tab

<img width="608" alt="Screenshot 2023-06-14 at 17 34 55" src="https://github.com/Automattic/wp-calypso/assets/3113712/fb23582a-6a40-4387-9480-030996c348bc">

<img width="580" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3113712/004b6c2a-d85e-4ec6-964a-94edb543be97">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-15 07:02 UTC, TimBroddin reviewed
For paid subscribers, shouldn't we send them to `https://wordpress.com/earn/payments/<siteid>` directly? There they will have the list of all "Customers and Subscribers".

2023-06-15 07:08 UTC, TimBroddin requested changes
Everything works as advertised, clean code too! 

The only thing we might want to reconsider it the link to the earn page (see comment above).

2023-06-15 13:32 UTC, TimBroddin approved these changes
Approved 🎇

2023-06-15 15:39 UTC, merged

2023-06-15 17:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8048053

Thank you @ivan-ottinger for including a screenshot in the description! This is really helpful for our translators.

2023-06-23 10:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8048053).