Plans 2023: Bound comparison grid title cell text with max width
Automattic/wp-calypso pull request #78143
Opened 2023-06-13 18:46 UTC by jeyip

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-14 04:11 UTC, southp requested changes
It does solve the issue, but I still find it weird that the gaps between the icon and the text are not consistent. Could we also fix that together?
<img width="336" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1842898/c27e7d87-ad4c-4308-ac81-a374a6930c38">

2023-06-17 04:08 UTC, jeyip commented
> It does solve the issue, but I still find it weird that the gaps between the icon and the text are not consistent. Could we also fix that together?

Ah this is a fair point. We totally can. I updated the max-width here [2b2053f](https://github.com/Automattic/wp-calypso/pull/78143/commits/2b2053f765c297e4323e3ad5d315d69ba240a444)

<img width="1081" alt="Screenshot 2023-06-16 at 6 50 44 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/248e7a00-61ee-4771-89a3-8d2062a8ab09">

There's a challenge though. With how text flows, I'm unsure we can guarantee that the Jetpack icon will always be the same distance from text if there's a newline. Below is the same max-width in this PR, but with different content.

<img width="1083" alt="Screenshot 2023-06-16 at 9 04 40 PM" src="https://github.com/Automattic/wp-calypso/assets/5414230/0acfbc79-1e65-433d-9b6f-130779cefc8d">

I don't know if there are alternative ways to approach the problem without a redesign of where the jetpack icon is rendered @southp 🤔 Do you happen to have any thoughts?

2023-06-19 11:08 UTC, southp approved these changes
Ah, thanks for the explanation. I can now see that it requires revisiting on how the text flows. Before we decide on that, this PR does solve the original issue and is a step forward, so let's deploy it and iterate in the near future when needed.

2023-06-19 11:10 UTC, southp commented
I'm deploying this since Jeremy is AFK :)

2023-06-19 11:10 UTC, merged

2023-06-27 17:35 UTC, jeyip commented
Thanks @southp!