add/agency dashboard remove phone number functionality
Automattic/wp-calypso pull request #78427
Opened 2023-06-20 12:57 UTC by TheSteveK

Related to # 1204774821045518-as-1204783884585808/f

## Proposed Changes

* This PR enables the remove SMS number functionality to the agency dashboard downtime notification settings

![Screenshot 2023-06-20 at 8 49 00 AM](https://github.com/Automattic/wp-calypso/assets/12895386/e41c7e1f-cfcf-4586-94e8-b7adb0139ee7)

## Testing Instructions

* Use the jetpack cloud live link below to access the dashboard, or apply this PR locally
* You'll need to be an agency partner to test this
* If not enabled, click the slider to enable SMS notifications, add a contact number if one does not exist
* Click the ... menu to the right of the contact once it's added and select remove
* You should see the modal from the screenshot above.  Click the remove button to remove the number. 
* You will then be taken back to the settings modal which should no longer have that number listed.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-21 04:50 UTC, yashwin requested changes
Works as expected. But I found an issue.

The actions menu and the verification status is not needed to be shown in the remove confirmation modal. 

<img width="473" alt="Screenshot 2023-06-21 at 10 14 42 AM" src="https://github.com/Automattic/wp-calypso/assets/10586875/cb074e10-9bbf-49fc-ba04-e53ddc9fcab9">

2023-06-21 04:50 UTC, yashwin commented on client/jetpack-cloud/sections/agency-dashboard/downtime-monitoring/configure-sms-notification/phone-number-editor.tsx
> +	// Remove email item when user confirms to remove the email address
NITPICK: This should be 

```suggestion
	// Remove phone item when user confirms to remove the phone number
```

2023-06-21 13:30 UTC, yashwin approved these changes
LGTM now 🚀 Thanks for making the suggested changes.

2023-06-21 14:40 UTC, merged

2023-06-21 15:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8059569

Thank you @TheSteveK for including a screenshot in the description! This is really helpful for our translators.

2023-06-30 09:39 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8059569).