Jetpack Pro Dash: Add ability to attach/use WC licenses
Automattic/wp-calypso pull request #78685
Opened 2023-06-27 14:22 UTC by rcoll

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-07-12 13:12 UTC, atanas-dev commented
FYI #78701 seems to refactor some related code (hence the conflicts).

The patch works as advertised, I couldn't get it to break, and it makes sense as part of the flow (I haven't examined the code).

2023-08-02 14:50 UTC, atanas-dev requested changes
I don't see `attachedSiteId` being added anywhere as a GET param in the URL after assigning so I get this:
![Screenshot 2023-08-02 at 17 42 14](https://github.com/Automattic/wp-calypso/assets/22746396/399a96bf-5ead-4061-9570-8ce1f9ba5e10)

Manually changing the URL also produces weird results e.g.:
http://jetpack.cloud.localhost:3000/partner-portal/download-products?products=woocommerce-
This should redirect you or show a 404.

---

Let's style the licenses at least a bit so they look like the ones in the listing section, with a gray code block for the license key, with a copy-to-cliboard button, with a separating border, with a background, etc.
![Screenshot 2023-08-02 at 17 49 56](https://github.com/Automattic/wp-calypso/assets/22746396/24c19717-771a-407d-96a4-2f361510bcd6)

2023-08-02 14:50 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/assign-license-form/index.tsx
> +		);
```suggestion
		const goToDownloadStep = licenseKeysArray.some( isWooCommerceProduct );
```

2023-08-02 14:50 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/assign-license-step-progress/index.tsx
> +	showDownloadStep?: boolean | null;
A nullable boolean is a red flag 😆
We should be able to leave it as a boolean-only and provide a default prop value instead.

2023-08-02 14:50 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
> +				family_slug === 'jetpack-packs' && ! isWooCommerceProduct( family_slug )
Is this check necessary? Jetpack Packs should not contain Woo products

2023-08-02 14:50 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/issue-multiple-licenses-form/index.tsx
> -				family_slug !== 'jetpack-backup-storage' &&
This was deleted in the rebase but it should have been kept.

2023-08-02 14:50 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/primary/assign-license/index.tsx
> +	);
```suggestion
	const showDownloadStep = licenseKeysArray.some( isWooCommerceProduct );
```

2023-08-02 14:50 UTC, atanas-dev commented on client/jetpack-cloud/sections/partner-portal/download-products-form/index.tsx
> +	const attachedSiteId = getQueryArg( window.location.href, 'attachedSiteId' ) as number;
```suggestion
	const attachedSiteId = getQueryArg( window.location.href, 'attachedSiteId' ) as string;
```

2023-08-02 17:07 UTC, heydemoura commented
> 
> Let's style the licenses at least a bit so they look like the ones in the listing section, with a gray code block for the license key, with a copy-to-cliboard button, with a separating border, with a background, etc. ![Screenshot 2023-08-02 at 17 49 56](https://user-images.githubusercontent.com/22746396/257852255-24c19717-771a-407d-96a4-2f361510bcd6.png) (we can skip all actions other than download)

I have updated the looks, to a simple but more organized set of components. Since at this point there's no need to copy the license to the clipboard as the licenses are already assigned. And is a temporary design, since we don't yet have definition from the design team about this.

![image](https://github.com/Automattic/wp-calypso/assets/5550190/8fcb1b31-a761-495a-b5c3-56ad3f0d2118)

2023-08-03 15:50 UTC, atanas-dev requested changes
![Screenshot 2023-08-03 at 18 49 16](https://github.com/Automattic/wp-calypso/assets/22746396/57cfd6ad-798c-4320-8cf2-ca63cfdc2fc3)
😁

Apart from that the rest looks good but the copy-to-clipboard button is important to add IMO.

EDIT: The Download button seems to be missing its busy animation now.

2023-08-03 16:07 UTC, heydemoura commented
> ![Screenshot 2023-08-03 at 18 49 16](https://user-images.githubusercontent.com/22746396/258166654-57cfd6ad-798c-4320-8cf2-ca63cfdc2fc3.png) 😁

Fixed the site url not rendering:
![image](https://github.com/Automattic/wp-calypso/assets/5550190/eac12521-0a63-41d4-b284-22ffc34f8831)

2023-08-03 16:13 UTC, heydemoura commented
> EDIT: The Download button seems to be missing its busy animation now.

Added a disabled stated while downloading. The `ActionCard` component on Calypso Components doesn't have a loading state prop, according to [the docs](https://wpcalypso.wordpress.com/devdocs/design/action-card)

![image](https://github.com/Automattic/wp-calypso/assets/5550190/869f4fd8-e98c-4f72-ae6f-18ee78a11e85)

2023-08-03 16:28 UTC, heydemoura commented
Added copy-to-clipboard button to downloads screen

![image](https://github.com/Automattic/wp-calypso/assets/5550190/30470579-481d-4a15-a4fe-6f44f404050b)

2023-08-03 16:52 UTC, atanas-dev approved these changes
🚢

2023-08-03 17:30 UTC, merged

2023-08-03 19:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8681321

Hi @rcoll, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Download product`
- `Your license has been applied to {{strong}}%(siteUrl)s{{/strong}}, but more action is required.`
- `No more action is required for these products:`
- `These extensions need to be downloaded and installed:`
- `Download and Install your product`
- `Download and install your product`

Thank you in advance!

2023-08-13 17:36 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8681321).