Subscriber Details: Display subscriber data on details page
Automattic/wp-calypso pull request #78714
Opened 2023-06-27 22:56 UTC by phcp

Closes https://github.com/Automattic/wp-calypso/issues/78366

## Proposed Changes

* Add country and url to Subscriber model
* Update useSubscriptionPlans output
* Add loading state
* Display subscriber data on details page

## Testing Instructions

* Apply this PR to your local
* Go to http://calypso.localhost:3000/subscribers/{site-slug}?flags=subscribers/view-subscriber-details
* Click on View on an external subscriber
* The subscriber information should be displayed
* Go back and click on View on an free wpcom subscriber
* The subscriber information should be displayed
* Go back and click on View on an paid wpcom subscriber
* The subscriber information should be displayed (with the plans stacked)
* Test the Subscriber List for regressions

<img width="1075" alt="Screenshot 2023-06-27 at 19 51 33" src="https://github.com/Automattic/wp-calypso/assets/3113712/99e0a549-9724-4c57-b999-5905b470e23b">

<img width="1080" alt="Screenshot 2023-06-27 at 19 43 11" src="https://github.com/Automattic/wp-calypso/assets/3113712/9e8d5838-4c9f-40dc-9c9a-43a9630037a6">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-28 07:29 UTC, TimBroddin commented
For external users I see "undefined: Free" as a plan:

<img width="1156" alt="CleanShot 2023-06-28 at 09 28 15@2x" src="https://github.com/Automattic/wp-calypso/assets/528287/cf2b51c2-7504-41ab-94cf-e593d9214a5d">

2023-06-28 07:32 UTC, TimBroddin requested changes
Looks good! I left a comment about the plan name being undefined on free plans. 

Also, I get France as a country for myself, but I guess that's due to the proxy.

2023-06-29 06:33 UTC, TimBroddin approved these changes
👍 Nice PR!

2023-06-29 07:19 UTC, merged

2023-06-29 09:20 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8069868

Thank you @phcp for including a screenshot in the description! This is really helpful for our translators.

2023-07-07 10:33 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8069868).