GS on Personal A/B: Privacy Settings  Implement A/B testing for Global Styles in Personal Plans
Automattic/wp-calypso pull request #78830
Opened 2023-06-30 09:00 UTC by rcrdortiz

Related to https://github.com/Automattic/dotcom-forge/issues/2866

## Proposed Changes

This pull request implements an A/B test to evaluate the effects of introducing global styles in Personal plans. Previously, global styles were only available to Premium plans. The notice users see now dynamically changes based on the experiment they are part of, which means users in the treatment group will see a message indicating they have access to Global Styles on their Personal plan.

| Before | After |
--------|-------
![image](https://github.com/Automattic/dotcom-forge/assets/1233880/4cf59bc4-66c5-4327-a7f5-ceb86e9838dc)|![Captura de Pantalla 2023-07-04 a las 10 15 10](https://github.com/Automattic/wp-calypso/assets/1989914/a8c2a134-a7d4-43f2-85c1-58259d3cdfbd)

## Testing Instructions

Testing Instructions:

* Open the Calypso live link
* Add some global styles to your **free** site, and launch it
* Navigate to Site Settings in the Calypso dashboard `/settings/general/{site}`
* Check the "Advanced Customization Notice" section
* For the users in the control group, the text should still indicate "Your site contains customized styles that will only be visible once you upgrade to a Premium plan."
* For the users in the treatment group, the text should be changed to "Your site contains customized styles that will only be visible once you upgrade to a Personal plan."
* Verify that the message displayed corresponds to the assigned group of the current user (control or treatment) in the `calypso_global_styles_personal` experiment.
* Ensure no other part of the site settings is affected by this change.

You can change your group here (21268-explat-experiment), you also need to clear the cache when switching between groups by executing this command in your sandbox:
`wp_cache_delete( 'global-styles-on-personal-{siteId}', 'a8c_experiments' );` 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-06-30 09:18 UTC, dsas requested changes
You'll also need to change the `upgradeUrl` on the Upgrade button,

2023-06-30 12:58 UTC, rcrdortiz commented on client/my-sites/site-settings/form-general.jsx
> +				link: localizeUrl( 'https://wordpress.com/support/user-roles/' ),
Linter made me do this for reasons.

2023-06-30 12:58 UTC, rcrdortiz commented
> You'll also need to change the `upgradeUrl` on the Upgrade button,

Nice catch, there ya go!

2023-07-03 14:04 UTC, mmtr commented
> ON HOLD, WAITING FOR AB INTERFACE CHANGES

They are ready now! https://github.com/Automattic/wp-calypso/pull/78895

2023-07-03 14:08 UTC, mmtr commented on client/my-sites/site-settings/form-general.jsx
> +						) }
Can this be simplified like this?

```suggestion
						<span>
							{ globalStylesOnPersonalExperiment
								? translate(
										'Your site contains customized styles that will only be visible once you upgrade to a Personal plan.'
								  )
								: translate(
										'Your site contains customized styles that will only be visible once you upgrade to a Premium plan.'
								  ) }
						</span>
						) }
```

2023-07-04 08:08 UTC, rcrdortiz commented on client/my-sites/site-settings/form-general.jsx
> +						) }
Sure

2023-07-04 09:39 UTC, dsas approved these changes
LGTM. Given this PR links to the plans grid, _maybe_ we should hold off on deploying it until the plans grid changes in #78634 are deployed. I'll go and review that next.

2023-07-04 09:52 UTC, rcrdortiz commented
> LGTM. Given this PR links to the plans grid, _maybe_ we should hold off on deploying it until the plans grid changes in #78634 are deployed. I'll go and review that next.

Since until we don't turn on the experiment we won't be showing the new copies to our users we can just ship this regardless of the plan grid.

2023-07-04 09:57 UTC, merged