Domains/add empty state to all domains
Automattic/wp-calypso pull request #78841
Opened 2023-06-30 10:41 UTC by zaguiini

Closes https://github.com/Automattic/dotcom-forge/issues/2869.

## Proposed Changes

Let's add an empty state component to `/domains/manage` when 'All domains' is selected and the user still has no www's.

![image](https://github.com/Automattic/wp-calypso/assets/26530524/22911101-9188-4295-9b2e-e7c0bf2a9c4a)

## Testing Instructions

1. Create an account and two free sites;
2. Browse `/domains/manage`.

You should see the empty state and the CTAs pointing to:
- `/start/domain`;
- `/domains/add`.

2023-06-30 11:44 UTC, nuriapenya requested changes
The empty state was correctly implemented 👍🏽 but the "Add a domain" CTA currently links to the onboarding stepper `/start/domain/domain-only`. I believe it should stay in Calypso and use the `/domains/add` path, so users can return to the empty state if necessary when clicking "Back".

(cc: @saygunnyc for a double check here)

<img width="1439" alt="Screenshot 2023-06-30 at 13 40 50" src="https://github.com/Automattic/wp-calypso/assets/7931304/bb57f756-8298-4be2-a089-8bab687180bc">


Could we also remove the "+" icon from the CTA? As we are not displaying the dropdown anymore.

2023-06-30 11:46 UTC, zaguiini commented
Thanks @nuriapenya

If the "Add a domain" CTA should point to `/domains/add`, what should "Transfer a domain" do?

2023-06-30 12:14 UTC, saygunnyc commented
> what should "Transfer a domain" do?

Link to the current transfer flow, for now, you can see it by clicking on the card below on Domains LP.  I believe there's a Calpyso version of this too. However, we should link to the new bulk domain transfer flow once launched. cc @alshakero 


<img width="1830" alt="Screenshot 2023-06-29 at 10 04 27 AM" src="https://github.com/Automattic/wp-calypso/assets/78876323/a2137477-91fa-4997-bf6c-7f06b67d14e2">

2023-06-30 13:03 UTC, zaguiini commented
Thanks @nuriapenya @saygunnyc this should be good to go now.

2023-06-30 14:22 UTC, nuriapenya approved these changes
Tested 👌🏽 everything looks good!

2023-06-30 14:23 UTC, merged

2023-06-30 16:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8072294

Thank you @zaguiini for including a screenshot in the description! This is really helpful for our translators.

2023-07-07 10:33 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8072294).