/read/subscriptions/: Implement custom site subscriptions list "not found" state component, and hide RecommendedSites component on search
Automattic/wp-calypso pull request #78929
Opened 2023-07-04 09:36 UTC by mashikag

![nVmevo.png](https://github.com/Automattic/wp-calypso/assets/2019970/3cdd0262-fe02-41f8-b7de-d8aa13810c16)

![jCKXOy.png](https://github.com/Automattic/wp-calypso/assets/2019970/aab3f68e-3b47-4360-9520-c226381f58d0)

![lqF0Lm.png](https://github.com/Automattic/wp-calypso/assets/2019970/747ddf59-dddd-4b85-8140-e2884dde46b9)

![IhOhRx.png](https://github.com/Automattic/wp-calypso/assets/2019970/5b2ce0e1-a108-4b47-8ea4-a6a2e575be74)

Fixes https://github.com/Automattic/wp-calypso/issues/78631

## Proposed Changes

* Add custom `NotFoundSiteSubscriptions` component in Reader, as per the Figma design: inDLaEQV8jJ21O4WXawIsJ-fi-3751_61105
* Hide the "Recommended sites" component when a search text is entered

## Testing Instructions

1. Go to http://calypso.localhost:3000/read/subscriptions
2. Enter some search string
3. Ensure the "Recommended sites" component is not displayed, once the search text is entered
4. Remove the search text
5. Ensure the Recommended sites are displayed once again
6. Enter a search string that does not match any of your site subscriptions, and ensure the expected text is displayed

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-07-04 13:42 UTC, phcp requested changes

2023-07-04 13:42 UTC, phcp commented on client/reader/site-subscriptions-manager/not-found-site-subscriptions.tsx
> +					'No results found for “%s” in your subscribed sites. Below are some recommended sites for you.',
"Below are some recommended sites for you." I think this part of the sentence should be removed when searching, as there is no recommendations in this case.

2023-07-04 13:42 UTC, phcp commented on client/reader/site-subscriptions-manager/not-found-site-subscriptions.tsx
> +					'No results found for “%s” in your subscribed sites. Below are some recommended sites for you.',
The empty view for filters is missing the filter type on the message.

<img width="801" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3113712/9b9de09c-fb0e-4641-949c-850d7fd3e1b4">

2023-07-04 15:05 UTC, phcp approved these changes
Approved as the fixes are intended to be on follow-up PRs. p1688482935153459/1688463459.066459-slack-C02TCEHP3HA

2023-07-04 16:56 UTC, merged

2023-07-04 18:20 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8350824

Thank you @mashikag for including a screenshot in the description! This is really helpful for our translators.

2023-07-12 14:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8350824).