Don't show refund policy and international fee notice in Jetpack cart
Automattic/wp-calypso pull request #79020
Opened 2023-07-05 16:20 UTC by jboland88

## Proposed Changes

* This diff removes the refund policy notice and international fee notice from the Jetpack and Akismet carts since these can be communicated more effectively elsewhere. 

## Testing Instructions

* With this PR applied, test the following checkouts
* http://calypso.localhost:3000/checkout/jetpack/jetpack_backup_t1_yearly
* http://calypso.localhost:3000/checkout/akismet/ak_plus_yearly_1
* Confirm that you no longer see the refund notice or the international fee included in the cart terms

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-07-06 18:22 UTC, CodeyGuyDylan requested changes
I noticed that a checkout with a Jetpack product but not siteless still shows the terms we are hiding here. Do we want to hide it in any cart that has a jetpack product?
![image](https://github.com/Automattic/wp-calypso/assets/65001528/b0a21aa3-7119-440a-88bf-d815b4451b7a)

2023-07-06 19:21 UTC, sirbrillig commented
> can be communicated more effectively elsewhere

Just curious: where are those going to be communicated?

2023-07-06 19:53 UTC, jboland88 commented
Thanks for the feedback @CodeyGuyDylan - I've added an update that should also account for site-based Jetpack checkouts

> Just curious: where are those going to be communicated?
@sirbrillig - great question
- For the 14-day refund period, we show this in two other places in the Jetpack checkout - both below the purchase button and in the right-hand sidebar. This is the "14-day money back guarantee"
- For the foreign transaction fee item, Here's a bit more context: pbNhbs-6Sw-p2#comment-16291. I don't think we have this copy elsewhere at the moment - perhaps it would be something that would be good to show when a new payment method is added? Thoughts?

2023-07-06 19:58 UTC, sirbrillig commented
> For the foreign transaction fee item, Here's a bit more context: pbNhbs-6Sw-p2#comment-16291. I don't think we have this copy elsewhere at the moment - perhaps it would be something that would be good to show when a new payment method is added? Thoughts?

That's fine. It was added because for some currencies (specifically using BRL with Stripe which happens only when the billing address is outside of Brazil), there's a possibility that what is displayed in checkout will actually be less than what you are charged due to currency conversions. But since it sounds like there's no legal requirement for that and we've documented the decision, I don't have an objections to removing it here.

2023-07-07 02:45 UTC, IanRamosC approved these changes
Code looks good. The functionality works as described in the test plan and in the comments.

2023-07-07 13:48 UTC, merged