Bulk Domain Transfer: Improve analytics
Automattic/wp-calypso pull request #79184
Opened 2023-07-10 13:37 UTC by escapemanuele

[Context](https://github.com/Automattic/dotcom-forge/issues/2970#issuecomment-1625757857)

## Changes

- Tracked ( `calypso_domain_transfer_complete_click` ) the user destination after landing on the complete page
- Tracked ( `calypso_domain_transfer_submit_form` ) when the user clicks on `Transfer X domains`, with `valid` and `numberOfValidDomains` as parameters

2023-07-10 15:19 UTC, allilevine commented
Thanks @escapemanuele, these events look great! The only other event I can think of to track where a user might get stuck or drop off is one for errors on /setup/domain-transfer/domains we show before the click on `Transfer x domains`, like this:
<img width="783" alt="Screen Shot 2023-07-10 at 11 18 24 AM" src="https://github.com/Automattic/wp-calypso/assets/1689238/3219103c-f5ec-45e4-a4de-048bd2ce8258">

Is it possible to trigger an event when the error is shown, with the actual error as a prop?

2023-07-10 15:40 UTC, escapemanuele commented
Thanks @allilevine, I added the `calypso_domain_transfer_domain_error` event!

2023-07-11 08:30 UTC, alshakero requested changes
Great! One small issue.

2023-07-11 08:30 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +		}
`shouldReportError` doesn't really imply there is an error, it means if there is one, we'd show it to the user. I added it to hide validation errors when domains are empty. 
```suggestion
		if ( shouldReportError && ! valid && message ) {
			recordTracksEvent( 'calypso_domain_transfer_domain_error', {
				domain,
				message,
			} );
		}
```

2023-07-11 09:41 UTC, alshakero approved these changes
Beautiful ✨

2023-07-11 10:11 UTC, merged