Bulk Domain Transfer: Improve domain form
Automattic/wp-calypso pull request #79300
Opened 2023-07-12 13:38 UTC by escapemanuele

## Changes

- Column for price
- Fixed authorization code error message

2023-07-13 15:26 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +	if ( ! saleCost && saleCost !== 0 ) {
```suggestion
	if ( saleCost === 0 ) {
```

2023-07-13 15:26 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +		return <div className="domains__domain-price-number disabled">$0</div>;
We should probably call `formatCurrency` on the zero.

2023-07-13 15:59 UTC, escapemanuele commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +	if ( ! saleCost && saleCost !== 0 ) {
I thought about this, but what about sales that are not zero but half the price? 🤔

2023-07-13 16:05 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +	if ( ! saleCost && saleCost !== 0 ) {
You're right. Bad suggestion.

2023-07-13 16:40 UTC, alshakero requested changes
Amazing work. This has been much harder than it seems. Left some comments.

2023-07-13 16:40 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domains.tsx
> +	}, 0 );
This probably should be a function outside the component, takes the state and gives a formatted price with a correct currency. I.e shouldn't be locked to USD.

2023-07-13 16:40 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +				{ formatCurrency( 0, currencyCode, { stripZeros: true } ) }
I just realized that we don't need currency for the zero, `0` is enough, but not `$0`.

2023-07-13 16:40 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domains.tsx
> +			currencyCode: 'USD',
Should be `undefined`.

2023-07-13 16:40 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domains.tsx
> +				<div>{ formatCurrency( totalPrice, 'USD', { stripZeros: true } ) }</div>
Should be covered by the function I mention above.

2023-07-13 16:52 UTC, escapemanuele commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +				{ formatCurrency( 0, currencyCode, { stripZeros: true } ) }
Ok! Do you mean just having
`<div className="domains__domain-price-number disabled">0</div>`
right?

2023-07-13 17:05 UTC, escapemanuele commented
Thank you @alshakero, I think I addressed all your feedback!

2023-07-13 18:02 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/domain-transfer-domains/domain-code-pair.tsx
> +				{ formatCurrency( 0, currencyCode, { stripZeros: true } ) }
Yes!

2023-07-13 18:21 UTC, alshakero approved these changes
Pushed some changes and it looks great now!

2023-07-13 18:21 UTC, alshakero approved these changes
Pushed some changes and it looks great now!

2023-07-13 18:56 UTC, merged

2023-07-13 19:20 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8549986

Hi @escapemanuele, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Unique code proving ownership, needed for secure domain transfer between registrars.`
- `Add your domains`
- `Next, add your domain name and authorization code below. Add as little or as many domains as you want.`

Thank you in advance!

2023-07-13 19:26 UTC, cometgrrl commented
Minor copy feedback:
“Add as little or as many”
I think “few” goes with “many” (silly, but English is :weird: like that)
Text wrapping is not great. Maybe putting the second sentence on a new line?
<img width="878" alt="SCR-20230713-kvbk" src="https://github.com/Automattic/wp-calypso/assets/86427589/99091aef-a571-404a-97ed-1d025cb656d7">

2023-07-13 19:26 UTC, cometgrrl commented
From the checkout screen, the back button used to go to /setup/domain-transfer/domains, and now it goes to /start/domains, which seems wrong.

2023-07-13 22:03 UTC, john-legg commented
This is great work! While I was testing, I noticed that the width of the Price column is a bit wide. The link to the designs doesn't seem to work for me, so I don't know if this is intentional or not, but I just wanted to point it out. It's more noticeable when there's multiple domain rows.

<img width="833" alt="Screenshot 2023-07-13 at 5 59 34 PM" src="https://github.com/Automattic/wp-calypso/assets/96805492/b88e3274-8914-4f52-a7a3-8a032b1e0297">

2023-07-14 09:33 UTC, escapemanuele commented
Hey @john-legg, thanks for the feedback. I gave the price column some space to accomodate for this:

![image](https://github.com/Automattic/wp-calypso/assets/52076348/6c6b9d0a-70d0-4d70-b7ff-6c89468cd463)

The `First year free` is taking some space.
This is from the designs:

![image](https://github.com/Automattic/wp-calypso/assets/52076348/92be4988-6aa5-4373-8a59-ee1eded263cc)

2023-07-14 12:03 UTC, karenroldan commented
Hi, @escapemanuele! 

**issue (ux,non-blocking):** There is a dollar sign on the price per domain based on Figma. But, right now, it only shows `0` 
![Ha4o4U.png](https://github.com/Automattic/wp-calypso/assets/67279475/98da7975-1939-4df7-84e0-53bbd44f018e)

2023-07-14 13:37 UTC, escapemanuele commented
Thank you @karenroldan, we'll try to address this!

2023-07-20 19:41 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8549986).