New hosted site: prevent anonymous browsing
Automattic/wp-calypso pull request #79578
Opened 2023-07-18 21:59 UTC by zaguiini

Closes https://github.com/Automattic/dotcom-forge/issues/3056.

## Proposed Changes

This PR gates `/setup/new-hosted-site` for logged in accounts. The original idea was to allow incognito browsing until the site creation step, but this was complicated to achieve due to the flow variation (hosting flow or not) and also I don't really see a lot of value in anonymous browsing since the user needs to sign in anyway, so let's just redirect first, keeping things simple.

Another good reason to sign in first is to maintain funnel compatibility. If we add the sign in step after plans, we'll need to create at least two funnels to account for this permutation, and that's a no-no for me.

Finally, there is no direct link to this flow as we want the user to decide whether they want to create a site from scratch or import one, so it makes more sense to send them to sign up first. I am thinking of dropping the `redirect_to` so that they always get redirected to `/sites`, seeing the forking step and then deciding. It feels like a better solution to me, but I'm not yet convinced because the user browsed `/setup/new-hosted-site` directly, so they're probably not interesting in importing a site.

Additionally, I perform a light clean up that might be out of scope of this PR, but no strong feelings in reverting them if you feel that's too unrelated to this PRs proposed changes.

## Testing Instructions

Browse `/setup/new-hosted-site` in incognito mode, and verify that you're redirected to `/start/hosting/user-hosting?redirect_to=/setup/new-hosted-site/plans`. Log in and you should be redirected to the `plans`.

Browse `/setup/new-hosted-site?hosting-flow=true` in incognito mode, and verify that you're redirected to `/start/hosting/user-hosting?redirect_to=/setup/new-hosted-site/options%3Fhosting-flow%3Dtrue`. Log in and you should be redirected to the `siteOptionsStep`.

2023-07-18 23:59 UTC, p-jackson commented on client/signup/config/flows.js
> +		getQueryArgs().redirect_to ??
We recently had issues reported with `redirect_to` params not being validated propertly. Read more at p7H4VZ-4sH-p2.

We have a `/me/validate-redirect` endpoint which can authoritatively confirm whether a redirect is safe. However introducing an async network call here would be problematic. We could also use a regex like #79189 to confirm the redirect is going to the `new-hosted-site` flow.

Another, perhaps even more straightforward solution, would be not to have a generic `?redirect_to` param, but a `?redirect_to_new_hosted_site_flow` query param that always redirects to the well known `/setup/new-hosted-flow` URL.

2023-07-19 00:44 UTC, p-jackson requested changes
I think you're totally right that we should just redirect folks to the start of the flow rather than have a special flow for people who somehow find themselves on the `/setup/new-hosted-flow` page while logged out.

Peronally I would go further and just let them go to the forking step after they sign up. I don't think we want special permutations of the flow that don't get tested very often.

Marking as "request changes" because I do think we need to address the issue I raised about the redirect query param.

2023-07-19 00:44 UTC, p-jackson commented on client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
> +	useAssertConditions(): AssertConditionResult {
I feel like the `useSideEffect` hook would be more appropriate than `useAssertConditions`. The assert conditions hook is all about returning an error, but that's really only a secondary concern to us. The primary thing we're trying to do is run a side-effect (call `window.location.assign()`) on certain conditions. So it feels like adding another `useEffect()` to `useSideEffect()` would make more sense.

2023-07-19 00:44 UTC, p-jackson commented on client/signup/config/flows.js
> +		getQueryArgs().redirect_to ??
Or maybe not redirecting at all like you suggest in your PR description and just going to the forking step?

2023-07-19 00:44 UTC, p-jackson commented on client/landing/stepper/declarative-flow/new-hosted-site-flow.ts
> +					: `/start/hosting?redirect_to=${ redirectTarget }`;
I've tested this locale stuff and I'm not sure it's actually necessary. If the user is logged out then `locale` will either be `null` or some inferred value from IP or browser settings. The `/start/hosting` page is just as capable of inferring the locale as the stepper page.

I tested this by logging out and setting my browser to French. I was redirected to `/start/hosting` (without the `/fr`) but was still shown a french login screen as expected.

2023-07-19 20:37 UTC, zaguiini commented
Alright @p-jackson, this should be good to go now! Thanks for the suggestions ✨

2023-07-21 02:49 UTC, p-jackson approved these changes

2023-07-21 02:51 UTC, merged