Fix link-in-bio styles.
Automattic/wp-calypso pull request #79756
Opened 2023-07-21 17:55 UTC by allilevine

Issue raised here: p1689919397847559-slack-C9EJ7KSGH

## Proposed Changes

* Add the `link-in-bio` class to this giant list of style corrections. If these are needed for every flow, we should make them less specific.

## Testing Instructions

* Go to /setup/link-in-bio/intro

Before | After

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-07-21 18:25 UTC, allilevine commented on client/landing/stepper/declarative-flow/internals/global.scss
> +.link-in-bio,
Adding this to cover /setup/link-in-bio/linkInBioSetup

2023-07-21 18:26 UTC, allilevine commented on client/landing/stepper/declarative-flow/internals/steps-repository/components/setup-form/style.scss
> +	.expanding-area textarea {
/setup/link-in-bio/linkInBioSetup has a specific `.expanding-area` textarea class that gets overwritten by another font family. I don't see it testing locally, but I see it on calypso.live.

2023-07-24 03:56 UTC, lsl commented
This looks fixed in prod. Maybe someone else picked it up?

2023-07-24 14:06 UTC, allilevine commented
> This looks fixed in prod. Maybe someone else picked it up?

I'm not seeing the fix on prod or staging. 🤔 I'm testing in Firefox and Chrome.

2023-07-25 04:56 UTC, lsl commented
The first step is fine, the second one is not :facepalm:

2023-07-25 06:13 UTC, nuriapenya requested changes
The broken alignment seems to be fixed, but I still see issues with the styles of the buttons. In both Intro and Setup pages, the primary CTA still has the wrong values:

Perhaps this is more related to: https://github.com/Automattic/dotcom-forge/issues/3163

<img width="1439" alt="Screenshot 2023-07-25 at 08 10 33" src="https://github.com/Automattic/wp-calypso/assets/7931304/f9b44208-7fd7-4716-bdcd-67916dd76df7">
<img width="1434" alt="Screenshot 2023-07-25 at 08 10 42" src="https://github.com/Automattic/wp-calypso/assets/7931304/07b07bdf-6384-4b38-9913-e12c8d29a05f">

2023-07-25 06:25 UTC, nuriapenya commented
Another thing I spot on the Launchpad screen in the testing link, is that the Header logo is repeated. Not happening in production. 

<img width="1437" alt="Screenshot 2023-07-25 at 08 23 56" src="https://github.com/Automattic/wp-calypso/assets/7931304/107aaecb-cbf2-419f-89ac-469277869247">

2023-07-25 06:54 UTC, lsl commented
> Another thing I spot on the Launchpad screen in the testing link, is that the Header logo is repeated. Not happening in production.

Are we loading the header twice and hiding one? (I think I've seen this before somewhere, sorry couldn't find a link)

> but I still see issues with the styles of the buttons. 

This should be fixed by https://github.com/Automattic/wp-calypso/pull/79708.

2023-07-25 06:58 UTC, lsl approved these changes
LGTM

2023-07-25 12:26 UTC, paulopmt1 commented
> is that the Header logo is repeated. Not happening in production.

I was also seeing that in both dev and staging. Fixed [with this commit](https://github.com/Automattic/wp-calypso/pull/79756/commits/d3c7e6fe2073a7c43c86d099548b620603dcb8ab).

2023-07-25 12:30 UTC, paulopmt1 approved these changes
Nice work @allilevine, it's working as expected!

2023-07-25 14:19 UTC, merged

2023-07-25 15:24 UTC, allilevine commented
Thank you! 🙌 Looks like everything except the button color has been resolved in production.

2023-07-25 16:48 UTC, paulopmt1 commented
> Thank you! 🙌 Looks like everything except the button color has been resolved in production.

I'll monitor https://github.com/Automattic/wp-calypso/pull/79708 and if it does not solve it, will create a fix for that.