Update styles for pricing page nav
Automattic/wp-calypso pull request #79974
Opened 2023-07-28 14:30 UTC by jboland88

## Proposed Changes

* This diff updates the nav on the Jetpack pricing page to match some changes on the main Jetpack.com

## Testing Instructions

* Apply this patch, make sure the nav matches D117317-code (see linked design)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-07-28 16:20 UTC, CodeyGuyDylan requested changes
It looks like the gap between the top nav and the megamenu is larger on this diff than on the jetpack.com one
![image](https://github.com/Automattic/wp-calypso/assets/65001528/769d5752-2914-45e3-bad3-b35c1bc4166a)
![image](https://github.com/Automattic/wp-calypso/assets/65001528/235f5f7f-e658-4ac8-be4f-f7eb22c97a7d)

2023-07-28 16:22 UTC, CodeyGuyDylan reviewed
Oh and is it just me, or do the titles on the Calypso one seem slightly less bold than the ones on jetpack.com?
![image](https://github.com/Automattic/wp-calypso/assets/65001528/8b386565-1cad-4979-83cf-333cf6474253)
![image](https://github.com/Automattic/wp-calypso/assets/65001528/23f9ad8c-3ea3-4234-8b4d-bc73656075eb)

2023-07-31 13:38 UTC, jboland88 commented
> It looks like the gap between the top nav and the megamenu is larger on this diff than on the jetpack.com one

@CodeyGuyDylan - good catch, got that fixed.
I noticed there is a bit of spacing difference on the bottom as well, but that needs to be updated on the Jetpack.com side.

I can see the bold difference in your screenshots, but was not able to reproduce on my end. What browser are you using?

2023-07-31 14:34 UTC, CodeyGuyDylan commented
> What browser are you using?

I am using Chrome

2023-07-31 20:59 UTC, IanRamosC approved these changes
It works as expected!

>I can see the bold difference in your screenshots, but was not able to reproduce on my end. What browser are you using?

I can also reproduce it here. It seems like there's `-webkit-font-smoothing: antialiased;` [in Calypso for screens with more than 120dpi](https://github.com/Automattic/wp-calypso/blob/trunk/client/assets/stylesheets/_main.scss#L63), which makes the text less blurry.

2023-08-01 14:51 UTC, merged

2023-08-01 15:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8677191

Hi @jboland88, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Write once, reach all`

Thank you in advance!

2023-08-13 17:35 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8677191).