Assembler: Copy updates Aug 1
Automattic/wp-calypso pull request #80271
Opened 2023-08-07 08:06 UTC by miksansegundo

Closes https://github.com/Automattic/wp-calypso/issues/80118

## Proposed Changes

- Update CTA subtitle copy in large breakpoint
- Update header title and description copy on main screen
- Update description copy on 
  - Header screen **using a shorter version to avoid an orphan**
  - Sections screen **using a shorter version to avoid an orphan**
  - Footer screen
  - Colors screen

### Update CTA subtitle copy in large breakpoint

|BEFORE >= 960px|AFTER >= 960px |AFTER < 960px (No changes)|
|--|--|--|
|<img width="1710" alt="Screenshot 2566-08-07 at 14 37 09" src="https://github.com/Automattic/wp-calypso/assets/1881481/a47f0751-a6de-4737-8c73-a00955e8abd4">|<img width="1684" alt="Screenshot 2566-08-07 at 13 22 42" src="https://github.com/Automattic/wp-calypso/assets/1881481/b5c1e193-7403-4cca-a119-2418a62a5a16">|<img width="909" alt="Screenshot 2566-08-07 at 13 23 23" src="https://github.com/Automattic/wp-calypso/assets/1881481/0acb2486-7099-48ec-b4a4-b1d986c6acf0">|

### Update header title and description copy on the main screen

|BEFORE|AFTER >= 1280px |AFTER < 1280px|
|--|--|--|
|<img width="297" alt="Screenshot 2566-08-07 at 14 33 29" src="https://github.com/Automattic/wp-calypso/assets/1881481/0d8c8e9a-c95d-48d0-bbe4-10882d6bfe59">|<img width="339" alt="Screenshot 2566-08-07 at 13 42 23" src="https://github.com/Automattic/wp-calypso/assets/1881481/a4eba36b-154f-4f27-baf0-937e991379a2">|<img width="301" alt="Screenshot 2566-08-07 at 13 42 05" src="https://github.com/Automattic/wp-calypso/assets/1881481/267abb8b-1eb8-4881-b698-9c6964aed3c5">|

### Update description copy on Header screen

|BEFORE|AFTER >= 1280px |AFTER < 1280px|
|--|--|--|
|<img width="322" alt="Screenshot 2566-08-07 at 14 39 34" src="https://github.com/Automattic/wp-calypso/assets/1881481/d5ff551a-3ea9-4bbb-b4f9-e60659239ab1">|<img width="342" alt="Screenshot 2566-08-07 at 14 42 31" src="https://github.com/Automattic/wp-calypso/assets/1881481/cb02cb11-a231-43e5-8083-57ef816bcfde">|<img width="278" alt="Screenshot 2566-08-07 at 14 43 13" src="https://github.com/Automattic/wp-calypso/assets/1881481/4560d08d-9a20-4244-9db7-069cdea95070">|

Note that the words "of the homepage" are being replaced from the new copy with "area" to avoid the following orphan word. cc: @lucasmendes-design @autumnfjeld

<img width="341" alt="Screenshot 2566-08-07 at 13 48 05" src="https://github.com/Automattic/wp-calypso/assets/1881481/ca825cf8-e24b-4c53-aa6b-71de9b4778f5">

### Update description copy on Sections screen

|BEFORE|AFTER >= 1280px |AFTER < 1280px|
|--|--|--|
|<img width="343" alt="Screenshot 2566-08-07 at 14 39 45" src="https://github.com/Automattic/wp-calypso/assets/1881481/381f2826-5bea-4b11-b685-8e2c1abd2b63">|<img width="344" alt="Screenshot 2566-08-07 at 14 14 43" src="https://github.com/Automattic/wp-calypso/assets/1881481/707304a0-832a-41b7-a909-3506c281d406">|<img width="268" alt="Screenshot 2566-08-07 at 14 15 28" src="https://github.com/Automattic/wp-calypso/assets/1881481/75cb6aa0-02da-4501-8c37-3f13d99dcbca">|

Note that the word "right" is being removed from the new copy to avoid the following orphan word. cc: @lucasmendes-design @autumnfjeld

<img width="315" alt="Screenshot 2566-08-07 at 14 08 06" src="https://github.com/Automattic/wp-calypso/assets/1881481/117de5e8-2386-45de-a82c-c76ddc2fff2f">

### Update description copy on Footer screen

|BEFORE|AFTER >= 1280px |AFTER < 1280px|
|--|--|--|
|<img width="345" alt="Screenshot 2566-08-07 at 14 40 06" src="https://github.com/Automattic/wp-calypso/assets/1881481/b7f00db8-5c2a-415c-9569-34a6ea881661">|<img width="325" alt="Screenshot 2566-08-07 at 14 18 51" src="https://github.com/Automattic/wp-calypso/assets/1881481/a6d6437e-e8cb-499e-91e0-269a74be7259">|<img width="301" alt="Screenshot 2566-08-07 at 14 19 07" src="https://github.com/Automattic/wp-calypso/assets/1881481/73e22c7f-07a9-4c53-ae3f-d380b8abf6c5">|

### Update description copy on Footer screen

|BEFORE|AFTER >= 1280px |AFTER < 1280px|
|--|--|--|
|<img width="343" alt="Screenshot 2566-08-07 at 14 40 24" src="https://github.com/Automattic/wp-calypso/assets/1881481/e085fe65-6049-467b-92ac-94d4b5982fe7">|<img width="341" alt="Screenshot 2566-08-07 at 14 22 07" src="https://github.com/Automattic/wp-calypso/assets/1881481/a50941de-3c68-4bfc-9625-d10866367da0">|<img width="296" alt="Screenshot 2566-08-07 at 14 22 20" src="https://github.com/Automattic/wp-calypso/assets/1881481/3bd4c4b7-8bec-4c38-a405-c9b90896943d">|

## Testing Instructions

* Using the Calypso Live link in the first comment below
* Create a new site, and continue until the Design picker screen
* Scroll to find the CTA `Design your own` and verify the copy updates when the window width is lower and greater than `960px` 
* Click `Start designing` and verify the copy updates on the main screen
* Resize the window to less than `1280px` to verify there isn‘t an orphan word in the last line. Repeat this verification for the following steps as well.
* Click `Header`
* Click `Footer`
* Click `Sections`
* Click `Colors`

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-08-07 08:55 UTC, fushar commented
> Update description copy on Sections screen

> Note that the word "right" is being removed from the new copy to avoid the following orphan word. cc: @lucasmendes-design @autumnfjeld

I guess we don't have to worry much about this one, as this will be removed anyway as per pbxlJb-4gM-p2#comment-2829 (right?) 😄

2023-08-07 15:23 UTC, autumnfjeld commented
## ✅ CTA
<img width="627" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/d82edd52-cd89-4ae5-a6f8-6140fee0f28c">


Continuing from this [slack discussion](p1691420232384589/1691169745.478139-slack-CRWCHQGUB) and the P2 [comment](pekYwv-2u4-p2#comment-1953).


The copy is ok, it can stay as it is, your changes can remain @miksansegundo. Thank you.   



----------------

@miksansegundo  Thanks for flagging  this orphan.
![image](https://github.com/Automattic/wp-calypso/assets/5665959/42317288-6ecf-4433-9a82-c0e5e09de705)

Let's use this:
<img width="332" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/1920cbf0-e92f-4e24-bde8-9923a239489b">


-----
Let's do the same for footer:  
<img width="322" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/48a01270-b53c-4708-959a-84c409cc324e">


----

Per @fushar 's [comment](https://github.com/Automattic/wp-calypso/pull/80271#issuecomment-1667465660):  I don't have the final answer now.    
But @miksansegundo 's suggestion to remove the word `right` works for me.   😄 

We'll still need a "Add sections" header and subcopy.  It will probably have to be above the pattern list.  So it will be a reconfiguration of this.   TBD
<img width="659" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5665959/b7cfc224-d705-491a-ac6c-f475707b59be">

2023-08-08 02:48 UTC, fushar commented
> We'll still need a "Add sections" header and subcopy. It will probably have to be above the pattern list. So it will be a reconfiguration of this. TBD

@autumnfjeld oh, you're right!

2023-08-08 02:54 UTC, fushar requested changes
❌ The copy for assembler CTA in empty TS search is now missing:

<img width="652" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/5776f30b-dc7a-4424-ac28-7ae1934a8d99">

2023-08-08 06:58 UTC, fushar commented
> SAVE BUTTON ON SECTIONS PANEL

> Should be consistent with Header & Footer panels. Change to Save sections

@miksansegundo I think this PR misses the above [requirement](https://github.com/Automattic/wp-calypso/issues/80118)☝️

2023-08-08 07:01 UTC, miksansegundo commented
✅ Copy updates in header and footer description
✅ Fixed the empty TS search results 

###  Breakpoint >= 960px

|BEFORE|AFTER|
|--|--|
|<img width="767" alt="Screenshot 2566-08-08 at 13 49 55" src="https://github.com/Automattic/wp-calypso/assets/1881481/25c0e3a5-0984-4487-8880-ef897387e583">|<img width="729" alt="Screenshot 2566-08-08 at 13 48 09" src="https://github.com/Automattic/wp-calypso/assets/1881481/d3d6fab3-774d-474b-99ed-f78c85cc2ab7">|

###  Breakpoint < 960px

|BEFORE|AFTER|
|--|--|
|<img width="618" alt="Screenshot 2566-08-08 at 13 50 15" src="https://github.com/Automattic/wp-calypso/assets/1881481/fa478da6-def8-4010-a6e9-86dfb9b53dc2">|<img width="583" alt="Screenshot 2566-08-08 at 13 48 27" src="https://github.com/Automattic/wp-calypso/assets/1881481/9d6e64f7-7c6b-4225-b602-5c104ff5848d">|

Nice catch @fushar, can you review it again? Thanks!

2023-08-08 07:06 UTC, miksansegundo commented
> I think this PR misses the above https://github.com/Automattic/wp-calypso/issues/80118☝️

✅ Updated

2023-08-08 07:11 UTC, fushar approved these changes
Retested, I believe it looks good now, nice 👍

2023-08-08 08:44 UTC, merged

2023-08-08 08:47 UTC, miksansegundo commented
Oh, I just realized that maybe I should better wait for the translations. I'll deploy it this time. Let me know if you think otherwise.

2023-08-08 11:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8691513

Thank you @miksansegundo for including a screenshot in the description! This is really helpful for our translators.

2023-08-18 13:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8691513).