SiteStatusContent: slugify site URL in Activity Log link
Automattic/wp-calypso pull request #80286
Opened 2023-08-07 19:56 UTC by mattgawarecki

This pull request fixes an incorrect linking behavior on the Agency Dashboard for sites inside nested paths (e.g., `myawesomesite.com/wordpress`), which were erroneously directed to a non-existent page (e.g., `/activity-log/myawesomesite.com/wordpress`).

Resolves `1202619025189113-as-1205175816509628`.

## Proposed Changes

* Wrap `siteUrl` inside a call to `urlToSlug` when building button `href`s in the site table's **Site** column.
* Add unit test coverage for **Site** column links in the Dashboard's site table, to ensure they point to the correct slug-ified Activity Log URLs.

## Testing Instructions

* Before starting, ensure you have access to an account that has at least one site that exists inside a nested path, and that this account can see the Agency Dashboard.
* In your testing environment with this pull request applied, visit `/dashboard` in Jetpack Cloud.
* Find a site in the table that exists inside a nested path, and click its name.
* Verify you're sent to that site's Activity Log, and not an error page.
* Inspect code changes and unit test cases to ensure they make sense and test the proper lines of code.

### Reference screenshots

#### Error condition

![image](https://github.com/Automattic/wp-calypso/assets/670067/c2508e02-9f0a-4767-b399-18dc23dc651a)

#### Corrected

<img width="868" alt="image" src="https://github.com/Automattic/wp-calypso/assets/670067/77c89c96-708b-4e43-aef1-5af8d6289b50">

2023-08-10 02:54 UTC, yashwin requested changes
This works as expected.

We also have another link that redirects to the activity log page, and this is broken here. Could we please fix this here too? Thanks!

<img width="377" alt="Screenshot 2023-08-10 at 8 22 28 AM" src="https://github.com/Automattic/wp-calypso/assets/10586875/51c9a2d5-dba5-4720-b3db-0beb1d673343">

2023-08-10 02:54 UTC, yashwin commented on client/jetpack-cloud/sections/agency-dashboard/sites-overview/test/site-status-content.jsx
Is there a specific reason why this file is in `.jsx`?

2023-08-10 12:25 UTC, mattgawarecki commented on client/jetpack-cloud/sections/agency-dashboard/sites-overview/test/site-status-content.jsx
`jest.mock` changes the type of the object being mocked, but TypeScript isn't able to see this; so, for example, setting a mock's behavior via `myMock.mockReturnValue( 42 )` would result in a type error and fail the build. :-(

2023-08-10 12:33 UTC, mattgawarecki commented
> we also have another link that redirects to the activity log page, and this is broken here. Could we please fix this here too? Thanks!

You got it 👍 I also found a handful of other links where we're doing the same thing, so I fixed those. PR updated and ready for re-review. 🙂

2023-08-11 05:55 UTC, yashwin approved these changes
LGTM 🚀 Thanks for fixing all the instances of this!

2023-08-14 18:24 UTC, merged