Fix/cleanup stale step artifacts
Automattic/wp-calypso pull request #80352
Opened 2023-08-09 00:20 UTC by jdc91

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-09-13 01:47 UTC, southp requested changes

2023-09-13 01:47 UTC, southp commented on client/signup/config/steps-pure.js
> -		'plans-ecommerce-fulfilled': {
Removing this will break the ecommerce flow, i.e. `/start/ecommerce`. What we need to do instead is to add an entry for it in `steps-pure.js` like `plans-personal` or `plans-premium` does :)

2023-09-14 00:34 UTC, jdc91 commented on client/signup/config/steps-pure.js
> -		'plans-ecommerce-fulfilled': {
Strange, does this mean this has been broken for sometime now?

2023-09-15 01:50 UTC, southp approved these changes
Thanks for making our code more eco-friendly and resilient :) 

I've confirmed that:

* No step is removed for any existing flows. 
* Attempting to introduce cases like no step component, no step definition, wrong spelling, etc., the test case has captured all of them as expected.


LGTM 🚢

2023-09-15 01:57 UTC, merged

2023-09-15 14:40 UTC, mreishus commented
Temp reverted due to a problem with domain only checkout, see p1694760534062509-slack-C02FMH4G8 and p1694757161262339-slack-C05CT832K2T for more info