Upgraded Swiper lib
Automattic/wp-calypso pull request #80396
Opened 2023-08-09 19:38 UTC by nelsonec87

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-08-10 00:33 UTC, noahtallen requested changes
I tested this on mobile iOS and it's a lot more choppy than trunk. Not sure what causes it though :/

2023-08-12 19:11 UTC, nelsonec87 commented
I could not reproduce the problem on my Android device (tested with calypso.live), so it may be specific to iOS.
Can someone with access to an iPhone on @Automattic/serenity test this, please?
![image](https://github.com/Automattic/wp-calypso/assets/3801502/f999d0df-d94d-4642-8228-28e5fd1877dd)

2023-08-14 11:54 UTC, daledupreez commented
@noahtallen, could you be more specific about what choppiness you're seeing? I've just tested with Safari on iOS, and I am not seeing any major difference between this branch and production, but I may be missing something that you're noticing.

2023-08-14 20:45 UTC, simison commented
Nice! This would work as a good example how to upgrade [Swiper in Jetpack slideshow block](https://github.com/search?q=repo%3AAutomattic%2Fjetpack%20swiper&type=code). cc @jeherve

2023-08-15 15:35 UTC, sixhours commented
> I tested this on mobile iOS and it's a lot more choppy than trunk.

I can reproduce this on iOS 16.6/iPhone 14 Pro Max in Safari and Chrome. With the update:

https://github.com/Automattic/wp-calypso/assets/2124984/eb5ab2e7-d73d-4910-ac48-5f4fa059396c

On trunk:

https://github.com/Automattic/wp-calypso/assets/2124984/c02ae440-6289-4310-aa26-2a11b17b9752

2023-08-15 21:15 UTC, noahtallen commented
Interesting! My phone (iPhone 12, iOS 16.6) performs the same as @sixhours on both trunk and this PR.

2023-08-15 21:24 UTC, nelsonec87 commented
@noahtallen / @sixhours , can you test again with the new config? :)

2023-08-15 21:34 UTC, noahtallen approved these changes
Thanks, that fixed it for me!


https://github.com/Automattic/wp-calypso/assets/6265975/7734df68-f1f7-457d-8dd9-7c7e5ae158d8

2023-08-15 21:35 UTC, merged