I18N: Localise Related content dummy date
Automattic/wp-calypso pull request #80698
Opened 2023-08-16 14:35 UTC by sdnunca

## Proposed Changes

On https://wordpress.com/settings/reading/, when activating the “Show post publish date” option in the Related Posts options, the date displayed below the sample posts is in the American format instead of the localized format set in https://wordpress.com/settings/writing/.

![image](https://github.com/Automattic/wp-calypso/assets/23708351/ecbba60b-404b-4118-b3d4-6f6483a77632)

This PR updates the dummy date to take into account the set format and timezone:
<img width="728" alt="image" src="https://github.com/Automattic/wp-calypso/assets/23708351/98364a20-3069-4fc1-a788-211bbb3566a5">

## Testing Instructions
1. Switch your Calypso locale to a Mag-16 one. 
1. Navigate to https://wordpress.com/settings/writing/ for a simple site and set a custom date format
1. Navigate to https://wordpress.com/settings/reading/, enable “Show post publish date” option in the Related Posts options and confirm the shown date is localized.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-08-17 08:15 UTC, yuliyan requested changes
~~Tried to test it locally and using calypso.live, but the date isn't showing for me:~~
<details>
<summary>Screenshot:</summary>

![CleanShot 2023-08-17 at 11 07 14](https://github.com/Automattic/wp-calypso/assets/2722412/0889d016-977a-48ee-813a-d219227be05c)

</details>

There's also a type error with the `updateFields` prop passed to child components in `<ReadingSettingsForm />`. I think the `date_format` and `timezone_string` in the Fields type definition should be optional in order to avoid that:
```
date_format?: string;
timezone_string?: string;
```

----

Edit: Tested again on a different site and the date is now showing in the specified format:

![CleanShot 2023-08-17 at 11 25 36](https://github.com/Automattic/wp-calypso/assets/2722412/2f37a26d-37e5-428e-ac70-8c8ce883b4ab)

The reason why it wasn't showing on the first testing site was because the `timezoneString` was empty. That being said, do you think it will be a good idea to keep [the hardcoded default value for postDate](https://github.com/Automattic/wp-calypso/pull/80698/files#diff-177e1264fdcbefe1314e12043523dafe53e3ce09c1365f384e9917df0d5f721aL43) so it can be used as a fallback?

2023-08-17 12:10 UTC, sdnunca commented
@yuliyan  thank you very much for the in-depth feedback. I've made the 2 properties optional, and added the previous string as fallback in case we don't have a date format / timezone configured.

2023-08-17 12:29 UTC, yuliyan approved these changes
Thank you for the quick fix! All checks pass now, LGTM 🚀

2023-08-17 12:57 UTC, merged

2024-01-11 15:53 UTC, emilyaudela commented
It looks like this fix isn't working anymore for some reason. Can you look into it when you get a chance?
<img width="763" alt="Screenshot 2024-01-11 at 8 51 59 AM" src="https://github.com/Automattic/wp-calypso/assets/36699353/f4ee3e0a-c6c6-455c-8c61-2255e059f98a">

<img width="1059" alt="Screenshot 2024-01-11 at 8 52 17 AM" src="https://github.com/Automattic/wp-calypso/assets/36699353/4d06732d-e98b-498a-a96c-77873d1e72d6">

2024-01-21 18:29 UTC, sdnunca commented
@emilyaudela I've tried to replicate the issue multiple times but it seems I'm unable to. 

Settings on https://wordpress.com/settings/writing/sorinnuncatestsupport.wordpress.com: 
![image](https://github.com/Automattic/wp-calypso/assets/23708351/782df3ac-5ad6-49d3-8289-bfc99145e6c7)

Display on https://wordpress.com/settings/reading/sorinnuncatestsupport.wordpress.com: 

![image](https://github.com/Automattic/wp-calypso/assets/23708351/d7ca9439-738c-4a15-8263-2e7afb0c945c)

So it seems the original fix is still working. 
If you're still able to reproduce it, could you please provide some more details so I can further look into it?