Newsletter Categories: Integrate with Newsletter Settings page and create Newsletter Categories toggle
Automattic/wp-calypso pull request #80779
Opened 2023-08-17 21:48 UTC by phcp

Closes https://github.com/Automattic/wp-calypso/issues/80728
Closes https://github.com/Automattic/wp-calypso/issues/80729

## Proposed Changes

* Integrate `NewsletterCategoriesSettings` component with Newsletter Settings page
* Create `settings/newsletter-categories` feature flag
* Create Enable Newsletter Categories toggle
* Fix styling issues 

## Testing Instructions

* Apply this PR to your local
* Go to http://calypso.localhost:3000/settings/newsletter/{site-slug}
* You should see the "Enable newsletter categories" toggle disabled
* Click to enable and you should see the Newsletter Categories list
* Select/unselect categories and save changes

<img width="753" alt="Screenshot 2023-08-17 at 18 19 19" src="https://github.com/Automattic/wp-calypso/assets/3113712/2eda0e03-94cf-435b-849c-ac10b85a56b0">

<img width="747" alt="Screenshot 2023-08-17 at 18 19 33" src="https://github.com/Automattic/wp-calypso/assets/3113712/f282df38-4e1e-43ea-aad6-405660e6ea0e">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-08-18 07:09 UTC, TimBroddin approved these changes
Very nice work! I'm approving this as codewise it looks solid, and the suggestion below can be done on a separate PR if wanted.

I personally find it a bit noisy. You click the toggle & a lot starts happening:
- the toast appears
- the list goes from loading state to loaded state
- the save button goes from disabled to enabled
- there's a layout shift (the loading line from the list disappears)

![CleanShot 2023-08-18 at 09 04 24](https://github.com/Automattic/wp-calypso/assets/528287/e9723d68-0df9-4da1-a3de-1969e7fa206b)

One option would be to already load the list (`display: none`)?

What do you think @crisbusquets ?

2023-08-18 07:21 UTC, crisbusquets commented
> Very nice work! I'm approving this as codewise it looks solid, and the suggestion below can be done on a separate PR if wanted.
> 
> I personally find it a bit noisy. You click the toggle & a lot starts happening:
> 
> * the toast appears
> * the list goes from loading state to loaded state
> * the save button goes from disabled to enabled
> * there's a layout shift (the loading line from the list disappears)
> 
> ![CleanShot 2023-08-18 at 09 04 24](https://user-images.githubusercontent.com/528287/261527262-e9723d68-0df9-4da1-a3de-1969e7fa206b.gif)
> 
> One option would be to already load the list (`display: none`)?
> 
> What do you think @crisbusquets ?

Hi, thanks for the ping!

I agree that it's a bit noisy. What worries me the most is the layout shift and the disabled/enabled state. Perhaps what you suggest with `display:none` could work better. If the animation feels smoother it won't feel as noisy.

2023-08-18 09:27 UTC, TimBroddin requested changes
Changing this to Request changes, as there's a TS error:

```
    client/my-sites/site-settings/settings-reading/main.tsx(180,8): error TS2741: Property 'handleAutosavingToggle' is missing in type '{ fields: Fields; handleToggle: (field: string) => (value: boolean) => void; handleSubmitForm: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean; isSavingSettings: boolean; savedSubscriptionOptions: SubscriptionOptions | undefined; updateFields: (fields: Fields) => void; }' but required in type 'NewsletterSettingsSectionProps'.
```

2023-08-18 12:36 UTC, TimBroddin approved these changes
🚀

2023-08-21 13:58 UTC, merged

2023-08-21 15:21 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8781693

Thank you @phcp for including a screenshot in the description! This is really helpful for our translators.

2023-09-01 12:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8781693).