[WIP] Membership tiers
Automattic/wp-calypso pull request #81014
Opened 2023-08-24 10:22 UTC by millerf

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-08-28 19:26 UTC, pottedmeat commented
Testing on Calypso for a Jetpack Ninja site:

- I created Gold and Silver plans.
- I updated the Gold plan by tripling the priced to 3/36
- It created a new monthly plan with the yearly price.

<img width="950" alt="image" src="https://github.com/Automattic/jetpack/assets/38750/ecce1a29-cadc-4477-a100-e41ccee08e83">

2023-08-29 09:46 UTC, millerf commented
> Testing on Calypso for a Jetpack Ninja site:
> 
> * I created Gold and Silver plans.
> * I updated the Gold plan by tripling the priced to 3/36
> * It created a new monthly plan with the yearly price.
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/38750/263806704-ecce1a29-cadc-4477-a100-e41ccee08e83.png">

I am not sure what I am seeing here.

> I created Gold and Silver plans.

Those were creating before the patch? It looks like they have a monthly plan but no yearly plans attached, which should not be possible when creating plans/tiers with this PR...

2023-08-30 02:51 UTC, pottedmeat commented
I was able to test succesfully.

2023-08-30 09:22 UTC, millerf commented
> I was able to test succesfully.

Did you only test this PR or the https://github.com/Automattic/jetpack/pull/32710?

2023-08-31 15:34 UTC, pottedmeat commented
> Did you only test this PR or the https://github.com/Automattic/jetpack/pull/32710?

I followed the Jetpack PR instructions.

2023-09-09 00:53 UTC, n3f approved these changes
WFM 👍 (plus a small comment)

2023-09-09 00:53 UTC, n3f commented on client/my-sites/earn/components/add-edit-plan-modal/index.tsx
> +	const annualFrequency = '1 year';
Should these be promoted to consts outside the component?

e.g.

```js
const MONTHLY_FREQUENCY = '1 month';
const YEARLY_FREQUENCY = '1 year';
...
const RecurringPaymentsPlanAddEditModal = ( {
```

2023-09-11 12:47 UTC, millerf commented on client/my-sites/earn/components/add-edit-plan-modal/index.tsx
> +	const annualFrequency = '1 year';
Yep. Nice one

2023-09-11 13:24 UTC, millerf commented on client/my-sites/earn/components/add-edit-plan-modal/index.tsx
> +	const annualFrequency = '1 year';
Done.

2023-10-06 04:32 UTC, worldomonation commented
Code Style build is permafailing and reporting a large number of linting issues. It seems this PR has been living for quite some time (1+ month) and the branch possibly longer than that, so I'd suggest that you pull the most recent `trunk` and rebase this branch on top. 

I wrote a p7H4VZ-3Oh-p2 on how to rebase without causing a review bomb.

2023-10-06 04:35 UTC, worldomonation requested changes
Please see previous comment.

2023-10-06 09:29 UTC, olaseni commented
This looks good from an `/email` perspective. I can see that the changes are really just formatting changes, and there seems to be no regression.

I did not test the other changes though.

2023-10-06 10:16 UTC, millerf commented
@worldomonation @olaseni It looks like the merge I intended didn't go as expected. 
I'll rebase on trunk from my latest good commit now and force-push.

Thanks for the pings

2023-10-06 10:17 UTC, millerf commented
The different pings were automatically added. I have no idea why. Sorry about the wide pings...

2023-10-06 16:02 UTC, millerf commented
Closing in favor of https://github.com/Automattic/wp-calypso/pull/82728

2023-10-06 16:02 UTC, closed without merging