Fix `Activate this design` button for Marketplace themes
Automattic/wp-calypso pull request #81357
Opened 2023-09-04 14:49 UTC by gcsecsey

Closes https://github.com/Automattic/dotcom-forge/issues/3581

## Proposed Changes

* add a query to refresh site details when the AT transfer is complete

## Testing Instructions

* with a SIMPLE site purchase the Business plan, or register a new test site from `/start/business`
* purchase a partner theme which has plugin dependencies (eg. `themes/makoney` or `themes/nokul`)
* after checkout, wait for the AT transfer to finish
* on the Thank You page, click the `Activate this theme` button
* check that the ActivationModal is shown (the eligibility modal before should **NOT** be shown)
   <img width="1892" alt="CleanShot 2023-09-01 at 13 42 08@2x" src="https://github.com/Automattic/wp-calypso/assets/11555574/d787dda7-3d66-4ead-9c45-67dc84ce8671">
* go to `wp-admin/plugins.php` and check that the dependency plugins are installed
* check that the theme is activated

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-09-05 08:04 UTC, epeicher requested changes
The code changes make sense to me, but if I clear the cache and follow the testing instructions, I can still reproduce the issue described in the linked task. 

Please see a video with the steps:

https://github.com/Automattic/wp-calypso/assets/3519124/7f69a7ad-6936-460a-8d56-401571060921

2023-09-05 10:23 UTC, gcsecsey commented
> The code changes make sense to me, but if I clear the cache and follow the testing instructions, I can still reproduce the issue described in the linked task.

Thanks @epeicher for testing this, I'll investigate running this with an empty cache further. Maybe the timing of the refetch is still too soon in this case.

> In the end, the theme is installed but not active, and the dependent plugins are not installed:

I've also tested this again with both themes and found an interesting detail. When testing with the Makoney theme, the dependency plugin `AinoBlocks` is installed. When testing with the Nokul theme, the dependencies aren't installed either.

Maybe there's also some difference in the configuration of these themes?

Makoney:
<img width="391" alt="CleanShot 2023-09-05 at 11 15 17@2x" src="https://github.com/Automattic/wp-calypso/assets/11555574/d095e966-7254-46ff-9b93-f4ed359d8ab1">

Nokul:
<img width="458" alt="CleanShot 2023-09-05 at 11 14 52@2x" src="https://github.com/Automattic/wp-calypso/assets/11555574/5b0a3c46-7bbc-4c7f-88c3-15c6be14c4c1">

2023-09-05 11:07 UTC, epeicher commented
> I've also tested this again with both themes and found an interesting detail. When testing with the Makoney theme, the dependency plugin `AinoBlocks` is installed. When testing with the Nokul theme, the dependencies aren't installed either.
> 
> Maybe there's also some difference in the configuration of these themes?

One difference I've found that may or may not be related is that `Makoney` only has one dependency but `Nokul` has two dependencies. I don't know if that could be related or if it just affects the timing 🤷 . Thanks for investigating this further!

2023-09-06 11:25 UTC, gcsecsey commented
I added the `isSiteAtomic` hook to the `useAtomicTransfer` hook as a final check. This makes the progress bar shown up until the `is_wpcom_atomic` flag is returned as true from the sites endpoint. This guarantees that the Calypso state is up-to-date when the user can click the `Activate` button. cc @WBerredo 

I couldn't find the root cause yet of why the dependency plugins of the `Nokul` theme. I'll raise a separate PR to address that, for now I've removed checking the plugins from the test steps. 

@epeicher please give another review to this when you can. 🙏

2023-09-06 16:00 UTC, epeicher approved these changes
I have tested and reviewed the changes and they Look Good To Me! 🚢 

https://github.com/Automattic/wp-calypso/assets/3519124/b8431d41-8cd4-415d-a5e8-485963eadcc9

2023-09-06 16:25 UTC, epeicher commented
>I couldn't find the root cause yet of why the dependency plugins of the Nokul theme. I'll raise a separate PR to address that, for now I've removed checking the plugins from the test steps.

That's great as it could be unrelated, so we can fix this issue now and iterate on that.

2023-09-07 09:05 UTC, merged