Stats: Release Paid Stats to WPCOM sites
Automattic/wp-calypso pull request #81730
Opened 2023-09-14 14:36 UTC by dognose24

Related to #80258 
## Proposed Changes

* Enable the feature flag `stats/paid-wpcom-stats` on all environments to release Paid Stats for all WPCOM sites.

## Testing Instructions

* Spin up the change with the Calypso Live link.
* Prepare a WPCOM site without any Stats purchases or WordPress.com plans.

#### Upgrade from Stats dashboard
* Navigate to Stats > `Traffic` page: `/stats/day/{site-slug}`.
* Ensure the upgrade notice shows on top of the page.
* Click on the `Upgrade my Stats` button.
* Ensure the page is redirected to the purchase wizard or standalone purchase page according to the `is_commercial` classifier.
* Ensure the purchase action can be done and the page is redirected to the checkout page.

#### Upgrade from Add-Ons page
* Navigate to the `Add-Ons` page: `/add-ons/{site-slug}`.
* Ensure the Stats product cards show on the page.
* Click on the `Upgrade Stats` button of Stats product cards.
* Ensure the page is redirected to the respective standalone purchase page.
* Ensure the purchase action can be done and the page is redirected to the checkout page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-09-14 16:36 UTC, ederrengifo requested changes
The color and add-on page look good! I do have some comments about minor adjustments based on the design:

- [x] Alignment with the bullets titles
- [x] Adjust spacing between buttons and text and between steps
- [x] Change the positioning of the benefits for the personal selection
- [x] Adjust decimals format for the commercial selection
- [x] Remove the word "benefits" for the commercial selection
- [x] Adjust the color of the Stats illustration

Here is an image with the details
<img width="2505" alt="paid-stats-feedback" src="https://github.com/Automattic/wp-calypso/assets/10525007/2a47cb06-9321-4a56-8c5f-0bb433c0c7d2">

2023-09-15 04:35 UTC, kangzj commented
Hi @dognose24 maybe we could ship the final touches suggested by @ederrengifo now and flip the feature flag on Monday. What do you think?

2023-09-15 05:30 UTC, dognose24 commented
@kangzj Yeah, I plan to ship this PR to flip the feature flag accompanying the feedback from @ederrengifo the following Monday! The changes could use another round of review. 🙏🏼

2023-09-15 05:41 UTC, dognose24 commented
> Adjust the color of the Stats illustration

Do you mean the bar chart color should follow the applied color scheme? Or just use `#1689DB` for standalone purchase pages and `#CCD9E7` for the wizard? @ederrengifo

2023-09-15 10:40 UTC, madebynoam commented
> Do you mean the bar chart color should follow the applied color scheme? Or just use #1689DB for standalone purchase pages and #CCD9E7 for the wizard? @ederrengifo

Hey @dognose24! 

I believe Eder was referring to the side illustration. The current version with the saturated blue is too strong and overwhelms the left content. So we want the bars in that illustration to be #CCD9E7

<img width="806" alt="image" src="https://github.com/Automattic/wp-calypso/assets/8889977/19ed3ee0-6f21-417d-a1d6-e3e980cb59df">

2023-09-15 14:42 UTC, dognose24 commented
@madebynoam Thanks for the explanation! The fix is updated in https://github.com/Automattic/wp-calypso/pull/81730/commits/d2b1c426db1689ce0437713afa3ca4675586c448.

2023-09-15 16:27 UTC, ederrengifo approved these changes
LGTM!

2023-09-17 22:01 UTC, kangzj approved these changes
Looks awesome! 👍 

I'm happy for the PR to ship as is. I'm just wondering whether we should change the colour of the slider to the primary theme colour. Otherwise, it feels like two many colours on a single page. @ederrengifo 

Looks awesome! 👍 

I'm happy for the PR to ship as is. I'm just wondering whether we could change the colour of the slider to the primary theme colour. Otherwise, it feels like two many colours on a single page or you think it's okay @ederrengifo. Thanks.

![image](https://github.com/Automattic/wp-calypso/assets/1425433/a3ed91ad-0d0c-4420-823f-dfedfe02ea6a)

2023-09-18 02:48 UTC, dognose24 commented
> colour of the slider to the primary theme colour

Do you mean to make the color the same as the green button `var(--color-accent)` in that case? Or the slider color is aligned with `var(--color-primary)` already.

> possibly the ticks and the number for steps as well?

Would the check symbols adapted to the color scheme create ambiguity in some cases? Like red color for included features. 🤔

<img width="1114" alt="截圖 2023-09-18 上午10 47 29" src="https://github.com/Automattic/wp-calypso/assets/6869813/6946a183-7fd5-4a6b-84e8-755d10677e3c">

2023-09-18 02:53 UTC, kangzj commented
> Do you mean to make the color the same as the green button var(--color-accent) in that case? Or the slider color is aligned with var(--color-primary) already.

> Would the check symbols adapted to the color scheme create ambiguity in some cases? Like red color for included features. 🤔

@dognose24 thanks for the explanation. Let's ship as is. I guess it's more of an @ederrengifo  question 😄

2023-09-18 03:10 UTC, merged