Update/rename inbox symbols components to mailboxes
Automattic/wp-calypso pull request #81804
Opened 2023-09-16 08:35 UTC by olaseni

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-09-18 17:09 UTC, wongasy requested changes
I realize that analytics will be updated for some events that rely on the path for reporting. However, in cases where the tracking event is not generated based on the path (e.g. `calypso_inbox_upsell`), we might want to keep analytics as-is to avoid disconnected data. If we change the event names, retrieving data becomes problematic. We'll need to remember to look for `calypso_mailboxes_upsell` instead of `calypso_inbox_upsell` after a certain date.

>Duplicate the inbox folder to a new mailboxes folder and converts all JSX to TSX

I wonder if this change is really needed. I see how cases like renaming `emailManagementInbox` to `emailManagementMailboxes` are beneficial, since generating a path that contains `mailboxes` when the function name says otherwise (`emailManagementInbox`) is confusing. However, I don't know if it's really necessary to ensure consistency between the path name and folder name of our code. This makes back-tracking of code changes difficult. I'd like to see @stephanethomas and @nightnei's thoughts on this as well.

2023-09-18 17:09 UTC, wongasy commented on client/my-sites/email/mailboxes/constants.ts
> +export const MAILBOXES_SOURCE = 'mailboxes';
```suggestion
export const INBOX_SOURCE = 'inbox';
```
I'm inclined to leave this as-is to allow data continuity. By changing this now, we'll have disconnected data where traffic prior to deploying this change will be reported against `inbox` and traffic after deploying this change will be reported against `mailboxes`.

2023-09-18 17:09 UTC, wongasy commented on client/my-sites/email/email-management/home/utils.ts
> + * `calypso_mailboxes_upsell`, when upsell triggered by a CTA click from My Mailboxes.
By changing the event name, we'll run into the issue where data becomes disconnected for different time periods. I'm inclined to keep the tracking event name as-is, which means the constant should be kept as `INBOX_SOURCE`.

2023-09-18 17:58 UTC, olaseni commented on client/my-sites/email/mailboxes/constants.ts
> +export const MAILBOXES_SOURCE = 'mailboxes';
Fine with me. I'll revert.

2023-09-19 08:23 UTC, stephanethomas commented
> Duplicate the inbox folder to a new mailboxes folder and converts all JSX to TSX

Unless I've missed something I'm not sure we should duplicate code - we don't have the same technical constraints in Calypso than in WordPress.com where you would need to split a refactoring into multiple patchs. Here, we can remove the old files and add the new ones in the same pull request, which would make it easier to understand changes. For example, it's not clear what was required to convert those files from JSX to TSX (maybe this kind of change should be done in a different pull request?).

> I wonder if this change is really needed. [...] I don't know if it's really necessary to ensure consistency between the path name and folder name of our code. This makes back-tracking of code changes difficult.

I would still update any reference in our code that mentions the former name. This will make it easier to find stuff in the future, as developers (or maybe that's just me?) will based their search on what they see in the user interface. I would even rename constants, and keep the former value:

```javascript
export const MAILBOXES_SOURCE = 'inbox';
```

2023-09-19 11:40 UTC, wongasy commented
>we can remove the old files and add the new ones in the same pull request, which would make it easier to understand changes.

Agreed. That way, it's clear that the files were renamed from `/inbox/...` to `/mailboxes/...`. With the changes done in separate PRs, when we come back to this particular commit, it's going to be as-if we introduced brand new code, but we didn't.

2023-09-20 08:28 UTC, olaseni commented
> Agreed. That way, it's clear that the files were renamed from /inbox/... to /mailboxes/.... 

Done. The are no longer any duplicate folders.

2023-09-20 11:11 UTC, olaseni commented on client/my-sites/domains/domain-management/components/domain/domain-info-card/email/types.tsx
> -};
Removing this one because there's absolutely no usage. Confirmed with @rafaelgallani

2023-09-20 19:02 UTC, wongasy approved these changes
LGTM!

Confirmed that I was able to:

* Purchase Professional Email
* Purchase Google Workspace
* Get the "My Mailboxes" item in the fallback menu for domain-only sites (strangely, I was only able to block the URL once, all subsequent page loads failed to fallback. Given that the fallback code looks right, I won't worry about the weirdness during testing)
* Purchase an additional mailbox (I only tested Titan. Google Workspace is taking a long time to setup which is stopping me from adding a new mailbox for Google. Given that all we're doing is renaming a folder and updating the path for embedded inbox, we should be good to proceed)

Since it's towards EOD now, let's hold off merging until tomorrow just to be safe. Hopefully the Jetpack stuff will be deployed tomorrow as well. I'm still not seeing "My Mailboxes" in the sidebar.

2023-09-20 19:02 UTC, wongasy commented on client/my-sites/email/mailboxes/new-mailbox-upsell/index.tsx
> +							recordTracksEvent( 'calypso_mailboxes_new_mailbox_upsell_click', {
```suggestion
							recordTracksEvent( 'calypso_inbox_new_mailbox_upsell_click', {
```

Let's maintain the same tracks event name for analytics continuity.

2023-09-20 19:08 UTC, wongasy commented
>Google Workspace is taking a long time to setup which is stopping me from adding a new mailbox for Google. 

Update - Setup finally completed. I was able to also confirm purchasing a new mailbox for Google Workspace!

2023-09-21 10:37 UTC, merged

2023-09-21 11:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9004452

Hi @olaseni, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Mailboxes are not supported on P2 sites`

Thank you in advance!

2023-10-05 09:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9004452).