Migration: Fix some issues around recording events and necessary props
Automattic/wp-calypso pull request #81959
Opened 2023-09-20 11:42 UTC by vishnugopal

This is part of an investigation around migration events dropping off in a funnel, with the current theory being that one event has fired off twice (or more). This PR is an attempt to fix that.

In addition, this changes a bunch of logic at places to include required keys in dependency arrays.

## Testing Instructions

Test the migration flows and make sure that events are recorded only once.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] ~~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~~

2023-09-20 11:43 UTC, vishnugopal commented on client/my-sites/migrate/section-migrate.jsx
> +				/* suppress this error for now */
As far as I can see, this function never works and must be replaced with 
![CleanShot 2023-09-20 at 17 13 32](https://github.com/Automattic/wp-calypso/assets/533/58889c75-39c2-4fb5-872c-140627dcee92)

I'll do that in a separate PR.

2023-09-22 11:39 UTC, ouikhuan requested changes

2023-09-22 11:39 UTC, ouikhuan commented on client/blocks/importer/wordpress/import-everything/pre-migration/index.tsx
> +					'calypso_site_migration_ready_screen',
I think I've found another bug that's causing `calypso_site_migration_ready_screen` triggering so high. It's not introduced in this PR. At the moment, when a source site is not connected to WordPress.com we'll show the update info screen. However, `showUpdatePluginInfo` will always be `false` at beginning so `calypso_site_migration_ready_screen` also triggers when `calypso_site_importer_show_update_info` triggered. It's fine if you handle it in this PR or with a new PR.

2023-09-22 11:39 UTC, ouikhuan commented on client/blocks/importer/wordpress/import-everything/pre-migration/update-plugins.tsx
> +	}, [ isMigrateFromWp, migrationTrackingProps ] );
For some reason `calypso_site_importer_show_update_info` is also triggering when a source site when from unconnected to connected now. 

To reproduce:
- Start the migration flow with a site that's not connected to WordPress.com
- Follow the flow and connecting the site.
- You'll see `calypso_site_importer_show_update_info` gets triggered again before the migrate ready screen shows.

2023-09-22 11:39 UTC, ouikhuan commented on client/blocks/importer/wordpress/import-everything/pre-migration/migration-credentials-form.tsx
> +export const MigrationCredentialsForm: React.FunctionComponent< Props > = ( {
I'm getting a Maximum update depth exceeded warning now when opening up the credential form. See the video below:

https://github.com/Automattic/wp-calypso/assets/4074459/63b81f99-a633-40f0-a012-477c0b5123f7

2023-09-22 11:39 UTC, ouikhuan commented on client/blocks/importer/wordpress/import-everything/pre-migration/upgrade-plan.tsx
> +	}, [ dispatch, migrationTrackingProps ] );
`calypso_site_migration_upgrade_plan_screen` gets triggered again when clicking on `Upgrade and migrate`

2023-09-22 11:39 UTC, ouikhuan commented on client/blocks/importer/wordpress/import-everything/confirm.tsx
> +	const showConfirmDialogOrStartImport = useCallback( () => {
I think this file is a part of old flow and not using anymore at the moment. Can't triggering this during my test.

2023-10-24 05:03 UTC, vishnugopal commented
Not continuing with this PR as we've changed things significantly since then and fixed other root causes.

2023-10-24 05:03 UTC, closed without merging