Recover anonId after identifyUser
Automattic/wp-calypso pull request #82269
Opened 2023-09-27 16:05 UTC by claudiucelfilip

Related to #

## Proposed Changes

After login and signup, a `identifyUser` tracks event is recorded. This removes `tk_ai`  cookie (anonId) which breaks continuity between ExPlat assignments.
This PR attempts to fix this by restoring the `tk_ai` cookie after it's been removed.

## Testing Instructions

* Visit a Logged Out Landing page, so that the `tk_ai` cookie is populated
* Go through the Log in flow and the Signup flow and make sure the `tk_ai` is the same

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-09-28 02:19 UTC, aaronyan reviewed
Great find and fix @claudiucelfilip! Thank you for investigating and finding a solution to persist the `tk_ai`.

I'm checking in with a few folks here (p4qSXL-6N9-p2) to make sure that this is okay too!

2023-09-28 11:20 UTC, gmovr commented
I tested this manually, and it seems to work well. In my case it didn't set `tk_ai` for my user, likely because I haven't been logged-out for a long time. 

But I manually added the `tk_ai` cookie via the console, and having this cookie present while also being logged-in doesn't seem to cause any issues. 

The Tracks events I've checked (e.g. page views, interactions, clicks) all fire correctly using my logged-in WPcom user ID.

This seems like a good solution for carrying over the logged-out experiment to Calypso. 👍

2023-09-28 19:22 UTC, xyu requested changes
Tracks works on the assumption that anon ids gets removed and associated with the real user id on login / signup. Trying to restore the anonid after it's already been aliased to a user id is likely to cause unintended consequences:
https://nosaraproject.wordpress.com/2023/09/28/restoring-the-tk_ai-on-wp-login-and-signup/#comment-20591

2023-09-29 01:48 UTC, aaronyan commented
I'm hoping this PR is not necessary if we are able to preserve the logged-out assignment while the user is logged-in. We're testing this out in this diff (D123174#2423467-code).

2023-09-29 09:24 UTC, claudiucelfilip commented
> I'm hoping this PR is not necessary if we are able to preserve the logged-out assignment while the user is logged-in. We're testing this out in this diff (D123174#2423467-code).

@aaronyan I think we still need some sort of a parallel cookie that the ExPlat assigned can use. I added a couple of proposals in the diff: D123174#2423857-code.
One of which suggest restoring the `tk_ai` into another cookie: #82385

2023-09-30 00:37 UTC, aaronyan commented
That looks awesome, thank you @claudiucelfilip! 🙌

2023-10-02 09:34 UTC, dzver approved these changes
LGTM

2023-10-02 09:37 UTC, dzver requested changes
Actually, I said it looks good but there's a failing test

2023-10-02 10:38 UTC, claudiucelfilip commented
> Actually, I said it looks good but there's a failing test

@dzver The test was fixed by extending the `cookie.parse` mock to work on multiple calls.

@xyu the [change](https://github.com/Automattic/wp-calypso/pull/82385) to restore the anonId to a different, `tk_ai_explat` cookie. This shouldn't affect Tracks behavior anymore.

2023-10-05 09:01 UTC, claudiucelfilip commented
Closing this as we've moved to a different approach (#82596) where we save the `anonId` as a user attribute on login and signup.

2023-10-05 09:01 UTC, closed without merging