Partner Themes on Onboarding: Support custom domains
Automattic/wp-calypso pull request #82292
Opened 2023-09-27 20:22 UTC by WBerredo

Fix https://github.com/Automattic/wp-calypso/issues/82279

## Proposed Changes

* Allow the usage of site slug from site data, instead of from  URL
* Avoid showing the Eligibility Modal when a domain is purchased as the actual domain shouldn't change.

## Testing Instructions

* Apply the diff D118900-code to your sandbox and direct requests to the sandbox
* Use the getting started flow from `/start/free` or `/start/business`
* Select a custom domain (non `.wordpress.com` ended)
* On the Desing Picker, select a Partner Theme
* Click on `Unlock Theme` and after the upgrade modal, you shouldn't see the Eligibility Modal
* The flow should proceed until the Thank You page, and you should be able to activate the theme

**Regression test**
* Select a wordpress.com domain
* The flow should proceed normally, including the Eligibility Modal displaying

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-09-28 10:34 UTC, mmtr approved these changes
Nice! Works as expected for me.

2023-09-28 10:55 UTC, gcsecsey approved these changes
LGTM and works as described. :shipit:

2023-09-28 12:55 UTC, epeicher requested changes
Changes LGTM. But the tests should be fixed before proceeding, the test error can be reproduced locally running for example:
```
yarn run test-client unified-design-picker
```

2023-09-28 17:29 UTC, epeicher approved these changes
I have tested again after https://github.com/Automattic/wp-calypso/pull/82292/commits/5adccf0a0d3fab583411deb7605472541cecd18b and it still works as expected. Tests also pass so this PR can progress 🎉

2023-09-28 17:31 UTC, epeicher commented
Previous failure in E2E Tests (Mobile) in TC was due to a timeout, so I don't think that should block the PR, but re-running again is a good option 👍

2023-09-29 10:29 UTC, gcsecsey commented
I've re-triggered the E2E tests in TC, and CI is all green now.

2023-09-29 14:01 UTC, merged