Explore adding some basic context to the launchpad navigator
Automattic/wp-calypso pull request #82601
Opened 2023-10-04 15:19 UTC by daledupreez

## Proposed Changes

* This PR explores adding some basic context and to the `FloatingNavigator` component, as well as improving the styles slightly to align better with the launchpad styles in Customer Home. The specific changes are:
   - Add a (hard-coded) "Next steps for your site" title, with styles to match the list in Customer Home
     * The replicated styles suggests that we should move more of the styles into the core components
   - Add a minimum width to the modal
   - Add an inactive/disabled `Older tasks` button -- this is a placeholder for the "show me older task lists" interaction I've been thinking of
   - Add an X button/icon to allow closing the modal explicitly

Furthermore, I want to call out changes _not_ included in this PR, which should be tackled in follow-ups:
 - The launchpad remains visible when doing client-side routing, which may or may not be what we want, but that should be handled in its own PR
 - The display and hiding of the card isn't smooth, or aligned with the Help Center or Notifications items
 - We are not treating or handling the card as a modal, e.g. when clicking on a task that navigates to a new page, or when clicking outside the card area
 - The Help Center, Notifications bar, and Launchpad Navigator can be stacked on each other, which needs to be untangled and sorted out
 - There seems to be a weird race condition where the tasks for the Customer Home and navigator task lists get re-sorted for some reason. Not sure what's going on for this yet.
 - This PR doesn't fix click handling for tasks that depend on injected functions, e.g. Share Site, where we need a function to show a modal

### Screenshot

<img width="1370" alt="Screenshot 2023-10-10 at 17 03 12" src="https://github.com/Automattic/wp-calypso/assets/3376401/3ca48917-baff-4a1d-bbd6-233538b618a3">

## Testing Instructions

* Run this branch locally or via Calypso.live
* Navigate to Customer Home for a site that is currently showing a task list
* Add `?flags=launchpad/navigator` to the URL
* Click on the launchpad navigator icon in the masterbar to open the modal
* Verify that you see the modal open up at a sufficiently wide starting point, and we show the "Next steps for your site header" while we're loading the checklist content
* Also verify that the modal has an X icon that is correctly clickable with the right cursor display
* Verify that clicking on the X icon closes the Launchpad Navigator
* Click on some of the tasks and verify that you're taken to the correct screens
  - If you're going to another Calypso screen (excluding Stepper screens), the launchpad navigator should remain visible across the transition (at least for now)
  - If you're leaving Calypso, the launchpad navigator should end up being hidden because we're losing both our client-side config state (i.e. the feature flag) _and_ possibly the context

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [N/A] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-10-04 16:09 UTC, valterlorran commented
@daledupreez tested and it looks excellent. Should we make this ready for review? Also, if it's OK for you, I can tackle the problem with task links. I noticed that before, and I was planning to work on it.

2023-10-04 17:38 UTC, valterlorran commented
@daledupreez I started the PR to fix the task actions here:
https://github.com/Automattic/wp-calypso/pull/82612

2023-10-05 03:10 UTC, nuriapenya commented
Oh, that was fast! ⚡ This already looks very promising. A couple of notes from my side:

* In my test, the tasks on the navigator do not match the ones at my home (this site was from the `write` intent):

<img width="1287" alt="Screenshot 2023-10-05 at 11 41 47" src="https://github.com/Automattic/wp-calypso/assets/7931304/9cc5d7ec-80cd-48f8-add3-e14a8b4d8701">

* Small one: The pointer is missing on hover. It should match the same hover: the account, help center, and notifications.
* Should close when clicking outside the component
* Should close when users click on other actions (notifications, help center) otherwise components stack:

<img width="443" alt="Screenshot 2023-10-05 at 11 54 50" src="https://github.com/Automattic/wp-calypso/assets/7931304/7d2ce761-ce36-47be-a6bf-5a6ca49e14a0">

* This is a bigger one, and we might do just simply a follow-up after the demo, but currently, we have 3 different interactions in that area: 
Notifications → open a slider
Help center → flying pop-up that can be dragged
Launchpad navigator → dropdown

Maybe we could make the Launchpad navigator look & behave like the notification slider? It would create some consistency, and the slider feels quite solid.

2023-10-05 03:12 UTC, nuriapenya requested changes
Added some comments above ☝🏽

2023-10-10 09:57 UTC, daledupreez commented
Thanks for taking a look, @nuriapenya! Most of the issues you flagged were existing shortcomings in our proof of concept, but we've handled a few of them in other PRs.

> * In my test, the tasks on the navigator do not match the ones at my home (this site was from the write intent)

This should be addressed by https://github.com/Automattic/wp-calypso/pull/82779

> * Small one: The pointer is missing on hover. It should match the same hover: the account, help center, and notifications.

Good catch! This is being addressed as a part of https://github.com/Automattic/wp-calypso/pull/82612 -- @markbiek also caught the issue in his review! 👀 
Also, that PR ensures that the tasks actually work (with some exceptions).

**Larger work items**

The interactions when closing and opening the existing masterbar items are already messy and inconsistent. I can get the Help Center and Notifications components to stack without the Launchpad Navigator interfering! 😬 

So I think that is something we'll need to refine across all three options, as well as making the incoming element animation consistent. I do think that the options there are complicated by the fact that we also need to consider the Help Center and Launchpad Navigator UX in the editor context.

I will look at whether we can lean on the Help Center implementation and components as a starting point so we keep that generally consistent, and we can iterate from there.

2023-10-10 09:59 UTC, daledupreez commented
Also, as a follow-up, I don't want to tackle any big or complicated tasks before we get basic alignment on the project as a whole -- our current goal is to get to a workable demo, even if there are known gaps and issues (which we should be honest about).

2023-10-10 16:40 UTC, valterlorran commented
> There seems to be a weird race condition where the tasks for the Customer Home and navigator task lists get re-sorted for some reason. Not sure what's going on for this yet.

This will probably be resolved when we merge https://github.com/Automattic/wp-calypso/pull/82669

2023-10-10 16:55 UTC, valterlorran approved these changes
LGTM!

2023-10-11 07:08 UTC, merged

2023-10-11 10:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9304213

Thank you @daledupreez for including a screenshot in the description! This is really helpful for our translators.

2023-10-30 12:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9304213).