BBE: add custom page type
Automattic/wp-calypso pull request #82870
Opened 2023-10-11 12:53 UTC by aneeshd16

Fixes https://github.com/Automattic/martech/issues/2165

## Proposed Changes

* Adds a new custom page type to the BBE flow.
* TBD

## Testing Instructions

* TBD

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-10-12 12:01 UTC, aneeshd16 commented on client/signup/difm/components/BrowserView.tsx
> -	SITEMAP_PAGE,
These have been deprecated and are no longer in use:

https://github.com/Automattic/wp-calypso/blob/3d91f1ca979992cb45d329b26899be635a2bcc05/client/signup/difm/constants.tsx#L36-L41

2023-10-12 12:01 UTC, aneeshd16 commented on client/signup/difm/components/BrowserView.tsx
> +			return null;
`null` since this page has a blank thumbnail.

2023-10-12 12:03 UTC, aneeshd16 commented on client/signup/steps/website-content/section-types/components/media-upload.tsx
I have extracted the media upload sections of `default-page-details` and `contact-page-details` into this component since it caused unnecessary duplication.

2023-10-12 12:04 UTC, aneeshd16 commented on client/signup/steps/website-content/section-types/hooks/use-change-handlers.ts
Extracted common change handlers to this file.

2023-10-16 09:11 UTC, southp requested changes
The new custom page type and the existing page types work as expected for me. I also really like how the PR restructure the code so that the duplicated parts are extracted into reusable units :) 

However, it looks like the replace / remove functions of media uploader are broken:

https://github.com/Automattic/wp-calypso/assets/1842898/2ed846f6-01ff-4164-a2ef-63db330f5946

Once that's fixed, this should be ready to ship :)

2023-10-16 12:59 UTC, aneeshd16 commented
Thanks for the review @southp!

I have fixed the bug via https://github.com/Automattic/wp-calypso/pull/82870/commits/a86995d44db6693a28e1bb55fff326f9c46c7d94. It was quite a peculiar bug where the `uploadId` from WordPress clashed with the key assigned by us. This bug would have happened with the existing code too, iff these following conditions were satisfied: The user creates a new site and the first image they upload is for the Photo Gallery page. 🙂

2023-10-19 02:48 UTC, southp approved these changes
Elegant fix! The PR now works great and LGTM 🚢

2023-10-19 04:50 UTC, merged

2023-10-19 06:20 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9407481

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

2023-10-25 14:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9407481).