Fix with theme signup flow for partner themes
Automattic/wp-calypso pull request #82930
Opened 2023-10-12 10:06 UTC by BogdanUngureanu

Instead of using the page function to redirect the user to checkout, we are now using the callback approach that's used in other addToCart flows.

This is needed in order for the checkout page to be properly displayed. Previously, the user was pointed to log-in again even though they just signed up for an account on WP.com

Related to https://github.com/Automattic/dotcom-forge/issues/4102

## Proposed Changes

* Redirect the user to checkout with the `callback` function from the stepper library.

## Testing Instructions

* Use the live link and open an incognito window
* Go to /themes
* Search for `olsen` partner theme
* Click on the Pick this design
* In the signup page, click on the `Continue with email` where you'll create a new account (you can use a `+` suffix for the email to have a unique email)
* Pick a site name and go to the plans page
* Click on Business
* Make sure that the Checkout page is displayed (and you're not redirected to log-in).  

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-10-12 16:54 UTC, WBerredo requested changes
> Manually, go to WordPress.com/checkout/your-site?signup=1 and you'll notice that the checkout actually loads.

I got to this point and the checkout works perfectly, even redirecting to the Congrats page at the end.


But its not redirecting to the Congrats page with the `onboarding` flag (maybe cause there is no `redirect_to` param?), which causes some problems with the experience later down the line.

Not sure if its related to the mentioned bug in testing instructions though and the need to change to WP.com in the middle of the process.

2023-10-13 09:09 UTC, BogdanUngureanu commented
Hi @WBerredo thanks for checking! Strange, the parameter should be there since the path is hardcoded in the `getWithThemeDestination` function to point to the marketplace thank you page (with the onboarding parameter passed).

I've also made another test (this time already logged-in) and the `onboarding` query param was passed correctly. 

IMO, I think we should merge it and test it again on production.

2023-10-13 10:58 UTC, Copons commented
@BogdanUngureanu do you think is there an opportunity to test this via E2E?

2023-10-13 11:18 UTC, BogdanUngureanu commented
@Copons I don't think this will be trivial. I had a look at the current tests and noticed that we would need to implement components (selectors) for a few sections:
- Logged out theme details (Currently there's only a [logged-in selector](https://github.com/Automattic/wp-calypso/blob/d2e42e5a427267a963237c3cd4f24430d2c2d76f/packages/calypso-e2e/src/lib/pages/themes-detail-page.ts)).
- Marketplace sections (For Partner and Community); Community themes uses a different URL than partners due to a technical limitation

2023-10-13 11:38 UTC, Copons commented
@BogdanUngureanu I think we could at least give it a try. It would be a nice exploration for covering complex paid flows involving signup, checkout, Atomic transfer, theme and plugin installations.

Here are some specs that, at a quick glance, contain pieces we could reuse or adapt:

- [VideoPress Signup](https://github.com/Automattic/wp-calypso/blob/8922b2d0741f30c260470414f398bde1d5965084/test/e2e/specs/onboarding/signup__videopress-tailored.ts): signup, checkout
- [Signup Business](https://github.com/Automattic/wp-calypso/blob/8922b2d0741f30c260470414f398bde1d5965084/test/e2e/specs/plans/plans__signup-business.ts): signup, checkout (for Business specifically)
- [Plugins Purchase](https://github.com/Automattic/wp-calypso/blob/8922b2d0741f30c260470414f398bde1d5965084/test/e2e/specs/plugins/plugins__purchase.ts): plugin purchase, checkout (Business)
- [Plugins Install/Remove](https://github.com/Automattic/wp-calypso/blob/8922b2d0741f30c260470414f398bde1d5965084/test/e2e/specs/plugins/plugins__install-remove.ts): plugin install
- [Onboarding Lifecycle](https://github.com/Automattic/wp-calypso/blob/8922b2d0741f30c260470414f398bde1d5965084/test/e2e/specs/onboarding/lifecycle__signup-onboarding-launch-cancel.ts#L161-L184): it seems to cover the Sell flow, maybe useful?

2023-10-13 12:16 UTC, BogdanUngureanu commented
@Copons Sure, I could give it a try. :)

2023-10-13 16:38 UTC, WBerredo commented
> Strange, the parameter should be there since the path is hardcoded in the getWithThemeDestination function to point to the marketplace thank you page (with the onboarding parameter passed).

Good point, I think the error is coming from this step on the testing instructions:

> Manually, go to WordPress.com/checkout/your-site?signup=1 and you'll notice that the checkout actually loads.

And as at this point, we start to point to prod, the `getWithThemeDestination` function would still have the old URL value.

2023-10-13 16:40 UTC, WBerredo commented
> I've also made another test (this time already logged-in) and the onboarding query param was passed correctly.

Yep, tested pointing `/start/with-theme?ref=calypshowcase&theme=olsen-fse&theme_type=marketplace` to the live link of this PR, with a logged-in session, and it worked.

> IMO, I think we should merge it and test it again on production.

Now I agree, because it might work given the tests.

2023-10-13 16:41 UTC, WBerredo approved these changes
LGTM based on the talks above.

2023-10-17 05:22 UTC, worldomonation commented
I tested out this PR using the calypso.live link.

**The Good**
- selecting a paid/community theme from `/themes` (eg. Zakra) and proceeding through signup and onboarding is successful!

**The Bad**
- theme installation takes essentially forever and feels like it's frozen. After the first ~10 seconds I thought the process had frozen, especially because the `Step 1 of 2` took only seconds to change to `Step 2 of 2` accompanied by the horizontal progress indicator quickly filling up to the maximum width.
- after the long installation completes, user is presented with two buttons: `Customize this design` and `View site`. Clicking on the `Customize this design` attempts but **fails** to load the Customizer after about half a minute.

I had not timed the process but I suspect the actual waiting was somewhere around 1 minute. Fortunately the process completed eventually (see screenshot below), but the long wait without visual feedback does not make this process pleasant to use.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/28be4b42-f6cc-461f-ab9d-8fb7f857ffc4)

Customizer issue:
![image](https://github.com/Automattic/wp-calypso/assets/6549265/c53c9544-bd4b-404f-9899-d5f81f47a973)

User id: 241364009
Site id: 224783273

2023-10-17 11:41 UTC, BogdanUngureanu commented
Hey @worldomonation, 
> theme installation takes essentially forever and feels like it's frozen. After the first ~10 seconds I thought the process had frozen, especially because the Step 1 of 2 took only seconds to change to Step 2 of 2 accompanied by the horizontal progress indicator quickly filling up to the maximum width.

The flow takes so long to complete because the site needs to be transferred to Atomic first and then the theme installed on the site. Unfortunately, I don't think we can do much about it. However, I think we could probably make some adjustments to the UI to feel that things are still happening.

> after the long installation completes, user is presented with two buttons: Customize this design and View site. Clicking on the Customize this design attempts but fails to load the Customizer after about half a minute.

This looks like a separate issue unrelated to the onboarding flow. cc @Automattic/bespin do you have a look into this?

With these in mind, I'll proceed with deploying this PR since these aren't related to this PR. :)

2023-10-17 11:43 UTC, merged