Create SidebarNavigator component
Automattic/wp-calypso pull request #83108
Opened 2023-10-17 15:35 UTC by mattgawarecki

This pull request adds menu navigation items for the Purchases view in Jetpack Cloud.

Depends on #83073, https://github.com/Automattic/jetpack-genesis/issues/57.
Resolves https://github.com/Automattic/jetpack-genesis/issues/61.

## Proposed Changes

* Add a collection of new menu items in `client/jetpack-cloud/sections/sidebar-navigation/purchases.tsx`, to be passed to `NewSidbar` as the value of the `menuItems` property.
* Import icons for each new menu item, matching designs (see: `Ra0o7IPph3bCS2xUCnAusZ-fi-4354%3A9506`).

## Testing Instructions

1. With this pull request loaded in your Jetpack Cloud test environment, visit `/dashboard?flags=jetpack/new-navigation`.
2. Click the **Purchases** item in the sidebar navigation panel.
3. Verify you're sent to the **Billing** page.
4. Look over each icon in the sidebar, ensuring the icon and its label match designs (see: `Ra0o7IPph3bCS2xUCnAusZ-fi-4354%3A9506`).
5. Click each link, ensuring you're sent to the appropriate page and the navigation item is highlighted afterward.
6. Verify that the text and icon for all menu items look and behave appropriately even as the viewport is resized.

### Mobile

<img width="457" alt="image" src="https://github.com/Automattic/wp-calypso/assets/670067/7944f43c-1e68-4cf1-8354-d2961e5ffb18">

### Desktop

<img width="1111" alt="image" src="https://github.com/Automattic/wp-calypso/assets/670067/cfb1600e-47d1-45f0-904a-532ff867ea6d">

2023-10-17 16:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9387371

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @mattgawarecki for including a screenshot in the description! This is really helpful for our translators.

2023-10-18 07:08 UTC, yashwin submitted a review, later dismissed
LGTM

2023-10-18 09:56 UTC, yashwin commented
@mattgawarecki: We must send the `isSelected` prop to the `SidebarNavigatorMenuItem` component. 

Check this for reference: https://github.com/Automattic/wp-calypso/pull/83159

2023-10-19 07:51 UTC, yashwin requested changes
Overall, it looks good. Just a few comments based on previous PR merges.

2023-10-19 07:51 UTC, yashwin commented on client/jetpack-cloud/sections/sidebar-navigation/purchases.tsx
> +const PARTNER_PORTAL_ROOT_PATH = '/partner-portal';
Can we now move this to `client/jetpack-cloud/sections/sidebar-navigation/lib/constants.ts`

2023-10-19 07:51 UTC, yashwin commented on client/jetpack-cloud/sections/sidebar-navigation/purchases.tsx
> +
We can now import these from `client/jetpack-cloud/sections/sidebar-navigation/lib/sidebar.ts`

2023-10-19 07:51 UTC, yashwin commented on client/jetpack-cloud/sections/sidebar-navigation/purchases.tsx
> +type ItemProps = {
Now we can use the `MenuItemProps` from `client/jetpack-cloud/sections/sidebar-navigation/types.ts`

2023-10-19 07:51 UTC, yashwin commented on client/jetpack-cloud/sections/sidebar-navigation/purchases.tsx
> +} );
I really like this idea and did the same in my PR! 

How about we do:

```suggestion
const createItem = ( props: ItemProps ) => ( {
	...props,
	path: PARTNER_PORTAL_ROOT_PATH,
	onClickMenuItem,
	isSelected: isSelected( props.link ),
} );
```

2023-10-19 07:51 UTC, yashwin commented on client/jetpack-cloud/sections/sidebar-navigation/purchases.tsx
> +			link: `${ PARTNER_PORTAL_ROOT_PATH }/billing`,
Can we move these URLs to `client/jetpack-cloud/sections/sidebar-navigation/lib/constants.ts`?

2023-10-20 02:20 UTC, yashwin approved these changes
LGTM. Thanks for addressing my comments 🚀

2023-10-20 05:37 UTC, yashwin commented
I did a rebase as there were conflicts

2023-10-20 13:51 UTC, merged

2023-10-20 14:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9387371).