ETK Performance: Defer loading the starter page templates plugins
Automattic/wp-calypso pull request #83351
Opened 2023-10-23 09:07 UTC by arthur791004

Related to pdDR7T-12w-p2

## Proposed Changes

* Defer loading the starter page templates plugins
  * starter-page-templates
  * starter-page-templates-error

## Testing Instructions

1. Checkout this branch.
2. in apps/editing-toolkit, run `yarn dev --sync`.
3. Create a new page on your sandboxed simple site
4. Make sure the starter page templates works as expected

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-10-23 09:40 UTC, alshakero requested changes

2023-10-23 09:40 UTC, alshakero commented on apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
> +			)
Turns out there is a backwards compatible way that goes like this:

```suggestion
 	true 
 );
 		wp_script_add_data( 'starter-page-templates', 'strategy', 'defer' );

```

2023-10-23 09:40 UTC, alshakero commented on apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
> +			)
+1

2023-10-23 09:52 UTC, alshakero approved these changes
Code looks great 👍🏼

2023-11-03 02:02 UTC, arthur791004 commented
Closing it as it's not planned. See pdDR7T-12w-p2#comment-1329.

2023-11-03 02:02 UTC, closed without merging