Jetpack Cloud: Update site selector appearance and behavior
Automattic/wp-calypso pull request #83438
Opened 2023-10-24 20:02 UTC by mattgawarecki

This pull request updates the look of the new navigation sidebar to more closely resemble designs (in terms of color, borders, etc). It also adds a way for customers who have an active partner key to _return_ to All Sites view if they leave it to manage a single site.

Resolves https://github.com/Automattic/jetpack-genesis/issues/66.

## Proposed Changes

*

## Testing Instructions

* In your Jetpack Cloud testing environment, apply this PR and load the Sites Management page. Make sure to add `?flags=jetpack/new-navigation` to your browser's query string so you can see the new navigation sidebar.
* Test opening and closing the Site Selector in the sidebar by repeatedly clicking the currently selected site. The selector should appear and disappear with each click.
* Select any site in your list to be sent to the single-site management view. Verify you're able to return to the Sites Management page by re-opening the site selector in the same way, and selecting All Sites.
* Inspect the appearance of the Site Selector and compare it with existing designs (see: ``). Pay special attention to border radii, colors when hovering over a site, and margins between the site selector and its containing elements.

2023-10-26 04:11 UTC, jkguidaven commented on client/jetpack-cloud/components/sidebar/index.tsx
> +	const canAccessJetpackManage = useSelector( hasActivePartnerKey );
Can we replace this with `has_jetpack_partner_access` props from the currentUser object? This way, we do not need to query the API.

2023-10-26 04:24 UTC, yashwin requested changes
Thanks for working on this!

I did a quick test and found a couple of issues based on how it looks in the prototype.

- The hover color is not green. It is gray.

<img width="274" alt="Screenshot 2023-10-26 at 9 46 38 AM" src="https://github.com/Automattic/wp-calypso/assets/10586875/a273261b-3049-4f89-9095-764944314360">

Prototype:

<img width="284" alt="Screenshot 2023-10-26 at 9 49 47 AM" src="https://github.com/Automattic/wp-calypso/assets/10586875/7381f4c4-eeba-4a79-bc2b-6e0eae8fee67">

- Is it possible to show the active site?

<img width="277" alt="Screenshot 2023-10-26 at 9 52 21 AM" src="https://github.com/Automattic/wp-calypso/assets/10586875/e84e306c-f50e-4bae-abf9-e3e1ce744040">

Prototype:

<img width="288" alt="Screenshot 2023-10-26 at 9 52 27 AM" src="https://github.com/Automattic/wp-calypso/assets/10586875/df831f0f-0262-4340-9bf7-22ca8e884154">

2023-10-26 04:24 UTC, yashwin commented on client/jetpack-cloud/style.scss
> +		&__sites {
Can we keep it `.site-selector__sites`. It becomes harder to search by the class name

2023-10-30 03:48 UTC, yashwin approved these changes
LGTM! Thanks for addressing my comments!

2023-10-30 06:08 UTC, jkguidaven approved these changes
Thanks for working on this and making the new feature more polished. LGTM 👍

2023-10-30 07:16 UTC, ilonagl approved these changes
Thank you for working on this!! It looks great.

2023-10-30 18:58 UTC, merged