Jetpack Manage: Add chevron down icon on All sites and Single site views
Automattic/wp-calypso pull request #83463
Opened 2023-10-25 13:22 UTC by vitozev

Resolves https://github.com/Automattic/jetpack-genesis/issues/63

## Proposed Changes

This PR adds chevron down icons next to the "All sites" title (in All Sites view) and next to the Site name (in Single Site view).

Before | After
--|--
Test|Test

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-10-25 13:39 UTC, vitozev commented on client/blocks/site/index.jsx
> +							</div>
The change in the elements was needed to ensure that the fade-out effect would continue working as expected for long site names.

2023-10-25 13:46 UTC, vitozev commented
The failing tests doesn't seem related to this PR, but will double-check tomorrow.

2023-10-26 04:07 UTC, yashwin requested changes
It looks good for "All Sites"

However, I found an issue with single site view:

> Verify that chevron down icon is displayed next to the site name in the sidebar

I see a chevron-right icon here. Is this expected? Also, I think the spacing between the site name & the chevron icon is a bit more.

<img width="272" alt="Screenshot 2023-10-26 at 9 31 59 AM" src="https://github.com/Automattic/wp-calypso/assets/10586875/c3f670af-bfcb-445c-bab6-58339fd73a4e">

2023-10-26 04:07 UTC, yashwin commented on client/blocks/all-sites/index.jsx
> +		showChevronIcon: false,
Could we rename this something more meaningful? Maybe like `showExpandIcon` or `showChevronDownIcon` since a chevron can be anything (up, down etc)?

2023-10-26 04:07 UTC, yashwin commented on client/blocks/all-sites/index.jsx
> +									className="all-sites__title-chevron-icon"
I have seen the design team suggesting using icons from :

import { Icon, chevronDown } from '@wordpress/icons';

2023-10-26 04:07 UTC, yashwin commented on client/blocks/all-sites/style.scss
> +		.all-sites__title-chevron-icon {
[NITPICK, NON-BLOCKER] Can we add an extra line space here?

```suggestion
		display: flex;
		
		.all-sites__title-chevron-icon {
```

2023-10-26 04:07 UTC, yashwin commented on client/blocks/site/style.scss
> +	.site__title-chevron-icon {
[NITPICK, NON-BLOCKER] Can we add an extra line space here?
```suggestion
	}
	
	.site__title-chevron-icon {
```

2023-10-27 10:41 UTC, vitozev commented on client/blocks/all-sites/index.jsx
> +		showChevronIcon: false,
Thanks! I've renamed it to `showChevronDownIcon`.

2023-10-27 10:41 UTC, vitozev commented on client/blocks/all-sites/index.jsx
> +									className="all-sites__title-chevron-icon"
I updated the icons to use the ones from the WP library.

2023-10-27 10:43 UTC, vitozev commented
Thanks for the feedback, @yashwin! I've addressed it and this PR can have another look now.

2023-10-30 03:57 UTC, yashwin approved these changes
LGTM 🚀 Thanks for addressing my comments!

2023-10-30 06:47 UTC, merged