Staging Sites: Display error when production->staging synchronization fails
Automattic/wp-calypso pull request #83587
Opened 2023-10-27 12:49 UTC by wojtekn

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-10-30 10:53 UTC, kozer requested changes

2023-10-30 10:53 UTC, kozer commented on client/my-sites/hosting/staging-site-card/card-content/staging-sync-card.tsx
> +	return Object.values( STAGING_SYNC_FAILED_ERROR_CODES ).includes( error );
`STAGING_SYNC_FAILED_ERROR_CODES` is an Array, not an object.
The code you wrote works, but the array object already has an `includes` [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes), so we can just write
```suggestion
	return STAGING_SYNC_FAILED_ERROR_CODES.includes( error );
```

2023-10-30 10:53 UTC, kozer commented on client/my-sites/hosting/staging-site-card/card-content/staging-sync-card.tsx
> +	return Object.values( STAGING_SYNC_JETPACK_ERROR_CODES ).includes( error );
```suggestion
	return STAGING_SYNC_JETPACK_ERROR_CODES.includes( error );
```

2023-10-30 11:07 UTC, kozer commented
I checked it and it seems to work as expected! I have added some code suggestions though!

However, when we refresh the pager, and before the data gets loaded, there is a timeframe when the checkboxes appear.
Can we `fetchingStatus` in order to avoid that?

We can also create another ticket for that and implement a "skeleton loader" as well so this will make things more complete from a UI/UX perspective.

2023-10-30 12:09 UTC, wojtekn commented
> I checked it and it seems to work as expected! I have added some code suggestions though!

Thanks for testing it. I applied the suggestion.

> We can also create another ticket for that and implement a "skeleton loader" as well so this will make things more complete from a UI/UX perspective.

Would you mind adding a new issue for that for our maintenance backlog?

2023-10-31 10:38 UTC, merged

2023-10-31 12:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9565242

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @wojtekn for including a screenshot in the description! This is really helpful for our translators.

2023-11-09 12:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9565242).