JP Manage: 56 - add tooltip to partner opt-in fieldset
Automattic/wp-calypso pull request #83605
Opened 2023-10-27 21:03 UTC by tbradsha

Resolves Automattic/jetpack-manage#56 - add tooltip to partner opt-in fieldset

## Proposed Changes

This does the following:

* Splits the opt-in logic into its own component: `PartnerProgramOptInFieldset`
* Adds an info icon to the fieldset
* Shows a popover if the info icon is clicked

Copy is pulled directly from original issue. Note that the original issue suggested using a lightbox, but upon testing it didn't seem to fit.

**Note:** I welcome any commits to improve the styling, particularly with regards to the "learn more" link. The styling and "Got it" button text was largely pulled from the existing popovers on the JP Manage dashboard:

![image](https://github.com/Automattic/wp-calypso/assets/32492176/1930bc32-947a-4f40-8e25-e6da3e604717)

## Testing Instructions

Using the `add/jp-manage/56-partner_opt-in_tooltip` branch:

1. Go here (may need `?flags=-jetpack/new-navigation`): `http://jetpack.cloud.localhost:3000/manage/signup`
2. Select one of the first two company types.
3. Click on the info icon.

It will look like this:
![image](https://github.com/Automattic/wp-calypso/assets/32492176/c0402bd3-6381-439b-ae46-ab924e0233cc)

I also considered an alternate, with the popover to the right, but slightly preferred the above:
![image](https://github.com/Automattic/wp-calypso/assets/32492176/dded05b9-3089-4db4-b3b5-dc16581579ad)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-10-30 08:37 UTC, coder-karen requested changes
The functionality works as advertised, and I agree the placement of the popup looks better just below (as you have it currently).

I spotted a few things that I'd think need changing though:

1. Hovering over the icon I'd expected the pointer to change, as with the info icons on the dashboard.

2. Currently the info icons don't appear to be accessible - I can't tab onto them. That said I can't tab on to the icons on the dashboard either, but I can tab on to the info icon on `partner-portal/billing` next to the 'Cost for month, year', which would be how I'd assume they should all be (I'll create a separate issue for those dashboard icons).

3. Lastly within the popup the link doesn't have an external link icon next to it, and it seems that it should given the only other link on the form itself has that icon too (it also looks like the links on the popups on the main dashboard don't either, will add that to an issue too). 

That said I know the issue itself said we should reuse the `i` functionality from the dashboard, though it seems it would make sense to fix those issues (accessibility and external link icon) now rather than fixing them in both places later. But perhaps we want more feedback on design expectations first, so maybe not as important in this PR. Issue created here: https://github.com/Automattic/jetpack-manage/issues/70

2023-10-30 14:40 UTC, tbradsha commented
> Hovering over the icon I'd expected the pointer to change
> Currently the info icons don't appear to be accessible - I can't tab onto them.

Indeed! Resolved in 2276c6f

> the popup the link doesn't have an external link icon next to it

b7ee2c8

2023-10-30 17:15 UTC, coder-karen approved these changes
Very nice! Looks great to me with those changes, thanks!

2023-10-30 17:18 UTC, merged

2023-10-30 19:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9561210

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @tbradsha for including a screenshot in the description! This is really helpful for our translators.

2023-11-09 12:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9561210).