Signup: handle passswordless existing account
Automattic/wp-calypso pull request #83767
Opened 2023-11-01 17:28 UTC by escapemanuele

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-01 18:07 UTC, alshakero requested changes
I'm getting no response when I click continue, and an 400 error from the endpoint.

1. Go to `user-social` step.
2. Go to `Continue with Email`. 
3. Type a passwordless email.
4. You'll be redirected to log-in.
5. Try to log in, you won't be able to.

2023-11-01 22:44 UTC, escapemanuele commented
Thank you @alshakero, missed that part! Should be fixed now.

2023-11-02 12:12 UTC, alshakero approved these changes
Tested with a passwordless account and normal account. All works great.

2023-11-02 12:12 UTC, alshakero commented on client/blocks/login/login-form.jsx
> +		}
This pattern is pretty strange around signup logic, we get some info from `props` then we call some function from props, it seems like `props` already has all the info and tools to make the decision, why should the component be involved.

2023-11-02 18:45 UTC, merged