GF Signup: Experiment social signups with the onboarding-pm flow
Automattic/wp-calypso pull request #83886
Opened 2023-11-03 20:05 UTC by jdc91

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-07 14:35 UTC, ddc22 commented
@aaronyan @southp curious to know your opinion about my approach to implement this experiment :)

2023-11-08 01:41 UTC, aaronyan reviewed
What happens if someone in `control` visits `onboarding-pm-social` and vice versa? Are they redirected to the appropriate page due to their assignment?

2023-11-08 02:28 UTC, jdc91 commented
> What happens if someone in control visits onboarding-pm-social and vice versa?

Ah good point! I can make that change 👍

2023-11-08 22:52 UTC, aaronyan commented
Thanks Dehan! I prefer if the experiment occurred on the same page and the contents change based on assignment. This would prevent users from manually seeing they are in an experiment. Would that be possible?

2023-11-08 23:23 UTC, jdc91 commented
@aaronyan this might take a bit longer since the styling of the component is tied mostly to the signup step user-social. I will see what I can do.

Some feedback here @escapemanuele to try to further encapsulate styles inside UI components instead of injecting SASS based on global page based selectors.

2023-11-09 15:39 UTC, escapemanuele commented
You are totally right @jdc91, that's solid and valid feedback. I'll keep it in mind!

2023-11-09 18:38 UTC, aaronyan reviewed
LGTM! I was able to assign myself and view experiences for `control` and `treatment` using the bookmarklet in Incognito + unblock third party cookies! Nice work @jdc91 at getting the experiences to load on the same URL.

2023-11-10 02:17 UTC, southp approved these changes
The code works as expected. How the variation works underneath is a bit hacky, but I think it's a balanced approach with all things considered. 🚢

2023-11-10 02:25 UTC, southp requested changes
Oh wait. Some pre-release E2E tests are failing. 
We will need to fix them before deploying.

2023-11-10 05:05 UTC, jdc91 commented on packages/calypso-e2e/src/lib/components/domain-search-component.ts
> +
@DustyReagan I am adding this line since there seems to be a delay the UI button that needs to be clicked.

2023-11-10 07:02 UTC, southp approved these changes
Leaving an explicit approval now that the e2e tests have been fixed.

2023-11-10 19:40 UTC, merged