Storage Add-Ons: Track spotlight plan card add-on upgrade CTA
Automattic/wp-calypso pull request #83891
Opened 2023-11-03 22:30 UTC by jeyip

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-06 23:25 UTC, jeyip commented
@chriskmnds I see that you're trying to refactor calls to tracks events to use `recordTracksEvent` in `client/my-sites/plans-grid/components/actions.tsx` [here](https://github.com/Automattic/wp-calypso/pull/83442 )

I wanted to check in and see how you feel about this PR -- it adds a _new_ `recordTracksEvent` to the same file.

I know, however, that we ultimately wanted to extract `recordTracksEvent` calls in the actions file ( [context]( https://github.com/Automattic/wp-calypso/issues/79006 ) ). If we prefer, I could started working on https://github.com/Automattic/wp-calypso/issues/79006 instead and add this new tracks events after we land on an implementation

2023-11-07 12:35 UTC, chriskmnds requested changes
Thanks for the ping @jeyip :-) This tests out _partially_ for me on the live image. 

I notice a slightly odd behavior with the CTA. Choosing 50GB on Business shows the "Upgrade" button, but I think that's incorrect? Clicking on it doesn't lead to any redirect and still records the same `calypso_signup_storage_add_on_upgrade_click ` event. I'm guessing that's not intended. Not sure if you see the same:

https://github.com/Automattic/wp-calypso/assets/1705499/f57c0490-c377-4ec0-8f55-e863274d6826

Concerning:

> I know, however, that we ultimately wanted to extract `recordTracksEvent` calls in the actions file ( https://github.com/Automattic/wp-calypso/issues/79006 ). If we prefer, I could started working on #79006 instead and add this new tracks events after we land on an implementation

I don't really see much benefit from doing the layer of abstraction mentioned in the linked issue. I think just passing along `recordTracksEvent` to the grid would be enough to keep things simple. So continuing to use it like you have here sounds good to me - we will just grab it from `helpers` in context instead of importing.

2023-11-09 20:11 UTC, jeyip commented
> I notice a slightly odd behavior with the CTA. Choosing 50GB on Business shows the "Upgrade" button, but I think that's incorrect? Clicking on it doesn't lead to any redirect and still records the same

Definitely incorrect -- I haven't seen that issue yet, so I'll try and replicate it 🤔

2024-03-15 13:33 UTC, southp commented
I think this is blocked by some of https://github.com/Automattic/wp-calypso/issues/85773, so I'm moving this to Blocked for now.

2025-07-25 19:16 UTC, closed without merging