Stats: Update chart range in response to nav arrows
Automattic/wp-calypso pull request #83911
Opened 2023-11-06 10:55 UTC by a8ck3n

Related to #83570.

## Proposed Changes

When updating the bar chart via the navigation arrows we now check the new query date and update the chart boundaries as needed.

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-06 22:00 UTC, kangzj requested changes
Thanks for working on this @a8ck3n 👍 

It works beautifully for the traffic page. However, this broke the arrows on the other pages, for example, `/stats/email/opens/day/227910/jetpack.com`.  The reason seems to be the other pages don't have the `chartStart` and `chartEnd` params. 🤔

2023-11-07 07:40 UTC, a8ck3n commented
> It works beautifully for the traffic page. However, this broke the arrows on the other pages […]

Thanks for catching this, @kangzj. I've updated the arrow handling to maintain the previous behaviour when the date range isn't present. I tested the changes on the Email Opens page, the Ads pages, and the Store pages. It is now working correctly in all instances where I found the chart + nav arrows combination. Note that the Subscribers page uses it's own wrapper/logic so that page behaves a little differently.

2023-11-07 22:03 UTC, kangzj approved these changes
The other places are all working well now! Thanks Kevin 👍 

I fixed a small issue when there's no chartStart / chartEnd in the URL for the traffic page (default range is used - e.g. last 30 days), the arrows don't work as expected. I figured, you  pre-processed the two parameters and chucked them in `dateRange` which I think should be used inside the header. I went ahead and tweaked it ( edcf832 ), and hope you don't mind 😄

2023-11-08 05:39 UTC, a8ck3n commented
> I went ahead and tweaked it ( [edcf832](https://github.com/Automattic/wp-calypso/commit/edcf8323439ef6aee095a4386dab3d2c686d2e12) ), and hope you don't mind 😄

Awesome! Thanks @kangzj. I'll have a look and get this shipped.

2023-11-08 06:20 UTC, merged