Stats: add "I don't solicite donations or sponsorships" to site identification conditions
Automattic/wp-calypso pull request #83927
Opened 2023-11-06 20:26 UTC by kangzj

Discussion: p7pQDF-8Yq-p2#comment-24253

## Proposed Changes

The PR proposes to add 'I don't solicite donations or sponsorships on my site' to the checklist for both Free plan selection and Commercial site disputation process, as the the condition is clearly stated in https://jetpack.com/support/jetpack-stats/free-or-paid/#how-is-a-commercial-site-defined .

## Testing Instructions

* Open a Calypso Live for a personal site `/stats/purchase/:siteSlug`
* Choose $0 a month
* Ensure the checklist is shown
* Check the checkboxes
* Ensure only when all checkboxes are checked, the purchase button becomes available

<img width="675" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1425433/ff13a646-3866-4672-be32-0a2717eefb29">

* Open a Calypso Live for a commercial site `/stats/purchase/:siteSlug`
* Click 'This is not a commercial site'
* Check the checkboxes
* Ensure only when all checkboxes are checked, the 'Request update' button becomes available

<img width="657" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1425433/9d8e0a14-e015-4b8f-ac1d-435a3c6fa63e">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-06 23:16 UTC, jsnmoon requested changes
Looks good. Ship away after fixing the typo (solicite -> solicit)!

2023-11-06 23:16 UTC, jsnmoon commented on client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx
> +								label={ translate( `I don't solicite donations or sponsorships on my site` ) }
```suggestion
								label={ translate( `I don't solicit donations or sponsorships on my site` ) }
```

2023-11-06 23:16 UTC, jsnmoon commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +- I don't solicite donations or sponsorships on my site.\n
```suggestion
- I don't solicit donations or sponsorships on my site.\n
```

2023-11-06 23:16 UTC, jsnmoon commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +											label={ translate( `I don't solicite donations or sponsorships on my site` ) }
```suggestion
											label={ translate( `I don't solicit donations or sponsorships on my site` ) }
```

2023-11-07 00:55 UTC, merged

2023-11-07 01:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9633996

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @kangzj for including a screenshot in the description! This is really helpful for our translators.

2023-11-16 12:35 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9633996).