Fix Jetpack Sale Banner and update text for BF 2023
Automattic/wp-calypso pull request #84101
Opened 2023-11-10 12:01 UTC by robertsreberski

- Update discount text
- Fix displaying of sale banner

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-10 21:16 UTC, elliottprogrammer requested changes
Unfortunately, in mobile view there are a couple of issues:

1. The top heading is cut off. It should say, "Best in-class products for your Jetpack site", but all we can see is, "products for your Jetpack site."
2. After clicking the mobile Menu icon, the menu jumps up toward the top, covering up the Menu icon, therefore there is no way to get out of the menu at that point (unless you press the escape key, but I don't think that is possible on a mobile device. We're now stuck in the menu with no way of seeing any page content.  The only way to close the menu (get un-trapped) is to either click a Menu link or refresh the page.

2023-11-13 11:02 UTC, robertsreberski commented
@elliottprogrammer ahh, thanks for spotting that 🤦‍♂️ indeed, that's a big issue. The commit I just pushed should solve it!

2023-11-13 11:11 UTC, robertsreberski commented
BTW, I updated coupon code to the production one already. To test this PR you need to update it to the test one manually as per updated instructions here: D128241-code

2023-11-13 14:56 UTC, elliottprogrammer approved these changes
Tested, everything seems to work excellent now!  Code looks good, I don't see any issues. Nice! 🙌
LGTM! 👍

2023-11-14 08:26 UTC, merged