Themes Showcase: Remove upgrade to premium banner
Automattic/wp-calypso pull request #84285
Opened 2023-11-17 10:39 UTC by rcrdortiz

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-23 15:51 UTC, BogdanUngureanu commented on client/my-sites/themes/single-site-wpcom.jsx
> +		if ( isEnabled( 'themes/premium' ) ) {
Any reason why are using this `if` since both branches use the same Upsellnudge with the same props? 🤔

2023-11-23 15:52 UTC, BogdanUngureanu requested changes
I think the code can be simplified a bit more. :)

2023-11-24 09:40 UTC, BogdanUngureanu commented
The upgrade to premium banner is removed. However, looks like the upload themes one contains a few logic errors:
- We only display the banner on Premium with a yearly subscription (we don't display it on monthly plans or 2-y plans)
- Looks like we try to display the banner in Jetpack Calypso (since `isEnabled` is a feature flag enabled only on Calypso blue - WPCOm)

It's not blocking us, since it was like that before, but I think we should create a follow up PR for this.

To simplify things, I think we can use the `siteHasFeature( FEATURE_UPLOAD_THEMES ) ` function that would remove the tight coupling to plans.

2023-11-24 09:40 UTC, BogdanUngureanu approved these changes

2023-11-24 09:50 UTC, rcrdortiz commented
> It's not blocking us, since it was like that before, but I think we should create a follow-up PR for this.

Added a bug draft to our board with this.

2023-11-24 09:52 UTC, merged

2023-11-24 10:00 UTC, BogdanUngureanu commented
cc @victorespigares Just want to let you know that we've removed the premium theme upsell from the /themes page.