Add reviews trigger button
Automattic/wp-calypso pull request #84506
Opened 2023-11-24 11:38 UTC by gcsecsey

Related to #

## Proposed Changes

* add the `marketplace-reviews-show` feature flag
* add the trigger button with the number of reviews
* only show the button when the feature flag is enabled 

## Testing Instructions

* Visit a plugin that already has reviews, etc. `/plugins/woocommerce-bookings`
* Check that the button is rendered on the page
* Disable the feature flag, by adding the `?flags=-marketplace-reviews-show` param to the URL
* Refresh the page and check that the button is not rendered anymore
* Enable the feature flag again, by adding the `?flags=marketplace-reviews-show` param to the URL
* Visit a plugin page that has no reviews
* Check that the button is not rendered on the page

| `marketplace-reviews-show` feature flag | `numberOfReviews` > 0 | Result |
|--------|--------|--------|
| `true` | `true`| ![CleanShot 2023-11-24 at 11 36 33@2x](https://github.com/Automattic/wp-calypso/assets/11555574/dc0a2071-2d8c-41b6-b1cd-bed5fa00844a) |
| `true` | `false` | ![CleanShot 2023-11-24 at 11 37 10@2x](https://github.com/Automattic/wp-calypso/assets/11555574/cb98de7a-29a8-4fdb-891c-c153ba817547) |
| `false` | `true` | ![CleanShot 2023-11-24 at 11 36 21@2x](https://github.com/Automattic/wp-calypso/assets/11555574/77978b7d-123b-421a-a838-dcbf8207cc14) | 
| `false` | `false` | ![CleanShot 2023-11-24 at 11 37 10@2x](https://github.com/Automattic/wp-calypso/assets/11555574/cb98de7a-29a8-4fdb-891c-c153ba817547) | 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-25 16:57 UTC, WBerredo requested changes
I've added some comments below but other than that I was able to reproduce the testing instructions and everything seems good.

---

On a more visual note, I think the font-size is a  little too big here (its inheriting `16px`), I would say `12px` would be more appropriate.

On a more nitpicky note, maybe it would be better placed next to the reviews, but I'm not sure how responsiveness would work in this case.

![CleanShot 2023-11-25 at 12 53 09@2x](https://github.com/Automattic/wp-calypso/assets/5039531/536ef8f5-a54b-4f69-afac-41b9aa8764a0)

2023-11-25 16:57 UTC, WBerredo commented on config/development.json
> +		"marketplace-reviews-show": true,
I've created a PR adding this flag: https://github.com/Automattic/wp-calypso/pull/84524

The only differences are its encapsulated on its own PR and its added on all relevant files (stage, production). 

Maybe we should use the other PR as base for this one.

2023-11-25 16:57 UTC, WBerredo commented on client/my-sites/plugins/plugin-details-header/index.jsx
> +								<Button borderless className="is-link">
I think we can use `isLink` property instead of adding the className for this.

2023-11-27 13:53 UTC, WBerredo commented on config/development.json
> +		"marketplace-reviews-show": true,
After the merge of https://github.com/Automattic/wp-calypso/pull/84524, I rebased the current PR with trunk.

2023-11-27 14:51 UTC, WBerredo commented on client/my-sites/plugins/plugin-details-header/index.jsx
> +								<Button borderless className="is-link">
They are actually not equivalent, sorry

2023-11-27 15:26 UTC, WBerredo approved these changes
LGTM! But I would wait an additional approval as I worked on it :)

2023-11-27 19:24 UTC, epeicher approved these changes
I have tested it, and it works as advertised. Changes LGTM! 🚢

2023-11-28 13:52 UTC, merged

2023-11-28 14:21 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9771350

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @gcsecsey for including a screenshot in the description! This is really helpful for our translators.

2023-12-07 20:43 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9771350).