Import flow: Redesign the capture screen
Automattic/wp-calypso pull request #84571
Opened 2023-11-27 18:49 UTC by bogiii

Related to https://github.com/Automattic/wp-calypso/issues/84569

## Proposed Changes

* Redesign the Capture step following [the Figma design](https://www.figma.com/file/Qk6oQI6SxPhh7FyngXVnAV/Migrate-from-Site-Backups?type=design&node-id=1950%3A12164&mode=design&t=xyHdYqzVOKuKF7Hq-1)

## Testing Instructions

* Go to `/setup/import-focused?siteSlug={SLUG}`
* Check if the capture screen is matched with Figma design

<img width="682" alt="Screenshot 2023-11-27 at 19 49 01" src="https://github.com/Automattic/wp-calypso/assets/1241413/a922d422-6d49-4a7e-8473-0a0f3776e0c2">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-11-28 07:05 UTC, ouikhuan requested changes
Looks good to me but we'll have to change the text in e2e flows because it's currently broken. It was looking for `don't have a site address` but it's `choose a content platform` now. See https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/lib/flows/start-import-flow.ts#L8

2023-11-28 09:50 UTC, ouikhuan approved these changes
LGTM 🚢

2023-11-28 11:06 UTC, merged

2023-11-28 13:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9771045

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

2023-12-07 20:43 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9771045).