Hosting Command Palette: Rank current site at the top
Automattic/wp-calypso pull request #84726
Opened 2023-11-30 22:50 UTC by danielbachhuber

Fixes https://github.com/Automattic/dotcom-forge/issues/4710

## Proposed Changes

Puts the current site at the top of the site list when using the command palette within an existing site context.

![CleanShot 2023-11-30 at 14 48 49@2x](https://github.com/Automattic/wp-calypso/assets/36432/8c80acc1-a788-4106-86a7-5668525b1ad1)

## Testing Instructions

1. Navigate to `/sites`.
2. Open the command palette, select 'Manage hosting configuration', and verify the site list matches your expected site order.
3. Navigate to Hosting Configuration for one of your sites.
4. Open the command palette, select 'Manage writing settings', and verify the current site appears at the top of the site list.

2023-12-01 08:54 UTC, katinthehatsite approved these changes
Nice work - it works as expected. If the command is available for a site and you are in the site content, the selected site will display as the first one in the nexted command.

2023-12-01 09:33 UTC, sejas requested changes
For me it ranks the current site to the top even if I'm on `/sites` page.

<img width="1396" alt="Screenshot 2023-12-01 at 10 28 48" src="https://github.com/Automattic/wp-calypso/assets/779993/ea4c0554-a52c-4a13-8e8f-abacdcdb753b">

2023-12-01 09:56 UTC, katinthehatsite commented
> For me it ranks the current site to the top even if I'm on `/sites` page.
> 
> <img alt="Screenshot 2023-12-01 at 10 28 48" width="1396" src="https://private-user-images.githubusercontent.com/779993/287222914-ea4c0554-a52c-4a13-8e8f-abacdcdb753b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjQ3NzQsIm5iZiI6MTcwMTQyNDQ3NCwicGF0aCI6Ii83Nzk5OTMvMjg3MjIyOTE0LWVhNGMwNTU0LWE1MmMtNGExMy04ZThmLWFiYWNkY2RiNzUzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwOTU0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWIyM2YwNGZiZGU2NmRiMTY4ZTBjNWVmOTQxZGFjYmY2ZmMyZGU4YzEyYTdiYjY4YTQ2NmY1ZTUyNDA5YWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rRs61AGYndlRJVhyvj-nIzbvvWQZ0IX8_cDhfn5A8UU">

Oh interesting, I am not sure why it did not rank it for me. I am wondering if perhaps the site I was testing with was already the first one in my site's list on the `/sites` page ...

2023-12-01 09:59 UTC, sejas reviewed
There is a bug that makes disappear the current site.

https://github.com/Automattic/wp-calypso/assets/779993/acf55668-0b04-4e6c-b696-259484bb8e28

**Steps to reproduce**
1. Navigate to a `/hosting-config/$siteSlug`
2. Open the command palette
3. Find a command like `Add new user`
4. Cancel by pressing `esc` or `backspace` to see all the root commands
5. Find a second command, it can be the same `Add new user`
6. Observe that your current site is gone from the list.

2023-12-01 10:01 UTC, sejas commented
> Oh interesting, I am not sure why it did not rank it for me. I am wondering if perhaps the site I was testing with was already the first one in my site's list on the /sites page ...

I think Calypso live loaded directly `/sites` and you didn't have a "current/selected" site the first time you accessed.

2023-12-01 10:44 UTC, sejas approved these changes
I fixed the bug by removing the `splice` , which was modifying the original `sortedSites` array. https://github.com/Automattic/wp-calypso/pull/84726/commits/b6a7f4120c3996275288967de04fee49cfa81714

Working as expected. Thanks for the PR!

## Screencast


https://github.com/Automattic/wp-calypso/assets/779993/2c41b01f-0188-4fa2-b432-6b143f1af0e7

2023-12-01 11:23 UTC, merged

2023-12-01 11:48 UTC, danielbachhuber commented
@sejas Thanks for the fix!

2023-12-01 12:53 UTC, danielbachhuber commented on client/components/command-palette/use-current-site-rank-top.ts
> +		currentPath.startsWith( '/me' )
@sejas This list seems like a pain to maintain.

Instead, I think we should only return `currentSiteId` if there's a `:site` in the matched route.

What do you think?

2023-12-04 18:10 UTC, sejas commented on client/components/command-palette/use-current-site-rank-top.ts
> +		currentPath.startsWith( '/me' )
- Created a PR here https://github.com/Automattic/wp-calypso/pull/84829 👌