GF Signup: Mobile sticky for dropdown and other cosmetic fixes and refactors
Automattic/wp-calypso pull request #85158
Opened 2023-12-12 16:29 UTC by jdc91

- Related https://github.com/Automattic/growth-foundations/issues/296

## Proposed Changes

- Introduces the a sticky dropdown for mobile based screens
- Externalises the config flag as an external prop to the grid
- Fix styling issues 

https://github.com/Automattic/wp-calypso/assets/3422709/5eebca67-8bca-4d2b-a197-60da6ef475b7

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-12-13 08:01 UTC, chriskmnds requested changes
Some concerns with the implementation. A few more bits I noticed, but these main ones I'd appreciate if addressed.

2023-12-13 08:01 UTC, chriskmnds commented on client/my-sites/plans-grid/components/comparison-grid/index.tsx
> +						isDropDownExperimentActive && isMobile() ? stickyRowOffset + 48 : stickyRowOffset
I don't think this should happen here. It's based on external context and should probably be passed into the grid as the offset value.

Also use of `isMobile` feels incorrect - here and elsewhere. Better use the mixins to align with the rest for now.

2023-12-13 08:01 UTC, chriskmnds commented on client/my-sites/plans-grid/components/plan-type-selector/components/interval-type-dropdown.tsx
> +		z-index: 2;
Let's add a comment on each of these z-index values. Why 2?

2023-12-13 08:01 UTC, chriskmnds commented on client/my-sites/plans-grid/components/plan-type-selector/components/interval-type-dropdown.tsx
> +				<StickyDropdown
Is this something we couldn't reuse (and extend if needed) the existing `StickyContainer` logic/component?

In reference to the entire logic in this file obviously, which is largely replicated. We should always strive for reusable parts, more so here that we are trying to reduce existing complexities.

2023-12-13 14:52 UTC, ddc22 commented
@chriskmnds Thanks for the feedback I agree with all your points. This implementation was a bit rushed due to my AFK. So I code quality suffered a bit since I didn't get a chance to do a hygiene check. 

Hopefully whoever carry this forward, (Or just plain drops this PR and pick it up from scratch) can get some value from this dirty implementation :).

### Can we Reuse StickyContainer?

This was my initial approach but due to my lack of familiarity with the concept I went back on it to do it from scratch (as a learning exercise). It will take a bit more effort but reuse of StickyContainer is definitely possible. And the comments that I included on the current implementation should help whoever takes over.

2023-12-13 14:59 UTC, ddc22 commented on client/my-sites/plans-grid/components/comparison-grid/index.tsx
> +						isDropDownExperimentActive && isMobile() ? stickyRowOffset + 48 : stickyRowOffset
Ah right I just did a simple search for isMobile and saw it used inside `plans-grid`, hence, thought it might be permissible to use here. Again yes probably should have done a hygiene check here.

2023-12-13 15:00 UTC, ddc22 commented on client/my-sites/plans-grid/components/plan-type-selector/components/interval-type-dropdown.tsx
> +		z-index: 2;
For whoever who takes over. Z indexes in this implementation are fighting to take over the sticky header of the features grid and comparison grid.

2023-12-13 15:00 UTC, ddc22 commented on client/my-sites/plans-grid/components/plan-type-selector/components/interval-type-dropdown.tsx
> +				<StickyDropdown
Answered below :)

2023-12-19 00:50 UTC, jeyip commented
Starting to shepherd this PR now ( or will start from scratch while reusing the StickyContainer after I get a better sense of the work that's been done )

2023-12-19 06:43 UTC, chriskmnds commented
> Starting to shepherd this PR now ( or will start from scratch while reusing the StickyContainer after I get a better sense of the work that's been done )

Yep, I think that should be priority one from what I gathered. I think also worth considering whether "stickiness" should even be part of the term-toggle itself and not something that `plans-features-main` imports and wraps the component with. If we're only intending to make it sticky in Calypso (signup & admin), then it might just be easier to import `StickyContainer` in `plans-features-main` and wrap the toggle with it. 🤔

2023-12-23 02:22 UTC, jeyip commented
Closing in favor of https://github.com/Automattic/wp-calypso/pull/85520

2023-12-23 02:22 UTC, closed without merging