Domains: Show domain as expiring on Domains page when auto-renewal is disabled
Automattic/wp-calypso pull request #85240
Opened 2023-12-13 17:56 UTC by stephanethomas

## Proposed Changes

This pull request seeks to provide more accurate information in the `Domains` page by showing `Expires` instead of `Renews` for any domain with auto-renewal disabled. It also fixes a typo in a component name.

Before | After
------ | -----
IMG | IMG

## Testing Instructions

2023-12-13 18:56 UTC, delputnam approved these changes
Nice update. Thank you! Works as expected for me.

2023-12-14 09:16 UTC, stephanethomas commented on packages/data-stores/src/queries/use-all-domains-query.ts
> +	| 'wpcom_domain'
Putting aside the new `auto_renewing` attribute, I've just reordered that list so it is easier to scan.

2023-12-14 16:36 UTC, nightnei requested changes
It works good on path `http://calypso.localhost:3000/domains/manage/nightnei.blog`:
<img width="1148" alt="Screenshot 2023-12-14 at 16 33 34" src="https://github.com/Automattic/wp-calypso/assets/5598437/650afdd6-6cf2-487d-919e-575b0e934e05">
<img width="1545" alt="Screenshot 2023-12-14 at 16 34 03" src="https://github.com/Automattic/wp-calypso/assets/5598437/4215ca10-9165-496a-a0a2-35fdf1dc7742">

But it works incorrectly here: `http://calypso.localhost:3000/domains/manage`
Always I see "Expires":
<img width="1545" alt="Screenshot 2023-12-14 at 16 34 57" src="https://github.com/Automattic/wp-calypso/assets/5598437/df9a574d-e18f-4858-9473-45f60606a2c4">
<img width="1545" alt="Screenshot 2023-12-14 at 16 35 32" src="https://github.com/Automattic/wp-calypso/assets/5598437/6e48d25f-8ab6-4cb6-8cd5-3b3eb95a92ca">

2023-12-18 16:54 UTC, stephanethomas commented
> But it works incorrectly here: `http://calypso.localhost:3000/domains/manage` Always I see "Expires"

Good catch! It indeed looks like we only query the following endpoint for that view:

```
https://public-api.wordpress.com/rest/v1.1/all-domains?no_wpcom=true&http_envelope=1
```
Which only returns partial data that doesn't contain the `auto_renewing` field:

```json
{
    "domain": "example-titan-yearly.com",
    "blog_id": 61448309,
    "blog_name": "example",
    "type": "mapping",
    "is_domain_only_site": false,
    "is_wpcom_staging_domain": false,
    "has_registration": true,
    "registration_date": "2022-01-03T14:50:27+00:00",
    "expiry": "2024-01-03T00:00:00+00:00",
    "wpcom_domain": false,
    "current_user_is_owner": true,
    "site_slug": "example.wordpress.com"
}
```

The site specific endpoint does provide that information though:

```
https://public-api.wordpress.com/rest/v1.2/sites/61448309/domains?http_envelope=1
```

As far I can see, we would have to update the `all-domains` API endpoint. I'm worried that surfacing this parameter may introduce performance issues though but I'll have a look tomorrow. @delputnam, what do you think of that approach?

2023-12-18 17:27 UTC, stephanethomas commented
I didn't want to wait until tomorrow, so I went ahead and created `D132406-code` to update the API. This is a good for another review 🙂.

2023-12-20 12:31 UTC, nightnei approved these changes
This PR LGTM and works well, only necessary to fix one exception for backend D132406-code

2023-12-21 13:42 UTC, merged

2023-12-21 14:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10444071

Thank you @stephanethomas for including a screenshot in the description! This is really helpful for our translators.

2024-02-23 12:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10444071).