Assembler First Flow: Allow people to choose the wordpress.com domain
Automattic/wp-calypso pull request #85277
Opened 2023-12-14 09:41 UTC by arthur791004

Related to pekYwv-3vI-p2#comment-2714

## Proposed Changes

* On the Domain screen, allow users to choose another `*.wordpress.com` domain
* On the Launchpad screen, don't show the `Upgrade plan` badge on the “Choose a domain” task

## Testing Instructions

* Go to /setup/assembler-first
* Create a new site
* Finish the Assembler screen
* Exit the Site Editor
* On the Launchpad screen, make sure you won't see the `Upgrade plan` badge on the “Choose a domain” task
* Pick the “Choose a domain” task, and make sure you can see the `*.wordpress.com` domain
* Select the domain, and make sure the domain of your site changed successfully

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-12-15 02:01 UTC, lsl reviewed
To use the domains step or more specifically: `requestSiteAddressChange` in a launchpad step you need to make sure every launchpad step you're using uses `siteId` otherwise you run into issues if the user uses the back button and lands on a url with a site slug no longer valid.

See my note here https://github.com/Automattic/dotcom-forge/issues/4582#issuecomment-1842109902

And the PR where we swapped blogger onboarding to use site id during the launchpad step: https://github.com/Automattic/wp-calypso/pull/84532

Looking at the steps you have it's probably as simple as adding isSiteAssemblerFlow to this line and similar:

https://github.com/Automattic/wp-calypso/pull/84532/files?w=1#diff-1af91985184f6d7b895325749a29ebd09bd8f1e4a570a3fa86cc9fb892416c3fR150

I limited them to the blog onboarding flow because we were pressed for testing time but maybe this could be done for all launchpad flows?

2023-12-15 02:23 UTC, fushar commented
Looks like the domain selection task is not completed after I choose a free domain. See:

https://github.com/Automattic/wp-calypso/assets/1525580/4cad8a50-4688-49bb-a655-fa6df28ce4a4

2023-12-15 02:25 UTC, fushar requested changes
When entering the flow the second time, and click "Start a new site", it results in irrecoverable error! Cannot reproduce this in production.

<img width="994" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/ea99c432-6c66-4dac-8774-83d957b55255">

2023-12-18 06:59 UTC, arthur791004 commented
> When entering the flow the second time, and click "Start a new site", it results in irrecoverable error! Cannot reproduce this in production.

@fushar It should be fixed by https://github.com/Automattic/wp-calypso/pull/85286. The reason is we use the site title from the onboarding store to create a new site. If we don't clear the data after the site creation, we will use the same value to create a new site and the error will be thrown. Hence, that PR resets the data of the onboarding store to resolve this issue.

2023-12-18 10:21 UTC, fushar approved these changes
Works fine for our Assembler-First flow.

But I'm not that confident about the possible effect of this PR in other flow... 🥲 Maybe we should ask other team.

2023-12-18 10:22 UTC, fushar commented
Also, it feels really weird that in Stepper framework the "steps" need to know which "flow" it is in (`isSiteAssemblerFlow()`, `isBlogOnboardingFlow()` etc). I know we're just following the existing pattern though 😄 .

2023-12-18 10:33 UTC, arthur791004 commented
@lsl Is it possible to replace the site slug with the new one? Or may the new one still be unavailable at this moment?

2023-12-19 08:48 UTC, merged

2023-12-20 00:22 UTC, lsl commented
> Is it possible to replace the site slug with the new one? Or may the new one still be unavailable at this moment?

This is what we previously did in the domains step, the issue is that then if the user uses the browser back button to choose a different domain (or change site name or whatever), the old slug will be in the url, at this point nothing works because it tries to save data against a non existent site slug.

2023-12-20 03:21 UTC, arthur791004 commented
Oh yes 🥲