Add StatsUpsellModal
Automattic/wp-calypso pull request #85457
Opened 2023-12-19 06:20 UTC by lsl

Fixes https://github.com/Automattic/dotcom-forge/issues/4911

## Proposed Changes

* Adds the StatsUpsellModal

## Testing Instructions

* Click on a stats specific upgrade button under /stats

Todo:
- [ ] Fix plan pricing and localization
- [ ] Localized currency font size needs reducing to match figma
- [ ] Check tracks events are firing right
- [ ] Check checkout link redirect to works and ideally update it to go back to the current path instead of just /stats/day/:site

Doing in follow up prs:
- [ ] Use it for the download csv button
- [ ] Use it for the banner button

![Screenshot 2023-12-19 at 17-05-08 Jetpack Stats ‹ Site Title — WordPress com](https://github.com/Automattic/wp-calypso/assets/811776/f06e6006-17a9-4b30-a26a-ecd823320b51)

2023-12-19 06:21 UTC, lsl commented on client/my-sites/stats/stats-upsell-modal/index.tsx
> +			__experimentalHideHeader={ true }
Needed to use this in order to match the design / avoid this header section:

![Screenshot 2023-12-19 at 14-39-06 Jetpack Stats ‹ Site Title — WordPress com](https://github.com/Automattic/wp-calypso/assets/811776/1a88bfeb-9d1a-484c-abe4-ce56987cfcf3)

2023-12-19 08:32 UTC, crisbusquets commented
Hi @lsl,
How should I test this? I couldn't trigger the modal using the Calypso.live links. Or should I wait? :)

2023-12-20 01:49 UTC, lsl commented
@crisbusquets Sorry, meant to mention the config flag. Testing instructions updated.

2023-12-20 15:28 UTC, crisbusquets commented
> Calypso Live [(direct link)](https://calypso.live?image=registry.a8c.com/calypso/app:build-91909)
> Jetpack Cloud live [(direct link)](https://calypso.live?image=registry.a8c.com/calypso/app:build-91909&env=jetpack)

Thanks @lsl !

There are a few things that need adjustments compared to Figma:
* Modal width: 700px instead of 860px
* Line-height for the heading should be 40px (instead of 48px)
* Checkmark icon, 18x18 instead of 24x24

2023-12-20 18:47 UTC, allilevine commented
@lsl Adding Cris' comment from Slack:

> what about adding this last item to the list (All Explorer plan features)?

p1703089221518989/1703086267.795209-slack-C068X5XJT3J

2023-12-20 23:49 UTC, lsl commented
> There are a few things that need adjustments compared to Figma:

Done

> what about adding this last item to the list (All Explorer plan features)?

Done

@crisbusquets any idea why the currency font seems bigger here than on figma? I think I got the sizing right but it looks noticeably larger. I also had to center the line vertically as aligning to the top made it misaligned.

2023-12-21 10:46 UTC, candy02058912 reviewed
This is what the modal looks like on smaller screen sizes
medium-sized (is that how I call this?)
![mobile-modal](https://github.com/Automattic/wp-calypso/assets/6586048/f6659a7a-a44f-46d5-9bd5-4528258196e8)

small-sized
![mobile](https://github.com/Automattic/wp-calypso/assets/6586048/fa27c4e5-fd1a-45ce-a7dc-938ad1215f5e)

I think we need a design review from @crisbusquets, but it won't be blocking this PR since it's all behind a feature flag.

2023-12-21 10:51 UTC, candy02058912 commented on client/my-sites/stats/stats-upsell-modal/index.tsx
> +							dangerouslySetInnerHTML={ { __html: planMonthly?.product_display_price ?? '' } }
Haven't played with code too much yet, am curious why we're using `dangerouslySetInnerHTML` here?

2023-12-21 10:58 UTC, candy02058912 commented on client/my-sites/stats/stats-upsell-modal/index.tsx
> +						<div className="stats-upsell-modal__feature">
Seeing a couple of these `stats-upsell-modal__feature` being repeated, what do you think about mapping through them, for example:
```
const features = [
  { key: 'all_stats', text: 'All stats available: traffic trends, sources, optimal time to post…' },
  // ...
];
```
And then:
```
{features.map((feature) => (
  <div key={feature.key} className="stats-upsell-modal__feature">
    <Gridicon icon="checkmark" size={18} />
    <div className="stats-upsell-modal__feature-text">{translate(feature.text)}</div>
  </div>
))}
```

2023-12-21 11:05 UTC, crisbusquets commented
> This is what the modal looks like on smaller screen sizes medium-sized (is that how I call this?) ![mobile-modal](https://private-user-images.githubusercontent.com/6586048/292178024-f6659a7a-a44f-46d5-9bd5-4528258196e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTY5NDYsIm5iZiI6MTcwMzE1NjY0NiwicGF0aCI6Ii82NTg2MDQ4LzI5MjE3ODAyNC1mNjY1OWE3YS1hNDRmLTQ2ZDUtOWJkNS00NTI4MjU4MTk2ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTEwNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQzZWQzZjgxM2E1ZGJlYTI3OGE3YWYzZGQxNDAwNjZhYjMzYjkxMGIyZDcxOGNiNTRiMjkwNzdjMTZkNTM5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AaGEdgMDi9AKT0t4q8rQkeO5wDun00NzjX8fhv2BwG0)
> 
> small-sized ![mobile](https://private-user-images.githubusercontent.com/6586048/292178155-fa27c4e5-fd1a-45ce-a7dc-938ad1215f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTY5NDYsIm5iZiI6MTcwMzE1NjY0NiwicGF0aCI6Ii82NTg2MDQ4LzI5MjE3ODE1NS1mYTI3YzRlNS1mZDFhLTQ1Y2UtYTdkYy05MzhhZDEyMTVmNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTEwNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM1MThmOWEwYWYwNzExYjQ2NDRkZjgzN2FiMGI4YmE1ZDE4OTg5MWM5ZTU0MTdiNDBhYWZhYmI4NmEwNTM5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g428N4Em27KYjzvtn6OIvkBclzz5YciGDGJMWjHOptA)
> 
> I think we need a design review from @crisbusquets, but it won't be blocking this PR since it's all behind a feature flag.

I'll work on this, @candy02058912. And share a proposal asap.

2023-12-21 11:07 UTC, candy02058912 commented on client/my-sites/stats/stats-upsell-modal/index.tsx
> +		recordTracksEvent( 'stats_upsell_modal_submit', {
This was not tracked.

2023-12-21 11:13 UTC, candy02058912 requested changes, later dismissed
Only blocking change is the Tracks event name

2023-12-21 11:25 UTC, crisbusquets commented
About the responsiveness of the modal:

If it's **mobile**, we could use this approach (in this example, I'm using a 375px width):
* The change is in the layout (vertical instead of horizontal), margins (32px instead of 40px), and heading font size (28px instead of 32px).

* Figma file: swECLCmqZdAXDKUjGtPa8A-fi-397_9258
* Figma specs: swECLCmqZdAXDKUjGtPa8A-fi-397_9910

![mobile](https://github.com/Automattic/wp-calypso/assets/25607244/69b5210b-f6d3-4bc1-9aab-0bdc3f9aa04a)

The modal for desktop should work even on small **tablets** (768px width):
![tablet](https://github.com/Automattic/wp-calypso/assets/25607244/ed8b1d50-0c1d-4b90-94b6-9c1f02abac1c)

2023-12-21 23:58 UTC, lsl commented
Mobile design looks good, I'll do in a follow up, issue here https://github.com/Automattic/dotcom-forge/issues/5008

2023-12-22 00:54 UTC, lsl commented
Bumped sizelimit since it was blocking the build, not sure if these sizes are hard limits or just a warning system for accidental blow outs. See https://github.com/Automattic/wp-calypso/pull/76914 for context, cc @jsnmoon

2023-12-22 02:20 UTC, merged

2023-12-22 03:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10461415

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @lsl for including a screenshot in the description! This is really helpful for our translators.

2023-12-24 21:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10461415).