Help Center: Add current page url to search query mapping
Automattic/wp-calypso pull request #85487
Opened 2023-12-19 14:31 UTC by agrullon95

Related to pdm0RZ-L3-p2

## Proposed Changes

Created a new hook that will map the current page URL to a search query. This will give users relevant search results in the Help Center whenever they navigate to a page that is in the mapping JSON file.

## Testing Instructions

* Checkout branch.
* Sandbox public API and test site.
* Navigate to `cd apps/editing-toolkit` and run `yarn dev --sync`.
* Load Calypso, open the help center, and navigate through all the links to test the different search query mappings.
* Ensure mappings are working for /wp-admin based pages (if specified in JSON).
* Ensure mappings are working in gutenberg editor (if specified in JSON).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2023-12-19 15:37 UTC, alshakero requested changes
Opening the Help Center in my home kills the page.

2023-12-19 16:42 UTC, alshakero approved these changes
Tested in wp admin and Calypso. Beautiful and works perfect.

2023-12-19 16:42 UTC, alshakero commented on packages/help-center/src/hooks/use-current-page-search-mapping.tsx
> +				break;
```suggestion
				return currentPageSearchMapping[ key as keyof typeof currentPageSearchMapping ];
```

2023-12-19 16:47 UTC, merged

2024-01-10 05:38 UTC, donalirl commented on packages/help-center/src/route-to-query-mapping.json
> +	"/stats/": "statistics",
Replace current suggestions with: 

https://wordpress.com/support/stats/
https://wordpress.com/support/stats/understand-your-sites-traffic/
https://wordpress.com/support/stats/learn-insights-about-your-website/
https://wordpress.com/support/google-analytics/
https://wordpress.com/support/getting-more-views-and-traffic/