Google My Business: Update Strings to Google Business Profile
Automattic/wp-calypso pull request #86301
Opened 2024-01-11 14:28 UTC by Aurorum

Fixes #84970

## Proposed Changes

* Replaces "Google My Business" with "Google Business Profile" for users following Google's rebranding of the service 

I've only touched translatable strings because I don't want to mess up any actual code, and I don't want to mess up any analytics either. But also, it seems that's what happens in Calypso when other services are renamed (eg. Twitter) so I don't think that's a problem - let me know if it should be changed though!  

Only other thing that needs updating is the endpoints `/connections` and `/external-services`, which I don't think I can do. 

## Testing Instructions

Should be a case of making sure the code looks sane since it's only strings, and confirming that the strings are updated on Calypso. 

<img width="1076" alt="Screenshot 2024-01-11 at 14 23 00" src="https://github.com/Automattic/wp-calypso/assets/43215253/7431e139-c104-4bde-b738-5c8043c2a6c7">

cc @stephanethomas @creativecoder

2024-01-14 23:23 UTC, creativecoder approved these changes
Thanks @Aurorum for the update!

I found a couple additional strings that seemed good to change, and added them in https://github.com/Automattic/wp-calypso/pull/86301/commits/6e14ebb11a1628efbbcad3e51990686b322c27dc

I personally haven't touched this feature in a long time, but these changes look good to me.

2024-02-21 03:48 UTC, olaseni requested changes
As mentioned in a comment, let's make changes to the title properties where analytics is concerned. The path property is still retained, so analytics is only partially impacted. Those pages don't receive a lot of views anyway.

We should also be good to make changes in comments, like in this [utils.js.](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/google-my-business/utils.js#L7), or in this [test unit file](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/data-layer/wpcom/sites/stats/google-my-business/test/index.js)

2024-02-21 03:48 UTC, olaseni commented on client/my-sites/google-my-business/new-account/index.js
>  				<PageViewTracker path="/google-my-business/new/:site" title="Google My Business > New" />
```suggestion
				<PageViewTracker path="/google-my-business/new/:site" title="Google Business Profile > New" />
```

I think we are fine to refactor the `PageViewTracker` title. The last I checked those paths are rarely viewed anyway.

2024-02-21 18:07 UTC, Aurorum commented on client/my-sites/google-my-business/new-account/index.js
>  				<PageViewTracker path="/google-my-business/new/:site" title="Google My Business > New" />
All done - thanks for taking a look! :)

2024-02-23 13:13 UTC, olaseni approved these changes
Thanks @Aurorum. The changes look good!

2024-02-27 11:07 UTC, merged

2024-02-27 13:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11481870

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

2024-03-01 21:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11481870).