Enable tracker init to re-run during runtime
Automattic/wp-calypso pull request #86306
Opened 2024-01-11 17:42 UTC by robertsreberski

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2024-01-12 16:49 UTC, CodeyGuyDylan requested changes
I tried the testing instructions a couple of times and I am consistently getting this error message along with these console errors
![image](https://github.com/Automattic/wp-calypso/assets/65001528/91b967f0-7348-4c6b-829e-5237a666f5e8)

2024-01-15 19:17 UTC, robertsreberski commented
@CodeyGuyDylan these issues are not related to each other.

As for the error message you see on the front end. It might be due to an issue with saving user information about "Do Not Sell" setting - which was introduced by this PR (https://github.com/Automattic/wp-calypso/pull/73107). We might need to address it as a potential bug.

As for the second issue. the error stands as "ERR_BLOCKED_BY_CLIENT". Are you sure you're not using any ad blockers, or the browser that blocks trackers by default? If I test the PR via the Calypso Live link, I don't get these console logs.

Thanks for checking out the PR and let me know!

2024-01-15 19:59 UTC, CodeyGuyDylan commented
> As for the error message you see on the front end. It might be due to an issue with saving user information about "Do Not Sell" setting - which was introduced by this PR (https://github.com/Automattic/wp-calypso/pull/73107). We might need to address it as a potential bug.

Interesting, so we can ignore it for this PR?

> As for the second issue. the error stands as "ERR_BLOCKED_BY_CLIENT". Are you sure you're not using any ad blockers, or the browser that blocks trackers by default? If I test the PR via the Calypso Live link, I don't get these console logs.

That was the issue 🤦🏻 . I have the blocker permanently disabled for checkout, but I was using the calypso live link and that was not whitelisted

2024-01-15 19:59 UTC, CodeyGuyDylan approved these changes
LGMT other than that non-related error when accepting the cookies

2024-01-15 20:03 UTC, robertsreberski commented
thanks @CodeyGuyDylan !

> Interesting, so we can ignore it for this PR?

I've created a separate maintenance issue for this: https://github.com/Automattic/jetpack-marketing/issues/506

2024-01-15 20:06 UTC, merged