Membership Coupons: Adjust character limit for coupons, add error for out of limit entries
Automattic/wp-calypso pull request #86669
Opened 2024-01-19 20:19 UTC by chrisfromthelc

Fixes: https://github.com/Automattic/gold/issues/292

## Proposed Changes

This patch should increase the memberships coupon length from 10 to 20 characters. It also adjusts the validation so that a message noting the valid range of the coupon is shown, as well as prevents form submission outside of that range.

## Testing Instructions

1. First, patch D135376-code to your sandbox.
2. Patch this diff or use the Calypso Live link.
3. Navigate to `/earn/payments/SITE_URL`
4. Attempt to add a coupon. Note that when entering text in the coupon code field, an entry less than 3 characters or attempting to enter more than 20 will result in a message "Coupon codes must be between 3 and 20 characters".
5. Enter two characters, and click into the Amount box and enter a number. The Save button should remain inactive.
6. Enter between 3 and 20 characters, and the Save button should be active. Try saving the coupon; it should successfully save.
7. You can also try reverting D135376-code and attempting the above steps; anything over 10 characters should trigger a 400 error.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2024-01-19 22:19 UTC, chrismccluskey commented on client/my-sites/earn/components/form-text-input-with-value-generation/index.tsx
> +				onCharacterLimitReached( true );
I think we want this to be `false`

2024-01-19 22:21 UTC, chrismccluskey requested changes
Looks good. I think I found a logic error but pretty easy to fix.

2024-01-19 22:21 UTC, chrismccluskey commented on client/my-sites/earn/components/form-text-input-with-value-generation/index.tsx
> +				onCharacterLimitReached( true );
I think we want this to be `false`.

2024-01-19 22:21 UTC, chrismccluskey commented on client/my-sites/earn/components/form-text-input-with-value-generation/index.tsx
> +				onCharacterLimitReached( false );
I think we want this to be `true`.

2024-01-22 22:16 UTC, chrismccluskey approved these changes
LGTM and works as expected!

2024-01-22 22:35 UTC, merged

2024-01-23 01:17 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10966939

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @chrisfromthelc, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Coupon codes must be at least 3 characters`
- `The coupon code maximum length of 20 characters has been reached`

Thank you in advance!

2024-01-26 11:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10966939).