ExPlat: Remove old A/A test
Automattic/wp-calypso pull request #86668
Opened 2024-01-19 19:35 UTC by aaronyan

This experiment was created and disabled in 2021 and can be removed from the code (experiment-20284). I noticed it while exploring some experiment alerts.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2024-01-19 19:38 UTC, aaronyan commented on client/my-sites/pages/main.jsx
> +					name={ `explat_test_aa_weekly_calypso_${ moment.utc().format( 'GGGG' ) }_week_${ moment.utc().week() }` }
The autogenereated A/A experiment profiles have names that end in `_3` instead of `_03`.

2024-01-22 09:03 UTC, jessie-ross requested changes
We use [the ISO 8601 week date system](https://en.wikipedia.org/wiki/ISO_week_date), it should be kept like this, and we should fix in the PHP side of things instead.

2024-02-02 23:16 UTC, aaronyan commented
Sounds good, thanks @jessie-ross!

2024-02-03 03:56 UTC, aaronyan commented
Closing this in favor of adjusting the php side! D136994-code

2024-02-03 03:56 UTC, closed without merging