Jetpack Manage pricing page: Add React hook to new public pricing endpoint
Automattic/wp-calypso pull request #86881
Opened 2024-01-26 01:51 UTC by gogdzl

Related to https://github.com/Automattic/jetpack-manage/issues/260

## Proposed Changes

* This PR modifies `useProductsQuery` adding a parameter to call the public facing endpoint, which does not need authentication.

## Testing Instructions

* Run the tests (`yarn run test-client client/state/partner-portal/licenses/test/hooks`)
* Add the `true` parameter to any usage of `useProductsQuery` (e.g. to the overview page, `client/jetpack-cloud/sections/overview/primary/overview-products/index.tsx`) and check the Network tab of your browser to ensure the correct endpoint is being called (`/wpcom/v2/jetpack-licensing/public/manage-pricing`) and it works.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2024-01-26 16:58 UTC, tbradsha commented on client/state/partner-portal/licenses/hooks/use-products-query.ts
> +	const productsPath = isPublicFacing
Non-blocking nitpick: maybe `productsAPIPath`?

2024-01-26 16:59 UTC, tbradsha commented on client/state/partner-portal/licenses/hooks/use-products-query.ts
>  		enabled: isPartnerOAuthTokenLoaded,
This needs to always be `true` if public.

2024-01-26 17:05 UTC, tbradsha requested changes
This is close. The only blocker I see is that we only call the API if `isPartnerOAuthTokenLoaded` is `true`, which won't be the case for non-Manage users.

In an ideal world I'd prefer the code variations to be decoupled a bit more, but now's not the time for a refactor. Not a blocker, but I would recommend at least creating a wrapper hook called `usePublicProductsQuery()`, though...this way it's clear the hook is querying public products without relying on a somewhat magic `bool` param that is easily overlooked.

2024-01-29 09:18 UTC, coder-karen requested changes
Adding a new param to the existing hook is an interesting approach! I did imagine a new hook, but if it can work then that is also an option.

I tested the hook out on another public page - the current `/pricing` page, and the products weren't being retrieved when passing through the true prop.

I then made sure my partner key was selected when on the parter portal dashboard page, and once selected the values were then retrieved from the pricing page - so that also confirms what @tbradsha was saying about still needing partner authentication here.

2024-01-29 16:36 UTC, tbradsha approved these changes
Works well, thanks!

2024-01-29 16:39 UTC, coder-karen approved these changes
For me, this now works, running the same test on the existing pricing page as before :) The tests run as well.

2024-01-29 17:09 UTC, merged