[WooCommerce NUX] Fix incorrect redirection for existing user
Automattic/wp-calypso pull request #87042
Opened 2024-01-31 10:47 UTC by chihsuan

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2024-02-01 06:30 UTC, ilyasfoo requested changes
@chihsuan I think this might be related to the PR, where another error looks broken (my account had 2fa)

Before:
<img width="803" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/4ef5d0ef-aa75-4aaf-9817-e4e6abf04717">

After:
<img width="914" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/728d856f-3410-4f0a-b02a-b4d28a188e78">

There's also this odd looking prompt when the social login failed (I disconnected sandbox so public-api isn't accessible):

<img width="634" alt="image" src="https://github.com/Automattic/wp-calypso/assets/3747241/bb1bc82c-13a7-482e-9c44-6113fe26cd1f">

Otherwise this was testing well!

2024-02-01 07:08 UTC, chihsuan commented
> @chihsuan I think this might be related to the PR, where another error looks broken (my account had 2fa)
> 
> Before: <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/3747241/301401341-4ef5d0ef-aa75-4aaf-9817-e4e6abf04717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzEzNjMsIm5iZiI6MTcwNjc3MTA2MywicGF0aCI6Ii8zNzQ3MjQxLzMwMTQwMTM0MS00ZWY1ZDBlZi1hYTc1LTRhYWYtOTgxNy1lNGU2YWJmMDQ3MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDcwNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUyOWM0NGE0MDdiZjEyYmYxZmYzNDc4NjA5ODhkYTlkZWE1MTk2ODNkMWY5YzAwYTA5YmE0YTU5ZjM5MTRlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0kpsqsekNnTnL4rMs9lyUii4s7XKhfa0xdavoZ2aDaE">
> 
> After: <img alt="image" width="914" src="https://private-user-images.githubusercontent.com/3747241/301403209-728d856f-3410-4f0a-b02a-b4d28a188e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzEzNjMsIm5iZiI6MTcwNjc3MTA2MywicGF0aCI6Ii8zNzQ3MjQxLzMwMTQwMzIwOS03MjhkODU2Zi0zNDEwLTRmMGEtYjAyYS1iNGQyOGExODhlNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDcwNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgxOTI3NTMzZGYzNGU1YTg4MWVmYmI1Y2JkMWViYjk3NGYxYjIyNDRjMWQ5YjhkYmQ4ZTc2MzkxMWU4YmNhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MSrvPihxBowpKIziIg0WXP7GpM0UvjD_lgkoB1mwkuY">
> 
> There's also this odd looking prompt when the social login failed (I disconnected sandbox so public-api isn't accessible):
> 
> <img alt="image" width="634" src="https://private-user-images.githubusercontent.com/3747241/301406663-bb1bc82c-13a7-482e-9c44-6113fe26cd1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzEzNjMsIm5iZiI6MTcwNjc3MTA2MywicGF0aCI6Ii8zNzQ3MjQxLzMwMTQwNjY2My1iYjFiYzgyYy0xM2E3LTQ4MmUtOWM0NC02MTEzZmUyNmNkMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDcwNDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQyNGIxNTU4OWRjYzVhMWFjM2I5MGY4NzZhMzBlNzVjZjExZTAyNWQyOGNhODI3NjM2NWQyYWMzYmZlMDBkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r-JeDXGZ7TqYZUqkQOQqt29_xu2VFaUnPIft7DN0RJQ">
> Otherwise this was testing well!

Good catch! @ilyasfoo Fixed in 71fd46fc4b3eea0aca545a589d73a4f0d1013666 🙏

2024-02-01 10:15 UTC, ilyasfoo approved these changes
Tested well! I have minor comments but pre-approving

2024-02-01 10:15 UTC, ilyasfoo commented on client/blocks/signup-form/index.jsx
> +			// Reset the signup step so that we don't re trigger this logic when the user goes back from login screen,
Nit
```suggestion
			// Reset the signup step so that we don't re trigger this logic when the user goes back from login screen.
```

2024-02-01 10:15 UTC, ilyasfoo commented on client/blocks/signup-form/index.jsx
> -			page( login( { redirectTo: this.props.redirectToAfterLoginUrl } ) );
Is there a potential of unintended behaviour since we're no longer exclusively use `this.props.redirectToAfterLoginUrl`, especially on non-Woo flows?

2024-02-01 10:47 UTC, chihsuan commented on client/blocks/signup-form/index.jsx
> -			page( login( { redirectTo: this.props.redirectToAfterLoginUrl } ) );
Good question! I think it should be safe. For signup flow, only Woo users will reach this logic.

https://github.com/Automattic/wp-calypso/blob/23d8e11f4c0b25896ee418f30f18727a6490502a/client/signup/steps/user/index.jsx#L590

And we still use `this.props.redirectToAfterLoginUrl` in the `getLoginLink`.  


https://github.com/Automattic/wp-calypso/blob/f4c142fd8d6f8dd4e560fb2f9fbbf6c4db6c2273/client/blocks/signup-form/index.jsx#L491-L503

Moreover, I believe that this `login()` call without any other additional parameters is a bug for all flows. Without passing any additional parameters, users will be redirected to the WP.com login screen and lose context.

2024-02-01 12:17 UTC, ilyasfoo commented on client/blocks/signup-form/index.jsx
> -			page( login( { redirectTo: this.props.redirectToAfterLoginUrl } ) );
Gotcha, thanks for clearing that up!

> Moreover, I believe that this login() call without any other additional parameters is a bug for all flows. Without passing any additional parameters, users will be redirected to the WP.com login screen and lose context.

Great point, I wonder if there's folks to tag about this 🤔

2024-02-01 23:16 UTC, moon0326 approved these changes
LGTM and tested well 👍 🚀

2024-02-05 07:28 UTC, merged

2024-02-05 10:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11264016

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @chihsuan for including a screenshot in the description! This is really helpful for our translators.

2024-02-11 16:34 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11264016).