Allow subdomains in glue records
Automattic/wp-calypso pull request #87191
Opened 2024-02-05 15:51 UTC by gius80

## Proposed Changes

This PR allows the use of subdomains in glue records.

## Testing Instructions

Apply this patch and verify that you can add glue records that include subdomain.

![glue-records-subdomain](https://github.com/Automattic/wp-calypso/assets/2797601/d5149a2d-550c-4ebb-af28-66b241345759)
## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

2024-02-05 19:01 UTC, leonardost requested changes
Tested and it's working nicely 🙂 there's just one thing that should be fixed before merging.

2024-02-05 19:01 UTC, leonardost commented on client/my-sites/domains/domain-management/settings/cards/glue-records-card.tsx
> +				/^([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/
```suggestion
				/^([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/
```
I think we need a backslash before the period there 🤔

2024-02-05 19:01 UTC, leonardost commented on client/my-sites/domains/domain-management/settings/cards/glue-records-card.tsx
> +				/^([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/
Also, I was testing long hostnames and it seems there's a 50 character limit in total for these name servers 😅 anything longer than that returns an `Invalid attribute value` error from KS. Couldn't find anything about this in the docs 😞 

So I guess we can add a `nameserver.length > 50` check before the regex check.

2024-02-06 09:53 UTC, gius80 commented on client/my-sites/domains/domain-management/settings/cards/glue-records-card.tsx
> +				/^([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)(.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$/
Good catch! Thanks @leonardost!

2024-02-06 10:17 UTC, merged

2024-02-06 12:44 UTC, leonardost commented on client/my-sites/domains/domain-management/settings/cards/glue-records-card.tsx
> +			nameserver.length > 50 ||
I think it would be a good idea to add a comment explaining this 50 character limit too 🙂