Accept invite: Validate email when creating account
Automattic/wp-calypso pull request #87415
Opened 2024-02-13 11:37 UTC by renancarvalho

Related to #87379

## Proposed Changes

* Implement email validation on passwordless invitation form. It should validate already existing users and any type of wrong email.
If the email already exists, it should show a message explaining that the email already exists, and offer links to log in or reset the password. After logging in, the user should be back to accept invite form.

## Testing Instructions

- Use live link or apply this branch locally
- From your atomic site, invite an user
- Get the invite in the email and accept the invitation
- When landing on WPCom type a wrong/malformed email 
- It should validate if the email is correct and disable the continue button
- If you use an existing email, it should present you options to login or reset password
- If you log in, it should bring you back to the accept invitation form again to accept or not the invitation.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-02-13 16:31 UTC, agrullon95 commented on client/blocks/signup-form/passwordless.jsx
> +		onInputBlur?.( event );
If possible, lets separate this into its own onblur event handler.

2024-02-13 17:12 UTC, agrullon95 approved these changes
## Tests:

- [x] Verify passwordless invite email validation for existing user
- [x] Verify passwordless invite works for new and existing users (after login)

A few things to point out/address in future PR:

1. If I enter an existing email and click the "Create an account" button, I only see an error "Invalid email input" notice without any details to explain why my email is invalid (in my case, it was an existing user). The input field validation doesn't trigger so we don't see the email error message below the email field.
2. Align styling for disabled button. Its grey on /log-in, but a different color on this screen.
3. Password reset flow for users doesn't properly navigate you back to the invitation screen. I haven't checked the feasibility of this but it would be nice if could easily navigate back to the invitation without clicking the invite email again after resetting your password.

2024-02-13 17:20 UTC, escapemanuele requested changes
Let's have the same validation for onChange and when clicking the button 👍

2024-02-14 09:36 UTC, renancarvalho commented on client/my-sites/invites/invite-accept-logged-out/index.jsx
> +						displayUsernameInput={ false }
This disabled the username from validation

2024-02-14 09:37 UTC, renancarvalho commented on client/blocks/signup-form/index.jsx
>  			'email',
Only email will be validated since this is passwordless

2024-02-14 09:37 UTC, renancarvalho commented on client/blocks/signup-form/index.jsx
> +			this.props.submitForm( this.state.form, passwordLessData );
Only submit the form if there are no errors

2024-02-14 10:42 UTC, escapemanuele approved these changes
Now it works great! LGTM

2024-02-14 10:45 UTC, merged