Checkout: Pre-fill Pix form from saved contact details
Automattic/wp-calypso pull request #87447
Opened 2024-02-14 04:36 UTC by sirbrillig

## Proposed Changes

This PR auto-completes the fields in the Pix payment method with saved contact details, if it can.

<img width="527" alt="Screenshot 2024-02-13 at 11 33 13 PM" src="https://github.com/Automattic/wp-calypso/assets/2036909/25edb5c0-047d-4c1f-9680-fef085509e1b">

> [!NOTE]
> At this time, changing the Pix fields and submitting the transaction will NOT save those fields for later. That would be a welcome improvement but this is a little tricky to do because they might differ from the user's tax or domain details and we only save one set. Which one should we keep?

Fixes https://github.com/Automattic/payments-shilling/issues/2412

## Testing Instructions

- Use an account with saved payment details; ideally one which has purchased a domain so it has a full address saved.
- To use Pix as a payment method option in checkout, first you'll need to have BRL as your currency, and then you'll need to select "Brazil" as the country inside checkout (and a Brazilian postal code like `61919-230`).
- Select Pix as the payment method and verify that most of the fields are filled already except for "Name" and "CPF". Verify that you can edit and change the fields.

2024-02-18 03:13 UTC, michaeldcain commented on client/my-sites/checkout/src/payment-methods/pix.tsx
> +		const regexpForStartingNumber = /^(\d+)\s+(.+)/;
From a few different searches online ([example](https://thebrazilbusiness.com/article/understanding-brazilian-addresses)), it looks like it might be common for Brazilian addresses to lead with the street, followed by the number (e.g. `Av. Paulista, 1098`).

338e7-pb/ Since our domain contact form doesn't care which side the number is on, we might want to assume that Brazilian users will input their address with the street number second and maybe change the regex: `^([^\d]*)(\d+)`

2024-02-18 03:14 UTC, michaeldcain requested changes
This works well, but we should reverse the regex to split apart the address field.

2024-02-19 23:20 UTC, sirbrillig commented on client/my-sites/checkout/src/payment-methods/pix.tsx
> +		const regexpForStartingNumber = /^(\d+)\s+(.+)/;
Good point. Updated to handle a variety of address formats from Brazil.

2024-02-20 16:57 UTC, michaeldcain approved these changes

2024-02-20 17:44 UTC, merged