Remove "All Woo Stores powered by WordPress.com" copy in non-NUX screens
Automattic/wp-calypso pull request #87517
Opened 2024-02-16 03:59 UTC by chihsuan

Close https://github.com/Automattic/wp-calypso/issues/87443
It's confusing to see "All Woo Stores powered by WordPress.com" copy in non-NUX screens as it's not relevant to the user. This PR removes the copy from non-NUX screens. We use `wccomFrom` to determine if the user is on a NUX screen or not.
## Proposed Changes

* Remove All Woo stores are powered by WordPress.com! when not from NUX context

## Testing Instructions

**NUX flow**

1. Using an existing WordPress.com account, go to `https://wordpress.com/me/security/connected-applications`
2. Disconnect from woocommerce.com
3. Log out from woo.com
4. Go to https://woo.com/start/#/installation
5. Click on "Try Woo Express for free"
6. Observe in the connection screen, there's `All Woo stores are powered by WordPress.com!`

<img width="1344" alt="Screenshot 2024-02-16 at 11 58 25" src="https://github.com/Automattic/wp-calypso/assets/4344253/01760487-e58c-44c6-bf6d-630a743f2565">

**non-NUX flow**

1. Using an existing WordPress.com account, go to `https://wordpress.com/me/security/connected-applications`
2. Disconnect from woocommerce.com
3. Log out from woo.com
4. Go to https://woo.com/my-dashboard/
5. Observe in the connection screen, there's NO `All Woo stores are powered by WordPress.com!`

<img width="1350" alt="Screenshot 2024-02-16 at 11 47 44" src="https://github.com/Automattic/wp-calypso/assets/4344253/ba60e397-7797-442c-925f-d4e357d04995">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-02-16 07:31 UTC, rjchow reviewed
There's a small bit of history behind this -
I introduced some of that wording as a stopgap while maintaining the intent of informing the user why they are logging into a wpcom account when they're trying to use a woo.com site. On reflection it does seem a bit misleading, but we might want to also consider the original intent.

I don't have too strong of an opinion either way as it seems neither the current nor the proposed solutions have an edge over the other. Maybe we could trouble @lauroraa (sorry, tagged the wrong Laura originally) 😀

2024-02-16 09:44 UTC, ilyasfoo requested changes
Tests well! A minor thing though, it looks like there is a quick flash of change when clicking either "login" or "sign up", where `All Woo Express stores are powered by WordPress.com!'` disappears and reappears when coming from NUX:

https://github.com/Automattic/wp-calypso/assets/3747241/fb5361f3-fbe5-44a5-8b9b-a64043627ea4

2024-02-19 08:03 UTC, chihsuan commented
> Tests well! A minor thing though, it looks like there is a quick flash of change when clicking either "login" or "sign up", where `All Woo Express stores are powered by WordPress.com!'` disappears and reappears when coming from NUX:

@ilyasfoo Good catch! I've added a fix for that in a987c59543dde89f4f4b0d453ac8b9815e902c16. 

The issue was that the route state was being updated before navigating to the new route, and login and signup flow used different query parameters to get the `wccom-from` value.

- Signup URL: the `wccom-from` parameter is nested within the `oauth2_redirect` parameter.

- Login URL: the `wccom-from` parameter is present directly in the URL query string.

I wanted to update the signup URL to use the same query parameter to get the `wccom-from` value. However, there is no filter to add `wccom-from` query parameter to signup url in wpcom (fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sjcpbz%2Qfvtahc.cuc%3Se%3Q60756803%2348-og) and it might be a risk to change wpcom code.

So I just created a selector to get the `wccom-from` value properly instead.

2024-02-19 09:33 UTC, ilyasfoo approved these changes
Awesome, thanks @chihsuan! Tested well 🚀

2024-02-20 11:56 UTC, rjchow approved these changes
I think Laura has a lot on her plate right now so let's go with this for now

2024-02-21 04:03 UTC, merged

2024-02-21 07:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11383037

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @chihsuan for including a screenshot in the description! This is really helpful for our translators.

2024-02-25 23:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11383037).