Update per_page param in use-fetch-dashboard-sites.ts
Automattic/wp-calypso pull request #88073
Opened 2024-03-01 11:13 UTC by cleacos

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-04 16:01 UTC, tbradsha commented on client/data/agency-dashboard/use-fetch-dashboard-sites.ts
> +					...( per_page && { per_page } ),
❤️

2024-03-04 16:01 UTC, tbradsha commented on client/data/agency-dashboard/use-fetch-dashboard-sites.ts
> +		...( per_page ? [ per_page ] : [] ),
Nice! We tried several variations, but not this one!

2024-03-04 16:09 UTC, tbradsha requested changes
This mostly works, but there are some quirks where the search filter doesn't update the URL/query consistently. See the URL here vs. the input:

![image](https://github.com/Automattic/wp-calypso/assets/32492176/684b574f-3c57-4c0d-9134-6050a3a68572)

One other suggestion: update the code to use `perPage` in the React context instead of `per_page` (used in the endpoint).

2024-03-04 17:39 UTC, cleacos commented
> One other suggestion: update the code to use perPage in the React context instead of per_page (used in the endpoint).

Yep, I usually use the camel case way on React context.

2024-03-04 17:44 UTC, cleacos commented
> but there are some quirks where the search filter doesn't update the URL/query consistently. See the URL here vs. the input:

Good catch! I can dig into it at some point this week. I think the idea I have to do that check and move it to the `updateDashboardURLQueryArgs` function instead of doing it in `sites-dashboard-v2.tsx`  should solve it.

2024-03-14 08:07 UTC, cleacos commented on client/lib/jetpack/paths.ts
> +export const sitesFavoritesPath = () => '/sites/favorites';
Note: We don't have `/sites/favorites` in A4A context

2024-03-14 08:08 UTC, cleacos commented on client/jetpack-cloud/sections/agency-dashboard/sites-overview/sites-dashboard-v2.tsx
> +		if ( path === sitesPath() || path === sitesFavoritesPath() ) {
In A4A we don't have sitesFavoritesPath

2024-03-14 08:09 UTC, cleacos commented on client/jetpack-cloud/sections/agency-dashboard/sites-overview/sites-dashboard-v2.tsx
> +				window.location.pathname !== sitesFavoritesPath() )
We don't have`sitesFavoritesPath` in A4A

2025-08-31 06:39 UTC, closed without merging