Site transfers: returns explicit error for invite key.
Automattic/wp-calypso pull request #88090
Opened 2024-03-01 17:35 UTC by cpapazoglou

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-01 19:47 UTC, WBerredo requested changes
I'm getting a different behavior testing the invalid invite flow.

With the cache cleared, it shows the message but then redirects to the success screen:
![CleanShot 2024-03-01 at 15 26 56](https://github.com/Automattic/wp-calypso/assets/5039531/2fc06baa-1e09-40ad-ab19-d95da406b46f)

And when I try the same URL the second time (cache not empty) it goes straight to the success screen:

![CleanShot 2024-03-01 at 15 12 05](https://github.com/Automattic/wp-calypso/assets/5039531/992a2850-7872-4f6d-80dd-9c823575c162)

2024-03-01 19:47 UTC, WBerredo commented on client/my-sites/site-settings/site-owner-transfer/accept-site-transfer.tsx
> +				error?.message ??
Its good to see this message is already translated by the API.

2024-03-01 20:24 UTC, cpapazoglou commented
> I'm getting a different behavior testing the invalid invite flow.
> 
> With the cache cleared, it shows the message but then redirects to the success screen: ![CleanShot 2024-03-01 at 15 26 56](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNjZmNhYTMwOThlZjQxMTI1ZDRiMTNhOTk0ZjgwYTY2MDE0ZTYxNWIyOGUzN2Y0OWRiOWU5MmI1YzI1MzI5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hN5LegR6myFHCsgM82LO3YqPq9TiXtR96Tk4irPkV2I) [ ![CleanShot 2024-03-01 at 15 26 56](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNjZmNhYTMwOThlZjQxMTI1ZDRiMTNhOTk0ZjgwYTY2MDE0ZTYxNWIyOGUzN2Y0OWRiOWU5MmI1YzI1MzI5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hN5LegR6myFHCsgM82LO3YqPq9TiXtR96Tk4irPkV2I) ](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNjZmNhYTMwOThlZjQxMTI1ZDRiMTNhOTk0ZjgwYTY2MDE0ZTYxNWIyOGUzN2Y0OWRiOWU5MmI1YzI1MzI5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hN5LegR6myFHCsgM82LO3YqPq9TiXtR96Tk4irPkV2I) [ ](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNjZmNhYTMwOThlZjQxMTI1ZDRiMTNhOTk0ZjgwYTY2MDE0ZTYxNWIyOGUzN2Y0OWRiOWU5MmI1YzI1MzI5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hN5LegR6myFHCsgM82LO3YqPq9TiXtR96Tk4irPkV2I)
> 
> And when I try the same URL the second time (cache not empty) it goes straight to the success screen:
> 
> ![CleanShot 2024-03-01 at 15 12 05](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhiNWY3OGU4NmNmZTA0OTlmYzEzZjFmY2ViYzY2YjkwYjVlMWNhYmU1N2M0ODUxMGI4MWIxZWVhYzllYjRlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tB4lg0ycuFVkp1KUm0JQJ2CjWTofGIHNK7qJji_34-s) [ ![CleanShot 2024-03-01 at 15 12 05](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhiNWY3OGU4NmNmZTA0OTlmYzEzZjFmY2ViYzY2YjkwYjVlMWNhYmU1N2M0ODUxMGI4MWIxZWVhYzllYjRlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tB4lg0ycuFVkp1KUm0JQJ2CjWTofGIHNK7qJji_34-s) ](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhiNWY3OGU4NmNmZTA0OTlmYzEzZjFmY2ViYzY2YjkwYjVlMWNhYmU1N2M0ODUxMGI4MWIxZWVhYzllYjRlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tB4lg0ycuFVkp1KUm0JQJ2CjWTofGIHNK7qJji_34-s) [ ](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjQ4OTksIm5iZiI6MTcwOTMyNDU5OSwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMjAyMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDhiNWY3OGU4NmNmZTA0OTlmYzEzZjFmY2ViYzY2YjkwYjVlMWNhYmU1N2M0ODUxMGI4MWIxZWVhYzllYjRlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tB4lg0ycuFVkp1KUm0JQJ2CjWTofGIHNK7qJji_34-s)

Sounds like you are trying from the account you sent the invite and not from the one you sent it too?

2024-03-01 20:30 UTC, WBerredo commented
> Sounds like you are trying from the account you sent the invite and not from the one you sent it too?

That's a good point, I tried with a site I was the owner. That said, I think we should also handle this case to have a more adequate message.

2024-03-04 10:16 UTC, cpapazoglou commented on client/my-sites/site-settings/site-owner-transfer/accept-site-transfer.tsx
> +				error?.message ??
Is it the same message or `Hold tight. We are making it happen!'`? I guess it might not have been translated yet.

https://github.com/Automattic/wp-calypso/blob/2586316b4442825af82af1de33d473645543d586/client/my-sites/site-settings/site-owner-transfer/accept-site-transfer.tsx#L134

2024-03-04 10:17 UTC, cpapazoglou commented
> I'm getting a different behavior testing the invalid invite flow.
> 
> With the cache cleared, it shows the message but then redirects to the success screen: ![CleanShot 2024-03-01 at 15 26 56](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQwMGNmMzBjMzdkNmEzNzcwZmIwN2I0Y2U0NDRiM2Q5MjMwYWM4NjI3YzI1NWNmOWExMzQ4ZjZkYmJkNzkxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6RzAWCUE672Djptq10u4cyIevtZ_b0g0Lv_RkLp6fFs) [ ![CleanShot 2024-03-01 at 15 26 56](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQwMGNmMzBjMzdkNmEzNzcwZmIwN2I0Y2U0NDRiM2Q5MjMwYWM4NjI3YzI1NWNmOWExMzQ4ZjZkYmJkNzkxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6RzAWCUE672Djptq10u4cyIevtZ_b0g0Lv_RkLp6fFs) ](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQwMGNmMzBjMzdkNmEzNzcwZmIwN2I0Y2U0NDRiM2Q5MjMwYWM4NjI3YzI1NWNmOWExMzQ4ZjZkYmJkNzkxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6RzAWCUE672Djptq10u4cyIevtZ_b0g0Lv_RkLp6fFs) [ ](https://private-user-images.githubusercontent.com/5039531/309371767-2fc06baa-1e09-40ad-ab19-d95da406b46f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MTc2Ny0yZmMwNmJhYS0xZTA5LTQwYWQtYWIxOS1kOTVkYTQwNmI0NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQwMGNmMzBjMzdkNmEzNzcwZmIwN2I0Y2U0NDRiM2Q5MjMwYWM4NjI3YzI1NWNmOWExMzQ4ZjZkYmJkNzkxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6RzAWCUE672Djptq10u4cyIevtZ_b0g0Lv_RkLp6fFs)
> 
> And when I try the same URL the second time (cache not empty) it goes straight to the success screen:
> 
> ![CleanShot 2024-03-01 at 15 12 05](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwZmRmNjViZDc2MDI1NTE0MDc1MzYwMDlhMWEwZDE1NzFmZTdlODZmMjhkNDY4N2VjZWNmOTE5NjU2NDRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c7MOup7pdlYorRQyA5qyWGhskt76WvOT3XVRrvSUdE0) [ ![CleanShot 2024-03-01 at 15 12 05](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwZmRmNjViZDc2MDI1NTE0MDc1MzYwMDlhMWEwZDE1NzFmZTdlODZmMjhkNDY4N2VjZWNmOTE5NjU2NDRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c7MOup7pdlYorRQyA5qyWGhskt76WvOT3XVRrvSUdE0) ](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwZmRmNjViZDc2MDI1NTE0MDc1MzYwMDlhMWEwZDE1NzFmZTdlODZmMjhkNDY4N2VjZWNmOTE5NjU2NDRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c7MOup7pdlYorRQyA5qyWGhskt76WvOT3XVRrvSUdE0) [ ](https://private-user-images.githubusercontent.com/5039531/309372041-992a2850-7872-4f6d-80dd-9c823575c162.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc2MTIsIm5iZiI6MTcwOTU0NzMxMiwicGF0aCI6Ii81MDM5NTMxLzMwOTM3MjA0MS05OTJhMjg1MC03ODcyLTRmNmQtODBkZC05YzgyMzU3NWMxNjIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTAxNTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwZmRmNjViZDc2MDI1NTE0MDc1MzYwMDlhMWEwZDE1NzFmZTdlODZmMjhkNDY4N2VjZWNmOTE5NjU2NDRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c7MOup7pdlYorRQyA5qyWGhskt76WvOT3XVRrvSUdE0)

Probably you were trying this in a site that you are already owning and thus you got to the success page?

https://github.com/Automattic/wp-calypso/blob/2586316b4442825af82af1de33d473645543d586/client/my-sites/site-settings/site-owner-transfer/accept-site-transfer.tsx#L89-L105

2024-03-04 12:58 UTC, WBerredo commented on client/my-sites/site-settings/site-owner-transfer/accept-site-transfer.tsx
> +				error?.message ??
Its actually a flickering with an already translated string:

![CleanShot 2024-03-01 at 15 12 05](https://github.com/Automattic/wp-calypso/assets/5039531/992a2850-7872-4f6d-80dd-9c823575c162)

But I guess this is not a regression as the flow for this PR shouldn't even get into this scren.

2024-03-04 12:59 UTC, WBerredo approved these changes
From an invited user perspective its working as described. LGTM!

![CleanShot 2024-03-04 at 09 47 40@2x](https://github.com/Automattic/wp-calypso/assets/5039531/36a9639c-201f-4960-bf9c-c88d14aa4faa)


PS: Thanks for updating the testing instructions btw

2024-03-04 15:06 UTC, merged