Pattern Library: Add search functionality
Automattic/wp-calypso pull request #88238
Opened 2024-03-06 14:47 UTC by fredrikekelund

Fixes https://github.com/Automattic/dotcom-forge/issues/5600

## Proposed Changes

This PR adds basic search functionality to the public pattern library. Searches are performed on the client by simple string matching of pattern titles, descriptions and category names.

On the `/patterns` home page, searches are performed against **all** patterns, and on category pages they are performed within that category.

Search queries are persisted to the URL in a query parameter. Back/forward history navigation is also supported.

## Testing Instructions

1. ~Apply D140727-code~
2. ~Sandbox `public-api.wordpress.com`~
3. Navigate to `/patterns`
4. Search for `contact`
5. Ensure that some pattern previews are rendered below the category links
6. Click on the `About` category
7. Search for `contact` again
8. Ensure that a single pattern preview is rendered below the category links

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-07 15:07 UTC, stephanethomas requested changes
I've tested it in French, and it works fine (e.g. looking up 'propos' returns the right <em>about</em> patterns). However, I've encountered a nasty bug three times where the page becomes uncontrollable (some sort of race condition between the url and the state which forces me to kill that page). It's not easy to reproduce but I was able to capture it:

![video](https://github.com/Automattic/wp-calypso/assets/594356/3ef7e176-9fd2-4a87-95c2-d3c633879962)

I've also noticed that http://calypso.localhost:3000/patterns/contact?s=something redirects to http://calypso.localhost:3000/patterns/contact upon reloading the page. I think it would be great to be able to support that parameter so people can share links like this. If that's not technically feasible, I'm fine with leaving it that way as long as users are able to bookmark specific patterns, e.g. http://calypso.localhost:3000/patterns/about-left-aligned-content.

Finally, Matt mentioned hiding the category tiles when searching in p1709818484459049-C06ELHR6L9J, but I understand this will be addressed in another pull request. By the way, would you mind adding screenshots to the description? ICYMI, I've explained the rationale in p1709635796339589-C06ELHR6L9J.

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/components/header/index.tsx
> +type Props = {
Could we keep the original name? That's the convention we've been following until now 🙂.
```suggestion
type PatternsHeaderProps = {
```

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/home/index.tsx
> +		return [];
I would have expected that function to return the whole list if the search term is empty:

```suggestion
		return patterns;
```

And this would allow us to simplify that calling code:

```javascript
const patternSearchResults = filterPatternsByQuery( patterns, searchTerm );
const patternsToRender = searchTerm ? patternSearchResults : patterns;
```

But maybe I've missed some edge case?

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/home/index.tsx
> +	const patternSearchResults = filterPatternsByQuery( patterns, searchTerm );
A small suggestion to be more consistent with the `searchTerm` parameter:
```suggestion
	const patternSearchResults = filterPatternsByTerm( patterns, searchTerm );
```

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/home/index.tsx
> +		const lowercaseSearch = searchTerm.toLowerCase();
We should move that line outside the `filter` call 🙂.

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/home/index.tsx
> +		);
The filtering code is a bit hard to grasp, maybe we could add a comment like this to clarify its purpose?
```suggestion
		// Filters out any null and undefined values
		const fields = [ pattern.title, pattern.description, ...patternCategories ].filter(
			( x ): x is NonNullable< typeof x > => Boolean( x )
		);
```

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/home/index.tsx
> +		const lowercaseSearch = searchTerm.toLowerCase();
Oh, and also update its name to be properly camelCased and to end with `Term`:
```suggestion
		const lowerCaseSearchTerm = searchTerm.toLowerCase();
```

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/home/index.tsx
> +	const isPatternsDisplaying = Boolean( category || searchTerm );
The mix of singular verb and plural noun is strange, what do think of the following instead?

```suggestion
	const showListOfPatterns = Boolean( category || searchTerm );
```

2024-03-07 15:07 UTC, stephanethomas commented on client/my-sites/patterns/home/index.tsx
> +	}, [] );
It wasn't immediately clear to me what those effects are supposed to do, maybe this could be improved with comments?

```suggestion
	// Resets the search term whenever the category changes
	useEffect( () => {
		setSearchTerm( '' );
	}, [ category ] );

	// Updates the url of the page whenever the search term changes
	useEffect( () => {
		const params = new URLSearchParams( window.location.search );

		if ( searchTerm ) {
			params.set( 's', searchTerm );
		} else {
			params.delete( 's' );
		}

		const paramsString = params.toString().length ? `?${ params.toString() }` : '';
		page( `${ window.location.pathname }${ paramsString }` );
	}, [ searchTerm ] );

	// Updates the search term whenever the url of the page changes
	useEffect( () => {
		function onPopstate() {
			const params = new URLSearchParams( window.location.search );
			setSearchTerm( params.get( 's' ) ?? '' );
		}

		window.addEventListener( 'popstate', onPopstate );

		return () => {
			window.removeEventListener( 'popstate', onPopstate );
		};
	}, [] );
```

2024-03-08 11:32 UTC, fredrikekelund commented on client/my-sites/patterns/components/header/index.tsx
> +type Props = {
I'm fine with sticking to that convention, but for the record, I find it superfluous to mirror the component name in the type name, _unless the props type definition is exported_

2024-03-08 13:48 UTC, fredrikekelund commented
> a nasty bug

I'm having trouble reproducing this… Just checking: did you modify the code while testing so that hot updating may be at fault here? I remember the `calypso/components/search` component having trouble with hot updating while I was working on this PR

2024-03-08 14:42 UTC, fredrikekelund commented on client/my-sites/patterns/home/index.tsx
> +		);
The Typescript dance is quite silly, but TS can't infer the correct type for `fields` without it. I'm fine with adding a comment to explain.

2024-03-08 15:34 UTC, fredrikekelund commented
I still haven't been able to reproduce the bug @stephanethomas mentioned, but @wongasy confirmed that she saw it too p1709906980722319/1709905760.272689-slack-C06ELHR6L9J

I have an assumption about what could have caused it, and I've implemented a fix. This should be good for another look!

2024-03-11 17:22 UTC, stephanethomas approved these changes
All good to me! I didn't encounter the strange bug I've mentioned before.

2024-03-11 17:22 UTC, stephanethomas commented on client/my-sites/patterns/components/header/index.tsx
> +	onSearch = ( s ) => s,
I'm a bit lost. According to the type definition, this function should return nothing. Am I missing something?

```suggestion
	onSearch = () => {},
```

2024-03-11 17:22 UTC, stephanethomas commented on client/my-sites/patterns/hooks/use-pattern-search-term.ts
> +	const [ searchTerm, setSearchTerm ] = useState( getQueryParam( 's' ) );
We refer to this query parameter in a few places, maybe we should add a constant for it?

2024-03-11 17:22 UTC, stephanethomas commented on client/my-sites/patterns/hooks/use-pattern-search-term.ts
> +	const lowerCaseSearchTerm = searchTerm.toLowerCase();
That's an edge case but for completeness we may want to also trim white spaces:

```suggestion
	const lowerCaseSearchTerm = searchTerm.toLowerCase().trim();
```

2024-03-11 17:22 UTC, stephanethomas commented on client/my-sites/patterns/hooks/use-pattern-search-term.ts
> +	const [ searchTerm, setSearchTerm ] = useState( getQueryParam( 's' ) );
As an aside, I would use `search` instead of `s` as it's easier to read 🙂.

2024-03-12 07:18 UTC, fredrikekelund commented on client/my-sites/patterns/components/header/index.tsx
> +	onSearch = ( s ) => s,
> Am I missing something?

Quite the opposite! 👍

2024-03-12 07:32 UTC, fredrikekelund commented on client/my-sites/patterns/hooks/use-pattern-search-term.ts
> +	const [ searchTerm, setSearchTerm ] = useState( getQueryParam( 's' ) );
Good call about adding a constant! I'll stick with `s`, though, if nothing else, to align with WP convention 😉

2024-03-12 07:50 UTC, merged