Add VAT notice in pricing banner
Automattic/wp-calypso pull request #88464
Opened 2024-03-13 14:21 UTC by robertsreberski

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-13 17:11 UTC, CodeyGuyDylan requested changes
From 960px to 1052px the notices at the top look like this:

![image](https://github.com/Automattic/wp-calypso/assets/65001528/d76958f6-07cb-4847-9700-4354335eb3dd)

Might want to set the media query later or do something different design-wise

2024-03-13 17:11 UTC, CodeyGuyDylan commented on client/components/jetpack/intro-pricing-banner/index.tsx
> +	// It's better to show more information rather than hide it. So we don't show notice if we don't have geodata yet.
This comment is conflicting (I think?) To it me the first sentence implies that we *should* show the notice until the geodata is available, but the next sentence says that we shouldnt

2024-03-14 09:13 UTC, robertsreberski commented on client/components/jetpack/intro-pricing-banner/index.tsx
> +	// It's better to show more information rather than hide it. So we don't show notice if we don't have geodata yet.
Ah, sorry, it sounds confusing. What I meant is that it's better to "pop-in" the information, rather than hide it from the view.

2024-03-14 16:35 UTC, robertsreberski commented
@CodeyGuyDylan I decided to address that resolution gap in the following way:

![CleanShot 2024-03-14 at 17 28 19@2x](https://github.com/Automattic/wp-calypso/assets/8419292/c86c1212-1d7a-4459-8f68-5df496b9452c)

Let me know what you think!

2024-03-14 16:52 UTC, CodeyGuyDylan approved these changes
Design looks better and the code looks good so I'll approve

![image](https://github.com/Automattic/wp-calypso/assets/65001528/318e34ff-199e-4fad-9229-b2167dcb6c6b)

I do think this could use some design improvement overall, it looks weird to me with the VAT line being the only one without an icon and the bulk pricing text being smaller than the rest 🤔

2024-03-15 11:38 UTC, merged

2024-03-15 12:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11606612

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @robertsreberski for including a screenshot in the description! This is really helpful for our translators.

2024-03-18 00:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11606612).