Rollback hosting trial banner from theme upload page
Automattic/wp-calypso pull request #88490
Opened 2024-03-13 20:36 UTC by chad1008

Related to 6027-gh-Automattic/dotcom-forge

## Proposed Changes

Remove the **Start your free Creator plan trial to access the theme install features** CTA in the upgrade nudge banner for logged-in users viewing `/themes/upload`, in favor of a standard upgrade nudge. For now we aren't removing the underlying logic, just focusing on disabling the CTA itself. If needed, we can remove the logic in a followup PR.

## Testing Instructions

- Using a free plan site that does not already support uploading themes, navigate to `/themes/upload` 
- When the page loads, confirm that CTA banner encourages an upgrade to the Creator plan, rather than offering a free trial
- Confirm that clicking on the banner opens a checkout modal with the Creator plan already added to the cart.
- Confirm that clicking on the banner does not open a free trial modal

**Before**
<img width="1101" alt="Upsell banner on theme upload page that reads 'Start your free Creator plan trial to access the theme install features'" src="https://github.com/Automattic/wp-calypso/assets/13856531/16d9143d-0d04-4b9f-8771-18f4dcd429b0">

**After**
<img width="1103" alt="Upsell banner on theme upload page that reads 'Upgrade to the Creator plan to access the theme install features'" src="https://github.com/Automattic/wp-calypso/assets/13856531/558ead0d-8e5d-45c1-91b8-db39b5fb653e">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-21 14:16 UTC, wongasy requested changes
It appears that the `isEligibleForHostingTrial` property was introduced from https://github.com/Automattic/wp-calypso/pull/86878 where the free trial banner was implemented. Perhaps the simpler change is to hardcode `isEligibleForHostingTrial` to `false` here:

https://github.com/Automattic/wp-calypso/blob/4e673c41dcf4d9ba285900faa73f2c82819c9463/client/my-sites/themes/theme-upload/index.jsx#L490-L492

That way, when we do want to re-enable free trial, we'd just bring back this one line.

2024-03-21 14:17 UTC, wongasy commented
A heads up that I've also tagged this PR with "DO NOT MERGE" since we are holding off these changes. Regardless, thought it might be useful to provide feedback in case we do move forward with the change at some point.

2024-03-27 17:27 UTC, wongasy commented
@chad1008 This work may return, we should have an update this week. The pattern work remains our priority, but whenever your plate becomes empty, let's be sure we address this feedback: https://github.com/Automattic/wp-calypso/pull/88490#pullrequestreview-1952358425

2024-03-29 21:30 UTC, chad1008 commented
Good call @wongasy, that's a much cleaner approach, thanks!

2024-04-03 15:09 UTC, wongasy approved these changes
LGTM and tests well! I was able to see the upgrade banner.

<img width="1543" alt="Screen Shot 2024-04-03 at 11 06 27 AM" src="https://github.com/Automattic/wp-calypso/assets/104910361/90965f2a-58d2-4257-9b46-d5c471abb612">

2024-04-04 15:28 UTC, merged