Github Deployments: Show permission notice above pagination component
Automattic/wp-calypso pull request #88647
Opened 2024-03-18 23:58 UTC by vykes-mac

Related to #

## Proposed Changes

* Move the permission notice above pagination to match design

## Testing Instructions

* go to /github-deployments/atomicSite/create
* adjust permissions to all repository
* pagination should be below the notice.

![image](https://github.com/Automattic/wp-calypso/assets/47489215/e82b75b1-5ff2-4d4b-9fa8-9e5c6a94e10d)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-19 14:04 UTC, javierarce commented
Thanks for working on this! I noticed a few problems:

- The padding bottom of the modal should be 32px.
- The distance between the pagination and the label above should be 24px.

There are other issues with the implementation of the modal, but I'll open a new issue for that.

![image](https://github.com/Automattic/wp-calypso/assets/4933/14452eff-4618-470d-8696-c09381b0a3c7)

Figma file: AkPDFrEtrfwxjLrVZzjRaj-fi-6542_172840

2024-03-19 19:57 UTC, vykes-mac commented
@javierarce I have adjusted the margins and paddings to fix the design. I also make the modal height fits with the content

![image](https://github.com/Automattic/wp-calypso/assets/47489215/d55ddb5c-d749-4ad4-a013-03e9dfdc3e5a)
![image](https://github.com/Automattic/wp-calypso/assets/47489215/cf36f8f4-153f-4230-ad91-eb005009301c)

2024-03-19 20:41 UTC, zaguiini commented
I'm unsure if fitting the modal height is the best option here. If there are less than 10 repos, it will keep shrinking, expanding. I think having a fixed shell is better 😬

2024-03-19 21:04 UTC, vykes-mac commented
We can probably add a min height , @javierarce wanted it to fit. Can probably have a max and min height

2024-03-20 12:52 UTC, javierarce commented
> We can probably add a min height , @javierarce wanted it to fit. Can probably have a max and min height

I tried out removing the fixed height manually, and I think taking off the predefined height might work. However, it'd be great to test this in the current branch to check if it's practical or too distracting.

In any case, what I was trying to solve is the issue of the content in these modals not being centered:

![image](https://github.com/Automattic/wp-calypso/assets/4933/3ff8c649-52cb-44b7-9594-1dd5a6cfee05)

2024-03-20 23:15 UTC, vykes-mac commented
@javierarce I have used a fix height and center the contents

![image](https://github.com/Automattic/wp-calypso/assets/47489215/1d75f0e7-e023-42aa-86b4-439de84bc053)

2024-03-22 01:00 UTC, vykes-mac commented
@javierarce pinging you.

2024-03-22 09:03 UTC, javierarce commented
> @javierarce I have used a fix height and center the contents

Perfect.

I've just been able to test that screen with the calypso.live link.

<img width="1220" alt="Screenshot 2024-03-22 at 09 59 33" src="https://github.com/Automattic/wp-calypso/assets/4933/7733c251-d458-4a30-b485-3d5b941d2282">

And locally, for some reason, this PR doesn't let me visit /github-deployments. 

But I'd say go on and merge it because there are some small general fixes we should add to the modal, and we could solve those in a different PR.

2024-03-22 10:18 UTC, Aurorum requested changes

2024-03-22 10:18 UTC, Aurorum commented on client/my-sites/github-deployments/deployment-creation/style.scss
> +.dialog__action-buttons-close {
Should this not be more specific? Might cause problems if it's loaded and then a dialog elsewhere is viewed.

2024-03-22 19:41 UTC, merged