A4A: Update sites dashboard URL for preview pane
Automattic/wp-calypso pull request #88644
Opened 2024-03-18 20:23 UTC by gogdzl

Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/76

## Proposed Changes

* This PR updates the URL control for the site dashboard's preview pane. Now, when a user selects a site, the browser's URL is automatically updated to reflect this choice. This means that if a user bookmarks this URL or revisits it later, they're taken directly to the preview pane of the selected site, preserving the pane's state and position.

IMPORTANT NOTE: IMPORTANT NOTE: The API connection has not been implemented yet. Therefore, we are currently using mocked data and simulating a server delay of 3 seconds to display the information. This delay is there to ensure that the system functions correctly and provides appropriate loading feedback to the user.

## Testing Instructions

* Go to the site dashboard (http://agencies.localhost:3000/sites).
* Make sure the mock data is displayed correctly.
* Select any of the sites.
* Make sure the pane is displayed and the URL is updated.
* Copy the URL.
* Paste it into a new window.
* Make sure it displays the correct site and feature (boost, scan, etc.).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-19 14:50 UTC, cleacos commented
This PR should be updated. Now, we are retrieving real sites from the endpoint.

2024-03-19 21:56 UTC, cleacos requested changes
![image](https://github.com/Automattic/wp-calypso/assets/9832440/27f658c0-4ab3-4344-8ccf-665c2fb7bb3c)

This PR breaks some functionalities. These tabs don't work: Activity and Scan.

Also, it breaks some styles in the side-by-side view, if I copy and paste the URL:

![image](https://github.com/Automattic/wp-calypso/assets/9832440/c03e2c2a-ae37-493e-b15f-cef4f016236c)

2024-03-19 21:58 UTC, cleacos commented
By the way, update the description (API part)

2024-03-20 09:09 UTC, coder-karen reviewed
Spotted the same issues as Clemente. I took a screenshot of my inspector as there were differences in the HTML between the two views, in case it helps here:

Correct sites list view:
<img width="1563" alt="Screenshot 2024-03-20 at 09 06 21" src="https://github.com/Automattic/wp-calypso/assets/16754605/696706de-b935-44f1-8fd1-3d8f19b414d3">

Sites list view after visiting the URL manually:
<img width="1532" alt="Screenshot 2024-03-20 at 09 06 46" src="https://github.com/Automattic/wp-calypso/assets/16754605/7d171156-73a5-4a76-8937-2c4d443a8994">

2024-03-20 16:44 UTC, gogdzl commented
Tabs fixed in https://github.com/Automattic/wp-calypso/pull/88644/commits/a1bd16b3c7adfa71c9ed3c53be0bf28ee031240a

2024-03-20 17:37 UTC, coder-karen reviewed
This looks beautiful!

I left a few non-blocker suggestions.

One other thing I've noticed though, when manually visiting a preview-pane-inclusive link, the sites overview display looks off:

<img width="407" alt="Screenshot 2024-03-20 at 17 33 25" src="https://github.com/Automattic/wp-calypso/assets/16754605/6fb083bf-07cf-49f1-8dc5-530b7f138d5c">

Also for some reason when testing locally I still can't see the Activity and Scan info, whereas I can using Horizon 🤔 Not sure if that one is just my environment.
The above sites overview display issue I can get in both.

2024-03-20 17:37 UTC, coder-karen commented on client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
> +				'/sites/' + category + '/' + sitesViewState.selectedSite.url + '/' + selectedSiteFeature
```suggestion
			page.replace(
				`/sites/${ category }/${ sitesViewState.selectedSite.url }/${ selectedSiteFeature }`
			);
```

What about using template literals like this?

2024-03-20 17:37 UTC, coder-karen commented on client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
> +			page.replace( '/sites/' + category + '/' + sitesViewState.selectedSite.url );
```suggestion
			page.replace( `/sites/${ category }/${ sitesViewState.selectedSite.url }` );
```
As above.

2024-03-20 17:37 UTC, coder-karen commented on client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
>  			page.replace( '/sites/' + category );
```suggestion
			page.replace( `/sites/${ category }` );
```
As above.

2024-03-20 17:40 UTC, gogdzl commented
> One other thing I've noticed though, when manually visiting a preview-pane-inclusive link, the sites overview display looks off:

I will have to fix that :crying_cat_face:

2024-03-20 18:02 UTC, gogdzl commented on client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
> +				'/sites/' + category + '/' + sitesViewState.selectedSite.url + '/' + selectedSiteFeature
Great suggestion! https://github.com/Automattic/wp-calypso/pull/88644/commits/6460b8e6b220e8236a005754738e31e4c2b04f93

2024-03-20 18:02 UTC, gogdzl commented on client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
> +			page.replace( '/sites/' + category + '/' + sitesViewState.selectedSite.url );
Great suggestion! https://github.com/Automattic/wp-calypso/commit/6460b8e6b220e8236a005754738e31e4c2b04f93

2024-03-20 18:02 UTC, gogdzl commented on client/a8c-for-agencies/sections/sites/sites-dashboard/index.tsx
>  			page.replace( '/sites/' + category );
Great suggestion! https://github.com/Automattic/wp-calypso/commit/6460b8e6b220e8236a005754738e31e4c2b04f93

2024-03-21 10:36 UTC, coder-karen commented
This looks great on Horizon now! I can't seem to test things properly locally though still - all the same issues remain despite rebuilding, rerunning 'yarn', using an incognito window - also updating the branch with trunk and fixing a merge conflict (not sure why it doesn't show on the PR here yet). So it might be better for someone else to confirm local also works, unless we're predominantly interested in Horizon as that's closer to the production environment.

2024-03-21 19:20 UTC, rcanepa approved these changes
LGTM. It works as expected and doesn't seem to introduce any regression.

2024-03-21 19:22 UTC, merged