Signup: Vertically align the Create your account component
Automattic/wp-calypso pull request #88661
Opened 2024-03-19 10:51 UTC by yuliyan

Related to 2824-gh-Automattic/martech

## Proposed Changes

* Vertically align the content of `. signup__step` using `display: flex;`.
* Set the minimum height of the `. signup__step` to `100vh` and subtract the `.layout__content` top padding and `.step-wrapper__header` top margin.
* Add margin bottom to `.step-wrapper` to compensate for `.step-wrapper__header` margin top.

**Before:**
![f0e4RFF0AlTPACtq](https://github.com/Automattic/wp-calypso/assets/2722412/ff6d9651-520a-4d83-a824-877f0dc82061)

**After:**
![YF0ZGpwme8KFCav5](https://github.com/Automattic/wp-calypso/assets/2722412/610006c3-a228-45e5-9377-8c47dfda8a91)

## Testing Instructions

* Code review.
* Navigate to `https://wordpress.com/start/user-social` and confirm the `Create your account` component is off-center vertically.
* Checkout the branch locally or use calypso.live build.
* Navigate to `start/user-social` and confirm the vertical centering is now fixed.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-19 14:27 UTC, niranjan-uma-shankar approved these changes
LGTM. Looks better on both desktop and mobile 👍

2024-03-19 14:44 UTC, niranjan-uma-shankar requested changes
I found an issue in non-EN locales. The "available in English" notification is misaligned. Here's a screenshot from `de`:

<img width="1634" alt="Screenshot 2024-03-19 at 3 43 51 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/3ac2eb08-af3a-45aa-94c0-80f81ee12217">

2024-03-19 23:54 UTC, yuliyan commented
> I found an issue in non-EN locales. The "available in English" notification is misaligned. Here's a screenshot from `de`:
> 
> <img alt="Screenshot 2024-03-19 at 3 43 51 PM" width="1634" src="https://private-user-images.githubusercontent.com/1269602/314106392-3ac2eb08-af3a-45aa-94c0-80f81ee12217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTIxNzQsIm5iZiI6MTcxMDg5MTg3NCwicGF0aCI6Ii8xMjY5NjAyLzMxNDEwNjM5Mi0zYWMyZWIwOC1hZjNhLTQ1YWEtOTRjMC04MGY4MWVlMTIyMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMjM0NDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY3ZDRmYzJlNzM1NTg1ZjZiY2EzYTc2ODVlNjZmZTU4MzM2ZjRhZTk4NzU1MjIwOWQ4OWQxN2Q0NTExMTBhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1AsZCA2mgPSwf64G7Z7BahJzHlkDagh0OaScL9cq2P0">

@niranjan-uma-shankar, thanks for catching that - I didn't test on non-English locales at all (which is a bit ironic 😅).

I switched to `flex-direction: column` and it should be good with and without the LocaleSuggestions component.

On a separate note, I've noticed that by having the component centered, it's now shifting vertically when the inner content changes. I'm not sure whether this is a problem for the UX but just wanted to bring it up,

2024-03-21 10:38 UTC, niranjan-uma-shankar commented
> On a separate note, I've noticed that by having the component centered, it's now shifting vertically when the inner content changes. I'm not sure whether this is a problem for the UX but just wanted to bring it up.

Good catch, I am not sure too. Maybe worth checking with @nuriapenya or on the P2 post p58i-gS9-p2.

2024-03-21 11:12 UTC, yuliyan commented
> (direct link)

On a second inspection, I've noticed that we have the same behavior currently when closing the locale suggestions component, so it appears that it's just the login with email content that starts shifting vertically after the change.

2024-03-21 11:13 UTC, niranjan-uma-shankar commented
True that, I noticed that too. It's just the login page that needs to be checked.

2024-04-01 11:07 UTC, nuriapenya commented
Hey @yuliyan thanks for taking care of this. No problem with the shifting; as you said, it is only for the email form, and I can't think of a solution that is responsive otherwise. So, LGTM!

2024-04-01 11:10 UTC, niranjan-uma-shankar approved these changes

2024-04-01 11:24 UTC, merged