Patterns Library: Start tracking calypso_pattern_library_view
Automattic/wp-calypso pull request #88763
Opened 2024-03-21 14:33 UTC by olaseni

This set of changes extend the `<PatternsPageViewTracker/>` component such that:

- `calypso_pattern_library_search` is no longer being tracked.
- `calypso_pattern_library_view`  is now being tracked

2024-03-21 15:34 UTC, fredrikekelund approved these changes
The `calypso_pattern_library_view` works as expected 👍 I left a couple of comments that would be good to address before landing this, but seeing as I'm AFK tomorrow, I'll approve this straight away to unblock you

2024-03-21 15:34 UTC, fredrikekelund commented on client/my-sites/patterns/components/page-view-tracker.tsx
>  	}, [ category, isDevAccount, isLoggedIn ] );
I think we could wrangle the updated properties for the `calypso_pattern_library_filter` event too in this PR.

2024-03-21 15:34 UTC, fredrikekelund commented on client/my-sites/patterns/components/page-view-tracker.tsx
> +	const [ debouncedSearchTerm, setDebouncedSearchTerm ] = useState( searchTerm );
👍

2024-03-21 15:34 UTC, fredrikekelund commented on client/my-sites/patterns/components/pattern-library/index.tsx
> +	const type = patternTypeFilter === PatternTypeFilter.REGULAR ? 'pattern' : 'page-layout';
```suggestion
	const tracksPatternType = patternTypeFilter === PatternTypeFilter.REGULAR ? 'pattern' : 'page-layout';
```
It doesn't have to be this exact name, but seeing as this component already holds a fair amount of code, I think we should be more specific with the variable names.

2024-03-21 15:34 UTC, fredrikekelund commented on client/my-sites/patterns/components/pattern-library/index.tsx
>  		} );
Maybe we should consider moving this into `PatternsPageViewTracker` now that we pass the `view` prop to that component?

2024-03-21 19:00 UTC, olaseni commented on client/my-sites/patterns/components/page-view-tracker.tsx
>  	}, [ category, isDevAccount, isLoggedIn ] );
Good eye!

2024-03-21 20:36 UTC, olaseni commented on client/my-sites/patterns/components/pattern-library/index.tsx
> +	const type = patternTypeFilter === PatternTypeFilter.REGULAR ? 'pattern' : 'page-layout';
`patternType` sounds okay.

2024-03-22 10:43 UTC, nightnei requested changes
LGTM and works as expected, but as I see, now we fire the even `calypso_pattern_library_view ` two times:
<img width="1522" alt="Screenshot 2024-03-22 at 10 36 00" src="https://github.com/Automattic/wp-calypso/assets/5598437/c3038b80-61b9-4e0b-948b-2e209ba06705">

I double checked - before we had also two times... hm.

Maybe I am missing something, but I suppose that it's not expected behaviour. And to fix it we need to do boolean conversion here https://github.com/Automattic/wp-calypso/pull/88763/files#r1535527198

2024-03-22 12:53 UTC, nightnei commented on client/my-sites/patterns/components/page-view-tracker.tsx
> +	}, [ isDevAccount, isLoggedIn, debouncedSearchTerm, patternTypeFilter, view ] );
```suggestion
	}, [ !! isDevAccount, isLoggedIn, debouncedSearchTerm, patternTypeFilter, view ] );
```

2024-03-22 12:58 UTC, nightnei commented on client/my-sites/patterns/components/page-view-tracker.tsx
>  	const isDevAccount = useSelector( ( state ) => getUserSetting( state, 'is_dev_account' ) );
```suggestion
	const isDevAccount = !! useSelector( ( state ) => getUserSetting( state, 'is_dev_account' ) );
```

2024-03-22 13:09 UTC, nightnei approved these changes
LGTM and works as expected, at least no new bug. But I noticed existed bug which we discussed with @olaseni to address in separate task. Details: p1711112211244959/1711102034.681499-slack-C06ELHR6L9J

2024-03-22 13:26 UTC, merged