Add/a4a/marketplace pressable section
Automattic/wp-calypso pull request #88849
Opened 2024-03-25 11:45 UTC by jkguidaven

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-03-25 11:57 UTC, jkguidaven commented on client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/style.scss
> +	border: 1.5px solid var(--studio-black);
No equivalent theme properties for studio black so I am force to use it directly.

2024-03-25 12:00 UTC, jkguidaven commented on client/a8c-for-agencies/sections/marketplace/pressable-overview/plan-selection/details.tsx
> +					</Button>
This is not 100% clear to me. I am basing the button on Pressable's existing pricing page, found at https://pressable.com/pricing/. Let me know what you think.

2024-03-25 13:01 UTC, simonktnga8c commented
Looks good to me @jkguidaven 👍 

The only issues I can see are that there should be an "s" at the end of "WordPress Installs" and "Number of visits".

2024-03-26 06:51 UTC, jkguidaven commented
> Looks good to me @jkguidaven 👍
> 
> The only issues I can see are that there should be an "s" at the end of "WordPress Installs" and "Number of visits".

Thanks for catching this. This has been fixed 👍

2024-03-26 11:43 UTC, madebynoam requested changes
Thanks for this @jkguidaven!

A small detail: On the containers we should have a 4px rounded corners:
![image](https://github.com/Automattic/wp-calypso/assets/8889977/94e23e22-3ce4-4b38-af9f-31afae631ab3)

On my live link, the slider only shows "More".
<img width="1049" alt="image" src="https://github.com/Automattic/wp-calypso/assets/8889977/b8dee399-4b13-4ab2-b89b-0fc202edfa43">

I'll try to test locally, to see if it works.

2024-03-27 09:03 UTC, jkguidaven commented
> A small detail: On the containers we should have a 4px rounded corners:

Good catch! This has been addressed in #88889. 👍 

> On my live link, the slider only shows "More".

I apologize for not mentioning this in the instructions. You need to sign up as an A4A Agency to access the data.  

Can you try to sign up here: https://agencies.automattic.com/signup.
This should set up your account. Also after signing up, please confirm with @Automattic/jetpack-Avalon if your account is non-billable so you won't accidentally get charged.

2024-03-27 09:08 UTC, closed without merging

2024-03-27 09:08 UTC, jkguidaven commented
Hi everyone,

I have to split this PR into four parts to make it much easier for devs to review. See below:

#88887
#88888
#88889
#88890

In that case, I am closing this PR.