Scheduled Updates: Add schedule timeline logs screen
Automattic/wp-calypso pull request #89090
Opened 2024-04-01 21:27 UTC by bogiii

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-04-02 10:11 UTC, JanaMW27 commented
I have shared these notes over on Slack, but I am bringing them here for reference:
A couple of notes from my side:
- I would add the number of plugins in the right corner with an info icon to show the list of plugins on hover.
- Are the colors on the icons dictated by the color palette that you have selected? Which colors would we use on default? Because with the current palette, we have 2 different greens, and it is a bit confusing.
- I would use a different format for the date to separate one block from the other, use a darker background for this section, remove the separation from one day to the next, and change the icon to a calendar icon.
- I would center the icon with the horizontal row rather than with the time.

2024-04-04 13:34 UTC, TimBroddin requested changes
This looks amazing!

Two small remarks:

- Maybe show seconds for the times? This way you can get a feeling of how long each step takes.
- The button is not vertical aligned. Looking at the code, this seems to be a restriction of the timeline component - but we can probably fix this in CSS `(align-self: center` on 
`.timeline .timeline-event .timeline-event__action-button-wrapper`)

![CleanShot 2024-04-04 at 15 29 08@2x](https://github.com/Automattic/wp-calypso/assets/528287/743f2c10-d4f2-42b2-9c89-a963ee709ed6)

2024-04-04 13:57 UTC, bogiii commented
> Maybe show seconds for the times? This way you can get a feeling of how long each step takes.

This will be covered in the next PR

> The button is not vertical aligned.

Fixed
<img width="703" alt="Screenshot 2024-04-04 at 15 55 57" src="https://github.com/Automattic/wp-calypso/assets/1241413/bcd09b8c-b2be-47fa-a4f3-b201cac491ba">

2024-04-04 13:59 UTC, zaerl approved these changes
Great start! :shipit:

2024-04-04 14:07 UTC, TimBroddin approved these changes

2024-04-04 14:20 UTC, merged