Help Center: Add articles feedback form
Automattic/wp-calypso pull request #89175
Opened 2024-04-03 17:37 UTC by renancarvalho

Related to #86531

## Proposed Changes

* This PR adds a small feedback form at the end of articles. More context #86531

![image](https://github.com/Automattic/wp-calypso/assets/52076348/d89646cc-9326-48a1-9957-24add377df75)

## Testing Instructions

* Use live link
* Navigate to any article in Help Center and scroll all the way down
* You should see the feedback 👍 or 👎 
* After selecting “yes” or “no”, the users should be able to optionally submit any free text
* With Track Vigilante (PCYsg-T9m-p2), check if the event `calypso_inlinehelp_article_feedback_click` is being logged
* Also Make sure to check atomic sites
* Results can be found in Crowd Signal (https://app.crowdsignal.com/), search for `HelpCenter articles feedback`
* The after submitting animation is from Crowd Signal, we can provide a custom message, will investigate what is the best.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-04-04 11:17 UTC, renancarvalho commented on packages/help-center/src/components/help-center-feedback-form.tsx
> +			<iframe
Loads `crowdsignal` survey, the submit happens in this tool and not in HelpCenter.

2024-04-04 13:25 UTC, agrullon95 commented on packages/help-center/src/components/help-center-feedback-form.tsx
> +					// 2 is used as `no` in crowdsignal as well, do no change
Small change here to "Do not change"

2024-04-04 17:21 UTC, agrullon95 requested changes
@renancarvalho - Nice work!

We should update the icons to emojis (Edit: This can be updated in another PR) and add the translation function to the iframe title.
The feedback survey is triggering the tracks event and tracking in crowdsignal correctly.

2024-04-04 17:21 UTC, agrullon95 commented on packages/help-center/src/components/help-center-feedback-form.tsx
> +					{ __( 'Yes' ) } <ThumbsUpIcon />
Let's update this to use thumbs-up emoji to match the /support.

2024-04-04 17:21 UTC, agrullon95 commented on packages/help-center/src/components/help-center-feedback-form.tsx
> +					{ __( 'No' ) } <ThumbsDownIcon />
Let's update this to use thumbs-down emoji to match the /support.

2024-04-04 17:21 UTC, agrullon95 commented on packages/help-center/src/components/help-center-feedback-form.tsx
> +				title="Feedback Form"
Lets use the translation function here.

2024-04-05 09:46 UTC, renancarvalho commented
@agrullon95 thank you for reviewing, regarding the 👍 and 👎 (emoji or icon), I got these icons from Calypso itself, I think it makes more sense to match Calypso "style", WDYT?

2024-04-05 11:16 UTC, agrullon95 commented
> @agrullon95 thank you for reviewing, regarding the 👍 and 👎 (emoji or icon), I got these icons from Calypso itself, I think it makes more sense to match Calypso "style", WDYT?

Let's keep it as is. I misread the slack conversation regarding these icons/emojis.

2024-04-05 15:06 UTC, agrullon95 approved these changes
The PR LGTM now. I tested on Simple and Atomic. We can wait for translation before merging.

2024-04-15 15:50 UTC, merged