Site Migration: Update error message to include the invalid URL
Automattic/wp-calypso pull request #89546
Opened 2024-04-15 17:53 UTC by sixhours

Related to paYKcK-4n3-p2#comment-3248 

## Proposed Changes

* It was suggested the error messages within this flow could be more helpful. This PR updates the error message for invalid URLs to specify the text you've input.
* If we opt to make this change, we should roll it out to EN locales only at first, since we'll need time for updated translations to come through. Either that or ensure this PR gets String Freeze'd before shipping.

**Before**

<img width="621" alt="Screenshot 2024-04-15 at 1 52 18 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/d63a617d-7ab6-4ff2-8e34-9d8c0e3500de">

**After**

<img width="638" alt="Screenshot 2024-04-15 at 1 52 10 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/a829f256-0392-4349-b13d-f4af6593cf86">

## Testing Instructions

* TBD

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-04-15 17:59 UTC, gabrielcaires commented
@sixhours  What is the benefit of repeating the same value we are already showing on the input?

2024-04-15 18:10 UTC, sixhours commented
> @sixhours What is the benefit of repeating the same value we are already showing on the input?

@andres-blanco mentioned it in a comment on that thread:

> It doesn’t mention the (invalid) URL you entered.

My thinking was the repetition might help them see the error in their URL.

But maybe we just need to not show the error message when the `urlValue` is empty?

2024-04-15 18:26 UTC, gabrielcaires commented
>  But maybe we just need to not show the error message when the `urlValue` is empty?
Agree 👍 

> My thinking was the repetition might help them see the error in their URL.

Based on the data we have gathered, it seems that users are having trouble understanding the meaning of URL.  
We have an issue just to improve the screen copy. #89543

2024-04-16 08:32 UTC, gabrielcaires commented
@sixhours What do you think about maintaining this PR by improving the error message and the other one updating the overall copy? My concern is we probably will have a revision that can make it hard to keep track of multiple PRs.

Regarding the error message, considering the high % of users setting wrong values as a domain.
What do you think about introducing an error message specific to users that set any value without a TLD?

Something like,
"Hey, I think you missed the domain suffix, they usually are (.com, .org, etc...)."
Just an example, I don't think it is a good copy :D

2024-04-16 19:17 UTC, sixhours commented
This change will cause issues because sometimes we show an error message after validating the URL and we preserve the urlValue in the text input, other times we'll validate the URL and clear the urlValue from the text input.

That's how you can end up in a state where the screen shows an error message but not the URL you submitted because they've entered an invalid URL like `something.aisdfua`.

<img width="642" alt="Screenshot 2024-04-16 at 3 17 07 PM" src="https://github.com/Automattic/wp-calypso/assets/2124984/130e9189-1461-485b-8672-be59706801ca">

I've been trying to figure out how to preserve the urlValue when it is invalid so we can offer the user more context.

2024-04-17 09:03 UTC, gabrielcaires commented
> This change will cause issues because sometimes we show an error message after validating the URL and we preserve the urlValue in the text input, other times we'll validate the URL and clear the urlValue from the text input.


Thanks for sharing it, I can take a look while you are in AFK.

2024-04-18 16:33 UTC, gabrielcaires commented
I think the form needs to be refactored to reduce the # of internal states.
setState is async and since we have multiples happening, we probably causing race conditions.

2024-04-24 09:02 UTC, bogiii requested changes

2024-04-24 09:02 UTC, bogiii commented on client/blocks/import/capture/capture-input.tsx
> +					className={ classnames( { 'is-error': showValidationMsg && urlValue } ) }
There is a `showValidationMsg` field; why is this additional condition not placed there since it is dedicated to showing/hiding validation messages?

2024-06-05 13:09 UTC, sixhours commented
This is well out of date and we seem to have conflicting thoughts on how to address the original issue around lack of clarity, so I'm going to close this and create a new issue.

2024-06-05 13:09 UTC, closed without merging