Congrats: remove legacy header code
Automattic/wp-calypso pull request #89823
Opened 2024-04-23 21:00 UTC by chad1008

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-04-23 21:01 UTC, chad1008 commented on client/my-sites/checkout/checkout-thank-you/header.jsx
Removing the basic domain transfer code, but leaving the nested condition for delayed transfers in place, as I believe those don't pass flow through the refactored congrats pages.

2024-04-24 17:56 UTC, chad1008 commented on client/my-sites/checkout/checkout-thank-you/header.jsx
> +		if ( isDelayedDomainTransfer( primaryPurchase ) ) {
Removing the basic domain transfer code, but leaving the nested condition for delayed transfers in place, as I believe those don't pass flow through the refactored congrats pages.

2024-04-24 19:18 UTC, chad1008 commented on client/my-sites/checkout/checkout-thank-you/header.jsx
> -	renderSimplifiedContent() {
Because this was only being called after a successful `isPlan` check, and those purchases won't load this header any longer, it felt like it made sense to remove this completely, along with the two tests related to `isSimplified`

2024-04-25 12:51 UTC, nightnei requested changes
Also, AFAIS we can remove variable export `class CheckoutThankYouHeader extends PureComponent {` and keep only default export.

2024-04-25 12:51 UTC, nightnei requested changes

2024-04-25 12:51 UTC, nightnei commented on client/my-sites/checkout/checkout-thank-you/header.jsx
> -		siteUnlaunchedBeforeUpgrade: PropTypes.bool,
Let's also clear everything from components where we use it (unfortunately we don't have TS here to see errors ☹️)

https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/checkout/checkout-thank-you/index.tsx#L725

2024-04-25 15:52 UTC, nightnei commented on client/my-sites/checkout/checkout-thank-you/header.jsx
> -		siteUnlaunchedBeforeUpgrade: PropTypes.bool,
Ignore it, I am working around this place so I will clean it up

2024-04-25 15:52 UTC, nightnei approved these changes

2024-04-25 16:18 UTC, merged