Akismet checkout: Enable coupon field in checkout.
Automattic/wp-calypso pull request #89867
Opened 2024-04-24 18:07 UTC by elliottprogrammer

Akismet checkout previously was not showing the coupon field, restricting the ability to enter a coupon code for Akismet products.

This PR enables the coupon field in Akismet checkout.

#### Screenshots

BEFORE | AFTER
--- | ---
![Screen Shot 2024-04-24 at 14 01 08](https://github.com/Automattic/wp-calypso/assets/11078128/57870455-7ebd-49b0-923c-de1a184ca053) | ![Screen Shot 2024-04-24 at 14 03 21](https://github.com/Automattic/wp-calypso/assets/11078128/6a31f13c-b90a-4854-ad9c-09590f6b8ed6)

## Testing Instructions

- Checkout and run this branch locally, or click the _Calypso Live (direct link)_ below.
- Go to checkout with any Akismet product, i.e.- `/checkout/akismet/ak_pro5h_yearly:-q-1`
- Verify that you can see the "Have a coupon?" link just below Step 2,  _Payment Method_ section in checkout (See screenshot)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?
- [ ]

2024-04-26 16:07 UTC, CodeyGuyDylan requested changes
I am only able to see the coupon field if I already have a saved card on file 🤔 

Here is an example of no saved card, even if I fill out the card info, the field does not show up

![image](https://github.com/Automattic/wp-calypso/assets/65001528/98fa4617-c93f-4b6f-af1d-ac899e685066)

If I use my sandbox where I have a saved card on file, I see the coupon field

![image](https://github.com/Automattic/wp-calypso/assets/65001528/a5f2be7d-8f34-4037-8cf1-a8f5439031cf)

2024-04-30 13:18 UTC, elliottprogrammer commented
Thanks for reviewing @CodeyGuyDylan! 😃

> I am only able to see the coupon field if I already have a saved card on file 🤔
> 
> Here is an example of no saved card, even if I fill out the card info, the field does not show up

Hmm.. I am not able to reproduce that. 🤔. I don't have any stored/saved credit cards, but the coupon field is still showing up for me.  See screenshot ⤵️

![Screen Shot 2024-04-30 at 09 02 58](https://github.com/Automattic/wp-calypso/assets/11078128/cc2d792b-17fe-4297-87d4-40cddbfea2b0)

I see in your screenshot you posted, it's showing the "Assign payment method later" option. I think that only shows up when it's a zero dollar or free purchase... (in which it would make sense that the coupon field doesn't show up). Were you maybe trying to purchase using A8C free credits (making it a zero dollar purchase)?

Can you try it again and make sure there is a dollar amount to pay (not paying the whole thing with free credits)?

2024-04-30 15:45 UTC, CodeyGuyDylan commented
> Can you try it again and make sure there is a dollar amount to pay (not paying the whole thing with free credits)?

This seems to be the issue, apologies for not catchiing that when I was testing, I think everything works correctly

2024-04-30 15:49 UTC, CodeyGuyDylan approved these changes
LGTM!

2024-04-30 15:58 UTC, sirbrillig approved these changes
No objection from a8c Payments.

2024-04-30 17:18 UTC, merged