Sites Dashboard v2: Update styles for GSV
Automattic/wp-calypso pull request #89894
Opened 2024-04-25 10:32 UTC by candy02058912

Fixes https://github.com/Automattic/dotcom-forge/issues/6714

## Proposed Changes

-  Update header font styles
-  Update link styles (color and size)
-  Adjust site icon size
-  Add box-shadow to site icon

Figma: PZtnZ1nHhnBrsuXDoMJHPD-fi-446_63469

| Before  | After |
| :-------------: | :-------------: |
| <img src="https://github.com/Automattic/wp-calypso/assets/6586048/fbce9ba7-d0eb-4086-95c9-fecaa345d1b5">  | <img src="https://github.com/Automattic/wp-calypso/assets/6586048/b096212d-52a2-4ca2-82a5-a0805ec71db3">|

## Testing Instructions

* Go to /sites?flags=layout/dotcom-nav-redesign-v2
* Make sure the styles are aligned with Figma
* Test on mobile to see if there's anything weird

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-04-25 10:37 UTC, cleacos requested changes
Sorry... This one is touching the ItemPreviewPane components.

I'll unlock it after merging the PR I'm working on with changes.

2024-04-26 00:07 UTC, cleacos commented on client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/index.tsx
> +					/>
This was updated. Already in trunk

2024-04-26 00:08 UTC, cleacos commented on client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/index.tsx
> +						) }
Updated. Check trunk

2024-04-26 00:08 UTC, cleacos commented on client/a8c-for-agencies/components/items-dashboard/item-preview-pane/types.ts
> +	adminUrl?: string;
Updated. Check trunk

2024-04-26 00:12 UTC, cleacos reviewed
Check the conflicts... but probably it will be better to start fresh, and cherry-pick your code.

2024-04-26 08:40 UTC, taipeicoder approved these changes
Code LGTM 👍 
Some non-blocking notes on my end:

1. The close button position is not as in Figma.

| Figma | PR |
| --- | --- |
| ![Screenshot 2024-04-26 at 4 33 36 PM](https://github.com/Automattic/wp-calypso/assets/797888/ea521571-c0b7-4921-b7c4-6507db3f6ce9) |  ![Screenshot 2024-04-26 at 4 34 01 PM](https://github.com/Automattic/wp-calypso/assets/797888/088d5485-4369-4b41-82b0-44cb07a5cbbe)| 

2. The external icon in Figma is 16x16, but in the PR seems to be 24x24.
3. In smaller viewports, the text doesn't seem vertically aligned and the icons too big in comparison with the text. 
![Screenshot 2024-04-26 at 4 36 09 PM](https://github.com/Automattic/wp-calypso/assets/797888/d52f689f-99be-46bb-a474-0833bb245931)

2024-04-26 10:13 UTC, candy02058912 commented
Will update the external icon link, went missing after the rebase.

2024-04-26 16:01 UTC, allilevine commented
> The external icon in Figma is 16x16, but in the PR seems to be 24x24.

It looks like the icon is now 16x16, but it's not aligned with the text:

<img width="1423" alt="Screen Shot 2024-04-26 at 11 58 42 AM" src="https://github.com/Automattic/wp-calypso/assets/1689238/d3540bcd-571a-4d93-a604-71b1d8dddda2">

Figma:

<img width="1116" alt="Screen Shot 2024-04-26 at 11 59 56 AM" src="https://github.com/Automattic/wp-calypso/assets/1689238/3fa21100-d7f0-4802-a628-6b7f99b448b5">

Non-blocking, as noted above, but we might want to make it slightly larger.

2024-04-26 16:03 UTC, allilevine commented
> 1. The close button position is not as in Figma.

I opened a follow-up: https://github.com/Automattic/dotcom-forge/issues/6772

2024-04-26 16:27 UTC, cleacos approved these changes
At the A4A side it looks good!

![image](https://github.com/Automattic/wp-calypso/assets/9832440/194160cb-427f-4b8e-ab3a-112d31bc3554)
At UI/design level, is the WP Admin link okay? it looks weird... font size...

LGTM!

2024-04-26 16:58 UTC, DustyReagan approved these changes
Nice work! 🎉  I'll go ahead and merge this one and we can followup on the remaining styling tweaks.

2024-04-26 16:59 UTC, merged