Add migration message and ticket creation
Automattic/wp-calypso pull request #89896
Opened 2024-04-25 11:21 UTC by heavyweight

Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-03 14:15 UTC, agrullon95 commented on client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/index.tsx
> +						{ __( `We'll explain you how to securely share your site credentials with us.` ) }
Can we double-check this sentence? It doesn't sound grammatically correct.
Small change to make it sound better: "We'll explain how to securely share your site credentials with us."

2024-05-06 08:21 UTC, escapemanuele commented on client/landing/stepper/declarative-flow/internals/steps-repository/importer-wordpress/index.tsx
> +					} }
On second thought, I think we probably show `submit` here, and then handle it in the flow.

2024-05-06 12:15 UTC, alshakero requested changes
I reviewed the code and it looks great. Beautiful work. Found two tiny issues. I'll check the tests and test it now.

2024-05-06 12:15 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/importer-migrate-message/hooks/use-submit-migration-ticket.ts
> +		sendTicket,
I don't think `useCallback` is adding any value. We can just return the return value of `useMutation`.

2024-05-06 12:15 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/importer-wordpress/index.tsx
> +							redirect_to: `/setup/${ props.flow }/migrateMessage?siteSlug=${ siteSlug }`,
I would escape both of these. 
```suggestion
							redirect_to: `/setup/${ encodeURIComponent ( props.flow ) }/migrateMessage?siteSlug=${ encodeURIComponent( siteSlug ) }`,
```

2024-05-06 12:15 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-upgrade-plan/index.tsx
> +	const goToMigrationAssistanceCheckout = ( userAcceptedDeal: boolean ) => {
This will fail type checks since it's expected to be `()` [here](https://github.com/Automattic/wp-calypso/blob/add/import-migration-ticket/client/landing/stepper/declarative-flow/internals/components/migration-assistance-modal/index.tsx#L16). Maybe make it optional?

```suggestion
	const goToMigrationAssistanceCheckout = ( userAcceptedDeal = false ) => {
```

2024-05-06 16:46 UTC, michaeldcain reviewed
I didn't review the other parts, but from a Payments perspective, this looks fine.

2024-05-07 08:58 UTC, renancarvalho approved these changes
Great work! Tested on import hosted, import focused flow and site-migration, all working fine 👍

2024-05-07 10:11 UTC, merged