A4A: add finish signup screen
Automattic/wp-calypso pull request #89988
Opened 2024-04-26 19:59 UTC by andrii-lysenko

Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/357

## Proposed Changes

This PR wraps up the work on the Streamline signup flow. After successful login/signup we redirect user to `signup/finish` where we finish registration.

@jkguidaven could you please verify if loading Hubspot script here is done properly?

Here are the tested flows:

**New user registration**

https://github.com/Automattic/wp-calypso/assets/60262784/aa65fc67-a3ec-461f-a7c5-70ca9c11d789

**Existing user**

https://github.com/Automattic/wp-calypso/assets/60262784/af3cb623-faea-4ecf-bae1-21db00fbdd2f

**Error in the Form**

https://github.com/Automattic/wp-calypso/assets/60262784/56c13fff-914e-4880-8618-4853ccb17593

## Testing Instructions

- Using current branch (preferrable through the local build) verify different scenarios of navigating to `/signup` endpoint and flows

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-04-26 20:01 UTC, andrii-lysenko commented on client/a8c-for-agencies/sections/signup/controller.tsx
> +export const tokenRedirect: Callback = ( ctx, next ) => {
We use similar logic as with `/connect` endpoint here to fill the tocken and then proceed to finish.

2024-04-26 21:03 UTC, gogdzl requested changes
Great job! The code looks quite good, we just have to adjust a few details here and there.

My biggest concern is about our local storage, we are not cleaning it up. We should set up a couple of places to clean this up; one of them being when we successfully create the agency, another one could be somewhere where the user might load the screen for the first time.

Other problem that I had was with our validation, we are only validating the fields when we try to create the agency, this takes us back to the first form if we have any kind of validation problem, even after we go through all the steps to create a WPCOM account. I think we could address this in a later PR to make the review easier to read, and also to improve code traceability. 
Here's a screenshot of what happened after I went through all the steps:
![image](https://github.com/Automattic/wp-calypso/assets/37049295/65e4dc2d-d750-4f27-be2f-4137063daaff)

After getting this error, I filled all the fields and the agency was registered just fine.

Great job overall!

2024-04-26 21:03 UTC, gogdzl commented on client/sections.js
> +		paths: [ '/signup', '/signup/finish', '/connect/oauth/token' ],
Isn't `'/connect/oauth/token'` supposed to be `'/signup/oauth/token'`?

2024-04-26 21:03 UTC, gogdzl commented on client/a8c-for-agencies/sections/signup/signup-form/index.tsx
> +				initialValues={ signupData }
Nice thinking here, makes sense to get stored data to fill in the form.

2024-04-26 21:03 UTC, gogdzl commented on client/a8c-for-agencies/sections/signup/primary/agency-signup-finish/index.tsx
> +	const notificationId = 'a4a-agency-signup-form';
I'm not sure about this comment, so feel free to ignore me: Isn't it a good idea to have an exclusive id here?

2024-04-26 22:53 UTC, andrii-lysenko commented on client/a8c-for-agencies/sections/signup/primary/agency-signup-finish/index.tsx
> +	const notificationId = 'a4a-agency-signup-form';
Yeah, I assumed it will actually be the same notification as in `/signup` we could keep the same one

2024-04-26 22:54 UTC, andrii-lysenko commented on client/sections.js
> +		paths: [ '/signup', '/signup/finish', '/connect/oauth/token' ],
Good catch, thanks!

2024-04-26 23:00 UTC, andrii-lysenko commented
@gogdzl Thank you for a thorough review.
Yes, I was thinking for clearing the storage, just forgot to add that. I wouldn't want thought to clear the storage on `/signup` page as it's easier for user to have the data he already filled. Assuming he never finished registration.
As per form validation, I definitely agree. Though, it's probably a regular maintenance task as it should work in both, new and old flows.

2024-04-29 19:10 UTC, gogdzl approved these changes
Great job! LGTM!

2024-04-29 20:27 UTC, merged