Nav Redesign v2: fix sites pagination footer
Automattic/wp-calypso pull request #90015
Opened 2024-04-29 08:04 UTC by roo2

WIP: this needs to be tested with A4A

Fixes the footer on the /sites page on mobile and tablet screens

**Before**
<img width="600" alt="Screenshot 2024-04-29 at 4 23 21 pm" src="https://github.com/Automattic/wp-calypso/assets/22446385/47f6101d-fc9b-4704-80bd-b899a2a95c7e">

**After**
<img width="600" alt="Screenshot 2024-04-29 at 4 23 32 pm" src="https://github.com/Automattic/wp-calypso/assets/22446385/8ff68eff-bfad-4f24-bc80-398dce008314">

### Test instructions

2024-04-29 09:02 UTC, roo2 commented
hmm I just haven't been able to test it on the A4A side, I've been able to get it set up locally, but not sure how many sites I need to connect to have the pagination control set up?

<img width="769" alt="Screenshot 2024-04-29 at 7 01 19 pm" src="https://github.com/Automattic/wp-calypso/assets/22446385/8d84b975-904a-4cae-89ef-ad9e52c5ff55">

2024-04-29 09:23 UTC, taipeicoder approved these changes
LGTM with A4A!

Mobile:
![Screenshot 2024-04-29 at 5 21 38 PM](https://github.com/Automattic/wp-calypso/assets/797888/f9a13775-6967-4bba-af00-0114a8298da6)

Desktop:
![Screenshot 2024-04-29 at 5 21 50 PM](https://github.com/Automattic/wp-calypso/assets/797888/84d5bab3-64f6-484c-91ef-afe1dccb0d2b)

2024-04-29 10:37 UTC, cleacos requested changes
It breaks a bit A4A:

![image](https://github.com/Automattic/wp-calypso/assets/9832440/c5aee12a-b56d-41b3-9a27-39781fa76506)

2024-04-29 10:44 UTC, cleacos commented
VS Production:

![image](https://github.com/Automattic/wp-calypso/assets/9832440/9651b559-ccf0-4a02-84ad-d27c65c6f8ed)

2024-04-30 01:15 UTC, roo2 commented
hey I spent the morning trying to work out how to test jetpack cloud because I can see that would be affected, but I wasn't able to work out how to get the /sites route to load there unfortunately. I've decided to just move the changes to be calypso only so I don't have to test jetpack cloud.
<img width="1343" alt="Screenshot 2024-04-30 at 11 04 01 am" src="https://github.com/Automattic/wp-calypso/assets/22446385/21e27eb3-0e76-47c1-a327-74b427fe443c">

2024-04-30 03:12 UTC, merged