Updated header styles for select reader sections
Automattic/wp-calypso pull request #90174
Opened 2024-05-01 18:19 UTC by davemart-in

## Description

This PR aims to remedy https://github.com/Automattic/loop/issues/175

Multiple reader sections have this awkward looking square looking header. We can likely remove the border around it and add a header tag to clean this up a bit:

## Before

![Image](https://github.com/Automattic/loop/assets/5634774/7756c1a3-ae04-4b3d-b509-6636afd39316)

## After

![Image](https://github.com/Automattic/loop/assets/5634774/2175d6a8-3ccb-4f1d-bb83-2b1a2f6d3bc9)

## Testing instructions
- Apply this patch
- Visit /read/a8c
- Visit /read/p2

2024-05-02 07:26 UTC, Aurorum requested changes
These styles changes aren't specific enough, I'm afraid! 😄 Probably best to make them just in the Reader and not the component itself. 

<img width="811" alt="Screenshot 2024-05-02 at 08 25 12" src="https://github.com/Automattic/wp-calypso/assets/43215253/cd7492a5-8a8e-4392-9fa7-8b548ec922aa">

2024-05-02 20:48 UTC, davemart-in commented
Thanks for catching that! I'll get a fix up for this.

2024-05-03 03:07 UTC, davemart-in commented
I believe this should be fixed now.

2024-05-03 06:11 UTC, roo2 approved these changes
LGTM!

2024-05-03 06:54 UTC, merged