A4A: Update the Referrals page based on new design.
Automattic/wp-calypso pull request #90327
Opened 2024-05-06 16:16 UTC by jkguidaven

This PR updates the Referrals page based on the new design.

**Updated Referrals page**
| Before | After |
|--------|--------|
| <img width="966" alt="Screenshot 2024-05-07 at 12 14 11 AM" src="https://github.com/Automattic/wp-calypso/assets/56598660/f7b2338d-fbd8-4670-8a7e-b76d10d7d6b1"> | <img width="966" alt="Screenshot 2024-05-07 at 12 10 52 AM" src="https://github.com/Automattic/wp-calypso/assets/56598660/fa111e03-3c39-45e3-a041-06c827f9abfa"> |

**Dedicated Commission details and terms page**
<img width="1350" alt="Screenshot 2024-05-07 at 12 11 02 AM" src="https://github.com/Automattic/wp-calypso/assets/56598660/d1884ce9-aeeb-404a-b91f-b8b4f8a142f1">

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/438

## Proposed Changes

* Update the Referrals page with a more simplified text.
* Add a dedicated Commission details and terms page.

## Testing Instructions

* Use the A4A live link and go to `/referrals`
* Confirm that the page matches the new design.
* Click the 'How can I earn?' link.
* Confirm that you are redirected to the new dedicated Commission details and terms page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-06 16:24 UTC, jkguidaven commented on client/a8c-for-agencies/sections/referrals/primary/footer/index.tsx
> +	const tosLink = ''; // FIXME: Add the correct link to the Terms of Service.
@madebynoam, I'd like to clarify which TOS link I should use in the footer.

2024-05-06 17:39 UTC, rcanepa commented on client/a8c-for-agencies/sections/referrals/primary/footer/index.tsx
> +	const tosLink = ''; // FIXME: Add the correct link to the Terms of Service.
@jkguidaven, the TOS link should point to https://automattic.com/for-agencies/platform-agreement/.

2024-05-06 18:17 UTC, rcanepa commented on client/a8c-for-agencies/sections/referrals/primary/footer/index.tsx
> +	const tosLink = ''; // FIXME: Add the correct link to the Terms of Service.
```suggestion
	const tosLink = 'https://automattic.com/for-agencies/platform-agreement/';
```

2024-05-06 18:20 UTC, rcanepa commented on client/a8c-for-agencies/sections/referrals/primary/footer/index.tsx
> +	const tosLink = ''; // FIXME: Add the correct link to the Terms of Service.
I went ahead and added the link myself.

2024-05-06 21:15 UTC, jeffgolenski commented
Notice is looking good, James. Just two small adjustments to help with legibility. Can we change the line-height and top margin of the description?

`.a4a-migration-offer__wrapper .a4a-migration-offer__description {
    color: var(--studio-gray-80);
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.65;
    margin-top: 16px;`

(feel free to change the margin to `rem` is that's what we're working with)

Current:
![CleanShot 2024-05-06 at 17 12 15](https://github.com/Automattic/wp-calypso/assets/214813/110d6471-c146-45aa-96a3-5088741d3ecb)


Proposed:
![CleanShot 2024-05-06 at 17 13 44](https://github.com/Automattic/wp-calypso/assets/214813/45020c2b-7384-4073-a826-d87a9f911abb)

2024-05-07 10:30 UTC, jkguidaven commented on client/a8c-for-agencies/sections/referrals/primary/footer/index.tsx
> +	const tosLink = ''; // FIXME: Add the correct link to the Terms of Service.
Thanks for adding the link. 👍

2024-05-07 10:42 UTC, jkguidaven commented
@jeffgolenski, thanks for the review and code snippet. I have applied it to the PR. 👍 

<img width="939" alt="Screenshot 2024-05-07 at 6 41 59 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/0cb44950-a75c-48c5-8f03-0247886f83e4">

2024-05-07 12:25 UTC, madebynoam requested changes
This is looking good. Thanks @jkguidaven!

Just a few notes:
1. Can we add a line break on the title so that there is no widow, and reads a bit easier:
<img width="977" alt="image" src="https://github.com/Automattic/wp-calypso/assets/8889977/1851ab99-b20c-4ae8-bae3-884476c65d92">

2. I saw that @jeffgolenski already covered the blue box edits.

2024-05-07 12:42 UTC, jkguidaven commented
> This is looking good. Thanks @jkguidaven!
> 
> Just a few notes:
> 
> 1. Can we add a line break on the title so that there is no widow, and reads a bit easier:
> 
> <img alt="image" width="977" src="https://private-user-images.githubusercontent.com/8889977/328518953-1851ab99-b20c-4ae8-bae3-884476c65d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODU1NDYsIm5iZiI6MTcxNTA4NTI0NiwicGF0aCI6Ii84ODg5OTc3LzMyODUxODk1My0xODUxYWI5OS1iMjBjLTRhZTgtYmFlMy04ODQ0NzZjNjVkOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTIzNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ4NWExNmExZGQ5OTU5ZDJhNjE1NDY0ZTBmZWExYjY0Y2FlYWRhNzAwN2U1NmEyM2FlYTA0ODM4NGM1MzFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vuEHYM7-9HGmpQf1RQ33GkIrPcF9vQTOrVIPrkjSqNs">
> 2. I saw that @jeffgolenski already covered the blue box edits.

This has been addressed. 👍 

<img width="1008" alt="Screenshot 2024-05-07 at 8 41 41 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/01f62a8f-5761-4d75-8021-ebd80b080672">

2024-05-07 12:43 UTC, madebynoam commented
> > This is looking good. Thanks @jkguidaven!
> > Just a few notes:
> > 
> > 1. Can we add a line break on the title so that there is no widow, and reads a bit easier:
> > 
> > <img alt="image" width="977" src="https://private-user-images.githubusercontent.com/8889977/328518953-1851ab99-b20c-4ae8-bae3-884476c65d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODU1NDYsIm5iZiI6MTcxNTA4NTI0NiwicGF0aCI6Ii84ODg5OTc3LzMyODUxODk1My0xODUxYWI5OS1iMjBjLTRhZTgtYmFlMy04ODQ0NzZjNjVkOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTIzNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ4NWExNmExZGQ5OTU5ZDJhNjE1NDY0ZTBmZWExYjY0Y2FlYWRhNzAwN2U1NmEyM2FlYTA0ODM4NGM1MzFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vuEHYM7-9HGmpQf1RQ33GkIrPcF9vQTOrVIPrkjSqNs">
> > 2. I saw that @jeffgolenski already covered the blue box edits.
> 
> This has been addressed. 👍
> 
> <img alt="Screenshot 2024-05-07 at 8 41 41 PM" width="1008" src="https://private-user-images.githubusercontent.com/56598660/328525173-01f62a8f-5761-4d75-8021-ebd80b080672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODYxMDIsIm5iZiI6MTcxNTA4NTgwMiwicGF0aCI6Ii81NjU5ODY2MC8zMjg1MjUxNzMtMDFmNjJhOGYtNTc2MS00ZDc1LTgwMjEtZWJkODBiMDgwNjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEyNDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMjgxZDY2NTlmNWFkMDlkMmY5NDQxZTRiZDE3OWExNWE1N2JkZTVmZTFmMzQ1MzBkYjYxYzI2YThhOWYyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMDSwO0pWAu1q-fSWSoigSAnfMgn53lkRR_7r3FnrIo">

Thank you, @jkguidaven!

2024-05-07 12:43 UTC, madebynoam approved these changes

2024-05-07 14:14 UTC, merged