Add site filter permissions check
Automattic/wp-calypso pull request #90384
Opened 2024-05-07 12:12 UTC by zaerl

Fixes https://github.com/Automattic/wp-calypso/issues/89968

## Proposed Changes

* Add `update_plugins` capability check
* Fix: add missing field to store type

## Testing Instructions

* Ensure to have a site where you don't have `update_plugins` capability. You can force it on the `WPCOM_JSON_API_Me_Sites_V1_2_Endpoint` endpoint.
* Go to `http://calypso.localhost:3000/plugins/scheduled-updates/edit/__ID__-...`
* Ensure the site is filtered away from the list.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-07 12:21 UTC, bogiii commented on client/blocks/plugins-scheduled-updates-multisite/schedule-form.tsx
> +import { SiteExcerptData } from '@automattic/sites';
Since we import type here, please update it to be `import type {...`

2024-05-07 12:53 UTC, TimBroddin reviewed
While testing I noticed that when calling `useSiteExcerptsQuery` with `[ 'atomic', 'capabilities' ]` I now get returned all P2's I'm part of as well 🤔 

## Situation with fetchFilter = `[ 'atomic' ]` and siteFilter = `() => true`

```
	const siteFilter = ( site: SiteExcerptData ): boolean => {
		return true;
	};
	const { data: sites } = useSiteExcerptsQuery( [ 'atomic' ], siteFilter );

	console.log('Amount of sites = ' + sites.length);

```

Result: `Amount of sites = 11`

## Situation with fetchFilter = `[ 'atomic', 'capabilities ]`  and siteFilter = `() => true`


```
	const siteFilter = ( site: SiteExcerptData ): boolean => {
		return true;
	};
	const { data: sites } = useSiteExcerptsQuery( [ 'atomic', 'capabilities' ], siteFilter );

	console.log('Amount of sites = ' + sites.length);

```

Result: `Amount of sites = 158`

## Situation with fetchFilter = `[ 'atomic', 'capabilities ]`  with siteFilter in place

```
	const siteFilter = ( site: SiteExcerptData ): boolean => {
		return ( site as SiteDetails ).capabilities?.update_plugins;
	};

	const { data: sites } = useSiteExcerptsQuery( [ 'atomic', 'capabilities' ], siteFilter );

	console.log('Amount of sites = ' + sites.length);
```

Result: `Amount of sites = 10` (as expected - but it's filtering from 158 sites and not my 11 Atomic sites)


I don't know if this matters a lot, since we're filtering on the capabilities inside siteFilter, but it surprised me and I wonder if this could cause any unforeseen issues.

2024-05-08 08:53 UTC, TimBroddin requested changes

2024-05-08 08:53 UTC, TimBroddin commented on client/blocks/plugins-scheduled-updates-multisite/schedule-form.tsx
> +	const { data: sites } = useSiteExcerptsQuery( [ 'atomic', 'capabilities' ], siteFilter );
Shouldn't this be `	const { data: sites } = useSiteExcerptsQuery(['atomic'], siteFilter, 'all', [ 'capabilities' ]) ; `?

2024-05-08 09:08 UTC, TimBroddin approved these changes
LGTM! 🚀

2024-05-08 09:20 UTC, merged