Global pages - add box shadow around content area frames
Automattic/wp-calypso pull request #90584
Opened 2024-05-10 14:31 UTC by Addison-Stavlo

Related to # Automattic/dotcom-forge#7072

## Proposed Changes

* Adds box shadow to sites, domains, and me content frames.

BEFORE
<img width="195" alt="Screenshot 2024-05-10 at 10 27 09 AM" src="https://github.com/Automattic/wp-calypso/assets/28742426/b96e32a4-83df-4ca8-bfe0-8df7a4004b30">

AFTER
<img width="205" alt="Screenshot 2024-05-10 at 10 27 15 AM" src="https://github.com/Automattic/wp-calypso/assets/28742426/075967b5-2358-4eff-ae1f-fd8813a4393b">

## Testing Instructions

* Run this calypso branch
* Visit /sites, verify there is a box shadow around the primary content frame.
* Visit /domains/manage, verify the same.
* Visit /me, verify the same.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-10 14:33 UTC, Addison-Stavlo commented on client/my-sites/domains/domain-management/list/bulk-all-domains.tsx
> +						box-shadow: 0px 0px 17.4px 0px rgba( 0, 0, 0, 0.05 );
Note - this is the only change I made in this file.  Previously it noted `box-shadow: none` and was missing the `;` breaking the next line style as well. Adding the `;` and saving caused the entire file to auto-format indentation and make these changes look much bigger.

2024-05-10 14:44 UTC, Addison-Stavlo commented on client/my-sites/domains/domain-management/list/bulk-all-domains.tsx
> +						box-shadow: 0 0 17.4px 0 rgba( 0, 0, 0, 0.05 );
This should be the only change I made to this file.  

Previously this had `box-shadow: none` without the ending semi-colon `;`. This broke the next line and auto formatting. As soon as i updated this style and added the semi-colon, saving caused auto format to upate alot of indentations and make this look like quite a bit more changes.

2024-05-10 19:54 UTC, DustyReagan approved these changes
Looks good!

2024-05-13 03:12 UTC, roo2 requested changes
it looks like the auto formatter changes are all in conflict with some other changes to the file now

2024-05-13 13:13 UTC, merged