Sign up: Add updated Site Intent step (WIP)
Automattic/wp-calypso pull request #90700
Opened 2024-05-14 16:30 UTC by agrullon95

Related to https://github.com/Automattic/wp-calypso/issues/90628

## Proposed Changes

* Add updated site intent screen based on designs from: https://www.figma.com/design/3u71fUJraClkRQiLrAORPf/Trail-Map-Project?node-id=3908-7311&m=dev

## Why are these changes being made?

* These changes are part of the initiative to improve the sign-up flow by helping tailor the onboarding experience based on the selected site intent option.

## Testing Instructions

* Checkout branch or use live link
* Navigate to `/setup/site-setup/intent?siteSlug={SITE_SLUG}`
* Compare changes to design (designs have not been finalized yet).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-14 16:30 UTC, agrullon95 commented on client/landing/stepper/declarative-flow/site-setup-flow.ts
> +			STEPS.INTENT_I2,
Temporarily changed to easily show changes in this PR within the `/site-setup` flow.

2024-05-14 16:31 UTC, agrullon95 commented on client/landing/stepper/declarative-flow/internals/steps-repository/intent-step-i2/intents.tsx
> +	const intents: Intent[] = [
Work in progress. Intents information will be updated when its finalized.

2024-05-14 16:42 UTC, alshakero requested changes
Beautiful! Can we give the cards some hover state?

2024-05-21 14:53 UTC, agrullon95 commented
Closing this PR and moving changes to: https://github.com/Automattic/wp-calypso/pull/90788

2024-05-21 14:53 UTC, closed without merging