Add large width on `/sites` and `/domains/manage`
Automattic/wp-calypso pull request #90779
Opened 2024-05-16 01:33 UTC by roo2

Adds max width to the sites and domains table 

Fixes 7186-gh-Automattic/dotcom-forge

1441px:

<img width="1432" alt="Screenshot 2024-05-16 at 11 30 50 am" src="https://github.com/Automattic/wp-calypso/assets/22446385/69ac7000-2912-45ca-b9a6-9200224a42de">

1800px:

<img width="1428" alt="Screenshot 2024-05-16 at 11 30 41 am" src="https://github.com/Automattic/wp-calypso/assets/22446385/bbaa2885-fef6-4363-935a-a786a99e23cc">

I've also applied a max width to the domains page to max.

I had to jump through a few hoops to implement this, in part this was to maintain the header effect where the line runs right across the page and keep everything lined up properly.

### Testing instructions

Test different widths and page states on the /sites page.

2024-05-16 06:29 UTC, fushar reviewed
I think we need some left and right padding; it looks awkward on wider screens. The paddings are there in production.

<img width="1380" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1525580/6a11fee6-ca4d-43d0-82a4-5db04177f2e8">

2024-05-16 10:41 UTC, cleacos commented
I left a comment in the issue

2024-05-17 02:00 UTC, roo2 commented
I've updated it so that the max width is only applied after >1920px wide screens, the table will be limited to 1400px and also added back in the side padding at this width, and tweaked alignment of the page number selector and header
<img width="1100" alt="Screenshot 2024-05-17 at 11 59 56 am" src="https://github.com/Automattic/wp-calypso/assets/22446385/f0ca901c-4ed5-4926-a722-d1b5f4374bf1">

2024-05-17 06:12 UTC, fushar approved these changes
It looks good to me now 👍

2024-05-17 06:59 UTC, cleacos requested changes
The table header is not aligned:

**Horizon:**
![image](https://github.com/Automattic/wp-calypso/assets/9832440/e5d66544-25a5-426e-8125-331d6a7d12f8)

**This PR:**
![image](https://github.com/Automattic/wp-calypso/assets/9832440/6a72ee11-976a-409d-9193-3a126a429e7d)

2024-05-19 23:02 UTC, roo2 commented
ahh thanks @cleacos , can't believe I missed that in my own screenshot! XD

2024-05-19 23:28 UTC, roo2 commented
Ahh I see I accidentally removed a first-child selector for the `td` padding, I've fixed it now:

<img width="973" alt="Screenshot 2024-05-20 at 9 26 39 am" src="https://github.com/Automattic/wp-calypso/assets/22446385/a7aa88e1-1178-4633-a2eb-766dff3ccdc5">

2024-05-19 23:51 UTC, merged