Dataviews: Update the layout styles to get rid of the fixed height
Automattic/wp-calypso pull request #90875
Opened 2024-05-20 08:28 UTC by arthur791004

Related to #

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-20 10:15 UTC, arthur791004 commented
@cleacos I made some changes to get rid of the fixed height from the .dataviews-view-table-wrapper element. What do you think?

2024-05-20 16:32 UTC, cleacos requested changes
This breaks the SitesDataViews styles at A4A:

<img width="1451" alt="image" src="https://github.com/Automattic/wp-calypso/assets/9832440/c9cb943c-a08f-4ed1-9b55-1dff5d91e280">

2024-05-21 02:53 UTC, arthur791004 commented
> This breaks the SitesDataViews styles at A4A:

Ooops, I didn't notice that on my original viewport... It should be resolved by https://github.com/Automattic/wp-calypso/pull/90875/commits/206b1c587cd52cf779c07a9b7f470ad58d063a6e

| Desktop | Mobile |
| - | - |
| ![image](https://github.com/Automattic/wp-calypso/assets/13596067/e4fad0ff-1c7b-4eb5-a6ba-0d45c2dc3560) | ![image](https://github.com/Automattic/wp-calypso/assets/13596067/6e570a73-93a0-41b4-8288-75b0c4cf2a76) |

2024-05-21 17:23 UTC, cleacos approved these changes
Thank you for fixing it. Now it looks good at A4A.

2024-05-21 17:48 UTC, Addison-Stavlo approved these changes
This looks good on my end!

2024-05-21 17:49 UTC, merged