Plans Grid: remove live chat and email support strings
Automattic/wp-calypso pull request #90980
Opened 2024-05-22 08:22 UTC by aneeshd16

Related to pau2Xa-5Vl-p2#comment-15472

## Proposed Changes

* This PR removes references to live chat and email support from the plans grid.

## Why are these changes being made?

* pau2Xa-5Ut-p2

## Testing Instructions

* Go to `/start/plans`. Confirm that there are no references to live chat or email support.
* Check a few other instances of the pricing grid, for example: `/setup/newsletter/plans` and confirm the same.
* Confirm the same for the trail map variants:
  * `/start/plans?flags=onboarding/trail-map-feature-grid-structure`
  * `/start/plans?flags=onboarding/trail-map-feature-grid-copy`
  * `/start/plans?flags=onboarding/trail-map-feature-grid`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-22 12:25 UTC, aneeshd16 commented on packages/calypso-products/src/features-list.tsx
> +				: i18n.translate( 'Email support' ),
Using an existing translated string till the new string is translated.

2024-05-22 12:26 UTC, aneeshd16 commented on packages/calypso-products/src/features-list.tsx
> +				: i18n.translate( '24/7 expert support' ),
Using an existing translated string till the new string is translated.

2024-05-22 12:39 UTC, aneeshd16 commented on packages/calypso-products/src/plans-list.tsx
> +	//TODO
TODO: Is there a way to view the WooExpress plans grid?

2024-05-23 02:55 UTC, oswian approved these changes
Code changes look good, tests as described.

2024-05-23 04:51 UTC, aneeshd16 commented on packages/calypso-products/src/plans-list.tsx
> +	//TODO
Update: The WooExpress plans grid is not shown anywhere, so I am skipping this change for now.

2024-05-23 06:11 UTC, niranjan-uma-shankar requested changes
The support features need to move one level up. Please check the version on https://wordpress.com/pricing/, the features are:
* No mention of support on the Starter plan
* "Fast support ..." on Explorer
* "Priority 24X7 ..." on Creator
* No mention of support on Entrepreneur since it has the "Everything in Creator, plus" line which implies that priority support is also available on this plan.

2024-05-23 08:02 UTC, aneeshd16 commented
Thanks @niranjan-uma-shankar for the review! I have updated the PR with the requested changes. I got confused since the grid on /pricing hides the free plan. 😅 

Can you please have a look when you get the chance?

2024-05-23 09:27 UTC, niranjan-uma-shankar reviewed
Sure, thanks for the changes. 

I believe we should cross out the support options when switching to monthly. This issue exists on production too, on control and the treatment versions of the offerings experiment.

2024-05-23 09:27 UTC, niranjan-uma-shankar commented on packages/calypso-products/src/features-list.tsx
> +				: i18n.translate( '24/7 expert support' ),
For the fallback here, wondering if we can use "24X7 priority support" which has [translations across all locales](https://translate.wordpress.com/projects/wpcom/-all-translated/885306/). Just so that it adds a minor differentiation from the Explorer plans. For the Explorer plan's [fallback string](https://github.com/Automattic/wp-calypso/pull/90980/files#diff-8c461e4e7786bd7359c23cd0cae753001d0ac1d71add984a115ab61b9f363e96R2698), we also have [translations](https://translate.wordpress.com/projects/wpcom/-all-translated/827656/) for just "Expert support", in case we wanted to remove the 24X7 part, but I don't feel too strongly about it.

2024-05-23 10:18 UTC, aneeshd16 commented
Thanks @niranjan-uma-shankar, those suggestions make sense to me. I have changed it to `24/7 priority support` since that  was the original string that you [linked to](https://translate.wordpress.com/projects/wpcom/-all-translated/885306/).

2024-05-23 12:00 UTC, niranjan-uma-shankar commented
Thanks @aneeshd16 . What do you think about [this comment](https://github.com/Automattic/wp-calypso/pull/90980#pullrequestreview-2073405333)? 

> I believe we should cross out the support options when switching to monthly. This issue exists on production too, on control and the treatment versions.

2024-05-23 12:09 UTC, aneeshd16 commented
Nice catch! I have added those features to the `getAnnualPlansOnlyFeatures` array via https://github.com/Automattic/wp-calypso/pull/90980/commits/815ccd94d885d1fc260f4aa71feaf9c0edea1663, so they will be crossed out when viewing monthly plans:

<img width="1482" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/c8bb5b2f-b341-4e8c-8bc5-2760271bdadc">

2024-05-23 12:40 UTC, aneeshd16 commented
Added "Help Center Support" to the Starter plan for the copy+structure variant via https://github.com/Automattic/wp-calypso/pull/90980/commits/8ab64f87e7ff390969449554fa101cd1cdca1c35. Context: p1716467421914249/1716444327.625359-slack-C06P2UC516Y

<img width="1527" alt="image" src="https://github.com/Automattic/wp-calypso/assets/5436027/f6a77c19-2cb0-4b60-b6f4-ac772648df37">

2024-05-23 13:34 UTC, niranjan-uma-shankar approved these changes
I'm approving the PR but there are a few more issues I noticed. I think it's fine to fix them in a follow-up.

1. In `/start/plans?flags=onboarding%2Ftrail-map-feature-grid-structure&intervalType=monthly`, the Support section is empty in mobile:

<img width="980" alt="Screenshot 2024-05-23 at 5 30 36 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/58c402e9-8fff-43f6-ac19-090b1bfe10a9">

And in `/start/plans?flags=onboarding%2Ftrail-map-feature-grid&intervalType=monthly` I think it adds some empty lines below "Help centre support":

<img width="351" alt="Screenshot 2024-05-23 at 5 33 00 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/35af974c-59cd-4113-bc96-0568e68decea">



2. In the structure only version, the support section is empty for the Starter and Free plan. I think the pattern is to show the feature crossed-out. 


<img width="1010" alt="Screenshot 2024-05-23 at 5 10 54 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/620d0caf-0f1c-4f6c-af6b-99694ce35d7a">

EDIT: We are not showing crossed-out features in mobile for other sections too, in structure-only and copy+structure. This is probably okay not to fix, but just noting it.

3. I think it's a bit off to show three different support features in the comparison table. This issue also exists in `/pricing` so cc'ing @claudiucelfilip. The weirdness was more pronounced in mobile view for me. Check the following comparison view between Creator and Entrepreneur - we only need to show that both have 24X7 priority support, the other two are not necessary.  
<img width="320" alt="Screenshot 2024-05-23 at 5 14 46 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/ca9202f9-f5f0-4dcd-98dc-0c1e94ff2fcf">

What I am thinking here is that in Desktop, we could show a single line called "Support levels" or something, and under Starter say "Help centre support", under Explorer say "Fast support ..." and under Creator and Entrepreneur say "Priority 24X7 ...". We do this for the themes features, where we mention unlimited vs dozens of themes. In mobile view, the comparison should show only one line with the support level text depending on the plan.


This issue also exists for the themes feature where we show "dozens of themes" and "unlimited themes" under the same plan for `/start/plans?flags=onboarding/trail-map-feature-grid-structure`:

<img width="318" alt="Screenshot 2024-05-23 at 5 24 13 PM" src="https://github.com/Automattic/wp-calypso/assets/1269602/484ef7f4-95fa-4c0e-9c7c-4666fc376338">

2024-05-23 13:37 UTC, niranjan-uma-shankar commented
Maybe also follow-up with @Automattic/i18n about the [fallback strings](https://github.com/Automattic/wp-calypso/pull/90980#discussion_r1611341527) that are added - the english strings are showing up in non-EN even though translations exist. Should be fine to merge and follow-up.

2024-05-24 04:51 UTC, merged

2024-05-24 06:44 UTC, aneeshd16 commented
I have created issues for the first two bugs:
* https://github.com/Automattic/martech/issues/3032
* https://github.com/Automattic/martech/issues/3033

> In the structure only version, the support section is empty for the Starter and Free plan. I think the pattern is to show the feature crossed-out.
> EDIT: We are not showing crossed-out features in mobile for other sections too, in structure-only and copy+structure. This is probably okay not to fix, but just noting it.

Yes, this was intentional and added via https://github.com/Automattic/wp-calypso/pull/89936

> What I am thinking here is that in Desktop, we could show a single line called "Support levels" or something, and under Starter say "Help centre support", under Explorer say "Fast support ..." and under Creator and Entrepreneur say "Priority 24X7 ...". We do this for the themes features, where we mention unlimited vs dozens of themes. In mobile view, the comparison should show only one line with the support level text depending on the plan.

The current way of doing this using `getConditionalTitle: ( planSlug ) => {}` in `packages/calypso-products/src/features-list.tsx` has some issues which are outlined here: p7H4VZ-4S4-p2. Plan-specific labels should be in `packages/calypso-products/src/plans-list.tsx`. I have a few ideas on how to make this work, I will come post a PR for this soon!