Stats: Update copy on commercial purchase page
Automattic/wp-calypso pull request #90982
Opened 2024-05-22 09:13 UTC by a8ck3n

Related to #

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-22 10:01 UTC, a8ck3n commented
Added "Learn more" text with link to this public blog post:

https://jetpack.com/blog/updates-to-jetpack-stats-for-commercial-sites/

2024-05-22 22:17 UTC, grzegorz-cp requested changes

2024-05-22 22:17 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +	if ( ! config.isEnabled( FLAGS_CHECKOUT_FLOWS_V2 ) ) {
It looks like the feature flag has been released, so does it make sense to keep the condition?

2024-05-22 22:17 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +			? translate( 'Upgrade and continue using Jetpack Stats' )
Instead of adding ternary operators everywhere, it would be easier to read the code if there was one `if` returning a set of the translations for commercial and another set for non-commercial visitors.

2024-05-22 22:17 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +			? translate( 'Upgrade and continue using Jetpack Stats' )
This will also avoid initialising the variables with an empty string.

2024-05-22 22:39 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +								<a href="https://jetpack.com/blog/updates-to-jetpack-stats-for-commercial-sites/" />
Let's put this in `const.js` in the main directory alongside other URLs.

2024-05-23 07:05 UTC, a8ck3n commented
Thanks for the feedback @grzegorz-cp. I've addressed those now. Going to review the feedback in Slack from design before requesting another review.

2024-05-24 02:04 UTC, grzegorz-cp requested changes
Looks good. Thanks for the updates. 
I left a few suggestions.

2024-05-24 02:04 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +					<p>Pick your Stats tier below:</p>
This needs to be translated.

2024-05-24 02:04 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +						<p>(*) 14-day money-back guarantee</p>
This also needs to be translated.

2024-05-24 02:04 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +function useLocalizedStrings( isCommercial: boolean ) {
The other functions in the file are arrow functions. Can you use the same type?

2024-05-24 02:04 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/styles.scss
> +.stats-purchase-flow__full-width-button {
Let's remove `button` from the name because it can be applied to other things.

2024-05-24 02:04 UTC, grzegorz-cp commented on client/my-sites/stats/stats-purchase/stats-purchase-single-item.tsx
> +						className="stats-purchase-flow__full-width-button"
`stats-purchase-flow` is a new prefix. Can you use the same one as the other elements?

2024-05-27 03:19 UTC, grzegorz-cp approved these changes
Looks good 👍 
I hope that the last commit message for https://github.com/Automattic/wp-calypso/pull/90982/commits/19dbd319e0fdaeb4d08234bf75fa5285dd86ed52 doesn't describe the project.

2024-05-27 03:22 UTC, merged