A4A: Product marketplace filtering improvements
Automattic/wp-calypso pull request #91291
Opened 2024-05-30 13:05 UTC by jkguidaven

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/590

## Proposed Changes

* Change the 'Search' label to 'Search products'.

| Before | After |
|--------|--------|
| <img width="201" alt="Screenshot 2024-05-30 at 8 57 56 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/02c38b96-c0c5-40fc-b736-76402585a59c"> | <img width="216" alt="Screenshot 2024-05-30 at 8 56 49 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/8994931b-c3bc-4f82-a228-c385bf8f58f2"> |

* Correct the 'Addon' type label to 'Add-on'.

| Before | After |
|--------|--------|
| <img width="508" alt="Screenshot 2024-05-30 at 8 59 20 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/7025b0f6-5be5-4f46-8bcf-600b834d400b"> | <img width="479" alt="Screenshot 2024-05-30 at 9 03 12 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/b2afe128-3a5b-4c3b-ab3d-c0dd627d0ca8"> | 

* Show an empty result message when no product matches.
   <img width="1579" alt="Screenshot 2024-05-30 at 9 04 30 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/26741ee1-5c0d-45a0-ad77-5c451eda258d">
* Show filtering dropdown shortcuts when there is active filter.
   <img width="657" alt="Screenshot 2024-05-30 at 9 04 52 PM" src="https://github.com/Automattic/wp-calypso/assets/56598660/b8634d6a-bb30-4058-8b93-0efd7529b083">

## Testing Instructions

* Use the A4A live link and go to `/marketplace/products`
* Confirm that the 'Search products' label is visible in the Search component.
* Click the Filter icon and hover on Type.
* Confirm that the 'Add-on' label is correct.
* Select some filters for category, type, and price.
* Confirm that a dropdown shortcut is visible.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-05-30 23:23 UTC, andrii-lysenko approved these changes
Looks and feels great!

2024-05-31 17:40 UTC, jeffgolenski requested changes
Outstanding, James. Thank you. 

One last request. In the empty state can you change "result" to "results" (make it plural) and you're good to ship! 

Thank you!

2024-06-03 02:31 UTC, jkguidaven commented
> Outstanding, James. Thank you.
> 
> One last request. In the empty state can you change "result" to "results" (make it plural) and you're good to ship!
> 
> Thank you!

Thanks. This has been addressed 👍

2024-06-04 21:13 UTC, andrii-lysenko commented
@jeffgolenski is it now good to go?

2024-06-05 07:41 UTC, jkguidaven commented
Apologize, I'll merge this today. 👍

2024-06-05 08:09 UTC, merged

2024-06-05 20:15 UTC, jeffgolenski commented
All good. Working as expected in prod! Thanks guys.

2024-06-06 23:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14077673

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

2024-06-09 21:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14077673).