A4A > Partner Directory: Implement Welcome View for the Dashboard
Automattic/wp-calypso pull request #91447
Opened 2024-06-04 09:52 UTC by yashwin

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/560

## Proposed Changes

This PR implements the welcome view for the dashboard

NOTE: 

- [Design](https://www.figma.com/design/fp9lBFMcpB15H7czSIthPW/Partner-Directories?node-id=6644-76437&m=dev)
- The links will be updated later in a different PR.

## Testing Instructions

1. Open the A4A live link.
2. Append the /referrals URL as /referrals?flags=-a4a-automated-referrals, and verify that the above changes are not reflected and that the Referrals page matches the production.
3. Go to Partner Directory - Dashboard > Verify the UI looks as below. 

<img width="1430" alt="Screenshot 2024-06-04 at 12 53 21 PM" src="https://github.com/Automattic/wp-calypso/assets/10586875/c5ab9e59-65e2-482a-8972-0a1ca48c9d04">

<img width="313" alt="Screenshot 2024-06-04 at 12 53 59 PM" src="https://github.com/Automattic/wp-calypso/assets/10586875/b89bcbff-f616-4efb-ab85-d98366b92b8a">

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-06-04 10:20 UTC, keoshi requested changes
Looking great!! Super speedy too!

Left some suggestions on how to tweak the step numbers, and apart from that I only have two minor suggestions:

- Hide the numbers on mobile.
- Apply a min-width to the buttons of around `100px` on desktop (when the buttons are on the side).

Thanks, Yashwin!

2024-06-04 10:20 UTC, keoshi commented on client/a8c-for-agencies/sections/referrals/common/step-section-item/style.scss
> +	font-size: rem(16px);
```suggestion
	font-size: rem(12px);
```

2024-06-04 10:20 UTC, keoshi commented on client/a8c-for-agencies/sections/referrals/common/step-section-item/style.scss
> +	width: 24px;
```suggestion
	width: 20px;
```

Since the border takes an additional 2px (20 + 2 + 2 = 24)

2024-06-04 10:20 UTC, keoshi commented on client/a8c-for-agencies/sections/referrals/common/step-section-item/style.scss
> +	height: 24px;
```suggestion
	height: 20px;
```

Since the border takes an additional 2px (20 + 2 + 2 = 24)

2024-06-04 10:20 UTC, keoshi commented on client/a8c-for-agencies/sections/referrals/common/step-section-item/style.scss
> +.step-section-item__step-number {
```suggestion
.step-section-item__step-number {
	display: flex;
	align-items: center;
	justify-content: center;
```

2024-06-04 10:54 UTC, yashwin commented
Thanks for the thorough review, @keoshi! 

I have addressed all your comments & updated the screenshot in the description.

2024-06-04 12:19 UTC, keoshi approved these changes
Very nice!! Ship it! 🚀

2024-06-05 07:40 UTC, merged

2024-06-06 23:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14075505

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

2024-06-09 15:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14075505).