[DO NOT MERGE] Add an environment dropdown in the site dashboard
Automattic/wp-calypso pull request #91504
Opened 2024-06-05 08:47 UTC by BogdanUngureanu

Instead of displaying a separate site entry for staging sites, we now display group sites with their corresponding staging site in a single entry. This is done by adding a dropdown with the site environment containing two options: Production and Staging.

When the user selects the staging option, they will be sent to the staging site detail page.

Related to https://github.com/Automattic/dotcom-forge/issues/7536

## Proposed Changes

* Add a new Environment dropdown in the Sites Dashboard
* Filter staging sites from the site list

## Why are these changes being made?

* Having separate entries for staging sites is confusing.

## Testing Instructions

* Use the live link
* Go to /sites and select an Atomic site
* Create a staging site
* Use the new Dropdown in the menu and navigate between staging and production site
* When you select an option, you'll be redirected to the corresponding environment

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-06-13 19:07 UTC, BogdanUngureanu commented
@lucasmendes-design I've updated the PR with the changes from your design. :) I've kept the staging badge from the site list view in the same place because there were other badges besides this one (p2, trial, etc). Also, on the URL line usually there isn't that much space compared to the Site title. :)

2024-06-14 12:37 UTC, lucasmendes-design commented
> I've kept the staging badge from the site list view in the same place because there were other badges besides this one. Also, on the URL line usually there isn't that much space compared to the Site title. :)

All good :) 

> I've updated the PR with the changes from your design.

Amazing work @BogdanUngureanu 💯 just a few notes:

- Can we make the badge and the chevron clickable (Red rectangle)? Not only the chevron.

<img width="1251" alt="Screenshot 2024-06-14 at 09 26 57" src="https://github.com/Automattic/wp-calypso/assets/98343583/d4c335d5-7612-4ec4-be48-00b839b6fbe2">

- Also, can we change the cursor icon from the pointer to the hand icon? Similar to URL and Quick action links.

- What do you think of adding a hover here (see example below)? Something around "Select dev environment"?

<img width="405" alt="Screenshot 2024-06-14 at 09 35 08" src="https://github.com/Automattic/wp-calypso/assets/98343583/238188b9-a70d-4216-a0ec-d0c8c201fac2">

2024-06-14 14:38 UTC, mmtr commented
> Filter staging sites from the site list

I do see them in `/sites/`:

<img width="1269" alt="Screenshot 2024-06-14 at 16 36 56" src="https://github.com/Automattic/wp-calypso/assets/1233880/e1edc1d8-89e7-440e-bf93-ac4a327a5b30">


Am I doing anything wrong?

2024-06-14 16:02 UTC, BogdanUngureanu commented
@lucasmendes-design Done :)

2024-06-14 16:53 UTC, lucasmendes-design commented
Thanks :) It's perfect. ✌🏽

2024-06-17 10:35 UTC, xavier-lc reviewed
> Use the new Dropdown in the menu and navigate between staging and production site

I didn't leave the page while waiting for the staging site to be set up, and I noticed that the dropdown didn't appear until I reloaded the page. Could we show it without needing to reload?

2024-06-17 10:38 UTC, xavier-lc reviewed
Minor thing: When opening the dropdown on staging, production appears preselected.

![image](https://github.com/Automattic/wp-calypso/assets/8511199/30960a20-2651-4666-a7b5-a27bed57f585)

2024-06-17 10:43 UTC, xavier-lc reviewed
I've noticed that the first card says `Staging site`, while the design shows the site plan as usual. Is that expected?

![image](https://github.com/Automattic/wp-calypso/assets/8511199/e857f9f5-857c-4753-96ae-a587666955fb)

2024-06-17 11:54 UTC, lucasmendes-design commented
> I've noticed that the first card says Staging site, while the design shows the site plan as usual. Is that expected?

It was expected to me, but currently, we display this card alsot empty. Since we now have only one entity in the site list I'd keep this information as it is.

2024-06-17 13:16 UTC, BogdanUngureanu commented
> I didn't leave the page while waiting for the staging site to be set up, and I noticed that the dropdown didn't appear until I reloaded the page. Could we show it without needing to reload?

I think it's fine. 

> Minor thing: When opening the dropdown on staging, production appears preselected.

Nice catch! I've updated the PR.

2024-06-17 13:32 UTC, xavier-lc approved these changes
Sorry for being picky, but I think it looks a bit weird to have both options highlighted on the dropdown. Other than that, LGTM.

![image](https://github.com/Automattic/wp-calypso/assets/8511199/34a7a275-dbee-4455-91ce-66817387b068)

2024-06-17 13:39 UTC, BogdanUngureanu commented
@xavier-lc Can you check again? My last commit should fix that issue.

2024-06-18 06:56 UTC, rcrdortiz requested changes
When a staging site is created I need to reload the page for the dropdown to appear. When I delete the staging site I also need to reload the page for the dropdown to be hidden.

2024-06-18 08:58 UTC, BogdanUngureanu commented
@rcrdortiz Fair enough. I would've been fine with the refresh on creation, but on delete it would probably result in a broken page.

2024-06-18 13:13 UTC, xavier-lc commented
After clicking on `Delete staging site`, the dropdown is set to production, but you can still toggle it to staging and end up on the screenshot. I think it'd be better to get rid of the dropdown once the delete process is triggered.

![image](https://github.com/Automattic/wp-calypso/assets/8511199/b9cda2cd-1361-4ccd-8c18-a092268f9f36)

2024-06-18 13:15 UTC, xavier-lc commented
> @xavier-lc Can you check again? My last commit should fix that issue.

I can still see it:

![Screenshot from 2024-06-18 15-14-03](https://github.com/Automattic/wp-calypso/assets/8511199/bd815f2b-d281-4751-a8dc-133ae6571dc9)

2024-06-18 15:11 UTC, xavier-lc approved these changes
LGTM 👌

2024-06-19 08:24 UTC, rcrdortiz approved these changes

2024-06-19 08:25 UTC, rcrdortiz commented
Works as expected now great job!

2024-06-19 10:11 UTC, BogdanUngureanu commented
I've updated the switcher component to use the dropdown component from wordpress/components. This will be more consistent with the rest of the design and also removes some CSS hacks.

2024-06-19 14:17 UTC, rcrdortiz commented
> I've updated the switcher component to use the dropdown component from wordpress/components. This will be more consistent with the rest of the design and also removes some CSS hacks.

I actually prefer the one we had before. The core one seems buggy, it doesn't highlight the active option or the option I'm hovering. And, once opened, you can't close it unless you click on the arrow again.


https://github.com/Automattic/wp-calypso/assets/1989914/149b7b35-1441-487b-88f5-6eb03c6c65e1

2024-06-19 16:03 UTC, mmtr commented
> The core one seems buggy

I wonder if this a bug specific to this PR. We are already using a similar dropdown in `/sites` which doesn't have all these issues:

https://github.com/Automattic/wp-calypso/assets/1233880/7ac7debb-e0b1-40c8-89a4-9e75b9f490ea

> I actually prefer the one we had before

To clarify, according to [the latest design](https://github.com/Automattic/dotcom-forge/issues/7536#issuecomment-2176624220), we should be using this new dropdown (but ensuring it works as expected!)

2024-06-19 16:07 UTC, BogdanUngureanu commented
@mmtr It was because the component was controlled and the `onFocusOutside` didn't work because `focusOnMount` was set to false (in order to avoid adding that box-shadow).

I pushed a commit that should fix all these issues by removing that prop and styling the component.

2024-06-20 10:12 UTC, rcrdortiz commented
> I pushed a commit that should fix all these issues by removing that prop and styling the component.

I'm still having some issues with the component. On a side note, could we make the selected option appear with the same highlight type as the video Miguel shared? This is how it's working for me atm


https://github.com/Automattic/wp-calypso/assets/1989914/f3d7de36-2ba3-4f54-a6fd-6e4fce127ba4

2024-06-20 15:09 UTC, BogdanUngureanu commented
Turns out, I can toggleProps has a prop called `as` that allows you to pass a custom Component for the toggle. This way, I removed the controlled state approach.

I also made some adjustments to the CSS to look more like the Site Actions component.

2024-06-21 07:50 UTC, mmtr commented
> I also made some adjustments to the CSS to look more like the Site Actions component.

It's still different for me, that blue background is not in the site actions dropdown:

Site actions | Staging selector
--- | ---
<img width="240" alt="Screenshot 2024-06-21 at 09 49 26" src="https://github.com/Automattic/wp-calypso/assets/1233880/79e44dfe-daff-4ad7-847b-2a8d90fb4fdf"> | <img width="249" alt="Screenshot 2024-06-21 at 09 48 46" src="https://github.com/Automattic/wp-calypso/assets/1233880/63df496e-9b69-4c4c-b82b-590da2986eef">

But let's not block this any further and address is on a follow-up

2024-06-21 08:04 UTC, mmtr reviewed
This tests very well for me, except on A4A. I'm unable to select a site now?


https://github.com/Automattic/wp-calypso/assets/1233880/d52dddc2-ec83-4344-917d-be759a5be026



For WP.com, i think the mobile view can be improved, but can be explored in a separate issue/PR:
- The staging selector, and the close/wp admin buttons can be in the same arrow and fully aligned to the left
- There is a small padding at the bottom which makes the yellow border a bit weird

<img width="508" alt="Screenshot 2024-06-21 at 09 52 50" src="https://github.com/Automattic/wp-calypso/assets/1233880/eef53f46-7d52-46b5-b99e-f45ead27feaa">

2024-06-21 08:04 UTC, mmtr commented on client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-header/index.tsx
> +							) }
Nitpick (non-blocking): This can be simplified
```suggestion
							{ extraProps && extraProps.subtitleExtra && ( <span><extraProps.subtitleExtra /></span> ) }
```

2024-06-21 08:04 UTC, mmtr commented on client/sites-dashboard-v2/sites-dataviews/dataviews-fields/site-field.tsx
> +								<button
Nitpick (non-blocking): Does this need to be a button? I wonder if this can cause accessibility issues with screen readers.

2024-06-21 08:28 UTC, BogdanUngureanu commented
> It's still different for me, that blue background is not in the site actions dropdown:

I don't think you can select an option in site actions.

2024-06-21 09:04 UTC, mmtr commented
> except on A4A. I'm unable to select a site now?

Turns out it's unrelated to this PR. It also happens on prod, and it's specific to one of my JN sites which expired but has not been removed from the site lists. Other JN sites are opened as expected

2024-06-21 09:04 UTC, mmtr approved these changes
Nice work!

2024-06-21 10:09 UTC, BogdanUngureanu commented
@mmtr I've pushed some styling changes that alleviate the issues you've mentioned. However, on landscape for iPhone SE, the UI is still experiencing problems unrelated to this change (e.g. the masterbar still appears even though on iPhone 14PM it doesn't).

2024-06-24 13:40 UTC, merged

2024-06-24 14:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/15325081

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @BogdanUngureanu, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Select environment`
- `Production`

Thank you in advance!

2024-06-30 12:31 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/15325081).