Help Center: clean-up part 1
Automattic/wp-calypso pull request #91880
Opened 2024-06-18 11:56 UTC by arcangelini

## Proposed Changes

Changes the support availability endpoint to support status endpoint. This new endpoint has proper naming to be aligned with our new omni-channel support. The variables and function naming is also updated.

## Why are these changes being made?

Most of this is variable renaming. The larger change is the update endpoint from: `help/eligibility/chat/mine` to: `help/support-status`.

## Testing Instructions

#### Needs to be used with D151949-code

1. Sandbox your public-api
2. Open up Calypso for this branch
3. Check out Help Center to ensure it is working properly
4. Open up a support request to check that messaging is working properly

2024-06-18 13:02 UTC, alshakero requested changes
Works great in Calypso and simple but couldn't test in Atomic because the new file is not imported in `class-help-center.php`

2024-06-18 13:02 UTC, alshakero commented on packages/help-center/src/hooks/use-chat-status.ts
> +	const { availability } = supportStatus || {};
```suggestion
	const availability = supportStatus.availability;
```

2024-06-18 13:02 UTC, alshakero commented on apps/editing-toolkit/editing-toolkit-plugin/help-center/class-wp-rest-help-center-support-status.php
This file is unimported anywhere.

2024-06-18 13:02 UTC, alshakero commented on apps/editing-toolkit/editing-toolkit-plugin/help-center/class-wp-rest-help-center-support-availability.php
This file is still imported in `class-help-center.php`

2024-06-19 05:49 UTC, agrullon95 approved these changes
LGTM. Tested on simple and atomic. I was able to open the support chart with the "Contact WordPress.com Support" and send a test message.

2024-06-19 07:35 UTC, merged