Site Settings: Add Jetpack Firewall Toggle to Security Settings Screen
Automattic/wp-calypso pull request #91966
Opened 2024-06-19 23:29 UTC by nateweller

Related to https://github.com/Automattic/jetpack-scan-team/issues/1228

## Proposed Changes

* TBD

## Why are these changes being made?

* TBD

## Testing Instructions

* TBD

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-29 18:00 UTC, dkmyta reviewed
Looks and works great, with the exception the Akismet UI glitch hijacking the save, returning an error notice and not immediately reflecting the new toggle state as we discussed.

Settings updates are working and are reflected in both the Jetpack and/or Protect UIs appropriately and vice-versa. Upgrading and downgrading performs as expected and the UIs are updated accordingly. 

One thing I did notice as a potential discussion point, when viewing these settings for an unsupported site, the toggles are just disabled rather than hidden as they are in the other UIs. I realize this is a difficult scenario because the BFP and Allow list settings are baked into the WAF card, but I think it may raise the question "why can I not enable these?". If hiding them is not a valid solution, perhaps we should add a notice of some sort for clarification? Thoughts?

2024-07-29 19:55 UTC, nateweller commented
> One thing I did notice as a potential discussion point, when viewing these settings for an unsupported site, the toggles are just disabled rather than hidden as they are in the other UIs. I realize this is a difficult scenario because the BFP and Allow list settings are baked into the WAF card, but I think it may raise the question "why can I not enable these?". If hiding them is not a valid solution, perhaps we should add a notice of some sort for clarification? Thoughts?

I'm not sure exactly where this is happening yet, each toggle _should_ be conditionally rendered based on the value of `wafModuleSupported()` method in `firewall.jsx`:

```
! this.props.isAtomic && ! this.props.isVip
```

When a toggle is rendered but disabled, the logic is more complex:

```
! this.props.isAtomic && ! this.props.isVip || isRequestingSettings || isSavingSettings || moduleDetailsNotLoaded || ( siteInDevMode && moduleUnavailableInDevMode )
```
Do you know what your state would have looked like roughly, when the toggles are disabled but still being rendered on the page?

2024-07-29 20:09 UTC, dkmyta commented
>Do you know what your state would have looked like roughly, when the toggles are disabled but still being rendered on the page?

Using a Pressable site, the toggles display as follows for the Security Settings page:
![Screen Shot on 2024-07-29 at 13-03-05](https://github.com/user-attachments/assets/6d54bab8-7d65-4cd2-94ab-efe1efd9172f)

2024-07-30 16:07 UTC, dkmyta requested changes
Works great if Akismet is activated, but that is a separate/existing issue that will hopefully be resolved external to this.

Every scenario I could think of testing is now accounted for with one minor exception to provide for perfect parity. When in an unsupported environment we now only display the BFP and Allow list toggles, in Jetpack/Protect we disable the Allow list if BFP is disabled as it has no usage outside of that scenario. 
![Screen Shot on 2024-07-30 at 08-57-43](https://github.com/user-attachments/assets/95e1f2b7-6fcf-40d7-8a3f-53ad7254190f)

In Calypso we still allow it to be toggled and entries added.
![Screen Shot on 2024-07-30 at 08-57-32](https://github.com/user-attachments/assets/ebda1ebc-f043-4724-8029-275e64aeb24c)

If we pursue this change, I think we may need to also ensure this is the case in the backward compatible version if that is at all handled uniquely.

2024-07-31 18:01 UTC, nateweller commented
@dkmyta What do you think about leaving the IP allow list available when the firewall/login protection features are turned off? My thinking being that you may want to allow list your own address prior to turning back on one of the features.

Perhaps we can sync up on how to present different WAF settings (i.e. show lists vs disable them when toggled off, disable or hide allow list when other features off, etc) with design during our meetup?

My proposal then being, let's merge this and follow up more broadly 😅

2024-07-31 18:09 UTC, dkmyta approved these changes

2024-08-06 20:14 UTC, merged

2024-08-06 21:22 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16462881

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @nateweller for including a screenshot in the description! This is really helpful for our translators.

2024-08-14 09:36 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16462881).