A4A: Update the referral object schema and UI to match the latest APIs
Automattic/wp-calypso pull request #91973
Opened 2024-06-20 07:38 UTC by atanas-dev

Related to D152547-code

## Proposed Changes

* A4A: Update the referral schema for agencies and clients to match the latest changes to the API.

## Why are these changes being made?

*

## Testing Instructions

* Make sure you create several new referrals before testing as data stored for referrals has changed.
* Make sure you check out some of the referrals and revoke some of the licenses to test all states.
* Make sure referrals and products are displayed correctly on http://agencies.localhost:3000/referrals/dashboard
* Make sure referrals and products are displayed correctly on http://agencies.localhost:3000/client/subscriptions

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-06-20 07:48 UTC, yashwin requested changes

2024-06-20 07:48 UTC, yashwin commented on client/a8c-for-agencies/sections/client/lib/get-subscription-status.tsx
> +				type: 'info',
Can we set this to `error`

2024-06-20 07:48 UTC, yashwin commented on client/a8c-for-agencies/sections/referrals/referral-details/components/assigned-to.tsx
> +		return [ 'info', translate( 'Canceled' ) ];
Can we set the status to `error`

2024-06-20 07:56 UTC, merged

2024-06-20 08:18 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14996380

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @atanas-dev, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Awaiting payment`

Thank you in advance!

2024-06-23 18:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14996380).