A4A: Blocked site selection row when migration is in progress
Automattic/wp-calypso pull request #92010
Opened 2024-06-20 20:24 UTC by paulopmt1

Related to https://github.com/Automattic/dotcom-forge/issues/7838

## Proposed Changes

* Blocked site selection row when migration is in progress
* Hided the site domain

## Testing Instructions

* Follow these instructions to mark a site as `migration-in-progress`: D152767-code
* Clear ES cache by following this instructions: p1718914253489269/1718913900.671429-slack-C06JY8QL0TU
* Open the Agency sites list and ensure the desired site is in `migration` state and doesn't allow you to discover its domain or see more information:

<img width="1314" alt="image" src="https://github.com/Automattic/wp-calypso/assets/1044309/c37e2f5e-41f4-4726-9e80-02ac791a8c0d">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-06-20 22:08 UTC, vykes-mac commented
> Set [the isTeamMember variable](https://github.com/Automattic/wp-calypso/blob/update/agencies-dashboard-migration-in-progress/client/a8c-for-agencies/sections/sites/features/jetpack/jetpack-sites-dataviews.tsx#L73) to false and ensure you can now navigate and see site details:

Shouldn't it be that if the team member flag is false then we cannot navigate and only HE's are able to navigate?

2024-06-20 22:28 UTC, vykes-mac commented
![image](https://github.com/Automattic/wp-calypso/assets/47489215/b0098c6a-56f8-4914-81d7-a2c5d26e5225)

With my site I can toggle monitor and add Boost. should everything be disabled for none team members?

2024-06-20 23:02 UTC, vykes-mac commented
@paulopmt1 The `<QueryReaderTeams/>` was not executing based on it's location. I moved it to the sites dashboard and also disable the other items in the row when migrating

2024-06-21 19:28 UTC, paulopmt1 commented
> should everything be disabled for none team members?
>  I moved it to the sites dashboard and also disable the other items in the row when migrating

Yeah, thanks for adding the other checks!

2024-06-24 15:40 UTC, cleacos requested changes
The code looks good, but I still see the chevron and the action menu and I can open the preview pane:

<img width="1357" alt="image" src="https://github.com/Automattic/wp-calypso/assets/9832440/d8cfae26-33f4-4f34-a0a1-ca1d00ab42c1">

2024-06-24 15:41 UTC, cleacos approved these changes
> Note: On the staging server, you can still click on it, but this only works for a11n. Once it's in prod, normal users won't be able to click on it:

OK

2024-06-24 16:29 UTC, merged