Stats: Adding empty state component for Clicks
Automattic/wp-calypso pull request #92231
Opened 2024-07-01 06:21 UTC by annacmc

Related to [#64](https://github.com/Automattic/red-team/issues/64)

## Proposed Changes

* adds a new empty state for Clicks

## Testing Instructions

* go to the live branch
* apply `stats/empty-module-traffic` feature flag
* verify that a page with empty Clicks views component works with and without the feature flag
* repeat for blogs with data

![image](https://github.com/Automattic/wp-calypso/assets/30754158/22f5fe6e-42fb-497e-b63a-1b309a94d7ca)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-01 22:01 UTC, grzegorz-cp requested changes
Let's maintain the CSS classes.

2024-07-01 22:01 UTC, grzegorz-cp commented on client/my-sites/stats/site.jsx
> +									'stats__flexible-grid-item--40--once-space',
We need to maintain the same classes to allow for proper grid rendering across environments.

2024-07-01 23:35 UTC, annacmc commented on client/my-sites/stats/site.jsx
> +									'stats__flexible-grid-item--40--once-space',
Oh yeah, totally - this was an oversight and I still had the commit sitting locally for this. Thanks for pointing it out :)

2024-07-02 02:20 UTC, grzegorz-cp approved these changes
👍

2024-07-02 02:30 UTC, merged

2024-07-02 04:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/15839334

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @annacmc for including a screenshot in the description! This is really helpful for our translators.

2024-07-07 16:35 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/15839334).