A4A: Add Site remove functionality.
Automattic/wp-calypso pull request #92317
Opened 2024-07-03 11:48 UTC by jkguidaven

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/745

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-03 13:49 UTC, keoshi approved these changes
Works great in my testing!

2024-07-03 15:23 UTC, rcanepa commented
Should we explicitly say that this action will only remove the site from the dashboard and nothing else? Some users might hesitate, thinking their site may be deleted or something similar.

Similarly, we need to mention that removing a site won't do anything to licenses activated on the site.

At the very least, I would replace `'Are you sure you want to remove the site [siteName]?'` with `'Are you sure you want to remove the site [siteName] from the dashboard?'`

2024-07-04 11:16 UTC, jkguidaven commented
> Should we explicitly say that this action will only remove the site from the dashboard and nothing else? Some users might hesitate, thinking their site may be deleted or something similar.
> 
> Similarly, we need to mention that removing a site won't do anything to licenses activated on the site.
> 
> At the very least, I would replace `'Are you sure you want to remove the site [siteName]?'` with `'Are you sure you want to remove the site [siteName] from the dashboard?'`

Good point! I made some changes to apply your suggestion. 

@madebynoam @keoshi I'm not sure if there is an upcoming design for the remove site flow, but let me know if there is.

2024-07-05 10:44 UTC, cleacos commented
We don't show sites that have errors:

Production, we can see the warning message and all the columns are disabled:

<img width="1368" alt="image" src="https://github.com/Automattic/wp-calypso/assets/9832440/56f33329-6c81-4f2b-b67c-a4f634610bfc">

This branch, the warning message disappear and columns are enabled:

<img width="968" alt="image" src="https://github.com/Automattic/wp-calypso/assets/9832440/d18b4d92-37d9-4a27-88d8-e4cfab493f90">

2024-07-05 10:48 UTC, cleacos reviewed
I tried to remove this site (disconnected site):

<img width="1304" alt="image" src="https://github.com/Automattic/wp-calypso/assets/9832440/c45b46a5-cac0-4c8e-bc4c-6e33fd76078a">

I see the confirm question and I clicked yes, but the site is not removed from the list without refreshing the full page.

2024-07-05 10:51 UTC, cleacos requested changes
There are parts that don't work as expected.

2024-07-05 11:53 UTC, jkguidaven commented
> I see the confirm question and I clicked yes, but the site is not removed from the list without refreshing the full page.

For some reason, the site profile reindexing hasn't been completed when we did the refetch after the remove site request, so the dashboard still shows the removed site.

I can add some arbitrary delay on the refetch, but I don't think It would fix all the delays we will have on the re-indexing. 🤔 Only, I think we can fix this by refetching sites table until the site is totally removed.

2024-07-05 12:00 UTC, cleacos commented
> I can add some arbitrary delay to the refetch, but I don't think it would fix all the delays we will have on the re-indexing. 🤔 Only, I think we can fix this by repeatedly refetching the sites table until the site is totally removed.

I don't know what would be the better one without spending too much time... One solution could be, in the app, to discard that site in the front end, setting a status like "Site pending to delete...".

2024-07-05 12:06 UTC, cleacos commented
It seems that at Horizon, we don't show a warning/error message for disconnected sites...

2024-07-05 12:07 UTC, cleacos approved these changes

2024-07-05 14:19 UTC, merged

2024-07-05 16:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16095331

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

2024-07-11 10:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16095331).