Help Center: adjust opening position based on last click
Automattic/wp-calypso pull request #92350
Opened 2024-07-03 22:27 UTC by arcangelini

## Proposed Changes

Listen and save click events and pass them to the Help Center container. Use this data to determine where the Help Center should open at.

## Why are these changes being made?

* It is important for the Help Center to open relative to where it is clicked. This can be done with some simple CSS.
* This change manages the Help Center location within itself to prevent excessive CSS around WordPress.com to accommodate different Help Center button locations.
* The goal was to create a solution that doesn't require updating CSS in all the places that Help Center is being called.

## Testing Instructions

1. Open local Calypso
2. Go to `/help` and `/home` to try out the different opening locations of Help Center.
3. Try different screen orientations
4. Test in WP-ADMIN

2024-07-04 13:02 UTC, alshakero commented
### Pushed some improvements
1. Used the button position instead of click position.
2. Added an animation.
3. Fixed minimizing.

2024-07-04 21:47 UTC, arcangelini reviewed
Tested in a few locations such as:
* Checkout
* WooCommerce installation
* Home
* Help

Everything seems to be opening correctly on screen even with constrained screen dimensions.

2024-07-05 23:39 UTC, alshakero requested changes

2024-07-05 23:39 UTC, alshakero commented on packages/help-center/src/hooks/use-opening-coordinates.ts
> +		coords.left = buttonRightEdge - helpCenterWidth - AESTHETIC_OFFSET;
Adding `AESTHETIC_OFFSET` here ruined the alignment with the button :(

It was so clean when they're aligned. I intentionally only added the gap vertically.

2024-07-05 23:39 UTC, alshakero commented on packages/help-center/src/hooks/use-opening-coordinates.ts
> +		coords.left = buttonLeftEdge + AESTHETIC_OFFSET;
+1.

2024-07-09 14:17 UTC, alshakero approved these changes
Tested on iPhone, iPad, and desktop sizes. All look great.

2024-07-10 08:46 UTC, merged