fix: gap between masterbar and notifications
Automattic/wp-calypso pull request #92422
Opened 2024-07-04 21:23 UTC by nightnei

Related to https://github.com/Automattic/dotcom-forge/issues/8062

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-05 09:08 UTC, fredrikekelund approved these changes
This tests well, but I agree with you, @nightnei, that the CSS selectors we're touching here are risky.

Let's hold off on landing this until Griffith has also taken a look.

---

I'd consider updating [these lines](https://github.com/Automattic/wp-calypso/blob/cd99aa2f724201d39705d8dc29a1b69045a28d67/client/hosting/sites/components/dotcom-style.scss#L683-L685) to something like this (in a follow-up PR):

```css
.wpcom-site div.is-section-hosting:not(.has-no-masterbar),
.wpcom-site div.is-section-hosting-dashboard:not(.has-no-masterbar),
.wpcom-site div.is-section-plugins:not(.has-no-masterbar) {
```

@taipeicoder, do you have any thoughts about that?

2024-07-05 09:37 UTC, taipeicoder approved these changes
This change would create a small regression issue where the mobile menu shows the scrollbar even though it's not scrollable, I would say it's an acceptable compromise if it prevents us from pursuing more complicated solutions 🙂.

![Screenshot 2024-07-05 at 5 32 31 PM](https://github.com/Automattic/wp-calypso/assets/797888/e1304726-c009-4f4a-96fb-782ca4e26b9b)

2024-07-05 15:12 UTC, nightnei commented
@taipeicoder coudl you please also take a look at @fredrikekelund comment above?

2024-07-05 15:25 UTC, taipeicoder commented
```css
.wpcom-site div.is-group-sites:not(.has-no-masterbar),
.wpcom-site div.is-group-sites-dashboard:not(.has-no-masterbar),
.wpcom-site div.is-section-plugins:not(.has-no-masterbar) 
```

The good thing about above is that it's more generic, so pages such as /domains/manage come for free. I also think it's okay if you prefer to change it to target more specific pages, as suggested in the [comment](https://github.com/Automattic/wp-calypso/pull/92422#pullrequestreview-2160303091). Happy to test again if you end up making those changes.

2024-07-08 09:41 UTC, fredrikekelund commented
> The good thing about above is that it's more generic, so pages such as /domains/manage come for free.

The generic nature of that selector also seems risky, though, since it unintentionally targeted several Calypso pages as well.

I have a very limited grasp of the styling changes we made in Untangling/Nav redesign, but generic CSS selectors have bitten me in the past in Calypso, so I typically argue for more precision (with added verbosity).

2024-07-08 09:44 UTC, taipeicoder commented
> > The good thing about above is that it's more generic, so pages such as /domains/manage come for free.
> 
> The generic nature of that selector also seems risky, though, since it unintentionally targeted several Calypso pages as well.
> 
> I have a very limited grasp of the styling changes we made in Untangling/Nav redesign, but generic CSS selectors have bitten me in the past in Calypso, so I typically argue for more precision (with added verbosity).

Yeah, and it's general but not enough since /profile and /read are not targeted under this selector. Let's change it to your suggestion!

2024-07-09 08:11 UTC, fredrikekelund requested changes
It looks like the `.is-section-hosting` selector doesn't really work (my bad!), since the problem fixed by #90251 has reappeared now.

To reproduce, go to the hosting overview settings for an Atomic site and shrink the viewport to 660px wide and 1200px tall. You'll notice that the viewport has a scrollbar (which is what #90251 removed). 

Maybe it's best to revert your latest changes, @nightnei, and look into a more robust solution in an upcoming PR. Making it so `div.layout` has a common CSS class across all the hosting setting views seems like a pretty smart approach.

2024-07-09 09:11 UTC, nightnei commented
> ~It looks like the .is-section-hosting selector doesn't really work (my bad!), since the problem fixed by https://github.com/Automattic/wp-calypso/pull/90251 has reappeared now.~

~Hm, I tested and I didn't see that bug... ~

>To reproduce, go to the hosting overview settings for an Atomic site and shrink the viewport to 660px wide and 1200px tall. You'll notice that the viewport has a scrollbar (which is what https://github.com/Automattic/wp-calypso/pull/90251 removed).

I see, I tested with "device view" and it doesn't show static scrollbar, unlike "desktop view"

>Maybe it's best to revert your latest changes, @nightnei, and look into a more robust solution in an upcoming PR. Making it so div.layout has a common CSS class across all the hosting setting views seems like a pretty smart approach.

I will do it

2024-07-09 09:20 UTC, fredrikekelund approved these changes

2024-07-09 10:01 UTC, merged

2024-07-09 16:56 UTC, nightnei commented
@taipeicoder @fredrikekelund I did investigation of the classnames, and we have a little bit mess there.
Recommend to read, since we all had the wrong picture of them - pcYYuD-1My-p2

And regarding our case:
```
.wpcom-site div.is-group-sites:not(.has-no-masterbar),
.wpcom-site div.is-group-sites-dashboard:not(.has-no-masterbar),
.wpcom-site div.is-section-plugins:not(.has-no-masterbar) 
```

1) At the current moment the last selector is redundant, since we also have `.is-group-sites` on Plugins pages. You can ask - why do we have it? I would answer - 🤷‍♂️ 😄 My assumption - it's just mistake. And we have much more mistakes across all these pages. More details in my P2.
2) I think it's not good idea to add extra selector for all hosting pages, at least ATM. If we add it - we will just increase the mess. We need to align, or at least to agree naming convention and then tweak this our case.