Help Center: Doc title is missing when minimized
Automattic/wp-calypso pull request #92567
Opened 2024-07-10 22:08 UTC by escapemanuele

Related to #

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-10 22:17 UTC, alshakero approved these changes
This fix works, but I would fetch the article title [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/components/help-center-header.tsx#L12) using `usePostByKey` and render its title instead. So that the `setShowSupportDoc` is more usuable.

2024-07-11 09:52 UTC, escapemanuele commented
Thanks @alshakero, I went on and addressed your feedback 👍

2024-07-11 10:07 UTC, alshakero requested changes
One tiny issue.

2024-07-11 10:07 UTC, alshakero commented on client/blocks/inline-help/inline-help-search-results.jsx
> +		const { link, post_id: postId, blog_id: blogId, title } = result;
No need for this anymore.

2024-07-11 10:07 UTC, alshakero commented on client/blocks/inline-help/inline-help-search-results.jsx
> +				setShowSupportDoc( link, postId, blogId, title );
+1

2024-07-11 10:07 UTC, alshakero commented on packages/help-center/src/components/help-center-header.tsx
> +		+( postId || 0 )
I think `useSupportArticleAlternatePostKey` should have default `blogId` itself.

2024-07-11 10:37 UTC, alshakero approved these changes
LGTM

2024-07-11 11:34 UTC, agrullon95 approved these changes
Working well. Tested by clicking Help Center article links in `/home` and clicking random articles within Help Center.

2024-07-11 14:31 UTC, heavyweight approved these changes

2024-07-11 16:55 UTC, merged