Plans Grid: move logic from action component to action hook
Automattic/wp-calypso pull request #92796
Opened 2024-07-18 13:54 UTC by aneeshd16

Related to #

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-19 05:11 UTC, aneeshd16 commented on client/my-sites/plans-features-main/hooks/use-generate-action-hook.tsx
> -};
This was already defined in `packages/plans-grid-next/src/types.ts`.

2024-07-22 05:41 UTC, aneeshd16 commented on packages/plans-grid-next/src/style.scss
Not sure what `gridrison` means. Probably a typo?

2024-08-07 11:21 UTC, chriskmnds requested changes
We had this sort of argument previously when these refactors  around the action hooks were getting started. If you can take a look at the initial PR by @southp and/or @jeyip, you will find my commenting there.

I strongly disagree that "storage-specific" logic being abstracted out of the plans-grid package - both for rendering whatever button-UI changes we render and for populating the cart. The intention is to use this grid in logged-out and storage is part of the grid. we shouldn't be reimplementing these at consuming (LandPack) end.

2024-08-07 11:40 UTC, chriskmnds commented
> Storage addon selection is Calypso-specific logic that does not belong in the PlanFeatures2023GridActions component of the plans-grid-next package. 

It's certainly not Calypso-specific. 

It's something of a "consuming-end" concern, although the grid is not abstracted that way. There's no clear separation between "this is a grid" and "this is a grid implementation for plans". The idea is to get there, but through layers of client/consuming ends: 

- Calypso -> WPCOM Plans Grid -> Grid
- LandPack -> WPCOM Plans Grid -> Grid
- JP -> WPCOM Plans Grid -> Grid

The storage logic belongs in the middle implementation (WPCOM Plans Grid) that will be shared across any WPCOM implementation (Calypso and LandPack and JP etc). If this PR moves it to the very side (Calypso), then it's probably wrong and best be abandoned. 🤷‍♂️

2024-08-07 18:40 UTC, jeyip commented
> Storage addon selection is Calypso-specific logic that does not belong in the PlanFeatures2023GridActions component of the plans-grid-next package.

I agree with Christos about add-ons not being Calypso specific.

Storage add-ons currently exist in the Landpack environment as well as Calypso, and will probably be added to more as the plans grid is implemented across other platforms.

2024-08-09 11:08 UTC, aneeshd16 commented
Thanks for sharing the additional notes and context, @chriskmnds!

I touched on this part in one of my previous PRs and chanced upon this comment:
https://github.com/Automattic/wp-calypso/blob/898be908c4465799eba2ab64daeddc3541d32099/packages/plans-grid-next/src/components/actions.tsx#L149

I wasn't unaware of the initial discussions you linked to and missed all that context. I'll close this PR for now, and we can revisit it if we decide to change directions.

2024-08-09 11:08 UTC, closed without merging

2024-08-09 13:47 UTC, chriskmnds commented
> Thanks for sharing the additional notes and context, @chriskmnds!
> 
> I touched on this part in one of my previous PRs and chanced upon this comment:
> 
> https://github.com/Automattic/wp-calypso/blob/898be908c4465799eba2ab64daeddc3541d32099/packages/plans-grid-next/src/components/actions.tsx#L149
> 
> I wasn't unaware of the initial discussions you linked to and missed all that context. I'll close this PR for now, and we can revisit it if we decide to change directions.

I can also take a closer look at some point. My reaction above was without digging much into it. I wanted to mainly bring that initial discussion/thought-process back on the table, in case we missed it. I may not be drawing the connections properly, so should take a closer look

The "upgrade" button/text definitely sounds like something to move out of plans-grid-next. doing that while keeping the storage selection logic in place for when we form the logged-out URLs or whatever else the grids need to react to it