Site Migration: Only show site picker if there are sites to show.
Automattic/wp-calypso pull request #92912
Opened 2024-07-23 20:46 UTC by sixhours

Related to https://github.com/Automattic/wp-calypso/issues/92558

## Proposed Changes

* If a user has no sites, there's no point in showing them the site picker. Let's just create a new site for them.

## Why are these changes being made?

* Discussion in https://github.com/Automattic/wp-calypso/issues/92558 and pcmemI-3dx-p2

## Testing Instructions

* From a logged-out state (or logged into an account with no sites), visit `wordpress.com/move`
* Put in the URL to migrate
* Replace the `wordpress.com` part of the URL with the calypso.live base URL or `calypso.localhost:3000` if you're running this branch locally
* You'll be asked to create a new user; do so by email.
* You should be brought directly to the step where you put in your URL. Do so and continue.
* You should *not* be shown the site picker.
* On the same branch, while logged into an account that has multiple sites, go to `wordpress.com/sites`
* Select the dropdown on the Add new site button -> Import an existing site
* You should be shown the step where you put in your URL; do so.
* You should still be shown the site picker.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-24 10:07 UTC, daledupreez reviewed
I have some comments from inspection, but I didn't get to test.

2024-07-24 10:07 UTC, daledupreez commented on client/landing/stepper/declarative-flow/site-migration-flow.ts
> +			( select ) => ( select( USER_STORE ) as UserSelect ).getCurrentUser()?.site_count ?? 0,
It may be worth dropping a comment here to explicitly note that we assume a user has no sites until we get an explicit data to indicate otherwise.

2024-07-24 10:07 UTC, daledupreez commented on client/landing/stepper/declarative-flow/site-migration-flow.ts
> +		}
I don't have strong opinions on this, but having two separate conditions here feels a bit awkward. As a different alternative, could we check the `siteCount` condition first?

```suggestion
		const maybeSitePickerStep = siteCount > 0 ? [ STEPS.PICK_SITE ] : [];
		const hostedVariantSteps = isHostedSiteMigrationFlow( this.variantSlug ?? FLOW_NAME )
			? maybeSitePickerStep.concat( [ STEPS.SITE_CREATION_STEP, STEPS.PROCESSING ] )
			: [];
```

2024-07-24 10:43 UTC, daledupreez reviewed
Also, I think we need to check the code to make sure we don't try to send users to the site picker step if they don't have sites.

2024-07-24 13:24 UTC, markbiek approved these changes
Dale had some small comments you might want to look at but this is working as expected.

2024-07-24 14:31 UTC, sixhours commented
> Also, I think we need to check the code to make sure we don't try to send users to the site picker step if they don't have sites.

I'm not sure what this means--I think that's what this PR is trying to prevent. Can you clarify?

2024-07-29 08:56 UTC, daledupreez commented
@sixhours, my concern here is that I don't see any changes that remove redirects to the step from within the flow. We're just removing the step from the list if available steps. So if we're unnecessarily seeing this step rendered now, this change will result in a 404 (or possibly other unexpected behaviour) after the step has been removed from the available steps.

Hopefully that clarifies my concern.

2024-07-31 15:34 UTC, markbiek approved these changes
LGTM!

2024-07-31 21:18 UTC, alshakero requested changes
Left a comment

2024-07-31 21:18 UTC, alshakero commented on client/landing/stepper/declarative-flow/internals/steps-repository/site-picker/index.tsx
> +	);
You're probably better off using Calypso state here, since the user is already fetched and cached [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/index.tsx#L105). 

```js
const sitesCount = useSelector( getCurrentUserSiteCount )
```

2024-08-01 14:38 UTC, sixhours commented on client/landing/stepper/declarative-flow/internals/steps-repository/site-picker/index.tsx
> +	);
Nice! Updated that, thanks for the tip!

2024-08-01 18:55 UTC, markbiek approved these changes
LGTM!

2024-08-01 18:55 UTC, merged