Help Center: Fix Contact form button styling
Automattic/wp-calypso pull request #92963
Opened 2024-07-25 09:50 UTC by agrullon95

Fixes: https://github.com/Automattic/dotcom-forge/issues/8411

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-07-25 10:05 UTC, alshakero reviewed
What if we remove all the styles except width 100%?

2024-07-25 11:47 UTC, agrullon95 commented
@alshakero - We can remove the `active` and `hover` styling. 
I would still need additional styling to change the background color to match what it previously was:

<img width="400" alt="CleanShot 2024-07-25 at 13 46 23@2x" src="https://github.com/user-attachments/assets/c80cf660-bc38-420f-8a3b-6b936109a3f3">

2024-07-25 17:11 UTC, alshakero commented
This means there is still CSS somewhere else messing with the button. If you delete everything, it should work. It only needs width: 100% and justify-elements: center.

2024-07-26 11:49 UTC, escapemanuele requested changes
Removing all the CSS caused this for me, the border disappears when mouse is inside the Help Center :)

<img width="771" alt="image" src="https://github.com/user-attachments/assets/1e406af4-5885-4216-abda-c3731b62058a">

2024-07-26 15:40 UTC, agrullon95 commented
@escapemanuele - I fixed the issue.

2024-07-29 11:07 UTC, arcangelini commented on packages/help-center/src/styles.scss
> +		components-button:not(.help-center-contact-form__site-picker-cta) {
```suggestion
		.components-button:not(.help-center-contact-form__site-picker-cta) {
```

Does this need to be a class?

2024-07-29 11:07 UTC, arcangelini commented
Tested and everything was working as expected.

2024-07-29 16:31 UTC, arcangelini approved these changes
🚀 🚀 🚀 
LGTM

2024-07-29 17:05 UTC, merged