Help Center: Remove back button arrow jump
Automattic/wp-calypso pull request #93204
Opened 2024-08-02 07:25 UTC by agrullon95

Fixes: https://github.com/Automattic/wp-calypso/issues/93053

## Proposed Changes

* Remove the arrow jump (shifts to the left on hover) in the Help Center Back button 

## Why are these changes being made?

* Fix glitch in the Help Center back button

## Testing Instructions

* Checkout branch or use live link
* Open the Help Center, click on a random article, and hover over the back button.
* Verify the arrow (should not shift to the left) and the `Back` text does not change on hover.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-08-02 08:24 UTC, alshakero requested changes
I think we need to change the cursor to pointer, otherwise the button won't seem clickable.

2024-08-19 21:40 UTC, escapemanuele approved these changes
From what I see the cursor is already a pointer, so this should be good to go!

2024-08-20 10:23 UTC, escapemanuele commented
It has passed some time now, and I keep thinking if the change was intentional, so...

@lucasmendes-design, do you want the back button in an article to animate when hovering? You should be able to check the difference using the live link

2024-08-20 12:58 UTC, alshakero commented
It was my idea to animate the arrow and Poli was on leave. So don't worry about removing it.

2024-08-20 14:05 UTC, merged