useSiteMetricsQuery: add support to disable automated data fetching
Automattic/wp-calypso pull request #93440
Opened 2024-08-12 01:12 UTC by chad1008

Related to #93032

## Proposed Changes

`useSiteMetricsQuery` runs Tanstack `useQuery` under the hood. This hook offers an `enabled` prop. This PR adds the option to pass values to that prop when calling `useSiteMetricsQuery`

I'd recommend reviewing this PR one commit at a time. The first commit on this branch adds the new prop, and implements it in the new bandwidth section of the hosting overview. The second commit updates the function to accept a single object instead of individual arguments. I didn't like the new unnamed boolean, and thought this would improve the ergonomics of the function. Other usages are also updated in the same commit. If we'd rather not make this change to the format of the arguments, we can revert just that one commit and go back to individual arguments.

## Why are these changes being made?

`useQuery`'s `enabled` prop defaults to `true`, which allows the query to automatically refetch under a number of different circumstances, including re-renders. If set to `false` the query doesn't run automatically, which is helpful if you want to delay or stop automatic fetching/refetching. We'll leave it defaulting to true, so most implementations won't need to worry about it, but for cases where disabling the query is helpful, we'll have a means of accomplishing it.

## Testing Instructions

- Visit the Calypso Live link for this branch
- Open /overview for any of your sites by clicking on the Hosting Overview button
- Append ?flags=hosting-overview-refinements to the end of the url
- Confirm that the new Bandwidth data loads as expected, and that it doesn't refresh or re-render its placeholder after the data appears for the first time
- Visit the Monitoring tab of the hosting overview and confirm that all of the charts load as expected with accurate data.
- Check for any new errors in the console

2024-08-12 09:49 UTC, fredrikekelund requested changes
I don't think we need to tweak this existing logic, and I don't see how this PR really improves the application or the code, either.

react-query has really solid built-in caching logic. If we want to avoid excessive refetching, then we should play with the combination of query key and `staleTime`. Since `staleTime` is already set to `Infinity` in `useSiteMetricsQuery`, the query key is the only thing we need to be concerned with. Instead of the approach taken here, I'd achieve the same effect by storing the return value of `getCurrentMonthRangeTimestamps` in local state, so we get a stable query key that way. 

However, I'm not convinced that the behavior this PR introduces (show more granular bandwidth data by refetching every time `AtomicSiteBandwidthUsage` mounts) is interesting to users, and it also adds load to the server. If anything, we could look into rounding `endInSeconds` to the nearest 15 or 30 minutes (although I'm not convinced that's necessary, either). 

Conditionally disabling the query based on whether it's returned data once is very bespoke behavior that'll likely be difficult to understand for the next dev who comes along.

2024-08-12 09:59 UTC, nightnei commented
> I don't think we need to tweak this existing logic, and I don't see how this PR really improves the application or the code, either.
> 
> react-query has really solid built-in caching logic. If we want to avoid excessive refetching, then we should play with the combination of query key and `staleTime`. Since `staleTime` is already set to `Infinity` in `useSiteMetricsQuery`, the query key is the only thing we need to be concerned with. Instead of the approach taken here, I'd achieve the same effect by storing the return value of `getCurrentMonthRangeTimestamps` in local state, so we get a stable query key that way.
> 
> However, I'm not convinced that the behavior this PR introduces (show more granular bandwidth data by refetching every time `AtomicSiteBandwidthUsage` mounts) is interesting to users, and it also adds load to the server. If anything, we could look into rounding `endInSeconds` to the nearest 15 or 30 minutes (although I'm not convinced that's necessary, either).
> 
> Conditionally disabling the query based on whether it's returned data once is very bespoke behavior that'll likely be difficult to understand for the next dev who comes along.

I agree with Fredrik. And it seems it was a bit misunderstanding - I was mentioning this [my comment](https://github.com/Automattic/wp-calypso/pull/93032#discussion_r1711486583), where the point is - avoid sending requests to the backend, in case of simple websites, since it's redundant request which overloads backend but never produce a useful payload.
So in a nutshel, I wanted to have something like `enableQuery: isAtomic` for the `useSiteMetricsQuery`

2024-08-14 13:48 UTC, chad1008 commented
Thank you both. You're right, @nightnei, definitely a misunderstanding. I see now where we got off on different pages. PR is updated, here are the highlights of the most recent change:

- brought back the logic to round the end time to the current hour, giving us a more stable query key
- `enableQuery` is now conditional on `isAtomic`, so we'll only fetch data when there's data to fetch
- removed the `AtomicSiteBandwidthUsage` subcomonent. It was only there to limit the `useSiteMetrics` call to atomic sites, but `enableQuery` makes that much easier, more elegant, and less verbose

2024-08-14 15:17 UTC, fredrikekelund approved these changes
Looking much better, and it tests well 👍

I recommend using multiple arguments for `useSiteMetricsQuery` instead of a destructured object, but I'll approve this PR straight away in the interest of unblocking you, @chad1008.

2024-08-14 15:17 UTC, fredrikekelund commented on client/my-sites/site-monitoring/use-metrics-query.ts
> +	enableQuery?: boolean;
I would lean towards using multiple arguments instead of a combined args object when there's only one optional parameter. Not a super big deal either way, but reducing the size of the diff is a nice additional benefit of that approach.

2024-08-14 16:26 UTC, chad1008 commented on client/my-sites/site-monitoring/use-metrics-query.ts
> +	enableQuery?: boolean;
Sounds good. Fortunately I kept that change to the structure of the arguments in a separate commit that's very easy to revert. I've taken care of that in 2ae150fd39118fd5111023d17a50beb929c66ed6.

Everything is still testing well for me, including on the Monitoring tab where the other implementations of this hook are used.

I'll give everything another look through wile I wait for CI and then get this one deployed.

2024-08-14 23:59 UTC, merged