A4A:
Automattic/wp-calypso pull request #93957
Opened 2024-08-27 14:22 UTC by jkguidaven

This pull request aims to prevent users from joining multiple agencies. When the current user is identified as a member of an existing agency and clicks an invite link, a screen with instructions on how to switch agencies is displayed.

<img width="1725" alt="Screenshot 2024-08-27 at 10 09 15 PM" src="https://github.com/user-attachments/assets/96b30dd0-6907-40b5-967d-878c9c7cf160">

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/964

## Proposed Changes

Before calling the endpoint to activate a member, we now check if the current user is a member of an agency by using the `/agency` endpoint. Here's what happens based on the user's status:
- If the user is not a member, we go ahead and activate the member.
- If the user is a member of a different agency, we display instructions.
- If the user is already a member of the agency, the page simply redirects to the overview page.

## Why are these changes being made?

* Our current architecture does not support multiple agencies at the moment, and we need to ensure that the user is aware of this limitation.

## Testing Instructions

**Testing the good path**
*Follow the instructions on this pull request and verify that the activation still works after the changes: https://github.com/Automattic/wp-calypso/pull/93922

**Testing the bad path (member of different agency)**
* Login as an agency user to A4A.
* Use the A4A live link below and go to the `/team/invite/accept?agency_id=${RANDOM_AGENCY_ID}&agency_name=Multidots&invite_id=67890&secret=abcdef`
* Make sure you replace the agency ID value above with a different ID that does not match the current user's agency.
* Confirm that the screen above is displayed. Make sure that it matches the design. 

**Testing the bad path (member of agency)**
* Login as an agency user to A4A.
* Use the A4A live link below and go to the `/team/invite/accept?agency_id=${YOUR_AGENCY_ID}&agency_name=Multidots&invite_id=67890&secret=abcdef`
* Make sure you replace the agency ID value above with the same agency ID of the current user.
* Confirm that the link redirects you to the Overview page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-08-27 14:24 UTC, jkguidaven commented on client/a8c-for-agencies/sections/team/controller.tsx
> +		agency_name: agencyName,
We need to pass the name of the inviting agency in the URL because we are unable to retrieve it from the UI with our current limited permissions.

We will need to update the magic link to include the agency's name as a parameter in the redirect URL.

2024-08-28 09:55 UTC, tiagonoronha requested changes
We need to adjust the logic here so that we first attempt to accept the invite by sending a POST request to `agency/<agency_id>/user-invites/<invite_id>`. If the user is already part of an agency, the request should return an error along with information about the existing and the target agency, which can then be used in the UI. 

So... this screen should be displayed after attempting to accept the invite, not before, as it currently works.

See D159704-code

2024-09-02 05:48 UTC, jkguidaven commented
> We need to adjust the logic here so that we first attempt to accept the invite by sending a POST request to `agency/<agency_id>/user-invites/<invite_id>`. If the user is already part of an agency, the request should return an error along with information about the existing and the target agency, which can then be used in the UI.
> 
> So... this screen should be displayed after attempting to accept the invite, not before, as it currently works.
> 
> See [D159704-code](https://href.li/?https://code.a8c.com/D159704)

@tiagonoronha I've made the necessary changes to follow the new endpoint spec. Can you have another look? 🙏

2024-09-04 06:56 UTC, yashwin approved these changes
Works as expected and the code changes look good to me! 🚢

2024-09-04 06:56 UTC, yashwin commented on client/a8c-for-agencies/sections/team/primary/team-accept-invite/no-multi-agency-message.tsx
> +						<>
Do we need the Fragment here?

2024-09-04 06:56 UTC, yashwin commented on client/a8c-for-agencies/sections/team/primary/team-accept-invite/no-multi-agency-message.tsx
> +						<>
Do we need the Fragment here?

2024-09-04 07:37 UTC, merged

2024-09-04 09:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16636442

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

2024-09-09 15:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16636442).