Last Used Login: implement the login option
Automattic/wp-calypso pull request #94009
Opened 2024-08-28 22:07 UTC by arcangelini

## Proposed Changes

* Look for `last_used_authentication_method` cookie
* Render the previously used method button on the left.
* Replace the original location of the button with an email option

## Why are these changes being made?

This is the final (hopefully) installment of the riveting Last Used Authentication Method saga. Up until this point we have structured the components to work better together and autonomously. Now it is time to put it all together to allow users the opportunity to use their last method.

## Testing Instructions

Test the login links and verify there is no regression.

2024-08-29 02:33 UTC, agrullon95 commented
Some issues I found:

1. The "Continue with Email" doesn't function when I click on it.
2. When I log in with Email, the email login button gets added under "Previously used" on the left side but remains on the right. The "Continue with Email" is missing in this scenario.

2024-08-29 02:51 UTC, agrullon95 commented on client/blocks/login/login-form.jsx
> +								Previously used
Let's translate `Previously used`

2024-08-29 03:07 UTC, agrullon95 commented on client/blocks/login/social.jsx
> +			service: 'magic',
Let's rename this `magic-login`. That should fix the "Continue with Email" button issue where it doesn't appear if you previously logged in with the magic login link option.

2024-08-29 03:16 UTC, agrullon95 commented on client/blocks/login/login-form.jsx
> +							reset={ this.resetLastUsedAuthenticationMethod }
Updating this prop should fix the "Continue with Email" button:

```suggestion
							resetLastUsedAuthenticationMethod={ this.resetLastUsedAuthenticationMethod }
```

2024-08-29 08:48 UTC, arcangelini commented
Thanks @agrullon95 

I pushed kind of late last night and had some oversights. 🤣

2024-08-29 09:56 UTC, heavyweight requested changes
I was logged in via github. Logged out and logged in with user/pass.
After logging out I got here..
<img width="1201" alt="Screenshot 2024-08-29 at 11 55 55" src="https://github.com/user-attachments/assets/b928ee81-f197-42f7-8b9d-50ca8f7b40ad">

2024-09-03 13:36 UTC, agrullon95 approved these changes
LGTM! Good job.

I wasn't able to test Apple and Github, but the rest of the login methods are working well.

2024-09-03 14:42 UTC, escapemanuele commented
I believe @heavyweight is going to be able to test Apple for sure

2024-09-04 11:34 UTC, heavyweight commented
Tested signup and login with apple and didn't find any issues

2024-09-05 15:30 UTC, escapemanuele approved these changes
It is now good to go, after all the things we need to do for the experiment.

Well done!

2024-09-06 09:11 UTC, merged

2024-09-06 11:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16654813

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @arcangelini, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Previously used`

Thank you in advance!

2024-09-09 15:29 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16654813).