Stats: adjust selected date colors
Automattic/wp-calypso pull request #94520
Opened 2024-09-13 03:25 UTC by kangzj

Related to #

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

<img width="663" alt="image" src="https://github.com/user-attachments/assets/dc8336c2-4a0e-4724-be5b-520b83e061ab">

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-09-13 03:28 UTC, kangzj commented on client/components/date-range/style.scss
> +						background-color: var(--color-neutral-20);
```suggestion
						background-color: var(--theme-highlight-color-0);
```

2024-09-13 03:28 UTC, kangzj commented on client/components/date-range/style.scss
> +		background-color: var(--color-neutral-20);
```suggestion
		background-color: var(--theme-highlight-color-0);
```

2024-09-13 03:28 UTC, kangzj commented on client/components/date-range/style.scss
> +		background-color: var(--color-neutral-20);
```suggestion
		background-color: var(--theme-highlight-color-0);
```

2024-09-15 23:03 UTC, kangzj commented on client/components/date-picker/style.scss
> +	background-color: var(--color-neutral-light);
use a different color than selected dates to tell them apart.

2024-09-15 23:56 UTC, annacmc requested changes
This looks awesome! However, It doesn't look like one of the colors is picking up the theme colors correctly. Here's a couple of screenshots from some of our not-blue themes:

| Sunrise  | Ectoplasm | Coffee |
| ------------- | ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/962c9487-d645-49b9-a106-c51ec7021c5e)  | ![image](https://github.com/user-attachments/assets/2f7c86fe-736b-4d28-aedd-fbeaffd78b7d)  | ![image](https://github.com/user-attachments/assets/3e569a82-1f2c-4ed8-8a4f-336cabb1a546)

2024-09-15 23:59 UTC, annacmc commented on client/components/date-range/style.scss
> +
I think the issue may be with how this variable is being defined

2024-09-16 01:52 UTC, kangzj commented
Thanks @annacmc good catch! If we get the variable in root then it will always pick up the default theme, so I move the definition in the class. And it could use another review now 😄

2024-09-16 03:53 UTC, annacmc approved these changes

2024-09-16 03:54 UTC, annacmc commented
Looks great now! 👍 

![image](https://github.com/user-attachments/assets/348137fa-813f-47ba-b2e8-289c229ea035)

2024-09-16 04:04 UTC, merged