Onboarding: Query all products for the with-plugin onboarding flow
Automattic/wp-calypso pull request #95312
Opened 2024-10-11 11:17 UTC by epeicher

Resolves https://github.com/Automattic/dotcom-forge/issues/9378

## Proposed Changes

* Check if the onboarding flow is `with-plugin` to query all products

## Why are these changes being made?

* An optimization change was done to query only domain products during the domain step as part of this PR https://github.com/Automattic/wp-calypso/pull/89716. But this step can be executed during the `with-plugins` flow that requires all products to be queried

## Testing Instructions

- Apply this patch
- Go to [WordPress.com/plugins](http://wordpress.com/plugins) (logged-out) and select a plugin (Sensei PRO)
Login/create an account
- Pick a domain
- You'll land in checkout (
- Check that the Sensei PRO subscription is in the checkout page
- Purchase the plan and the product
- Check the purchase is completed successfully

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-10-11 12:51 UTC, BogdanUngureanu approved these changes
LGTM, nice job!

The only issue (non-blocking for this PR) I could notice was that when selecting the monthly option I got a annual business subscription in checkout.

2024-10-11 12:58 UTC, WBerredo requested changes
I would go ahead with this solution some days ago 🥲

But after reading pdDR7T-1M7-p2 and understanding how each step should not care about other steps or the flow they are in (this case), I don't think this is the best solution here.

If we want to go with a quick solution just in order to unblock the users, I would just remove the type param and let it retrieve all products from the list. 

And using it as an interim solution while we provide a fix where the plugin step really retrieves all the data needed for it to work, similar to the `with-theme` flow. I think this is the path we should pursue now.

2024-10-11 13:26 UTC, epeicher commented
> I would go ahead with this solution some days ago 🥲

Well, that was identified yesterday 😉 

> But after reading pdDR7T-1M7-p2 and understanding how each step should not care about other steps or the flow they are in (this case), I don't think this is the best solution here.

I read it and thought the same, but in this scenario we are using the `flow`, not the `step`, in the same way that is being [used extensively](https://github.com/Automattic/wp-calypso/pull/95312/files#diff-dac1653ca8a4fe77505424b91353f493df971ad43841fce152c3572a13738a65R1379) in that piece of code
 
> If we want to go with a quick solution just in order to unblock the users, I would just remove the type param and let it retrieve all products from the list.
> 
> And using it as an interim solution while we provide a fix where the plugin step really retrieves all the data needed for it to work, similar to the `with-theme` flow. I think this is the path we should pursue now.

This solution refines the work done by the task https://github.com/Automattic/wp-calypso/pull/89716 but it does not remove it completely. It updates the code to the scenario where it breaks. I don't understand why you would like to remove it completely and undo the optimization suggested as part of https://github.com/Automattic/wp-calypso/pull/89716, do you foresee any scenarios that break?

2024-10-11 13:52 UTC, WBerredo commented
> Well, that was identified yesterday 😉

Maybe I didn't make myself clear. I meant to say that I would have gone ahead with this change if we had reached the same conclusion some days ago, but now, after seeing how the stepper SHOULD work, this doesn't sound ideal anymore.

> I read it and thought the same, but in this scenario, we are using the flow

During some moments in the video, they also mention checking the current flow to take decisions on a step.

> This solution refines the work done by the task https://github.com/Automattic/wp-calypso/pull/89716 but it does not remove it completely. It updates the code to the scenario where it breaks. I don't understand why you would like to remove it completely and undo the optimization suggested as part of https://github.com/Automattic/wp-calypso/pull/89716, do you foresee any scenarios that break?

Because I see both changes as interim solutions that must be removed in the near future (max 2 work days I would say?), and the completely removal of this property is much easier to undo later when we get a proper solution.

2024-10-14 13:42 UTC, epeicher commented
Closing this in favour of https://github.com/Automattic/wp-calypso/pull/95329. There is a further explanation of the issue and the solution here pdt2If-1Nz-p2

2024-10-14 13:42 UTC, closed without merging