Performance Profiler: Add preview box to timeline screenshots
Automattic/wp-calypso pull request #95515
Opened 2024-10-18 12:04 UTC by epeicher

Resolves https://github.com/Automattic/dotcom-forge/issues/9192

## Proposed Changes

* Displays a modal when clicking on a Screenshot of the timeline preview

|Logged-in | Logged-out|
|-------|------|
|![CleanShot 2024-10-18 at 14 06 10@2x](https://github.com/user-attachments/assets/91f8ebbe-0191-46be-a82b-bff4ba76058c)|    ![CleanShot 2024-10-18 at 14 06 30@2x](https://github.com/user-attachments/assets/4857f1b0-d8f9-4ace-871a-c56fee40e054)   |

## Why are these changes being made?

* For consistency with a similar behaviour in the tool. To improve the UX by allowing the user to preview the images in a bigger size.

## Testing Instructions

* Apply this changes and navigate to `/speed-test` tool with a valid URL
* Go to the timeline and click on an image
* Check a modal is displayed with the contents of the clicked image
* Repeat using the logged-in version (activate the flag `performance-profiler/logged-in`)
* Check a modal is displayed with the contents of the clicked image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-10-18 14:12 UTC, WBerredo requested changes
I can see some issues that we might want to dive in:

* We might want to add a background to the `X` button for cases where it mixes with the background. Something like a black background with some opacity.
* On the logged in version the modal is centralized on the screen but I think it should be centralized on the Performance Profiler section, so bringing the sidebar width into the calculation might help.
* The resolution is compromised we see it on the modal (worse on bigger screens), so if we don't receive a different source for the images, it might help to add some image treatment to amplify it without losing (much) readability.

![CleanShot 2024-10-18 at 11 07 15@2x](https://github.com/user-attachments/assets/85ae0dc2-da35-49e9-bac6-db9c2057ba93)

2024-10-18 14:32 UTC, epeicher commented
> I can see some issues that we might want to dive in:
> 
> * We might want to add a background to the `X` button for cases where it mixes with the background. Something like a black background with some opacity.
> * On the logged in version the modal is centralized on the screen but I think it should be centralized on the Performance Profiler section, so bringing the sidebar width into the calculation might help.
> * The resolution is compromised we see it on the modal (worse on bigger screens), so if we don't receive a different source for the images, it might help to add some image treatment to amplify it without losing (much) readability.
> 
> ![CleanShot 2024-10-18 at 11 07 15@2x](https://private-user-images.githubusercontent.com/5039531/377899818-85ae0dc2-da35-49e9-bac6-db9c2057ba93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjExMTQsIm5iZiI6MTcyOTI2MDgxNCwicGF0aCI6Ii81MDM5NTMxLzM3Nzg5OTgxOC04NWFlMGRjMi1kYTM1LTQ5ZTktYmFjNi1kYjljMjA1N2JhOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMTQxMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY5YjBkOTRkY2FkOTA3NzE4MzQwMzYzZDU4OTdlMjFmNmNjMDRiNTc0YzRlODc0NzAwYzQ0ZDgwNmE0ZDRmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0ul6mnTcjA1fbJAhY7iGgkN0Fwj3bRfelmMPX-ZPDLo)

Thanks for your comments @WBerredo, I would be interested in knowing if all comments are a blocker for this task or if any of them can be accomplished with a follow-up task.

This is my view:

> We might want to add a background to the X button for cases where it mixes with the background. Something like a black background with some opacity.

That's a good catch. This can be simple to add as part of this task. I will investigate options. I'm pinging @matt-west for any tips. 

> On the logged in version the modal is centralized on the screen but I think it should be centralized on the Performance Profiler section, so bringing the sidebar width into the calculation might help.

This is the same approach used for the screenshots displayed in the `Insights` section. They were added as part of this PR https://github.com/Automattic/wp-calypso/pull/94582 and updated as part of this other PR https://github.com/Automattic/wp-calypso/pull/94890. In my opinion, because this is a Modal, centering with regards to the right screen could look misaligned. I will also loop in @matt-west for another opinion.


> The resolution is compromised we see it on the modal (worse on bigger screens), so if we don't receive a different source for the images, it might help to add some image treatment to amplify it without losing (much) readability.

I am not sure if the extra CPU work required for this is worthy for a potentially minimally used feature here. But I would create a follow-up for further investigation/discussion. What do you think?

2024-10-18 14:37 UTC, WBerredo commented
You are right, sorry for not making clear what is a blocker or not.

> That's a good catch. This can be simple to add as part of this task. 

Agreed, I wouldn't merge without this change but it should be very easy to accomplish too.

> This is the same approach used for the screenshots displayed in the Insights section. They were added as part of this PR https://github.com/Automattic/wp-calypso/pull/94582 and updated as part of this other PR https://github.com/Automattic/wp-calypso/pull/94890. In my opinion, because this is a Modal, centering with regards to the right screen could look misaligned. I will also loop in @matt-west for another opinion.

Yeah, I'm not very sure about this topic either, and Matt is definitely a better person to define this :)

> I am not sure if the extra CPU work required for this is worthy for a potentially minimally used feature here. But I would create a follow-up for further investigation/discussion. What do you think?

I agree it can be a follow-up task but I would also defer to @matt-west  the decision if its worth to pursue or not.

---

All in all, I would just use the first one as a blocker.

2024-10-18 15:53 UTC, epeicher commented
@WBerredo I have tried different solutions, like just increasing the contrast in the [`filter` property](https://github.com/Automattic/wp-calypso/pull/95515/files#diff-d87fa49533e04dada2b332cab4c80b3f45df61599c9d5579007449edff490b89R61), but I have found scenarios where it does not look great, for example, when there is a cart icon behind. Eventually, I have implemented a solution that adds a two different _icon_ backgrounds depending on the _image_ background.

<details>
  <summary><i>Please find an explanation from claude here</i></summary>
Here's how this CSS-only solution works:

We create two pseudo-elements (::before and ::after) that will serve as our adaptive background.
The ::before element has a white background with mix-blend-mode: difference. This inverts dark backgrounds but leaves light backgrounds mostly unchanged.
The ::after element has a black background with mix-blend-mode: screen. This lightens dark backgrounds but leaves light backgrounds mostly unchanged.
The combination of these two effects creates a background that adapts to be visible on both light and dark underlying images or colors.
The SVG icon itself uses mix-blend-mode: difference to ensure it remains visible against the adaptive background.
</details>

These are the results in different white and black images with carts or other icons:

|Example 1 | Example 2|Example 3 | Example 4|
|-------|------|------|------|
|   ![CleanShot 2024-10-18 at 17 41 27@2x](https://github.com/user-attachments/assets/46cd71f4-c77f-454c-9ee4-70591eae6580)|     ![CleanShot 2024-10-18 at 17 41 56@2x](https://github.com/user-attachments/assets/15f1db1e-08d1-42d1-9d9b-7dbfb24e8445)      |      ![CleanShot 2024-10-18 at 17 41 36@2x](https://github.com/user-attachments/assets/5e689e70-0a2e-49ed-b1cd-41d2afd744aa)       |    ![CleanShot 2024-10-18 at 17 41 49@2x](https://github.com/user-attachments/assets/4d3df136-53b4-4845-a72e-f4148db6b39c)             |

2024-10-18 17:35 UTC, WBerredo approved these changes
> Eventually, I have implemented a solution that adds a two different icon backgrounds depending on the image background.

🤯 This is even better than I anticipated. TIL and IMHO it deserves a P2. 

LGTM! 🚢

PS: I added a cursor pointer to the thumbnail as I have forgot to mention the first time.

2024-10-21 09:01 UTC, matt-west commented
Sorry for the slow response.

> In my opinion, because this is a Modal, centering with regards to the right screen could look misaligned

Agreed, the modal should be centred based on the full-width of the window.

> The resolution is compromised we see it on the modal (worse on bigger screens), so if we don't receive a different source for the images, it might help to add some image treatment to amplify it without losing (much) readability.

If we can’t get better resolution images from Google, I don’t think we should try to upscale them on our end. PageSpeed Insights doesn’t allow you to expand the images in their timeline. While this would be a nice feature to have, I don’t think we should add it if the screenshots will always look this pixelated. It doesn’t add any value beyond how they are currently displayed in the timeline.

> Eventually, I have implemented a solution that adds a two different icon backgrounds depending on the image background.

@epeicher This is a really cool solution! Nice work. Can you please use the `closeSmall` icon instead so that there’s some whitespace around the `X`.

2024-10-21 10:47 UTC, epeicher commented
Hi @matt-west , I have been having a look at the `Modal` component, [docs here](https://wordpress.github.io/gutenberg/?path=/docs/components-modal--docs), and I have not found a way to override the `close` icon. Also, looking at the [source code](https://github.com/WordPress/gutenberg/blob/55a701641146dc4c5c2cb2162ce581e59f176716/packages/components/src/modal/index.tsx#L349), it seems the icon used is `close` from `@wordpress/icons` and it does not allow to configure it.

Alternatively, if I reduce the `width` of the icon with a single CSS property, we've got the extra padding. 

Are you happy with this approach?

|Before | After|
|-------|------|
|   ![CleanShot 2024-10-21 at 12 46 25@2x](https://github.com/user-attachments/assets/7c0b6404-0aee-401e-8c1f-1f90a6ca94f1)   |![CleanShot 2024-10-21 at 12 38 26@2x](https://github.com/user-attachments/assets/3c84b140-ea66-4e2d-b0c7-822fee639c55)|

2024-10-21 12:04 UTC, matt-west commented
Yep, that works. Thanks @epeicher

2024-10-21 13:05 UTC, merged

2024-10-21 14:19 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16935546

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @epeicher for including a screenshot in the description! This is really helpful for our translators.

2024-10-27 16:32 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16935546).