Help Center: calypso links open in same tab
Automattic/wp-calypso pull request #95899
Opened 2024-10-30 16:17 UTC by arcangelini

Fixes #93429

## Proposed Changes

Extend Help Center article filter and action hooks to allow opening the Help Center to a specific article.

## Why are these changes being made?

Currently when the users clicks a link to Calypso from within the Help Center article it is opened in another tab. The better option would be to open the link in the same tab and persist the article. That is what we are doing here.

Since there was not an easy way to filter out only the calypso admin pages I opted to not include the site slug in the URL. This means they will need to select the site if its a URL like `https://wordpress.com/media/`, but it also means that it won't break URLs like `https://wordpress.com/learn`.

## Testing Instructions

1. Open the Help Center and click the article Getting Started
2. Scroll down to see the link for [WordPress.com plan](https://wordpress.com/plans/) and click that.
3. You should see it open in the same tab and the Help Center should open again to the article you were on.
4. Try a few other articles to see if other links work as well.
5. Regression test.

2024-10-31 12:57 UTC, renancarvalho reviewed
I tested using live link and got redirected to `https://wordpress.com/plans//?help-center=http%3A%2F%2Fen.support.wordpress.com%2Fgetting-started-with-wordpress-com%2F` with a blank page without any errors on the console 🤔 

<img width="2048" alt="image" src="https://github.com/user-attachments/assets/a9986221-bfd8-4c8f-b0d6-ee76843663bb">

2024-11-04 16:28 UTC, escapemanuele requested changes
Tested and I get the same as Renan!

2024-11-13 08:50 UTC, heavyweight commented
I'm seeing this on click..

https://github.com/user-attachments/assets/fed6c1d3-af04-435d-b2e4-0b1bc36d2109

2024-11-13 12:15 UTC, arcangelini commented
@heavyweight That is correct. You still need to select the site you would like to use. The reason being is that it would likely be too complicated to determine if the link that the user just clicked requires a site slug. There are other link in the page that do not require site slugs.

2024-12-13 12:27 UTC, escapemanuele commented on packages/help-center/src/hooks/use-action-hooks.ts
> +				return isThisASupportArticleLink( helpCenterParam );
Just checking this, and I believe we can't remove the subscribe-block action hook, since it is used in launchpad

2024-12-13 15:28 UTC, escapemanuele commented
Hey @kriskarkoski, would you like to give this a spin when you have time?

2024-12-17 19:49 UTC, kriskarkoski commented
I am not sure if this is just not testing properly due to calyspo.live, but testing from [https://container-focused-napier.calypso.live/sites](https://container-focused-napier.calypso.live/sites) I searched for Getting Started as it wasn't showing in the default suggestions. I scrolled down and clicked the linked text [WordPress.com plan](https://wordpress.com/plans/) and it opened [https://wordpress.com/plans/?help-center=http%3A%2F%2Fen.support.wordpress.com%2Fgetting-started-with-wordpress-com%2F.](https://wordpress.com/plans/?help-center=http%3A%2F%2Fen.support.wordpress.com%2Fgetting-started-with-wordpress-com%2F.) I assume that is because it's not on production yet so I tried to go to [container-focused-napier.calypso.live](https://container-focused-napier.calypso.live/sites)[/plans/?help-center=http%3A%2F%2Fen.support.wordpress.com%2Fgetting-started-with-wordpress-com%2F](https://wordpress.com/plans/?help-center=http%3A%2F%2Fen.support.wordpress.com%2Fgetting-started-with-wordpress-com%2F.) but that redirects to https://wordpress.com/pricing/.

2025-06-04 16:40 UTC, closed without merging