A4A: Hide Dataview actions on the Referrals table.
Automattic/wp-calypso pull request #96456
Opened 2024-11-15 15:41 UTC by jkguidaven

This PR hides the Dataview actions from the Referrals page's table since they are not being utilized at this time.
<img width="701" alt="Screenshot 2024-11-15 at 11 37 08 PM" src="https://github.com/user-attachments/assets/061df6fa-6e29-4ee3-bd15-bec942bb3829">
<img width="618" alt="Screenshot 2024-11-15 at 11 37 31 PM" src="https://github.com/user-attachments/assets/819f5e4f-faa0-4cdb-adf9-d3a7430c22cd">

## Proposed Changes

* Implement a CSS rule to conceal the data view actions, since the DataView interface lacks this option.

## Why are these changes being made?

* This causes confusion among users, so we should eliminate it if it’s not working.

## Testing Instructions

* Use the A4A live link and go to the `/referrals/dashboard` page.
* Confirm that the Gear icons are no longer visible in the page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-11-17 18:40 UTC, cleacos commented
I'm okay with hiding the icon, but this kind of style hack was removed/avoided with the DataViews update project to match the core component behavior. So the "rule" is that if core doesn't have that implementation (hide the wheel), we "cannot" do it via style-hack. The procedure should be ask/implemented in the core.

@jeffgolenski and @madebynoam, what should we do here?

2024-11-17 18:41 UTC, cleacos requested changes
This is a preventing rejection until we have more feedback

2024-11-18 19:43 UTC, oandregal commented
> I'm okay with hiding the icon, but this kind of style hack was removed/avoided with the DataViews update project to match the core component behavior. So the "rule" is that if core doesn't have that implementation (hide the wheel), we "cannot" do it via style-hack. The procedure should be ask/implemented in the core.

I recommend against hacking the library. A few weeks ago, it tooks us weeks updating the library because of them, so we should find better ways to deal with this.

There're two reasons the view config control is still visible when the consumer disabled everything:

- Moving fields around. Disabling this needs a proper API in core. There was some discussion around this topic [here](https://github.com/WordPress/gutenberg/pull/64646#issuecomment-2299055945).
- Pagination: figure out how users can change items per page without the view config.

<img width="397" alt="Screenshot 2024-11-18 at 20 35 54" src="https://github.com/user-attachments/assets/38cc0d65-a516-48d5-a0bb-06cb8b013308">

I'd love to see us creating issues in core to discuss your needs and then implement them. I'm happy to help making people more comfortable to prepare PRs to core.

2024-11-26 10:31 UTC, jkguidaven commented
@cleacos @oandregal thank you for pointing that out. I apologize for the delayed response.

I agree that this issue needs to be brought up in core if we are to support this use case. But first, I'll reevaluate whether our use case is genuinely valid or if this is something the design should adjust and reconsider. If this is indeed a needed feature, I will open an issue in core to initiate a discussion on it.

In the meantime, I'll close these PRs and revert the maintenance ticket to a blocked status.

2024-11-26 10:31 UTC, closed without merging