Add the authorization Step for the Application Passwords
Automattic/wp-calypso pull request #96891
Opened 2024-11-28 16:50 UTC by valterlorran

Related to #

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-12-04 12:41 UTC, andres-blanco requested changes
Here's a bunch of small design differences that doesn't match the figma file:
* Spacing between the title and the paragraph below
* The site URL should be bold
* Spacing between paragraph and CTA button 
* The weight of the `Share credentials instead` link is different
* Spacing between `Share credentials instead` link and `Here's what else you're getting` title is different
* Spacing between `Here's what else you're getting` title and the description box is different
* The description box items have icons in the figma
* Font size of the description box items is different

Also, the `Need help? Let us guide you` link in the top right is missing.
<img width="237" alt="image" src="https://github.com/user-attachments/assets/55a79337-e954-4320-ad47-8ba02ca55b2a">

Please tackle the easy fixes and leave the rest for a subsequent PR.

2024-12-04 12:43 UTC, andres-blanco commented
@valterlorran the CTA en the Figma reads `Authorize access`, in the PR is `Authorize`

2024-12-04 12:48 UTC, andres-blanco commented
https://github.com/user-attachments/assets/9ab761fc-7592-41fb-9e7b-f42f7122bef1

When I click authorize I get redirected to the first step of the flow. Based on the `undefined` that appears on the URL this might be related to the `site_url` vs `from` parameter

2024-12-04 13:11 UTC, valterlorran commented
@andres-blanco 

>  Spacing between the title and the paragraph below

 We should not override these values to not create inconsistencies with other steps. We should use the default behavior of the component.
> The site URL should be bold

Fixed
> Spacing between paragraph and CTA button

 I’m assuming this means the space between the `We're ready to migrate…` subtitle and the `Authorize access` button: Again the space added between is default of the header and the step container, reducing that would be different from other steps.
> The weight of the Share credentials instead link is different

I’m using the default link that we have been using in other steps. I think if we decide to tackle that, we should do a refactor.
> Spacing between Share credentials instead link and Here's what else you're getting title is different

 Fixed
> Spacing between Here's what else you're getting title and the description box is different

Fixed
> The description box items have icons in the figma

 Isn’t that showing up for you? Can you share a screen shot?
> Font size of the description box items is different

I used the $font-body-small instead of hardcoding the site and to have consistence.

2024-12-04 16:31 UTC, andres-blanco commented
> Isn’t that showing up for you? Can you share a screen shot?
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/158eca52-a275-42ca-997d-309a45adbc78">

Figma: F8foKv974Gc5dTHSh0i0Wo-fi-648_7452

2024-12-04 16:48 UTC, andres-blanco requested changes
The code overall looks good and the happy path seems to be working correctly. I found a couple of blockers.

* When I get redirected to the wp-admin screen to authorize there's no Application Name pre-filled (we should user the `app_name` query param specified here https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/)
<img width="738" alt="image" src="https://github.com/user-attachments/assets/04fe06c3-ce4b-4476-9294-adf1a43c9aa1">

* The let us guide you in the top right is still missing

2024-12-04 16:48 UTC, andres-blanco commented on client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-application-password-authorization/components/authorization.tsx
> +						translate( 'Uninterrupted service throughout the entire migration experience.' ),
where this strings added to the string freeze PR we where using for having translations ready earliear?

2024-12-04 17:50 UTC, valterlorran commented
> When I get redirected to the wp-admin screen to authorize there's no Application Name pre-filled (we should user the app_name query param specified here

This should be working, the thing is that on the testing instructions I didn't add the App ID and App Name, but this should come from the endpoint. In order for that to work just add the app_id and the app_name params to your authorizationUrl:

Please see: fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Szvtengvba%2Snhgbzngrq%2Qzvtengvba%2Qgbbyf.cuc%3Se%3Q9r16q365%231171%2Q1178-og

2024-12-04 17:56 UTC, andres-blanco approved these changes
Based on [this comment ](https://github.com/Automattic/wp-calypso/pull/96891#issuecomment-2518140902) I think this is in a good state for merging.

2024-12-04 19:07 UTC, merged

2024-12-04 21:31 UTC, a8ci18n commented
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17046536

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @valterlorran for including a screenshot in the description! This is really helpful for our translators.

2024-12-08 18:30 UTC, a8ci18n commented
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17046536).