Help Center: Refactoring shouldUseHelpCenterExperience
Automattic/wp-calypso pull request #97352
Opened 2024-12-11 17:52 UTC by escapemanuele

Related to #

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

2024-12-18 13:41 UTC, AllTerrainDeveloper requested changes
I've seen a couple of things that might be better to get them addressed for completeness and cleanliness :)

2024-12-18 13:41 UTC, AllTerrainDeveloper commented on packages/odie-client/src/components/message/index.tsx
> +			<strong className="message-header-name"></strong>
Is this really needed? If so, we probably don't need the above fragment

2024-12-18 13:41 UTC, AllTerrainDeveloper commented on packages/odie-client/src/components/message/thinking-placeholder.tsx
> +			<>
We don't need that fragment

2024-12-18 13:41 UTC, AllTerrainDeveloper commented on packages/odie-client/src/components/message/user-message.tsx
> +		return isLastMessage && <GetSupport onClickAdditionalEvent={ handleContactSupportClick } />;
I think is preferable to return NULL. Eg.
```suggestion
		return isLastMessage ? <GetSupport onClickAdditionalEvent={ handleContactSupportClick } /> : null;
```

2024-12-18 13:41 UTC, AllTerrainDeveloper commented on packages/odie-client/src/components/message/index.tsx
> +			{ message.role === 'business' && (
Same here, I don't htink we need that Fragment?

2024-12-18 13:41 UTC, AllTerrainDeveloper commented on packages/odie-client/src/components/message/messages-container.tsx
> +				{ ! chatMessagesLoaded ? (
I know it's not part of this set of changes, but probably changing the order would ease the reading, eg

chatMessagesLoaded ? showChat: showSpinner

2024-12-18 14:06 UTC, escapemanuele commented
Thanks @AllTerrainDeveloper, I pushed a refactor ✌️

2024-12-19 13:35 UTC, AllTerrainDeveloper commented
I've tried to test it but I can't get the new experience

2024-12-19 14:14 UTC, AllTerrainDeveloper approved these changes
This looks good to me now!

2025-01-13 18:02 UTC, alshakero reviewed
Did a thorough code review and everything looks great. I will test tomorrow.

2025-01-13 18:02 UTC, alshakero commented on packages/help-center/src/components/help-center.tsx
> +		<HelpCenterRequiredContextProvider value={ { ...props } }>
```suggestion
		<HelpCenterRequiredContextProvider value={ props }>
```

2025-01-14 09:15 UTC, escapemanuele commented
Thank you @alshakero, I added your suggestion!
Ping me when you're able to give it a spin, so we can move forward.

2025-01-14 09:57 UTC, AllTerrainDeveloper approved these changes
I have reviewed and tested, I couldn't find any error and everything looks good!

2025-01-14 10:20 UTC, agrullon95 commented on packages/help-center/src/components/help-center-feedback-form.tsx
> +				<p>{ __( 'Was this helpful?' ) }</p>
```suggestion
				<p>{ __( 'Was this helpful?', __i18n_text_domain__ ) }</p>
```

2025-01-14 10:22 UTC, escapemanuele commented on packages/help-center/src/components/help-center-feedback-form.tsx
> +				<p>{ __( 'Was this helpful?' ) }</p>
Great catch!

2025-01-14 10:33 UTC, agrullon95 approved these changes
LGTM
Tests:

- [x] Start a chat with Odie
- [ ] Start a chat with an Happiness Engineer in staging
- [ ] Use a free user to check that you are sent to forums
- [x] Check History (you need to have > 1 conversations)
- [x] Sanity check for articles

2025-01-14 10:39 UTC, merged